github/advisory-database

advisories/github-reviewed/2022/01/GHSA-566m-qj78-rww5/GHSA-566m-qj78-rww5.json
=> Advisory improvement for GHSA-566m-qj78-rww5

advisories/github-reviewed/2022/02/GHSA-j9cf-pr2x-5273/GHSA-j9cf-pr2x-5273.json
=> Advisory improvement for GHSA-j9cf-pr2x-5273

advisories/github-reviewed/2021/12/GHSA-7q9f-x6rm-qmxr/GHSA-7q9f-x6rm-qmxr.json
**Updates**
- Description
- Summary
=> Advisory improvement for GHSA-7q9f-x6rm-qmxr

advisories/github-reviewed/2022/02/GHSA-332q-7ff2-57h2/GHSA-332q-7ff2-57h2.json
**Updates**
- Description
- Summary
=> Advisory improvement for GHSA-332q-7ff2-57h2

advisories/github-reviewed/2020/08/GHSA-w542-cpp9-r3g7/GHSA-w542-cpp9-r3g7.json
=> Advisory improvement for GHSA-w542-cpp9-r3g7

advisories/github-reviewed/2022/01/GHSA-r8j4-96mx-rjcc/GHSA-r8j4-96mx-rjcc.json
**Updates**
- Description
- Summary
=> Advisory improvement for GHSA-r8j4-96mx-rjcc

advisories/github-reviewed/2022/01/GHSA-x8rq-rc7x-5fg5/GHSA-x8rq-rc7x-5fg5.json
**Updates**
- Description
- Summary
=> Advisory improvement for GHSA-x8rq-rc7x-5fg5

advisories/github-reviewed/2017/10/GHSA-5726-g6r9-5f22/GHSA-5726-g6r9-5f22.json
**Updates**
- Description
- References
=> Advisory improvement for GHSA-5726-g6r9-5f22

advisories/unreviewed/2022/02/GHSA-jf5r-8hm2-f872/GHSA-jf5r-8hm2-f872.json
**Updates**
- Severity
- Summary
=> Advisory improvement for GHSA-jf5r-8hm2-f872

advisories/unreviewed/2022/02/GHSA-jf5r-8hm2-f872/GHSA-jf5r-8hm2-f872.json
**Updates**
* Severity
* Affected
=> Advisory improvement for  GHSA-jf5r-8hm2-f872

advisories/github-reviewed/2018/07/GHSA-mq6c-fh97-4gwv/GHSA-mq6c-fh97-4gwv.json
**Updates**
- Description
- Summary
Improves the title mainly, so it makes a bit more sense.
=> Contribution to "Fastify denial-of-service vulnerability with large JSON payloads in fastify"

advisories/github-reviewed/2022/02/GHSA-m6j2-v3gq-45r5/GHSA-m6j2-v3gq-45r5.json
=> Contribution to "Cross-site Scripting in aurelia-framework"

advisories/github-reviewed/2021/09/GHSA-grj5-8x6q-hc9q/GHSA-grj5-8x6q-hc9q.json
=> Contribution to "Path traversal in Grafana Loki"

advisories/unreviewed/2021/12/GHSA-mh9j-v6mq-pfch/GHSA-mh9j-v6mq-pfch.json
=> Contribution to "matyhtf framework v3.0.5 is affected by a path manipulati..."

advisories/github-reviewed/2018/09/GHSA-6g87-ff9q-v847/GHSA-6g87-ff9q-v847.json
=> Contribution to "High severity vulnerability that affects websockets"

advisories/github-reviewed/2017/10/GHSA-hgmw-x865-hf9x/GHSA-hgmw-x865-hf9x.json
=> Fix package name case sensitivity for GHSA-hgmw-x865-hf9x

advisories/github-reviewed/2017/10/GHSA-r23g-3qw4-gfh2/GHSA-r23g-3qw4-gfh2.json
=> Fix package name case sensitivity for GHSA-r23g-3qw4-gfh2

advisories/github-reviewed/2020/09/GHSA-8c8c-4vfj-rrpc/GHSA-8c8c-4vfj-rrpc.json
**Updates**
- Description
- References
=> Contribution to "Reflected Cross-Site Scripting in redis-commander"

advisories/github-reviewed/2021/09/GHSA-whgm-jr23-g3j9/GHSA-whgm-jr23-g3j9.json
**Updates**
- Add patched version
=> Contribution to "Uncontrolled Resource Consumption in ansi-html"

advisories/github-reviewed/2019/06/GHSA-wxhq-pm8v-cw75/GHSA-wxhq-pm8v-cw75.json
=> Contribution to "Regular Expression Denial of Service in clean-css"

advisories/github-reviewed/2018/10/GHSA-rrpm-pj7p-7j9q/GHSA-rrpm-pj7p-7j9q.json
=> Contribution to "High severity vulnerability that affects org.springframework.security.oauth:spring-security-oauth2"

advisories/github-reviewed/2018/07/GHSA-8g7p-74h8-hg48/GHSA-8g7p-74h8-hg48.json
**Updates**
- Description
- References
=> Contribution to "Denial of Service in https-proxy-agent"

advisories/github-reviewed/2021/06/GHSA-hr32-mgpm-qf2f/GHSA-hr32-mgpm-qf2f.json
=> Contribution to "Generation of Error Message Containing Sensitive Information in RESTEasy client"

advisories/unreviewed/2022/03/GHSA-ph3v-2hq5-5qfq/GHSA-ph3v-2hq5-5qfq.json
**Updates**
- Severity
- Summary
=> Contribution to "** UNSUPPORTED WHEN ASSIGNED ** In the..."

advisories/github-reviewed/2022/03/GHSA-w749-p3v6-hccq/GHSA-w749-p3v6-hccq.json
=> Contribution to "Possible code injection vulnerability in Rails / Active Storage"

advisories/github-reviewed/2022/01/GHSA-29mw-wpgm-hmr9/GHSA-29mw-wpgm-hmr9.json
=> Contribution to "Regular Expression Denial of Service (ReDoS) in lodash"

advisories/github-reviewed/2021/05/GHSA-35jh-r3h4-6jhm/GHSA-35jh-r3h4-6jhm.json
=> Contribution to "Command Injection in lodash"

advisories/github-reviewed/2020/07/GHSA-p6mc-m468-83gw/GHSA-p6mc-m468-83gw.json
**Updates**
- Description
- References
=> Contribution to "Prototype Pollution in lodash"

advisories/github-reviewed/2021/12/GHSA-c6c4-jmqx-3r33/GHSA-c6c4-jmqx-3r33.json
=> Contribution to "Open Redirect in xdLocalStorage"

advisories/github-reviewed/2021/12/GHSA-76qm-4f93-fg6f/GHSA-76qm-4f93-fg6f.json
=> Contribution to "Improper Input Validation in xdLocalStorage"

advisories/github-reviewed/2022/02/GHSA-jf5r-8hm2-f872/GHSA-jf5r-8hm2-f872.json
**Updates**
- CWEs
- Description
- Summary
=> Contribution to "Authorization Bypass Through User-Controlled Key in url-parse"

advisories/github-reviewed/2021/12/GHSA-jfh8-c2jp-5v3q/GHSA-jfh8-c2jp-5v3q.json
**Updates**
- CVSS
- Description
- References
- Severity
=> Contribution to "Remote code injection in Log4j"

advisories/github-reviewed/2021/05/GHSA-vj3f-3286-r4pf/GHSA-vj3f-3286-r4pf.json
=> Contribution to "Path Traversal in Docker"

advisories/github-reviewed/2020/03/GHSA-7q25-qrjw-6fg2/GHSA-7q25-qrjw-6fg2.json
**Updates**
- Description
- Severity
=> Contribution to "Malicious package may avoid detection in python auditing"

advisories/github-reviewed/2022/01/GHSA-5rqg-jm4f-cqx7/GHSA-5rqg-jm4f-cqx7.json
=> Contribution to "Infinite loop causing Denial of Service in colors"

advisories/github-reviewed/2022/01/GHSA-8vj2-vxx3-667w/GHSA-8vj2-vxx3-667w.json
=> Contribution to "Arbitrary expression injection in Pillow"

advisories/github-reviewed/2017/10/GHSA-6mq2-37j5-w6r6/GHSA-6mq2-37j5-w6r6.json
=> Contribution to "Moderate severity vulnerability that affects webrick"

advisories/github-reviewed/2021/06/GHSA-mg2g-8pwj-r2j2/GHSA-mg2g-8pwj-r2j2.json
=> Contribution to "Authentication bypass in SilverStripe GraphQL"

advisories/github-reviewed/2022/03/GHSA-3gx9-37ww-9qw6/GHSA-3gx9-37ww-9qw6.json
=> Contribution to "Code injection in Spring Cloud Gateway"

advisories/github-reviewed/2021/09/GHSA-8v63-cqqc-6r2c/GHSA-8v63-cqqc-6r2c.json
=> Contribution to "Prototype Pollution in object-path"

advisories/github-reviewed/2021/11/GHSA-qg54-694p-wgpp/GHSA-qg54-694p-wgpp.json
**Updates**
- Description
- References
=> Contribution to "Regular expression denial of service vulnerability (ReDoS) in date"

advisories/github-reviewed/2022/01/GHSA-qrpm-p2h7-hrv2/GHSA-qrpm-p2h7-hrv2.json
=> Contribution to "Exposure of Sensitive Information to an Unauthorized Actor in nanoid"

advisories/github-reviewed/2021/12/GHSA-mh9j-v6mq-pfch/GHSA-mh9j-v6mq-pfch.json
=> Contribution to "Path manipulation in matyhtf/framework"

advisories/unreviewed/2022/02/GHSA-gwmc-6795-qghj/GHSA-gwmc-6795-qghj.json
**Updates**
- CWEs
- Severity
- Summary
=> Contribution to "HashiCorp Nomad and Nomad Enterprise 0.3.0 through 1.0.17..."

advisories/github-reviewed/2020/09/GHSA-754h-5r27-7x3r/GHSA-754h-5r27-7x3r.json
**Updates**
- Description
- References
=> Contribution to "RCE in Symfony"

advisories/github-reviewed/2021/05/GHSA-4943-9vgg-gr5r/GHSA-4943-9vgg-gr5r.json
**Updates**
- CVSS
- CWEs
- Severity
=> Contribution to "Cross-site Scripting in quill"

advisories/github-reviewed/2020/04/GHSA-fv3h-8x5j-pvgq/GHSA-fv3h-8x5j-pvgq.json
=> Contribution to "XSS in python-markdown2"

advisories/github-reviewed/2022/02/GHSA-4cpg-3vgw-4877/GHSA-4cpg-3vgw-4877.json
**Updates**
- Description
- References
=> Contribution to "Prototype pollution in Plist"

advisories/github-reviewed/2022/03/GHSA-xvch-5gv4-984h/GHSA-xvch-5gv4-984h.json
=> Contribution to "Prototype Pollution in minimist"

advisories/github-reviewed/2022/03/GHSA-57j2-w4cx-62h2/GHSA-57j2-w4cx-62h2.json
=> Contribution to "Deeply nested json in jackson-databind"

advisories/unreviewed/2022/03/GHSA-4r65-35qq-ch8j/GHSA-4r65-35qq-ch8j.json
=> Contribution to "A flaw was found in Ansible Engine's ansible-connection..."

advisories/github-reviewed/2021/09/GHSA-93q8-gq69-wqmw/GHSA-93q8-gq69-wqmw.json
=> Contribution to " Inefficient Regular Expression Complexity in chalk/ansi-regex"

advisories/unreviewed/2021/12/GHSA-qrvj-274h-hfcg/GHSA-qrvj-274h-hfcg.json
=> Contribution to "ThinkPHP v6.0.8 was discovered to contain a..."

advisories/github-reviewed/2018/12/GHSA-894g-6j7q-2hx6/GHSA-894g-6j7q-2hx6.json
=> Contribution to "High severity vulnerability that affects flask-admin"

advisories/github-reviewed/2021/12/GHSA-668q-qrv7-99fm/GHSA-668q-qrv7-99fm.json
=> Contribution to "Deserialization of Untrusted Data in logback"

advisories/github-reviewed/2022/01/GHSA-2vj5-px25-gjrp/GHSA-2vj5-px25-gjrp.json
=> Contribution to "pytorch-lightning is vulnerable to Deserialization of Untrusted Data"

advisories/github-reviewed/2020/06/GHSA-xxgp-pcfc-3vgc/GHSA-xxgp-pcfc-3vgc.json
=> Contribution to "Privilege Escalation in Hibernate Validator"

advisories/github-reviewed/2022/03/GHSA-36p3-wjmg-h94x/GHSA-36p3-wjmg-h94x.json
=> Contribution to "Remote Code Execution in Spring Framework"

advisories/github-reviewed/2020/09/GHSA-8px5-63x9-5c7p/GHSA-8px5-63x9-5c7p.json
**Updates**
- Description
- References
=> Contribution to "Command Injection in pullit"

advisories/github-reviewed/2022/03/GHSA-7p99-3798-f85c/GHSA-7p99-3798-f85c.json
**Updates**
- Description
- References 
Added reference to patch commit that fixes issue
=> Contribution to "URL Redirection to Untrusted Site ('Open Redirect') in express-openid-connect"

README.md
Add a little text to explain what ecosystems we support and what they are generally.
=> Add ecosystem explainer

advisories/github-reviewed/2021/12/GHSA-p6xc-xr62-6r2g/GHSA-p6xc-xr62-6r2g.json
=> Contribution to "Improper Input Validation and Uncontrolled Recursion in Apache Log4j2"

advisories/unreviewed/2022/02/GHSA-6jm6-cmcp-fqjq/GHSA-6jm6-cmcp-fqjq.json
**Updates**
- Description
- Summary
=> Contribution to "HashiCorp Nomad and Nomad Enterprise before 1.0.17, 1.1.x..."

advisories/github-reviewed/2020/03/GHSA-gww7-p5w4-wrfv/GHSA-gww7-p5w4-wrfv.json
=> [GHSA-gww7-p5w4-wrfv] Deserialization of Untrusted Data in jackson-databind

advisories/github-reviewed/2020/03/GHSA-4w82-r329-3q67/GHSA-4w82-r329-3q67.json
**Updates**
- Description
- References
=> [GHSA-4w82-r329-3q67] Deserialization of Untrusted Data in jackson-databind

advisories/github-reviewed/2021/12/GHSA-qjw2-hr98-qgfh/GHSA-qjw2-hr98-qgfh.json
**Updates**
- Description
- References
- Severity
=> [GHSA-qjw2-hr98-qgfh] Unsafe Deserialization in jackson-databind

advisories/github-reviewed/2022/02/GHSA-q62h-jw38-24vh/GHSA-q62h-jw38-24vh.json
=> [GHSA-q62h-jw38-24vh] Uncaught Exception in zip4j

advisories/github-reviewed/2022/03/GHSA-636j-7x7r-gvw2/GHSA-636j-7x7r-gvw2.json
=> [GHSA-636j-7x7r-gvw2] Old sessions not blocked by login enable function in Snipe-IT

advisories/github-reviewed/2022/04/GHSA-fwr7-v2mv-hh25/GHSA-fwr7-v2mv-hh25.json
Successor of #199 and possibly #200.
=> [GHSA-fwr7-v2mv-hh25] Prototype Pollution in async #199

advisories/github-reviewed/2022/04/GHSA-fwr7-v2mv-hh25/GHSA-fwr7-v2mv-hh25.json
**Updates**
- Description
- References
=> [GHSA-fwr7-v2mv-hh25] Prototype Pollution in async

advisories/github-reviewed/2022/04/GHSA-3vjf-82ff-p4r3/GHSA-3vjf-82ff-p4r3.json
=> [GHSA-3vjf-82ff-p4r3] Incorrect protocol extraction via \r, \n and \t characters

advisories/github-reviewed/2022/04/GHSA-g5rr-p69h-7v3g/GHSA-g5rr-p69h-7v3g.json
**Updates**
- Description
- References
=> [GHSA-g5rr-p69h-7v3g] Insufficient type validation in pocketmine/pocketmine-mp

advisories/github-reviewed/2020/09/GHSA-5vj8-3v2h-h38v/GHSA-5vj8-3v2h-h38v.json
=> [GHSA-5vj8-3v2h-h38v] Remote Code Execution in next

advisories/github-reviewed/2021/08/GHSA-vxf5-wxwp-m7g9/GHSA-vxf5-wxwp-m7g9.json
=> [GHSA-vxf5-wxwp-m7g9] Open Redirect in Next.js

advisories/github-reviewed/2022/04/GHSA-xm99-6pv5-q363/GHSA-xm99-6pv5-q363.json
=> [GHSA-xm99-6pv5-q363] OS Command injection in github.com/kardianos/service

advisories/github-reviewed/2022/04/GHSA-4pm3-f52j-8ggh/GHSA-4pm3-f52j-8ggh.json
**Updates**
- Description
- References
=> [GHSA-4pm3-f52j-8ggh] Improper Input Validation in GeoServer

advisories/github-reviewed/2022/04/GHSA-qffw-8wg7-h665/GHSA-qffw-8wg7-h665.json
**Updates**
- Description
- References
=> [GHSA-qffw-8wg7-h665] Command injection in git-interface

advisories/github-reviewed/2021/08/GHSA-w7j2-35mf-95p7/GHSA-w7j2-35mf-95p7.json
=> [GHSA-w7j2-35mf-95p7] Incorrect check on buffer length in rand_core

advisories/github-reviewed/2022/03/GHSA-838h-jqp6-cf2f/GHSA-838h-jqp6-cf2f.json
**Updates**
- Description
- References
=> [GHSA-838h-jqp6-cf2f] Sandbox bypass leading to arbitrary code execution in Deno

advisories/github-reviewed/2022/04/GHSA-6jmm-mp6w-4rrg/GHSA-6jmm-mp6w-4rrg.json
**Updates**
- Description
- References
=> [GHSA-6jmm-mp6w-4rrg] OutOfMemory Exception by specifically crafted processing instruction in NekoHtml Parser

advisories/github-reviewed/2022/04/GHSA-75p6-52g3-rqc8/GHSA-75p6-52g3-rqc8.json
=> [GHSA-75p6-52g3-rqc8] Privilege escalation vulnerability on Token Exchange feature

advisories/github-reviewed/2017/11/GHSA-mw35-24gh-f82w/GHSA-mw35-24gh-f82w.json
=> [GHSA-mw35-24gh-f82w] High severity vulnerability that affects keycloak-connect and keycloak-js

advisories/github-reviewed/2021/11/GHSA-6mcm-j9cj-3vc3/GHSA-6mcm-j9cj-3vc3.json
=> [GHSA-6mcm-j9cj-3vc3] Infinite loop in Apache MINA

advisories/github-reviewed/2022/04/GHSA-vx9g-377x-xwxq/GHSA-vx9g-377x-xwxq.json
=> [GHSA-vx9g-377x-xwxq] Server side request forgery in gibbon

advisories/github-reviewed/2022/04/GHSA-6v73-fgf6-w5j7/GHSA-6v73-fgf6-w5j7.json
=> [GHSA-6v73-fgf6-w5j7] Code Injection in Spring Cloud Function

advisories/github-reviewed/2022/04/GHSA-8xc6-g8xw-h2c4/GHSA-8xc6-g8xw-h2c4.json
**Updates**
- Description
- References
=> [GHSA-8xc6-g8xw-h2c4] YARP Denial of Service Vulnerability

advisories/github-reviewed/2022/04/GHSA-7gc6-qh9x-w6h8/GHSA-7gc6-qh9x-w6h8.json
**Updates**
- Description
- References
=> [GHSA-7gc6-qh9x-w6h8] Incorrect Authorization in cross-fetch

advisories/github-reviewed/2022/04/GHSA-cvx5-m8vg-vxgc/GHSA-cvx5-m8vg-vxgc.json
**Updates**
- Description
- References
=> [GHSA-cvx5-m8vg-vxgc] Arbitrary filesystem write access from velocity.

advisories/github-reviewed/2022/03/GHSA-6xp6-fmc8-pmmr/GHSA-6xp6-fmc8-pmmr.json
=> [GHSA-6xp6-fmc8-pmmr] Temporary Directory Hijacking Vulnerability in Keycloak

advisories/unreviewed/2022/03/GHSA-x3mh-jvjw-3xwx/GHSA-x3mh-jvjw-3xwx.json
**Updates**
- Description
- References
- Summary
=> [GHSA-x3mh-jvjw-3xwx] Infinite loop in `BN_mod_sqrt()` reachable when parsing certificates

advisories/github-reviewed/2022/04/GHSA-28xr-mwxg-3qc8/GHSA-28xr-mwxg-3qc8.json
=> [GHSA-28xr-mwxg-3qc8] Command injection in simple-git

advisories/github-reviewed/2019/07/GHSA-c9jj-3wvg-q65h/GHSA-c9jj-3wvg-q65h.json
=> Contribution to "Vulnerability that affects org.apache.pdfbox:pdfbox"

advisories/github-reviewed/2022/05/GHSA-j77r-2fxf-5jrw/GHSA-j77r-2fxf-5jrw.json
**Updates**
- Description
- References
=> [GHSA-j77r-2fxf-5jrw] Improper path handling in kustomization files allows path traversal

advisories/github-reviewed/2022/05/GHSA-qf8x-vqjv-92gr/GHSA-qf8x-vqjv-92gr.json
=> [GHSA-qf8x-vqjv-92gr] Authentication bypass and denial of service (DoS) vulnerabilities in Apple Game Center auth adapter 

advisories/github-reviewed/2021/04/GHSA-gfr2-qpxh-qj9m/GHSA-gfr2-qpxh-qj9m.json
=> [GHSA-gfr2-qpxh-qj9m] Path Traversal in Ansible

advisories/github-reviewed/2022/02/GHSA-j667-c2hm-f2wp/GHSA-j667-c2hm-f2wp.json
=> [GHSA-j667-c2hm-f2wp] Insertion of Sensitive Information into Log File and Improper Output Neutralization for Logs in ansible

advisories/github-reviewed/2022/05/GHSA-52rh-5rpj-c3w6/GHSA-52rh-5rpj-c3w6.json
**Updates**
- Description
- References
=> [GHSA-52rh-5rpj-c3w6] Improper handling of multiline messages in node-irc

advisories/github-reviewed/2022/02/GHSA-j33j-fg2g-mcv2/GHSA-j33j-fg2g-mcv2.json
**Updates**
- Description
- References
=> [GHSA-j33j-fg2g-mcv2] Cross-Site Request Forgery in CakePHP

advisories/github-reviewed/2022/04/GHSA-x446-3xhq-5xfp/GHSA-x446-3xhq-5xfp.json
=> [GHSA-x446-3xhq-5xfp] Exposure of Resource to Wrong Sphere in Simple-Wayland-HotKey-Daemon

advisories/github-reviewed/2022/03/GHSA-p4jg-pccf-h82c/GHSA-p4jg-pccf-h82c.json
=> [GHSA-p4jg-pccf-h82c] Insecure Temporary File in SWHKD

advisories/github-reviewed/2022/03/GHSA-8m49-2xj8-67v9/GHSA-8m49-2xj8-67v9.json
=> [GHSA-8m49-2xj8-67v9] Data Loss/Denial of Service in SWHKD

advisories/github-reviewed/2021/01/GHSA-395w-qhqr-9fr6/GHSA-395w-qhqr-9fr6.json
=> [GHSA-395w-qhqr-9fr6] Path Traversal in Apache Flink

advisories/github-reviewed/2022/03/GHSA-r5qj-cvf9-p85h/GHSA-r5qj-cvf9-p85h.json
=> [GHSA-r5qj-cvf9-p85h] Code Injection in PyTorch Lightning

advisories/github-reviewed/2018/07/GHSA-p6h9-gw49-rqm4/GHSA-p6h9-gw49-rqm4.json
=> [GHSA-p6h9-gw49-rqm4] Moderate severity vulnerability that affects markdown2

advisories/github-reviewed/2018/10/GHSA-4fq3-mr56-cg6r/GHSA-4fq3-mr56-cg6r.json
=> [GHSA-4fq3-mr56-cg6r] High severity vulnerability that affects org.springframework.data:spring-data-commons

advisories/github-reviewed/2018/07/GHSA-cq94-qf6q-mf2h/GHSA-cq94-qf6q-mf2h.json
=> [GHSA-cq94-qf6q-mf2h] Moderate severity vulnerability that affects pysaml2

advisories/github-reviewed/2022/01/GHSA-fh56-85cw-5pq6/GHSA-fh56-85cw-5pq6.json
=> [GHSA-fh56-85cw-5pq6] Out-of-bounds Write in ujson

advisories/github-reviewed/2022/05/GHSA-6h5x-7c5m-7cr7/GHSA-6h5x-7c5m-7cr7.json
=> [GHSA-6h5x-7c5m-7cr7] Exposure of Sensitive Information in eventsource

advisories/github-reviewed/2022/05/GHSA-wq4h-7r42-5hrr/GHSA-wq4h-7r42-5hrr.json
**Updates**
- Description
- References
=> [GHSA-wq4h-7r42-5hrr] Possible shell escape sequence injection vulnerability in Rack

advisories/github-reviewed/2022/05/GHSA-hp87-p4gw-j4gq/GHSA-hp87-p4gw-j4gq.json
=> [GHSA-hp87-p4gw-j4gq] Unhandled exception in gopkg.in/yaml.v3

advisories/github-reviewed/2022/04/GHSA-h8pj-cxx2-jfg2/GHSA-h8pj-cxx2-jfg2.json
=> [GHSA-h8pj-cxx2-jfg2] Improper Input Validation in httpx

advisories/github-reviewed/2022/03/GHSA-gff7-g5r8-mg8m/GHSA-gff7-g5r8-mg8m.json
=> [GHSA-gff7-g5r8-mg8m] Prototype Pollution in simple-plist

advisories/github-reviewed/2020/08/GHSA-9x4c-63pf-525f/GHSA-9x4c-63pf-525f.json
**Updates**
- Description
- References
=> [GHSA-9x4c-63pf-525f] Arbitrary Code Generation

advisories/github-reviewed/2021/10/GHSA-pfwg-rxf4-97c3/GHSA-pfwg-rxf4-97c3.json
**Updates**
- Description
- References
=> [GHSA-pfwg-rxf4-97c3] Open Redirect in Apache Superset

advisories/github-reviewed/2021/08/GHSA-q9h2-4xhf-23xx/GHSA-q9h2-4xhf-23xx.json
=> [GHSA-q9h2-4xhf-23xx] Data races in im

advisories/github-reviewed/2021/08/GHSA-wrvc-72w7-xpmj/GHSA-wrvc-72w7-xpmj.json
**Updates**
- Description
- References
=> [GHSA-wrvc-72w7-xpmj] Incorrect Comparison in sodiumoxide

advisories/github-reviewed/2021/06/GHSA-rvwf-54qp-4r6v/GHSA-rvwf-54qp-4r6v.json
=> [GHSA-rvwf-54qp-4r6v] XML Entity Expansion in SnakeYAML

advisories/github-reviewed/2022/06/GHSA-5c5f-7vfq-3732/GHSA-5c5f-7vfq-3732.json
=> [GHSA-5c5f-7vfq-3732] JMESPath for Ruby using JSON.load instead of JSON.parse

advisories/github-reviewed/2021/04/GHSA-53xj-v576-3ch2/GHSA-53xj-v576-3ch2.json
Looks like the package name should be "giting", `seria-number` doesn't seem to exist 
**Updates**
- Severity
=> [GHSA-53xj-v576-3ch2] OS Command Injection in giting

advisories/github-reviewed/2021/11/GHSA-fwf6-rw69-hhj4/GHSA-fwf6-rw69-hhj4.json
"html-2-csv" doesn't seem to exist, I think this one is https://pypi.org/project/html-to-csv/
**Updates**
=> [GHSA-fwf6-rw69-hhj4] Improper Neutralization of Formula Elements in a CSV File in html-2-csv

advisories/github-reviewed/2021/08/GHSA-gmw6-94gg-2rc2/GHSA-gmw6-94gg-2rc2.json
Removing the 2nd affected product here because it doesn't seem to exist. 
/arborist does: https://www.npmjs.com/search?q=%40npmcli%2Farborist
But /arborist2 does not: https://www.npmjs.com/search?q=%40npmcli%2Farborist2
Unclear what happened there. 
**Updates**
- Severity
=> [GHSA-gmw6-94gg-2rc2] UNIX Symbolic Link (Symlink) Following in @npmcli/arborist

advisories/github-reviewed/2022/06/GHSA-83gg-pwxf-jr89/GHSA-83gg-pwxf-jr89.json
**Updates**
- Description
- References
=> [GHSA-83gg-pwxf-jr89] `array!` macro is unsound in presence of traits that implement methods it calls internally

advisories/github-reviewed/2022/06/GHSA-cqpr-pcm7-m3jc/GHSA-cqpr-pcm7-m3jc.json
**Updates**
- Description
- References
=> [GHSA-cqpr-pcm7-m3jc] Potential segfault in `localtime_r` invocations

advisories/github-reviewed/2022/05/GHSA-x4cf-6jr3-3qvp/GHSA-x4cf-6jr3-3qvp.json
**Updates**
The version was misassigned in the Advisory Database Sync. It should read 0.7.2 instead of 7.2
=> [GHSA-x4cf-6jr3-3qvp] Out-of-bounds Read in Facebook Hermes

advisories/github-reviewed/2022/05/GHSA-327c-qx3v-h673/GHSA-327c-qx3v-h673.json
**Updates**
The version was misassigned in the Advisory Database Sync. It should read 0.7.2 instead of 7.2
=> [GHSA-327c-qx3v-h673] Always-Incorrect Control Flow Implementation in Facebook Hermes

advisories/github-reviewed/2022/05/GHSA-2w73-fqqj-c92p/GHSA-2w73-fqqj-c92p.json
**Updates**
- Fix a typo in the title
=> [GHSA-2w73-fqqj-c92p] Improper Input Validation in Undertoe

advisories/github-reviewed/2022/05/GHSA-g954-5hwp-pp24/GHSA-g954-5hwp-pp24.json
=> [GHSA-g954-5hwp-pp24] Prototype Pollution in protobufjs

advisories/github-reviewed/2022/02/GHSA-j4f2-536g-r55m/GHSA-j4f2-536g-r55m.json
=> [GHSA-j4f2-536g-r55m] Resource exhaustion in engine.io 

advisories/github-reviewed/2022/06/GHSA-rwqr-c348-m5wr/GHSA-rwqr-c348-m5wr.json
**Updates**
- Description
- References
- Severity
- Summary
=> [GHSA-rwqr-c348-m5wr] Denial of Service in aiohttp

advisories/github-reviewed/2022/05/GHSA-9x5v-8352-244g/GHSA-9x5v-8352-244g.json
=> [GHSA-9x5v-8352-244g] Missing Authorization in Jenkins Pipeline: Shared Groovy Libraries Plugin

advisories/github-reviewed/2022/05/GHSA-72gx-qq2m-6xr2/GHSA-72gx-qq2m-6xr2.json
=> [GHSA-72gx-qq2m-6xr2] Improper Control of Generation of Code in Jenkins Script Security Plugin

advisories/github-reviewed/2021/05/GHSA-xg2h-wx96-xgxr/GHSA-xg2h-wx96-xgxr.json
=> [GHSA-xg2h-wx96-xgxr] RandomAlphaNumeric and CryptoRandomAlphaNumeric are not as random as they should be

advisories/github-reviewed/2022/06/GHSA-w24x-87mr-4r23/GHSA-w24x-87mr-4r23.json
=> [GHSA-w24x-87mr-4r23] SpEL Injection in Spring Data MongoDB

advisories/github-reviewed/2022/06/GHSA-rvgf-69j7-xh78/GHSA-rvgf-69j7-xh78.json
**Updates**
- CVSS
- CWEs
- Description
- Severity
- Summary
=> [GHSA-rvgf-69j7-xh78] Uncontrolled Resource Consumption in @discordjs/opus

advisories/github-reviewed/2020/09/GHSA-m2mx-rfpw-jghv/GHSA-m2mx-rfpw-jghv.json
=> [GHSA-m2mx-rfpw-jghv] DLL Injection in kerberos

advisories/github-reviewed/2017/10/GHSA-qrgf-jqqm-x7xv/GHSA-qrgf-jqqm-x7xv.json
=> [GHSA-qrgf-jqqm-x7xv] High severity vulnerability that affects dragonfly

advisories/github-reviewed/2022/07/GHSA-735f-pg76-fxc4/GHSA-735f-pg76-fxc4.json
=> [GHSA-735f-pg76-fxc4] Heap memory corruption with RSA private key operation

advisories/github-reviewed/2017/10/GHSA-7g65-ghrg-hpf5/GHSA-7g65-ghrg-hpf5.json
=> [GHSA-7g65-ghrg-hpf5] Moderate severity vulnerability that affects actionpack

advisories/github-reviewed/2022/05/GHSA-hxrm-9w7p-39cc/GHSA-hxrm-9w7p-39cc.json
=> [GHSA-hxrm-9w7p-39cc] Cookie parsing failure

advisories/github-reviewed/2021/11/GHSA-xx4c-jj58-r7x6/GHSA-xx4c-jj58-r7x6.json
=> [GHSA-xx4c-jj58-r7x6]  Inefficient Regular Expression Complexity in Validator.js

advisories/github-reviewed/2017/10/GHSA-92w9-2pqw-rhjj/GHSA-92w9-2pqw-rhjj.json
=> [GHSA-92w9-2pqw-rhjj] Moderate severity vulnerability that affects actionpack

advisories/github-reviewed/2017/10/GHSA-p692-7mm3-3fxg/GHSA-p692-7mm3-3fxg.json
=> [GHSA-p692-7mm3-3fxg] actionpack is vulnerable to remote bypass authentication

advisories/github-reviewed/2017/10/GHSA-98mf-8f57-64qf/GHSA-98mf-8f57-64qf.json
=> [GHSA-98mf-8f57-64qf] Moderate severity vulnerability that affects actionpack

advisories/github-reviewed/2019/05/GHSA-ww4x-rwq6-qpgf/GHSA-ww4x-rwq6-qpgf.json
**Updates**
- Description
- References
=> [GHSA-ww4x-rwq6-qpgf] Cross-site Request Forgery in OmniAuth

advisories/github-reviewed/2021/11/GHSA-v5vg-g7rq-363w/GHSA-v5vg-g7rq-363w.json
=> [GHSA-v5vg-g7rq-363w] Prototype Pollution in json-pointer

advisories/github-reviewed/2017/10/GHSA-4ww3-3rxj-8v6q/GHSA-4ww3-3rxj-8v6q.json
**Updates**
- CVSS
- References
=> [GHSA-4ww3-3rxj-8v6q] High severity vulnerability that affects actionpack

advisories/github-reviewed/2022/05/GHSA-4m44-5j2g-xf64/GHSA-4m44-5j2g-xf64.json
=> [GHSA-4m44-5j2g-xf64] Improper Neutralization of Input During Web Page Generation in CKEditor4

advisories/github-reviewed/2021/09/GHSA-7h6j-2268-fhcm/GHSA-7h6j-2268-fhcm.json
=> [GHSA-7h6j-2268-fhcm] Improper Certificate Handling

advisories/github-reviewed/2022/06/GHSA-75rw-34q6-72cr/GHSA-75rw-34q6-72cr.json
=> [GHSA-75rw-34q6-72cr] Signature forgery in Biscuit

advisories/github-reviewed/2022/02/GHSA-5wmg-j84w-4jj4/GHSA-5wmg-j84w-4jj4.json
=> [GHSA-5wmg-j84w-4jj4] Arbitrary File Write via Archive Extraction in mholt/archiver

advisories/github-reviewed/2022/02/GHSA-5x92-p4p5-33c4/GHSA-5x92-p4p5-33c4.json
=> [GHSA-5x92-p4p5-33c4] Path Traversal in HashiCorp Nomad

advisories/github-reviewed/2022/02/GHSA-fqfh-778m-2v32/GHSA-fqfh-778m-2v32.json
=> [GHSA-fqfh-778m-2v32] GitHub CLI can execute a git binary from the current directory

advisories/github-reviewed/2022/07/GHSA-f2gr-7299-487h/GHSA-f2gr-7299-487h.json
=> [GHSA-f2gr-7299-487h] DOS and excessive memory usage when passing untrusted user input to to dag import

advisories/github-reviewed/2021/08/GHSA-7774-7vr3-cc8j/GHSA-7774-7vr3-cc8j.json
=> [GHSA-7774-7vr3-cc8j] Authorization Policy Bypass Due to Case Insensitive Host Comparison

advisories/github-reviewed/2022/03/GHSA-8c26-wmh5-6g9v/GHSA-8c26-wmh5-6g9v.json
**Updates**
- Description
- References
=> [GHSA-8c26-wmh5-6g9v] Use of a Broken or Risky Cryptographic Algorithm in golang.org/x/crypto/ssh

advisories/github-reviewed/2019/10/GHSA-49pj-69vf-c689/GHSA-49pj-69vf-c689.json
=> [GHSA-49pj-69vf-c689] Incorrect Default Permissions in netaddr

advisories/github-reviewed/2021/08/GHSA-23fq-q7hc-993r/GHSA-23fq-q7hc-993r.json
=> [GHSA-23fq-q7hc-993r] Improper Preservation of Permissions in HashiCorp Vault

advisories/github-reviewed/2022/07/GHSA-cj88-88mr-972w/GHSA-cj88-88mr-972w.json
**Updates**
- Description
- References
- Summary
=> [GHSA-cj88-88mr-972w] glob-parent before 6.0.1 vulnerable to Regular Expression Denial of Service (ReDoS)

advisories/github-reviewed/2022/04/GHSA-jv64-2m3x-6v4q/GHSA-jv64-2m3x-6v4q.json
**Updates**
- CVSS
- Description
=> [GHSA-jv64-2m3x-6v4q] Cross-site scripting (XSS) vulnerability exists in the "contact us" plugin for Subrion CMS

advisories/github-reviewed/2022/01/GHSA-gf8q-jrpm-jvxq/GHSA-gf8q-jrpm-jvxq.json
=> [GHSA-gf8q-jrpm-jvxq] URL parsing in node-forge could lead to undesired behavior.

advisories/github-reviewed/2018/06/GHSA-pr3h-jjhj-573x/GHSA-pr3h-jjhj-573x.json
=> [GHSA-pr3h-jjhj-573x] High severity vulnerability that affects sprockets

advisories/github-reviewed/2022/07/GHSA-xg72-6c83-ghh4/GHSA-xg72-6c83-ghh4.json
=> [GHSA-xg72-6c83-ghh4] Microweber Stored Cross-site Scripting before v1.2.20

advisories/github-reviewed/2022/07/GHSA-44vr-rwwj-p88h/GHSA-44vr-rwwj-p88h.json
=> [GHSA-44vr-rwwj-p88h] Shescape vulnerable to insufficient escaping of whitespace

advisories/github-reviewed/2021/05/GHSA-58pf-pcwv-qg85/GHSA-58pf-pcwv-qg85.json
**Updates**
- Description
- Severity
=> [GHSA-58pf-pcwv-qg85] Path traversal

advisories/github-reviewed/2022/01/GHSA-xhw6-hjc9-679m/GHSA-xhw6-hjc9-679m.json
**Updates**
- Description
- References
=> [GHSA-xhw6-hjc9-679m] Token validation bypass in Pac4j

advisories/github-reviewed/2018/10/GHSA-jc8g-xhw5-6x46/GHSA-jc8g-xhw5-6x46.json
=> [GHSA-jc8g-xhw5-6x46] Improper Certificate Validation in Microsoft .NET Framework components

advisories/github-reviewed/2021/12/GHSA-q54r-r9pr-w7qv/GHSA-q54r-r9pr-w7qv.json
=> [GHSA-q54r-r9pr-w7qv] XSS in Hexo

advisories/github-reviewed/2022/05/GHSA-p9wx-v264-q34p/GHSA-p9wx-v264-q34p.json
=> [GHSA-p9wx-v264-q34p] Improper Certificate Validation in Microsoft .NET Framework components

advisories/github-reviewed/2022/06/GHSA-pf6p-25r2-fx45/GHSA-pf6p-25r2-fx45.json
=> [GHSA-pf6p-25r2-fx45] Server-Side Request Forgery in dompdf/dompdf 

advisories/github-reviewed/2022/07/GHSA-7mwh-4pqv-wmr8/GHSA-7mwh-4pqv-wmr8.json
**Updates**
- Description
- References
=> [GHSA-7mwh-4pqv-wmr8] Regular expression denial of service in scss-tokenizer

advisories/github-reviewed/2022/07/GHSA-mhxj-85r3-2x55/GHSA-mhxj-85r3-2x55.json
**Updates**
- CVSS
- Description
- Severity
=> [GHSA-mhxj-85r3-2x55] file-type vulnerable to Infinite Loop via malformed MKV file

advisories/github-reviewed/2021/08/GHSA-88f9-7xxh-c688/GHSA-88f9-7xxh-c688.json
**Updates**
- Description
- References
=> [GHSA-88f9-7xxh-c688] Configuration leak

advisories/github-reviewed/2022/04/GHSA-86r3-4gq8-xw8q/GHSA-86r3-4gq8-xw8q.json
**Updates**
- CVSS
- CWEs
- Description
- References
- Severity
- Summary
**Comments**
CVE Rejected
=> [GHSA-86r3-4gq8-xw8q] Remote Code Execution in Laravel

advisories/github-reviewed/2022/06/GHSA-vv7q-mfpc-qgm5/GHSA-vv7q-mfpc-qgm5.json
**Updates**
- CVSS
- Description
- References
- Severity
- Summary
**Comments**
CVE Rejected.
=> [GHSA-vv7q-mfpc-qgm5] Unserialized Pop Chain in Laravel

advisories/github-reviewed/2022/06/GHSA-chj3-f7xw-367m/GHSA-chj3-f7xw-367m.json
**Updates**
- Description
**Comments**
Requesting to update POC as part of the description and researcher recognition for @lirantal in the advisory _Credits_ section
=> [GHSA-chj3-f7xw-367m] OS Command Injection in git-promise

advisories/github-reviewed/2022/07/GHSA-8jmw-wjr8-2x66/GHSA-8jmw-wjr8-2x66.json
**Updates**
**Comments**
Requesting to add researcher recognition for @lirantal in the advisory's _Credits_ section
=> [GHSA-8jmw-wjr8-2x66] Command injection in git-clone

advisories/github-reviewed/2022/05/GHSA-3x62-x456-q2vm/GHSA-3x62-x456-q2vm.json
**Updates**
- Description
**Comments**
Updating the description with proof-of-concept information and requesting to add recognition for researcher @lirantal in the advisory's _Credits_ section
=> [GHSA-3x62-x456-q2vm] OS Command Injection in git-pull-or-clone

advisories/github-reviewed/2022/01/GHSA-53xv-c2hx-5w6q/GHSA-53xv-c2hx-5w6q.json
**Updates**
- References
**Comments**
Update new reference
=> [GHSA-53xv-c2hx-5w6q] Command Injection in node-windows

advisories/github-reviewed/2021/12/GHSA-792j-9wj3-j634/GHSA-792j-9wj3-j634.json
**Updates**
- References
**Comments**
Replace references.
=> [GHSA-792j-9wj3-j634] Command injection in github-todos

advisories/unreviewed/2021/12/GHSA-wjqc-j537-j9gj/GHSA-wjqc-j537-j9gj.json
**Updates**
- References
**Comments**
Updating product metadata & references.
=> [GHSA-wjqc-j537-j9gj] Command injection in git-it-electron

advisories/github-reviewed/2021/08/GHSA-jg8v-48h5-wgxg/GHSA-jg8v-48h5-wgxg.json
**Updates**
**Comments**
https://github.com/Stuk/jszip/pull/824
=> [GHSA-jg8v-48h5-wgxg] Prototype Pollution

advisories/github-reviewed/2022/08/GHSA-mw9h-hcp7-fgc6/GHSA-mw9h-hcp7-fgc6.json
**Updates**
- CVSS
- Severity
**Comments**
CVSS string was incorrectly copied? score is 5.3, not 7.5
=> [GHSA-mw9h-hcp7-fgc6] Exposure of Sensitive Information in OPCFoundation.NetStandard.Opc.Ua.Server

advisories/github-reviewed/2022/06/GHSA-6fp8-cxc9-4fr9/GHSA-6fp8-cxc9-4fr9.json
**Updates**
**Comments**
Core library was not flagged
=> [GHSA-6fp8-cxc9-4fr9] Uncontrolled Resource Consumption in OPCFoundation.NetStandard.Opc.Ua

advisories/github-reviewed/2022/06/GHSA-fvxf-r9fw-49pc/GHSA-fvxf-r9fw-49pc.json
**Updates**
**Comments**
.core library was not flagged
=> [GHSA-fvxf-r9fw-49pc] Incorrect Implementation of Authentication Algorithm in OPCFoundation.NetStandard.Opc.Ua

advisories/github-reviewed/2022/06/GHSA-vhfw-v69p-crcw/GHSA-vhfw-v69p-crcw.json
**Updates**
- CVSS
**Comments**
flag core library and provide the CVSS string
=> [GHSA-vhfw-v69p-crcw] Uncontrolled Resource Consumption in OPCFoundation.NetStandard.Opc.Ua

advisories/github-reviewed/2022/06/GHSA-r7pq-3x6p-7jcm/GHSA-r7pq-3x6p-7jcm.json
**Updates**
- CVSS
- CWEs
**Comments**
flag core package and add missing information
=> [GHSA-r7pq-3x6p-7jcm] Memory Allocation with Excessive Size Value in OPCFoundation.NetStandard.Opc.Ua

advisories/github-reviewed/2021/11/GHSA-mjww-934m-h4jw/GHSA-mjww-934m-h4jw.json
**Updates**
**Comments**
flag core library
=> [GHSA-mjww-934m-h4jw] Improper Certificate Validation in OPCFoundation.NetStandard.Opc.Ua

advisories/github-reviewed/2018/10/GHSA-mv2r-q4g5-j8q5/GHSA-mv2r-q4g5-j8q5.json
**Updates**
**Comments**
Correcting fixed package versions for Microsoft.AspNetCore.DataProtection.AzureStorage released 9/10/2019.
=> [GHSA-mv2r-q4g5-j8q5] Denial of service in ASP.NET Core

advisories/github-reviewed/2022/05/GHSA-xr8f-59pp-rxxh/GHSA-xr8f-59pp-rxxh.json
**Updates**
**Comments**
Previously listed fixed versions of Microsoft.AspNetCore.SpaServices did not exist. Updating to the correct versions released on 9//10/2019.
=> [GHSA-xr8f-59pp-rxxh] Elevation of privilege in ASP.NET Core

advisories/github-reviewed/2022/06/GHSA-q4qm-xhf9-4p8f/GHSA-q4qm-xhf9-4p8f.json
**Updates**
**Comments**
Fixed in version 1.2.0, ref: https://github.com/mher/flower/issues/1217
=> [GHSA-q4qm-xhf9-4p8f] Flower OAuth authentication bypass

advisories/github-reviewed/2022/03/GHSA-f8q4-jwww-x3wv/GHSA-f8q4-jwww-x3wv.json
**Updates**
**Comments**
This problem was fixed in 2.9.3 for the 2.9.x branch.
=> [GHSA-f8q4-jwww-x3wv] Race Condition in Paramiko

advisories/github-reviewed/2019/06/GHSA-gc94-6w89-hpqr/GHSA-gc94-6w89-hpqr.json
**Updates**
- Description
**Comments**
https://github.com/pillys/fs-path/pull/5
=> [GHSA-gc94-6w89-hpqr] Command Injection in fs-path

advisories/github-reviewed/2022/06/GHSA-gp95-ppv5-3jc5/GHSA-gp95-ppv5-3jc5.json
**Updates**
- References
- Summary
**Comments**
Better advisory title & add a detailed reference
=> [GHSA-gp95-ppv5-3jc5] Possible vulnerability in sharp at 'npm install' time if an attacker has control over build environment

advisories/github-reviewed/2022/09/GHSA-jj62-mc3m-j769/GHSA-jj62-mc3m-j769.json
**Updates**
**Comments**
Formatting the package name to match the one found in packagist.
https://packagist.org/packages/feehi/cms
=> [GHSA-jj62-mc3m-j769] FeehiCMS has an arbitrary file upload vulnerability

advisories/github-reviewed/2022/09/GHSA-xvqg-mv25-rwvw/GHSA-xvqg-mv25-rwvw.json
**Updates**
- Description
- References
**Comments**
The URL for the reference is incorrect.
=> [GHSA-xvqg-mv25-rwvw] Parsing issue in matrix-org/node-irc leading to room takeovers

advisories/github-reviewed/2022/05/GHSA-3wqf-4x89-9g79/GHSA-3wqf-4x89-9g79.json
**Updates**
**Comments**
Bootstrap 3 uses jQuery's `find` method, so it is not affected by the XSS vulnerability:
- collapse: https://github.com/twbs/bootstrap/blob/v3.4.1/js/collapse.js#L140
- tooltip: https://github.com/twbs/bootstrap/blob/v3.4.1/js/tooltip.js#L352
- scrollspy: https://github.com/twbs/bootstrap/blob/v3.4.1/js/scrollspy.js#L56
=> [GHSA-3wqf-4x89-9g79] Bootstrap vulnerable to Cross-Site Scripting (XSS)

advisories/github-reviewed/2018/07/GHSA-jxqq-cqm6-pfq9/GHSA-jxqq-cqm6-pfq9.json
**Updates**
**Comments**
Vulnerability has been patched in new version: https://github.com/dodo/node-slug/issues/82
=> [GHSA-jxqq-cqm6-pfq9] Regular Expression Denial of Service in slug

advisories/github-reviewed/2021/06/GHSA-656c-6cxf-hvcv/GHSA-656c-6cxf-hvcv.json
**Updates**
- CVSS
- Description
- References
- Severity
**Comments**
The CVE was mis-scored and mis-classified. Added context for the reduced scoring decision.
=> [GHSA-656c-6cxf-hvcv] Deserialization of Untrusted Data in Flask-Caching

advisories/github-reviewed/2022/06/GHSA-vvv8-xw5f-3f88/GHSA-vvv8-xw5f-3f88.json
**Updates**
**Comments**
Patched version information
=> [GHSA-vvv8-xw5f-3f88] Prototype Pollution in mout

advisories/github-reviewed/2022/09/GHSA-8r89-x93x-mjq2/GHSA-8r89-x93x-mjq2.json
**Updates**
**Comments**
The vulnerability did not affect versions prior to 4.0.0
=> [GHSA-8r89-x93x-mjq2] Craft CMS Stored Cross-site Scripting in User Addresses Title

advisories/github-reviewed/2022/09/GHSA-wxvf-839f-jqmh/GHSA-wxvf-839f-jqmh.json
**Updates**
**Comments**
The vulnerability did not affect versions prior to 4.0.0
=> [GHSA-wxvf-839f-jqmh] Craft CMS Cross site Scripting vulnerability

advisories/github-reviewed/2018/07/GHSA-cqp5-m4pq-gfgp/GHSA-cqp5-m4pq-gfgp.json
**Updates**
**Comments**
Wrong Npm package name!
=> [GHSA-cqp5-m4pq-gfgp] Prototype Pollution in defaults-deep

advisories/github-reviewed/2022/08/GHSA-mfpj-3qhm-976m/GHSA-mfpj-3qhm-976m.json
**Updates**
**Comments**
https://github.com/FreeOpcUa/opcua-asyncio/pull/1040
=> [GHSA-mfpj-3qhm-976m] Uncontrolled Resource Consumption in asyncua and opcua

advisories/github-reviewed/2021/05/GHSA-cf4h-3jhx-xvhq/GHSA-cf4h-3jhx-xvhq.json
**Updates**
- Severity
**Comments**
Arbitrary Code Execution in underscore
=> [GHSA-cf4h-3jhx-xvhq] Arbitrary Code Execution in underscore

advisories/github-reviewed/2022/09/GHSA-8qv5-68g4-248j/GHSA-8qv5-68g4-248j.json
**Updates**
**Comments**
The correct version is mentioned in prose, but the wrong version is listed in the formal version fields.
=> [GHSA-8qv5-68g4-248j] Scala subject to file deletion, code execution due to Java deserialization chain with LazyList object deserialization

advisories/github-reviewed/2022/09/GHSA-rhwx-hjx2-x4qr/GHSA-rhwx-hjx2-x4qr.json
**Updates**
**Comments**
This vulnerability has been resolved by https://github.com/pdfkit/pdfkit/pull/509.
=> [GHSA-rhwx-hjx2-x4qr] PDFKit vulnerable to Command Injection

advisories/github-reviewed/2021/10/GHSA-gpqq-952q-5327/GHSA-gpqq-952q-5327.json
**Updates**
- Description
**Comments**
The PoC exploit code now matches the explanation of the result.
=> [GHSA-gpqq-952q-5327] XSS in the `of` option of the `.position()` util in jquery-ui

advisories/github-reviewed/2022/10/GHSA-jjjh-jjxp-wpff/GHSA-jjjh-jjxp-wpff.json
**Updates**
- Summary
**Comments**
Title was not correct
=> [GHSA-jjjh-jjxp-wpff] Deserialization of Untrusted Data in FasterXML jackson-databind

advisories/github-reviewed/2022/10/GHSA-rgv9-q543-rqg4/GHSA-rgv9-q543-rqg4.json
**Updates**
- CWEs
- Summary
**Comments**
Title and CWE were incorrect.
=> [GHSA-rgv9-q543-rqg4] Deserialization of Untrusted Data in FasterXML jackson-databind

README.md
Updates the README with a link to the Pub ecosystem.
=> Add Pub to README

advisories/github-reviewed/2022/01/GHSA-f9jg-8p32-2f55/GHSA-f9jg-8p32-2f55.json
**Updates**
- CVSS
- CWEs
- Severity
**Comments**
Fix versions (it's currently unfixed), add CWE and CVSS.
=> [GHSA-f9jg-8p32-2f55] ANSI escape characters not filtered

advisories/github-reviewed/2022/10/GHSA-9pgh-qqpf-7wqj/GHSA-9pgh-qqpf-7wqj.json
**Updates**
- Description
**Comments**
The link to issue in the Advisory was incorrect.
=> [GHSA-9pgh-qqpf-7wqj] Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution') in @xmldom/xmldom and xmldom

advisories/github-reviewed/2019/10/GHSA-8687-vv9j-hgph/GHSA-8687-vv9j-hgph.json
**Updates**
**Comments**
Commit was cherry-picked back in 4.13.21. https://github.com/Automattic/mongoose/commits/4.13.21
=> [GHSA-8687-vv9j-hgph] Improper Input Validation in Automattic Mongoose

advisories/github-reviewed/2022/05/GHSA-g4rg-993r-mgx7/GHSA-g4rg-993r-mgx7.json
**Updates**
- CVSS
- Severity
**Comments**
https://nvd.nist.gov/vuln/detail/CVE-2021-42740
https://github.com/substack/node-shell-quote/commit/5799416ed454aa4ec9afafc895b4e31760ea1abe
https://github.com/substack/node-shell-quote/blob/master/CHANGELOG.md#173
https://www.npmjs.com/package/shell-quote
=> [GHSA-g4rg-993r-mgx7] Improper Neutralization of Special Elements used in a Command in Shell-quote

advisories/github-reviewed/2022/10/GHSA-x4q7-m6fp-4v9v/GHSA-x4q7-m6fp-4v9v.json
Hello,
I am unsure if this is the correct route, but I cannot find another way to modify this value via [the original advisory](https://github.com/octobercms/october/security/advisories/GHSA-x4q7-m6fp-4v9v).
Thank you
=> [GHSA-x4q7-m6fp-4v9v] Fixes 0 introduced affecting version 1

advisories/github-reviewed/2022/05/GHSA-242j-2gm6-5rwx/GHSA-242j-2gm6-5rwx.json
**Updates**
**Comments**
There's one package that was provided in backfill request https://github.com/github/advisory-database/issues/739 that's missing from this list.
=> [GHSA-242j-2gm6-5rwx] ASP.NET Core and Visual Studio Denial of Service Vulnerability

advisories/github-reviewed/2022/08/GHSA-3rq8-h3gj-r5c6/GHSA-3rq8-h3gj-r5c6.json
**Updates**
**Comments**
There's a mismatch when comparing the list of packages in the description of this CVE.
=> [GHSA-3rq8-h3gj-r5c6]  .NET Denial of Service Vulnerability

advisories/github-reviewed/2022/05/GHSA-23cv-jh4v-vffm/GHSA-23cv-jh4v-vffm.json
**Updates**
**Comments**
Those changes are based on inputs from the .NET team that owns those packages. //cc @leecow
=> [GHSA-23cv-jh4v-vffm] Denial of service in ASP.NET Core

advisories/github-reviewed/2022/05/GHSA-r4mw-gxf7-vxr9/GHSA-r4mw-gxf7-vxr9.json
**Updates**
**Comments**
The added packages are based on input from the .NET team. //cc @leecow
=> [GHSA-r4mw-gxf7-vxr9] Remote code execution in Microsoft.WindowsDesktop.App.Ref

advisories/github-reviewed/2022/05/GHSA-655q-9gvg-q4cm/GHSA-655q-9gvg-q4cm.json
**Updates**
**Comments**
Those additional impacted packages are based on inputs from the .NET team. //cc @leecow
=> [GHSA-655q-9gvg-q4cm] Remote code execution in ASP.NET Core

advisories/github-reviewed/2022/11/GHSA-43xg-8wmj-cw8h/GHSA-43xg-8wmj-cw8h.json
**Updates**
- References
**Comments**
add patch for XSS, add link to source code
=> [GHSA-43xg-8wmj-cw8h] Apache Spark vulnerable to Injection

advisories/github-reviewed/2022/06/GHSA-77hf-23pq-2g7c/GHSA-77hf-23pq-2g7c.json
**Updates**
**Comments**
add source code link
=> [GHSA-77hf-23pq-2g7c] Code injection in Apache NiFi and NiFi Registry

advisories/github-reviewed/2022/05/GHSA-h7wm-ph43-c39p/GHSA-h7wm-ph43-c39p.json
**Updates**
**Comments**
It's still not fixed - https://github.com/github/advisory-database/pull/699
=> [GHSA-h7wm-ph43-c39p] Scrapy denial of service vulnerability

advisories/github-reviewed/2022/10/GHSA-76p3-8jx3-jpfq/GHSA-76p3-8jx3-jpfq.json
**Updates**
**Comments**
This was back-ported in this PR: https://github.com/webpack/loader-utils/pull/220
=> [GHSA-76p3-8jx3-jpfq] Prototype pollution in webpack loader-utils

advisories/github-reviewed/2021/04/GHSA-vgv5-cxvh-vfxh/GHSA-vgv5-cxvh-vfxh.json
**Updates**
**Comments**
Version 0.1.5 and upper should not be threated as vulnerable.
=> [GHSA-vgv5-cxvh-vfxh] Arbitrary code execution in clickhouse-driver

advisories/github-reviewed/2022/10/GHSA-qm95-pgcg-qqfq/GHSA-qm95-pgcg-qqfq.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
- format code examples
- add backports for Socket.IO v2
- add examples of malicious values
- decrease the severity of the vulnerability
=> [GHSA-qm95-pgcg-qqfq] Insufficient validation when decoding a Socket.IO packet

advisories/github-reviewed/2022/10/GHSA-hhq3-ff78-jv3g/GHSA-hhq3-ff78-jv3g.json
**Updates**
- Summary
**Comments**
Removed trailing space in title
=> [GHSA-hhq3-ff78-jv3g] loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) 

advisories/github-reviewed/2022/11/GHSA-7fxj-fr3v-r9gj/GHSA-7fxj-fr3v-r9gj.json
**Updates**
- CVSS
- Description
- References
- Severity
- Summary
**Comments**
Update to proper title & description, correct severity, and add a reference.
=> [GHSA-7fxj-fr3v-r9gj] TiDB vulnerable to Use of Externally-Controlled Format String

advisories/github-reviewed/2022/02/GHSA-j8jw-g6fq-mp7h/GHSA-j8jw-g6fq-mp7h.json
**Updates**
- Description
**Comments**
This vulnerability was also fixed for 5.3 branch in version 5.3.20
https://hibernate.atlassian.net/browse/HHH-14225?jql=project%20%3D%20HHH%20AND%20fixVersion%20in%20(5.3.20)%20ORDER%20BY%20updated
=> [GHSA-j8jw-g6fq-mp7h] SQL injection in hibernate-core

advisories/github-reviewed/2022/11/GHSA-w37g-rhq8-7m4j/GHSA-w37g-rhq8-7m4j.json
**Updates**
- Summary
**Comments**
Fixed typo in the Title
=> [GHSA-w37g-rhq8-7m4j] Snakeyaml vulnerbale to Stack overflow leading to denial of service

advisories/github-reviewed/2022/01/GHSA-w2mh-6xj5-f77f/GHSA-w2mh-6xj5-f77f.json
**Updates**
**Comments**
Add source code documentation to the advisory.
=> [GHSA-w2mh-6xj5-f77f] Incorrect Permission Assignment for Critical Resource in Jenkins Bitbucket Branch Source Plugin

advisories/github-reviewed/2022/01/GHSA-w4jv-6rg4-pr4m/GHSA-w4jv-6rg4-pr4m.json
**Updates**
**Comments**
Add source code documentation to the advisory.
=> [GHSA-w4jv-6rg4-pr4m] Cross-Site Request Forgery in Jenkins Bitbucket Branch Source Plugin

advisories/github-reviewed/2022/01/GHSA-fpj7-9xm6-8hgr/GHSA-fpj7-9xm6-8hgr.json
**Updates**
**Comments**
Fill in details outlining this vulnerability has been fixed https://www.jenkins.io/security/advisory/2022-01-12/#SECURITY-2141
=> [GHSA-fpj7-9xm6-8hgr] Observable Discrepancy and Observable Timing Discrepancy in Jenkins Configuration as Code Plugin

advisories/github-reviewed/2022/03/GHSA-hpm9-fx8v-w45v/GHSA-hpm9-fx8v-w45v.json
**Updates**
- CVSS
- Severity
**Comments**
Fill in fixed version according to https://www.jenkins.io/security/advisory/2022-03-29/#SECURITY-2161
=> [GHSA-hpm9-fx8v-w45v] Plaintext storage in Jenkins instant-messaging Plugin

advisories/github-reviewed/2022/02/GHSA-34wx-x2w9-vqm3/GHSA-34wx-x2w9-vqm3.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update advisory data according to https://www.jenkins.io/security/advisory/2022-02-09/
Also adds an entry about the LTS version ranges affected
=> [GHSA-34wx-x2w9-vqm3] Deserialization of Untrusted Data in Jenkins Core

advisories/github-reviewed/2022/02/GHSA-w4jq-qh47-hvjq/GHSA-w4jq-qh47-hvjq.json
**Updates**
**Comments**
The affected and patched versions are incorrect.
=> [GHSA-w4jq-qh47-hvjq] Improper Input Validation in Xerces

advisories/github-reviewed/2022/11/GHSA-w573-4hg7-7wgq/GHSA-w573-4hg7-7wgq.json
**Updates**
**Comments**
https://github.com/SamVerschueren/decode-uri-component/issues/6#issuecomment-1334014223 and also https://github.com/SamVerschueren/decode-uri-component/issues/5#issuecomment-1334011541
=> [GHSA-w573-4hg7-7wgq] decode-uri-component vulnerable to Denial of Service (DoS)

advisories/github-reviewed/2020/06/GHSA-6hgm-866r-3cjv/GHSA-6hgm-866r-3cjv.json
**Updates**
- CWEs
**Comments**
CWE = CWE-502 based on CVE-2015-6420 in NVD
=> [GHSA-6hgm-866r-3cjv] Insecure Deserialization in Apache Commons Collection

advisories/github-reviewed/2022/02/GHSA-vwx4-frpr-w27j/GHSA-vwx4-frpr-w27j.json
**Updates**
- CVSS
- Severity
**Comments**
Update advisory according to https://www.jenkins.io/security/advisory/2022-02-15/#SECURITY-2280
=> [GHSA-vwx4-frpr-w27j] Improper Synchronization in Jenkins Convertigo Mobile Platform Plugin

advisories/github-reviewed/2022/02/GHSA-38w8-h222-wrpp/GHSA-38w8-h222-wrpp.json
**Updates**
- CVSS
- Description
**Comments**
Update versions affected according to https://www.jenkins.io/security/advisory/2022-02-15/#SECURITY-1377
=> [GHSA-38w8-h222-wrpp] Improper Restriction of XML External Entity Reference in Jenkins Chef Sinatra

advisories/github-reviewed/2022/02/GHSA-m5wp-p3gj-7q5g/GHSA-m5wp-p3gj-7q5g.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-02-15/#SECURITY-2177
=> [GHSA-m5wp-p3gj-7q5g] Missing Authorization in Jenkins dbCharts Plugin

advisories/github-reviewed/2022/02/GHSA-vx6f-6rp6-f2px/GHSA-vx6f-6rp6-f2px.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS evaluation according to https://www.jenkins.io/security/advisory/2022-02-15/#SECURITY-2177
=> [GHSA-vx6f-6rp6-f2px] Cross-Site Request Forgery in Jenkins dbCharts Plugin

advisories/github-reviewed/2022/04/GHSA-jmxr-w2jc-qp7w/GHSA-jmxr-w2jc-qp7w.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update versions affected and CVSS evaluation according to https://www.jenkins.io/security/advisory/2022-04-12/#SECURITY-2655
=> [GHSA-jmxr-w2jc-qp7w] Improper Input Validation in Jenkins Promoted Builds Plugin

advisories/github-reviewed/2022/04/GHSA-v98r-gjgc-m9pf/GHSA-v98r-gjgc-m9pf.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Correct versions affected and fixed according to https://www.jenkins.io/security/advisory/2022-04-12/#SECURITY-2617
=> [GHSA-v98r-gjgc-m9pf] Cross-site Scripting in Jenkins Promoted Builds Plugin

advisories/github-reviewed/2022/02/GHSA-fhfh-6cjg-57rg/GHSA-fhfh-6cjg-57rg.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update versions affected and fixed according to https://www.jenkins.io/security/advisory/2022-02-15/#SECURITY-2536
=> [GHSA-fhfh-6cjg-57rg] Jenkins Snow Commander Plugin 2.0 vulnerable to Cross-Site Request Forgery

advisories/github-reviewed/2022/05/GHSA-rr2r-g6xm-58xj/GHSA-rr2r-g6xm-58xj.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-1969
=> [GHSA-rr2r-g6xm-58xj] Cross Site Request Forgery in Jenkins Storable Configs Plugin

advisories/github-reviewed/2022/05/GHSA-wqmp-2p5r-rhfv/GHSA-wqmp-2p5r-rhfv.json
**Updates**
- CVSS
- Description
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-1969
=> [GHSA-wqmp-2p5r-rhfv] XML External Entity Reference in Jenkins Storable Configs Plugin

advisories/github-reviewed/2022/05/GHSA-cj9j-v8jp-6hm9/GHSA-cj9j-v8jp-6hm9.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2267
=> [GHSA-cj9j-v8jp-6hm9] Cross-site Scripting in Jenkins Autocomplete Parameter Plugin

advisories/github-reviewed/2022/05/GHSA-7c3v-2jjv-hq3c/GHSA-7c3v-2jjv-hq3c.json
**Updates**
- CVSS
**Comments**
Fix CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2322
=> [GHSA-7c3v-2jjv-hq3c] Cross-Site Request Forgery in Jenkins Autocomplete Parameter Plugin

advisories/github-reviewed/2022/05/GHSA-9w23-w757-mvv8/GHSA-9w23-w757-mvv8.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2717
=> [GHSA-9w23-w757-mvv8] Cross-site Scripting in Jenkins vboxwrapper Plugin

advisories/github-reviewed/2022/05/GHSA-mw4r-5mfc-m5vc/GHSA-mw4r-5mfc-m5vc.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2717
=> [GHSA-mw4r-5mfc-m5vc] Cross site scripting in Jenkins Selection tasks Plugin

advisories/github-reviewed/2022/05/GHSA-h3v9-46pp-h33w/GHSA-h3v9-46pp-h33w.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2717
=> [GHSA-h3v9-46pp-h33w] Cross-site Scripting in Jenkins Multiselect parameter Plugin

advisories/github-reviewed/2022/05/GHSA-5pmp-7wc9-v7vw/GHSA-5pmp-7wc9-v7vw.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS and details according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2717
=> [GHSA-5pmp-7wc9-v7vw] Cross-site Scripting in Jenkins JDK Parameter Plugin

advisories/github-reviewed/2022/05/GHSA-ppwv-mvqg-q89h/GHSA-ppwv-mvqg-q89h.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring and description according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2717
=> [GHSA-ppwv-mvqg-q89h] Cross-site Scripting in Jenkins Autocomplete Parameter Plugin

advisories/github-reviewed/2022/05/GHSA-6wh8-mr6f-6cx2/GHSA-6wh8-mr6f-6cx2.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2717
=> [GHSA-6wh8-mr6f-6cx2] Cross-site Scripting in Jenkins Application Detector Plugin

advisories/github-reviewed/2022/05/GHSA-9g33-48jh-jq7v/GHSA-9g33-48jh-jq7v.json
**Updates**
- CVSS
**Comments**
Update CVSS according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2093
=> [GHSA-9g33-48jh-jq7v] Cross Site Request Forgery in Jenkins SSH Plugin

advisories/github-reviewed/2022/05/GHSA-4m42-8qfq-h3q9/GHSA-4m42-8qfq-h3q9.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2600
=> [GHSA-4m42-8qfq-h3q9] Cross-site Scripting in Jenkins Rundeck Plugin

advisories/github-reviewed/2022/05/GHSA-5phj-qv74-pv4w/GHSA-5phj-qv74-pv4w.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2753
=> [GHSA-5phj-qv74-pv4w] Missing permission check in Jenkins GitLab Plugin

advisories/github-reviewed/2022/05/GHSA-5m4q-x28v-q6wp/GHSA-5m4q-x28v-q6wp.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2502
=> [GHSA-5m4q-x28v-q6wp] Missing permission check in Jenkins Blue Ocean Plugin

advisories/github-reviewed/2022/05/GHSA-hgpq-42pf-9vfq/GHSA-hgpq-42pf-9vfq.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2502
=> [GHSA-hgpq-42pf-9vfq] Cross Site Request Forgery in Jenkins Blue Ocean Plugin

advisories/github-reviewed/2022/05/GHSA-g74w-93cp-5p3p/GHSA-g74w-93cp-5p3p.json
**Updates**
- CVSS
- Description
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-714
I've updated the description too, given the complexity this vulnerability and mitigation bring in.
=> [GHSA-g74w-93cp-5p3p] Insufficiently Protected Credentials in Jenkins Pipeline SCM API for Blue Ocean Plugin

advisories/github-reviewed/2022/05/GHSA-p566-wpxx-574m/GHSA-p566-wpxx-574m.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2604
=> [GHSA-p566-wpxx-574m] Missing Authorization in Jenkins WMI Windows Agents plugin

advisories/github-reviewed/2022/05/GHSA-xhw3-wmx2-76wf/GHSA-xhw3-wmx2-76wf.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2604
=> [GHSA-xhw3-wmx2-76wf] Buffer overflow in Jenkins WMI Windows Agents plugin

advisories/github-reviewed/2022/05/GHSA-8vfc-fcr2-47pj/GHSA-8vfc-fcr2-47pj.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2478
=> [GHSA-8vfc-fcr2-47pj] Path traversal in Jenkins REPO Plugin

advisories/github-reviewed/2022/05/GHSA-5786-3qjg-mr88/GHSA-5786-3qjg-mr88.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2478
=> [GHSA-5786-3qjg-mr88] Path traversal in Jenkins Mercurial Plugin

advisories/github-reviewed/2022/05/GHSA-84cm-vjwm-m979/GHSA-84cm-vjwm-m979.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring and description according to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2478
=> [GHSA-84cm-vjwm-m979] Path traversal in Jenkins Git Plugin

advisories/github-reviewed/2022/11/GHSA-g56w-cwg4-hxx9/GHSA-g56w-cwg4-hxx9.json
**Updates**
**Comments**
The project provided two versions where this is fixed: `2.14.2.Final` and `2.13.5.Final`
See the announcement: https://github.com/quarkusio/quarkus/discussions/29527
=> [GHSA-g56w-cwg4-hxx9] Code injection in quarkus dev ui config editor

advisories/github-reviewed/2022/06/GHSA-9h79-5m2f-mqj2/GHSA-9h79-5m2f-mqj2.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2089
=> [GHSA-9h79-5m2f-mqj2] Squash TM Publisher (Squash4Jenkins) Plugin stores passwords stored in plain text

advisories/github-reviewed/2022/06/GHSA-c965-p3w4-835c/GHSA-c965-p3w4-835c.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2279
=> [GHSA-c965-p3w4-835c] Cross-Site Request Forgery in Jenkins vRealize Orchestrator Plugin

advisories/github-reviewed/2022/06/GHSA-rq99-93c5-33f6/GHSA-rq99-93c5-33f6.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2249
=> [GHSA-rq99-93c5-33f6] Cross-Site Request Forgery in Jenkins ThreadFix Plugin

advisories/github-reviewed/2022/06/GHSA-q8v3-7h6q-g39q/GHSA-q8v3-7h6q-g39q.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2240
=> [GHSA-q8v3-7h6q-g39q] Cross-Site Request Forgery in Jenkins Jianliao Notification Plugin

advisories/github-reviewed/2022/06/GHSA-g67p-jvvc-qf54/GHSA-g67p-jvvc-qf54.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2281
=> [GHSA-g67p-jvvc-qf54] Cross-Site Request Forgery in Jenkins EasyQA Plugin

advisories/github-reviewed/2022/06/GHSA-xcp5-j5fj-3xp6/GHSA-xcp5-j5fj-3xp6.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2066
=> [GHSA-xcp5-j5fj-3xp6] Plaintext Storage of a Password in Jenkins EasyQA Plugin

advisories/github-reviewed/2022/06/GHSA-7495-24mx-hph2/GHSA-7495-24mx-hph2.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2276
=> [GHSA-7495-24mx-hph2] Missing permission check in Jenkins Convertigo Mobile Platform Plugin

advisories/github-reviewed/2022/06/GHSA-24h8-cpqm-qmf3/GHSA-24h8-cpqm-qmf3.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2276
=> [GHSA-24h8-cpqm-qmf3] Cross-Site Request Forgery in Jenkins Convertigo Mobile Platform Plugin

advisories/github-reviewed/2022/06/GHSA-c8mf-mc3f-2wvc/GHSA-c8mf-mc3f-2wvc.json
**Updates**
- CVSS
- Description
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2064
=> [GHSA-c8mf-mc3f-2wvc] Plaintext Storage of a Password in Jenkins Convertigo Mobile Platform Plugin 

advisories/github-reviewed/2022/06/GHSA-88r9-hfj2-54hv/GHSA-88r9-hfj2-54hv.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS score according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2784
=> [GHSA-88r9-hfj2-54hv] Cross-site Scripting in Jenkins Stash Branch Parameter Plugin

advisories/github-reviewed/2022/06/GHSA-438w-rjj9-5fjf/GHSA-438w-rjj9-5fjf.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
=> [GHSA-438w-rjj9-5fjf] Cross-site Scripting in Jenkins Repository Connector Plugin

advisories/github-reviewed/2022/06/GHSA-fcqr-gh8w-wm8f/GHSA-fcqr-gh8w-wm8f.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
=> [GHSA-fcqr-gh8w-wm8f] Cross-site Scripting in Jenkins Readonly Parameter Plugin

advisories/github-reviewed/2022/09/GHSA-f2j5-w76m-3rqh/GHSA-f2j5-w76m-3rqh.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-09-21/#SECURITY-2821
=> [GHSA-f2j5-w76m-3rqh] Jenkins Anchore Container Image Scanner Plugin vulnerable to cross site scripting

advisories/github-reviewed/2022/06/GHSA-6882-385p-hhhw/GHSA-6882-385p-hhhw.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
=> [GHSA-6882-385p-hhhw] Cross-site Scripting in Jenkins ontrack Jenkins Plugin

advisories/github-reviewed/2022/06/GHSA-5247-whvj-83qw/GHSA-5247-whvj-83qw.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
=> [GHSA-5247-whvj-83qw] Cross-site Scripting in Jenkins Maven Metadata Plugin

advisories/github-reviewed/2022/06/GHSA-6923-546p-6rrc/GHSA-6923-546p-6rrc.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
=> [GHSA-6923-546p-6rrc] Cross-site Scripting in Jenkins Image Tag Parameter Plugin

advisories/github-reviewed/2022/06/GHSA-x95w-qf3m-pqpx/GHSA-x95w-qf3m-pqpx.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS score according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2784
=> [GHSA-x95w-qf3m-pqpx] Cross-site Scripting in Jenkins Filesystem List Parameter Plugin

advisories/github-reviewed/2022/06/GHSA-5hh2-f4h9-446g/GHSA-5hh2-f4h9-446g.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS score according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2784
=> [GHSA-5hh2-f4h9-446g] Cross-site Scripting in Jenkins Date Parameter Plugin

advisories/github-reviewed/2022/06/GHSA-hc44-p2qq-cfm9/GHSA-hc44-p2qq-cfm9.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
=> [GHSA-hc44-p2qq-cfm9] Cross-site Scripting in Jenkins CRX Content Package Deployer Plugin

advisories/github-reviewed/2022/06/GHSA-65r6-w7vr-c75r/GHSA-65r6-w7vr-c75r.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
=> [GHSA-65r6-w7vr-c75r] Cross-site Scripting in Jenkins Agent Server Parameter Plugin

advisories/github-reviewed/2022/06/GHSA-h642-5h74-3x9c/GHSA-h642-5h74-3x9c.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2768
=> [GHSA-h642-5h74-3x9c] Cross-site Scripting in Jenkins Nested View Plugin

advisories/github-reviewed/2022/06/GHSA-298j-9q4w-6rm4/GHSA-298j-9q4w-6rm4.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Fill in fixed version according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2549
=> [GHSA-298j-9q4w-6rm4] Protection Mechanism Failure in Jenkins xUnit Plugin

advisories/github-reviewed/2022/06/GHSA-xxhf-xq6v-c8mj/GHSA-xxhf-xq6v-c8mj.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2794
=> [GHSA-xxhf-xq6v-c8mj] Missing Authorization in Jenkins Embeddable Build Status Plugin

advisories/github-reviewed/2022/06/GHSA-93mx-2vf9-28c4/GHSA-93mx-2vf9-28c4.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2792
=> [GHSA-93mx-2vf9-28c4] Path Traversal in Jenkins Embeddable Build Status Plugin

advisories/github-reviewed/2022/06/GHSA-39r3-h8q6-2phq/GHSA-39r3-h8q6-2phq.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2567
=> [GHSA-39r3-h8q6-2phq] Cross site scripting in Jenkins Embeddable Build Status Plugin

advisories/github-reviewed/2022/06/GHSA-29q6-p2cg-4v23/GHSA-29q6-p2cg-4v23.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Fill in fixed version according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2705
=> [GHSA-29q6-p2cg-4v23] Path Traversal in Jenkins Pipeline: Input Step Plugin

advisories/github-reviewed/2022/06/GHSA-64mj-3p92-589v/GHSA-64mj-3p92-589v.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Fill in fixed version according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2760
=> [GHSA-64mj-3p92-589v] Cross-site Scripting in Jenkins JUnit Plugin

advisories/github-reviewed/2021/08/GHSA-wcg3-cvx6-7396/GHSA-wcg3-cvx6-7396.json
**Updates**
- Description
**Comments**
Fix Markdown formatting
=> [GHSA-wcg3-cvx6-7396] Segmentation fault in time

advisories/github-reviewed/2022/07/GHSA-w257-f7qj-4vrq/GHSA-w257-f7qj-4vrq.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-1939
=> [GHSA-w257-f7qj-4vrq] Cross-site Scripting in Jenkins eXtreme Feedback Panel Plugin

advisories/github-reviewed/2022/07/GHSA-j2gv-q44j-xm42/GHSA-j2gv-q44j-xm42.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-1118
=> [GHSA-j2gv-q44j-xm42] Cross site scripting in Jenkins build-metrics Plugin

advisories/github-reviewed/2022/07/GHSA-hpf7-mmqw-g6vq/GHSA-hpf7-mmqw-g6vq.json
**Updates**
- CVSS
- Severity
**Comments**
This vulnerability has been fixed and released in 2.1.11, https://github.com/jenkinsci/plot-plugin/releases/tag/plot-2.1.11
=> [GHSA-hpf7-mmqw-g6vq] Cross-site Scripting in Jenkins Plot Plugin

advisories/github-reviewed/2022/07/GHSA-8hv7-4vfc-w8pg/GHSA-8hv7-4vfc-w8pg.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2788
=> [GHSA-8hv7-4vfc-w8pg] Cross-site Scripting in Jenkins TestNG Results Plugin

advisories/github-reviewed/2022/07/GHSA-qq85-8g89-r5rc/GHSA-qq85-8g89-r5rc.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2657
=> [GHSA-qq85-8g89-r5rc] Cross-Site Request Forgery in Jenkins Request Rename Or Delete Plugin

advisories/github-reviewed/2022/07/GHSA-3q7f-w8fr-368v/GHSA-3q7f-w8fr-368v.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2658
=> [GHSA-3q7f-w8fr-368v] Cross-Site Request Forgery in Jenkins XPath Configuration Viewer Plugin

advisories/github-reviewed/2022/07/GHSA-wppp-xqfv-6cm7/GHSA-wppp-xqfv-6cm7.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2055
=> [GHSA-wppp-xqfv-6cm7] Insufficiently Protected Credentials in Jenkins Cisco Spark Plugin

advisories/github-reviewed/2022/07/GHSA-h5h5-m2mc-j2pv/GHSA-h5h5-m2mc-j2pv.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2073
=> [GHSA-h5h5-m2mc-j2pv] Plaintext Storage of a Password in Jenkins Elasticsearch Query Plugin

advisories/github-reviewed/2022/07/GHSA-gvmr-mp5q-9wvw/GHSA-gvmr-mp5q-9wvw.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2160
=> [GHSA-gvmr-mp5q-9wvw] Plaintext Storage of a Password in Jenkins Skype notifier Plugin

advisories/github-reviewed/2022/07/GHSA-pgp9-x83g-v8x8/GHSA-pgp9-x83g-v8x8.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2088
=> [GHSA-pgp9-x83g-v8x8] Plaintext Storage of a Password in Jenkins RocketChat Notifier Plugin

advisories/github-reviewed/2022/07/GHSA-7298-w54j-q7wm/GHSA-7298-w54j-q7wm.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2056
=> [GHSA-7298-w54j-q7wm] Cleartext Storage of Sensitive Information in Jenkins Build Notifications Plugin

advisories/github-reviewed/2022/07/GHSA-v3r8-6vfj-pppf/GHSA-v3r8-6vfj-pppf.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2056
=> [GHSA-v3r8-6vfj-pppf] Plaintext Storage of a Password in Jenkins Build Notifications Plugin

advisories/github-reviewed/2022/09/GHSA-j7xv-fc46-hgpg/GHSA-j7xv-fc46-hgpg.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Adjust CVSS scoring according to https://www.jenkins.io/security/advisory/2022-09-21/#SECURITY-2243
=> [GHSA-j7xv-fc46-hgpg] Jenkins BigPanda Notifier Plugin stores BigPanda API key unencrypted

advisories/github-reviewed/2022/07/GHSA-cp6q-836q-gmj3/GHSA-cp6q-836q-gmj3.json
**Updates**
- CVSS
- Description
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2061
=> [GHSA-cp6q-836q-gmj3] Cross-Site Request Forgery in Jenkins Failed Job Deactivator Plugin

advisories/github-reviewed/2022/07/GHSA-57f2-52wj-7vj6/GHSA-57f2-52wj-7vj6.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update advisory details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-2629
=> [GHSA-57f2-52wj-7vj6] Jenkins Compuware ISPW Operations Plugin before 1.0.9 vulnerable to protection mechanism failure

advisories/github-reviewed/2022/07/GHSA-6xf5-c3cx-67pv/GHSA-6xf5-c3cx-67pv.json
**Updates**
- CVSS
- Severity
- Summary
**Comments**
Update advisory details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-2413
=> [GHSA-6xf5-c3cx-67pv] Jenkins CLIF Performance Testing Plugin allows attackers to replace arbitrary files with other content

advisories/github-reviewed/2022/09/GHSA-cpm5-cqr9-7p79/GHSA-cpm5-cqr9-7p79.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Adjust CVSS scoring according to https://www.jenkins.io/security/advisory/2022-09-21/#SECURITY-2243
=> [GHSA-cpm5-cqr9-7p79] Jenkins BigPanda Notifier Plugin Missing Password Field Masking

advisories/github-reviewed/2022/09/GHSA-6cvr-rvpm-9wx4/GHSA-6cvr-rvpm-9wx4.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Adjust CVSS scoring according to https://www.jenkins.io/security/advisory/2022-09-21/#SECURITY-2708
=> [GHSA-6cvr-rvpm-9wx4] Jenkins SCM HttpClient Plugin vulnerable to Cross-Site Request Forgery

advisories/github-reviewed/2022/07/GHSA-6xhf-xx3j-75f5/GHSA-6xhf-xx3j-75f5.json
**Updates**
- Description
**Comments**
Add sourcecode URL
=> [GHSA-6xhf-xx3j-75f5] Incorrect Authorization in Jenkins requests-plugin

advisories/github-reviewed/2022/07/GHSA-2v6r-jf2g-j5q5/GHSA-2v6r-jf2g-j5q5.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2332
=> [GHSA-2v6r-jf2g-j5q5] Cross-site Scripting in Jenkins Rich Text Publisher Plugin

advisories/github-reviewed/2022/07/GHSA-hqmp-vxj7-5wpq/GHSA-hqmp-vxj7-5wpq.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2165
=> [GHSA-hqmp-vxj7-5wpq] Cross-site Scripting in Jenkins Validating Email Parameter Plugin

advisories/github-reviewed/2022/07/GHSA-hv54-cc8f-42jq/GHSA-hv54-cc8f-42jq.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2000
=> [GHSA-hv54-cc8f-42jq] Cross-Site Request Forgery in Jenkins Recipe Plugin

advisories/github-reviewed/2022/07/GHSA-rm23-6mwv-8q9q/GHSA-rm23-6mwv-8q9q.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2000
=> [GHSA-rm23-6mwv-8q9q] XML External Entity Reference in Jenkins Recipe Plugin

advisories/github-reviewed/2022/07/GHSA-j33r-cgm6-pv48/GHSA-j33r-cgm6-pv48.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2000
=> [GHSA-j33r-cgm6-pv48] Missing Authorization in Jenkins Recipe Plugin

advisories/github-reviewed/2022/07/GHSA-7rrx-375m-j6cr/GHSA-7rrx-375m-j6cr.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2799
=> [GHSA-7rrx-375m-j6cr] Cross-site Scripting in Jenkins Deployment Dashboard Plugin

advisories/github-reviewed/2022/07/GHSA-x4g7-5xrm-5wmq/GHSA-x4g7-5xrm-5wmq.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2798%20(2)
=> [GHSA-x4g7-5xrm-5wmq] Cross-Site Request Forgery in Jenkins Deployment Dashboard Plugin

advisories/github-reviewed/2022/07/GHSA-qhmj-29vh-8mjm/GHSA-qhmj-29vh-8mjm.json
**Updates**
**Comments**
Fill in source code field
=> [GHSA-qhmj-29vh-8mjm] Incorrect Authorization in Jenkins Request Rename Or Delete Plugin

advisories/github-reviewed/2022/05/GHSA-98gq-6hxg-52r6/GHSA-98gq-6hxg-52r6.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-1889
=> [GHSA-98gq-6hxg-52r6] Improper Neutralization of Input During Web Page Generation in Jenkins

advisories/github-reviewed/2022/05/GHSA-wv63-gwr9-5c55/GHSA-wv63-gwr9-5c55.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-2035
=> [GHSA-wv63-gwr9-5c55] Improper Neutralization of Input During Web Page Generation in Jenkins

advisories/github-reviewed/2022/05/GHSA-mj7q-cmf3-mg7h/GHSA-mj7q-cmf3-mg7h.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-2171
=> [GHSA-mj7q-cmf3-mg7h] Improper Neutralization of Input During Web Page Generation in Jenkins

advisories/github-reviewed/2022/05/GHSA-qv6f-rcv6-6q3x/GHSA-qv6f-rcv6-6q3x.json
**Updates**
- Description
- Summary
**Comments**
Disclose more details according to https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-1923
=> [GHSA-qv6f-rcv6-6q3x] Deserialization of Untrusted Data in Jenkins

advisories/github-reviewed/2022/05/GHSA-vpjm-58cw-r8q5/GHSA-vpjm-58cw-r8q5.json
**Updates**
- Description
- Summary
**Comments**
Disclose more details according to https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-1452
=> [GHSA-vpjm-58cw-r8q5] Improper Link Resolution Before File Access in Jenkins

advisories/github-reviewed/2022/05/GHSA-pxgq-gqr9-5gwx/GHSA-pxgq-gqr9-5gwx.json
**Updates**
- Description
- Summary
**Comments**
Disclose more details according to https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-2021
=> [GHSA-pxgq-gqr9-5gwx] Improper Input Validation in Jenkins

advisories/github-reviewed/2022/05/GHSA-f585-9fw3-rj2m/GHSA-f585-9fw3-rj2m.json
**Updates**
- Description
- Summary
**Comments**
Fill in more details according to https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-2023
=> [GHSA-f585-9fw3-rj2m] Improper Input Validation in Jenkins

advisories/github-reviewed/2022/05/GHSA-cxqw-vjcr-gp5g/GHSA-cxqw-vjcr-gp5g.json
**Updates**
- Description
- Summary
**Comments**
Disclose more details according to https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-2025
=> [GHSA-cxqw-vjcr-gp5g] Allocation of Resources Without Limits or Throttling in Jenkins

advisories/github-reviewed/2022/05/GHSA-4625-q52w-39cx/GHSA-4625-q52w-39cx.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring and details according to https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-2047
=> [GHSA-4625-q52w-39cx] Incorrect Authorization in Jenkins

advisories/github-reviewed/2022/05/GHSA-qxp6-27gw-99cj/GHSA-qxp6-27gw-99cj.json
**Updates**
- Description
**Comments**
Fill in more details according to https://www.jenkins.io/security/advisory/2021-01-26/#jenkins-security-advisory-2021-01-26
=> [GHSA-qxp6-27gw-99cj] Time-of-check Time-of-use (TOCTOU) Race Condition in Jenkins

advisories/github-reviewed/2021/06/GHSA-4ffq-6g62-j4v4/GHSA-4ffq-6g62-j4v4.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2021-02-24/#SECURITY-2188%20(2)
=> [GHSA-4ffq-6g62-j4v4] Cross-Site Request Forgery in the Jenkins Claim plugin

advisories/github-reviewed/2022/05/GHSA-pvwx-3jx5-24r2/GHSA-pvwx-3jx5-24r2.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2021-04-07/#SECURITY-1721
=> [GHSA-pvwx-3jx5-24r2] Improper Input Validation in Jenkins

advisories/github-reviewed/2022/05/GHSA-w2hv-rcqr-2h7r/GHSA-w2hv-rcqr-2h7r.json
**Updates**
- Description
- Summary
**Comments**
Correct versions affected according https://www.jenkins.io/security/advisory/2021-04-07/#SECURITY-1871
=> [GHSA-w2hv-rcqr-2h7r] mproper Handling of Inconsistent Structural Elements in Jenkins

advisories/github-reviewed/2022/01/GHSA-p479-rwhp-rwjx/GHSA-p479-rwhp-rwjx.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2021-06-16/#SECURITY-2224
=> [GHSA-p479-rwhp-rwjx] Cross-site scripting in Jenkins Scriptler Plugin

advisories/github-reviewed/2022/01/GHSA-5c6c-w4c4-vgvx/GHSA-5c6c-w4c4-vgvx.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2021-06-16/#SECURITY-2390
=> [GHSA-5c6c-w4c4-vgvx] Cross-site scripting in Jenkins Scriptler Plugin

advisories/github-reviewed/2021/06/GHSA-8h77-3xwr-hqhh/GHSA-8h77-3xwr-hqhh.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2021-06-10/#SECURITY-2367
=> [GHSA-8h77-3xwr-hqhh] Cross-site scripting in Jenkins Kiuwan Plugin

advisories/github-reviewed/2022/05/GHSA-p674-hh8x-rv5h/GHSA-p674-hh8x-rv5h.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2021-05-25/#SECURITY-2340
=> [GHSA-p674-hh8x-rv5h] XML external entity vulnerability in Jenkins Nuget Plugin

advisories/github-reviewed/2022/11/GHSA-f3gj-hvv4-f57v/GHSA-f3gj-hvv4-f57v.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2921
=> [GHSA-f3gj-hvv4-f57v] XML External Entity Reference in Jenkins CCCC Plugin

advisories/github-reviewed/2021/06/GHSA-gchq-9r68-6jwv/GHSA-gchq-9r68-6jwv.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2021-05-11/#SECURITY-2349
=> [GHSA-gchq-9r68-6jwv] Cross-Site Request Forgery in Jenkins Credentials Plugin

advisories/github-reviewed/2021/06/GHSA-jwhm-9cjm-4493/GHSA-jwhm-9cjm-4493.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2021-05-11/#SECURITY-2233
=> [GHSA-jwhm-9cjm-4493] Cross-site Scripting in Jenkins Dashboard View Plugin

advisories/github-reviewed/2021/06/GHSA-rrvg-2c69-p9rf/GHSA-rrvg-2c69-p9rf.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2021-05-11/#SECURITY-2251%20(1)
=> [GHSA-rrvg-2c69-p9rf] Cross-Site Request Forgery in Jenkins Xray 

advisories/github-reviewed/2021/06/GHSA-h6qv-f5gf-8gcf/GHSA-h6qv-f5gf-8gcf.json
**Updates**
- Description
**Comments**
Update versions affected according to https://www.jenkins.io/security/advisory/2021-05-11/#SECURITY-2327
=> [GHSA-h6qv-f5gf-8gcf] Missing Authorization in Jenkins P4 plugin

advisories/github-reviewed/2022/03/GHSA-3rj3-qp2j-4fj2/GHSA-3rj3-qp2j-4fj2.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2021-05-11/#SECURITY-2327
=> [GHSA-3rj3-qp2j-4fj2] Cross-Site Request Forgery in Jenkins P4 Plugin

advisories/github-reviewed/2021/07/GHSA-hxxp-6546-wv6r/GHSA-hxxp-6546-wv6r.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2021-06-30/#SECURITY-2329
=> [GHSA-hxxp-6546-wv6r] Improper Restriction of XML External Entity Reference

advisories/github-reviewed/2022/11/GHSA-298r-5c48-7q2r/GHSA-298r-5c48-7q2r.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2888
=> [GHSA-298r-5c48-7q2r] Jenkins JUnit Plugin subject to Cross-site Scripting via URL conversion

advisories/github-reviewed/2022/11/GHSA-3g9q-cmgv-g4p6/GHSA-3g9q-cmgv-g4p6.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Fill in fixed version according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2949
=> [GHSA-3g9q-cmgv-g4p6] Path Traversal in Jenkins Pipeline Utility Steps Plugin

advisories/github-reviewed/2022/11/GHSA-h8hf-hxx6-5g6v/GHSA-h8hf-hxx6-5g6v.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Fill in fixed versions according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2946
=> [GHSA-h8hf-hxx6-5g6v] Cross-site Scripting in Jenkins Naginator Plugin

advisories/github-reviewed/2022/11/GHSA-w2j3-pq63-339w/GHSA-w2j3-pq63-339w.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Fill in versions fixed according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2804
=> [GHSA-w2j3-pq63-339w] Incorrect Authorization in Jenkins Support Core Plugin

advisories/github-reviewed/2022/11/GHSA-x2w2-5552-fjv6/GHSA-x2w2-5552-fjv6.json
**Updates**
- CVSS
- Description
**Comments**
Fill in versions fixed according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2912
=> [GHSA-x2w2-5552-fjv6] Plaintext Storage of a Password in Jenkins NS-ND Integration Performance Publisher Plugin

advisories/github-reviewed/2022/11/GHSA-3vwm-fc87-mq6h/GHSA-3vwm-fc87-mq6h.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Fill in versions fixed according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2910%20(1)
=> [GHSA-3vwm-fc87-mq6h] Improper Certificate Validation in Jenkins NS-ND Integration Performance Publisher Plugin

advisories/github-reviewed/2022/11/GHSA-j923-26c2-qq9p/GHSA-j923-26c2-qq9p.json
**Updates**
- CVSS
- Severity
**Comments**
Correct versions affected according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2802
=> [GHSA-j923-26c2-qq9p] Jenkins BART Plugin vulnerable to cross-site scripting (XSS)

advisories/github-reviewed/2022/11/GHSA-9pqq-h9qv-28fp/GHSA-9pqq-h9qv-28fp.json
**Updates**
**Comments**
Correct versions affected according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2842
=> [GHSA-9pqq-h9qv-28fp] Jenkins Config Rotator Plugin vulnerable to path traversal

advisories/github-reviewed/2022/11/GHSA-h4wx-78p9-fwxw/GHSA-h4wx-78p9-fwxw.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2927
=> [GHSA-h4wx-78p9-fwxw] XML External Entity Reference in Jenkins SourceMonitor Plugin

advisories/github-reviewed/2022/11/GHSA-24hp-84jp-8wgm/GHSA-24hp-84jp-8wgm.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2938
=> [GHSA-24hp-84jp-8wgm] Cross-Site Request Forgery in Jenkins Cluster Statistics Plugin

advisories/github-reviewed/2022/11/GHSA-8538-25v4-25pg/GHSA-8538-25v4-25pg.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2941
=> [GHSA-8538-25v4-25pg] XML External Entity Reference in Jenkins JAPEX Plugin

advisories/github-reviewed/2022/11/GHSA-chcg-gh9p-96c5/GHSA-chcg-gh9p-96c5.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2947
=> [GHSA-chcg-gh9p-96c5] Jenkins Associated Files Plugin vulnerable to cross-site scripting (XSS)

advisories/github-reviewed/2020/01/GHSA-8wx2-9q48-vm9r/GHSA-8wx2-9q48-vm9r.json
**Updates**
**Comments**
Fixed the versions for to match the actual artifact versions on Maven Central.
=> [GHSA-8wx2-9q48-vm9r] RFD attack via Content-Disposition header sourced from request input by Spring MVC or Spring WebFlux Application

advisories/github-reviewed/2022/03/GHSA-36p3-wjmg-h94x/GHSA-36p3-wjmg-h94x.json
**Updates**
**Comments**
Fixed the versions for to match the actual artifact versions on Maven Central.
=> [GHSA-36p3-wjmg-h94x] Remote Code Execution in Spring Framework

advisories/github-reviewed/2022/10/GHSA-7vr5-72w7-q6jc/GHSA-7vr5-72w7-q6jc.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Correct CVSS scoring and affected products according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2824%20(1)
Given the nature and mitigation of this vulnerability, I added the other affected component too.
=> [GHSA-7vr5-72w7-q6jc] Jenkins Script Security Plugin sandbox bypass vulnerability

advisories/github-reviewed/2022/10/GHSA-27rf-8mjp-r363/GHSA-27rf-8mjp-r363.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Correct CVSS scoring and affected products according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2824%20(1)
Given the nature and mitigation of this vulnerability, I added the other affected component too.
=> [GHSA-27rf-8mjp-r363] Jenkins Script Security Plugin sandbox bypass vulnerability

advisories/github-reviewed/2022/10/GHSA-64r9-x74q-wxmh/GHSA-64r9-x74q-wxmh.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2881
=> [GHSA-64r9-x74q-wxmh] Jenkins Pipeline: Supporting APIs Plugin vulnerable to stored Cross-site Scripting

advisories/github-reviewed/2022/10/GHSA-2jxx-2x93-2q2f/GHSA-2jxx-2x93-2q2f.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2874
=> [GHSA-2jxx-2x93-2q2f] Jenkins Generic Webhook Trigger Plugin potentially allows attackers to use statistical methods to obtain valid webhook token

advisories/github-reviewed/2022/10/GHSA-5fvg-h778-jjjx/GHSA-5fvg-h778-jjjx.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2845%20(1)
=> [GHSA-5fvg-h778-jjjx] Jenkins Katalon Plugin Missing Authorization vulnerability

advisories/github-reviewed/2022/10/GHSA-hvcr-927w-qcvq/GHSA-hvcr-927w-qcvq.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2836
=> [GHSA-hvcr-927w-qcvq] Jenkins Contrast Continuous Application Security Plugin vulnerable to stored Cross-site Scripting

advisories/github-reviewed/2022/10/GHSA-2x49-wj38-78q9/GHSA-2x49-wj38-78q9.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2620
=> [GHSA-2x49-wj38-78q9] Jenkins Compuware Topaz Utilities Plugin vulnerable to Protection Mechanism Failure

advisories/github-reviewed/2022/10/GHSA-682j-2p53-xp5f/GHSA-682j-2p53-xp5f.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2622
=> [GHSA-682j-2p53-xp5f] Jenkins Compuware Source Code Download for Endevor, PDS, and ISPW Plugin vulnerable to Protection Mechanism Failure

advisories/github-reviewed/2022/10/GHSA-mfcw-83qg-4vw3/GHSA-mfcw-83qg-4vw3.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2627
=> [GHSA-mfcw-83qg-4vw3] Jenkins Compuware Xpediter Code Coverage Plugin vulnerable to Protection Mechanism Failure

advisories/github-reviewed/2022/10/GHSA-vf5v-6wjm-vr7v/GHSA-vf5v-6wjm-vr7v.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2797
=> [GHSA-vf5v-6wjm-vr7v] Jenkins Custom Checkbox Parameter Plugin vulnerable to stored Cross-site Scripting

advisories/github-reviewed/2022/10/GHSA-mf4p-wjrm-cmjp/GHSA-mf4p-wjrm-cmjp.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2480
=> [GHSA-mf4p-wjrm-cmjp] Jenkins S3 Explorer Plugin 1does not mask the AWS_SECRET_ACCESS_KEY form field

advisories/github-reviewed/2022/10/GHSA-xp3r-9wx8-q2mm/GHSA-xp3r-9wx8-q2mm.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2624
=> [GHSA-xp3r-9wx8-q2mm] Jenkins Compuware Topaz for Total Test Plugin vulnerable to Protection Mechanism Failure

advisories/github-reviewed/2022/05/GHSA-xqpp-26pp-2365/GHSA-xqpp-26pp-2365.json
**Updates**
**Comments**
fix typo in the package name.
=> [GHSA-xqpp-26pp-2365] XSS vulnerability in Jenkins Markdown Formatter Plugin

advisories/github-reviewed/2022/05/GHSA-58xm-mxjf-254g/GHSA-58xm-mxjf-254g.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
=> [GHSA-58xm-mxjf-254g] Missing Authorization in Jenkins

advisories/github-reviewed/2022/05/GHSA-4g38-hrm4-rg94/GHSA-4g38-hrm4-rg94.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
=> [GHSA-4g38-hrm4-rg94] Improper Limitation of a Pathname to a Restricted Directory in Jenkins

advisories/github-reviewed/2022/05/GHSA-3q84-vrvx-rfvf/GHSA-3q84-vrvx-rfvf.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
=> [GHSA-3q84-vrvx-rfvf] Missing Authorization in Jenkins

advisories/github-reviewed/2022/05/GHSA-m9hr-259f-2v23/GHSA-m9hr-259f-2v23.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
=> [GHSA-m9hr-259f-2v23] Missing Authorization in Jenkins

advisories/github-reviewed/2022/05/GHSA-j3cq-h6vh-gx7f/GHSA-j3cq-h6vh-gx7f.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
=> [GHSA-j3cq-h6vh-gx7f] Missing Authorization in Jenkins

advisories/github-reviewed/2022/05/GHSA-97c3-w9cr-6qc2/GHSA-97c3-w9cr-6qc2.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
=> [GHSA-97c3-w9cr-6qc2] Protection Mechanism Failure in Jenkins

advisories/github-reviewed/2022/05/GHSA-2c79-h2h5-g3fw/GHSA-2c79-h2h5-g3fw.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
=> [GHSA-2c79-h2h5-g3fw] Incorrect Authorization in Jenkins

advisories/github-reviewed/2022/05/GHSA-929w-q433-4h9x/GHSA-929w-q433-4h9x.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Provide full advisory disclosure according to https://www.jenkins.io/security/advisory/2021-11-04/#SECURITY-2455
=> [GHSA-929w-q433-4h9x] Improper Authorization in Jenkins

advisories/github-reviewed/2022/05/GHSA-pgj6-jmj5-wqfx/GHSA-pgj6-jmj5-wqfx.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Provide full advisory disclosure according to https://www.jenkins.io/security/advisory/2021-11-04/#SECURITY-2455
=> [GHSA-pgj6-jmj5-wqfx] Missing Authorization in Jenkins

advisories/github-reviewed/2022/05/GHSA-cvvm-4cr9-r436/GHSA-cvvm-4cr9-r436.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Provide full advisory disclosure according to https://www.jenkins.io/security/advisory/2021-11-04/#SECURITY-2455
=> [GHSA-cvvm-4cr9-r436] Missing Authorization in Jenkins

advisories/github-reviewed/2022/05/GHSA-c5r9-rx53-q3gf/GHSA-c5r9-rx53-q3gf.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2021-11-04/#SECURITY-2423
=> [GHSA-c5r9-rx53-q3gf] Protection Mechanism Failure in Jenkins

advisories/github-reviewed/2022/05/GHSA-cv2w-q8c3-xjv7/GHSA-cv2w-q8c3-xjv7.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2021-11-04/#SECURITY-2428
=> [GHSA-cv2w-q8c3-xjv7] Incomplete List of Disallowed Inputs in Jenkins

advisories/github-reviewed/2022/05/GHSA-m8r4-c7jm-w782/GHSA-m8r4-c7jm-w782.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update versions affected according to https://www.jenkins.io/security/advisory/2020-12-03/#SECURITY-1856
=> [GHSA-m8r4-c7jm-w782] Download of Code Without Integrity Check in Jenkins Plugin Installation Manager

advisories/github-reviewed/2022/05/GHSA-hvmc-7g2x-r3p9/GHSA-hvmc-7g2x-r3p9.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2020-08-12/#SECURITY-1955
=> [GHSA-hvmc-7g2x-r3p9] Improper Neutralization of Input During Web Page Generation in Jenkins

advisories/github-reviewed/2022/05/GHSA-9g4m-ffx6-c29g/GHSA-9g4m-ffx6-c29g.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2020-08-12/#SECURITY-1957
=> [GHSA-9g4m-ffx6-c29g] Improper Neutralization of Input During Web Page Generation in Jenkins

advisories/github-reviewed/2022/02/GHSA-rpj6-2q8r-98f8/GHSA-rpj6-2q8r-98f8.json
**Updates**
- Description
- Summary
**Comments**
Update description according to https://www.jenkins.io/security/advisory/2020-10-08/#SECURITY-1815, to reflect the Jenkins version this vulnerability is exploitable on.
=> [GHSA-rpj6-2q8r-98f8] Incorrect default pattern in Jenkins Audit Trail Plugin 

advisories/github-reviewed/2022/12/GHSA-65hj-9ppw-77xc/GHSA-65hj-9ppw-77xc.json
**Updates**
**Comments**
Fixed issue
=> [GHSA-65hj-9ppw-77xc] ff4j is vulnerable to Remote Code Execution (RCE)

advisories/github-reviewed/2022/05/GHSA-c735-g9f2-2mvp/GHSA-c735-g9f2-2mvp.json
**Updates**
- Description
**Comments**
Disclose more details according to https://www.jenkins.io/security/advisory/2020-03-25/#SECURITY-1774
=> [GHSA-c735-g9f2-2mvp] Cross-Site Request Forgery in Jenkins

advisories/github-reviewed/2022/05/GHSA-crg2-6xv3-qg5f/GHSA-crg2-6xv3-qg5f.json
**Updates**
- Description
**Comments**
Disclose more details according to https://www.jenkins.io/security/advisory/2020-03-25/#SECURITY-1793
=> [GHSA-crg2-6xv3-qg5f] Improper Neutralization of Input During Web Page Generation in Jenkins

advisories/github-reviewed/2022/12/GHSA-mjmj-j48q-9wg2/GHSA-mjmj-j48q-9wg2.json
**Updates**
**Comments**
The fix will be deployed in version 1.34:
https://bitbucket.org/snakeyaml/snakeyaml/issues/561/cve-2022-1471-vulnerability-in#comment-64634374
=> [GHSA-mjmj-j48q-9wg2] SnakeYaml Constructor Deserialization Remote Code Execution

advisories/github-reviewed/2022/12/GHSA-89w7-5q45-r53w/GHSA-89w7-5q45-r53w.json
**Updates**
**Comments**
Requesting to attribute and credit this vulnerability to GitHub user @lirantal, who discovered and reported the vulnerability to Snyk.
=> [GHSA-89w7-5q45-r53w] lite-server vulnerable to Denial of Service

advisories/github-reviewed/2022/12/GHSA-pppv-ch8p-rp2w/GHSA-pppv-ch8p-rp2w.json
**Updates**
**Comments**
Requesting to attribute and credit this vulnerability to GitHub user @lirantal, who discovered and reported the vulnerability to Snyk.
=> [GHSA-pppv-ch8p-rp2w] lite-dev-server vulnerable to Directory Traversal

advisories/github-reviewed/2022/12/GHSA-wcwm-c3mr-pxcr/GHSA-wcwm-c3mr-pxcr.json
**Updates**
**Comments**
Requesting to attribute and credit this vulnerability to GitHub user @lirantal, who discovered and reported the vulnerability to Snyk.
=> [GHSA-wcwm-c3mr-pxcr] easy-static-server vulnerable to Directory Traversal

advisories/github-reviewed/2022/05/GHSA-qgj4-rc8m-44mq/GHSA-qgj4-rc8m-44mq.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2020-07-15/#SECURITY-1868
=> [GHSA-qgj4-rc8m-44mq] Improper Neutralization of Input During Web Page Generation in Jenkins

advisories/github-reviewed/2022/05/GHSA-g4j6-m3m3-crw8/GHSA-g4j6-m3m3-crw8.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2020-07-15/#SECURITY-1901
=> [GHSA-g4j6-m3m3-crw8] Improper Neutralization of Input During Web Page Generation in Jenkins

advisories/github-reviewed/2022/05/GHSA-864v-5q2g-fr64/GHSA-864v-5q2g-fr64.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2020-07-15/#SECURITY-1902
=> [GHSA-864v-5q2g-fr64] Improper Neutralization of Input During Web Page Generation in Jenkins

advisories/github-reviewed/2022/05/GHSA-gfhj-524q-gcrm/GHSA-gfhj-524q-gcrm.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2020-07-15/#SECURITY-1945
=> [GHSA-gfhj-524q-gcrm] Improper Neutralization of Input During Web Page Generation in Jenkins

advisories/github-reviewed/2022/05/GHSA-h6qc-455m-7v6v/GHSA-h6qc-455m-7v6v.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2020-07-15/#SECURITY-1924
=> [GHSA-h6qc-455m-7v6v] Improper Neutralization of Input During Web Page Generation in Jenkins Matrix Project Plugin

advisories/github-reviewed/2022/05/GHSA-w43x-5f8f-686p/GHSA-w43x-5f8f-686p.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2020-07-15/#SECURITY-1925
=> [GHSA-w43x-5f8f-686p] Improper Neutralization of Input During Web Page Generation in Jenkins Matrix Project Plugin

advisories/github-reviewed/2022/05/GHSA-vr6v-wjfw-rxcr/GHSA-vr6v-wjfw-rxcr.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2020-07-15/#SECURITY-1909
=> [GHSA-vr6v-wjfw-rxcr] Improper Neutralization of Input During Web Page Generation in Jenkins Matrix Authorization Strategy Plugin

advisories/github-reviewed/2022/12/GHSA-9c47-m6qq-7p4h/GHSA-9c47-m6qq-7p4h.json
**Updates**
- Description
- References
**Comments**
Includes information about a backport for v1 and fixes a typo in the Mitigation section.
=> [GHSA-9c47-m6qq-7p4h] Prototype Pollution in JSON5 via Parse Method

advisories/github-reviewed/2022/12/GHSA-hcpj-qp55-gfph/GHSA-hcpj-qp55-gfph.json
**Updates**
- References
**Comments**
https://github.com/gitpython-developers/GitPython/releases/tag/3.1.30
https://github.com/gitpython-developers/GitPython/issues/1515
=> [GHSA-hcpj-qp55-gfph] GitPython vulnerable to Remote Code Execution due to improper user input validation

advisories/github-reviewed/2022/10/GHSA-w596-4wvx-j9j6/GHSA-w596-4wvx-j9j6.json
**Updates**
- Description
- Summary
**Comments**
Fixing spelling and trimming whitespace.
=> [GHSA-w596-4wvx-j9j6] ReDoS in py library when used with subversion 

advisories/github-reviewed/2022/02/GHSA-wqv3-8cm6-h6wg/GHSA-wqv3-8cm6-h6wg.json
**Updates**
**Comments**
adaptor k8s.io/kube-proxy go module version. https://pkg.go.dev/k8s.io/kube-proxy?tab=versions
=> [GHSA-wqv3-8cm6-h6wg] Improper Authentication in Kubernetes

advisories/github-reviewed/2022/11/GHSA-47fc-vmwq-366v/GHSA-47fc-vmwq-366v.json
**Updates**
**Comments**
Adding patched version 1.13.1
=> [GHSA-47fc-vmwq-366v] PyTorch vulnerable to arbitrary code execution

advisories/github-reviewed/2022/12/GHSA-4jv9-3563-23j3/GHSA-4jv9-3563-23j3.json
**Updates**
**Comments**
Add reference to patched version
=> [GHSA-4jv9-3563-23j3] Knex.js has a limited SQL injection vulnerability

advisories/github-reviewed/2023/01/GHSA-3xq5-wjfh-ppjc/GHSA-3xq5-wjfh-ppjc.json
**Updates**
**Comments**
Wrong luxon 1.x version, it is not 1.38.1 but 1.28.1. See https://www.npmjs.com/package/luxon?activeTab=versions
=> [GHSA-3xq5-wjfh-ppjc] Luxon Inefficient Regular Expression Complexity vulnerability

advisories/github-reviewed/2022/01/GHSA-p46c-w9m3-7qr2/GHSA-p46c-w9m3-7qr2.json
**Updates**
- References
**Comments**
Issue is fixed refer : https://github.com/sunrise-choir/flumedb-rs/pull/12
=> [GHSA-p46c-w9m3-7qr2] Use of Uninitialized Resource in flumedb.

advisories/github-reviewed/2023/01/GHSA-9vvw-cc9w-f27h/GHSA-9vvw-cc9w-f27h.json
**Updates**
**Comments**
debug 2.6.9 has also been patched:
- see commit https://github.com/debug-js/debug/commit/f53962e944a87e6ca9bb622a2a12dffc22a9bb5a
- see release https://github.com/debug-js/debug/releases/tag/2.6.9
=> [GHSA-9vvw-cc9w-f27h] debug Inefficient Regular Expression Complexity vulnerability

advisories/github-reviewed/2022/12/GHSA-v3c5-jqr6-7qm8/GHSA-v3c5-jqr6-7qm8.json
**Updates**
**Comments**
Fixed with https://github.com/PythonCharmers/python-future/commit/c91d70b34ef0402aef3e9d04364ba98509dca76f
=> [GHSA-v3c5-jqr6-7qm8] Python Charmers Future denial of service vulnerability

advisories/github-reviewed/2019/12/GHSA-qhrx-hcm6-pmrw/GHSA-qhrx-hcm6-pmrw.json
**Updates**
**Comments**
Link to source code location
=> [GHSA-qhrx-hcm6-pmrw] Unsafe deserialization in SmtpTransport in CakePHP

advisories/github-reviewed/2021/08/GHSA-mc36-5m36-hjh5/GHSA-mc36-5m36-hjh5.json
**Updates**
- References
**Comments**
Fix is been provided check fix commit
=> [GHSA-mc36-5m36-hjh5] Data races in slock

advisories/github-reviewed/2021/08/GHSA-3837-87vh-xq3w/GHSA-3837-87vh-xq3w.json
**Updates**
- References
**Comments**
Fix is been made 
Refer : https://github.com/purpleposeidon/v9/commit/18847c50e5d36561cc91c996c3539ddb1eacf6c7
https://github.com/purpleposeidon/v9/issues/1
=> [GHSA-3837-87vh-xq3w] Data race in v9

advisories/github-reviewed/2023/01/GHSA-hq7p-j377-6v63/GHSA-hq7p-j377-6v63.json
**Updates**
- References
**Comments**
Patch for fix in Rails 7
=> [GHSA-hq7p-j377-6v63] SQL Injection Vulnerability via ActiveRecord comments

advisories/github-reviewed/2021/08/GHSA-w9r2-qrpm-4rmj/GHSA-w9r2-qrpm-4rmj.json
**Updates**
- References
**Comments**
Fix has been provided
=> [GHSA-w9r2-qrpm-4rmj] Data race in disrustor

advisories/github-reviewed/2023/01/GHSA-6g8q-qfpv-57wp/GHSA-6g8q-qfpv-57wp.json
**Updates**
- Summary
**Comments**
The new title is more specific and to the point what is actually vulnerable in this framework.
It's also the same title as used by the original reporter, @markstory,  who is the core dev of the framework.
=> [GHSA-6g8q-qfpv-57wp] CakePHP vulnerable to SQL injection

advisories/github-reviewed/2023/01/GHSA-2pj2-gchf-wmw7/GHSA-2pj2-gchf-wmw7.json
**Updates**
**Comments**
Added patched version v2.11.3 (https://github.com/srikanth-lingala/zip4j/releases/tag/v2.11.3)
=> [GHSA-2pj2-gchf-wmw7] Zip4j Origin Validation Error

advisories/github-reviewed/2021/01/GHSA-w7jx-j77m-wp65/GHSA-w7jx-j77m-wp65.json
**Updates**
**Comments**
According to this source, composer and nuget are also vulnerable. 
https://github.com/tinymce/tinymce/security/advisories/GHSA-w7jx-j77m-wp65
=> [GHSA-w7jx-j77m-wp65] Cross-site scripting vulnerability in TinyMCE

advisories/github-reviewed/2022/04/GHSA-qggc-pj29-j27m/GHSA-qggc-pj29-j27m.json
**Updates**
**Comments**
Typo in patch version for 6.2.x
=> [GHSA-qggc-pj29-j27m] Improper Privilege Management in Mattermost

advisories/github-reviewed/2021/09/GHSA-rp65-9cf3-cjxr/GHSA-rp65-9cf3-cjxr.json
**Updates**
- CVSS
**Comments**
(CWE-1333)
=> [GHSA-rp65-9cf3-cjxr] Inefficient Regular Expression Complexity in nth-check

advisories/github-reviewed/2022/05/GHSA-3gv7-3h64-78cm/GHSA-3gv7-3h64-78cm.json
**Updates**
**Comments**
Version typo for 7.x patch
=> [GHSA-3gv7-3h64-78cm] Exposure of Sensitive Information to an Unauthorized Actor in Apache Tomcat

advisories/github-reviewed/2022/02/GHSA-p5pg-wm9q-8v6r/GHSA-p5pg-wm9q-8v6r.json
**Updates**
**Comments**
https://mvnrepository.com/artifact/com.drewnoakes/metadata-extractor
=> [GHSA-p5pg-wm9q-8v6r] Improper Handling of Exceptional Conditions inn metadata-extractor

advisories/github-reviewed/2023/01/GHSA-qrg7-hfx7-95c5/GHSA-qrg7-hfx7-95c5.json
**Updates**
**Comments**
fix package name
=> [GHSA-qrg7-hfx7-95c5] Command injection in Git package in Wrangler

advisories/github-reviewed/2021/10/GHSA-97x5-cc53-cv4v/GHSA-97x5-cc53-cv4v.json
**Updates**
**Comments**
As suggested in the changelog https://froala.com/wysiwyg-editor/changelog/#4.0.11
Original comment:
https://github.com/froala/wysiwyg-editor/issues/3880#issuecomment-1170372130
=> [GHSA-97x5-cc53-cv4v] Cross site scripting in froala-editor

advisories/github-reviewed/2022/05/GHSA-v67x-gpg7-mwv3/GHSA-v67x-gpg7-mwv3.json
**Updates**
- References
**Comments**
Fix is been applied 
Refer :
https://github.com/jenkinsci/kubernetes-plugin/commit/43a1d15b0875ae89ae16f2a2bfdd44ffd1e5f46d
https://www.jenkins.io/security/advisory/2018-06-04/#SECURITY-883
=> [GHSA-v67x-gpg7-mwv3] Exposure of Sensitive Information in Jenkins Kubernetes Plugin

advisories/github-reviewed/2021/08/GHSA-cmhx-cq75-c4mj/GHSA-cmhx-cq75-c4mj.json
Updates
- Severity, CVSS vector
=> [GHSA-cmhx-cq75-c4mj] missing CVSS vector, adding missing vector based on NVD data

advisories/github-reviewed/2022/05/GHSA-qwqv-j7jr-4hp6/GHSA-qwqv-j7jr-4hp6.json
**Updates**
**Comments**
https://github.com/savon-noir/python-libnmap/releases/tag/v0.7.3
=> [GHSA-qwqv-j7jr-4hp6] Argument injection in python-libnmap

advisories/github-reviewed/2023/01/GHSA-jqh6-9574-5x22/GHSA-jqh6-9574-5x22.json
**Updates**
- References
**Comments**
Adds the fix commit link
=> [GHSA-jqh6-9574-5x22]  MITM based Zip Slip in `ca.uhn.hapi.fhir:org.hl7.fhir.core`

advisories/github-reviewed/2023/03/GHSA-hm7p-r324-hhf3/GHSA-hm7p-r324-hhf3.json
**Updates**
- Description
**Comments**
v2 is not affected, see author statement https://github.com/phpseclib/phpseclib/commit/6298d1cd55c3ffa44533bd41906caec246b60440#commitcomment-103226722
=> [GHSA-hm7p-r324-hhf3] phpseclib Infinite Loop vulnerability

advisories/github-reviewed/2022/03/GHSA-m6gg-86c6-gfr9/GHSA-m6gg-86c6-gfr9.json
**Updates**
- Summary
**Comments**
This issue affects Kibana, not Elasticsearch.
=> [GHSA-m6gg-86c6-gfr9] Cross-site Scripting in elasticsearch

advisories/github-reviewed/2023/03/GHSA-qcrj-6ffc-v7hq/GHSA-qcrj-6ffc-v7hq.json
**Updates**
**Comments**
https://github.com/craftcms/cms/commit/ea7f660890736d4d0a2274a3bc7c27142efae873
=> [GHSA-qcrj-6ffc-v7hq] Craft CMS Stored Ctos-site Scripting Injection Vulnerability

advisories/github-reviewed/2022/02/GHSA-8c9h-4q7g-fp7h/GHSA-8c9h-4q7g-fp7h.json
**Updates**
- Description
**Comments**
Make clear that this is a disputed CVE by copying the description that NIST / MITRE use since 10/31/2022 5:15:11
see change history on https://nvd.nist.gov/vuln/detail/CVE-2022-24198
=> [GHSA-8c9h-4q7g-fp7h] Out-of-bounds Read in iText

advisories/github-reviewed/2023/03/GHSA-jh36-q97c-9928/GHSA-jh36-q97c-9928.json
**Updates**
**Comments**
fix package repository name
=> [GHSA-jh36-q97c-9928] Kubernetes vulnerable to validation bypass

advisories/github-reviewed/2022/11/GHSA-4r6j-fwcx-94cf/GHSA-4r6j-fwcx-94cf.json
**Updates**
**Comments**
https://research.jfrog.com/vulnerabilities/snowflake-connector-python-redos-xray-257185/
Shows "Fixed in 2.8.2"
=> [GHSA-4r6j-fwcx-94cf] snowflake-connector-python is vulnerable to Regular Expression Denial of Service (ReDoS)

advisories/github-reviewed/2022/05/GHSA-4rjr-3gj2-5crq/GHSA-4rjr-3gj2-5crq.json
**Updates**
**Comments**
wrong package name
=> [GHSA-4rjr-3gj2-5crq] Exposure of Sensitive Information to an Unauthorized Actor in MongoDB Rust Driver

advisories/github-reviewed/2022/01/GHSA-w428-f65r-h4q2/GHSA-w428-f65r-h4q2.json
**Updates**
**Comments**
wrong pkg name
=> [GHSA-w428-f65r-h4q2] Deserialization of Untrusted Data in rust-cpuid

advisories/github-reviewed/2019/06/GHSA-q22g-8fr4-qpj4/GHSA-q22g-8fr4-qpj4.json
https://github.com/jonschlinkert/remarkable/pull/335#issuecomment-515958379
=> GHSA-q22g-8fr4-qpj4: add fixed version

advisories/github-reviewed/2021/09/GHSA-jp7f-grcv-6mjf/GHSA-jp7f-grcv-6mjf.json
**Updates**
**Comments**
Corrected casing of package name to match the name in NuGet.
=> [GHSA-jp7f-grcv-6mjf] Partial path traversal in sharpcompress

advisories/github-reviewed/2019/09/GHSA-fxh6-w476-hgr4/GHSA-fxh6-w476-hgr4.json
**Updates**
**Comments**
Corrected casing of package name to match the name in NuGet.
=> [GHSA-fxh6-w476-hgr4] Directory Traversal in SharpCompress

advisories/github-reviewed/2021/12/GHSA-xmc8-26q4-qjhx/GHSA-xmc8-26q4-qjhx.json
**Updates**
**Comments**
Description says `This affects the package com.fasterxml.jackson.dataformat:jackson-dataformat-cbor from 0 and before 2.11.4`.
=> [GHSA-xmc8-26q4-qjhx] Denial of Service (DoS) in Jackson Dataformat CBOR

advisories/github-reviewed/2020/09/GHSA-8px5-63x9-5c7p/GHSA-8px5-63x9-5c7p.json
**Updates**
- Description
**Comments**
This entry needs to be updated to a newly assigned CVE that was requested for it as it didn't exist before: CVE-2018-25083 
(and note that a new entry got created https://github.com/advisories/GHSA-2w9p-xf5h-qwj3 but it should be marked as a duplicate, or removed to not confuse folks).
=> [GHSA-8px5-63x9-5c7p] Command Injection in pullit

advisories/github-reviewed/2021/09/GHSA-468q-v4jj-485h/GHSA-468q-v4jj-485h.json
**Updates**
- Description
- References
**Comments**
wrong pkg name
=> [GHSA-468q-v4jj-485h] Inefficient Regular Expression Complexity in taro

advisories/github-reviewed/2022/12/GHSA-642q-2q68-9j3p/GHSA-642q-2q68-9j3p.json
**Updates**
**Comments**
The fix is been applied 
Refer this : https://huntr.dev/bounties/404ce7dd-f345-4d98-ad80-c53ac74f4e5c/
=> [GHSA-642q-2q68-9j3p] usememos/memos Cross-Site Request Forgery vulnerability

advisories/github-reviewed/2021/09/GHSA-9gr3-7897-pp7m/GHSA-9gr3-7897-pp7m.json
**Updates**
- References
**Comments**
Adding the patch link for v11.1.1: https://github.com/vercel/next.js/commit/7afc97c5744b38bdf36aa7f87625f438224688aa
In this patch, the developer introduced CSP, which is typical for preventing XSS. Additionally, we can see a unit test with a response similar to the advisory description: "SVG with a script tag attempting XSS"
=> [GHSA-9gr3-7897-pp7m] XSS in Image Optimization API for Next.js

advisories/github-reviewed/2021/03/GHSA-g3rq-g295-4j3m/GHSA-g3rq-g295-4j3m.json
**Updates**
- References
**Comments**
Adding the patch link for v2.11.3: 
https://github.com/pallets/jinja/commit/15ef8f09b659f9100610583938005a7a10472d4d
This commit patch is the merge of the original pull (https://github.com/pallets/jinja/pull/1343).
=> [GHSA-g3rq-g295-4j3m] Regular Expression Denial of Service (ReDoS) in Jinja2

advisories/github-reviewed/2022/09/GHSA-xx9w-464f-7h6f/GHSA-xx9w-464f-7h6f.json
=> [GHSA-xx9w-464f-7h6f]  Harbor fails to validate the user permissions when updating a robot account

advisories/github-reviewed/2021/11/GHSA-8cvr-4rrf-f244/GHSA-8cvr-4rrf-f244.json
=> [GHSA-8cvr-4rrf-f244] Infinite open connection causes OctoRPKI to hang forever

advisories/github-reviewed/2022/09/GHSA-qv98-3369-g364/GHSA-qv98-3369-g364.json
=> [GHSA-qv98-3369-g364] KubeVirt vulnerable to arbitrary file read on host

advisories/github-reviewed/2022/09/GHSA-8c6p-v837-77f6/GHSA-8c6p-v837-77f6.json
=> [GHSA-8c6p-v837-77f6] Harbor fails to validate the user permissions when updating tag immutability policies

advisories/github-reviewed/2021/08/GHSA-qgm6-9472-pwq7/GHSA-qgm6-9472-pwq7.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: https://crates.io/crates/openssl-src/111.14.0+1.1.1j
=> [GHSA-qgm6-9472-pwq7] Integer Overflow in openssl-src

advisories/github-reviewed/2021/08/GHSA-pp74-39w2-v4w9/GHSA-pp74-39w2-v4w9.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: https://crates.io/crates/pleaser/0.4.0
=> [GHSA-pp74-39w2-v4w9] Permissions bypass in pleaser

advisories/github-reviewed/2022/03/GHSA-x3mh-jvjw-3xwx/GHSA-x3mh-jvjw-3xwx.json
=> [GHSA-x3mh-jvjw-3xwx] openssl-src's infinite loop in `BN_mod_sqrt()` reachable when parsing certificates

advisories/github-reviewed/2022/09/GHSA-jf8p-3vjh-pq94/GHSA-jf8p-3vjh-pq94.json
=> [GHSA-jf8p-3vjh-pq94] Harbor fails to validate the user permissions when viewing Webhook policies
