- advisories/github-reviewed/2022/01/GHSA-566m-qj78-rww5/GHSA-566m-qj78-rww5.json
**Updates**
The fix for the vulnerability was backported in [v7.0.36](https://github.com/postcss/postcss/releases/tag/7.0.36)
> Advisory improvement for GHSA-566m-qj78-rww5

- advisories/github-reviewed/2021/12/GHSA-7rjr-3q55-vv33/GHSA-7rjr-3q55-vv33.json
Updates:
* Affected products
Removing org.apache.logging.log4j:log4j-api as it is not impacted.
> removed log4j-api from GHSA-7rjr-3q55-vv33

- advisories/github-reviewed/2020/09/GHSA-hg79-j56m-fxgv/GHSA-hg79-j56m-fxgv.json
React publishes experimental versions with a version prefix of "0.0.0-".
This advisory causes false positives for all experimental versions,
therefore the `introduced` version should be changed to `0.0.1`
Full version history:
https://www.npmjs.com/package/react?activeTab=versions
> Exclude experimental React versions from advisory GHSA-hg79-j56m-fxgv

- advisories/github-reviewed/2021/11/GHSA-x24j-87x9-jvv5/GHSA-x24j-87x9-jvv5.json
`publify-core` does not exist. `publify_core` does (which https://github.com/github/advisory-database/blob/d6004eb8de91ad341605da869ab1b9f1e4abe433/advisories/github-reviewed/2022/02/GHSA-x3rq-r3cm-5vc4/GHSA-x3rq-r3cm-5vc4.json encodes correctly).
> Fix incorrect RubyGems package name in GHSA-x24j-87x9-jvv5

- advisories/github-reviewed/2021/11/GHSA-5629-8855-gf4g/GHSA-5629-8855-gf4g.json
`solidus_core` is the correct package name: https://rubygems.org/gems/solidus_core
> Fix incorrect package name for GHSA-5629-8855-gf4g

- advisories/github-reviewed/2021/06/GHSA-v528-7hrm-frqp/GHSA-v528-7hrm-frqp.json
**Updates**
this advisory informs about Affected versions < 1.3.2 and >= 2.0.0, < 2.4.1 .
but [nvd.nist.gov](https://nvd.nist.gov/vuln/detail/CVE-2021-27568)’s report excludes version 2.3.1.
version 2.3.1 should be added to Patched versions .
Could you check it, please?
thanks!
> Contribution to "Improper Check for Unusual or Exceptional Conditions in json-smart"

- .github/workflows/delete_staging_and_head_branches.yaml
When a PR is closed, whether it's merged or otherwise, we want to cleanup the staging and head branches. This PR updates the existing action that deletes the staging branch when a PR is merged to now delete both the staging and head branches when a PR is closed.
> Delete staging and head branches on PR close

- advisories/github-reviewed/2022/03/GHSA-cr6m-62pq-hmqh/GHSA-cr6m-62pq-hmqh.json
This issue only affects v2.0.3 and v2.0.4.
Please let me know if I edited this incorrectly.
> [npm] fix `npm-lockfile` CVE's affected versions

- advisories/github-reviewed/2021/06/GHSA-mg2g-8pwj-r2j2/GHSA-mg2g-8pwj-r2j2.json
I couldn't figure out how to do this via the "Improvement Suggestion" UI. Hopefully it'll still all be fine 🤞 
Per https://www.silverstripe.org/download/security-releases/cve-2020-26136, these are the correct ranges.
> Improve GHSA-mg2g-8pwj-r2j2

- advisories/github-reviewed/2021/12/GHSA-jfh8-c2jp-5v3q/GHSA-jfh8-c2jp-5v3q.json
**Updates**
- Description
- References
[NVD about CVE-2021-44228](https://nvd.nist.gov/vuln/detail/CVE-2021-44228) shows that there are security releases for 2.12.2, 2.12.3, and 2.3.1. 
also there are next ranges:
From (including) 2.0.1,	Up to (excluding) 2.3.1
From (including) 2.4.0	Up to (excluding) 2.12.2
From (including) 2.13.0	Up to (excluding) 2.15.0
It seems that CVE-2021-44228 doesn't affect on another versions (eg. 2.12.4).
thanks!
> Contribution to "Remote code injection in Log4j"

- advisories/github-reviewed/2021/12/GHSA-7rjr-3q55-vv33/GHSA-7rjr-3q55-vv33.json
**Updates**
- Description
[NVD for CVE-2021-45046](https://nvd.nist.gov/vuln/detail/CVE-2021-45046) shows that Log4j 2.16.0 (Java 8) and 2.12.2 (Java 7) fix this issue by removing support for message lookup patterns and disabling JNDI functionality by default.
Ranges:
From (including) 2.0.1 Up to (excluding) 2.12.2
From (including) 2.13.0 Up to (excluding) 2.16.0
so, it seems this vulnerability doesn't affected on another versions of Log4j (eg. 2.12.4).
thanks!
> Contribution to "Incomplete fix for Apache Log4j vulnerability"

- advisories/github-reviewed/2022/03/GHSA-4qrp-27r3-66fj/GHSA-4qrp-27r3-66fj.json
Package name **MUST** be lowercase for `composer/composer` and `packagist.org` to pick it up correctly.
Ref: https://github.com/Roave/SecurityAdvisoriesBuilder/issues/573
Ref: https://github.com/Roave/SecurityAdvisoriesBuilder/runs/5601510148?check_suite_focus=true
Ref: https://twitter.com/Ocramius/status/1504824415866998784
> Updated latest `sylius/sylius` advisory to comply with packagist.org package naming requirements

- advisories/github-reviewed/2022/02/GHSA-fg2v-w576-w4v3/GHSA-fg2v-w576-w4v3.json
**Updates**
- Description
NVD details about CVE-2021-31684 were updated 03/01/2022 and now affected versions are next:
* From (including)1.3  Up to (excluding)1.3.3
* From (including) 2.4  Up to (excluding) 2.4.4
links:
* https://nvd.nist.gov/vuln/detail/CVE-2021-31684
> Contribution to "Out of bounds read in json-smart"

- advisories/github-reviewed/2022/03/GHSA-57j2-w4cx-62h2/GHSA-57j2-w4cx-62h2.json
**Updates**
-----------------
Due to dependency issues with original fix (2.13.2.1), the jackson team have also released (2.12.6.1) which also contains the fix.
So there are two "valid" build options, 2.13.2.1 & 2.12.6.1
https://github.com/FasterXML/jackson-databind/issues/3428#issuecomment-1079825039
(This is my very pr to this repo, so please forgive any obvious errors)
> Contribution to "Deeply nested json in jackson-databind"

- advisories/github-reviewed/2022/03/GHSA-36p3-wjmg-h94x/GHSA-36p3-wjmg-h94x.json
**Updates**
Marking `spring-beans` and `spring-core` as affected results in pretty much every Spring application being vulnerable to CVE-2022-22965 which is not accurate as per https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement. Keeping `spring-beans` and `spring-core` in this advisory will lead to a lot of churn and false positives.
> Contribution to "Remote Code Execution in Spring Framework"

- advisories/github-reviewed/2022/03/GHSA-99wh-973f-779p/GHSA-99wh-973f-779p.json
As per the reference docs, the bug was introduced in 5.1-beta1 and fixed in 5.1
https://huntr.dev/bounties/d63972a2-b910-480a-a86b-d1f75d24d563/
https://nvd.nist.gov/vuln/detail/CVE-2022-0265
> Fix affected versions for GHSA-99wh-973f-779p

- advisories/github-reviewed/2022/01/GHSA-jcxc-rh6w-wf49/GHSA-jcxc-rh6w-wf49.json
> Contribution to "Link Following in Iris"

- advisories/github-reviewed/2019/01/GHSA-cf66-xwfp-gvc4/GHSA-cf66-xwfp-gvc4.json
**Updates**
- Description
Hello, the recommendation section says the following:
```
For webpack-dev-server 2.x update to version 2.11.4 or later.
For webpack-dev-server 3.x update to version 3.1.11 or later.
```
But dependabot only considers the upgrade to >= 3.1.11 as a fix, but does not consider an upgrade to >=2.11.4 as a fix for webpack 2.x.
Thank you for the amazing work with dependabot so far!
> [GHSA-cf66-xwfp-gvc4] Missing Origin Validation in webpack-dev-server

- advisories/github-reviewed/2021/12/GHSA-25mp-g6fv-mqxx/GHSA-25mp-g6fv-mqxx.json
Problem is that security vulnerability is incorrectly applied to v0.4 version of `next`, when it was totally different product, and that affects some of my packages which still depend on `next@0.4`
**Updates**
- Description
> [GHSA-25mp-g6fv-mqxx] Unexpected server crash in Next.js.

- advisories/github-reviewed/2022/02/GHSA-q62h-jw38-24vh/GHSA-q62h-jw38-24vh.json
**Updates**
Issue related to the CVE was fixed in v2.10.0 and all previous versions of until then were affected by this issue. The one prior to v2.10.0 is 2.9.1.
> [GHSA-q62h-jw38-24vh] Uncaught Exception in zip4j

- advisories/github-reviewed/2019/10/GHSA-p979-4mfw-53vg/GHSA-p979-4mfw-53vg.json
**Updates**
----
The description says:
> Netty before 4.1.42.Final mishandles whitespace
`4.1.42.Final` is technically a different version than `4.1.42`, since `Final` is a build component.
> [GHSA-p979-4mfw-53vg] HTTP Request Smuggling in Netty

- advisories/github-reviewed/2022/03/GHSA-r7c9-c69m-rph8/GHSA-r7c9-c69m-rph8.json
**Updates**
---
The vulnerability was added with this commit - https://github.com/sebastianbergmann/phpunit/commit/3aaddb1c5bd9b9b8d070b4cf120e71c36fd08412
You can see from the tags on that commit that it was added in 4.8.19 and no earlier.
> [GHSA-r7c9-c69m-rph8] Code injection in PHPUnit

- advisories/github-reviewed/2021/08/GHSA-mmc9-pwm7-qj5w/GHSA-mmc9-pwm7-qj5w.json
[RUSTSEC-2019-0035](https://rustsec.org/advisories/RUSTSEC-2019-0035.html) says the patched version is `^0.3.1`. There is [no published 0.3.2 release](https://crates.io/crates/rand_core/versions).
> [GHSA-mmc9-pwm7-qj5w] Unaligned memory access in rand_core

- advisories/github-reviewed/2022/04/GHSA-mwm4-5qwr-g9pf/GHSA-mwm4-5qwr-g9pf.json
> [GHSA-mwm4-5qwr-g9pf] Keycloak is vulnerable to IDN homograph attack

- advisories/github-reviewed/2022/02/GHSA-h236-g5gh-vq6c/GHSA-h236-g5gh-vq6c.json
I didn't find anything that looked like a XSS fix in the 3.0.6 release, so I tried out the PoC described in https://blog.compass-security.com/2020/07/yet-another-froala-0-day-xss/ until I found the version that fixed it.  
That version was 3.2.3.  
That same version also includes a "Fixed XSS Vulnerability in WYSIWYG HTML Editor" in the change-notes.  
**Updates**
- Description
> [GHSA-h236-g5gh-vq6c] Cross-site scripting in Froala Editor

- advisories/github-reviewed/2022/05/GHSA-hp87-p4gw-j4gq/GHSA-hp87-p4gw-j4gq.json
**This is not an improvement PR, do NOT merge it**
**This is a request to fix the broken GHSA**
As there seems to be no other way to deal with a totally broken GitHub CVE, I'm afraid I need to give notice via an improvement request in the hope something hooman notices how messed up this GitHub CVE is ... albeit admittedly based on upstream.
- The affected versions data is wrong, as it does not concern the widely used yaml.v2. This now causes an enormous number of false positives. See https://github.com/go-yaml/yaml/issues/666#issuecomment-1133337993.
- yaml.v3 has (not only) incompatible unmarshalling changes that can silently break a lot of applications trying to upgrade from yaml.v2 to yaml.v3. For instance, at least in some situations the keys of unmarshalled maps change from …
> DO NOT MERGE but please fix [GHSA-hp87-p4gw-j4gq] Unhandled exception in gopkg.in/yaml.v3

- advisories/github-reviewed/2021/08/GHSA-jrcf-4jp8-m28v/GHSA-jrcf-4jp8-m28v.json
> [GHSA-jrcf-4jp8-m28v] miow invalidly assumes the memory layout of std::net::SocketAddr

- advisories/github-reviewed/2022/05/GHSA-hj57-j5cw-2mwp/GHSA-hj57-j5cw-2mwp.json
Add omitted CVE ID to GHSA-hj57-j5cw-2mwp; it seems to have been taken by GHSA-mjqc-5c9x-xfcc (see #361).  Fix the Go package name.
Followup to #335, which was closed automatically.  Incorporates fix from #344 (thanks @dghubble!).
> GHSA-hj57-j5cw-2mwp: add CVE ID; fix Go package name

- advisories/github-reviewed/2021/08/GHSA-566x-hhrf-qf8m/GHSA-566x-hhrf-qf8m.json
**Updates**
- CVSS
- CWEs
- Description
- Severity
- Summary
It looks like this was mostly drawn from the CWE assignment in CVE-2020-35923 which is completely wrong. I've sent an email to NVD to correct it on that end, but things should also be updated here. Reviewers can see the linked RustSec advisory for a more complete explanation. Most importantly, version 1.1.1 of ordered-float is patched against this issue. It's entirely unclear to me if I've expressed that properly in the advisory here, I can't find documentation for how you express versions in this.
I think this should be assigned Low severity because it requires a rather esoteric code pattern (catching a panic then using some piece of state from the panic site) to even cause a problem.
> [GHSA-566x-hhrf-qf8m] Use after free in ordered-float

- advisories/github-reviewed/2021/12/GHSA-mmjf-f5jw-w72q/GHSA-mmjf-f5jw-w72q.json
Addresses #405 
- openssl-src 111 release stream is not supposed to be affected by this advisory
- openssl-src has two release streams - 111 for 1.1.1 and 300 for 3.0 vendored OpenSSL
- openssl-src release stream 111 brings vendored openssl 1.1.1 and
- openssl-src release stream 300 brings vendored openssl 3.0
- I've fixed the advisory to make sure only 300 release stream is advised to upgrade as 111 is unaffected
- This is pinging a lot of people as this widely used vendored openssl uses 111 release stream
> [GHSA-mmjf-f5jw-w72q] openssl-src 111 stream is not affected

- advisories/github-reviewed/2022/05/GHSA-638m-m8mh-7gw2/GHSA-638m-m8mh-7gw2.json
Further to #405 
We today updated RUSTSEC-2022-0025,26,27 to reflect the reality for openssl-src :
https://github.com/rustsec/advisory-db/pull/1263
This advisory was missing release path fixed version for openssl-src 111 release stream
Currently dependabot is asking to switch 300 release stream which is incorrect advice as there are two separate streams
> [GHSA-638m-m8mh-7gw2] 111.20.0 fixed version for openssl-src 111

- advisories/github-reviewed/2021/08/GHSA-wf5p-c75w-w3wh/GHSA-wf5p-c75w-w3wh.json
Tensorflow-lite doesn't seem to be a package name on https://pypi.org/search/?q=tensorflow-lite
Checking this link though: https://github.com/tensorflow/tensorflow/commit/d6b57f461b39fd1aa8c1b870f1b974aac3554955
...I think they may be referring to https://pypi.org/project/tflite/ ? 
**Updates**
> [GHSA-wf5p-c75w-w3wh] Null pointer dereference in TFLite MLIR optimizations

- advisories/github-reviewed/2022/05/GHSA-g323-fr93-4j3c/GHSA-g323-fr93-4j3c.json
#405 
**Correction**
- openssl-src 111 stream is not affected
- only 300 stream is affected and affected should be marked only 300.0.0 => && <  300.0.6
We've adjusted the associated RustSec
> [GHSA-g323-fr93-4j3c] openssl-src 111 stream is not affected

- advisories/github-reviewed/2022/06/GHSA-rxhx-9fj6-6h2m/GHSA-rxhx-9fj6-6h2m.json
**Updates**
- Description
- References
> [GHSA-rxhx-9fj6-6h2m] enum_map macro can cause UB when `Enum` trait is incorrectly implemented

- advisories/github-reviewed/2022/06/GHSA-7v4j-8wvr-v55r/GHSA-7v4j-8wvr-v55r.json
**Updates**
- CVSS
- Description
- Severity
> [GHSA-7v4j-8wvr-v55r] `array!` macro is unsound when its length is impure constant

- advisories/github-reviewed/2022/06/GHSA-mpg5-fvwp-42m2/GHSA-mpg5-fvwp-42m2.json
**Updates**
- Description
This advisory only affects dashmap 5.0.0, nothing before that version. I tried to list affected versions as just 5.0.0, but the form wouldn't let me.
Source: The cited RustSec advisory: https://rustsec.org/advisories/RUSTSEC-2022-0002.html
> [GHSA-mpg5-fvwp-42m2] Unsoundness in `dashmap` references

- advisories/github-reviewed/2022/01/GHSA-c5hx-w945-j4pq/GHSA-c5hx-w945-j4pq.json
Updating with the CWE from https://nvd.nist.gov/vuln/detail/CVE-2021-45706.
**Updates**
- CWEs
> [GHSA-c5hx-w945-j4pq] Memory flaw in zeroize_derive

- advisories/github-reviewed/2022/06/GHSA-r45x-ghr2-qjxc/GHSA-r45x-ghr2-qjxc.json
**Updates**
- CVSS
- CWEs
- Description
- Severity
> [GHSA-r45x-ghr2-qjxc] `#[zeroize(drop)]` doesn't implement `Drop` for `enum`s

- advisories/github-reviewed/2022/05/GHSA-x4cf-6jr3-3qvp/GHSA-x4cf-6jr3-3qvp.json
**Updates**
There is no version 7.2 of hermes-engine, so far the latest version is 0.11.0, the patched version supposed to be 0.7.2
> [GHSA-x4cf-6jr3-3qvp] Out-of-bounds Read in Facebook Hermes

- advisories/github-reviewed/2022/06/GHSA-pfrx-2q88-qq97/GHSA-pfrx-2q88-qq97.json
**Updates**
- Description
My intention is to make it clearer that got v11 has been patched as well and not all versions “before 12.1.0” are vulnerable.
> [GHSA-pfrx-2q88-qq97] Got allows a redirect to a UNIX socket

- advisories/github-reviewed/2022/05/GHSA-mh2h-6j8q-x246/GHSA-mh2h-6j8q-x246.json
> [GHSA-mh2h-6j8q-x246] Improper Neutralization of Special Elements in Output Used by a Downstream Component in Codecov

- advisories/github-reviewed/2022/06/GHSA-3m6f-3gfg-4x56/GHSA-3m6f-3gfg-4x56.json
See the originating RustSec advisory; this only affects version 0.6.0: https://rustsec.org/advisories/RUSTSEC-2021-0125.html
**Updates**
> [GHSA-3m6f-3gfg-4x56] Panic on incorrect date input to `simple_asn1`

- README.md
This PR adds Erlang to the supported ecosystems list.
> Add Erlang as a supported ecosystem

- README.md
Small update to move Erlang entry into alphabetized position in list of supported ecosystems
> Keep supported ecosystem list alphabetized

- advisories/github-reviewed/2021/06/GHSA-fvx8-v524-8579/GHSA-fvx8-v524-8579.json
**Updates**
- Description
- References
> [GHSA-fvx8-v524-8579] Cleartext Storage of Sensitive Information

- advisories/github-reviewed/2022/07/GHSA-cj88-88mr-972w/GHSA-cj88-88mr-972w.json
**Updates**
Dependabot / github harasses open source maintainers by including bogus & false vulnerability reports, which makes people create 1000s of issues all over GitHub. Can you stop this?
https://github.com/paulmillr/chokidar/issues/1191
> [GHSA-cj88-88mr-972w] glob-parent before 6.0.1 vulnerable to Regular Expression Denial of Service (ReDoS)

- README.md
The last segment of the previous URL is already part of the package group.
> Fixed link to Maven package registry

- advisories/github-reviewed/2022/07/GHSA-mhxj-85r3-2x55/GHSA-mhxj-85r3-2x55.json
**Updates**
**Resons**
If you check the [diff between 12.4.2 and 13.0.0](https://github.com/sindresorhus/file-type/compare/v12.4.2...v13.0.0#diff-c853b2249e99790d8725774cf63c90c5ab17112067df6e267f3701d7bf591d12R611-R613), you can see that the vulnerable code was introduced between these two versions, so v13.0.0 is the first vulnerable version.
> [GHSA-mhxj-85r3-2x55] file-type vulnerable to Infinite Loop via malformed MKV file

- advisories/github-reviewed/2022/05/GHSA-chqf-hx79-gxc6/GHSA-chqf-hx79-gxc6.json
**Updates**
- References: added links to current upstream repository and issue tracker
> [GHSA-chqf-hx79-gxc6] Improper Restriction of XML External Entity Reference in Openpyxl

- README.md
Updates the list of supported ecosystems to now include `GitHub Actions`
> Add GitHub Actions to list of supported ecosystems

- advisories/github-reviewed/2022/02/GHSA-6qq8-5wq3-86rp/GHSA-6qq8-5wq3-86rp.json
> [GHSA-6qq8-5wq3-86rp] Traefik vulnerable to Open Redirect via handling of X-Forwarded-Prefix header

- .github/workflows/stale.yaml
- CONTRIBUTING.md
This PR adds the [stale](https://github.com/marketplace/actions/close-stale-issues) Action to the repository to automatically mark and close stale pull requests after 30 days of inactivity. It additionally updates the contributing.md to better reflect the actions that the workflow will take.
> Add stale Action to repo to handle PRs

- advisories/github-reviewed/2022/05/GHSA-g954-5hwp-pp24/GHSA-g954-5hwp-pp24.json
**Updates**
- Description
**Comments**
The vulnerable code was not introduced yet in 6.9.0 (no util.setProperty in https://github.com/protobufjs/protobuf.js/blob/v6.10.0/src/util.js).
Version 6.10.0 is the first vulnerable release (https://github.com/protobufjs/protobuf.js/blob/07e8185379d6ca6235b71685566c3ce4f594ed34/src/util.js#L176).
> [GHSA-g954-5hwp-pp24] Prototype Pollution in protobufjs

- advisories/github-reviewed/2022/01/GHSA-jq4p-mq33-w375/GHSA-jq4p-mq33-w375.json
**Updates**
**Comments**
Mitigation was released as 2.17.1. There is no 2.17.2 release.
https://github.com/laminas/laminas-form/releases/tag/2.17.1
> [GHSA-jq4p-mq33-w375] Cross-site Scripting when rendering error messages in laminas-form

- advisories/github-reviewed/2022/07/GHSA-fw3v-x4f2-v673/GHSA-fw3v-x4f2-v673.json
**Updates**
- CVSS
- CWEs
- Severity
**Comments**
This is a ReDoS, and I don't think that can reasonably be assumed to have either a confidentiality or integrity impact.
> [GHSA-fw3v-x4f2-v673] Mistune v2.0.2 vulnerable to catastrophic backtracking

- advisories/github-reviewed/2018/10/GHSA-jc8g-xhw5-6x46/GHSA-jc8g-xhw5-6x46.json
**Updates**
**Comments**
Package id System.ServiceModel.Duplex 4.1.0 doesn't exist. Should be 4.0.1. The patched version is 4.0.2.
> [GHSA-jc8g-xhw5-6x46] Improper Certificate Validation in Microsoft .NET Framework components

- advisories/github-reviewed/2022/07/GHSA-f825-f98c-gj3g/GHSA-f825-f98c-gj3g.json
**Updates**
**Comments**
new patch has been released to fix this in version 5
> [GHSA-f825-f98c-gj3g] automattic/mongoose vulnerable to Prototype pollution via Schema.path

- advisories/github-reviewed/2022/06/GHSA-j32j-2hxv-rqf7/GHSA-j32j-2hxv-rqf7.json
**Updates**
**Comments**
The Snyk references show the fixed versions. These can also be verified by checking the two project github repos (which I did)
> [GHSA-j32j-2hxv-rqf7] Uncontrolled Resource Consumption in pg-native and libpq

- advisories/github-reviewed/2022/06/GHSA-5q2v-6j86-5h9v/GHSA-5q2v-6j86-5h9v.json
**Updates**
- CVSS
**Comments**
provide CVSS string and the Core package which contains the vulnerability. It has been changed on the github project itself, but has not been picked up here yet
> [GHSA-5q2v-6j86-5h9v] Security Update for the OPC UA .NET Standard Stack

- advisories/unreviewed/2022/05/GHSA-7v44-75jf-22gj/GHSA-7v44-75jf-22gj.json
**Updates**
- Summary
**Comments**
Not mapped to a package. Dependency graph says kevinpapst/kimai2 is a composer package
> [GHSA-7v44-75jf-22gj] Kimai v2 before 1.1 has XSS via a timesheet description.

- advisories/unreviewed/2022/04/GHSA-6wj9-77wq-jq7p/GHSA-6wj9-77wq-jq7p.json
**Updates**
- Summary
**Comments**
Not mapped
> [GHSA-6wj9-77wq-jq7p] Nokogiri before 1.5.4 is vulnerable to XXE attacks

- advisories/github-reviewed/2021/08/GHSA-69fv-gw6g-8ccg/GHSA-69fv-gw6g-8ccg.json
**Updates**
**Comments**
We withdrew [PYSEC-2019-144](https://github.com/pypa/advisory-database/blob/c141d734181d6cfe02a72db3a50008b9a464362e/vulns/arrayfire/PYSEC-2019-144.yaml) in https://github.com/pypa/advisory-database/pull/99 as this specifically affected the rust bindings only
> [GHSA-69fv-gw6g-8ccg] Potential memory corruption in arrayfire

- advisories/github-reviewed/2022/09/GHSA-74w3-p89x-ffgh/GHSA-74w3-p89x-ffgh.json
**Updates**
- Severity
**Comments**
Severity of this case is incredibly inflated. There's no vulnerability here, and a risk of one is very low: this package has been stable for years, and has a perfect security track record.
Calling everything "Critical" undermines my trust in your whole security advisory program. This advisory has also been marked as "GitHub reviewed", and the review did not catch how absurd this advisory is.
> [GHSA-74w3-p89x-ffgh] ansi_term is Unmaintained

- advisories/github-reviewed/2021/06/GHSA-q2q7-5pp4-w6pg/GHSA-q2q7-5pp4-w6pg.json
**Updates**
**Comments**
* `docker run -it --rm debian:buster bash -c 'apt update && apt install python3-pip -y && pip3 install urllib3==1.25.3 && time python3 -c "import urllib3; urllib3.util.parse_url(\"http://\"+  (\"@\"*10000) + \"[\")"'` gives a runtime of 0.064s for the test on my system
* `docker run -it --rm debian:buster bash -c 'apt update && apt install python3-pip -y && pip3 install urllib3==1.25.4 && time python3 -c "import urllib3; urllib3.util.parse_url(\"http://\"+  (\"@\"*10000) + \"[\")"'` gives a runtime of 4.531s for the test  on my system
* `docker run -it --rm debian:buster bash -c 'apt update && apt install python3-pip -y && pip3 install urllib3==1.26.4 && time python3 -c "import urllib3; urllib3.util.parse_url(\"http://\"+  (\"@\"*10000) + …
> [GHSA-q2q7-5pp4-w6pg] Catastrophic backtracking in URL authority parser when passed URL containing many @ characters

- advisories/github-reviewed/2022/09/GHSA-rfj2-q3h3-hm5j/GHSA-rfj2-q3h3-hm5j.json
**Updates**
- CVSS
- Severity
**Comments**
The Security Response WG intentionally marked this vulnerability as "low" severity rather than going with the CVSS assessment, with the following reasoning:
> Note that **by design** Cargo allows code execution at build time, due to build scripts and procedural macros. The vulnerabilities in this advisory allow performing a subset of the possible damage in a harder to track down way. Your dependencies must still be trusted if you want to be protected from attacks, as it's possible to perform the same attacks with build scripts and procedural macros.
This updates the severity of this advisory to reflect the text of the advisory.
> [GHSA-rfj2-q3h3-hm5j] Cargo extracting malicious crates can corrupt arbitrary files

- advisories/github-reviewed/2022/09/GHSA-2hvr-h6gw-qrxp/GHSA-2hvr-h6gw-qrxp.json
**Updates**
- CVSS
- Severity
**Comments**
The Security Response WG intentionally marked this vulnerability as "low" severity rather than going with the CVSS assessment, with the following reasoning:
> Note that **by design** Cargo allows code execution at build time, due to build scripts and procedural macros. The vulnerabilities in this advisory allow performing a subset of the possible damage in a harder to track down way. Your dependencies must still be trusted if you want to be protected from attacks, as it's possible to perform the same attacks with build scripts and procedural macros.
This updates the severity of this advisory to reflect the text of the advisory.
> [GHSA-2hvr-h6gw-qrxp] Cargo extracting malicious crates can fill the file system

- advisories/github-reviewed/2022/09/GHSA-mw37-wx8p-gp45/GHSA-mw37-wx8p-gp45.json
**Updates**
**Comments**
The vulnerability did not affect versions prior to 4.0.0
> [GHSA-mw37-wx8p-gp45] Craft CMS vulnerable to Cross-site Scripting via Drafts

- advisories/github-reviewed/2022/07/GHSA-9339-86wc-4qgf/GHSA-9339-86wc-4qgf.json
**Updates**
- References
**Comments**
Xalan 2.7.3 release candidate is under review, and can soon be expected :)
https://lists.apache.org/thread/x3f7xv3p1g32qj2hlg8wd57pwcpld471
> [GHSA-9339-86wc-4qgf] Apache Xalan Java XSLT library integer truncation issue when processing malicious XSLT stylesheets

- advisories/github-reviewed/2022/05/GHSA-h7wm-ph43-c39p/GHSA-h7wm-ph43-c39p.json
**Updates**
**Comments**
https://github.com/scrapy/scrapy/issues/482 is still open and there's no evidence its getting worked on or has been resolved, so this should be an open-ended advisory.
> [GHSA-h7wm-ph43-c39p] Scrapy denial of service vulnerability

- advisories/github-reviewed/2022/09/GHSA-8qv5-68g4-248j/GHSA-8qv5-68g4-248j.json
**Updates**
**Comments**
There's no version 2.19.0 and the CVE was fixed in 2.13.9: https://github.com/scala/scala/releases/tag/v2.13.9, https://nvd.nist.gov/vuln/detail/CVE-2022-36944
> [GHSA-8qv5-68g4-248j] Scala subject to file deletion, code execution due to Java deserialization chain with LazyList object deserialization

- advisories/github-reviewed/2021/05/GHSA-f2jv-r9rf-7988/GHSA-f2jv-r9rf-7988.json
**Updates**
**Comments**
Including the [webjars](https://www.webjars.org/) which package up the handlebars javascript as a Java artifact and are available on Maven
https://search.maven.org/artifact/org.webjars.bowergithub.wycats/handlebars.js/4.7.2/jar
https://search.maven.org/artifact/org.webjars.npm/handlebars/4.7.7/jar
https://search.maven.org/artifact/org.webjars/handlebars/4.7.6/jar
https://search.maven.org/artifact/org.webjars.bower/handlebars/4.7.6/jar
> [GHSA-f2jv-r9rf-7988] Remote code execution in handlebars when compiling templates

- advisories/github-reviewed/2022/09/GHSA-f36p-42jv-8rh2/GHSA-f36p-42jv-8rh2.json
**Updates**
**Comments**
The project namespace was renamed from `com.wire.bots` to `com.wire` in the past, this change adds the old name to the affected products
> [GHSA-f36p-42jv-8rh2] Lithium vulnerable to Cross Site Scripting in provided Swagger-UI

- advisories/github-reviewed/2019/04/GHSA-wv67-q8rr-grjp/GHSA-wv67-q8rr-grjp.json
The CVE identifier for GHSA-wv67-q8rr-grjp is incorrect. CVE-2019-5428 was rejected as a duplicate of CVE-2019-11358 per the NVD database
https://nvd.nist.gov/vuln/detail/CVE-2019-5428
> update CVE record to correct identifier

- advisories/github-reviewed/2022/10/GHSA-77xx-rxvh-q682/GHSA-77xx-rxvh-q682.json
**Updates**
**Comments**
HSQLDB is not hosted on github let alone here https://github.com/myxof/hypersql, and there is no such thing as a release 2.7.1, neither on sourceforge: https://sourceforge.net/projects/hsqldb/files/, nor on maven central: https://repo1.maven.org/maven2/org/hsqldb/hsqldb/
~Is this CVE a legitimate?~ (it seems to be, but maybe published prematurely as no release is available yet)
> [GHSA-77xx-rxvh-q682] HyperSQL DataBase vulnerable to remote code execution when processing untrusted input

- advisories/github-reviewed/2022/09/GHSA-9xgj-fcgf-x6mw/GHSA-9xgj-fcgf-x6mw.json
**Updates**
- CWEs
**Comments**
CWE-88 is a much more accurate description of the vulnerability (this is **argument injection**) compared to CWE-94, which is more generic and not as descriptive.
> [GHSA-9xgj-fcgf-x6mw] Poetry Argument Injection can lead to Local Code Execution

- advisories/github-reviewed/2022/05/GHSA-99v3-9x35-c5vf/GHSA-99v3-9x35-c5vf.json
**Updates**
**Comments**
WSS4J 3.0.0 is not impacted. "as used in Apache CXF 2.7.x before 2.7.13 and 3.0.x before 3.0.2" -> This refers to Apache CXF, which embeds WSS4J.
> [GHSA-99v3-9x35-c5vf] Improper Authentication in Apache WSS4J

- advisories/github-reviewed/2022/04/GHSA-28xr-mwxg-3qc8/GHSA-28xr-mwxg-3qc8.json
**Updates**
- Description
**Comments**
Affected products said 3.5.0, but the text said 3.6.0. Both of these indicate that 3.5.0 is correct: https://github.com/steveukx/git-js/releases/tag/simple-git%403.5.0
https://security.snyk.io/vuln/SNYK-JS-SIMPLEGIT-2434306
> [GHSA-28xr-mwxg-3qc8] Command injection in simple-git

- advisories/github-reviewed/2022/10/GHSA-9pgh-qqpf-7wqj/GHSA-9pgh-qqpf-7wqj.json
**Updates**
**Comments**
Maintainer has merged https://github.com/xmldom/xmldom/pull/441 which backports the fix to 0.7.x branch and released as 0.7.6.
Updated changelog: https://github.com/xmldom/xmldom/blob/master/CHANGELOG.md#076
Hopefully this would resolve the dependabot alert generated for this to allow for 0.7.6 to be considered as a fixed version as well, thanks.
> [GHSA-9pgh-qqpf-7wqj] Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution') in @xmldom/xmldom and xmldom

- advisories/github-reviewed/2022/10/GHSA-jjjh-jjxp-wpff/GHSA-jjjh-jjxp-wpff.json
**Updates**
- Description
- References
**Comments**
This CVE is also fixed in Jackson Databind 2.13.4.1. I think it makes more sense to use this version than a release candidate (2.14.0-rc1).
> [GHSA-jjjh-jjxp-wpff] Uncontrolled Resource Consumption in Jackson-databind

- advisories/github-reviewed/2022/10/GHSA-w596-4wvx-j9j6/GHSA-w596-4wvx-j9j6.json
**Updates**
- Description
**Comments**
https://github.com/pytest-dev/py/issues/287#issuecomment-1283567565
> [GHSA-w596-4wvx-j9j6] ReDoS in py library

- advisories/github-reviewed/2022/10/GHSA-2j79-8pqc-r7x6/GHSA-2j79-8pqc-r7x6.json
**Updates**
- Description
- References
- Summary
**Comments**
This vulnerability was also fixed for 2.x releases by cherry-picking the commit to the v2 branch:
https://github.com/software-mansion/react-native-reanimated/blob/2.10.0/src/reanimated2/Colors.ts#L26
> [GHSA-2j79-8pqc-r7x6] react-native-reanimated vulnerable to ReDoS

- advisories/github-reviewed/2022/05/GHSA-g4rg-993r-mgx7/GHSA-g4rg-993r-mgx7.json
**Updates**
- References
**Comments**
Original GitHub project is gone - links 404. NPM registry points to updated project (https://github.com/ljharb/shell-quote). Replacing the target(s) seem to point to relevant commits.
> [GHSA-g4rg-993r-mgx7] Improper Neutralization of Special Elements used in a Command in Shell-quote

- advisories/github-reviewed/2022/09/GHSA-3f7h-mf4q-vrm4/GHSA-3f7h-mf4q-vrm4.json
**Updates**
**Comments**
This appears to be incorrect and this whole advisory needs to be updated and identify the correct library. I am not familiar enough with this vul to confidently update this whole advisory to be correct.
Link to the issue in woodstox: https://github.com/FasterXML/woodstox/issues/157#issuecomment-1274221678
> [GHSA-3f7h-mf4q-vrm4] XStream Denial of Service due to parser crash

- advisories/github-reviewed/2022/09/GHSA-3mq5-fq9h-gj7j/GHSA-3mq5-fq9h-gj7j.json
**Updates**
- References
**Comments**
Clearly, the issue is not in XStream but in Woodstox. https://github.com/FasterXML/woodstox/issues/160
> [GHSA-3mq5-fq9h-gj7j] XStream Denial of Service due to parser crash

- advisories/github-reviewed/2022/09/GHSA-8gq9-2x98-w8hf/GHSA-8gq9-2x98-w8hf.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Fix severity according to NIST https://nvd.nist.gov/vuln/detail/CVE-2022-1941
> [GHSA-8gq9-2x98-w8hf] protobuf-cpp and protobuf-python have potential Denial of Service issue

- advisories/github-reviewed/2022/10/GHSA-wrx5-rp7m-mm49/GHSA-wrx5-rp7m-mm49.json
**Updates**
- Description
- References
**Comments**
Adding more technical information about the issue and link to working proof of concept and possible solutions. (More details about the issue can be found in the added references.)
> [GHSA-wrx5-rp7m-mm49] JXPath vulnerable to remote code execution when interpreting untrusted XPath expressions

- advisories/github-reviewed/2021/11/GHSA-rrc9-gqf8-8rwg/GHSA-rrc9-gqf8-8rwg.json
**Updates**
- CWEs
**Comments**
CWE is wrong - the vulnerability is prototype pollution, which can have varied effects depending on context.
> [GHSA-rrc9-gqf8-8rwg] Prototype Pollution via file load in aws-sdk and @aws-sdk/shared-ini-file-loader

- advisories/github-reviewed/2022/07/GHSA-98g7-rxmf-rrxm/GHSA-98g7-rxmf-rrxm.json
**Updates**
- CVE-2021-4178 Incorrect affected version range
The affected versions that mentioned in the Vulnerability details:
>= 5.0.0-beta-1, < 5.0.3
>= 5.1.0, < 5.1.2
>= 5.2.0, < 5.3.2
>= 5.5.0, < 5.7.4
>= 5.8.0, < 5.8.1
>= 5.9.0, < 5.11.2
According to [5.10.2 release](https://github.com/fabric8io/kubernetes-client/releases/tag/v5.10.2),  5.10.2 is a patched version and not affected.
Please add this patch to the affected version.
Thanks,
Shaul
> [GHSA-98g7-rxmf-rrxm] fabric8 kubernetes-client vulnerable 

- advisories/github-reviewed/2022/09/GHSA-rhwx-hjx2-x4qr/GHSA-rhwx-hjx2-x4qr.json
**Updates**
**Comments**
The changes in 0.8.7 was insufficient to fix command injection. It only partially fixed a specific case of it, but command injection and environment reading was still possible: https://github.com/pdfkit/pdfkit/issues/517
> [GHSA-rhwx-hjx2-x4qr] PDFKit vulnerable to Command Injection

- advisories/github-reviewed/2022/11/GHSA-crh6-fp67-6883/GHSA-crh6-fp67-6883.json
**Updates**
- CWEs
**Comments**
add 	CWE-112: Missing XML Validation to advisory - the root cause is that malformed XML (multiple root nodes) is not rejected by the parser
> [GHSA-crh6-fp67-6883] xmldom allows multiple root nodes in a DOM

- advisories/github-reviewed/2022/10/GHSA-vg46-2rrj-3647/GHSA-vg46-2rrj-3647.json
**Updates**
**Comments**
It looks like the version on PyPI is https://pypi.org/project/Twisted/22.10.0rc1/ without the extra .
> [GHSA-vg46-2rrj-3647] Twisted vulnerable to NameVirtualHost Host header injection

- advisories/github-reviewed/2022/06/GHSA-2m4x-4q9j-w97g/GHSA-2m4x-4q9j-w97g.json
**Updates**
- CWEs
**Comments**
DOS is caused by an unhandled runtime panic case on compiling bad input
> [GHSA-2m4x-4q9j-w97g] Denial of service in Open Policy Agent 

- advisories/github-reviewed/2022/11/GHSA-8g2p-5pqh-5jmc/GHSA-8g2p-5pqh-5jmc.json
**Updates**
- References
**Comments**
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-41064 seems just reserved, but I think it's also the same as https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-41064
> [GHSA-8g2p-5pqh-5jmc] .NET Information Disclosure Vulnerability

- advisories/github-reviewed/2022/05/GHSA-8cw2-jv5c-c825/GHSA-8cw2-jv5c-c825.json
**Updates**
**Comments**
For Python, Apache Arrow's library is called `pyarrow` in PyPI. (https://pypi.org/project/pyarrow/)
The `arrow` package is an unrelated datetime package with no dependencies on the vulnerable version of `pyarrow`. (https://pypi.org/project/arrow/)
> [GHSA-8cw2-jv5c-c825] Missing Initialization of Resource in Apache Arrow

- advisories/github-reviewed/2022/10/GHSA-rgv9-q543-rqg4/GHSA-rgv9-q543-rqg4.json
**Updates**
- Description
**Comments**
As claimed in https://github.com/FasterXML/jackson-databind/issues/3582, `jackson-databind:2.12.7.1` also has fixed this CVE
> [GHSA-rgv9-q543-rqg4] Uncontrolled Resource Consumption in FasterXML jackson-databind

- advisories/github-reviewed/2022/11/GHSA-653v-rqx9-j85p/GHSA-653v-rqx9-j85p.json
**Updates**
**Comments**
The vulnerabilty has been fixed by 1.1.9: https://github.com/mattphillips/deep-object-diff/pull/87
> [GHSA-653v-rqx9-j85p] deep-object-diff vulnerable to Prototype Pollution

- advisories/github-reviewed/2019/09/GHSA-r74q-gxcg-73hx/GHSA-r74q-gxcg-73hx.json
**Updates**
- References
**Comments**
The old commit link was the entire commit history of the `master` branch which is not helpful when diving into changes related to the vulnerability. The updated link is the patch commit that fixes the issue.
> [GHSA-r74q-gxcg-73hx] Improper Input Validation in simple_form

- advisories/github-reviewed/2022/10/GHSA-qm95-pgcg-qqfq/GHSA-qm95-pgcg-qqfq.json
**Updates**
- CWEs
**Comments**
proposal - attach CWE-1287 (improper validation of specified type of input) to this advisory. Root cause is library fails to enforce that packets are `Buffer` objects - see also workaround
> [GHSA-qm95-pgcg-qqfq] Insufficient validation when decoding a Socket.IO packet

- advisories/github-reviewed/2022/08/GHSA-4696-g7jj-xg2h/GHSA-4696-g7jj-xg2h.json
**Updates**
**Comments**
The package is for Android developer. It should not be a npm package.
> [GHSA-4696-g7jj-xg2h] Mapbox is vulnerable to Integer Overflow

- advisories/github-reviewed/2022/01/GHSA-f7vh-qwp3-x37m/GHSA-f7vh-qwp3-x37m.json
**Updates**
**Comments**
The artifact's name was not correct. The artifact org.apache.logging.log4j:log4j does not exist in version 1.2.x, only for versions >=2.0. The correct artifact name for the given version is log4j:log4j
> [GHSA-f7vh-qwp3-x37m] Deserialization of Untrusted Data in Apache Log4j

- advisories/github-reviewed/2022/11/GHSA-2p9h-ccw7-33gf/GHSA-2p9h-ccw7-33gf.json
**Updates**
**Comments**
Cleo 1.0.0 (yanked) and >= 2.0.0 include a fix for this regular expression.
> [GHSA-2p9h-ccw7-33gf] cleo is vulnerable to Regular Expression Denial of Service (ReDoS)

- advisories/github-reviewed/2022/11/GHSA-w37g-rhq8-7m4j/GHSA-w37g-rhq8-7m4j.json
**Updates**
**Comments**
It seems like the affected versions are incorrect. When reviewing the referenced links it seems this has been fixed in version 1.32. Also see https://security.snyk.io/package/maven/org.yaml:snakeyaml
> [GHSA-w37g-rhq8-7m4j] Snakeyaml vulnerbale to Stack overflow leading to denial of service

- advisories/github-reviewed/2022/01/GHSA-gqm2-2gcx-p88w/GHSA-gqm2-2gcx-p88w.json
**Updates**
**Comments**
Updating first version including a fix according to https://www.jenkins.io/security/advisory/2022-01-12/#SECURITY-2342
> [GHSA-gqm2-2gcx-p88w] Incorrect Permission Assignment for Critical Resource in Jenkins Credentials Binding Plugin

- advisories/github-reviewed/2022/03/GHSA-85f9-w9cx-h363/GHSA-85f9-w9cx-h363.json
**Updates**
- CVSS
- Severity
**Comments**
Update details according to https://www.jenkins.io/security/advisory/2022-03-29/#SECURITY-2062%20(1)
This CSRF vulnerability is not yet fixed.
> [GHSA-85f9-w9cx-h363] Cross site request forgery in Jenkins Job and Node ownership Plugin

- advisories/github-reviewed/2021/03/GHSA-mvg9-xffr-p774/GHSA-mvg9-xffr-p774.json
**Updates**
**Comments**
The patch version occurred in version 8.2.0, not 8.1.1. The vulnerability was first discovered in 8.1.1. https://security.gentoo.org/glsa/202107-33 has the correct affected package range. 
Additionally, we can see that the vulnerability fixing commit (cbdce6c5d054fccaf4af34b47f212355c64ace7a) didn't appear until tag 8.2.0:
~/Pillow$ git tag --contains cbdce6c5d054fccaf4af34b47f212355c64ace7a
8.2.0
8.3.0
8.3.1
8.3.2
8.4.0
9.0.0
9.0.1
9.1.0
9.1.1
9.2.0
9.3.0
> [GHSA-mvg9-xffr-p774] Out of bounds read in Pillow

- advisories/github-reviewed/2022/02/GHSA-64q9-f38h-9mwx/GHSA-64q9-f38h-9mwx.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS evaluation according to https://www.jenkins.io/security/advisory/2022-02-15/#SECURITY-2548
Also fixed the source code URL.
> [GHSA-64q9-f38h-9mwx] Protection Mechanism Failure in Jenkins Doktor Plugin

- advisories/github-reviewed/2022/02/GHSA-g5wh-fw4m-2v28/GHSA-g5wh-fw4m-2v28.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS evaluation according to https://www.jenkins.io/security/advisory/2022-02-15/#SECURITY-2545
> [GHSA-g5wh-fw4m-2v28] CSRF vulnerability in Jenkins autonomiq plugin

- advisories/github-reviewed/2022/02/GHSA-fm6q-97gw-c4wh/GHSA-fm6q-97gw-c4wh.json
**Updates**
- CVSS
- Severity
- Summary
**Comments**
Update fixed version and CVSS evaluation according to https://www.jenkins.io/security/advisory/2022-02-15/#SECURITY-2429
> [GHSA-fm6q-97gw-c4wh] Secret exposure in Jenkins HashiCorp Vault Plugin

- advisories/github-reviewed/2022/05/GHSA-7h2j-h5xp-h3gh/GHSA-7h2j-h5xp-h3gh.json
**Updates**
- CVSS
- Severity
**Comments**
Update CVSS scoring to https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2093 and remove fixed version.
This vulnerability is not addressed yet.
> [GHSA-7h2j-h5xp-h3gh] Missing Authorization in Jenkins SSH plugin

- advisories/github-reviewed/2022/02/GHSA-2phq-ghf8-6586/GHSA-2phq-ghf8-6586.json
**Updates**
- CVSS
- Description
**Comments**
Update versions affected according to https://www.jenkins.io/security/advisory/2022-02-15/#SECURITY-2536
> [GHSA-2phq-ghf8-6586] Jenkins Snow Commander Plugin prior to 2.0 vulnerable to Missing Authorization

- advisories/github-reviewed/2021/08/GHSA-wcg3-cvx6-7396/GHSA-wcg3-cvx6-7396.json
**Updates**
**Comments**
All versions of `0.1.x` are listed as vulnerable in the advisory description.
> [GHSA-wcg3-cvx6-7396] Segmentation fault in time

- advisories/github-reviewed/2022/06/GHSA-35r9-gfqf-r6cw/GHSA-35r9-gfqf-r6cw.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2279
> [GHSA-35r9-gfqf-r6cw] Missing permission check in Jenkins vRealize Orchestrator Plugin

- advisories/github-reviewed/2022/06/GHSA-77vq-4j66-46m5/GHSA-77vq-4j66-46m5.json
**Updates**
- CVSS
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2249
> [GHSA-77vq-4j66-46m5] Missing Authorization in Jenkins ThreadFix Plugin

- advisories/github-reviewed/2022/06/GHSA-jhfv-8936-g652/GHSA-jhfv-8936-g652.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
This has been fixed in 0.0.5, specifically in this commit: https://github.com/jenkinsci/hidden-parameter-plugin/commit/b1cf577b0fe6c5db1e25031a653d84dc424e6bb9#diff-4ef68932c4bd2675faf307ce8adc92598e41c5aed65cc7bf9d86cc8d41010eedR5-R6
> [GHSA-jhfv-8936-g652] Cross-site Scripting in Jenkins Hidden Parameter Plugin

- advisories/github-reviewed/2022/09/GHSA-j2mj-g8jp-gjfm/GHSA-j2mj-g8jp-gjfm.json
**Updates**
- CVSS
- Severity
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2022-09-21/#SECURITY-2737
> [GHSA-j2mj-g8jp-gjfm] Jenkins NS-ND Integration Performance Publisher Plugin vulnerable to Missing Authorization

- advisories/github-reviewed/2022/09/GHSA-fq2h-r2h9-pj8r/GHSA-fq2h-r2h9-pj8r.json
**Updates**
- CVSS
- Severity
**Comments**
Fill in details according to https://www.jenkins.io/security/advisory/2022-09-21/#SECURITY-2858
The vulnerability has been fixed in https://github.com/jenkinsci/cavisson-ns-nd-integration-plugin/commit/d77c6c7a279da002178f8244f37093773dd6aee5
> [GHSA-fq2h-r2h9-pj8r] Jenkins NS-ND Integration Performance Publisher Plugin vulnerable to Cross-site Scripting

- advisories/github-reviewed/2022/09/GHSA-j8xr-2279-88qj/GHSA-j8xr-2279-88qj.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Fix CVSS scoring according to https://www.jenkins.io/security/advisory/2022-09-21/#SECURITY-2805
> [GHSA-j8xr-2279-88qj] Jenkins RQM Plugin vulnerable to Improper Restriction of XML External Entity Reference

- advisories/github-reviewed/2022/09/GHSA-7jwg-hq85-c6m6/GHSA-7jwg-hq85-c6m6.json
**Updates**
- CVSS
- Severity
- Summary
**Comments**
Fix CVSS scoring according to https://www.jenkins.io/security/advisory/2022-09-21/#SECURITY-2068
> [GHSA-7jwg-hq85-c6m6] Jenkins SmallTest Plugin improperly validates hostname

- advisories/github-reviewed/2022/09/GHSA-pxp5-g66h-wpv2/GHSA-pxp5-g66h-wpv2.json
**Updates**
- CVSS
- Severity
- Summary
**Comments**
Fix CVSS scoring according to https://www.jenkins.io/security/advisory/2022-09-21/#SECURITY-2069
> [GHSA-pxp5-g66h-wpv2] Jenkins View26 Test-Reporting Plugin improperly validates hostname

- advisories/github-reviewed/2022/09/GHSA-qgv4-7jhx-c72q/GHSA-qgv4-7jhx-c72q.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
This has been fixed in https://github.com/jenkinsci/rundeck-plugin/commit/ab63fbeba11dac081078cd9acbf40d03b4f6f2a4, shipped in 3.6.12
> [GHSA-qgv4-7jhx-c72q] Jenkins Rundeck Plugin Missing Authorization vulnerability

- advisories/github-reviewed/2022/07/GHSA-h5g3-v72x-hc6f/GHSA-h5g3-v72x-hc6f.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2083
> [GHSA-h5g3-v72x-hc6f] Plaintext Storage of a Password in Jenkins Jigomerge Plugin

- advisories/github-reviewed/2022/07/GHSA-2qh6-hhvv-m2ww/GHSA-2qh6-hhvv-m2ww.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update advisory details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-2053
The vulnerability has been addressed in 1.16: https://github.com/jenkinsci/http-request-plugin/releases/tag/http_request-1.16, SECURITY-2053
> [GHSA-2qh6-hhvv-m2ww] Jenkins HTTP Request Plugin stores HTTP Request passwords unencrypted

- advisories/github-reviewed/2022/09/GHSA-f7fq-wp2x-jc25/GHSA-f7fq-wp2x-jc25.json
**Updates**
- CVSS
- Description
**Comments**
Fill in details according to https://www.jenkins.io/security/advisory/2022-09-21/#SECURITY-2645
> [GHSA-f7fq-wp2x-jc25] Jenkins WildFly Deployer Plugin vulnerable to path traversal

- advisories/github-reviewed/2022/07/GHSA-j5qq-6rpm-qjgh/GHSA-j5qq-6rpm-qjgh.json
**Updates**
- CVSS
- Severity
- Summary
**Comments**
Provide advisory details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-2764
> [GHSA-j5qq-6rpm-qjgh] Jenkins Deployer Framework Plugin does not restrict application path of applications when configuring a deployment

- advisories/github-reviewed/2022/07/GHSA-449w-c77c-vmf6/GHSA-449w-c77c-vmf6.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Provide full advisory disclosure according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-284
> [GHSA-449w-c77c-vmf6] Jenkins Git Plugin before 4.11.4 provides unauthenticated attackers information about the existence of jobs

- advisories/github-reviewed/2022/07/GHSA-v878-67xw-grw2/GHSA-v878-67xw-grw2.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update advisory disclosure according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-284
> [GHSA-v878-67xw-grw2] Jenkins Git Plugin before 4.11.4 is missing a permission check

- advisories/github-reviewed/2022/07/GHSA-q4mr-j6w9-r2mr/GHSA-q4mr-j6w9-r2mr.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2798%20(2)
> [GHSA-q4mr-j6w9-r2mr] Missing Authorization in Jenkins Deployment Dashboard Plugin

- advisories/github-reviewed/2022/11/GHSA-562r-vg33-8x8h/GHSA-562r-vg33-8x8h.json
**Updates**
- Description
**Comments**
The wording in description was referring to a non-existing version 2.5.1, and there was a typo in the provided sample code.
> [GHSA-562r-vg33-8x8h] TemporaryFolder on unix-like systems does not limit access to created files

- advisories/github-reviewed/2022/07/GHSA-cm7j-p8hc-97vj/GHSA-cm7j-p8hc-97vj.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-1468
> [GHSA-cm7j-p8hc-97vj] Jenkins Git client plugin 3.11.0 does not perform SSH host key verification

- advisories/github-reviewed/2022/07/GHSA-8xwj-2wgh-gprh/GHSA-8xwj-2wgh-gprh.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Enhance disclosure of details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-284
> [GHSA-8xwj-2wgh-gprh] Jenkins Git Plugin before 4.11.4 allows attackers to trigger builds of jobs to use an attacker-specified Git repo

- advisories/github-reviewed/2022/07/GHSA-vpf7-q2rx-26mh/GHSA-vpf7-q2rx-26mh.json
**Updates**
- CVSS
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-2593
> [GHSA-vpf7-q2rx-26mh] Jenkins HashiCorp Vault Plugin does not perform permission checks in several HTTP endpoints that perform Vault connection tests

- advisories/github-reviewed/2022/07/GHSA-75fc-fv3p-xh82/GHSA-75fc-fv3p-xh82.json
**Updates**
- CVSS
- Description
**Comments**
Update advisory details with more information according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-2621
> [GHSA-75fc-fv3p-xh82] Jenkins Compuware Source Code Download is missing authorization

- advisories/github-reviewed/2022/07/GHSA-8528-c6m6-gppm/GHSA-8528-c6m6-gppm.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update advisory details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-1375%20(1)
> [GHSA-8528-c6m6-gppm] Jenkins OpenShift Deployer Plugin allows connection to attacker-specified URL using attacker-specified credentials

- advisories/github-reviewed/2022/07/GHSA-jvjh-9r4q-8q5q/GHSA-jvjh-9r4q-8q5q.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update advisory details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-1375%20(1)
> [GHSA-jvjh-9r4q-8q5q] Jenkins OpenShift Deployer Plugin does not perform a permission check in a method implementing form validation

- advisories/github-reviewed/2022/07/GHSA-5mv2-vqq7-mq5h/GHSA-5mv2-vqq7-mq5h.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update advisory details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-1375%20(2)
> [GHSA-5mv2-vqq7-mq5h] Jenkins OpenShift Deployer Plugin allows attackers to check for file path, upload SSH key file

- advisories/github-reviewed/2022/07/GHSA-78fg-pvgg-6g3r/GHSA-78fg-pvgg-6g3r.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update advisory details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-1375%20(2)
> [GHSA-78fg-pvgg-6g3r] OpenShift Deployer Plugin does not perform permission checks in methods implementing form validation

- advisories/github-reviewed/2022/07/GHSA-hm53-hrhh-gwfq/GHSA-hm53-hrhh-gwfq.json
**Updates**
- Description
- Summary
**Comments**
Update CVE specific details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-2105%20(1)
> [GHSA-hm53-hrhh-gwfq] Openstack Heat Plugin does not perform permission checks in methods implementing form validation

- advisories/github-reviewed/2022/07/GHSA-m485-79jq-cxx7/GHSA-m485-79jq-cxx7.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update advisory details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-2656
> [GHSA-m485-79jq-cxx7] Jenkins Google Cloud Backup Plugin allows attackers with Overall/Read permission to request a manual backup

- advisories/github-reviewed/2022/07/GHSA-5x3f-7m52-9cgf/GHSA-5x3f-7m52-9cgf.json
**Updates**
- CVSS
**Comments**
Update advisory details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-2790%20(2)
> [GHSA-5x3f-7m52-9cgf] Jenkins Coverity Plugin vulnerable to cross-site request forgery (CSRF)

- advisories/github-reviewed/2022/07/GHSA-99mq-hw5m-gwjj/GHSA-99mq-hw5m-gwjj.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update advisory details according to https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-2790%20(2)
> [GHSA-99mq-hw5m-gwjj] Jenkins Coverity Plugin is missing authorization, leading to Credential Capture

- advisories/github-reviewed/2022/05/GHSA-7qf3-c2q8-69m3/GHSA-7qf3-c2q8-69m3.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring and details according to https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-2153
> [GHSA-7qf3-c2q8-69m3] Improper Neutralization of Input During Web Page Generation in Jenkins

- advisories/github-reviewed/2022/05/GHSA-732f-w585-gmpc/GHSA-732f-w585-gmpc.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Fix CVSS scoring according to https://www.jenkins.io/security/advisory/2021-06-18/#SECURITY-2330
> [GHSA-732f-w585-gmpc] Jenkins Generic Webhook Trigger plugin 1.72 and earlier vulnerable to XML external entity (XXE) attacks

- advisories/github-reviewed/2022/05/GHSA-rc7h-x6cq-988q/GHSA-rc7h-x6cq-988q.json
**Updates**
- Description
- References
**Comments**
There is another fix in the 3.6 branch, with 3.6.10.Final - see https://issues.redhat.com/browse/JGRP-2055
3.6 is the branch prior to 4.0 branch, it was also fixed in 4.0.0.
> [GHSA-rc7h-x6cq-988q] Improper Input Validation in JGroups

- advisories/github-reviewed/2022/11/GHSA-wcjj-qm5v-j4pc/GHSA-wcjj-qm5v-j4pc.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2094
Also simplifies the version range
> [GHSA-wcjj-qm5v-j4pc] Jenkins Reverse Proxy Auth Plugin vulnerable due to plaintext storage of passwords

- advisories/github-reviewed/2022/11/GHSA-fv42-mx39-6fpw/GHSA-fv42-mx39-6fpw.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Fill in versions fixed according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2564
> [GHSA-fv42-mx39-6fpw] Jenkins Script Security Plugin vulnerable due to inadequate encryption strength

- advisories/github-reviewed/2022/11/GHSA-v535-pc6r-77qh/GHSA-v535-pc6r-77qh.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Fill in versions fixed according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2843
> [GHSA-v535-pc6r-77qh] Jenkins CloudBees Docker Hub/Registry Notification Plugin is missing permission checks

- advisories/github-reviewed/2022/11/GHSA-vj5r-mmp4-3hrx/GHSA-vj5r-mmp4-3hrx.json
**Updates**
- CVSS
- Severity
- Summary
**Comments**
Correct versions affected according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2910%20(2)
> [GHSA-vj5r-mmp4-3hrx] Jenkins NS-ND Integration Performance Publisher Plugin vulnerable due to improper certificate validation

- advisories/github-reviewed/2022/11/GHSA-4598-wcg8-x56g/GHSA-4598-wcg8-x56g.json
**Updates**
- CVSS
- Description
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-766
> [GHSA-4598-wcg8-x56g] XML External Entity Reference in Jenkins Violations Plugin

- advisories/github-reviewed/2022/11/GHSA-8847-xvjw-9g43/GHSA-8847-xvjw-9g43.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2937 and fix maven group and artifact name
> [GHSA-8847-xvjw-9g43] Jenkins OSF Builder Suite XML Linter Plugin vulnerable to XML external entity (XXE) attacks

- advisories/github-reviewed/2022/10/GHSA-4hjj-9gp7-4frg/GHSA-4hjj-9gp7-4frg.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Updates the maven group ID and adds another software component impacted by this CVE according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2824%20(2)
> [GHSA-4hjj-9gp7-4frg] Jenkins Pipeline: Groovy Libraries Plugin vulnerable to Protection Mechanism Failure

- advisories/github-reviewed/2022/10/GHSA-7qw2-h9gj-hcvh/GHSA-7qw2-h9gj-hcvh.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Updates the maven group ID and adds another software component impacted by this CVE according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2824%20(2)
> [GHSA-7qw2-h9gj-hcvh] Jenkins Pipeline: Deprecated Groovy Libraries Plugin vulnerable to Protection Mechanism Failure

- advisories/github-reviewed/2022/10/GHSA-g66m-fqxf-3w35/GHSA-g66m-fqxf-3w35.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Correct CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2880
> [GHSA-g66m-fqxf-3w35] Jenkins Pipeline: Input Step Plugin vulnerable to Inappropriate Encoding for Output Context

- advisories/github-reviewed/2022/10/GHSA-j7pg-863g-22p6/GHSA-j7pg-863g-22p6.json
**Updates**
- Description
- Summary
**Comments**
Provide details about the actual endpoint affected according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2831
> [GHSA-j7pg-863g-22p6] Jenkins Mercurial Plugin provides info about jobs triggered or scheduled for polling through webhook endpoint

- advisories/github-reviewed/2022/10/GHSA-f9f9-4r63-4qcc/GHSA-f9f9-4r63-4qcc.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2877
> [GHSA-f9f9-4r63-4qcc] Jenkins GitLab Plugin potentially allows attackers to use statistical methods to obtain valid webhook token

- advisories/github-reviewed/2022/10/GHSA-2w2m-ccf8-57cq/GHSA-2w2m-ccf8-57cq.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2337
> [GHSA-2w2m-ccf8-57cq] Jenkins REPO Plugin does not configure XML parser to prevent XXE attacks

- advisories/github-reviewed/2022/12/GHSA-q5j9-f95w-f4pr/GHSA-q5j9-f95w-f4pr.json
**Updates**
**Comments**
"Affected versions" and "Patched versions" were wrong.
The vulnerability is due to Terasorna-gfw-common 1.0.0.RELEASE.
Therefore, upgrading to at least 1.0.1.RELEASE can avoid the vulnerability.
> [GHSA-q5j9-f95w-f4pr] TERASOLUNA Server Framework vulnerable to ClassLoader manipulation

- advisories/github-reviewed/2022/10/GHSA-x8j7-vxh9-p67g/GHSA-x8j7-vxh9-p67g.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2845%20(2)
> [GHSA-x8j7-vxh9-p67g] Jenkins Katalon Plugin vulnerable to Cross-Site Request Forgery

- advisories/github-reviewed/2022/10/GHSA-35rx-7pc8-6963/GHSA-35rx-7pc8-6963.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2846
> [GHSA-35rx-7pc8-6963] Jenkins Katalon Plugin stores API keys unencrypted

- advisories/github-reviewed/2022/10/GHSA-vhwv-8897-jm7q/GHSA-vhwv-8897-jm7q.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2625
> [GHSA-vhwv-8897-jm7q] Jenkins Compuware Topaz for Total Test Plugin does not configure its XML parser to prevent XXE attacks

- advisories/github-reviewed/2022/10/GHSA-px4x-hjm5-w8x3/GHSA-px4x-hjm5-w8x3.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2863
> [GHSA-px4x-hjm5-w8x3] Jenkins XFramium Builder Plugin disables Content-Security-Policy protection for user-generated content

- advisories/github-reviewed/2022/10/GHSA-cvxj-4745-843x/GHSA-cvxj-4745-843x.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2864
> [GHSA-cvxj-4745-843x] Jenkins ScreenRecorder Plugin disables Content-Security-Policy protection for user-generated content

- advisories/github-reviewed/2022/10/GHSA-wmfh-h3vm-rcxm/GHSA-wmfh-h3vm-rcxm.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2865
This has been fixed in https://github.com/jenkinsci/neuvector-vulnerability-scanner-plugin/commit/e0a72373ef1c20c41b8eb086883a7090cf04809c, which has been released in 1.22
> [GHSA-wmfh-h3vm-rcxm] Jenkins NeuVector Vulnerability Scanner Plugin disables Content-Security-Policy protection for user-generated content

- advisories/github-reviewed/2022/10/GHSA-7rrj-hqv6-fvpp/GHSA-7rrj-hqv6-fvpp.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2866
> [GHSA-7rrj-hqv6-fvpp] Jenkins 360 FireLine Plugin disables Content-Security-Policy protection for user-generated content

- advisories/github-reviewed/2022/05/GHSA-43j2-r4v3-m8jp/GHSA-43j2-r4v3-m8jp.json
**Updates**
- CVSS
- Description
- Summary
**Comments**
Correct maven artifact ID according to https://www.jenkins.io/security/advisory/2020-05-06/#SECURITY-1374
> [GHSA-43j2-r4v3-m8jp] Insufficiently Protected Credentials in Jenkins Credentials Binding Plugin

- advisories/github-reviewed/2022/05/GHSA-7ff8-qfwx-8gx5/GHSA-7ff8-qfwx-8gx5.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Fix maven artifact ID according to https://www.jenkins.io/security/advisory/2020-05-06/#SECURITY-1835
> [GHSA-7ff8-qfwx-8gx5] Insufficiently Protected Credentials in Jenkins Credentials Binding Plugin

- advisories/github-reviewed/2022/11/GHSA-4vrc-q7m6-vq7w/GHSA-4vrc-q7m6-vq7w.json
**Updates**
**Comments**
The package is wrong. Actually, the lin-cms for python 0.2.1 has not been released. I think the actual package is for Java.
> [GHSA-4vrc-q7m6-vq7w] Lin CMS vulnerable to Improper Authentication

- advisories/github-reviewed/2022/12/GHSA-54r5-wr8x-x5v3/GHSA-54r5-wr8x-x5v3.json
**Updates**
- CVSS
- CWEs
- Description
- References
- Severity
**Comments**
**I am the Apiman project's co-founder and maintainer, Marc Savy.**
GitHub Analogy:
Think of this like someone being able to use GitHub's APIs to discover and clone a repo from someone else's private GitHub org. 
It's not just the fact you managed to read data about that private org that's the problem — you also got access to the contents of the repository when you shouldn't have, which may contain sensitive information.
I hope that makes sense.
> [GHSA-54r5-wr8x-x5v3] Apiman has insufficient checks for read permissions

- advisories/github-reviewed/2022/05/GHSA-8wcw-cw2f-h4g2/GHSA-8wcw-cw2f-h4g2.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2020-11-04/#SECURITY-2099
> [GHSA-8wcw-cw2f-h4g2] Improper Authentication (empty password) in Jenkins Active Directory Plugin

- advisories/github-reviewed/2022/05/GHSA-954f-xw44-56r2/GHSA-954f-xw44-56r2.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2020-11-04/#SECURITY-2123
> [GHSA-954f-xw44-56r2] Authentication cache in Active Directory Jenkins Plugin allows logging in with any password

- advisories/github-reviewed/2022/05/GHSA-x58r-wxc3-7pqr/GHSA-x58r-wxc3-7pqr.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Update CVSS scoring according to https://www.jenkins.io/security/advisory/2020-11-04/#SECURITY-2115
> [GHSA-x58r-wxc3-7pqr] Improper Restriction of XML External Entity Reference in Jenkins Mercurial Plugin

- advisories/github-reviewed/2022/11/GHSA-7fxm-c848-89q8/GHSA-7fxm-c848-89q8.json
**Updates**
**Comments**
Requesting to attribute and credit this vulnerability to GitHub user @lirantal, who discovered and reported the vulnerability to Snyk.
> [GHSA-7fxm-c848-89q8] static-dev-server vulnerable to path traversal

- advisories/github-reviewed/2021/12/GHSA-5cqm-crxm-6qpv/GHSA-5cqm-crxm-6qpv.json
**Updates**
**Comments**
This issue was fixed in commit https://github.com/ruby/cgi/commit/ad079c1cb5f58eba1ffac46da79995fcf94a3a6e for 0.1.0.1 version.
> [GHSA-5cqm-crxm-6qpv] Buffer overrun in CGI.escape_html

- advisories/github-reviewed/2022/09/GHSA-42hx-vrxx-5r6v/GHSA-42hx-vrxx-5r6v.json
**Updates**
**Comments**
I'm not sure if this is the proper way to mark all versions as affected, sorry if that's not the case. There is no fixed version for this issue currently.
When this advisory was created, the last released version was 3.19.5. Since then, newer versions have been released, but the issue is still not fixed (see the changelog for 3.20.1 https://github.com/xdan/jodit/blob/master/CHANGELOG.md#3201, released right after 3.19.5).
> [GHSA-42hx-vrxx-5r6v] Jodit Editor vulnerable to Cross-site Scripting

- advisories/github-reviewed/2022/01/GHSA-4vf4-qmvg-mh7h/GHSA-4vf4-qmvg-mh7h.json
**Updates**
**Comments**
Sync versions with https://github.com/rubysec/ruby-advisory-db/blob/master/gems/cgi/CVE-2021-41819.yml
> [GHSA-4vf4-qmvg-mh7h] Cookie prefix spoofing in CGI

- advisories/github-reviewed/2021/12/GHSA-qrmm-w75w-3wpx/GHSA-qrmm-w75w-3wpx.json
**Updates**
**Comments**
Swashbuckle repackages the swagger-ui-dist npm package and thus inherits the vulnerability. Fixed in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/401c7cb81e5efe835ceb8aae23e82057d57c7d29 and released in 6.4.
> [GHSA-qrmm-w75w-3wpx] Server side request forgery in SwaggerUI

- advisories/github-reviewed/2022/11/GHSA-hgp8-w8fj-r4cm/GHSA-hgp8-w8fj-r4cm.json
**Updates**
**Comments**
There is no package just named `tooljet` on npmjs.com.
> [GHSA-hgp8-w8fj-r4cm] ToolJet is vulnerable to Denial of Service (DoS)

- advisories/github-reviewed/2022/04/GHSA-h6xw-mghq-7523/GHSA-h6xw-mghq-7523.json
**Updates**
- References
**Comments**
The fix is in v1.2.0.
Check this for reference : https://github.com/waycrate/swhkd/releases/tag/1.2.0
> [GHSA-h6xw-mghq-7523] Unsafe parsing in SWHKD

- advisories/github-reviewed/2022/11/GHSA-g56w-cwg4-hxx9/GHSA-g56w-cwg4-hxx9.json
**Updates**
**Comments**
As indicated in https://github.com/quarkusio/quarkus/discussions/29527#discussioncomment-4387809 the affected package is:
`io.quarkus:quarkus-vertx-http-deployment` and not `io.quarkus:quarkus-parent`
> [GHSA-g56w-cwg4-hxx9] Code injection in quarkus dev ui config editor

- advisories/github-reviewed/2022/07/GHSA-8jmw-wjr8-2x66/GHSA-8jmw-wjr8-2x66.json
**Updates**
- CWEs
**Comments**
To be precise, this vulnerability should actually be specified as CWE-88
> [GHSA-8jmw-wjr8-2x66] Command injection in git-clone

- advisories/github-reviewed/2023/01/GHSA-3xq5-wjfh-ppjc/GHSA-3xq5-wjfh-ppjc.json
**Updates**
**Comments**
Original maintainer advisory says 1.28.1.  Looks like conversion to general GHSA typo'd this at 1.38.1.  As such, fixing version to recent tag does not allow audits to pass as they are looking for 1.38.1.
> [GHSA-3xq5-wjfh-ppjc] Luxon Inefficient Regular Expression Complexity vulnerability

- advisories/github-reviewed/2022/12/GHSA-hh82-3pmq-7frp/GHSA-hh82-3pmq-7frp.json
CVSS vector is not correct, it should be:
CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N
but is:
CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:N
> Fix GHSA-hh82-3pmq-7frp CVSS vector

- advisories/github-reviewed/2022/01/GHSA-9783-42pm-x5jq/GHSA-9783-42pm-x5jq.json
**Updates**
- References
**Comments**
The issue is fixed refer : https://github.com/jblondin/csv-sniffer/pull/2
> [GHSA-9783-42pm-x5jq] Use of Uninitialized Resource in csv-sniffer.

- advisories/github-reviewed/2022/11/GHSA-hrpp-h998-j3pp/GHSA-hrpp-h998-j3pp.json
**Updates**
- Description
- References
**Comments**
This issue is not specific to Express and affects multiple web frameworks that use `qs` for query string parsing, and having it in there incorrectly flags older Express versions with looser `qs` dependencies or yarn and other override configurations that update the `qs` version. Only `qs` module needs to be updated, no specific code change was done in the `express` module itself to mitigate the issue outlined.
> [GHSA-hrpp-h998-j3pp] qs vulnerable to Prototype Pollution

- advisories/github-reviewed/2020/02/GHSA-mxhp-79qh-mcx6/GHSA-mxhp-79qh-mcx6.json
**Updates**
- Description
- References
- Summary
**Comments**
The original research at https://www.usenix.org/system/files/sec21-xiao.pdf indicates that taffydb version 2.7.3 is vulnerable. Version 2.7.3 is the latest version of taffydb available at https://www.npmjs.com/package/taffydb. 
Snyk published CVE-2019-10790 and omitted the issue with "taffydb" and the affected newer versions. Their own vulnerability database is accurate: https://security.snyk.io/vuln/SNYK-JS-TAFFYDB-2992450
> [GHSA-mxhp-79qh-mcx6] taffy can allow access to any data items in the DB

- advisories/github-reviewed/2023/01/GHSA-579w-22j4-4749/GHSA-579w-22j4-4749.json
**Updates**
- Description
**Comments**
Based on this release note https://rubyonrails.org/2023/1/17/Rails-Versions-6-0-6-1-6-1-7-1-7-0-4-1-have-been-released also the version 6.0.6.1 is fixing this vulnerability
> [GHSA-579w-22j4-4749] Denial of Service Vulnerability in ActiveRecord’s PostgreSQL adapter

- advisories/github-reviewed/2023/01/GHSA-8xww-x3g3-6jcv/GHSA-8xww-x3g3-6jcv.json
**Updates**
- Description
**Comments**
Based on this release note https://rubyonrails.org/2023/1/17/Rails-Versions-6-0-6-1-6-1-7-1-7-0-4-1-have-been-released also the version 6.0.6.1 is fixing this vulnerability
> [GHSA-8xww-x3g3-6jcv] ReDoS based DoS vulnerability in Action Dispatch

- advisories/github-reviewed/2023/01/GHSA-j6gc-792m-qgm2/GHSA-j6gc-792m-qgm2.json
**Updates**
- Description
**Comments**
Based on this release note https://rubyonrails.org/2023/1/17/Rails-Versions-6-0-6-1-6-1-7-1-7-0-4-1-have-been-released also the version 6.0.6.1 is fixing the vulnerability
> [GHSA-j6gc-792m-qgm2] ReDoS based DoS vulnerability in Active Support’s underscore

- advisories/github-reviewed/2021/03/GHSA-2cxf-6567-7pp6/GHSA-2cxf-6567-7pp6.json
**Updates**
**Comments**
Please see https://github.com/google/osv.dev/issues/1002#issuecomment-1409795116 for full context.
Introduced: 0, Fixed: 1.0.0-beta.9 includes "1.0.0-beta10" and "1.0.0-beta11" according to Maven's version ordering rules. 
This does not appear to be intentional. 
Instead we set Introduced to 1.0.0-beta.6, which is the very first available version (and it doesn't include the erroneus  "1.0.0-beta10" and "1.0.0-beta11" versions.
> [GHSA-2cxf-6567-7pp6] Local Information Disclosure Vulnerability

- advisories/github-reviewed/2023/01/GHSA-p84v-45xj-wwqj/GHSA-p84v-45xj-wwqj.json
**Updates**
- Description
**Comments**
The original Rails advisory for [CVE-2023-22792](https://discuss.rubyonrails.org/t/cve-2023-22792-possible-redos-based-dos-vulnerability-in-action-dispatch/82115) states that there is no fixed version for actionpack 6.0.x.
> [GHSA-p84v-45xj-wwqj] ReDoS based DoS vulnerability in Action Dispatch

- advisories/github-reviewed/2022/02/GHSA-3c7p-vv5r-cmr5/GHSA-3c7p-vv5r-cmr5.json
**Updates**
- References
**Comments**
The patch for SOLR-14663 (CVE-2020-13957) is in 8.6.3, *not* 8.6.2 - https://github.com/apache/solr/commit/e001c2221812a0ba9e9378855040ce72f93eced4. Furthermore, since there is no LTS patch for 7.x and the Solr project itself is only tracking fixes for 8.x/9.x (see SOLR-14925 https://issues.apache.org/jira/browse/SOLR-14925), if the 7.x version is to be the *minimum* version bump required to fix the issue it should agree with the 8.x patch which is 8.6.3.
> [GHSA-3c7p-vv5r-cmr5] Incorrect Authorization in Apache Solr

- advisories/github-reviewed/2023/02/GHSA-6pm2-j2v8-h3cj/GHSA-6pm2-j2v8-h3cj.json
**Updates**
**Comments**
The metasploit-framework is not affected by this vulnerability.
> [GHSA-6pm2-j2v8-h3cj] Fortra GoAnywhere MFT Deserialization of Untrusted Data vulnerability affects metasploit-framework

- advisories/github-reviewed/2023/02/GHSA-8x6c-cv3v-vp6g/GHSA-8x6c-cv3v-vp6g.json
**Updates**
- CVSS
- CWEs
- Severity
- Summary
**Comments**
This advisory should be deleted because (as stated in description) it is NO vulnerability within this package but an problem with a dependency only. And all latest versions of this package "cacheable-request" use an semver range for the vulnerable "http-cache-semantics" allowing them to simply update to the secured "http-cache-semantics@4.1.1".
There is no vulnerability in this package and this package works with secured dependency without changes needed.
Therefore no security thread and no advisory needed.
> [GHSA-8x6c-cv3v-vp6g] cacheable-request depends on http-cache-semantics, which is vulnerable to Regular Expression Denial of Service

- advisories/github-reviewed/2022/05/GHSA-fj6c-prgj-gr3r/GHSA-fj6c-prgj-gr3r.json
**Updates**
**Comments**
Similar to https://github.com/github/advisory-database/pull/1714, this sets an upper bound on the 5.x branch.
> [GHSA-fj6c-prgj-gr3r] Improper Limitation of a Pathname to a Restricted Directory in Apache Tomcat

- advisories/github-reviewed/2023/02/GHSA-2hrw-hx67-34x6/GHSA-2hrw-hx67-34x6.json
**Updates**
**Comments**
Range >= 4.0.0, <= 4.1.7 was not in line with textual description of the affected versions and cause a false-positive when using 4.0.10
> [GHSA-2hrw-hx67-34x6] Resource exhaustion in Django

- advisories/github-reviewed/2022/02/GHSA-x4rg-4545-4w7w/GHSA-x4rg-4545-4w7w.json
**Updates**
**Comments**
"2019.02.25.00" is not a valid SemVer or Go module version (i.e. it's not possible to install a Go package at such a version).
This change aligns this entry with https://pkg.go.dev/vuln/GO-2021-0088
> [GHSA-x4rg-4545-4w7w] Improper Input Validation and Excessive Iteration in Go Facebook Thrift

- advisories/github-reviewed/2021/05/GHSA-2w7w-2j92-44hx/GHSA-2w7w-2j92-44hx.json
**Updates**
**Comments**
The current OSV entry has this as the encoding for one of the ranges:
```
"ranges": [
{
"type": "ECOSYSTEM",
"events": [
{
"introduced": "0"
}
]
}
],
```
This incorrectly means that every version is affected according to the OSV schema's evaluation rules. Add a patch version explicitly to have the "fix" version be reflected for the "10.1.*" branch as an upper bound.
> [GHSA-2w7w-2j92-44hx] HTTP Request Smuggling in akka-http-core

- advisories/github-reviewed/2022/05/GHSA-9qh2-6fxg-9m4g/GHSA-9qh2-6fxg-9m4g.json
**Updates**
- References
**Comments**
Change 1) 
version: The following commit which adds a length check was included in version 1.1.2  https://github.com/BYVoid/OpenCC/commit/4a4f9e58e505fca93605f22363c133df66a91a5e it was originally part of PR560 ( https://github.com/BYVoid/OpenCC/pull/560 )
Change 2)
pip: OpenCC is also available in pip via pypi  https://pypi.org/project/OpenCC/
> [GHSA-9qh2-6fxg-9m4g] Open Chinese Convert subject to Denial of Service via Out-of-bounds Read

- advisories/github-reviewed/2022/09/GHSA-gwc9-m7rh-j2ww/GHSA-gwc9-m7rh-j2ww.json
**Updates**
- Description
**Comments**
In the announcement it is mentioned that the attacker can be unauthenticated. That's an important distinction.
> [GHSA-gwc9-m7rh-j2ww] x/crypto/ssh vulnerable to panic via SSH server

- advisories/github-reviewed/2019/05/GHSA-ww4x-rwq6-qpgf/GHSA-ww4x-rwq6-qpgf.json
**Updates**
- Description
**Comments**
omniauth 1.9.2 fixes an unrelated security issue, and is just as vulnerable to this problem as omniauth 1.9.1.
https://github.com/omniauth/omniauth/releases/tag/v1.9.2
> [GHSA-ww4x-rwq6-qpgf] Cross-site Request Forgery in OmniAuth

- advisories/github-reviewed/2022/03/GHSA-xvch-5gv4-984h/GHSA-xvch-5gv4-984h.json
**Updates**
- Description
- References
**Comments**
Published a backport.
> [GHSA-xvch-5gv4-984h] Prototype Pollution in minimist

- advisories/github-reviewed/2018/10/GHSA-p699-3wgc-7h72/GHSA-p699-3wgc-7h72.json
**Updates**
- Description
- Summary
**Comments**
This vulnerability is related to another package org.apache.tika:tika-parsers. Please see this commit: https://github.com/apache/tika/commit/1b6ca3685c196cfd89f5f95c19cc919ce10c5aff#diff-43f8cbe58aaab159ce88bd95fafc46dd
> [GHSA-p699-3wgc-7h72] Moderate severity vulnerability that affects org.apache.tika:tika-core

- advisories/github-reviewed/2023/02/GHSA-x4qr-2fvf-3mr5/GHSA-x4qr-2fvf-3mr5.json
**Updates**
- CVSS
- Severity
**Comments**
The official CVE sites list CVE-2023-0286 as being a high attack complexity (see https://nvd.nist.gov/vuln/detail/CVE-2023-0286, https://access.redhat.com/security/cve/cve-2023-0286)
> [GHSA-x4qr-2fvf-3mr5] Vulnerable OpenSSL included in cryptography wheels

- advisories/github-reviewed/2019/01/GHSA-wjxj-f8rg-99wx/GHSA-wjxj-f8rg-99wx.json
**Updates**
- Description
**Comments**
https://github.com/apache/thrift/releases/tag/0.9.3.1 describes that CVE-2018-1320 has been fixed there by implementing https://issues.apache.org/jira/browse/THRIFT-4506.
> [GHSA-wjxj-f8rg-99wx] Improper Input Validation in Apache Thrift

- advisories/github-reviewed/2022/11/GHSA-vqp6-rc3h-83cp/GHSA-vqp6-rc3h-83cp.json
**Updates**
**Comments**
The package described is not the import path of the module.
This makes the package unable to detect by scanners.
> [GHSA-vqp6-rc3h-83cp] Tailscale Windows daemon is vulnerable to RCE via CSRF

- advisories/github-reviewed/2023/03/GHSA-6q8m-42qq-64r7/GHSA-6q8m-42qq-64r7.json
Copied/following from #1744 to fix a minor mistake in 'fixed' version fields.
**Updates**
- CVSS
- References
- Severity
**Comments**
I am part of the team that submitted the CVE Request. Due to confusion in communicating versioning, this advisory appears to be incorrect. We marked the CVE as impacting Zowe versions < 1.28.2 or < 2.5.0 which is understood by many of our consumers, but not by automation. We'll fix this going forward. The actual Imperative versions affected are < 4.18.10 or >= 5.0.0, < 5.7.1, and the PRs which fixed the issue were added to the references section.  As for verifying my authenticity, I am a Zowe Organization Owner/Administrator and Zowe CLI Squad Member (which owns the Imperative framework). I can provide additional information if required, …
> Improve https://github.com/advisories/GHSA-6q8m-42qq-64r7

- advisories/github-reviewed/2022/09/GHSA-3mq5-fq9h-gj7j/GHSA-3mq5-fq9h-gj7j.json
**Updates**
**Comments**
Source code link is wrong. Also, the canonical advisory with better info is GHSA-f8cc-g7j8-xxpm which is *technically* a duplicate but was submitted and enriched by the xstream team and should be considered ground truth over this advisory.
> [GHSA-3mq5-fq9h-gj7j] Denial of Service due to parser crash

- advisories/github-reviewed/2022/05/GHSA-3295-h9qx-r82x/GHSA-3295-h9qx-r82x.json
**Updates**
**Comments**
v1.0.7 of acegi-security appears to be listed as affected in the original announcement url (per Internet Archive) https://web.archive.org/web/20110802082343/http://www.springsource.com/security/cve-2010-3700, and there appear to be no fixed versions released
> [GHSA-3295-h9qx-r82x] Authentication Bypass Using an Alternate Path or Channel in SpringSource Spring Security and Acegi Security

- advisories/github-reviewed/2022/10/GHSA-wrx5-rp7m-mm49/GHSA-wrx5-rp7m-mm49.json
**Updates**
- Affected products: None
- CVSS: None
- Description: Rejected
- Severity: None
**Comments**
This issue got dismissed: https://nvd.nist.gov/vuln/detail/CVE-2022-41852
We should remove it from the GitHub Advisory database.
Do we have a procedure for such cases somewhere?
Thanks!
> [GHSA-wrx5-rp7m-mm49] JXPath vulnerable to remote code execution when interpreting untrusted XPath expressions: Rejected

- advisories/github-reviewed/2022/06/GHSA-75rw-34q6-72cr/GHSA-75rw-34q6-72cr.json
**Updates**
**Comments**
The affected Go package github.com/biscuit-auth/biscuit-go was released in semantic version 2.0.0, instead of 2.0. This change also makes it compliant to the semantic versioning scheme natively used in Go.
> [GHSA-75rw-34q6-72cr] Signature forgery in Biscuit

- advisories/github-reviewed/2019/01/GHSA-mc23-976p-j42x/GHSA-mc23-976p-j42x.json
**Updates**
**Comments**
The affected version was mistakenly listed as `>= 3.10`, whereas `>= 3.10.0` would be semantically correct. See https://github.com/xtermjs/xterm.js/releases/tag/3.10.0 for reference.
> [GHSA-mc23-976p-j42x] xterm vulnerable to remote code execution 

- advisories/github-reviewed/2023/02/GHSA-qpm3-vr34-h8w8/GHSA-qpm3-vr34-h8w8.json
**Updates**
**Comments**
The fix is been made in v2.5.0-beta.1 
Refer : https://pkg.go.dev/vuln/GO-2023-1567
> [GHSA-qpm3-vr34-h8w8] Open Redirect in Caddy

- advisories/github-reviewed/2018/10/GHSA-6x9x-8qw9-9pp6/GHSA-6x9x-8qw9-9pp6.json
**Updates**
**Comments**
https://bugs.eclipse.org/bugs/show_bug.cgi?id=535669 indicates that All EOL releases - 9.2.x and older (all configurations) are affected, so adjusting the ranges to reflect that
> [GHSA-6x9x-8qw9-9pp6] Jetty vulnerable to authorization bypass due to inconsistent HTTP request handling (HTTP Request Smuggling)

- advisories/github-reviewed/2022/10/GHSA-5hq7-j5wq-p227/GHSA-5hq7-j5wq-p227.json
**Updates**
- References
**Comments**
* Removed two redundant references that both redirected to other, already cited csirt.divd.nl references
* The affected version was mistakenly listed as >= 6.0, whereas only >= 6.0.0 is semantically correct. See https://github.com/feathersjs-ecosystem/feathers-sequelize/releases/tag/v6.0.0 for reference.
> [GHSA-5hq7-j5wq-p227] feathers-sequelize vulnerable to SQL injection due to improper parameter filtering

- advisories/github-reviewed/2023/03/GHSA-933g-v89r-x8pf/GHSA-933g-v89r-x8pf.json
**Updates**
**Comments**
2.7.22 contains the fix for the CVE.
> [GHSA-933g-v89r-x8pf] Apache Dubbo vulnerable to Deserialization of Untrusted Data

- advisories/github-reviewed/2023/03/GHSA-jh36-q97c-9928/GHSA-jh36-q97c-9928.json
**Updates**
**Comments**
fix version typo
this is the 2nd or 3rd version typo that's caused programmatic issues when reading GHSAs - recommend a static analysis check as part of acceptance to remove these errors
> [GHSA-jh36-q97c-9928] Kubernetes vulnerable to validation bypass

- advisories/github-reviewed/2022/05/GHSA-4wrc-f8pq-fpqp/GHSA-4wrc-f8pq-fpqp.json
**Updates**
- Description
- Summary
**Comments**
The offending feature has been deprecated much earlier than 6.0; 6.0 actually removes the feature. Replaced commit links with actual issue links to document that.
> [GHSA-4wrc-f8pq-fpqp] Pivotal Spring Framework contains unsafe Java deserialization methods

- advisories/github-reviewed/2022/08/GHSA-chw2-6c7r-37p7/GHSA-chw2-6c7r-37p7.json
> A fix is available on the main branch of the repository.
https://github.com/litejs/uri-template-lite/commit/cbeec2b2a275d819fb534137a155df14729706f8 > https://github.com/litejs/uri-template-lite/commits/v22.9.0
> GHSA-chw2-6c7r-37p7: add fixed version

- advisories/github-reviewed/2021/12/GHSA-7rpj-hg47-cx62/GHSA-7rpj-hg47-cx62.json
**Updates**
- Description
- References
**Comments**
the first affected version is 1.4.198 (as of 1/03/2022)
see: 
- https://nvd.nist.gov/vuln/detail/CVE-2021-23463
- https://github.com/h2database/h2database/pull/3199#issuecomment-1002830390
The removed Oracle link was designated as "not applicable" and removed on 4/28/2022
> [GHSA-7rpj-hg47-cx62] Improper Restriction of XML External Entity Reference in com.h2database:h2.

- README.md
Wording modeled after GitHub docs: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/about-repository-security-advisories
> Adding sources of advisories to README

- advisories/github-reviewed/2021/05/GHSA-x5r6-x823-9848/GHSA-x5r6-x823-9848.json
**Updates**
- Description
- References
**Comments**
The affected version is incorrect. It should be <2.1.0
When reviewing the pull (https://github.com/418sec/json-ptr/pull/3), the comment "Fixed in v2.1.0 and above." denotes when the fix occurred. 
Additionally, the apply for the fix: "I went ahead applied the fix for flitbit#30 (Eli's alternative), which also fixes flitbit#28, supplied the missing tests, and I put it in a branch in the underlying repo, which was slightly ahead of your fork (I had already updated dependencies to address other security warnings)." 
This confirms the following patch link: https://github.com/flitbit/json-ptr/commit/2539e3494c80af1eef24f0f433654a61f255f011, which is present here: https://github.com/flitbit/json-ptr/compare/v2.0.0...v2.1.0 …
> [GHSA-x5r6-x823-9848] Arbitrary Code Execution in json-ptr

- advisories/github-reviewed/2021/08/GHSA-xmr7-v725-2jjr/GHSA-xmr7-v725-2jjr.json
**Updates**
- References
**Comments**
Adding the patch link for the advisory (https://github.com/kivikakk/comrak/commit/b3efbb6e427bcd33bb14db45753ad4fd98e0f5bf).
As mentioned in the changelog (https://github.com/kivikakk/comrak/releases/tag/0.9.1): "SECURITY: we were matching unsafe URL prefixes, such as data: or javascript:, in a case-sensitive manner. This meant prefixes like Data: were untouched. Please upgrade as soon as possible. (Kouhei Morita)"
> [GHSA-xmr7-v725-2jjr] XSS in comrak

- advisories/github-reviewed/2020/02/GHSA-cqqj-4p63-rrmm/GHSA-cqqj-4p63-rrmm.json
**Updates**
**Comments**
User submitted issue here: https://github.com/github/advisory-database/issues/1809#issue-1635568293
"the affected package is incorrect. the file that's edited in the patch commit (https://github.com/netty/netty/pull/9871/files#diff-e26989b9171ef22c27c9f7d80689cfb059d568c9bd10e75970d96c02d0654878) is of the package io.netty:netty-codec-http and not io.netty:netty-handler as currently mapped."
> [GHSA-cqqj-4p63-rrmm] HTTP Request Smuggling in Netty

- advisories/github-reviewed/2022/05/GHSA-jwpw-q68h-r678/GHSA-jwpw-q68h-r678.json
**Updates**
- References
**Comments**
This is actually a duplicate of GHSA-9324-jv53-9cc8, can we merge these as the same one? Also can we link this to the repo if they are not available for merge?
> [GHSA-jwpw-q68h-r678] Improper Neutralization of CRLF Sequences in dio

- advisories/github-reviewed/2023/03/GHSA-xrqq-wqh4-5hg2/GHSA-xrqq-wqh4-5hg2.json
**Updates**
- CVSS
- CWEs
- Description
- Severity
**Comments**
The assigned CVE is a false-positive, the described cross-site scripting vulnerability of `v0.15.4` of the package is invalid. Please reject the corresponding CVE in order to resolve current issues with Dependabot, packagist.org and the `roave/security-advisories` package (which all use GitHub advisories as their source of truth). Investigations are available at https://github.com/darylldoyle/svg-sanitizer/issues/88
> [GHSA-xrqq-wqh4-5hg2] svg-sanitizer has Cross-site Scripting Bypass

- advisories/github-reviewed/2022/09/GHSA-m7w4-q5vg-5xfp/GHSA-m7w4-q5vg-5xfp.json
**Updates**
**Comments**
Using the actual package import path so that scanners can find this package.
the actual import path is `github.com/mattermost/mattermost-server/v6` as shown [here](https://github.com/mattermost/mattermost-server/blob/master/go.mod)
> [GHSA-m7w4-q5vg-5xfp] Mattermost subject to Denial of Service via upload of special GIF

- advisories/github-reviewed/2021/11/GHSA-458f-26r3-x2c3/GHSA-458f-26r3-x2c3.json
**Updates**
- References
**Comments**
Adding the patch link (https://github.com/schollz/rwtxt/commit/c09fb17375c4c47b49524c688288af1fe20e730a)
In the commit, the developer started to introduce bluemonday.UGCPolicy().Sanitize, which is specifically designed to scrub user-generated content of XSS. More info here on the sanitization function: https://github.com/microcosm-cc/bluemonday.
Additionally, this was the only commit within the history related to XSS.
> [GHSA-458f-26r3-x2c3] Cross-site Scripting in github.com/schollz/rwtxt

- advisories/github-reviewed/2018/10/GHSA-45xm-v8gq-7jqx/GHSA-45xm-v8gq-7jqx.json
**Updates**
- References
**Comments**
Adding the patch link (https://github.com/eclipse-vertx/vert.x/commit/269a583330695d1418a4f5578f7169350b2e1332)
The CVE is in the commit message and references the same issue link (2648): "CVE-2018-12541: When a WebSocket upgrade has a body > 8192 send an appropriate response immediately and close the connection afterward. - fixes #2648"
> [GHSA-45xm-v8gq-7jqx] Excessive memory allocation

- advisories/github-reviewed/2020/01/GHSA-6x3v-rw2q-9gx7/GHSA-6x3v-rw2q-9gx7.json
**Updates**
- References
**Comments**
Hi, as I can see, a fix for 9.4.x branch was committed and is part of 9.4.15: https://github.com/infinispan/infinispan/pull/7043 I hope I made the change in a correct way.
> [GHSA-6x3v-rw2q-9gx7] Improper implementation of the session fixation protection in Infinispan

- advisories/github-reviewed/2020/09/GHSA-46m8-42hm-wvvw/GHSA-46m8-42hm-wvvw.json
**Updates**
- References
**Comments**
Adding the patch link (https://github.com/joypixels/emojione/commit/613079b16c00e47fb3c44744a67ed88a9295afb1)
Issue 61 (https://github.com/joypixels/emojione/issues/61) recommends how to update the escaping function. In the commit (https://github.com/joypixels/emojione/commit/613079b16c00e47fb3c44744a67ed88a9295afb1), it's a replication of the advice in the issue to resolve the XSS vulnerability.
> [GHSA-46m8-42hm-wvvw] Cross-Site Scripting in emojione

- advisories/github-reviewed/2022/04/GHSA-558x-2xjg-6232/GHSA-558x-2xjg-6232.json
**Updates**
**Comments**
Spring only started stripping .RELEASE from their version strings with 5.3.0.
https://repo1.maven.org/maven2/org/springframework/spring-expression/
> [GHSA-558x-2xjg-6232] Allocation of Resources Without Limits or Throttling in Spring Framework

- advisories/github-reviewed/2022/11/GHSA-4p38-rc98-cr39/GHSA-4p38-rc98-cr39.json
**Updates**
- References
**Comments**
Adding the patch link (https://github.com/TribalSystems/Zenario/commit/4f95a557af3c0b82e448a6ff8f4c167525972e4a)
The commit comment (https://github.com/TribalSystems/Zenario/commit/4f95a557af3c0b82e448a6ff8f4c167525972e4a) matches the release log (https://github.com/TribalSystems/Zenario/releases/tag/9.0.57473) for the version from the advisory. Additionally, only two commits existed between the prior version and the patched version (https://github.com/TribalSystems/Zenario/compare/9.0.55141...9.0.57473) and https://github.com/TribalSystems/Zenario/commit/4f95a557af3c0b82e448a6ff8f4c167525972e4acommit 4f95a557 is related to the vulnerability.
> [GHSA-4p38-rc98-cr39] Zenario CMS is vulnerable to Remote Code Execution (RCE).

- advisories/github-reviewed/2022/11/GHSA-4pcg-wr6c-h9cq/GHSA-4pcg-wr6c-h9cq.json
**Updates**
- References
**Comments**
Adding the PR: https://github.com/fastify/fastify-websocket/pull/228
Adding patch link for v5.0.1: https://github.com/fastify/fastify-websocket/commit/7e8c41a51c101c3d5ce88caee4f71d9c29eb2863
Adding patch link for v7.1.1: https://github.com/fastify/fastify-websocket/commit/c24adeb3efd57a18b2f287c35d029e88b5a47194
These were mentioned in the release of v5.0.1 (https://github.com/fastify/fastify-websocket/releases/tag/v5.0.1) and v7.1.1 (https://github.com/fastify/fastify-websocket/releases/tag/v7.1.1)
> [GHSA-4pcg-wr6c-h9cq] fastify/websocket vulnerable to uncaught exception via crash on malformed packet

- advisories/github-reviewed/2022/02/GHSA-5946-mpw5-pqxx/GHSA-5946-mpw5-pqxx.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/cobbler/cobbler/commit/10b2112db83fedfc391e900edfedc2b4e507d3f7
The CVE is in the commit message: "Fix CVE-2021-45082 and CVE-2021-45083"
It's also the primary merge from the original PR (https://github.com/cobbler/cobbler/pull/2945)
> [GHSA-5946-mpw5-pqxx] Incorrect Default Permissions in Cobbler

- advisories/github-reviewed/2021/04/GHSA-5pxj-mhwj-x5gv/GHSA-5pxj-mhwj-x5gv.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/victornpb/asciitable.js/commit/8db8fc5ffa7a2a6e8596709d99b200afb53f40ab
This is the primary merge for v1.0.3 from the original PR (https://github.com/victornpb/asciitable.js/pull/1/commits)
> [GHSA-5pxj-mhwj-x5gv] Prototype Pollution in asciitable.js

- advisories/github-reviewed/2021/11/GHSA-5j5w-g665-5m35/GHSA-5j5w-g665-5m35.json
**Updates**
- References
**Comments**
Adding patch link for v1.4.12: https://github.com/containerd/containerd/commit/db00065a969a983ceb0a409833f93f705f284ea4
Adding patch link for v1.5.8: https://github.com/containerd/containerd/commit/26c76a3014e71af5ad2f396ec76e0e0ecc8e25a3
The GHSA-ID is in the message: "Merge pull request from GHSA-5j5w-g665-5m35"
> [GHSA-5j5w-g665-5m35] Ambiguous OCI manifest parsing

- advisories/github-reviewed/2023/03/GHSA-8wg7-88cg-7p9j/GHSA-8wg7-88cg-7p9j.json
**Updates**
- CVSS
- Severity
**Comments**
This CVE has been rejected. Please remove it from advisories.
> [GHSA-8wg7-88cg-7p9j] Pimcore vulnerable to Cross-site Scripting

- advisories/github-reviewed/2021/08/GHSA-p9gf-gmfv-398m/GHSA-p9gf-gmfv-398m.json
**Updates**
- Summary
**Comments**
pkg name is dash, “-“, instead of underscore,”_”
> [GHSA-p9gf-gmfv-398m] Double free in slice_deque

- advisories/github-reviewed/2021/08/GHSA-7j44-fv4x-79g9/GHSA-7j44-fv4x-79g9.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/matklad/once_cell/commit/afcca95a05240ebd931ab20998c946f77ef1e284
PR to close the original issue (https://github.com/matklad/once_cell/issues/46): https://github.com/matklad/once_cell/pull/47
The patch link is the merge of 47, which was used to close issue 46.
> [GHSA-7j44-fv4x-79g9] Improper Input Validation in once_cell

- advisories/github-reviewed/2021/08/GHSA-6wj2-g87r-pm62/GHSA-6wj2-g87r-pm62.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/kivikakk/comrak/commit/b72340cabe4749952530b4fb6b4fcc706bc973e5
As mentioned in the advisory, the patch escapes ampersands and is the only security-related fix in the timeline (https://github.com/kivikakk/comrak/compare/0.10.0...0.10.1).
> [GHSA-6wj2-g87r-pm62] Cross-site Scripting in comrak

- advisories/github-reviewed/2018/08/GHSA-7322-9mx6-5j2m/GHSA-7322-9mx6-5j2m.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/vmg/redcarpet/commit/2cee777c1e5babe8a1e2683d31ea75cc4afe55fb
The fix was mentioned in the reference link from Openwall: https://www.openwall.com/lists/oss-security/2015/06/29/3
> [GHSA-7322-9mx6-5j2m] redcarpet Buffer Overflow vulnerability

- advisories/github-reviewed/2022/05/GHSA-73rx-3f9r-x949/GHSA-73rx-3f9r-x949.json
**Updates**
- References
**Comments**
Adding a patch link: https://github.com/apache/tomcat/commit/52382ebfbce20a98b01cd9d37184a12703987a5a
Validation comes from a previous reference link (https://lists.apache.org/thread/bol4f8wyjfsbo135tw9gy49o5nf8qpth):
- CVE-2017-7674 
- The CORS Filter did not add an HTTP Vary header indicating that the response varies depending on Origin. This permitted client and server side cache poisoning in some circumstances.
- This was fixed in revision 1795816
The revision git-svn-id matches the one in the commit message, and the message is very similar: "CORS filter should set Vary header in response. git-svn-id: https://svn.apache.org/repos/asf/tomcat/tc7.0.x/trunk@1795816"
> [GHSA-73rx-3f9r-x949] Insufficient Verification of Data Authenticity in Apache Tomcat

- advisories/github-reviewed/2022/04/GHSA-7627-mp87-jf6q/GHSA-7627-mp87-jf6q.json
**Updates**
- References
**Comments**
Adding a patch link for v1.6.0: https://github.com/CocoaPods/cocoapods-downloader/commit/b70bc39c75645aa6d4a01a3ca6de40477c84f4b5
Adding a patch link for v1.6.3: https://github.com/CocoaPods/cocoapods-downloader/commit/52a0d54464932a90ded5a59c71a016e8dec0ca84
These are linked in PRs, in which 124 (https://github.com/CocoaPods/cocoapods-downloader/pull/124) was for v1.6.0, and 128 (https://github.com/CocoaPods/cocoapods-downloader/pull/128) was for v1.6.3.
> [GHSA-7627-mp87-jf6q] Command injection in cocoapods-downloader

- advisories/github-reviewed/2023/01/GHSA-7jf5-fvgf-48c6/GHSA-7jf5-fvgf-48c6.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/Velocidex/velociraptor/commit/4718bb0cb426564568abc77910e90a2c211a32e6
This is the only commit between https://github.com/Velocidex/velociraptor/compare/v0.6.7-4...v0.6.7-5. The commit makes changes to the client ID to validate. They also validate user access before they write to the filesystem, which is suspect for the original path traversal.
> [GHSA-7jf5-fvgf-48c6] Velociraptor subject to Path Traversal

- advisories/github-reviewed/2022/12/GHSA-7p7c-pvvx-2vx3/GHSA-7p7c-pvvx-2vx3.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/stephank/hyper-staticfile/commit/1e40e31d64bc6b32e595d24074092dcf84410b2b
Adding PR that closes the original issue (https://github.com/stephank/hyper-staticfile/issues/35): https://github.com/stephank/hyper-staticfile/pull/36
This is the commit used to close issue 35.
> [GHSA-7p7c-pvvx-2vx3] hyper-staticfile's improper validation of Windows paths could lead to directory traversal attack

- advisories/github-reviewed/2022/01/GHSA-7rjp-fgwj-47rw/GHSA-7rjp-fgwj-47rw.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/apache/shenyu/commit/9a02215013037e1cc8cd41f216164628a9e9e28f
Adding PR: https://github.com/apache/incubator-shenyu/pull/2723
The PR was referenced in an original reference (https://www.openwall.com/lists/oss-security/2022/01/26/3)
"Upgrade to Apache ShenYu (incubating) 2.4.2 or apply patch
https://github.com/apache/incubator-shenyu/pull/2723."
> [GHSA-7rjp-fgwj-47rw] Missing authentication in ShenYu

- advisories/github-reviewed/2022/03/GHSA-838h-jqp6-cf2f/GHSA-838h-jqp6-cf2f.json
**Updates**
- References
**Comments**
Adding patch link for v1.20.3: https://github.com/denoland/deno/commit/fcfce1bb869fddc629e6d889d6ba1328b80b0dcf
This is the commit from the PR (https://github.com/denoland/deno/pull/14115/commits) that appeared between https://github.com/denoland/deno/compare/v1.20.2...v1.20.3
> [GHSA-838h-jqp6-cf2f] Sandbox bypass leading to arbitrary code execution in Deno

- advisories/github-reviewed/2019/09/GHSA-8864-rhmw-5m6f/GHSA-8864-rhmw-5m6f.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/status-board/status-board/commit/19106617865406aa6f8edec036dcb1db427d5f71
This is linked in the PR (https://github.com/status-board/status-board/pull/948), but it's the primary commit that removes the ${safeDashboardName} from the error message as described in the advisory.
> [GHSA-8864-rhmw-5m6f] Status Board vulnerable to Cross-Site Scripting before v1.1.82

- advisories/github-reviewed/2022/11/GHSA-8c2c-jxwj-jqgf/GHSA-8c2c-jxwj-jqgf.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/spatie/browsershot/commit/92cf16fc098211731f80d21687abeafbe2c457ad
The developer no longer allows URLs to direct to a file location. Additionally, the unit test is pointed at the Browsershot:url method.
> [GHSA-8c2c-jxwj-jqgf] Browsershot does not validate URL protocols passed to Browsershot URL method

- advisories/github-reviewed/2022/01/GHSA-8c5j-9r9f-c6w8/GHSA-8c5j-9r9f-c6w8.json
**Updates**
- References
**Comments**
Adding patch link for v2.2.26: https://github.com/django/django/commit/c9f648ccfac5ab90fb2829a66da4f77e68c7f93a
Adding patch link for v3.2.11: https://github.com/django/django/commit/c7fe895bca06daf12cc1670b56eaf72a1ef27a16
Adding patch link for v4.0.1: https://github.com/django/django/commit/2a8ec7f546d6d5806e221ec948c5146b55bd7489
The CVE is in the commit message: "Fixed CVE-2021-45116 -- Fixed potential information disclosure in dictsort template filter."
> [GHSA-8c5j-9r9f-c6w8] Information disclosure in Django

- advisories/github-reviewed/2021/08/GHSA-8fgg-5v78-6g76/GHSA-8fgg-5v78-6g76.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/wwylele/byte-struct-rs/commit/a535678377de12bc6bc22620c5f59bcc1369f76f
Within the comments of the issue (https://github.com/wwylele/byte-struct-rs/issues/1), the developer references the commit: "I decided to think less and just replace it with safe code that is possible today in a535678"
> [GHSA-8fgg-5v78-6g76] Deserializing an array can free uninitialized memory in byte_struct

- advisories/github-reviewed/2023/01/GHSA-8v4j-7jgf-5rg9/GHSA-8v4j-7jgf-5rg9.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/seanmonstar/warp/commit/0074a0a3e98786509259bfe3821d3b3f094257aa
This PR (https://github.com/seanmonstar/warp/pull/997) closes the original issue (https://github.com/seanmonstar/warp/issues/937).
> [GHSA-8v4j-7jgf-5rg9] Warp vulnerable to Path Traversal via Improper validation of Windows paths

- advisories/github-reviewed/2022/02/GHSA-8vwm-8vj8-rqjf/GHSA-8vwm-8vj8-rqjf.json
**Updates**
- References
**Comments**
Adding patch link: https://github.com/google/fscrypt/commit/91aa3ebf42032ca783c41f9ec25d885875f66ddb
This is the complete merge of the PR (https://github.com/google/fscrypt/pull/346) to validate the patch for v0.3.3
> [GHSA-8vwm-8vj8-rqjf] User login denial of service in github.com/google/fscrypt

- advisories/github-reviewed/2023/01/GHSA-579w-22j4-4749/GHSA-579w-22j4-4749.json
Hello,
I see that you've reported that versions `>=6.0.0, < 6.0.6.1` are vulnerable to CVE-2022-44566. From looing in all the references that you've attached I see that none of them references to those vulnerable versions, even I can see that [Ruby On Rails official announce ](https://rubyonrails.org/2023/1/17/Rails-Versions-6-0-6-1-6-1-7-1-7-0-4-1-have-been-released) also don't reference to a fix in that version.
Can you please explain why you chose to classify those versions as vulnerable too?
Thank You
> Removing versions 6.0.x from vulnerable versions

- advisories/github-reviewed/2023/03/GHSA-8fww-64cx-x8p5/GHSA-8fww-64cx-x8p5.json
**Updates**
- References
**Comments**
Affected versions should match more the previous security report: https://github.com/advisories/GHSA-8fww-64cx-x8p5
Fix for 4.3.x does not seem to be out yet: https://github.com/redis/redis-py/pull/2672
> [GHSA-8fww-64cx-x8p5] redis-py Race Condition due to incomplete fix

- advisories/github-reviewed/2023/02/GHSA-6wxg-wh7f-rqpr/GHSA-6wxg-wh7f-rqpr.json
**Updates**
**Comments**
As the different major versions of this product lives in different repos, we have done 2 separate security advisories, one in each repo. But for security tools to correctly  report if a version is vulnerable or not, both advisories need to mention both versions 4.x and 5.x.
> [GHSA-6wxg-wh7f-rqpr] XML External Entity (XXE) vulnerability in apoc.import.graphml

- advisories/github-reviewed/2022/05/GHSA-8vxv-2g8p-2249/GHSA-8vxv-2g8p-2249.json
**Updates**
- References
**Comments**
Adding the patch link: https://github.com/constantoine/totp-rs/commit/1f1e1a6fe722deb1656f483b1367ea4be978db5b
The developer introduced a time comparison as requested in issue 13 (https://github.com/constantoine/totp-rs/issues/13). Additionally, only two commits existed between releases https://github.com/constantoine/totp-rs/compare/v1.0...v1.1.0, with one being the commit merge.
> [GHSA-8vxv-2g8p-2249] Observable Timing Discrepancy in totp-rs

- advisories/github-reviewed/2018/07/GHSA-924m-4pmx-c67h/GHSA-924m-4pmx-c67h.json
**Updates**
- References
**Comments**
Adding the patch link: https://github.com/IdentityPython/pysaml2/commit/6312a41e037954850867f29d329e5007df1424a5
The PR (https://github.com/IdentityPython/pysaml2/pull/454) with the patch was referenced in the original issue (https://github.com/IdentityPython/pysaml2/issues/451).
It also appears that the repo owner changed from 'rohe' to 'IdentityPython,' but it redirects appropriately.
> [GHSA-924m-4pmx-c67h] High severity vulnerability that affects pysaml2

- advisories/github-reviewed/2022/01/GHSA-92cx-4xm7-jr9m/GHSA-92cx-4xm7-jr9m.json
**Updates**
- References
**Comments**
Adding the patch link for v0.25.4: https://github.com/rusqlite/rusqlite/commit/f4f95f8caf9fd53bffd0c19530be2484c644cc16
Adding three patch links for v0.26.2: 
https://github.com/rusqlite/rusqlite/commit/30f8c8c502675011603c4d066396bf317fd49e71
https://github.com/rusqlite/rusqlite/commit/612158507e90f41d409cd0fa80eb21c992b1bc08
https://github.com/rusqlite/rusqlite/commit/934e0c709e156753881da98b32e9853f9ffe4a1b
Adding the issue: https://github.com/rusqlite/rusqlite/issues/1048
Adding the pull: https://github.com/rusqlite/rusqlite/pull/1049
The issue was originally linked in a reference (https://raw.githubusercontent.com/rustsec/advisory-db/main/crates/rusqlite/RUSTSEC-2021-0128.md), which has the above commits. For v0.26.2 it was a mixture of three …
> [GHSA-92cx-4xm7-jr9m] Use After Free in rusqlite

- advisories/github-reviewed/2023/01/GHSA-96jv-r488-c2rj/GHSA-96jv-r488-c2rj.json
**Updates**
- References
**Comments**
Adding the patch link for v0.4.4: https://github.com/alexcrichton/bzip2-rs/commit/90c9c182cd5a5ebc75810aebd89b347a7bdf590b
The patch is the complete merge of the original pull (https://github.com/alexcrichton/bzip2-rs/pull/86)
> [GHSA-96jv-r488-c2rj] bzip2 allows attackers to cause a denial of service via a large file that triggers an integer overflow

- advisories/github-reviewed/2019/02/GHSA-9c2p-jw8p-f84v/GHSA-9c2p-jw8p-f84v.json
**Updates**
- References
**Comments**
Adding the patch link for v3.20.0: https://github.com/sequelize/sequelize/commit/23952a2b020cc3571f090e67dae7feb084e1be71
The patch was mentioned in the original issue (https://github.com/sequelize/sequelize/issues/5671): "somebody already fixed this one in 23952a2."
> [GHSA-9c2p-jw8p-f84v] SQL Injection in sequelize

- advisories/github-reviewed/2018/08/GHSA-9cp3-fh5x-xfcj/GHSA-9cp3-fh5x-xfcj.json
**Updates**
- References
**Comments**
Adding the patch link for v1.0.1: https://github.com/node-modules/charset/commit/effda0c48c51b47a47f4cad7db0c51ee7407cc1b
This is the complete merge for pull (https://github.com/node-modules/charset/pull/11), which closes the original issue (https://github.com/node-modules/charset/issues/10)
> [GHSA-9cp3-fh5x-xfcj] Regular Expression Denial of Service in charset

- advisories/github-reviewed/2022/11/GHSA-9fmc-5fq4-5jwh/GHSA-9fmc-5fq4-5jwh.json
**Updates**
- References
**Comments**
Adding the patch link for v1.4.2: https://github.com/hashicorp/nomad/commit/dd6a4634a9652197fe4182e830f9a737d0ae1216
In this patch, the developer is now checking if tokens expire before triggering events, which would only end once the token was garbage collected—a very similar description to the original advisory.
> [GHSA-9fmc-5fq4-5jwh] HashiCorp Nomad vulnerable to Insufficient Session Expiration

- advisories/github-reviewed/2022/12/GHSA-9h6h-9g78-86f7/GHSA-9h6h-9g78-86f7.json
**Updates**
- References
**Comments**
Adding two patch links for v0.19.1: 
https://github.com/fkie-cad/yapscan/commit/a75a20b50be673b96b1d42187b97f8cfe60728df
https://github.com/fkie-cad/yapscan/commit/fef9a33ceb66f6b929839f7eaf393b629681bc5d
These two patches were referenced in the original issue (https://github.com/fkie-cad/yapscan/issues/35)
> [GHSA-9h6h-9g78-86f7] Yapscan's report receiver server vulnerable to path traversal and log injection

- advisories/github-reviewed/2022/11/GHSA-9jc5-9wh5-mc36/GHSA-9jc5-9wh5-mc36.json
**Updates**
- References
**Comments**
Adding the patch links for v8.5.10: https://github.com/concretecms/concretecms/commit/6d46ca042fcfeda0f7881d8744f5216ef1abce0e
Adding the patch links for v9.1.3: https://github.com/concretecms/concretecms/commit/51f19b377a19c97a8b8f1d4d0f13724ed1c7c7a7
Adding the pull: https://github.com/concretecms/concretecms/pull/10999
The patches are related to the original advisory: "This PR prevents XSS in the microsoft application tile color."
> [GHSA-9jc5-9wh5-mc36] Concrete CMS vulnerable to Cross-site Scripting

- advisories/github-reviewed/2021/08/GHSA-9p29-94hp-8rvc/GHSA-9p29-94hp-8rvc.json
**Updates**
- References
**Comments**
Adding the patch links for v0.34.0: https://github.com/increments/qiita-markdown/commit/b5d4e60bf537ceb177e70bf91653d29575e1aa21
Only a few commits for v0.34.0: https://github.com/increments/qiita-markdown/compare/v0.33.0...v0.34.0. The patch added is the only one related to the original XSS issue.
> [GHSA-9p29-94hp-8rvc] qiita-markdown Cross-site Scripting vulnerability

- advisories/github-reviewed/2021/08/GHSA-9pp4-8p8v-g78w/GHSA-9pp4-8p8v-g78w.json
**Updates**
- References
**Comments**
Adding the patch link for v0.1.1: https://github.com/vertexclique/lever/commit/4a4cca61cdb25061967d58522229e147483007b1
The patch is the complete merge of pull (https://github.com/vertexclique/lever/pull/17), which was referenced in the original issue (https://github.com/vertexclique/lever/issues/15)
> [GHSA-9pp4-8p8v-g78w] Data races in lever

- advisories/github-reviewed/2021/08/GHSA-9wgh-vjj7-7433/GHSA-9wgh-vjj7-7433.json
**Updates**
- References
**Comments**
Adding the patch link for v0.23.12: https://github.com/image-rs/image/commit/5cbe1e6767d11aff3f14c7ad69a06b04e8d583c7
The patch is the complete merge of pull (https://github.com/image-rs/image/pull/1358), which was referenced in the original issue (https://github.com/image-rs/image/issues/1357) as the fix.
> [GHSA-9wgh-vjj7-7433] Mutable reference with immutable provenance in image

- advisories/github-reviewed/2021/11/GHSA-9wx7-jrvc-28mm/GHSA-9wx7-jrvc-28mm.json
**Updates**
- References
**Comments**
Adding the patch link for v2.0.1 of the Python instance: https://github.com/starkbank/ecdsa-python/commit/d136170666e9510eb63c2572551805807bd4c17f
Only a few commits for v2.0.1 (https://github.com/starkbank/ecdsa-python/compare/v2.0.0...v2.0.1) and the changelog also reference the same commit message: "Signature r and s range check," related to the original vulnerability.
> [GHSA-9wx7-jrvc-28mm] Signature verification vulnerability in Stark Bank ecdsa libraries

- advisories/github-reviewed/2021/08/GHSA-9xjr-m6f3-v5wm/GHSA-9xjr-m6f3-v5wm.json
**Updates**
- References
**Comments**
Adding the patch link for v0.9.4: https://github.com/hyperium/hyper/commit/01160abd92956e5f995cc45790df7a2b86c8989f
Referenced in changelog (https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v094-2016-05-09):  "enable hostname verification by default for OpenSSL (01160abd, closes 472)"
> [GHSA-9xjr-m6f3-v5wm] HTTPS MitM vulnerability due to lack of hostname verification

- advisories/github-reviewed/2019/11/GHSA-c3gv-9cxf-6f57/GHSA-c3gv-9cxf-6f57.json
**Updates**
- References
**Comments**
Adding the patch link for v2.3.1: https://github.com/flavorjones/loofah/commit/0c6617af440879ce97440f6eb6c58636456dc8ec
The CVE and original issue (171) are mentioned in the commit message: "mitigate XSS vulnerability in SVG animate attributes this addresses CVE-2019-15587 see #171 for more information"
> [GHSA-c3gv-9cxf-6f57] Cross-site Scripting in Loofah

- advisories/github-reviewed/2022/09/GHSA-jv3g-j58f-9mq9/GHSA-jv3g-j58f-9mq9.json
**Updates**
**Comments**
The jose library affected by this vulnerability has been released in semantic versions 1.0.0, 2.0.0, 3.0.0, and 4.0.0, instead of 1.0, 2.0, 3.0 and 4.0 (see https://github.com/panva/jose/releases). This change makes the advisory compliant to the semantic versioning scheme natively used in npm.
> [GHSA-jv3g-j58f-9mq9] JOSE vulnerable to resource exhaustion via specifically crafted JWE

- advisories/github-reviewed/2022/05/GHSA-3wqf-4x89-9g79/GHSA-3wqf-4x89-9g79.json
**Updates**
**Comments**
The affected version was mistakenly listed as >= 4.0, whereas only >= 4.0.0 is semantically correct. See https://github.com/twbs/bootstrap/releases/tag/v4.0.0 for reference.
> [GHSA-3wqf-4x89-9g79] Bootstrap vulnerable to Cross-Site Scripting (XSS)

- advisories/github-reviewed/2020/04/GHSA-gxr4-xjj5-5px2/GHSA-gxr4-xjj5-5px2.json
**Updates**
**Comments**
The lower bound of affected versions was mistakenly listed as `>= 1.2` but only `>= 1.2.0` complies with the semantic versioning scheme used with npm.
> [GHSA-gxr4-xjj5-5px2] Potential XSS vulnerability in jQuery

- advisories/github-reviewed/2022/10/GHSA-qpv8-4pjq-qqh7/GHSA-qpv8-4pjq-qqh7.json
**Updates**
**Comments**
Lower bounds of affected versions were mistakenly reported as `6.0` but only `6.0.0` complies with the semantic versioning scheme used by npm.
> [GHSA-qpv8-4pjq-qqh7] feathers-sequelize contains improper input validation leading to SQL injection

- advisories/github-reviewed/2022/10/GHSA-p5m3-27vh-52j4/GHSA-p5m3-27vh-52j4.json
**Updates**
**Comments**
Lower bounds of affected versions were mistakenly reported as `6.0` but only `6.0.0` complies with the semantic versioning scheme used by npm.
> [GHSA-p5m3-27vh-52j4] Feather-Sequelize cleanQuery method vulnerable to Prototype Pollution

- advisories/github-reviewed/2021/05/GHSA-vcjf-mgcg-jxjq/GHSA-vcjf-mgcg-jxjq.json
**Updates**
**Comments**
Affected and patched version were mistakenly listed as `4.14` but only `4.14.0` is correct, see https://github.com/ckeditor/ckeditor4/releases/tag/4.14.0
> [GHSA-vcjf-mgcg-jxjq] CKEditor 4.0 vulnerability in the HTML Data Processor

- advisories/github-reviewed/2020/06/GHSA-77qv-gh6f-pgh4/GHSA-77qv-gh6f-pgh4.json
**Updates**
- Description
**Comments**
The affected version was mistakenly listed as 0.95 but only 0.9.5 is correct. 0.95 has never been released. See https://github.com/erelsgl/limdu/commit/b624c7e018d977b6c6a0c8449206cd1f364d8d98 for reference. This change also ensures compliance with the semantic versioning scheme.
> [GHSA-77qv-gh6f-pgh4] Command Injection in Limdu

- advisories/github-reviewed/2018/12/GHSA-gfv6-cj92-g3hx/GHSA-gfv6-cj92-g3hx.json
**Updates**
- References
**Comments**
Adding the patch link for v0.8.0: https://github.com/OpenKMIP/PyKMIP/commit/3a7b880bdf70d295ed8af3a5880bab65fa6b3932
The commit patch closes the original issue (430): "Fix a denial-of-service bug by setting the server socket timeout. Closes 430"
> [GHSA-gfv6-cj92-g3hx] Moderate severity vulnerability that affects pykmip

- advisories/github-reviewed/2021/12/GHSA-gfhx-jjwq-63gv/GHSA-gfhx-jjwq-63gv.json
**Updates**
- References
**Comments**
Adding the patch link for v6.4.2: https://github.com/apereo/cas/commit/376bf087d6d4267f61fc9f8028aa0d1ef407c3f0
As validation, the developer starts to sanitize the ticket-id/username described in the original reference link (https://apereo.github.io/2021/10/18/restvuln/): "Malicious scripts can be submitted to CAS via parameters such as the ticket id or the username."
> [GHSA-gfhx-jjwq-63gv] Cross-site Scripting in Apereo CAS

- advisories/github-reviewed/2017/10/GHSA-gcqq-w6gr-h9j9/GHSA-gcqq-w6gr-h9j9.json
**Updates**
- References
**Comments**
Adding the patch link for v1.2.1: https://github.com/rubyzip/rubyzip/commit/ce4208fdecc2ad079b05d3c49d70fe6ed1d07016
The commit patch message references the original issue: "Fix 315 and resolve relative path vulnerability"
> [GHSA-gcqq-w6gr-h9j9] Directory traversal vulnerability in RubyZip

- advisories/github-reviewed/2018/07/GHSA-g7q5-pjjr-gqvp/GHSA-g7q5-pjjr-gqvp.json
**Updates**
- References
**Comments**
Adding the patch link for v2.3.3: https://github.com/salesforce/tough-cookie/commit/f1ed420a6a92ea7a5418df6e39e676556bc0c71d
The commit patch message references the original issue: "Constrain spaces before = to 256 Side-steps ReDoS in Issue 92."
> [GHSA-g7q5-pjjr-gqvp] Regular Expression Denial of Service in tough-cookie

- advisories/github-reviewed/2022/04/GHSA-g5mm-vmx4-3rg7/GHSA-g5mm-vmx4-3rg7.json
**Updates**
- References
**Comments**
Adding the patch link for v5.2.21: https://github.com/spring-projects/spring-framework/commit/833e750175349ab4fd502109a8b41af77e25cdea
Adding the patch link for v5.3.19: 
https://github.com/spring-projects/spring-framework/commit/a7cf19cec5ebd270f97a194d749e2d5701ad2ab7
In this patch, the developer starts lower casing to prevent the case sensitivity in the disallowedField on a DataBinder: PropertyAccessorUtils.canonicalPropertyName(disallowedFields[i]).toLowerCase(); Surrounding text also helps validate this is the patch link: "support case-insensitive pattern matching in {@link #isAllowed}. Subclasses"
> [GHSA-g5mm-vmx4-3rg7] Improper handling of case sensitivity in Spring Framework

- advisories/github-reviewed/2022/09/GHSA-gfhp-jgp6-838j/GHSA-gfhp-jgp6-838j.json
**Updates**
- References
**Comments**
Adding the patch link for v6.13: https://github.com/Orckestra/C1-CMS-Foundation/commit/af856ab5a62d19acf6aea1b1f4c6c3c4985c9446
This is the full merge of the original pull (https://github.com/Orckestra/C1-CMS-Foundation/pull/814)
> [GHSA-gfhp-jgp6-838j] Orckestra C1 CMS's deserialization of untrusted data allows for arbitrary code execution.

- advisories/github-reviewed/2022/09/GHSA-qv98-3369-g364/GHSA-qv98-3369-g364.json
**Updates**
**Comments**
The affected version was mistakenly listed as >= 0.20, whereas only >= 0.20.0 is semantically correct. See https://github.com/kubevirt/kubevirt/releases/tag/v0.20.0 for reference.
> [GHSA-qv98-3369-g364] KubeVirt vulnerable to arbitrary file read on host

- advisories/github-reviewed/2023/02/GHSA-r7jw-wp68-3xch/GHSA-r7jw-wp68-3xch.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: 
https://crates.io/crates/openssl-src/111.25.0+1.1.1t
> [GHSA-r7jw-wp68-3xch] openssl-src vulnerable to Use-after-free following `BIO_new_NDEF`

- advisories/github-reviewed/2023/03/GHSA-7rqg-hjwc-6mjf/GHSA-7rqg-hjwc-6mjf.json
**Updates**
**Comments**
Lower bounds of affected versions were mistakenly reported in a non-semver compliant format. This change adapts `9.2` to `9.2.0` and `9.3` to `9.3.0`. These versions also match with the vendor-issued security advisory available at https://github.com/grafana/grafana/security/advisories/GHSA-7rqg-hjwc-6mjf
> [GHSA-7rqg-hjwc-6mjf] Grafana vulnerable to Stored Cross-site Scripting in Text plugin

- advisories/github-reviewed/2022/09/GHSA-3637-v6vq-xqqw/GHSA-3637-v6vq-xqqw.json
> [GHSA-3637-v6vq-xqqw] Harbor fails to validate the user permissions when updating tag retention policies

- advisories/github-reviewed/2022/05/GHSA-q9wj-f4qw-6vfj/GHSA-q9wj-f4qw-6vfj.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: https://crates.io/crates/openssl-src/111.16.0+1.1.1l
> [GHSA-q9wj-f4qw-6vfj] Read buffer overruns processing ASN.1 strings

- advisories/github-reviewed/2023/02/GHSA-p52g-cm5j-mjv4/GHSA-p52g-cm5j-mjv4.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: https://crates.io/crates/openssl-src/300.0.0+3.0.0
> [GHSA-p52g-cm5j-mjv4] openssl-src subject to Timing Oracle in RSA Decryption

- advisories/github-reviewed/2023/01/GHSA-mc52-jpm2-cqh6/GHSA-mc52-jpm2-cqh6.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: https://crates.io/crates/deno/1.9.0
> [GHSA-mc52-jpm2-cqh6] Deno is vulnerable to race condition via interactive permission prompt spoofing

- advisories/github-reviewed/2021/08/GHSA-jq65-29v4-4x35/GHSA-jq65-29v4-4x35.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: https://crates.io/crates/openssl-src/111.9.0+1.1.1g
> [GHSA-jq65-29v4-4x35] Null pointer deference in openssl-src 

- advisories/github-reviewed/2021/08/GHSA-8hfj-xrj2-pm22/GHSA-8hfj-xrj2-pm22.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version:
https://crates.io/crates/openssl-src/111.11.0+1.1.1h   
https://crates.io/crates/openssl-src/111.15.0+1.1.1k
> [GHSA-8hfj-xrj2-pm22] Certificate check bypass in openssl-src

- advisories/github-reviewed/2021/08/GHSA-84rm-qf37-fgc2/GHSA-84rm-qf37-fgc2.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: https://crates.io/crates/openssl-src/111.14.0+1.1.1j
> [GHSA-84rm-qf37-fgc2] Integer Overflow in openssl-src

- advisories/github-reviewed/2021/08/GHSA-83mx-573x-5rw9/GHSA-83mx-573x-5rw9.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: https://crates.io/crates/openssl-src/111.15.0+1.1.1k
> [GHSA-83mx-573x-5rw9] Null pointer deference in openssl-src

- advisories/github-reviewed/2022/05/GHSA-5ww6-px42-wc85/GHSA-5ww6-px42-wc85.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: https://crates.io/crates/openssl-src/111.16.0+1.1.1l
> [GHSA-5ww6-px42-wc85] SM2 Decryption Buffer Overflow

- advisories/github-reviewed/2022/02/GHSA-g6w6-r76c-28j7/GHSA-g6w6-r76c-28j7.json
**Updates**
**Comments**
The affected version was mistakenly listed as >= 2.0, whereas only >= 2.0.0 is semantically correct. See https://github.com/nats-io/nats-server/releases/tag/v2.0.0 for reference.
> [GHSA-g6w6-r76c-28j7] Incorrect Authorization in NATS nats-server

- advisories/github-reviewed/2022/07/GHSA-3wx7-46ch-7rq2/GHSA-3wx7-46ch-7rq2.json
**Updates**
**Comments**
Make the affected product versions SemVer compliant and match the actual package version: https://crates.io/crates/openssl-src/111.22.0+1.1.1q)
> [GHSA-3wx7-46ch-7rq2] AES OCB fails to encrypt some bytes

- advisories/github-reviewed/2023/02/GHSA-v5w6-wcm8-jm4q/GHSA-v5w6-wcm8-jm4q.json
> [GHSA-v5w6-wcm8-jm4q] openssl-src contains Double free after calling `PEM_read_bio_ex`

- advisories/github-reviewed/2020/09/GHSA-g336-c7wv-8hp3/GHSA-g336-c7wv-8hp3.json
**Updates**
- References
**Comments**
Adding the patch link for v2.2.1: 
https://github.com/swagger-api/swagger-ui/commit/a1aea70f2c64533bf053a41d4da5a8accd0117b7
This patch's pull (https://github.com/swagger-api/swagger-ui/pull/2334) closed the original issue (https://github.com/swagger-api/swagger-ui/issues/1617).
> [GHSA-g336-c7wv-8hp3] Cross-Site Scripting in swagger-ui

- advisories/github-reviewed/2021/12/GHSA-fxwm-rx68-p5vx/GHSA-fxwm-rx68-p5vx.json
**Updates**
- References
**Comments**
Adding the patch link for v2.3.7.1: 
https://github.com/ezsystems/ezplatform-richtext/commit/3cebfe2ae4c22e6590632a0ff71893854a16afc5
The GHSA-ID is in the message: "Merge pull request from GHSA-fxwm-rx68-p5vx"
> [GHSA-fxwm-rx68-p5vx] XSS in richtext custom tag attributes in ezsystems/ezplatform-richtext

- advisories/github-reviewed/2018/07/GHSA-fxpg-gg9g-76gj/GHSA-fxpg-gg9g-76gj.json
**Updates**
- References
**Comments**
Adding the patches for v1.2.2: 
https://github.com/django/django/commit/7f84657b6b2243cc787bdb9f296710c8d13ad0bd
The patches are mentioned in an original reference link (https://www.djangoproject.com/weblog/2010/sep/08/security-release/): "Patches may be obtained directly from the appropriate changesets:
Django trunk: https://github.com/django/django/commit/9e3b327aca
Django 1.2: https://github.com/django/django/commit/7f84657b6b"
> [GHSA-fxpg-gg9g-76gj] Moderate severity vulnerability that affects django

- advisories/github-reviewed/2019/04/GHSA-frxx-2m33-6wcr/GHSA-frxx-2m33-6wcr.json
**Updates**
- References
**Comments**
Adding the patches for v1.7.1: 
https://github.com/tensorflow/tensorflow/commit/41335abb46f80ca644b5738550daef6136ba5476
https://github.com/tensorflow/tensorflow/commit/8badd11d875a826bd318ed439909d5c47a7fb811
The patches are mentioned in an original reference link (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2018-003.md): "We have patched the vulnerability in GitHub commits 41335abb and 8badd11d."
> [GHSA-frxx-2m33-6wcr] Improper Restriction of Operations within the Bounds of a Memory Buffer in Google TensorFlow

- advisories/github-reviewed/2022/05/GHSA-fff8-4w9p-7v76/GHSA-fff8-4w9p-7v76.json
**Updates**
- References
**Comments**
Adding the patch link for v2.1: https://github.com/pygments/pygments/commit/db6dd826f8624179e563aaded391efe824462f51
The patch message is very similar to the original advisory: "Fix Shell Injection in FontManager._get_nix_font_path"
> [GHSA-fff8-4w9p-7v76] Command Injection in Pygments

- advisories/github-reviewed/2021/07/GHSA-f3pg-qwvg-p99c/GHSA-f3pg-qwvg-p99c.json
**Updates**
- References
**Comments**
Adding the patch link for v0.14.10: https://github.com/hyperium/hyper/commit/1fb719e0b61a4f3d911562a436a2ff05fd7cb759
The GHSA-ID is in the commit message of the patch: "fix(http1): reject content-lengths that have a plus sign prefix.....See GHSA-f3pg-qwvg-p99c"
> [GHSA-f3pg-qwvg-p99c] Lenient Parsing of Content-Length Header When Prefixed with Plus Sign

- advisories/github-reviewed/2019/08/GHSA-cr5j-953j-xw5p/GHSA-cr5j-953j-xw5p.json
**Updates**
- References
**Comments**
Adding patch link for nokogirl v1.10.4: https://github.com/sparklemotion/nokogiri/commit/5d30128343573a9428c86efc758ba2c66e9f12dc
This is the complete merge related to the original issue (https://github.com/sparklemotion/nokogiri/issues/1915). The changelog was additionally updated during the merge: "Address CVE-2019-5477."
> [GHSA-cr5j-953j-xw5p] Arbitrary execution of code in Nokogiri

- advisories/github-reviewed/2022/10/GHSA-f2rj-m42r-6jm2/GHSA-f2rj-m42r-6jm2.json
**Updates**
- References
**Comments**
Adding the patch link for v0.13.237: https://github.com/zalando/skipper/commit/842634347da8fe77e396f66edea79d329fd72130
This is the merged commit for the patch of the original pull (https://github.com/zalando/skipper/pull/2058)
> [GHSA-f2rj-m42r-6jm2] Skipper vulnerable to SSRF via X-Skipper-Proxy

- advisories/github-reviewed/2018/10/GHSA-cvj4-g3gx-8vqq/GHSA-cvj4-g3gx-8vqq.json
**Updates**
- References
**Comments**
Adding patch link for v2.3.12: https://github.com/restlet/restlet-framework-java/commit/fe75aff3af23b879b984db7a2b6824cee0ef0fc5
The patch fixed the XEE injection security in an XML extension. Additionally, this was the only security-related commit for v2.3.12: https://github.com/restlet/restlet-framework-java/compare/2.3.11...2.3.12
> [GHSA-cvj4-g3gx-8vqq] Restlet Framework allows remote attackers to access arbitrary files via a crafted REST API HTTP request

- advisories/github-reviewed/2018/10/GHSA-cgjx-mwpx-47jv/GHSA-cgjx-mwpx-47jv.json
**Updates**
- References
**Comments**
Adding patch link for v2.5.0: https://github.com/florianholzapfel/express-restify-mongoose/commit/746defcd808e2ed1e8931dc36702b25b7db0e94b
Adding patch link for v3.1.0: https://github.com/florianholzapfel/express-restify-mongoose/commit/23ccb247d0074bfaca6737cdff52d89c6d6e4a7c
The pull (https://github.com/florianholzapfel/express-restify-mongoose/pull/253) was referenced as closing the original issue (https://github.com/florianholzapfel/express-restify-mongoose/issues/252)
> [GHSA-cgjx-mwpx-47jv] Private Data Disclosure in express-restify-mongoose

- advisories/github-reviewed/2020/09/GHSA-c7pp-x73h-4m2v/GHSA-c7pp-x73h-4m2v.json
**Updates**
- References
**Comments**
Adding patch link for v2.0.0-rc.12: https://github.com/bootstrap-vue/bootstrap-vue/commit/ba6f3f8359e257589d744f180312c09bf9f12289
Pull 2134 (https://github.com/bootstrap-vue/bootstrap-vue/pull/2134) closed the original issue (https://github.com/bootstrap-vue/bootstrap-vue/issues/1974); the patch provided is the complete merge of 2134.
> [GHSA-c7pp-x73h-4m2v] Cross-Site Scripting in bootstrap-vue

- advisories/github-reviewed/2019/06/GHSA-cff4-rrq6-h78w/GHSA-cff4-rrq6-h78w.json
**Updates**
- References
**Comments**
Adding patch link for v1.2.4: https://github.com/mathisonian/command-exists/commit/7ca91ba71604df6817a28c93d7776af9c49c431a
The developer started to sanitize commands which prevented the original command injection vulnerability. Only two commits existed for v1.2.4, and the other was a release bump: https://github.com/mathisonian/command-exists/compare/v1.2.3...v1.2.4
> [GHSA-cff4-rrq6-h78w] Command Injection in command-exists

- advisories/github-reviewed/2021/09/GHSA-ccw8-7688-vqx4/GHSA-ccw8-7688-vqx4.json
**Updates**
- References
**Comments**
Adding patch link for v1.8.15: https://github.com/hashicorp/consul/commit/ccf8eb1947357434eb6e66303ddab79f4c9d4103
Adding patch link for v1.9.9: https://github.com/hashicorp/consul/commit/473edd1764b6739e2e4610ea5dede4c2bc6009d1
Adding patch link for v1.10.2: https://github.com/hashicorp/consul/commit/3357e57dac9aadabd476f7a14973e47f003c4cf0
Adding original pull: https://github.com/hashicorp/consul/pull/10925
The CVE is mentioned in the pull and associated changelogs added on each patch: "rpc: authorize raft requests CVE-2021-37219"
> [GHSA-ccw8-7688-vqx4] HashiCorp Consul Privilege Escalation Vulnerability

- advisories/github-reviewed/2022/12/GHSA-f8p3-q834-q9cj/GHSA-f8p3-q834-q9cj.json
**Updates**
- References
**Comments**
Adding the patch link for v2.3.2: https://github.com/php-mod/curl/commit/0bddefe8bbd292065f23dd6e24d2c745c4865cf7
From an original reference link (https://wpscan.com/vulnerability/0b547728-27d2-402e-ae17-90d539344ec7), they found the underlying issue of the XSS to be the following: "the cause was found to be test files from the php-mod/curl library, which was missing appropriate response headers before outputting user input." The patch adds the missing response headers for the same post_file_path_upload.php and post_multidimensional.php files.
> [GHSA-f8p3-q834-q9cj] php-mod/curl allows Cross-site Scripting

- advisories/github-reviewed/2020/08/GHSA-f9vc-q3hh-qhfv/GHSA-f9vc-q3hh-qhfv.json
**Updates**
- References
**Comments**
Adding the patch link for v1.4.1: https://github.com/jonschlinkert/remarkable/commit/d54ed887f4997221cd7cb9790e953a83c504de36
The original issue (https://github.com/jonschlinkert/remarkable/issues/97) mentions, "Doing it in renderer is not correct. There should be url encoding only." The commit patch message is very similar: "Normalize links before they hit renderer"
> [GHSA-f9vc-q3hh-qhfv] Content Injection in remarkable

- advisories/github-reviewed/2022/05/GHSA-cxw7-85xm-3xrc/GHSA-cxw7-85xm-3xrc.json
**Updates**
- References
**Comments**
Adding patch link for v4.2.3: https://github.com/plone/Products.CMFPlone/commit/c3a98f4e6cf26501485de9c8354c49afdea21df8
Adding patch link for v4.3b1: https://github.com/plone/Products.CMFPlone/commit/a9479a5b38646fe0b0a9066ee46de9c18de32bfa
The commit patch message reads: "various security fixes based on PloneHotfix20121106," which is similar to the original link provided: https://plone.org/products/plone-hotfix/releases/20121106 (even though the original link doesn't work anymore, we can note the name of plone-hotfix 20121106)
> [GHSA-cxw7-85xm-3xrc] Plone Code Injection vulnerability

- advisories/github-reviewed/2021/07/GHSA-c72p-9xmj-rx3w/GHSA-c72p-9xmj-rx3w.json
**Updates**
- References
**Comments**
Adding patch link for v1.4.8: https://github.com/containerd/containerd/commit/22e9a70c71eff6507be71955947a611f2ed91e6c
Adding patch link for v1.5.4: https://github.com/containerd/containerd/commit/7ad08c69e09ee4930a48dbf2aab3cd612458617f
The GHSA-ID is in the commit message: "Merge pull request from GHSA-c72p-9xmj-rx3w Use chmod path for checking symlink"
> [GHSA-c72p-9xmj-rx3w] Archive package allows chmod of file outside of unpack target directory

- advisories/github-reviewed/2022/02/GHSA-c6rq-rjc2-86v2/GHSA-c6rq-rjc2-86v2.json
**Updates**
- References
**Comments**
Adding two patch links for v1.1.0: 
https://github.com/isaacs/chownr/commit/a631d841022880e5c8d694408a7e96d6d576d0ce
https://github.com/isaacs/chownr/commit/36a93e3f0a220062c47b237cf6ab6d5f55cd79c9
Many discussions in the original issue (https://github.com/isaacs/chownr/issues/14) to use fs.lchown instead of fs.chown to address the vulnerability. The project owner eventually added patches to do so. These are the only two commits related to the patch v1.1.0: https://github.com/isaacs/chownr/compare/v1.0.1...v1.1.0. Additionally, one of the commit patch messages addresses the TOCTOU issue: "use lchown to address part 1 of TOCTOU issue"
> [GHSA-c6rq-rjc2-86v2] Time-of-check Time-of-use (TOCTOU) Race Condition in chownr

- advisories/github-reviewed/2019/09/GHSA-gjh4-fcv3-whpq/GHSA-gjh4-fcv3-whpq.json
**Updates**
- References
**Comments**
Adding the patch link for v0.107.6: https://github.com/webtorrent/webtorrent/commit/7e829b5d52c32d2e6d8f5fbcf0f8f418fffde083
This is the complete merge of the original pull (https://github.com/webtorrent/webtorrent/pull/1714) to resolve the cross-site scripting issue.
> [GHSA-gjh4-fcv3-whpq] Cross-Site Scripting in webtorrent

- advisories/github-reviewed/2021/06/GHSA-gq5r-cc4w-g8xf/GHSA-gq5r-cc4w-g8xf.json
**Updates**
- References
**Comments**
Adding the patch link for v0.7.0: https://github.com/russellhaering/gosaml2/commit/66e3b7affd622b8b24ea1e18845f045e46b23424
Pull 90 (https://github.com/russellhaering/gosaml2/pull/90) closed the original issue 59 (https://github.com/russellhaering/gosaml2/issues/59), the patch I provided is the complete merge of pull 90.
> [GHSA-gq5r-cc4w-g8xf] gosaml2 is vulnerable to NULL Pointer Dereference

- advisories/github-reviewed/2021/08/GHSA-gv73-9mwv-fwgq/GHSA-gv73-9mwv-fwgq.json
**Updates**
- References
**Comments**
Adding the patch link for v0.6.1: https://github.com/danburkert/prost/commit/04091d3e745c27590a5f1b7f581793e4159486b5
The original issue is linked in the commit patch message: "apply recursion limit when skipping fields. Fixes tokio-rs 267.
> [GHSA-gv73-9mwv-fwgq] Out of bounds write in prost

- advisories/github-reviewed/2019/07/GHSA-grgm-pph5-j5h7/GHSA-grgm-pph5-j5h7.json
**Updates**
- References
**Comments**
Adding the patch link for v2.6.18: https://github.com/ansible/ansible/commit/3ff6505e8ff0e4655bab008886983476ef903375
Adding the patch link for v2.7.12: https://github.com/ansible/ansible/commit/a11c3edfa41e7e4a4db323cdabfc2eae1b61da2a
Adding the patch link for v2.8.2: https://github.com/ansible/ansible/commit/04e94274fb92e116e9082cc9b86b1fd05c836922
The patches are the complete merge of the original pull 57188 (https://github.com/ansible/ansible/pull/57188) for the corresponding patched versions.
> [GHSA-grgm-pph5-j5h7] Exposure of Sensitive Information to an Unauthorized Actor in ansible

- advisories/github-reviewed/2020/09/GHSA-gvg7-pp82-cff3/GHSA-gvg7-pp82-cff3.json
**Updates**
- References
**Comments**
Adding the patch link for v0.4.11: https://github.com/c3js/c3/commit/de3864650300488a63d0541620e9828b00e94b42
This is the merge of the pull 1675 (https://github.com/c3js/c3/pull/1675) that closed the original issue 1536 (https://github.com/c3js/c3/issues/1536): 'Sanitise string embedded in tooltip - 1536'
> [GHSA-gvg7-pp82-cff3] Cross-Site Scripting in c3

- advisories/github-reviewed/2022/08/GHSA-gwj5-wp6r-5q9f/GHSA-gwj5-wp6r-5q9f.json
**Updates**
- References
**Comments**
Adding the patch link for v0.8.0: https://github.com/crypto-org-chain/cronos/commit/2f2cc88b501b47149690fdef05afbbbe5bc116c9
This is the only commit for v0.8.0 (https://github.com/crypto-org-chain/cronos/compare/v0.7.1...v0.8.0), and it's to apply the patch so selfdestruct doesn't delete bytecode of smart contracts, an aspect of the underlying DoS from the advisory.
> [GHSA-gwj5-wp6r-5q9f] Cronos vulnerable to DoS through unintended Contract Selfdestruct

- advisories/github-reviewed/2018/10/GHSA-h39x-m55c-v55h/GHSA-h39x-m55c-v55h.json
**Updates**
- References
**Comments**
Adding the patch link for v3.5.4: https://github.com/vert-x3/vertx-web/commit/57a65dce6f4c5aa5e3ce7288685e7f3447eb8f3b
The CVE and original issue 1025 is in the commit patch message: "CVE-2018-12542: The StaticHandler uses external input to construct a pathname that should be within a restricted directory, but it does not properly neutralize '\' (forward slashes) sequences that can resolve to a location that is outside of that directory when running on Windows Operating Systems. - fixes 1025"
> [GHSA-h39x-m55c-v55h] Eclipse Vert.x does not properly neutralize '' (forward slashes) sequences that can resolve to an external location

- advisories/github-reviewed/2020/08/GHSA-h6m7-j4h3-9rf5/GHSA-h6m7-j4h3-9rf5.json
**Updates**
- References
**Comments**
Adding the patch link for v1.3.14 /v1.4.7/v1.5.2/v1.6.4: https://github.com/Sylius/SyliusResourceBundle/commit/73d9aba182947473a5935b31caf65ca263091e00
The GHSA-ID is mentioned in the commit patch message: "Merge pull request from GHSA-h6m7-j4h3-9rf5. Sanitize request input before passing it to expression language evaluator"
> [GHSA-h6m7-j4h3-9rf5] Remote Code Execution in SyliusResourceBundle

- advisories/github-reviewed/2020/09/GHSA-h6mq-3cj6-h738/GHSA-h6mq-3cj6-h738.json
**Updates**
- References
**Comments**
Adding the patch link for v1.9.1: https://github.com/showdownjs/showdown/commit/1cd281f0643ef613dc1d36847d4c6cbb22501d91
The original pull 670 () is mentioned in the commit patch: "fix(openLinksInNewWindow): add rel="noopener noreferrer" to links
Add rel="noreferrer" to links when openLinksInNewWindow is on. Also add noopener when openLinksInNewWindow is on. target="_blank" without also adding rel="noopener noreferrer" creates a vulnerability (since the site you're linking to has access to the window.opener by default. This  adds rel="noopener noreferrer" to links generated by the makeHtml converter when openLinksInNewWindow is true.
Closes 670"
> [GHSA-h6mq-3cj6-h738] Reverse Tabnabbing in showdown

- advisories/github-reviewed/2019/06/GHSA-h9x2-5rm7-x4gm/GHSA-h9x2-5rm7-x4gm.json
**Updates**
- References
**Comments**
Adding the patch link for v3.0.1: https://github.com/vadimdemedes/secure-compare/commit/dd1ff1ac0122de7e0af4f00c61ed73261062394a
The original pull 1 (https://github.com/vadimdemedes/secure-compare/pull/1) is linked to the commit patch.
> [GHSA-h9x2-5rm7-x4gm] Insecure Comparison in secure-compare

- advisories/github-reviewed/2022/12/GHSA-gw62-c7w4-x449/GHSA-gw62-c7w4-x449.json
**Updates**
**Comments**
Convert affected version to a pseudoversion based off the fixed commit to make it SEMVER compliant
> [GHSA-gw62-c7w4-x449] studygolang vulnerable to cross-site scripting

- advisories/github-reviewed/2022/09/GHSA-hc94-9v26-gxwv/GHSA-hc94-9v26-gxwv.json
**Updates**
- References
**Comments**
Adding the patch link for v4.4.1: https://github.com/GluuFederation/oxAuth/commit/58c4ac9bbf2addf4b419bf155de99db57a202f5c
From an original reference link (https://gluu.org/gluu-4-4-1/): "To mitigate this risk, we’ve implemented both a request_uri blocklist and a request_uri allowlist that are configurable in the Gluu Server OpenID Provider JSON configuration."
The patch provided an "added restriction for request_uri parameter (blacklist/allowed list)" as described in the advisory.
> [GHSA-hc94-9v26-gxwv] Gluu Oxauth before v4.4.1 vulnerable to Server-Side Request Forgery attacks via a crafted request_uri parameter

- advisories/github-reviewed/2022/12/GHSA-hcpj-qp55-gfph/GHSA-hcpj-qp55-gfph.json
**Updates**
- References
**Comments**
Adding the patch link for v3.1.30: https://github.com/gitpython-developers/GitPython/commit/2625ed9fc074091c531c27ffcba7902771130261
The CVE and issue are mentioned in the commit patch message: "Forbid unsafe protocol URLs in Repo.clone{,_from}() Since the URL is passed directly to git clone, and the remote-ext helper will happily execute shell commands, so by default disallow URLs that contain a "::" unless a new unsafe_protocols kwarg is passed. (CVE-2022-24439)
Fixes 1515"
> [GHSA-hcpj-qp55-gfph] GitPython vulnerable to Remote Code Execution due to improper user input validation

- advisories/github-reviewed/2021/11/GHSA-hf9p-9r39-r2h3/GHSA-hf9p-9r39-r2h3.json
**Updates**
- References
**Comments**
Adding the patch link for v8.5.3: https://github.com/concretecms/concretecms/commit/d296f4ba4f6ad94b199c21c1b16f0d185adab343
This is the merge of the original pull (https://github.com/concretecms/concretecms/pull/8713) to resolve the issue
> [GHSA-hf9p-9r39-r2h3] Unrestricted Uploads in Concrete5

- advisories/github-reviewed/2022/05/GHSA-hpv5-v8g5-c864/GHSA-hpv5-v8g5-c864.json
**Updates**
- References
**Comments**
Adding the patch link for v0.8: https://github.com/lepture/mistune/commit/d6f0b6402299bf5a380e7b4e77bd80e8736630fe
The original pull (140) is linked to the patch: "Fix bypassing XSS vulnerability."
> [GHSA-hpv5-v8g5-c864] Cross-site Scripting in Mistune

- advisories/github-reviewed/2022/05/GHSA-hfjr-m75m-wmh7/GHSA-hfjr-m75m-wmh7.json
**Updates**
- References
**Comments**
Adding the patch link for v1.1.1: https://github.com/jenkinsci/zulip-plugin/commit/2a9dd6c41c2d913b0414d015b3118e3ddb60bd90
The commit patch message mentioned the originating SECURITY-1621 reference link (https://www.jenkins.io/security/advisory/2019-10-23/#SECURITY-1621): "SECURITY-1621 Store global config API key as Secret"
> [GHSA-hfjr-m75m-wmh7] Jenkins Zulip Plugin vulnerable to Insufficiently Protected Credentials

- advisories/github-reviewed/2022/02/GHSA-hrxv-694f-22g3/GHSA-hrxv-694f-22g3.json
**Updates**
- References
**Comments**
Adding the patch link for v0.19.0: https://github.com/eclipse/lemminx/commit/076b88052c2a63f60a98ef4b45e3e38c217b70ae
Other commits in the original pull (https://github.com/eclipse/lemminx/pull/1174) are for changelog/version updates. The patch provided is part of the pull and is the one to fix the insecure redirects.
> [GHSA-hrxv-694f-22g3] Exposure of Sensitive Information to an Unauthorized Actor in LemMinX

- advisories/github-reviewed/2021/08/GHSA-hqc8-j86x-2764/GHSA-hqc8-j86x-2764.json
**Updates**
- References
**Comments**
Adding the patch link for v0.3.3: https://github.com/nathansizemore/simple-slab/commit/5e0524c1db836e2192e1cd818848d96937c0b587
The original issue 2 (https://github.com/nathansizemore/simple-slab/issues/2) is mentioned in the message: "Fixes OOB access and off by one error. closes 2"
> [GHSA-hqc8-j86x-2764] Off-by-one error in simple-slab

- advisories/github-reviewed/2022/05/GHSA-hv53-qjg6-5pm9/GHSA-hv53-qjg6-5pm9.json
**Updates**
- References
**Comments**
Adding the patch link for v1.3.0: https://github.com/jenkinsci/gatling-plugin/commit/8a9ae59c6b3328776d38af6596b35cef1ced05a7
The commit patch message mentions one of the original reference links SECURITY-1633 (https://jenkins.io/security/advisory/2020-04-07/#SECURITY-1633): "[SECURITY-1633] No longer display the Gatling html reports through Jenkins..."
> [GHSA-hv53-qjg6-5pm9] XSS vulnerability in Jenkins Gatling Plugin

- advisories/github-reviewed/2018/03/GHSA-hwhh-2fwm-cfgw/GHSA-hwhh-2fwm-cfgw.json
**Updates**
- References
**Comments**
Adding the patch link for v4.2.6: https://github.com/doorkeeper-gem/doorkeeper/commit/7b1a8373ecd69768c896000c7971dbf48948c1b5
This is the complete merge of the pull (970) that closed the original issue (969) for the XSS vulnerability: "Fix XSS issues in default views"
> [GHSA-hwhh-2fwm-cfgw] Doorkeeper is vulnerable to stored XSS and code execution

- advisories/github-reviewed/2022/02/GHSA-j586-cj67-vg4p/GHSA-j586-cj67-vg4p.json
**Updates**
- References
**Comments**
Adding the patch link for v8.9.19: https://github.com/drupal/core/commit/6359b3ea5aacf85399285c522c6d787a218c897c
Adding the patch link for v9.1.13: https://github.com/drupal/core/commit/801910fcdfc14ee6120051089a2129e455186ad8
Adding the patch link for v9.2.6: https://github.com/drupal/core/commit/20cd85db8198c63101bd050ea973b13f2f3edef6
The commit patch message references the original link ID SA-CORE-2021-007 (https://www.drupal.org/sa-core-2021-007): "SA-CORE-2021-007"
> [GHSA-j586-cj67-vg4p] Cross-Site Request Forgery in Drupal core

- advisories/github-reviewed/2017/10/GHSA-jgqf-hwc5-hh37/GHSA-jgqf-hwc5-hh37.json
**Updates**
- References
**Comments**
Adding the patch link for v0.11.1: https://github.com/pillarjs/send/commit/98a5b89982b38e79db684177cf94730ce7fc7aed
This commit patch was mentioned in the original pull 70 (https://github.com/pillarjs/send/pull/70) to properly fix the root path disclosure issue: "Fix root path disclosure. fixes 70"
> [GHSA-jgqf-hwc5-hh37] Root Path Disclosure in send

- advisories/github-reviewed/2022/07/GHSA-jjc5-fp7p-6f8w/GHSA-jjc5-fp7p-6f8w.json
**Updates**
- References
**Comments**
Adding the patch link for v1.5.8: https://github.com/ericcornelissen/shescape/commit/aceea7358f7222984e21260381ebc5ec4543b76f
This commit patch is the complete merge into main of the originally linked pull 332 (https://github.com/ericcornelissen/shescape/pull/332): "Improve testing and escaping of newlines (332)"
> [GHSA-jjc5-fp7p-6f8w] Shescape prior to 1.5.8 vulnerable to insufficient escaping of line feeds for CMD

- advisories/github-reviewed/2021/11/GHSA-hwhf-64mh-r662/GHSA-hwhf-64mh-r662.json
**Updates**
- References
**Comments**
Adding the patch link for v1.14.2: https://github.com/fluent/fluentd/commit/5482a3d049dab351de0be68f4b4bc562319d8511
The commit patch message mentions the GHSA-ID: "Merge pull request from GHSA-hwhf-64mh-r662. parser_apache2: Fix too wide matching regexp"
> [GHSA-hwhf-64mh-r662] ReDoS vulnerability in parser_apache2

- advisories/github-reviewed/2022/01/GHSA-jrh2-hc4r-7jwx/GHSA-jrh2-hc4r-7jwx.json
**Updates**
- References
**Comments**
Adding the patch link for v2.2.26: https://github.com/django/django/commit/4cb35b384ceef52123fc66411a73c36a706825e1
Adding the patch link for v3.2.11: https://github.com/django/django/commit/8d2f7cff76200cbd2337b2cf1707e383eb1fb54b
Adding the patch link for v4.0.1: https://github.com/django/django/commit/e1592e0f26302e79856cc7f2218ae848ae19b0f6
The CVE is in the commit patch message: "Fixed CVE-2021-45452 -- Fixed potential path traversal in storage subsystem."
> [GHSA-jrh2-hc4r-7jwx] Directory-traversal in Django

- advisories/github-reviewed/2021/08/GHSA-jrf8-cmgg-gv2m/GHSA-jrf8-cmgg-gv2m.json
**Updates**
- References
**Comments**
Adding the patch link for v9.0.0: https://github.com/gz/rust-cpuid/commit/91b676eecd01f2163e2984215e2c0ac89e30ce75
The commit patch closes the original issue 40 (https://github.com/gz/rust-cpuid/issues/40): "Fix unsound transmutes (fixes 40)"
> [GHSA-jrf8-cmgg-gv2m] Error on unsupported architectures in raw-cpuid

- advisories/github-reviewed/2022/12/GHSA-jv85-mqxj-3f9j/GHSA-jv85-mqxj-3f9j.json
**Updates**
- References
**Comments**
Adding the patch link for v22.11.0: https://github.com/getsentry/sentry/commit/565f971da955d57c754a47f5802fe9f9f7c66b39
Adding the original pull: https://github.com/getsentry/sentry/pull/40905
In the pull, the description is very similar to the original advisory: "Moves the invite functionality from cookies to the session. This is to harden the security of the platform. With the cookie approach, a client can manipulate the cookie value for pending-invite resulting in situations where an invite code can be reused."
> [GHSA-jv85-mqxj-3f9j] Sentry vulnerable to invite code reuse via cookie manipulation

- advisories/github-reviewed/2021/10/GHSA-m836-gxwq-j2pm/GHSA-m836-gxwq-j2pm.json
**Updates**
- References
**Comments**
Adding the patch link for v0.53.1: https://github.com/treeverse/lakeFS/commit/f2117281cadb14fdf9ac7fe287f84d5c10308b88
The GHSA-ID is in the commit message: "Merge pull request from GHSA-m836-gxwq-j2pm"
> [GHSA-m836-gxwq-j2pm] Improper Access Control in github.com/treeverse/lakefs

- advisories/github-reviewed/2022/05/GHSA-m8r4-c7jm-w782/GHSA-m8r4-c7jm-w782.json
**Updates**
- References
**Comments**
Adding the patch link for v2.2.0: https://github.com/jenkinsci/plugin-installation-manager-tool/commit/dfc745c3a97a3fea74a3fe2e92d8a4440cbbf867
Only three commits exist for v2.2.0 (https://github.com/jenkinsci/plugin-installation-manager-tool/compare/2.1.3...2.2.0), in which the commit above is related to verifying plugin downloads: "Check that downloads are correct"
> [GHSA-m8r4-c7jm-w782] Jenkins Plugin Installation Manager Tool did not verify plugin downloads

- advisories/github-reviewed/2022/08/GHSA-mfpj-3qhm-976m/GHSA-mfpj-3qhm-976m.json
**Updates**
- References
**Comments**
Adding the patch link for asyncua v0.9.96: https://github.com/FreeOpcUa/opcua-asyncio/commit/01c7acf047887b62d979cd4373d370e72a4b9057
CVE is in the commit message: "Check limits of messages (CVE-2022-25304) (1040)"
> [GHSA-mfpj-3qhm-976m] Uncontrolled Resource Consumption in asyncua and opcua

- advisories/github-reviewed/2023/04/GHSA-776f-qx25-q3cc/GHSA-776f-qx25-q3cc.json
**Updates**
**Comments**
https://github.com/Leonidas-from-XIV/node-xml2js/issues/663
Fixed in version 0.5.0
> [GHSA-776f-qx25-q3cc] xml2js is vulnerable to prototype pollution 

- advisories/github-reviewed/2019/07/GHSA-mfv8-q39f-mgfg/GHSA-mfv8-q39f-mgfg.json
**Updates**
- References
**Comments**
Adding the patch link for v1.0.0.a20: https://github.com/inveniosoftware/invenio-communities/commit/505da72c5acd7dfbd4148f884c73c9c3372b76f4
The patch relates to the same XSS within the two Jinja templates in the invenio-communities module, where the developer starts to sanitize the HTML output. Very few commits exist for version 1.0.0.a20 (https://github.com/inveniosoftware/invenio-communities/compare/v1.0.0a19...v1.0.0a20): "views: sanitize HTML output in templates"
> [GHSA-mfv8-q39f-mgfg] Cross-site Scripting in invenio-communities

- advisories/github-reviewed/2023/02/GHSA-mhgm-52vg-pvvc/GHSA-mhgm-52vg-pvvc.json
**Updates**
- References
**Comments**
Adding the patch link for v0.5.0: https://github.com/schibsted/strongbox/commit/e61f7c36efa898e8b44de6222cd66d2bcdd073e6
The patch updated the AWS Encryption SDK, which contains the underlying issue allowing privilege escalation in Strongbox. An additional note from the changelog (within the patch commit) that mentions another GHSA from the original reference link: "Upgrade AWS Encryption SDK dependency due to GHSA-55xh-53m6-936r"
> [GHSA-mhgm-52vg-pvvc] Privilege escalation in Strongbox

- advisories/github-reviewed/2018/07/GHSA-mj4x-wcxf-hm8x/GHSA-mj4x-wcxf-hm8x.json
**Updates**
- References
**Comments**
Adding the patch link for v1.9.4: https://github.com/nov/json-jwt/commit/a3b2147f0f6d9aca653e7a30e453d3a92b33413f
The commit patch that closed the original pull (62): " Merge pull request #62 from bdewater/verify-gcm-auth-tag-length
Verify the GCM auth tag length"
> [GHSA-mj4x-wcxf-hm8x] Json-jwt (RubyGems) did not verify, or incorrectly verifies, the cryptographic signature for data

- advisories/github-reviewed/2023/04/GHSA-f8vr-r385-rh5r/GHSA-f8vr-r385-rh5r.json
**Updates**
- Description
**Comments**
Correct a typo on `processing`
> [GHSA-f8vr-r385-rh5r] hyper and h2 vulnerable to denial of service

- advisories/github-reviewed/2021/08/GHSA-2367-c296-3mp2/GHSA-2367-c296-3mp2.json
**Updates**
- References
**Comments**
Adding the patch link for v0.4.16: https://github.com/alexcrichton/tar-rs/commit/54651a87ae6ba7d81fcc72ffdee2ea7eca2c7e85
This is the complete merge of the original pull (156): "Merge pull request 156 from alexcrichton/protect-hard-links. Don't allow hardlinks to overwrite existing files"
> [GHSA-2367-c296-3mp2] Link following in tar

- advisories/github-reviewed/2023/02/GHSA-pfcc-3g6r-8rg8/GHSA-pfcc-3g6r-8rg8.json
**Updates**
- References
**Comments**
https://github.com/advisories/GHSA-pfcc-3g6r-8rg8 (CVE-2022-4492)
Updating patched versions:
* `2.3.5.Final` contains the patch for `2.3.x` versions.
* `2.2.24.Final` contains the back-ported patch for `2.2.x` versions.
**Relevant Links**
* Undertow tracking issue listing the fixed versions: https://issues.redhat.com/browse/UNDERTOW-2212
* PR with the fix for 2.3.x: https://github.com/undertow-io/undertow/pull/1447
* PR with the backport to 2.2.x: https://github.com/undertow-io/undertow/pull/1457
> [GHSA-pfcc-3g6r-8rg8] Undertow client not checking server identity presented by server certificate in https connections

- advisories/github-reviewed/2021/05/GHSA-q27f-v3r6-9v77/GHSA-q27f-v3r6-9v77.json
**Updates**
- References
**Comments**
Adding the patch link for v1.1.6: https://github.com/igrigorik/em-http-request/commit/e5fa144f8d21050dd1fc15a4dc8aa34ac6f30602
The original issue and CVE are in the commit patch message: "Merge TLS verification patch from Faraday (340). Closes 339, CVE-2020-13482"
> [GHSA-q27f-v3r6-9v77] Improper Certificate Validation in EM-HTTP-Request

- advisories/github-reviewed/2022/07/GHSA-pp3f-98qg-5g75/GHSA-pp3f-98qg-5g75.json
**Updates**
- References
**Comments**
Adding the patch link for v0.5.9: https://github.com/kubernetes-sigs/aws-iam-authenticator/commit/029d1dcf2ec8d662d9b1c21260bb197404bc8218
This commit patch is specific for v0.5.9 (https://github.com/kubernetes-sigs/aws-iam-authenticator/compare/v0.5.8...v0.5.9), it's from the original pull (469): "Add query parameter validation for multiple parameters"
> [GHSA-pp3f-98qg-5g75] aws-iam-authenticator allow-listed IAM identity may be able to modify their username, escalate privileges before v0.5.9

- advisories/github-reviewed/2022/07/GHSA-pmjg-52h9-72qv/GHSA-pmjg-52h9-72qv.json
**Updates**
- References
**Comments**
Adding the patch link for v2.3.6: https://github.com/argoproj/argo-cd/commit/8d5119b1e3038a2c1d8b651cb242525e9e734c4c
Adding the patch link for v2.4.5: https://github.com/argoproj/argo-cd/commit/3800a1e49d1d5a00a6692fee83396a37a6abe89a
The GHSA-ID is in the commit patch message: "Merge pull request from GHSA-pmjg-52h9-72qv"
> [GHSA-pmjg-52h9-72qv] Argo CD SSO users vulnerable to Cross-site Scripting

- advisories/github-reviewed/2019/01/GHSA-ph58-4vrj-w6hr/GHSA-ph58-4vrj-w6hr.json
**Updates**
- References
**Comments**
Adding the patch link for v3.4.0: https://github.com/twbs/bootstrap/commit/2a5ba23ce8f041f3548317acc992ed8a736b609d
This is the complete merge of 27047 that closed 27405. It fixes multiple CVEs: "* fix(affix): XSS on target config. Fixes #27045"
> [GHSA-ph58-4vrj-w6hr] bootstrap Cross-site Scripting vulnerability

- advisories/github-reviewed/2019/05/GHSA-pgr8-jg6h-8gw6/GHSA-pgr8-jg6h-8gw6.json
**Updates**
- References
**Comments**
Adding the patch link for v3.3.2: https://github.com/webpack-contrib/webpack-bundle-analyzer/commit/20f2b4c553ee343f491faf63e39427fba9908c7c
The patch commit from the original pull (264) that closes the original issue (263): "Fix regression with escaping internal assets"
> [GHSA-pgr8-jg6h-8gw6] Cross-Site Scripting in webpack-bundle-analyzer

- advisories/github-reviewed/2021/08/GHSA-pf3p-x6qj-6j7q/GHSA-pf3p-x6qj-6j7q.json
**Updates**
- References
**Comments**
Adding the patch link for v0.7.6: https://github.com/tokio-rs/mio/commit/152e0751f0be1c9b0cbd6778645b76bcb0eba93c
Adding the pull: https://github.com/tokio-rs/mio/pull/1388
The pull (1388) closed the original issue (1386): "Don't assume memory layout of std::net::SocketAddr. Fixes 1388."
1388 pull message: "Fixes 1386"
> [GHSA-pf3p-x6qj-6j7q] mio invalidly assumes the memory layout of std::net::SocketAddr

- advisories/github-reviewed/2021/09/GHSA-p9wf-3xpg-c9g5/GHSA-p9wf-3xpg-c9g5.json
**Updates**
- References
**Comments**
Adding the patch link for v4.5.0: https://github.com/geopython/pywps/commit/7d6b26a2e931df2feca0b7fb24f4d01610825aee
The commit patch is the complete merge of the original pull (616): "Merge pull request #616 from cehbrecht/fix-lxml-parser. Fix lxml default parser"
> [GHSA-p9wf-3xpg-c9g5] XML External Entity Injection in PyWPS

- advisories/github-reviewed/2022/06/GHSA-p2g9-94wh-65c2/GHSA-p2g9-94wh-65c2.json
**Updates**
- References
**Comments**
Adding the patch link for v3.1.3: https://github.com/rust-ammonia/ammonia/commit/6c7bf22907a75d1bbaed52e4f7dd9716f5e6f737
The patch commit is from the original pull (147): "Fix a space bug in clean_text. I mixed up FF with CR when reading an ASCII table. Bug reported via email."
> [GHSA-p2g9-94wh-65c2] Space bug in `clean_text`

- advisories/github-reviewed/2021/09/GHSA-mwgj-7x7j-6966/GHSA-mwgj-7x7j-6966.json
**Updates**
- References
**Comments**
Adding patch links for v1.1.0 (each closed the below pulls): https://github.com/facebookresearch/ParlAI/commit/507d066ef432ea27d3e201da08009872a2f37725
https://github.com/facebookresearch/ParlAI/commit/4374fa2aba383db6526ab36e939eb1cf8ef99879
Adding original pulls: https://github.com/facebookresearch/ParlAI/pull/3402
https://github.com/facebookresearch/ParlAI/pull/3429
From the release for v1.1.0: "[security] RCE fixed in chat services (3402, 3429)" -> 3402 & 3429 are in regards to the unsafe YAML that causes the RCE.
> [GHSA-mwgj-7x7j-6966] Deserialization of Untrusted Data in ParlAI

- advisories/github-reviewed/2022/02/GHSA-mpq4-rjj8-fjph/GHSA-mpq4-rjj8-fjph.json
**Updates**
- References
**Comments**
Adding patch links for v0.3.3: https://github.com/google/fscrypt/commit/91aa3ebf42032ca783c41f9ec25d885875f66ddb
The patch commit is the complete merge of the original pull (346): "Merge pull request 346 from google/fixes
Metadata validation and other security improvements"
> [GHSA-mpq4-rjj8-fjph] Uncontrolled Resource Consumption in github.com/google/fscrypt

- advisories/github-reviewed/2021/08/GHSA-mm7v-vpv8-xfc3/GHSA-mm7v-vpv8-xfc3.json
**Updates**
- References
**Comments**
Adding patch links for v0.6.10: 
https://github.com/servo/rust-smallvec/commit/c20cfa8584e649f00dc0767ab6fad63a3f59a296
https://github.com/servo/rust-smallvec/commit/f96322b9243405cc82701cc73f1b19313b413ab4
Adding additional issue: https://github.com/servo/rust-smallvec/issues/149 
The commit (https://github.com/servo/rust-smallvec/commit/c20cfa8584e649f00dc0767ab6fad63a3f59a296) closed the original issue 148 (https://github.com/servo/rust-smallvec/issues/148). In issue 148, developers also mentioned that 149 (https://github.com/servo/rust-smallvec/issues/149) was relevant. The commit (https://github.com/servo/rust-smallvec/commit/f96322b9243405cc82701cc73f1b19313b413ab4) closed 149, which was related to the original vulnerability.
> [GHSA-mm7v-vpv8-xfc3] Double free in smallvec

- advisories/github-reviewed/2018/07/GHSA-mm62-wxc8-cf7m/GHSA-mm62-wxc8-cf7m.json
**Updates**
- References
**Comments**
Adding the patch link for v1.0.0: https://github.com/commenthol/serialize-to-js/commit/1cd433960e5b9db4c0b537afb28366198a319429
The patch commit started to santize the input function as described in the PoC from the advisory: "harmful deserialization fix"
> [GHSA-mm62-wxc8-cf7m] Code Execution Through IIFE in serialize-to-js

- advisories/github-reviewed/2022/04/GHSA-mm33-5vfq-3mm3/GHSA-mm33-5vfq-3mm3.json
**Updates**
- References
**Comments**
Adding the patch link for v5.2.7.1: https://github.com/rails/rails/commit/d2253115ac2b30f5f7210670af906cebf79cf809
Adding the patch link for v6.0.4.8: https://github.com/rails/rails/commit/5299b57d596ea274f77f5ffee2b79c6ee0255508
Adding the patch link for v6.1.5.1: https://github.com/rails/rails/commit/2b820a2a69fa50cffa74b4aedc57bf92ed6910ec
Adding the patch link for v7.0.2.4: https://github.com/rails/rails/commit/8198d7c4accad0b6ba956b9d59528534a289866b
The commit patch for each version that closed the original pull (44635): "Merge pull request 44635 from imtayadeway/tjw/api-csp-i
Generate content security policy for non-HTML responses."
> [GHSA-mm33-5vfq-3mm3] Cross-site Scripting Vulnerability in Action Pack

- advisories/github-reviewed/2022/01/GHSA-53xv-c2hx-5w6q/GHSA-53xv-c2hx-5w6q.json
**Updates**
- References
**Comments**
Adding the patch link for v1.0.0-beta.6: https://github.com/coreybutler/node-windows/commit/a379d31366edbd7a672a981e6c09e185ab448dd3
It's the only related commit to the command injection fix: "prevent arbitrary command execution."
> [GHSA-53xv-c2hx-5w6q] Command Injection in node-windows

- advisories/github-reviewed/2017/10/GHSA-4jm3-pfpf-h54p/GHSA-4jm3-pfpf-h54p.json
**Updates**
- References
**Comments**
Adding the patch link for v1.0.3: https://github.com/dejan/espeak-ruby/commit/5251744b13bdd9fb0c72c612226e72d330bac143
The original issue (7) was mentioned in the commit patch message: "Replace sanitized_text method - Fix 7. Remove `sanitized_text` method and use `IO.popen` rather than `system` to prevent command injection."
> [GHSA-4jm3-pfpf-h54p] espeak-ruby allows arbitrary command execution

- advisories/github-reviewed/2022/05/GHSA-4pmp-38hf-rmwj/GHSA-4pmp-38hf-rmwj.json
**Updates**
**Comments**
The first available pypi package is from 2018: https://pypi.org/project/neutron/#history (predating the versions listed here), and none of them follow the calver versions specified. 
It seems likely this is a false match (at least for PyPI), and should be withdrawn
> [GHSA-4pmp-38hf-rmwj] OpenStack Neutron allows remote authenticated users to cause a denial of service

- advisories/github-reviewed/2018/03/GHSA-446m-mv8f-q348/GHSA-446m-mv8f-q348.json
**Updates**
- References
**Comments**
Adding the patch link for v2.19.3: https://github.com/moment/moment/commit/69ed9d44957fa6ab12b73d2ae29d286a857b80eb
This is the complete merge of the original pull (4326) from the advisory: "[bugfix] Fix for ReDOS vulnerability (see 4163) (4326)
* Limiting regex match to 256 chars, fixing 4163
* Limiting regex match to 256 chars, fixing 4163
* Also limiting numbers to fix 4163"
> [GHSA-446m-mv8f-q348] Regular Expression Denial of Service in moment

- advisories/github-reviewed/2019/05/GHSA-42xw-2xvc-qx8m/GHSA-42xw-2xvc-qx8m.json
**Updates**
- References
**Comments**
Adding the patch link for v0.18.1: https://github.com/axios/axios/commit/acabfbdf00a58bb866c9d070e8a10d1d0dbeb572
This was from pull 1485 that was used to fix the original issue (1098): "Destroy stream on exceeding maxContentLength (fixes 1098) (1485)"
> [GHSA-42xw-2xvc-qx8m] Denial of Service in axios

- advisories/github-reviewed/2022/05/GHSA-4262-wr7p-gpcj/GHSA-4262-wr7p-gpcj.json
**Updates**
- References
**Comments**
Adding the patch link for v3.0.13: https://github.com/rundeck/rundeck/commit/e992e94bba22d9fca3a669f0d02c85b80a19f848
This was from pull 4407 that was used to fix the original issue (4406): "Merge pull request 4407 from rundeck/issue/4406-stored-xss
Fix 4406: stored xss vulnerability"
> [GHSA-4262-wr7p-gpcj] Rundeck Community Edition vulnerable to Cross-site Scripting

- advisories/github-reviewed/2022/11/GHSA-3gfj-fxx4-f22w/GHSA-3gfj-fxx4-f22w.json
**Updates**
- References
**Comments**
Adding the patch link for v0.2.5: https://github.com/openfga/openfga/commit/776e80505e8d184b2286acc8268d8d74f36a9984
The GHSA-ID is mentioned in the commit patch message: "Merge pull request from GHSA-3gfj-fxx4-f22w"
> [GHSA-3gfj-fxx4-f22w] OpenFGA Authorization Bypass

- advisories/github-reviewed/2021/04/GHSA-3c67-gc48-983w/GHSA-3c67-gc48-983w.json
**Updates**
- References
**Comments**
Adding the patch link for v2.9.7: https://github.com/ansible/ansible/commit/b2551bb6943eec078066aa3a923e0bb3ed85abe8
The CVE is mentioned in the commit patch message: "ansible-galaxy - Fix tar path traversal issue during install - CVE-2020-10691 - 2.9 (68601)
* ansible-galaxy - Fix tar path traversal issue during install - CVE-2020-10691 (68596)"
> [GHSA-3c67-gc48-983w] Path Traversal in Ansible

- advisories/github-reviewed/2021/08/GHSA-37jj-wp7g-7wj4/GHSA-37jj-wp7g-7wj4.json
**Updates**
- References
**Comments**
Adding the patch link for v0.2.4: https://github.com/hrektts/cdr-rs/commit/0e6006de464caa331643f86cd2d9ba3b32b09833
The commit patch is from pull 11 (https://github.com/hrektts/cdr-rs/pull/11), which closed the original issue (10) from the advisory: "Fix not to use uninitialized memory"
> [GHSA-37jj-wp7g-7wj4] Read of uninitialized memory in cdr

- advisories/github-reviewed/2020/08/GHSA-363h-vj6q-3cmj/GHSA-363h-vj6q-3cmj.json
**Updates**
- References
**Comments**
Adding the patch link for v6.1.0: https://github.com/hapijs/hapi/commit/d47f57abf23bdaa84f61aed2bac94ae5f358afb7
This is the complete merge of the original pull (1766) from the advisory: "Merge pull request 1766 from patrickkettner/rosetta-flash prepend jsonp callbacks with a comment to prevent the rosetta-flash vulnerability"
> [GHSA-363h-vj6q-3cmj] Rosetta-Flash JSONP Vulnerability in hapi

- advisories/github-reviewed/2021/09/GHSA-32hw-3pvh-vcvc/GHSA-32hw-3pvh-vcvc.json
**Updates**
- References
**Comments**
Adding the patch link for v3.3.4: https://github.com/mautic/mautic/commit/942cb6992df619fdf1c181bfad9e25d5d4178b6f
The GHSA-ID in the commit patch message: "Merge pull request from GHSA-32hw-3pvh-vcvc
* Fixing xss on common controller for Mautic 3.x branch.
* Add test cases to validate xss filteration."
> [GHSA-32hw-3pvh-vcvc] XSS vulnerability on password reset page

- advisories/github-reviewed/2021/08/GHSA-2v78-j59h-fmpf/GHSA-2v78-j59h-fmpf.json
**Updates**
- References
**Comments**
Adding the patch link for v0.10.1: https://github.com/nabijaczleweli/safe-transmute-rs/commit/a134e06d740f9d7c287f74c0af2cd06206774364
This commit was the original pull (36) merge to resolve the overflow: "Fix vec-to-vec conversion primitives - wrong function parameter order!"
> [GHSA-2v78-j59h-fmpf] Heap overflow or corruption in safe-transmute

- advisories/github-reviewed/2021/07/GHSA-2f2w-349x-vrqm/GHSA-2f2w-349x-vrqm.json
**Updates**
- References
**Comments**
Adding the patch link for v3.5.7: https://github.com/getkirby/kirby/commit/f5ead62f8510158bed5baf58ca0e851875778a09
The GHSA-ID is in the commit message: "Merge pull request from GHSA-2f2w-349x-vrqm. [3.5.7] `v-html` security fixes"
> [GHSA-2f2w-349x-vrqm] Cross-site scripting (XSS) from field and configuration text displayed in the Panel

- advisories/github-reviewed/2022/05/GHSA-2chv-87wj-pjv2/GHSA-2chv-87wj-pjv2.json
**Updates**
- References
**Comments**
Adding the patch link for v2.7.2: https://github.com/OHDSI/WebAPI/commit/d7b12b2f5234e425e5bc76545e75de0d6eb3f8fd
This is the complete merge of the original pull (1101): "Fixes SQL injection vulnerability (1101)"
> [GHSA-2chv-87wj-pjv2] OHDSI WebAPI vulnerable to SQL Injection

- advisories/github-reviewed/2022/04/GHSA-5h7w-hmxc-99g5/GHSA-5h7w-hmxc-99g5.json
**Updates**
- References
**Comments**
Adding the patch link for v1.9.10: https://github.com/10up/safe-svg/commit/00cb9a86d1bff2214714557d1901ec3896564e50
This is the complete merge of the original pull (28): "Merge pull request 28 from 10up/fix/proper-type-checking. Better checking of the file type when determining which files are SVGs"
> [GHSA-5h7w-hmxc-99g5] Cross site scripting in safe-svg

- advisories/github-reviewed/2022/01/GHSA-64wv-8vwp-xgw2/GHSA-64wv-8vwp-xgw2.json
**Updates**
- References
**Comments**
Adding the patch link for v0.33.1: https://github.com/ash-rs/ash/commit/2c98b6f384a017de031698bd623551a45f24c8f9
Only two commits for v0.33.1 (https://github.com/ash-rs/ash/compare/0.33.0...0.33.1), also the developers are fixing the same function read_spv as mentioned in the advisory: "util: Zero-initialize result to prevent possible uninit memory read (470)"
> [GHSA-64wv-8vwp-xgw2] Use of Uninitialized Resource in ash.

- advisories/github-reviewed/2018/10/GHSA-6j63-35hj-vmcg/GHSA-6j63-35hj-vmcg.json
**Updates**
- References
**Comments**
Adding the patch link for v1.1.1: https://github.com/nedap/mysql-binuuid-rails/commit/9ae920951b46ff0163b16c55d744e89acb1036d4
This is the complete merge of the original pull (18): "Fix possible SQL injection issue (18)"
> [GHSA-6j63-35hj-vmcg] SQL injection in mysql-bunuuid-rails

- advisories/github-reviewed/2022/05/GHSA-4mgv-m5cm-f9h7/GHSA-4mgv-m5cm-f9h7.json
**Updates**
- References
**Comments**
Adding the patch link for v2.2.0: https://github.com/hashicorp/vault-action/commit/3526e1be65cf8faf42d6088bc5da8bff596c718a
This is the complete merge of the original pull (208): "Mask each line of multi-line secrets (208)
> [GHSA-4mgv-m5cm-f9h7] Vault GitHub Action did not correctly mask multi-line secrets in output

- advisories/github-reviewed/2021/10/GHSA-7534-mm45-c74v/GHSA-7534-mm45-c74v.json
**Updates**
- References
**Comments**
Adding the patch link for v8.3.0: https://github.com/python-pillow/Pillow/commit/31c473898c29d1b7cb6555ce67d9503a4906b83f
This is the complete merge of the original pull (5567): "Merge pull request 5567 from radarhere/sprintf. Limit sprintf modes to 10 characters"
> [GHSA-7534-mm45-c74v] Buffer Overflow in Pillow

- advisories/github-reviewed/2022/03/GHSA-69p3-xp37-f692/GHSA-69p3-xp37-f692.json
**Updates**
- References
**Comments**
Adding the patch link for v4.9.3: https://github.com/ManageIQ/kubeclient/commit/109ea71de5a8881748f03ebbe103b49f0f1c7887
This is the complete merge of the original pull (556): "Merge pull request 556 from cben/v4.y-security-config-ssl_verify [v4.y] SECURITY: Kubeclient::Config: return ssl_options[:verify_ssl] correctly"
> [GHSA-69p3-xp37-f692] Improper Certificate Validation in kubeclient

- advisories/github-reviewed/2022/05/GHSA-6gcg-hp2x-q54h/GHSA-6gcg-hp2x-q54h.json
**Updates**
- References
**Comments**
Adding the patch link for v2.1.15: https://github.com/argoproj/argo-cd/commit/7357cfdb58a560de70a0538c6e3bef6fe39505ea
Adding the patch link for v2.2.9: https://github.com/argoproj/argo-cd/commit/5e767a4b9e30983330c0fdec322192281a90eb84
Adding the patch link for v2.3.4: https://github.com/argoproj/argo-cd/commit/d36d95dc9f71ec61c1a93794f81ece6d61a0d943
The GHSA-ID is the in the commit patch message: "Merge pull request from GHSA-6gcg-hp2x-q54h"
> [GHSA-6gcg-hp2x-q54h] Symlink following allows leaking out-of-bound manifests and JSON files from Argo CD repo-server

- advisories/github-reviewed/2021/04/GHSA-6hgr-2g6q-3rmc/GHSA-6hgr-2g6q-3rmc.json
**Updates**
- References
**Comments**
Adding the patch link for v6.0.5: https://github.com/vaadin/flow/commit/815b967fc84fefa8d3a4d72b9a036f48b0d96326
Adding the pull: https://github.com/vaadin/flow/pull/10577
In the original reference link (https://vaadin.com/security/cve-2021-31408), the authors referenced pull 10577: "PR: https://github.com/vaadin/flow/pull/10577" The patch provided is the backport for v6.0.5 of the pull: "fix: store spring csrf to bootstrap page (10577)"
> [GHSA-6hgr-2g6q-3rmc] Server session is not invalidated when logout() helper method of Authentication module is used in Vaadin 18-19

- advisories/github-reviewed/2022/02/GHSA-6hv3-7c34-4hx8/GHSA-6hv3-7c34-4hx8.json
**Updates**
- References
**Comments**
Adding the patch link for v0.9.5: https://github.com/hashicorp/nomad/commit/e8238305ef0b9ef37be3efd86a8d34bfbed5f63f
The commit patch is the complete merge of the original pull (6055) for v0.9.5: "Render consul templates using task env only (6055)"
> [GHSA-6hv3-7c34-4hx8] Hashicorp Nomad Information Exposure Through Environmental Variables

- advisories/github-reviewed/2021/04/GHSA-6757-jp84-gxfx/GHSA-6757-jp84-gxfx.json
**Updates**
- References
**Comments**
Adding the patch link for v5.3.1: https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0
This is the complete merge of the original pull (386): "Prevents arbitrary code execution during python/object/new constructor (386)"
> [GHSA-6757-jp84-gxfx] Improper Input Validation in PyYAML

- advisories/github-reviewed/2022/05/GHSA-683w-84m7-p8pw/GHSA-683w-84m7-p8pw.json
**Updates**
- References
**Comments**
Adding patch link for v4.2.3: https://github.com/plone/Products.CMFPlone/commit/c3a98f4e6cf26501485de9c8354c49afdea21df8
Adding patch link for v4.3b1: https://github.com/plone/Products.CMFPlone/commit/a9479a5b38646fe0b0a9066ee46de9c18de32bfa
The commit patch message reads: "various security fixes based on PloneHotfix20121106," which is similar to the original link provided: https://plone.org/products/plone-hotfix/releases/20121106 (even though the original link doesn't work anymore, we can note the name of plone-hotfix 20121106)
> [GHSA-683w-84m7-p8pw] User account enumeration via crafted URL

- advisories/github-reviewed/2022/05/GHSA-68g5-8q7f-m384/GHSA-68g5-8q7f-m384.json
**Updates**
- References
**Comments**
Adding patch link for v8.5.16: https://github.com/apache/tomcat/commit/dacb030b85fe0e0b3da87469e23d0f31252fdede
Adding patch link for v9.0.0-M22: https://github.com/apache/tomcat/commit/cf181edc9a8c239cde704cffc3c503425bdcae2b
From a different reference link(https://svn.apache.org/viewvc?view=revision&revision=1796090): "Fix https://bz.apache.org/bugzilla/show_bug.cgi?id=61120. Do not ignore path parameters when processing HTTP/2 requests. This is the fix for CVE-2017-7675"
Patch commit message: "Fix https://bz.apache.org/bugzilla/show_bug.cgi?id=61120 Do not ignore path parameters when processing HTTP/2 requests."
> [GHSA-68g5-8q7f-m384] Improper Limitation of a Pathname to a Restricted Directory in Apache Tomcat

- advisories/github-reviewed/2022/01/GHSA-7wq4-89xx-g62j/GHSA-7wq4-89xx-g62j.json
**Updates**
- References
**Comments**
Adding patch link for v2.4.2: https://github.com/apache/shenyu/commit/0e826ceae97a1258cb15c73a3072118c920e8654
From an original reference link(https://www.openwall.com/lists/oss-security/2022/01/26/4): "Upgrade to Apache ShenYu (incubating) 2.4.2 or apply patch https://github.com/apache/incubator-shenyu/pull/2357."
The commit patch added is the complete merge of 2357: "fix shenyu-admin: add dashboard user permission (2357)"
> [GHSA-7wq4-89xx-g62j] Password exposure in ShenYu

- advisories/github-reviewed/2022/02/GHSA-jrpg-35hw-m4p9/GHSA-jrpg-35hw-m4p9.json
**Updates**
- References
**Comments**
Adding patch link for v1.11.2: https://github.com/go-gitea/gitea/commit/6f5656ab0ebec03fe63898208dabc802c4be46ab : "Logout POST action (10582) (10585)"
https://github.com/go-gitea/gitea/commit/ed664a9e1dae4d4660e60c981173bbc5102e69ea : "Change admin dashboard to POST (10465) (10466)"
https://github.com/go-gitea/gitea/commit/4cb18601ff33dda5edb47d5b452cc8f2dc39dd67 : "Change action GETs to POST (10462) (10464)"
These are the complete backports of the original pulls
> [GHSA-jrpg-35hw-m4p9] Capture-replay in Gitea

- advisories/github-reviewed/2020/09/GHSA-qgfr-5hqp-vrw9/GHSA-qgfr-5hqp-vrw9.json
**Updates**
- References
**Comments**
Adding patch link for v4.2.1: https://github.com/kevva/decompress/commit/967146e70f48be32ed1a69daa3941d681944d513
This is the complete merge of the original pull 73: "Prevent directory traversal (73)"
> [GHSA-qgfr-5hqp-vrw9] Path Traversal in decompress

- advisories/github-reviewed/2021/08/GHSA-qj3v-q2vj-4c8h/GHSA-qj3v-q2vj-4c8h.json
**Updates**
- References
**Comments**
Adding patch link for v0.3.1: https://github.com/arkworks-rs/r1cs-std/commit/47ddbaa411afe7c499311a248a38135e5a192b67
This is the complete merge of the original pull 70: "Enforce mul_by_inverse (70)
* proposal to fix mul_by_inverse
* update CHANGELOG
* rollback to a secure impl
* update changelog"
> [GHSA-qj3v-q2vj-4c8h] Calculation error in ark-r1cs-std

- advisories/github-reviewed/2023/01/GHSA-qrg7-hfx7-95c5/GHSA-qrg7-hfx7-95c5.json
**Updates**
- References
**Comments**
Adding the patch link for v0.7.4-security1 (https://github.com/rancher/wrangler/compare/v0.7.2...v0.7.4-security1): https://github.com/rancher/wrangler/commit/12397eec50155cb2d24aa70bdf9e90c5f3b9a727
Adding the patch link for v0.8.5-security1: https://github.com/rancher/wrangler/commit/8649ecc062204f28764fd80157a621cbae89c9cf
Adding the patch link for v0.8.11: https://github.com/rancher/wrangler/commit/5a387e13e8d51e3340d9e5012a1951f0cca5fc90
Adding the patch link for v1.0.1: https://github.com/rancher/wrangler/commit/341018c8fef3e12867c7cb2649bd2cecac75f287
In the patch, the developers added the '--' argument, which ensures that the g.URL argument is always treated as a URL and not an option to the ls-remote command. This would prevent the command …
> [GHSA-qrg7-hfx7-95c5] Command injection in Git package in Wrangler

- advisories/github-reviewed/2022/06/GHSA-qx2j-85q5-ffp8/GHSA-qx2j-85q5-ffp8.json
**Updates**
- References
**Comments**
Adding the patch link for v0.13.218: https://github.com/zalando/skipper/commit/998a658ce5a68a336a98f4e63e4371e200860dfc
This is the complete merge of the original pull 2028: "
fix: Query predicate could be bypassed by prepared request, config is enabled by default and you can disable with -validate-query=false or (2028)"
> [GHSA-qx2j-85q5-ffp8] Query predicate bypass in Zalando Skipper

- advisories/github-reviewed/2021/11/GHSA-r28h-x6hv-2fq3/GHSA-r28h-x6hv-2fq3.json
**Updates**
- References
**Comments**
Adding the patch link for v1.0.1: https://github.com/starkbank/ecdsa-java/commit/ed22e484186d6c66d3686bfe39d01bdbabf219b6
The developer started checking the signature range to ensure it wasn't non-zero, which is the same as the original advisory, and targeted the same ecdsa-java function: "Merge pull request #16 from starkbank/fix/signature-range. Fixed signature range"
> [GHSA-r28h-x6hv-2fq3] Improper Verification of Cryptographic Signature in starkbank-ecdsa

- advisories/github-reviewed/2019/02/GHSA-rv95-4wxj-6fqq/GHSA-rv95-4wxj-6fqq.json
**Updates**
- References
**Comments**
Adding the patch link for v1.7.0: https://github.com/Pylons/colander/commit/98805557c10ab5ff3016ed09aa2d48c49b9df40b
The patch link provided is the complete merge of the original pull 323: "Merge pull request 323 from Pylons/fix/url-validator-dos. Fix: url validator"
> [GHSA-rv95-4wxj-6fqq] Loop with Unreachable Exit Condition ('Infinite Loop') in Pylons Colander

- advisories/github-reviewed/2017/10/GHSA-v9v4-7jp6-8c73/GHSA-v9v4-7jp6-8c73.json
**Updates**
- References
**Comments**
Adding the patch link for v3.0.8: https://github.com/rails/rails/commit/53a2c0baf2b128dd4808eca313256f6f4bb8c4cd
https://github.com/rails/rails/commit/ed3796434af6069ced6a641293cf88eef3b284da
The patches were noted from the original reference link(https://rubyonrails.org/2011/6/8/potential-xss-vulnerability-in-ruby-on-rails-applications) of the upgrading aspect -> https://gist.github.com/NZKoz/b2ceb626fc2bcdfe497f
Within the gist, two commits exist for the patch, which is provided above: "Ensure that the strings returned by SafeBuffer#gsub and friends aren't considered html_safe?" & "Do not modify a safe buffer in helpers"v
> [GHSA-v9v4-7jp6-8c73] Moderate severity vulnerability that affects rails

- advisories/github-reviewed/2021/08/GHSA-vcw4-8ph6-7vw8/GHSA-vcw4-8ph6-7vw8.json
**Updates**
- References
**Comments**
Adding the patch link for v0.4.7: https://github.com/SergioBenitez/Rocket/commit/b53a906a8e170fe9b151381c66a76a872c419f9e
The original issue (1534) is referenced in the commit patch message: "Fix soundness issue: make 'Formatter' panic-safe. Fixes 1534."
> [GHSA-vcw4-8ph6-7vw8] Use after free in Rocket

- advisories/github-reviewed/2019/08/GHSA-vx6v-2rg6-865h/GHSA-vx6v-2rg6-865h.json
**Updates**
- References
**Comments**
Adding the patch link for v0.9.1: https://github.com/ierror/django-js-reverse/commit/78d6aff2276f2d341f643b095515f8aaba5e67c2
This is the complete merge of the original pull 81: "avoid xss when using js_reverse_inline"
> [GHSA-vx6v-2rg6-865h] Cross-site Scripting in django-js-reverse

- advisories/github-reviewed/2019/02/GHSA-wh4h-v3f2-r2pp/GHSA-wh4h-v3f2-r2pp.json
**Updates**
- References
**Comments**
Adding the patch link for v1.11.19: https://github.com/django/django/commit/0bbb560183fabf0533289700845dafa94951f227
Adding the patch link for v2.0.11: https://github.com/django/django/commit/1f42f82566c9d2d73aff1c42790d6b1b243f7676
Adding the patch link for v2.1.6: https://github.com/django/django/commit/40cd19055773705301c3428ed5e08a036d2091f3
The CVE is referenced in the commit patch message: "Fixed CVE-2019-6975 -- Fixed memory exhaustion in utils.numberformat.format()."
> [GHSA-wh4h-v3f2-r2pp] Uncontrolled Memory Consumption in Django

- advisories/github-reviewed/2017/11/GHSA-wmjf-jpjj-9f3j/GHSA-wmjf-jpjj-9f3j.json
**Updates**
- References
**Comments**
Adding the patch link for 0.49.0: https://github.com/rubocop/rubocop/commit/dcb258fabd5f2624c1ea0e1634763094590c09d7
This commit closed the original issue 4336: "[Fix 4336] Store rubocop_cache in safer directories"
> [GHSA-wmjf-jpjj-9f3j] Rubocop Exposure of Resource to Wrong Sphere

- advisories/github-reviewed/2022/02/GHSA-wmrx-57hm-mw7r/GHSA-wmrx-57hm-mw7r.json
**Updates**
- References
**Comments**
Adding the patch link for v1.0.18: https://github.com/hashicorp/nomad/commit/1aa46c3796e924b72eb45a7f02dae32df0c1179c
Adding the patch link for v1.1.12: https://github.com/hashicorp/nomad/commit/fcb3a5d016a3dfcc63efcdb567373735a0703279
Adding the patch link for v1.2.6: https://github.com/hashicorp/nomad/commit/b3c0e6a7a53d624003698b48b6c59739552c3721
The CVE (CVE-2022-24683) was mentioned in the updated changelog during the patch: "Resolve symlinks to prevent unauthorized access to files outside the allocation directory. [CVE-2022-24683]"
> [GHSA-wmrx-57hm-mw7r] Arbitrary file reads in HashiCorp Nomad

- advisories/github-reviewed/2020/06/GHSA-wpjr-j57x-wxfw/GHSA-wpjr-j57x-wxfw.json
**Updates**
- References
**Comments**
Adding the patch link for v2.2.13: https://github.com/django/django/commit/07e59caa02831c4569bbebb9eb773bdd9cb4b206
Adding the patch link for v3.0.7: https://github.com/django/django/commit/84b2da5552e100ae3294f564f6c862fef8d0e693
The CVE (CVE-2020-13254) is mentioned in the commit patch message: "Fixed CVE-2020-13254 -- Enforced cache key validation in memcached backends."
> [GHSA-wpjr-j57x-wxfw] Data leakage via cache key collision in Django

- advisories/github-reviewed/2021/04/GHSA-wq5h-f9p5-q7fx/GHSA-wq5h-f9p5-q7fx.json
**Updates**
- References
**Comments**
Adding the patch link for v2.11.7 (https://github.com/wagtail/wagtail/compare/v2.11.6...v2.11.7), it's the only commit related to the fix: https://github.com/wagtail/wagtail/commit/5c7a60977cba478f6a35390ba98cffc2bd41c8a4
Adding the patch link for v2.12.4: https://github.com/wagtail/wagtail/commit/915f6ed2bd7d53154103cc4424a0f18695cdad6c
The patch links contain the same workaround provided in the original advisory: adding check_url within the function link_entity.
> [GHSA-wq5h-f9p5-q7fx] Improper validation of URLs ('Cross-site Scripting') in Wagtail rich text fields

- advisories/github-reviewed/2020/09/GHSA-5v9h-q3gj-c32x/GHSA-5v9h-q3gj-c32x.json
**Updates**
- References
**Comments**
Adding the patch link for v3.23.6 (https://github.com/sequelize/sequelize/compare/v3.23.5...v3.23.6): https://github.com/sequelize/sequelize/commit/562d52585902090f4e53eb21c61314098c29d795
The original issue (6194) referenced pull 6305, which was backported in pull 6306 for v3.23.6: "mysql case for GEOGRAPHY/GEOMETRY sql injection (6306)"
> [GHSA-5v9h-q3gj-c32x] SQL Injection via GeoJSON in sequelize

- advisories/github-reviewed/2018/11/GHSA-7xfp-9c55-5vqj/GHSA-7xfp-9c55-5vqj.json
**Updates**
- References
**Comments**
Adding patch link for v2.68.0: https://github.com/request/request/commit/29d81814bc16bc79cb112b4face8be6fc00061dd
From the original pull 2018: "Thanks I've added your commit here 2022 + a test case."
The commit patch added is the complete merge of 2022 that closed 2018: "Merge pull request 2022 from simov/fix-multipart. Convert numeric multipart bodies to string"
> [GHSA-7xfp-9c55-5vqj] Remote Memory Exposure in request

- advisories/github-reviewed/2018/07/GHSA-q2qh-cgc2-qhr3/GHSA-q2qh-cgc2-qhr3.json
**Updates**
- References
**Comments**
Adding patch link for v6.4.9: https://github.com/vercel/serve/commit/6adad6881c61991da61ebc857857c53409544575
This is the complete merge of the original pull 316: "Scope to working directory correctly (316)
* Scope to working directory correctly
* Make it a little faster"
> [GHSA-q2qh-cgc2-qhr3] Directory Traversal in serve

- advisories/github-reviewed/2021/05/GHSA-rjqq-98f6-6j3r/GHSA-rjqq-98f6-6j3r.json
**Updates**
- References
**Comments**
Adding the patch link for v2.3.1: https://github.com/apostrophecms/sanitize-html/commit/bdf7836ef8f0e5b21f9a1aab0623ae8fcd09c1da
This is the complete merge of the original pull (458): "Merge pull request 458 from apostrophecms/stop-idna-iframe-attacks. Stop idna iframe attacks"
> [GHSA-rjqq-98f6-6j3r] Improper Input Validation in sanitize-html

- advisories/github-reviewed/2020/09/GHSA-rvg8-pwq2-xj7q/GHSA-rvg8-pwq2-xj7q.json
**Updates**
- References
**Comments**
Adding the patch link for v3.0.0: https://github.com/brianloveswords/base64url/commit/4fbd954a0a69e9d898de2146557cc6e893e79542
The patch link provided is the complete merge of the original pull 25: "Merge pull request 25 from MeirionHughes/master. fix: validate encode input and ensure zero-filled Buffer"
> [GHSA-rvg8-pwq2-xj7q] Out-of-bounds Read in base64url

- advisories/github-reviewed/2018/07/GHSA-rvj9-8cvx-3vq9/GHSA-rvj9-8cvx-3vq9.json
**Updates**
- References
**Comments**
Adding the patch link for v0.9.3: https://github.com/cisco/node-jose/commit/f92cffb4a0398b4b1158be98423369233282e0af
The patch link message: "Fix: Validate EC public key is on configured curve" Very few commits for v0.9.3 (https://github.com/cisco/node-jose/compare/0.9.2...0.9.3), and this is the only commit related to fixing the invalid curve attack.
> [GHSA-rvj9-8cvx-3vq9] Invalid Curve Attack in node-jose

- advisories/github-reviewed/2017/10/GHSA-v633-x5vv-hqwc/GHSA-v633-x5vv-hqwc.json
**Updates**
- References
**Comments**
Adding the patch link for v1.6.3: https://github.com/expressjs/serve-index/commit/7381a1d1458959e57ee53ac932b06ff17904777e
The patch link fixes the original issue 28: "Properly escape file names in HTML. fixes 28."
> [GHSA-v633-x5vv-hqwc] Cross-Site Scripting in serve-index

- advisories/github-reviewed/2020/09/GHSA-w7rc-rwvf-8q5r/GHSA-w7rc-rwvf-8q5r.json
**Updates**
- References
**Comments**
Adding the patch link for v2.6.1: https://github.com/node-fetch/node-fetch/commit/2358a6c2563d1730a0cdaccc197c611949f6a334
Adding the patch link for v3.0.0-beta.9: https://github.com/node-fetch/node-fetch/commit/eaff0094c4dfdd5b78711a8c4f1b61e33d282072
The developers started to honor the size option after following a redirect, which is related to the original advisory: "Fix: honor the `size` option after following a redirect."
> [GHSA-w7rc-rwvf-8q5r] The `size` option isn't honored after following a redirect in node-fetch

- advisories/github-reviewed/2019/06/GHSA-wfp9-vr4j-f49j/GHSA-wfp9-vr4j-f49j.json
**Updates**
- References
**Comments**
Adding the patch link for v4.12.0: https://github.com/sequelize/sequelize/commit/ccb99daedb69e8750a241436415ccac8abef358d
Adding the pull: https://github.com/sequelize/sequelize/pull/8240
The pull 8240 fixed the original issue 7310: "feat(query-generator): change operators to be represented by symbols (8240)" From the pull description: "Fixes 7310"
> [GHSA-wfp9-vr4j-f49j] NoSQL Injection in sequelize

- advisories/github-reviewed/2021/09/GHSA-wfrj-qqc2-83cm/GHSA-wfrj-qqc2-83cm.json
**Updates**
- References
**Comments**
Adding the patch link for v4.15.0: https://github.com/TryGhost/Ghost/commit/93e4b2eafd18bc8e4c17924e0824e73617e7940c
The GHSA-ID is referenced in the commit patch message: "Fixed remote command injection when using sendmail email transport
refs GHSA-wfrj-qqc2-83cm
refs GHSA-48ww-j4fc-435p"
> [GHSA-wfrj-qqc2-83cm] Remote command injection when using sendmail email transport

- advisories/github-reviewed/2023/02/GHSA-wqxw-8h5g-hq56/GHSA-wqxw-8h5g-hq56.json
**Updates**
- References
**Comments**
Adding the patch link for v3.1.4: https://github.com/switcherapi/switcher-client-master/commit/374752563d6ce9353ee592b40c809c8136f24930
The CVE and GHSA-ID are mentioned in the commit patch message: "Merge pull request from GHSA-wqxw-8h5g-hq56
Fixes CVE-2023-23925 - Added TimedMatch for safe REGEX execution"
> [GHSA-wqxw-8h5g-hq56] Switcher Client contains Regular Expression Denial of Service (ReDoS)

- advisories/github-reviewed/2022/09/GHSA-6hrg-qmvc-2xh8/GHSA-6hrg-qmvc-2xh8.json
**Updates**
According to the commit log and release notes for joblib 1.1.1 the arbitrary code execution fix for 1.2.0 was backported into 1.1.1 released Oct 10, 2022.
joblib/joblib 
**Comments**
https://github.com/joblib/joblib/pull/1352
https://github.com/joblib/joblib/pull/1327
> [GHSA-6hrg-qmvc-2xh8] joblib vulnerable to arbitrary code execution

- advisories/github-reviewed/2018/07/GHSA-wrvr-8mpx-r7pp/GHSA-wrvr-8mpx-r7pp.json
**Updates**
- References
**Comments**
Adding the patch link for v1.4.1: https://github.com/broofa/mime/commit/855d0c4b8b22e4a80b9401a81f2872058eae274d
Adding the patch link for v2.0.3: https://github.com/broofa/mime/commit/1df903fdeb9ae7eaa048795b8d580ce2c98f40b0
The original issue (167) is mentioned in the commit patch message: "Fix 167"
> [GHSA-wrvr-8mpx-r7pp] mime Regular Expression Denial of Service when mime lookup performed on untrusted user input

- advisories/github-reviewed/2023/01/GHSA-rc47-6667-2j5j/GHSA-rc47-6667-2j5j.json
**Updates**
- References
**Comments**
Adding the patch link for v4.1.1: https://github.com/kornelski/http-cache-semantics/commit/560b2d8ef452bbba20ffed69dc155d63ac757b74#comments
The Snyk link from the advisory contained the patch link (https://security.snyk.io/vuln/SNYK-JS-HTTPCACHESEMANTICS-3248783): "Don't use regex to trim whitespace"
> [GHSA-rc47-6667-2j5j] http-cache-semantics vulnerable to Regular Expression Denial of Service

- advisories/github-reviewed/2022/05/GHSA-rcx6-7jp6-pqf2/GHSA-rcx6-7jp6-pqf2.json
**Updates**
- References
**Comments**
Adding the patch link just for the latest version -> v1.4.0-beta.2: https://github.com/emberjs/ember.js/commit/12fa46ba1c6efb9ddac7bfdef7f4f6909781c801
The other versions were backported around this commit. The CVE is in the commit patch message: "[SECURITY CVE-2014-0014] Ensure {{group}} helper escapes properly."
> [GHSA-rcx6-7jp6-pqf2] ember-source Cross-site Scripting vulnerability

- advisories/github-reviewed/2021/09/GHSA-x6jv-5vfg-gm7x/GHSA-x6jv-5vfg-gm7x.json
**Updates**
- References
**Comments**
Adding the patch link for v2.0.0: https://github.com/apache/servicecomb-service-center/commit/f4f44fe5d4a7e530ca8ee7c6f2c9e891ae8353c9
This is the complete merge of the original pull 788: "SCB-2094 Fix Security Vulnerability - Directory Traversal (788)"
> [GHSA-x6jv-5vfg-gm7x] Path traversal in ServcieCenter

- advisories/github-reviewed/2022/11/GHSA-rg6w-c352-p8pg/GHSA-rg6w-c352-p8pg.json
**Updates**
- References
**Comments**
Adding the patch link for v8.5.10: https://github.com/concretecms/concretecms/commit/0bd65388e5a6d455d8b2469fc166f1b6fdf1abbb
Adding the patch link for v9.1.3: https://github.com/concretecms/concretecms/commit/5e353be6a12764dbc2338246f2c1b6058cdfd037
Adding the pull: https://github.com/concretecms/concretecms/pull/10996
From the changelog in relation to the advisory CVE: "CVE-2022-43692 Sanitized output to prevent XSS in dashboard search pages."
The commit patch message: "Prevent browser blocked reflected XSS in dashboard search pages"
> [GHSA-rg6w-c352-p8pg] Concrete CMS vulnerable to Reflected Cross-site Scripting

- advisories/github-reviewed/2023/04/GHSA-h3r8-h5qw-4r35/GHSA-h3r8-h5qw-4r35.json
**Updates**
- Description
**Comments**
From the upstream [changelog](https://github.com/sidekiq/sidekiq/blob/main/Changes.md#708):
> SECURITY Sanitize period input parameter on Metrics pages. Specially crafted values can lead to XSS. This functionality was introduced in 7.0.4. 
But currently the advisory applies to all versions < 7.0.8.
> [GHSA-h3r8-h5qw-4r35] sidekiq vulnerable to cross-site scripting 

- advisories/github-reviewed/2021/05/GHSA-35jh-r3h4-6jhm/GHSA-35jh-r3h4-6jhm.json
**Updates**
**Comments**
as seen both in the CVE description and in the reference commits the vulnerability is in the _.template function
this function can be installed independently though the npm package manager https://www.npmjs.com/package/lodash.template
> [GHSA-35jh-r3h4-6jhm] Command Injection in lodash

- advisories/github-reviewed/2022/01/GHSA-6v39-p2xq-g5c3/GHSA-6v39-p2xq-g5c3.json
**Updates**
- References
**Comments**
Adding patch link for v2.4.2: https://github.com/apache/shenyu/pull/2462/commits/50e4b5e626ad94b415e26ef4fbe584bd51fd1b77
Adding PR: https://github.com/apache/incubator-shenyu/pull/2462
The PR was referenced in an original reference (https://www.openwall.com/lists/oss-security/2022/01/26/2)
"Upgrade to Apache ShenYu (incubating) 2.4.2 or apply patch
https://github.com/apache/incubator-shenyu/pull/2462."
> [GHSA-6v39-p2xq-g5c3] Missing authentication in ShenYu

- advisories/github-reviewed/2022/11/GHSA-6q49-35h6-rq2p/GHSA-6q49-35h6-rq2p.json
**Updates**
- References
**Comments**
Adding the patch links for the latest versions of v3.57.4: https://github.com/spatie/browsershot/commit/92cf16fc098211731f80d21687abeafbe2c457ad
https://github.com/spatie/browsershot/commit/554c3e566fde8c47ad1ac9be47eaeb9a84c4dfe2
We can see the developer no longer allows file:// in the Browsershot::html method: "do not allow file urls"
An additional commit was later added to allow users to explicitly enable files for HTML content, which I believe would be helpful for the advisory: "Allow user to explicitly use a local file for html content."
> [GHSA-6q49-35h6-rq2p] Browsershot version 3.57.3 vulnerable to improper input validation

- advisories/github-reviewed/2020/06/GHSA-mhp6-pxh8-r675/GHSA-mhp6-pxh8-r675.json
**Updates**
- References
**Comments**
Adding the patch link for v1.8.0: https://github.com/angular/angular.js/commit/2df43c07779137d1bddf7f3b282a1287a8634acd
This is the complete merge of the original pull 17028: "fix(jqLite): prevent possible XSS due to regex-based HTML replacement"
Also, removing the extra pull link that had a comma after it...
> [GHSA-mhp6-pxh8-r675] Cross site scripting in Angular

- advisories/github-reviewed/2022/05/GHSA-j8p3-8m69-2hqq/GHSA-j8p3-8m69-2hqq.json
**Updates**
- References
**Comments**
Adding the patch link for v3.2.5: https://github.com/cakephp/cakephp/commit/908754649f70bab2b1093942e17c9a46a2fcf6c2
The developer started to get the client IP from REMOTE_ADDR. Additionally, this is the same code as referenced in the original reference link (https://legalhackers.com/advisories/CakePHP-IP-Spoofing-Vulnerability.txt) and targets the same function -> clientIp(): 
Commit message is also similar to advisory for spoofing: " Don't trust Client-IP header unless behind a proxy
REMOTE_ADDR is a far safer place to get an client's IP over the header
which is easily spoofed. If someone is trusting the proxy we'll prefer
x-forwarded-for and fallback to client-ip should that not exist."
> [GHSA-j8p3-8m69-2hqq] CakePHP allows remote attackers to spoof their IP

- advisories/github-reviewed/2022/04/GHSA-qf9q-q4hh-qph3/GHSA-qf9q-q4hh-qph3.json
**Updates**
- References
**Comments**
Adding the patch link for v2.6.0: https://github.com/ankane/blazer/commit/f49fbfed7b9e406a69eb78c463c3aa5d35006d8d
Adding additional issue: https://github.com/ankane/blazer/issues/391
From issue 391, which references the original issue of 392: "thanks for reporting! More info on the issue: 392"
The commit patch added closed issue 391: "Fixed quoting issue with variables - fixes 391"
> [GHSA-qf9q-q4hh-qph3] SQL injection in blazer

- advisories/github-reviewed/2022/11/GHSA-q56r-mw39-944g/GHSA-q56r-mw39-944g.json
**Updates**
- References
**Comments**
Adding the patch link for v8.5.10: https://github.com/concretecms/concretecms/commit/d5dd12c40efed326b26862391b7e1e6f414cdd55
Adding the patch link for v9.1.3: https://github.com/concretecms/concretecms/commit/a4dc73a4a47823373d4b4824534bb9b7d251f72c
Commit patch message matches the description of the advisory: "Make the legacy_salt functionality easier to read and use strict comparison"
> [GHSA-q56r-mw39-944g] Concrete CMS vulnerable to Improper Authentication

- advisories/github-reviewed/2022/11/GHSA-4r6j-fwcx-94cf/GHSA-4r6j-fwcx-94cf.json
**Updates**
**Comments**
Just updating the affected version range to correspond to the patch version being 2.8.2 (so 2.8.1 would also be flagged as vulnerable)
> [GHSA-4r6j-fwcx-94cf] snowflake-connector-python is vulnerable to Regular Expression Denial of Service (ReDoS)

- advisories/github-reviewed/2023/01/GHSA-5pm2-9mr2-3frq/GHSA-5pm2-9mr2-3frq.json
**Updates**
**Comments**
The CVE was fixed in ODP.NET 19c lines as well, starting with Oracle.ManagedDataAccess 19.18 and Oracle.ManagedDataAccess.Core 2.19.80. Here are the excerpts from these two product NuGet READMEs.
Bug Fixes since Oracle.ManagedDataAccess.Core NuGet Package 2.19.170
====================================================================
...
Bug 34617083 RESOLVE CVE-2023-21893
Bug Fixes since Oracle.ManagedDataAccess NuGet Package 19.17.0
===================================================================
...
Bug 34617083 RESOLVE CVE-2023-21893
> [GHSA-5pm2-9mr2-3frq] Component takeover in Oracle Data Provider for .NET

- advisories/github-reviewed/2022/10/GHSA-5jp2-vwrj-99rf/GHSA-5jp2-vwrj-99rf.json
**Updates**
- References
**Comments**
Adding the patch links for v6.7.9: https://github.com/concourse/concourse/commit/ba885834d9bcbb9d1ccb9964faa7af0e78a72205
Adding the patch links for v7.8.3: https://github.com/concourse/concourse/commit/57e06711b0d861775a5a6bd078a34abeb0e2638e
Adding the commit patch link directly into the advisory for their respective versions. They are from the original pull 8566: "fix team_name overwritten bug"
> [GHSA-5jp2-vwrj-99rf] Team scope authorization bypass when Post/Put request with :team_name in body, allows HTTP parameter pollution 

- advisories/github-reviewed/2021/05/GHSA-4pv3-63jw-4jw2/GHSA-4pv3-63jw-4jw2.json
**Updates**
- References
**Comments**
Adding the patch links for the latest v1.24.1: https://github.com/apache/tika/commit/0f4d5de0f85455e91433fb0b464ea0461d7c891d
From comments in the patch that relate to the original advisory: "TikaInputStream includes a few safety features to protect against parsers that may fail to check for an EOF or may incorrectly rely on the unreliable value returned from {link FileInputStream#skip}.  These parser failures can lead to infinite loops."
Additionally, System.exit was removed in the last file, an aspect of what could be triggered from the original vulnerability.
> [GHSA-4pv3-63jw-4jw2] Missing Release of Memory after Effective Lifetime in Apache Tika

- advisories/github-reviewed/2017/10/GHSA-4936-rj25-6wm6/GHSA-4936-rj25-6wm6.json
**Updates**
- References
**Comments**
Adding the patch links for the latest v2.0.2: https://github.com/savonrb/nori/commit/818f5263b1d597b603d46cbe1702cd2717259e32
https://github.com/savonrb/nori/commit/c5e07f5c32e615f0a4a7ee2782d37f7a33261be4
In the changelog, the developers mention the Rails CVE-2013-0156, which was mentioned in the advisory: "Fix for remote code execution bug. For more in-depth information, read about the recent [Rails hotfix](https://groups.google.com/forum/?fromgroups=#!topic/rubyonrails-security/61bkgvnSGTQ)."
Additionally, the developer targets the YAML and symbol type conversion aspect: "fixed YAML remote code execution vulnerability"
> [GHSA-4936-rj25-6wm6] nori contains Improper Input Validation

- advisories/github-reviewed/2022/05/GHSA-46r5-59fg-2fjc/GHSA-46r5-59fg-2fjc.json
**Updates**
- References
**Comments**
Adding the patch links for v9.2.0.CR1: https://github.com/infinispan/infinispan/commit/1deadcb1c74ea0337abd5382c0150b000f6b106f
https://github.com/infinispan/infinispan/commit/2944b0d1369a230bde88392b222921537c99331e
The developer didn't squash the merge, so the patches appear as two separate patch links from the original 5639 pull: 
"ISPN-8624 White list unmarshalling for GenericJBossMarshaller "
"ISPN-8624 Custom marshaller implementors should verify class names"
> [GHSA-46r5-59fg-2fjc] Deserialization of Untrusted Data in Infinispan

- advisories/github-reviewed/2022/11/GHSA-rc2q-x9mf-w3vf/GHSA-rc2q-x9mf-w3vf.json
**Updates**
- Description
**Comments**
See analysis done in the context of the Gradle Build tool report - https://github.com/gradle/gradle/issues/24062#issuecomment-1525631857
*  introduced a lower bound, as there are older versions that are not affected.
* I reformatted and clarified the description as well.
I did not attempt to update the CVE score, as I do not master the meaning of all fields. But the level seems highly inflated, as if TestNG could be used in a webapp accepting uploads. But that's not the case at all. Not sure how to represent this in the CVE score.
And if a user runs test with an infected JAR, there are much more serious risks simply from code execution _directly_.
> [GHSA-rc2q-x9mf-w3vf] TestNG is vulnerable to Path Traversal

- advisories/github-reviewed/2022/01/GHSA-29mw-wpgm-hmr9/GHSA-29mw-wpgm-hmr9.json
**Updates**
**Comments**
as seen both in the CVE description and in the reference commits the vulnerability is in the _.trim and _.trimEnd functions
these functions can be installed independently though the npm package manager https://www.npmjs.com/package/lodash.trim https://www.npmjs.com/package/lodash.trimend
> [GHSA-29mw-wpgm-hmr9] Regular Expression Denial of Service (ReDoS) in lodash

- advisories/github-reviewed/2021/11/GHSA-6mqr-q86q-6gwr/GHSA-6mqr-q86q-6gwr.json
**Updates**
- References
**Comments**
Adding the patch link for v4.2.1: https://github.com/spree/spree_auth_devise/commit/50bf2444a851f10dff926eb4ea3674976d9d279d
The commit patch message is very similar to the original advisory: "[PATCH] Fix account takeover through CSRF attack"
> [GHSA-6mqr-q86q-6gwr] Authentication Bypass by CSRF Weakness

- advisories/github-reviewed/2021/08/GHSA-q9h2-4xhf-23xx/GHSA-q9h2-4xhf-23xx.json
**Updates**
- References
**Comments**
Adding the patch link for v15.1.0: https://github.com/bodil/im-rs/commit/0b3a7b228b0fe70446393f55c8b893f349f3f6bd
This is the complete merge of the originally linked pull 158: "Add Send and Sync bounds for TreeFocus"
> [GHSA-q9h2-4xhf-23xx] Data races in im

- advisories/github-reviewed/2022/05/GHSA-q73f-vjc2-3gqf/GHSA-q73f-vjc2-3gqf.json
**Updates**
- References
**Comments**
Adding the patch link for v2015.1.2: https://github.com/openstack/glance/commit/eb99e45829a1b4c93db5692bdbf636a86faa56c4
The patch closed the original bug (https://bugs.launchpad.net/glance/+bug/1471912): "Don't import files with backed files.....Closes-bug: 1471912"
> [GHSA-q73f-vjc2-3gqf] OpenStack Image Service (Glance) allows remote authenticated users to read arbitrary file

- advisories/github-reviewed/2022/09/GHSA-m69r-9g56-7mv8/GHSA-m69r-9g56-7mv8.json
**Updates**
- References
**Comments**
Adding the patch link for v1.13.2: https://github.com/hashicorp/consul/commit/8f6fb4f6fe9488b8ec37da71ac503081d7d3760b
Adding the pull: https://github.com/hashicorp/consul/pull/14579
The developer starts to check that only one SAN URI value is present, similar to the original vulnerability: "Added URI length checks to ConnectCA CSR requests. Prior to this change, it was possible for a malicious actor to designate multiple SAN URI values in a call to the `ConnectCA.Sign` endpoint. The endpoint now only allows for exactly one SAN URI to be specified."
> [GHSA-m69r-9g56-7mv8] HashiCorp Consul vulnerable to authorization bypass

- advisories/github-reviewed/2022/05/GHSA-jgm2-m5cg-f66g/GHSA-jgm2-m5cg-f66g.json
**Updates**
- References
**Comments**
Adding the patch link for v7.0.30: https://github.com/apache/tomcat/commit/f78c0cdfc8a3c2efdfe6df6b69e5e3daafa3f588
This is the commit patch link for the original Apache-SVN reference link (http://svn.apache.org/viewvc?view=revision&revision=1377892): "Merged revision 1377887 from tomcat/trunk:
Remove unneeded handling of FORM authentication in RealmBase.
The login and error pages are handled via forward, so processing completes before this code is ever reached.
The action page is handled elsewhere.
git-svn-id: https://svn.apache.org/repos/asf/tomcat/tc7.0.x/trunk@1377892"
> [GHSA-jgm2-m5cg-f66g] Authentication Bypass in Apache Tomcat

- advisories/github-reviewed/2022/11/GHSA-gmpq-xrxj-xh8m/GHSA-gmpq-xrxj-xh8m.json
**Updates**
- References
**Comments**
Adding the patch link for v7.2.0: https://github.com/archesproject/arches/commit/7ed53e23a616edf3301d95814d9d64de5e3072a9
Adding the GHSL link: https://securitylab.github.com/advisories/GHSL-2022-070_GHSL-2022-072_Arches/
The GHSL link references the CVE: "GHSL-2022-070_GHSL-2022-072: SQL injection in Arches - CVE-2022-41892"
And the issues referenced in the commit patch reference GHSL-2022-070_GHSL-2022-072: "fixes9019, 9021, 9026 in stable/7.1.1"
> [GHSA-gmpq-xrxj-xh8m] Arches vulnerable to execution of arbitrary SQL

- advisories/github-reviewed/2023/04/GHSA-f8vr-r385-rh5r/GHSA-f8vr-r385-rh5r.json
**Updates**
- Description
**Comments**
Follow-up for https://github.com/github/advisory-database/pull/2057, that PR removed some mentions to hyper but not all. This PR removes the remaining (actually, the sentence "both packages incorrectly process..." is kinda confusing).
> [GHSA-f8vr-r385-rh5r] h2 vulnerable to denial of service

- advisories/github-reviewed/2017/10/GHSA-h835-75hw-pj89/GHSA-h835-75hw-pj89.json
**Updates**
- References
**Comments**
Adding the patch link for v3.0.17: https://github.com/rails/rails/commit/780a718723cf87b49cfe204d355948c4e0932d23
Adding the patch link for v3.1.8: https://github.com/rails/rails/commit/d0c9759d3aeb6327d68dd6c0de0fe2fed4e3c870
Adding the patch link for v3.2.8: https://github.com/rails/rails/commit/28f2c6f4037081da0a82104a3f473165ed4ed2ce
Adding the issue: https://github.com/rails/rails/issues/7215
The issue references the original CVE (CVE-2012-3464): "html_escape should escape single quotes.....Closes 7215"
> [GHSA-h835-75hw-pj89] activesupport Cross-site Scripting vulnerability

- advisories/github-reviewed/2022/01/GHSA-xrcv-f9gm-v42c/GHSA-xrcv-f9gm-v42c.json
**Updates**
- References
**Comments**
Adding the patch link for v9.0.0: https://github.com/python-pillow/Pillow/commit/5543e4e2d409cd9e409bc64cdc77be0af007a31f
Adding the pull: https://github.com/python-pillow/Pillow/pull/5920
The pull has the CVE (CVE-2022-22816) in the title: "CVE-2022-22815, CVE-2022-22816: Fixed ImagePath.Path array handling 5920"
> [GHSA-xrcv-f9gm-v42c] Out-of-bounds Read in Pillow

- advisories/github-reviewed/2021/08/GHSA-xr7r-88qv-q7hm/GHSA-xr7r-88qv-q7hm.json
**Updates**
- References
**Comments**
Adding the patch link for v0.10.2: https://github.com/pyfisch/cbor/commit/1aec4f9d71855dbfb223fa61ca60260400cc5d5f
Adding the pull: https://github.com/pyfisch/cbor/pull/153
The commit patch message is very similar to the original advisory: "Prevent stack overflow from nested tags" The developer also added a recursion check for nested tags.
> [GHSA-xr7r-88qv-q7hm] Out of bounds write in serde_cbor

- advisories/github-reviewed/2022/06/GHSA-xfqg-p48g-hh94/GHSA-xfqg-p48g-hh94.json
**Updates**
- References
**Comments**
Adding the patch link for v7.5.29: https://github.com/ezsystems/ezpublish-kernel/commit/913fe17281536a91437d94e8267181ae8b57f5d5
IBX-1755 (https://issues.ibexa.co/browse/IBX-1755) was released as IBEXA-SA-2022-006, which is one of the originally linked references (https://developers.ibexa.co/security-advisories/ibexa-sa-2022-006-vulnerabilities-in-page-builder-login-and-commerce): "IBX-1755: Implemented constant time authentication"
> [GHSA-xfqg-p48g-hh94] Login timing attack in ezsystems/ezpublish-kernel

- advisories/github-reviewed/2018/03/GHSA-x7rv-cr6v-4vm4/GHSA-x7rv-cr6v-4vm4.json
**Updates**
- References
**Comments**
Adding the patch link for v2.2.1: https://github.com/flavorjones/loofah/commit/f739cf8eac5851f328b8044281d6653f74eff116
The CVE (CVE-2018-8048) is in the commit patch message: "tests and fix for CVE-2018-8048"
> [GHSA-x7rv-cr6v-4vm4] Cross-site Scripting in loofah

- advisories/github-reviewed/2021/09/GHSA-x7g2-wrrp-r6h3/GHSA-x7g2-wrrp-r6h3.json
**Updates**
- References
**Comments**
Adding the patch link for v3.3.4: https://github.com/mautic/mautic/commit/d1cad766a2de74e6c6b89d6d78c2a5f2e36ba91c
The GHSA-ID is in the commit patch message: "Merge pull request from GHSA-x7g2-wrrp-r6h3"
> [GHSA-x7g2-wrrp-r6h3] Use of a Broken or Risky Cryptographic Algorithm

- advisories/github-reviewed/2021/08/GHSA-x4qm-mcjq-v2gf/GHSA-x4qm-mcjq-v2gf.json
**Updates**
- References
**Comments**
Adding the patch link for v0.8.0: https://github.com/tokio-rs/prost/commit/59f2a7311dd6540696bfd0145f5281ce495f4385
Adding the pull: https://github.com/tokio-rs/prost/pull/439
The original issue (438) was fixed by pull 439: "Fix 438: Check for overflow in Duration and Timestamp processing (439)"
> [GHSA-x4qm-mcjq-v2gf] Overflow in prost-types

- advisories/github-reviewed/2022/05/GHSA-wx7c-8j35-mpg8/GHSA-wx7c-8j35-mpg8.json
**Updates**
- References
**Comments**
Adding the patch link for v0.13.6: https://github.com/fatfreecrm/fat_free_crm/commit/86fd7f98c9583fd36384987282d1c086fdcecd7c
The CVE is mentioned in the commit patch message: "Fix for CVE-2015-1585 - CSRF vulnerability."
> [GHSA-wx7c-8j35-mpg8] Fat Free CRM Cross-Site Request Forgery vulnerability

- advisories/github-reviewed/2017/11/GHSA-wwh7-4jw9-33x6/GHSA-wwh7-4jw9-33x6.json
**Updates**
- References
**Comments**
Adding the patch link for v1.3.1: https://github.com/brianmario/yajl-ruby/commit/a8ca8f476655adaa187eedc60bdc770fff3c51ce
Adding the pull: https://github.com/brianmario/yajl-ruby/pull/178
The original issue (176) was fixed by pull 178: "Don't advance our end pointer until we've checked we have enough buffer left and have peeked ahead to see that a unicode escape is approaching."
> [GHSA-wwh7-4jw9-33x6] yajl-ruby vulnerable to Use of Externally-Controlled Format String

- advisories/github-reviewed/2020/09/GHSA-w725-67p7-xv22/GHSA-w725-67p7-xv22.json
**Updates**
- References
**Comments**
Adding the patch link for v3.0.0: https://github.com/DylanPiercey/local-devices/commit/57b9a933c9d23d34bd5a055536db824de66db553
This is the complete merge of the original pull 16: "fix: validate ip address before executing command for 'find' (16)"
> [GHSA-w725-67p7-xv22] Command Injection in local-devices

- advisories/github-reviewed/2022/03/GHSA-w267-m9c4-8555/GHSA-w267-m9c4-8555.json
**Updates**
- References
**Comments**
Adding the patch link for v6.4.8.1: https://github.com/shopware/platform/commit/47b4b094c13f62db860be2f431138bb45c0bd0b6
The NEXT ID (NEXT-19820) is mentioned in one of the originally linked references (https://docs.shopware.com/en/shopware-6-en/security-updates/security-update-02-2022?category=security-updates): "NEXT-19820: User session is not logged out if the password is reset via password recovery"
Commit patch message: "NEXT-19820 - Improve session invalidation on customer updates"
> [GHSA-w267-m9c4-8555] Shopware user session is not logged out if the password is reset via password recovery

- advisories/github-reviewed/2022/05/GHSA-vmhj-p9hw-vgrf/GHSA-vmhj-p9hw-vgrf.json
**Updates**
- References
**Comments**
Adding the patch link for v2.0.6: https://github.com/containers/podman/commit/c140ecdc9b416ab4efd4d21d14acd63b6adbdd42
The CVE is mentioned in the commit patch message: "This resolves CVE-2020-1726."
> [GHSA-vmhj-p9hw-vgrf] Podman has Files or Directories Accessible to External Parties

- advisories/github-reviewed/2023/05/GHSA-m2qf-hxjv-5gpq/GHSA-m2qf-hxjv-5gpq.json
**Updates**
**Comments**
The fix was backported to the 2.2.x branch, released in Flask 2.2.5.
> [GHSA-m2qf-hxjv-5gpq] Flask vulnerable to possible disclosure of permanent session cookie due to missing Vary: Cookie header

- advisories/github-reviewed/2023/03/GHSA-c25x-cm9x-qqgx/GHSA-c25x-cm9x-qqgx.json
**Updates**
**Comments**
The change only affects a single specific rev - not the wide range specified previously.
See the source advisory here.
https://github.com/denoland/deno/security/advisories/GHSA-c25x-cm9x-qqgx
> [GHSA-c25x-cm9x-qqgx] Deno improperly handles resizable ArrayBuffer

- advisories/github-reviewed/2023/03/GHSA-pqg3-xfx2-fmqp/GHSA-pqg3-xfx2-fmqp.json
**Updates**
- CVSS
- References
**Comments**
The score mentioned earlier is incorrect. You can view the correct score on the Jenkins Security Advisory 2023-03-08 (https://www.jenkins.io/security/advisory/2023-03-08/) at the following link: https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
I have also added a blog post about this research.
> [GHSA-pqg3-xfx2-fmqp] Cross site scripting vulnerability in update-center2 

- advisories/github-reviewed/2023/03/GHSA-j664-qhh4-hpf8/GHSA-j664-qhh4-hpf8.json
**Updates**
- CVSS
- References
- Severity
**Comments**
The score mentioned earlier is incorrect. You can view the correct score on the Jenkins Security Advisory 2023-03-08 (https://www.jenkins.io/security/advisory/2023-03-08/)  at the following link: https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
I have also added a blog post about this research.
> [GHSA-j664-qhh4-hpf8] Cross-site Scripting vulnerability in Jenkins

- advisories/github-reviewed/2020/08/GHSA-vrv8-v4w8-f95h/GHSA-vrv8-v4w8-f95h.json
**Updates**
- References
**Comments**
Adding the patch link for v4.9.11: https://github.com/tinymce/tinymce/commit/2b71c922214d388838d930806207a66c14e80f63
Adding the patch link for v5.4.1: https://github.com/tinymce/tinymce/pull/5843/commits/696e43658dc9750ec24fdc4650bd2be9653daf5b
Adding the PR: https://github.com/tinymce/tinymce/pull/5843
The security release text (https://www.tiny.cloud/docs/release-notes/release-notes54/#securityfixes):
"TinyMCE 5.4 provides fixes for the following security issues:
Fixed content in an iframe element parsing as DOM elements instead of text content."
Matches the updated changelog in the patch commit: "Fixed content in an iframe element parsing as dom elements instead of text content #TINY-5943"
> [GHSA-vrv8-v4w8-f95h] Cross-site scripting vulnerability in TinyMCE

- advisories/github-reviewed/2021/09/GHSA-v9j4-cp63-qv62/GHSA-v9j4-cp63-qv62.json
**Updates**
- References
**Comments**
Reference : 
https://github.com/gen2brain/go-unarr/commit/239ec404d348280b50bbf671327709e8857fc5f4
https://pkg.go.dev/github.com/gen2brain/go-unarr?tab=versions
> [GHSA-v9j4-cp63-qv62] Tarslip in go-unarr

- advisories/github-reviewed/2022/12/GHSA-f683-35w9-28g5/GHSA-f683-35w9-28g5.json
**Updates**
- References
**Comments**
Adding the patch link for the latest v3.2.6: https://github.com/bihor/fp_newsletter/commit/bc673cd9ab04f3fdd1225303f2ccb378b11a3747
As the advisory describes, "multiple vulnerabilities" and multiple were fixed related to the advisory (CAPTCHA bypass, arbitrary subscriptions, and information disclosures):"
Security fix: default password for fe_users set to a random password.	 
Security fix: mathematical captcha check enhanced (it was possible to cheat).	 
Security fix: settings.doubleOptOut set from 0 to 1. You can set it to 0 if you don't want a double opt out subscription.	 
Security fix: additional check added to the delete-action (it was possible to unsubscribe all users).	 
Security fix: Information Disclosure in the new- and unsubscribe-action."
> [GHSA-f683-35w9-28g5] Multiple vulnerabilities in extension "Newsletter subscriber management" (fp_newsletter)

- advisories/github-reviewed/2018/06/GHSA-vwjc-q9px-r9vq/GHSA-vwjc-q9px-r9vq.json
**Updates**
- References
**Comments**
Adding the patch link for the v1.4.0: https://github.com/jfhbrook/node-ecstatic/commit/0d0a2779ac5e5843d3745920212dfac9b69440e2
This is from the original pull 179 to do the actual fix by adding checks: "put modifiedDate check in a block, check for Invalid Date case"
> [GHSA-vwjc-q9px-r9vq] Denial of Service in ecstatic

- advisories/github-reviewed/2022/12/GHSA-2c7v-qcjp-4mg2/GHSA-2c7v-qcjp-4mg2.json
**Updates**
- References
**Comments**
Adding the patch link for the v3.1.32: https://github.com/dotnet/wpf/commit/7b0be4d41c33ce8525d8160bf8869cac10f8a8cd
Adding the patch link for the v6.0.12: https://github.com/dotnet/wpf/commit/c08825a9889e6c798fe95ed5ec1f6a9f517ab5a0
Adding the patch link for the v7.0.1: https://github.com/dotnet/wpf/commit/5f4c0f7763a06b024c8a517616e0fc0194e997a4
The CVE is in the commit message: "Change RestrictiveXamlXmlReader to use an allow list
- Removes the old deny list logic used by RestrictiveXamlXmlReader
- Provides an extensible (via registry) allow list mechanism
Fixes CVE-2022-41089."
> [GHSA-2c7v-qcjp-4mg2] .NET Remote Code Execution Vulnerability

- advisories/github-reviewed/2021/08/GHSA-f865-m6cq-j9vx/GHSA-f865-m6cq-j9vx.json
**Updates**
**Comments**
There is a patched version released 1.3.0
> [GHSA-f865-m6cq-j9vx] ReDOS in Mpmath

- advisories/github-reviewed/2021/08/GHSA-9jxw-cfrh-jxq6/GHSA-9jxw-cfrh-jxq6.json
**Updates**
- References
**Comments**
Adding the patch link for the v2.5.1: https://github.com/fiveai/Cachet/commit/6442976c25930cb370c65a22784b9caee7ed1de2
The GHSA-ID is in the commit message: "Prevent new lines and variables in settings values GHSA-88f9-7xxh-c688 and GHSA-9jxw-cfrh-jxq6"
> [GHSA-9jxw-cfrh-jxq6] Cachet vulnerable to new line injection during configuration edition

- advisories/github-reviewed/2023/04/GHSA-4r6h-8v6p-xvw6/GHSA-4r6h-8v6p-xvw6.json
**Updates**
- Description
- References
**Comments**
The NPM package `xlxs`and the repository hosted on Github.com are no longer maintained by SheetJS, see https://git.sheetjs.com/sheetjs/sheetjs/issues/2667. Hence, no fixed version will be released via NPM.
> [GHSA-4r6h-8v6p-xvw6] Prototype Pollution in sheetJS

- advisories/github-reviewed/2020/02/GHSA-3jqw-vv45-mjhh/GHSA-3jqw-vv45-mjhh.json
**Updates**
- References
**Comments**
Adding the patch links for the v0.7.4: https://github.com/matestack/matestack-ui-core/commit/e96915cf20c4fa0571df7fa21e9b09a69be19107
https://github.com/matestack/matestack-ui-core/commit/5c61571739e860db9ca578fe09ab4733878cb0fc
Here the developers started to escape the incoming argument in the Plain class to avoid any potentially malicious inputs: "Fix basic XSS vector, check with more of them" 
"Explicitly define html_escape In async actions the view context doesn't seem to be available, from where html_escape was called before."
> [GHSA-3jqw-vv45-mjhh] XSS/Script injection vulnerability in matestack

- advisories/github-reviewed/2021/08/GHSA-7774-7vr3-cc8j/GHSA-7774-7vr3-cc8j.json
**Updates**
- References
**Comments**
Adding the patch link for v1.9.8: https://github.com/istio/istio/commit/084b417a486dbe9b9024d4812877016a484572b1
Adding the patch link for v1.10.4: https://github.com/istio/istio/commit/76ed51413ddd2a7fa253a368ab20a9cec5fb1cbe
Adding the patch link for v1.11.1: https://github.com/istio/istio/commit/90b00bdf891e6c770cb3235c14a9b1fda96cc7c5
The patch links apply a case-insensitive match for host fields, which is similar to the original advisory description: "use case-insensitive match for host field in authz"
> [GHSA-7774-7vr3-cc8j] Authorization Policy Bypass Due to Case Insensitive Host Comparison

- advisories/github-reviewed/2022/11/GHSA-7wg4-8m5p-hrfg/GHSA-7wg4-8m5p-hrfg.json
**Updates**
- References
**Comments**
Adding the patch link for v1.4.2: https://github.com/hashicorp/nomad/commit/3b24f26603e2b116ba324101afa8a7e3a7a769a5
The updated changelog during the patch link is very similar to the advisory: "Fixed a bug where non-sensitive variable metadata (paths and raft indexes) was exposed via the template `nomadVarList` function to other jobs in the same namespace."
> [GHSA-7wg4-8m5p-hrfg] HashiCorp Nomad vulnerable to non-sensitive metadata exposure

- advisories/github-reviewed/2022/02/GHSA-r773-pmw3-f4mr/GHSA-r773-pmw3-f4mr.json
**Updates**
- References
**Comments**
Adding the patch link for v2.0.2: https://github.com/vgno/koa-remove-trailing-slashes/commit/e7ce4000e9fe4d957332df1056640a22ebea28ee
The developer removed the ability to redirect from relative URLs. Additionally, the patched code is in the same location as the advisory (index.js::removeTrailingSlashes()): "fix: only redirect for current origin"
> [GHSA-r773-pmw3-f4mr] Open Redirect in koa-remove-trailing-slashes

- advisories/github-reviewed/2023/01/GHSA-m589-mv4q-p7rj/GHSA-m589-mv4q-p7rj.json
**Updates**
- References
**Comments**
Adding the patch link for v0.8.3: https://github.com/amodm/webbrowser-rs/commit/431b5139e274b7e456bea27e768aaa121b97be4c
The commit message is very similar to the original tag comment for the advisory (The guarantee of web browser being opened (instead of local file association), now solves for the scenario where the URL is crafted to be an executable.): "define consistent behavior to include opening web browser even for local files" "This library guarantees that it's a browser that is opened (as determined by `http` scheme association, not local file association)."
> [GHSA-m589-mv4q-p7rj] webbrowser-rs allows attackers to access arbitrary files via supplying a crafted URL

- advisories/github-reviewed/2022/04/GHSA-jmxr-w2jc-qp7w/GHSA-jmxr-w2jc-qp7w.json
**Updates**
**Comments**
updating to include fix as 876.v99d29788b per https://www.jenkins.io/security/advisory/2022-04-12/#SECURITY-2655 and based on the version range used in https://github.com/advisories/GHSA-v98r-gjgc-m9pf not including the `_36b_` suffix
> [GHSA-jmxr-w2jc-qp7w] Promotion names in Jenkins promoted builds Plugin are not validated when using Job DSL

- advisories/github-reviewed/2022/01/GHSA-85rq-hp8x-ghjq/GHSA-85rq-hp8x-ghjq.json
**Updates**
**Comments**
Updating affected version range to extend up to excluding the fix version.  ~~Also I see in https://nvd.nist.gov/vuln/detail/CVE-2022-20613 that it has version 1.34.2 as excluded but I don't see any mention of that in the Jenkins announcement at https://www.jenkins.io/security/advisory/2022-01-12/#SECURITY-2163 so have left that out for the moment~~
Added 1.34.2 in based on https://github.com/github/advisory-database/issues/771#issuecomment-1549355480
> [GHSA-85rq-hp8x-ghjq] Cross-Site Request Forgery in Jenkins Mailer Plugin

- advisories/github-reviewed/2022/01/GHSA-558x-h7rg-997v/GHSA-558x-h7rg-997v.json
**Updates**
**Comments**
Adds separate version range for 1.34.2 based on CVE range info from https://nvd.nist.gov/vuln/detail/CVE-2022-20614
> [GHSA-558x-h7rg-997v] Incorrect Permission Assignment for Critical Resource in Jenkins Mailer Plugin

- advisories/github-reviewed/2022/05/GHSA-6fr3-286q-q3cr/GHSA-6fr3-286q-q3cr.json
**Updates**
**Comments**
Add backports based on cve.org data from https://github.com/CVEProject/cvelist/blob/16860a328d970faa6e4350b0fa446f64a52e52ca/2020/2xxx/CVE-2020-2252.json
> [GHSA-6fr3-286q-q3cr] Improper Validation of Certificate with Host Mismatch in Jenkins Mailer Plugin

- advisories/github-reviewed/2022/01/GHSA-9wxh-jjj5-67cv/GHSA-9wxh-jjj5-67cv.json
**Updates**
**Comments**
add backports per https://github.com/CVEProject/cvelist/blob/2d78eb36f4d084db7fb35f1535d8d84fdcb7d859/2022/20xxx/CVE-2022-20620.json
> [GHSA-9wxh-jjj5-67cv] Missing permission checks in SSH Agent Plugin allow enumerating credentials IDs

- advisories/github-reviewed/2022/01/GHSA-gg9m-x3cg-69vh/GHSA-gg9m-x3cg-69vh.json
**Updates**
**Comments**
add backports per https://github.com/CVEProject/cvelist/blob/2d78eb36f4d084db7fb35f1535d8d84fdcb7d859/2022/20xxx/CVE-2022-20621.json
> [GHSA-gg9m-x3cg-69vh] Access key stored in plain text by Jenkins Metrics Plugin

- advisories/github-reviewed/2023/05/GHSA-cqmj-92xf-r6r9/GHSA-cqmj-92xf-r6r9.json
**Updates**
**Comments**
The version range was updated.
The commit (https://github.com/socketio/socket.io-parser/commit/1c220ddbf45ea4b44bc8dbf6f9ae245f672ba1b9) was released in version `4.0.4`, so the list of affected versions can be updated from `>= 4.0.0, < 4.2.3` to `>= 4.0.4, < 4.2.3`
> [GHSA-cqmj-92xf-r6r9] Insufficient validation when decoding a Socket.IO packet

- advisories/github-reviewed/2020/01/GHSA-2qrg-x229-3v8q/GHSA-2qrg-x229-3v8q.json
**Updates**
**Comments**
The latest version of log4j 1.x is 1.2.17 not 1.2.27.
> [GHSA-2qrg-x229-3v8q] Deserialization of Untrusted Data in Log4j

- advisories/github-reviewed/2021/11/GHSA-gpqc-4pp7-5954/GHSA-gpqc-4pp7-5954.json
**Updates**
- References
**Comments**
Add CVE-2021-41275 to this advisory. Reference: 
https://github.com/rubysec/ruby-advisory-db/blob/master/gems/spree_auth_devise/CVE-2021-41275.yml
> [GHSA-gpqc-4pp7-5954] Authentication Bypass by CSRF Weakness

- advisories/github-reviewed/2021/11/GHSA-8xfw-5q82-3652/GHSA-8xfw-5q82-3652.json
**Updates**
- References
**Comments**
Please add CVE-2021-41275 to this advisory. Referece: https://github.com/rubysec/ruby-advisory-db/blob/master/gems/spree_auth_devise/CVE-2021-41275.yml
> [GHSA-8xfw-5q82-3652] Authentication Bypass by CSRF Weakness

- advisories/github-reviewed/2017/10/GHSA-xf96-32q2-9rw2/GHSA-xf96-32q2-9rw2.json
**Updates**
**Comments**
Change package name from rails to activerecord. Reference: https://github.com/rubysec/ruby-advisory-db/blob/master/gems/activerecord/CVE-2008-4094.yml
> [GHSA-xf96-32q2-9rw2] rails vulnerable to SQL injection

- advisories/github-reviewed/2017/10/GHSA-gjxw-5w2q-7grf/GHSA-gjxw-5w2q-7grf.json
**Updates**
**Comments**
Change package name from rails to activerecord. Reference: https://github.com/rubysec/ruby-advisory-db/blob/master/gems/activerecord/CVE-2010-3933.yml
> [GHSA-gjxw-5w2q-7grf] rails Improper Input Validation vulnerability

- advisories/github-reviewed/2017/10/GHSA-xxr8-833v-c7wc/GHSA-xxr8-833v-c7wc.json
**Updates**
**Comments**
Change package name from rails to actionpack. Reference: https://github.com/rubysec/ruby-advisory-db/blob/master/gems/actionpack/CVE-2011-4319.yml
> [GHSA-xxr8-833v-c7wc] Cross-site Scripting vulnerability in  i18n translations helper method

- advisories/github-reviewed/2023/04/GHSA-j4rf-7357-f4cg/GHSA-j4rf-7357-f4cg.json
**Updates**
- CVSS
**Comments**
The CVSS scores in this copy of the advisory were what they were when I originally created it, not what I ended up publishing in https://github.com/apptainer/apptainer/security/advisories/GHSA-j4rf-7357-f4cg.  Please update this one to match.  The NVD vector matched the published one except they said the attack complexity was low.
> [GHSA-j4rf-7357-f4cg] Unpatched extfs vulnerabilities are exploitable through suid-mode Apptainer and Singularity

- advisories/github-reviewed/2021/08/GHSA-6xx3-rg99-gc3p/GHSA-6xx3-rg99-gc3p.json
**Updates**
**Comments**
Added NuGet's BouncyCastle to affected products based on https://github.com/bcgit/bc-csharp/wiki/CVE-2020-15522
> [GHSA-6xx3-rg99-gc3p] Timing based private key exposure in Bouncy Castle

- advisories/github-reviewed/2018/07/GHSA-rch9-xh7r-mqgw/GHSA-rch9-xh7r-mqgw.json
**Updates**
**Comments**
the cpe in nvd references to to this package `cpe:2.3:a:sencha:connect:*:*:*:*:*:node.js:*:*`
also, in nvd there's a link to the patch which is to the `connect` package's repository (https://github.com/senchalabs/connect/commit/6d5dd30075d2bc4ee97afdbbe3d9d98d8d52d74b)
> [GHSA-rch9-xh7r-mqgw] Cross-Site Scripting in simple-server

- advisories/github-reviewed/2023/05/GHSA-2c4m-59x9-fr2g/GHSA-2c4m-59x9-fr2g.json
**Updates**
**Comments**
Patched in https://github.com/gin-gonic/gin/pull/3556, released in 1.9.1
> [GHSA-2c4m-59x9-fr2g] Gin Web Framework does not properly sanitize filename parameter of Context.FileAttachment function

- advisories/github-reviewed/2022/05/GHSA-58xm-mxjf-254g/GHSA-58xm-mxjf-254g.json
**Updates**
**Comments**
Adjust the affected ranges to reflect 2.303.3 being the fix for the LTS release per https://www.jenkins.io/security/advisory/2021-11-04/#SECURITY-2455
> [GHSA-58xm-mxjf-254g] Multiple vulnerabilities allow bypassing path filtering of agent-to-controller access control in Jenkins

- advisories/github-reviewed/2023/05/GHSA-282v-666c-3fvg/GHSA-282v-666c-3fvg.json
**Updates**
**Comments**
4.30.0 has been released.  NVD updated to show fixed (https://nvd.nist.gov/vuln/detail/CVE-2023-2800).  4.30.0 released 4 days ago (https://github.com/huggingface/transformers/releases)
> [GHSA-282v-666c-3fvg] transformers has Insecure Temporary File

- advisories/github-reviewed/2022/05/GHSA-95xq-v4m2-fq3r/GHSA-95xq-v4m2-fq3r.json
**Updates**
**Comments**
The [grit gem](https://rubygems.org/gems/grit) has no version 2.6.1. I believe the advisory is referring to [gitlab-grit](https://rubygems.org/gems/gitlab-grit), who's ChangeLog mentions 2.6.1 included various security fixes:
https://gitlab.com/gitlab-org/gitlab-grit/-/blob/v2.6.1/History.txt?ref_type=tags#L2
> [GHSA-95xq-v4m2-fq3r] GitLab Grit Gem for Ruby contains a flaw allowing arbitrary commands to be executed

- advisories/github-reviewed/2022/05/GHSA-mmrq-6999-72v8/GHSA-mmrq-6999-72v8.json
**Updates**
**Comments**
The official [blog post](https://www.ruby-lang.org/en/news/2018/10/17/openssl-x509-name-equality-check-does-not-work-correctly-cve-2018-16395/) states:
> The openssl 2.1.2 gem or later includes a fix for the vulnerability, so upgrade the openssl gem to the latest version if you are using Ruby 2.4 or a later series.
> [GHSA-mmrq-6999-72v8] Incorrect value comparison in Ruby openssl

- advisories/github-reviewed/2018/10/GHSA-x5x7-3v85-wpc4/GHSA-x5x7-3v85-wpc4.json
**Updates**
- Summary
**Comments**
Remove leading whitespace from summary
> [GHSA-x5x7-3v85-wpc4]  Apache Struts allows entering a custom URL in a form field if built-in URLValidator is used

- advisories/github-reviewed/2023/04/GHSA-qw69-rqj8-6qw8/GHSA-qw69-rqj8-6qw8.json
**Updates**
**Comments**
This GHSA is showing as a false positive when we have the documented, patched versions specified in our dependency list.
> [GHSA-qw69-rqj8-6qw8] OutOfMemoryError for large multipart without filename in Eclipse Jetty

- advisories/github-reviewed/2023/06/GHSA-7gf7-jv65-wjmh/GHSA-7gf7-jv65-wjmh.json
**Updates**
- CWEs
- Description
- References
**Comments**
Update affected versions, add more accurate CWE.
> [GHSA-7gf7-jv65-wjmh] xml-rs vulnerable to denial of service via invalid token in XML document

- advisories/github-reviewed/2023/04/GHSA-p26g-97m4-6q7c/GHSA-p26g-97m4-6q7c.json
**Updates**
**Comments**
Similar fix as https://github.com/github/advisory-database/pull/2393; The correct version is already specified in the details markdown.
> [GHSA-p26g-97m4-6q7c] Eclipse Jetty's cookie parsing of quoted values can exfiltrate values from other cookies

- advisories/github-reviewed/2023/06/GHSA-r7wr-4w5q-55m6/GHSA-r7wr-4w5q-55m6.json
https://github.com/cilium/cilium/security/advisories/GHSA-r7wr-4w5q-55m6 states that Cilium versions <1.13 are not affected. 
Update introduced version accordingly
> [GHSA-r7wr-4w5q-55m6] Update introduced version

- advisories/github-reviewed/2017/10/GHSA-8qrh-h9m2-5fvf/GHSA-8qrh-h9m2-5fvf.json
**Updates**
**Comments**
This GHSA advisory (GHSA-8qrh-h9m2-5fvf) was split to ruby-advisory-db:
* gems/actionpack/CVE-2009-3009.yml
* gems/activesupport/CVE-2009-3009.yml
This is a change-package-name PR plus clone-advisory for 2nd package-name.
> [GHSA-8qrh-h9m2-5fvf] Moderate severity vulnerability that affects rails

- advisories/github-reviewed/2017/10/GHSA-v9v4-7jp6-8c73/GHSA-v9v4-7jp6-8c73.json
**Updates**
**Comments**
This GHSA advisory (GHSA-v9v4-7jp6-8c73) was split to ruby-advisory-db:
* gems/actionpack/CVE-2011-2197.yml
* gems/activesupport/CVE-2011-2197.yml
This is a change-package-name PR plus clone-advisory for 2nd package-name.- activesupport.
> [GHSA-v9v4-7jp6-8c73] rails Cross-site Scripting vulnerability

- advisories/github-reviewed/2023/06/GHSA-3x74-v64j-qc3f/GHSA-3x74-v64j-qc3f.json
**Updates**
- References
**Comments**
The affected version was way too broad and was including every Craft 3 release, which is incorrect.
> [GHSA-3x74-v64j-qc3f] CraftCMS Server-Side Template Injection vulnerability

- advisories/github-reviewed/2019/04/GHSA-6c3j-c64m-qhgq/GHSA-6c3j-c64m-qhgq.json
**Updates**
**Comments**
Issue 4333 here https://research.insecurelabs.org/jquery/test/ is a test for this. Does not affect versions below 1.1.4. Those packages does not appear to exist for npm or nuget though, but for jQuery itself, this holds, so I think it would make sense to set it at >= 1.1.4, as there is no non-npm js library ecosystem.
The jquery-rails versioning scheme does not follow jQuery versioning, and the initial version uses jQuery 1.4.2, so it makes sense to leave it at < 4.3.4 as that was the version that started using jQuery 3.4.0
> [GHSA-6c3j-c64m-qhgq] XSS in jQuery as used in Drupal, Backdrop CMS, and other products

- advisories/github-reviewed/2022/09/GHSA-3f7h-mf4q-vrm4/GHSA-3f7h-mf4q-vrm4.json
**Updates**
- CVSS
- Severity
**Comments**
Based on https://nvd.nist.gov/vuln/detail/CVE-2022-40152 the Severity should be 7.5 (NVD). Or at least 6.5 (Google).
Low seems to be the wrong Severity for this advisory.
> [GHSA-3f7h-mf4q-vrm4] Denial of Service due to parser crash

- advisories/github-reviewed/2022/12/GHSA-6jvc-q2x7-pchv/GHSA-6jvc-q2x7-pchv.json
**Updates**
**Comments**
According to the OSV spec, the name field should be a Go module path.
>The Go ecosystem; the name field is a Go module path.
https://ossf.github.io/osv-schema/#affectedpackage-field
It should be `github.com/aws/aws-sdk-go` in this case.
> [GHSA-6jvc-q2x7-pchv] AWS S3 Crypto SDK sends an unencrypted hash of the plaintext alongside the ciphertext as a metadata field

- advisories/github-reviewed/2023/07/GHSA-cfgp-2977-2fmm/GHSA-cfgp-2977-2fmm.json
**Updates**
**Comments**
After a thorough analysis, we believe that those 2 ecosystems are not impacted as they don't wrap the vulnerable C++ implementation of gRPC:
* Go, cf https://go-review.googlesource.com/c/vulndb/+/503837/3/data/excluded/GO-2023-1847.yaml#2 and https://github.com/grpc/grpc-go
* npm, grpc-js is a pure javascript implementation according to https://www.npmjs.com/package/@grpc/grpc-js.
The deprecatd grpc package (https://www.npmjs.com/package/grpc) is probably the one that is vulnerable (versions to be defined)
> [GHSA-cfgp-2977-2fmm] Connection confusion in gRPC

- advisories/github-reviewed/2023/06/GHSA-fmrf-p77g-vv5c/GHSA-fmrf-p77g-vv5c.json
**Updates**
**Comments**
This is a vulnerability in the Wikibase extension, not in MediaWiki core.
> [GHSA-fmrf-p77g-vv5c] MediaWiki Cross-site Scripting vulnerability

- advisories/github-reviewed/2023/06/GHSA-w44m-8mv2-v78h/GHSA-w44m-8mv2-v78h.json
**Updates**
**Comments**
Wrong version mentioned here now breaks builds for cosmos-sdk v0.45.x branches which are NOT affected by this vulnerability. Corrected version numbers.
> [GHSA-w44m-8mv2-v78h] Cosmos "Barberry" vulnerability in github.com/cosmos/cosmos-sdk

- advisories/github-reviewed/2018/07/GHSA-hxxf-q3w9-4xgw/GHSA-hxxf-q3w9-4xgw.json
**Updates**
**Comments**
For eslint-scope pathced version must be 3.7.3.
Postmortem (https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes/) says:
2018-07-12 17:41 UTC: The ESLint team published eslint-scope@3.7.3 with the code from eslint-scope@3.7.1 so that caches could pick up the new version.
> [GHSA-hxxf-q3w9-4xgw] Malicious Package in eslint-scope

- advisories/github-reviewed/2023/06/GHSA-g98v-hv3f-hcfr/GHSA-g98v-hv3f-hcfr.json
**Updates**
- Description
**Comments**
Rust v1.70 released the `IsTerminal` trait as stable.
The updated text is copied from the RUSTSEC security advisory.
> [GHSA-g98v-hv3f-hcfr] atty potential unaligned read

- advisories/github-reviewed/2021/08/GHSA-3288-cwgw-ch86/GHSA-3288-cwgw-ch86.json
This attribute should contain the function name without parenthesis (see https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/08/GHSA-vhfr-v4w9-45v8/GHSA-vhfr-v4w9-45v8.json#L24 for example)
> Fix function name in GHSA-3288-cwgw-ch86

- advisories/github-reviewed/2023/06/GHSA-c2qf-rxjj-qqgw/GHSA-c2qf-rxjj-qqgw.json
**Updates**
- References
**Comments**
Update advisory to reflect backported patch
> [GHSA-c2qf-rxjj-qqgw] semver vulnerable to Regular Expression Denial of Service

- advisories/github-reviewed/2023/07/GHSA-58qw-p7qm-5rvh/GHSA-58qw-p7qm-5rvh.json
**Updates**
**Comments**
There are no patched versions of the `jetty-xml` artifacts that fix or address this Advisory.
> [GHSA-58qw-p7qm-5rvh] Eclipse Jetty XmlParser allows arbitrary DOCTYPE declarations

- advisories/github-reviewed/2023/07/GHSA-6628-q6j9-w8vg/GHSA-6628-q6j9-w8vg.json
**Updates**
**Comments**
The fix https://github.com/grpc/grpc/commit/2485fa94bd8a723e5c977d55a3ce10b301b437f8 referenced in the description doesn't touch any code used by the Dart grpc implementation.
> [GHSA-6628-q6j9-w8vg] gRPC Reachable Assertion issue

- advisories/github-reviewed/2023/06/GHSA-257q-pv89-v3xv/GHSA-257q-pv89-v3xv.json
**Updates**
- Description
**Comments**
CVE-2020-23064 is a duplicate of CVE-2020-11023. This is also mentioned on Snyk's page: https://security.snyk.io/vuln/SNYK-JS-JQUERY-565129.
For npm and nuget it should thus have the same lower bound as GHSA-jpcq-cgw6-v4j6. 
For jquery-rails the first version is using 1.4.2, so all versions below 4.4.0 (which uses jQuery 3.5.1) are vulnerable.
The links for these advisories (GHSA-jpcq-cgw6-v4j6 and GHSA-257q-pv89-v3xv) should be merged, and probably also the Affected products listing.
For testing, see https://research.insecurelabs.org/jquery/test/ issue 4647.
> [GHSA-257q-pv89-v3xv] jQuery Cross Site Scripting vulnerability

- advisories/github-reviewed/2023/07/GHSA-7gj7-224w-vpr3/GHSA-7gj7-224w-vpr3.json
**Updates**
**Comments**
Vulnerable and fixed product is Spring Boot Admin, not thymeleaf.
https://github.com/codecentric/spring-boot-admin/commit/f1f6ac6f613e1c0afc121c8989f28b4155a6797a#diff-1ea8b144c29588e08221597d56d8be10b4b4a210f248a83f2e837152a3d2e0d7
> [GHSA-7gj7-224w-vpr3] Thymeleaf allows sandbox bypass via crafted HTML

- advisories/github-reviewed/2022/05/GHSA-rfvw-5848-gxc5/GHSA-rfvw-5848-gxc5.json
**Updates**
**Comments**
The versions listed were incorrect - especially for silverstripe/admin which doesn't even have a version 3 at the moment.
There was a historical precedent for just calling all related core modules by the version number that silverstripe/framework was on. But 1.x on silverstripe/admin is in-step with 4.x of silverstripe/framework.
Note that this is causing issues for anyone running `composer audit`, or any other composer command that triggers an audit, in projects that use `silverstripe/admin`. This needs to be fixed ASAP.
> [GHSA-rfvw-5848-gxc5] Silverstripe Flash Clipboard Reflected XSS

- advisories/github-reviewed/2022/05/GHSA-369m-2gv6-mw28/GHSA-369m-2gv6-mw28.json
**Updates**
- Description
**Comments**
The 1.4.0 gem release contains this commit:
https://github.com/ruby/webrick/commit/4ac0f3843ab82d1c31e1cfc719409208adef7813
This commit references this other commit:
https://github.com/ruby/ruby/commit/6617c41292
whose description says:
> It had failed to sanitize some type of exception messages.  Reported and
patched by Yusuke Endoh (mame) at https://hackerone.com/reports/223363
So this clearly fixes CVE-2017-10784 (you can verify by matching the CVE/name with the hackerone report for example)
The previously provided versions were for the version of **Ruby** itself.
As far as I am aware, the advisory database can not model this constraint.
Currently, I think this causes false dependabot alerts for potentially every Jekyll user.
> [GHSA-369m-2gv6-mw28] WEBrick RCE Vulnerability

- advisories/github-reviewed/2022/10/GHSA-9w4g-fp9h-3q2v/GHSA-9w4g-fp9h-3q2v.json
**Updates**
- References
**Comments**
Looking at the commit https://github.com/apache/flume/commit/eee179a09df405c1ab55ae25a53b76ca1050bb97 that seems to correspond to this, it appears that the affected artifact should be org.apache.flume.flume-ng-sources:flume-jms-source similar to https://github.com/advisories/GHSA-h9mh-mgpv-gqmv
> [GHSA-9w4g-fp9h-3q2v] Apache Flume vulnerable to remote code execution via deserialization of unsafe providerURL

- advisories/github-reviewed/2023/03/GHSA-p8p7-x288-28g6/GHSA-p8p7-x288-28g6.json
**Updates**
- Description
**Comments**
The NVD states that the vulnerability is for versions up to and including 2.88.1 (not 2.88.2), see source here:
https://nvd.nist.gov/vuln/detail/CVE-2023-28155
> [GHSA-p8p7-x288-28g6] Server-Side Request Forgery in Request

- advisories/github-reviewed/2022/05/GHSA-6hvf-xvwm-vrw4/GHSA-6hvf-xvwm-vrw4.json
**Updates**
- References
**Comments**
* Added additional references and source code location
* Removed affected ecosystem information (wrong ecosystem/unsupported)
The CVE concerns the C++ version of the xmltooling library, not the Java library.
Per the advisory (https://shibboleth.net/community/advisories/secadv_20190311.txt), we can trace back the commit and tickets here:
* https://git.shibboleth.net/view/?p=cpp-xmltooling.git;a=commit;h=af27c422f551e16989ff6f1722d83614c8550eb5
* https://shibboleth.atlassian.net/browse/CPPXT-143
Where we can see the actual component is "XMLTooling - C++" - not the Java library. Version 3.0.4 does not exist in the Java library - releases stop at 1.4.6:
* …
> [GHSA-6hvf-xvwm-vrw4] XMLTooling Library Incorrectly Handles Some Exceptions

- advisories/github-reviewed/2022/05/GHSA-65j5-vpm7-6xp4/GHSA-65j5-vpm7-6xp4.json
**Updates**
**Comments**
This version range is not composer-compliant, and is unusable in the composer ecosystem: `< 3.1.33-dev-4` therefore becomes `<3.1.33` (which is the patched version anyway).
Ref: https://github.com/Roave/SecurityAdvisoriesBuilder/actions/runs/5661243781
> Could not parse version constraint < 3.1.33-dev-4: Invalid version string "3.1.33-dev-4"
Ref: https://github.com/Roave/SecurityAdvisoriesBuilder/actions/runs/5661243781/job/15338734912#step:7:20
Note that `3.1.33-dev-4` is not published to packagist anyway: https://packagist.org/packages/smarty/smarty
> [GHSA-65j5-vpm7-6xp4] Smarty Path Traversal Vulnerability

- advisories/github-reviewed/2023/07/GHSA-7gj7-224w-vpr3/GHSA-7gj7-224w-vpr3.json
**Updates**
- References
**Comments**
Modifications performed in Thymeleaf for 3.1.2 securing the scenario of CVE-2023-38286 further, from the standpoint of Thymeleaf.
> [GHSA-7gj7-224w-vpr3] Thymeleaf, as used in Spring Boot Admin, allows sandbox bypass via crafted HTML

- advisories/github-reviewed/2022/05/GHSA-r4h9-gv2m-9x97/GHSA-r4h9-gv2m-9x97.json
**Updates**
**Comments**
The dependency range `< 2.3.1-17-g6f82e6c` is not valid in the packagist ecosystem.
As mentioned in https://github.com/croogo/croogo/issues/847, the security issue is fixed in 4.x.
> [GHSA-r4h9-gv2m-9x97] Croogo XSS

- advisories/github-reviewed/2023/07/GHSA-wj7q-gjg8-3cpm/GHSA-wj7q-gjg8-3cpm.json
**Updates**
- Description
- References
**Comments**
Fixed for php7.x versions, see https://github.com/thephpleague/oauth2-server/pull/1359
> [GHSA-wj7q-gjg8-3cpm] league/oauth2-server key exposed in exception message when passing as a string and providing an invalid pass phrase

- advisories/github-reviewed/2020/06/GHSA-xfv3-rrfm-f2rv/GHSA-xfv3-rrfm-f2rv.json
**Updates**
**Comments**
Adds the affected version ranges for netty 3.x, which was packaged as a single artifact `netty` under the `org.jboss.netty` namespace: https://central.sonatype.com/namespace/org.jboss.netty
> [GHSA-xfv3-rrfm-f2rv] Information Exposure in Netty

- advisories/github-reviewed/2022/05/GHSA-7rx6-4vwv-432g/GHSA-7rx6-4vwv-432g.json
**Updates**
**Comments**
Adjusts affected version ranges to account for Jenkins backported fix per https://github.com/CVEProject/cvelist/blob/1f5ffa2118d4a1c833c50a6d03eda5bd0aac005c/2021/21xxx/CVE-2021-21647.json#L22-L25
> [GHSA-7rx6-4vwv-432g] Missing permission check in CloudBees CD Plugin allows scheduling builds

- advisories/github-reviewed/2020/02/GHSA-p2v9-g2qv-p635/GHSA-p2v9-g2qv-p635.json
> [GHSA-p2v9-g2qv-p635] HTTP Request Smuggling in Netty

- advisories/github-reviewed/2021/02/GHSA-5mcr-gq6c-3hq2/GHSA-5mcr-gq6c-3hq2.json
> [GHSA-5mcr-gq6c-3hq2] Local Information Disclosure Vulnerability in Netty on Unix-Like systems

- advisories/github-reviewed/2021/03/GHSA-wm47-8v5p-wjpj/GHSA-wm47-8v5p-wjpj.json
> [GHSA-wm47-8v5p-wjpj] Possible request smuggling in HTTP/2 due missing validation

- advisories/github-reviewed/2021/03/GHSA-f256-j965-7f32/GHSA-f256-j965-7f32.json
> [GHSA-f256-j965-7f32] Possible request smuggling in HTTP/2 due missing validation of content-length

- advisories/github-reviewed/2021/09/GHSA-grg4-wf29-r9vv/GHSA-grg4-wf29-r9vv.json
> [GHSA-grg4-wf29-r9vv] Bzip2Decoder doesn't allow setting size restrictions for decompressed data

- advisories/github-reviewed/2021/09/GHSA-9vjp-v76f-g363/GHSA-9vjp-v76f-g363.json
> [GHSA-9vjp-v76f-g363]  SnappyFrameDecoder doesn't restrict chunk length any may buffer skippable chunks in an unnecessary way

- advisories/github-reviewed/2021/12/GHSA-wx5j-54mm-rqqq/GHSA-wx5j-54mm-rqqq.json
> [GHSA-wx5j-54mm-rqqq] HTTP request smuggling in io.netty:netty-codec-http

- README.md
PR to add swift as a supported ecosystem and links out to the dns rfc to explain the namespace constraint in place of a file server based registry
Closes #2447
> Add swift to the list of supported ecosystems

- advisories/github-reviewed/2021/01/GHSA-5949-rw7g-wx7w/GHSA-5949-rw7g-wx7w.json
**Updates**
**Comments**
By https://github.com/FasterXML/jackson-databind/issues/2854 a fix was released in 2.6.7.5 (released 22-Jun-2021)
> [GHSA-5949-rw7g-wx7w] Deserialization of untrusted data in jackson-databind

- advisories/github-reviewed/2022/01/GHSA-77rm-9x9h-xj3g/GHSA-77rm-9x9h-xj3g.json
**Updates**
**Comments**
The protobuf-parent Maven package is a placeholder package to pull in all the needed protobuf packages, This meta package doesn't have to be installed, nor does it contain any code.
You can see that if you look at the Maven repo
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.11.1/
vs
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-parent/3.11.1/
The code for this is in the -java package
> [GHSA-77rm-9x9h-xj3g] NULL Pointer Dereference in Protocol Buffers

- advisories/github-reviewed/2023/08/GHSA-36xx-7vf6-7mv3/GHSA-36xx-7vf6-7mv3.json
**Updates**
- CVSS
- Severity
**Comments**
As indicated in the notice, there's no confidentiality, integrity or availability impact on a vanilla install using the built in authenticator. The problem will only be present if a project has implemented a custom authenticator doesn't validate if a password is present.
https://github.com/silverstripe/silverstripe-framework/security/advisories/GHSA-36xx-7vf6-7mv3
> [GHSA-36xx-7vf6-7mv3] Silverstripe Framework: Members with no password can be created and bypass custom login forms

- advisories/github-reviewed/2023/04/GHSA-gq63-p39p-jrjf/GHSA-gq63-p39p-jrjf.json
**Updates**
- Description
- References
- Summary
**Comments**
It seems this CVE was requested from the original user of the original report, submitting vague issues from their own implementation of Yii2. PHP frameworks can still write insecure code if they work around the protections in place by the framework. With failure to replicate the issue on the framework or provide details - the author resulted to requesting and obtaining an CVE for a non-issue.
https://github.com/yiisoft/yii2/issues/19755#issuecomment-1506531748
This was even misleading that the fix version of v2.0.47 was going to resolve this fake issue - as it never existed to begin with.
I looked at patterns in past how this was handled and it seems they are never deleted, so a withdrawn report seems best. …
> [GHSA-gq63-p39p-jrjf] SQL injectionin Yii 2

- advisories/github-reviewed/2023/07/GHSA-p9xf-74xh-mhw5/GHSA-p9xf-74xh-mhw5.json
**Updates**
- fix package name in advisory
**Comments**
`https://` should not be contained in package names.
> [GHSA-p9xf-74xh-mhw5] fix package name in GHSA-p9xf-74xh-mhw5.json

- advisories/github-reviewed/2019/07/GHSA-5wv5-4vpf-pj6m/GHSA-5wv5-4vpf-pj6m.json
**Updates**
**Comments**
Change this version 1.0.0 for 1.0 because, this version 1.0.0 is invalid
Flask: https://pypi.org/project/Flask/1.0/#history
Github Adv Response:
```json
"advisory": {
"ghsaId": "GHSA-5wv5-4vpf-pj6m",
"identifiers": [
{
"type": "GHSA",
"value": "GHSA-5wv5-4vpf-pj6m"
},
{
"type": "CVE",
"value": "CVE-2019-1010083"
}
],
"description": "The Pallets Project Flask before 1.0 is affected by unexpected memory usage. The impact is denial of service. The attack vector is crafted encoded JSON data. The fixed version is 1. NOTE this may overlap CVE-2018-1000656.",
"references": [
{
"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-1010083"
},
{
"url": "https://www.palletsprojects.com/blog/flask-1-0-released/"
},
{
"url": …
```
> [GHSA-5wv5-4vpf-pj6m] Pallets Project Flask is vulnerable to Denial of Service via Unexpected memory usage

- advisories/github-reviewed/2021/06/GHSA-2f88-5hg8-9x2x/GHSA-2f88-5hg8-9x2x.json
**Updates**
**Comments**
The org.apache.maven:maven package isn't a jar, it's metadata to install the maven jars. Since there's no jar for this, it won't be found when inspecting the post-build images. You can see the metadata here
https://repo1.maven.org/maven2/org/apache/maven/maven/3.8.1/
The actual code fixes for this one can be found in maven-core and maven-compat to allow blocking of http
https://issues.apache.org/jira/browse/MNG-7116
https://github.com/apache/maven/commit/fa79cb22e456cc65522b5bab8c4240fe08c5775f
And the mirror blocking patch and config change in maven-core
https://issues.apache.org/jira/browse/MNG-7117
https://github.com/apache/maven/commit/899465aeec03753ea91e15a79579eab76369c016
This update also adds the maven-core and maven-compat packages so …
> [GHSA-2f88-5hg8-9x2x] Origin Validation Error in Apache Maven

- advisories/github-reviewed/2018/10/GHSA-wfcc-pff6-rgc5/GHSA-wfcc-pff6-rgc5.json
**Updates**
**Comments**
Removes the lower bound so that versions prior to 9.2.0 get flagged as vulnerable
> [GHSA-wfcc-pff6-rgc5] Jetty vulnerable to exposure of sensitive information due to observable discrepancy

- advisories/github-reviewed/2023/07/GHSA-cf7p-gm2m-833m/GHSA-cf7p-gm2m-833m.json
**Updates**
**Comments**
SSH certificate parsing was added in 40.0.0 by https://github.com/pyca/cryptography/commit/aca8de845e751dd45fe4e48f8492f357d34d1861
> [GHSA-cf7p-gm2m-833m] cryptography mishandles SSH certificates

- advisories/github-reviewed/2023/08/GHSA-vmch-3w2x-vhgq/GHSA-vmch-3w2x-vhgq.json
**Updates**
**Comments**
The vulnerability description includes the list of vulnerable and patched packages for .NET 6 and ASP.Net Core 2.1, but those are not represented in the Affected Products section which only listed the .NET 7 packages. I simply added the packages already listed in the description to the Affected Products list.
Other vulnerabilities for .NET do correctly list this information for all the affected/supported .NET versions. See for example this vulnerability, it lists both .NET 7 and .NET 6 affected versions: https://github.com/advisories/GHSA-555c-2p6r-68mm
> [GHSA-vmch-3w2x-vhgq] .NET Denial of Service Vulnerability

- advisories/github-reviewed/2023/07/GHSA-xqr8-7jwr-rhp7/GHSA-xqr8-7jwr-rhp7.json
**Updates**
**Comments**
There is no `0` in the fix version. https://pypi.org/project/certifi/#history
This causes grype to detect the updated package as not being fixed since the version string is different. 
/cc https://github.com/anchore/grype/issues/1430
> [GHSA-xqr8-7jwr-rhp7] Removal of e-Tugra root certificate

- advisories/github-reviewed/2018/10/GHSA-4446-656p-f54g/GHSA-4446-656p-f54g.json
**Updates**
**Comments**
Vulnerable component was not added to bcprov-jdk14 until version 1.58 and bcprov-jdk15on until version 1.57. This can be observed by searching for `xmss` in the following source archives:
* https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk14/1.57/bcprov-jdk14-1.57-sources.jar
* https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk14/1.58/bcprov-jdk14-1.58-sources.jar
* https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56-sources.jar
* https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.57/bcprov-jdk15on-1.57-sources.jar
Additionally, bcmail-jdk15 ends at version 1.46 and the affected versions actually live in bcmail-jdk15on.
> [GHSA-4446-656p-f54g] Deserialization of Untrusted Data in Bouncy castle

- advisories/github-reviewed/2021/03/GHSA-5mg8-w23w-74h3/GHSA-5mg8-w23w-74h3.json
**Updates**
- References
**Comments**
Version 30 didn't actually fix this issue, it just marked the function as deprecated (the functionality still existed). This is explained here
https://github.com/google/guava/issues/4011#issuecomment-1573923586
The actual fix is here
https://github.com/google/guava/commit/feb83a1c8fd2e7670b244d5afd23cba5aca43284
which went into version 32
> [GHSA-5mg8-w23w-74h3] Information Disclosure in Guava

- advisories/github-reviewed/2018/10/GHSA-9rgv-h7x4-qw8g/GHSA-9rgv-h7x4-qw8g.json
**Updates**
**Comments**
The upstream bug for this specifies it affects all 9.x versions, but the older versions are deprecated and unfixed
https://bugs.eclipse.org/bugs/show_bug.cgi?id=535670#c0
> [GHSA-9rgv-h7x4-qw8g] Moderate severity vulnerability that affects org.eclipse.jetty:jetty-server

- advisories/github-reviewed/2022/11/GHSA-fhw8-8j55-vwgq/GHSA-fhw8-8j55-vwgq.json
**Updates**
**Comments**
Maven module "sshd-common" was introduced in Apache Mina 2.1.0: https://mina.apache.org/sshd-project/download_2.1.0.html
All versions of Apache Mina are vulnerable - but until version 2.1.0 there was no "sshd-common" module and vulnerable code was in "sshd-core" module:
https://github.com/apache/mina-sshd/commit/10de190e7d3f9189deb76b8d08c72334a1fe2df0#diff-ae34d3a1529f7942e1a47771dd21724c3fef1c7568d3f8455ed9efad96d748ba
So I added "org.apache.sshd:sshd-core" affected package until version 2.1.0.
> [GHSA-fhw8-8j55-vwgq] Unsafe deserialization in Apache MINA SSHD

- advisories/github-reviewed/2018/01/GHSA-8jjf-w7j6-323c/GHSA-8jjf-w7j6-323c.json
**Updates**
- CWEs
**Comments**
Not sure if XML injection is correct here. The attacker adds XML to the token. It's not added by the system. So I would at least propose CWE-347 is added. Btw, I'm also the original finder of this vulnerability (I'm webtonull on hackerone).
> [GHSA-8jjf-w7j6-323c] Samlify vulnerable to Authentication Bypass by allowing tokens to be reused with different usernames

- advisories/github-reviewed/2023/04/GHSA-329j-jfvr-rhr6/GHSA-329j-jfvr-rhr6.json
**Updates**
- Description
- References
**Comments**
https://issues.apache.org/jira/browse/SPARK-41958 indicates it was fixed in 3.3.3/3.4.0, not only 3.4.0
> [GHSA-329j-jfvr-rhr6] Apache Spark vulnerable to Improper Privilege Management

- advisories/github-reviewed/2022/05/GHSA-qw3f-w4pf-jh5f/GHSA-qw3f-w4pf-jh5f.json
**Updates**
**Comments**
Vulnerable component `org.apache.tika.sax.StandardsText` was added to the 1.x branch in version 1.17 https://github.com/apache/tika/commit/e76302196ebcafb7b51fce37fbe8256e6c0fbc51
As an aside, since this CVE tracks backporting the fix for CVE-2022-30126 to the 1.x branch, would it make sense to exclude the 1.x branch from the 2.x CVE's affected versions?
> [GHSA-qw3f-w4pf-jh5f] Regular expression denial of service in apache tika

- advisories/github-reviewed/2022/09/GHSA-2jjq-x548-rhpv/GHSA-2jjq-x548-rhpv.json
**Updates**
**Comments**
as per conversation with target project owner
https://github.com/laverdet/isolated-vm/issues/379
```
laverdet commented last month
Hi the issue was one of documentation. 218e87a is the commit that "fixed" the issue.
```
and commit in question produced was merged in version 4.3.7
https://github.com/laverdet/isolated-vm/commits/v4.3.7
only if cachedData supplied by user this vulnerability coming into picture
it is similar to eval() in base nodejs - when you using it to execute something random coming from user input you will run into security issue
but it doesn't mean nodejs versions providing base eval functionality are all vulnerable
same here - only cachedData produced by isolated-vm methods should be used here by design and maintainer added …
> [GHSA-2jjq-x548-rhpv] isolated-vm has vulnerable CachedDataOptions in API

- advisories/github-reviewed/2023/08/GHSA-6r78-m64m-qwcf/GHSA-6r78-m64m-qwcf.json
**Updates**
**Comments**
4.20.0-rc is also affected.
> [GHSA-6r78-m64m-qwcf] Moq v4.20.0 and 4.20.1 share hashed user data

- advisories/github-reviewed/2022/05/GHSA-r58r-74gx-6wx3/GHSA-r58r-74gx-6wx3.json
**Updates**
**Comments**
The version numbers in the original report are incorrect. They are the version of the underlying libxml2 library, and not the version of the Nokogiri gem. I am the maintainer of Nokogiri. The correct version that a patched version of libxml2 appears in is Nokogiri 1.8.2.
See:
- https://github.com/sparklemotion/nokogiri/issues/1714
- https://github.com/sparklemotion/nokogiri/blob/main/CHANGELOG.md#182--2018-01-29
- https://github.com/rubysec/ruby-advisory-db/blob/master/gems/nokogiri/CVE-2017-15412.yml
> [GHSA-r58r-74gx-6wx3] Nokogiri gem, via libxml, is affected by DoS vulnerabilities

- advisories/github-reviewed/2023/08/GHSA-2474-2566-3qxp/GHSA-2474-2566-3qxp.json
**Updates**
- References
**Comments**
https://github.com/apache/xmlgraphics-batik/commit/64658ccda90deaf6bf5f5b4d4a2ec365fe648bfa is the more relevant mitigation commit. As discussed in https://www.openwall.com/lists/oss-security/2023/08/22/5, including `java.lang.System` in the allowlist by default was a significant part of the issue, and the chosen mitigation was to use a blank allowlist by default.
> [GHSA-2474-2566-3qxp] Apache Batik information disclosure vulnerability

- advisories/github-reviewed/2023/06/GHSA-353f-5xf4-qw67/GHSA-353f-5xf4-qw67.json
**Updates**
- Description
- References
**Comments**
Added Reference Link and Fix Steps
> [GHSA-353f-5xf4-qw67] Vite Server Options (server.fs.deny) can be bypassed using double forward-slash (//)

- advisories/github-reviewed/2023/07/GHSA-hr8g-6v94-x4m9/GHSA-hr8g-6v94-x4m9.json
**Updates**
**Comments**
As described at https://www.bouncycastle.org/latest_releases.html:
"BC 1.71 changed the jdk15on jars to jdk18on so the base has now moved to Java 8. For earlier JVMs, or containers/applications that cannot cope with multi-release jars, you should now use the jdk15to18 jars"
This means that jdk15on artifacts (used until version 1.71) are not accounted for with current affected products definition.
> [GHSA-hr8g-6v94-x4m9] Bouncy Castle For Java LDAP injection vulnerability

- advisories/github-reviewed/2022/01/GHSA-2h63-qp69-fwvw/GHSA-2h63-qp69-fwvw.json
**Updates**
**Comments**
The reference commit and associated ASF JIRA issue https://issues.apache.org/jira/browse/BATIK-1284 indicate that the vulnerable component is `org.apache.batik.apps.svgbrowser.NodePickerPanel`. I've been unable to find references to `org.apache.batik.apps.svgbrowser` in the packages currently listed on this advisory, and searching the Batik repo at the `batik-1_13` didn't find any references to the svgbrowser module outside of `batik-svgbrowser` or commented-out and test code. Based on https://xmlgraphics.apache.org/batik/using/architecture.html#applicationComponents `batik-svgbrowser` appears to be an application module provided as a demo of how to use Batik that could be used by other applications but is not used by the Batik APIs themselves.
> [GHSA-2h63-qp69-fwvw] Server-side request forgery (SSRF) in Apache Batik

- advisories/github-reviewed/2021/09/GHSA-3j6g-hxx5-3q26/GHSA-3j6g-hxx5-3q26.json
**Updates**
**Comments**
According to following sources, Kafka Java Client contained in "kafka-clients" artifact is also affected but Maven coordinates are missing:
https://kafka.apache.org/cve-list ("CVE-2021-38153 Timing Attack Vulnerability for Apache Kafka Connect and Clients")
https://support.confluent.io/hc/en-us/articles/4407632156692-CVE-2021-38153-Confluent-Platform-Vulnerability-Timing-attacks
I also corrected "Affected versions" and "Patched versions" according to sources above.
Another issue is non-existent "org.apache.kafka:kafka" Maven artifact:
https://search.maven.org/search?q=g:org.apache.kafka%20AND%20a:kafka
Kafka server-side artifacts include version of Scala used for build - removal of Scala version suffix is proposed in KIP-897: …
> [GHSA-3j6g-hxx5-3q26] Observable Discrepancy in Apache Kafka

- advisories/github-reviewed/2023/08/GHSA-wfm5-v35h-vwf4/GHSA-wfm5-v35h-vwf4.json
**Updates**
**Comments**
A new version of GitPython, `v3.1.33`, has been released with a fix:
https://github.com/gitpython-developers/GitPython/releases/tag/3.1.33
> [GHSA-wfm5-v35h-vwf4] GitPython untrusted search path on Windows systems leading to arbitrary code execution

- advisories/github-reviewed/2022/11/GHSA-jf2p-4gqj-849g/GHSA-jf2p-4gqj-849g.json
**Updates**
- References
**Comments**
https://github.com/joniles/mpxj/commit/287ad0234213c52b0638565e14bd9cf3ed44cedd is a merge commit and has a lot of noise unrelated to the patch. https://github.com/joniles/mpxj/commit/ae0af24345d79ad45705265d9927fe55e94a5721, one of the parents of the merge, is the true patch commit.
> [GHSA-jf2p-4gqj-849g] Temporary File Information Disclosure vulnerability in MPXJ

- advisories/github-reviewed/2023/08/GHSA-r285-q736-9v95/GHSA-r285-q736-9v95.json
**Updates**
**Comments**
Origin GitHub issue has been marked as resolved by package author.
Reference patch commit: 0d17b270a3c33d3bed56cadd9a43da7717ab11f4
> [GHSA-r285-q736-9v95] Filename spoofing in archive

- advisories/github-reviewed/2023/09/GHSA-5q66-v53q-pm35/GHSA-5q66-v53q-pm35.json
**Updates**
**Comments**
Only 22.0.2 is affected
> [GHSA-5q66-v53q-pm35] Keycloak vulnerable to Plaintext Storage of User Password

- advisories/github-reviewed/2023/09/GHSA-3gh6-v5v9-6v9j/GHSA-3gh6-v5v9-6v9j.json
**Updates**
- Summary
**Comments**
The title incorrectly says "CgiServlet".
There's no such class in Jetty, it's just called "CGI" and it happens to extend from HttpServlet.
See: https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/CGI.java
> [GHSA-3gh6-v5v9-6v9j] Jetty vulnerable to errant command quoting in CgiServlet

- advisories/github-reviewed/2023/09/GHSA-3q5p-3558-364f/GHSA-3q5p-3558-364f.json
**Updates**
**Comments**
A release has finally been published with the vulnerability patched. Dependabot should probably also publish this.
https://github.com/gofiber/fiber/releases/tag/v2.49.2
> [GHSA-3q5p-3558-364f] Fiber unauthorized access vulnerability in `ctx.IsFromLocal()`

- advisories/github-reviewed/2023/01/GHSA-23c2-gwp5-pxw9/GHSA-23c2-gwp5-pxw9.json
**Updates**
- References
**Comments**
Adding the patch link for this advisory associated to version 1.0.1: https://github.com/rails/globalid/compare/v1.0.0...v1.0.1 
The CVE is in the commit message:
" Fix ReDoS vulnerability in name parsing
Thanks to ooooooo_q for the patch!
[CVE-2023-22799]"
> [GHSA-23c2-gwp5-pxw9] ReDoS based DoS vulnerability in GlobalID

- advisories/github-reviewed/2021/08/GHSA-2vx6-fcw6-hpr6/GHSA-2vx6-fcw6-hpr6.json
**Updates**
- References
**Comments**
Adding the patch link for v0.12.4: https://github.com/PyO3/pyo3/commit/1ee3961a0de6a74a4c5160c97a88696a2164025b
Only two commits exist for v0.12.4: https://github.com/PyO3/pyo3/compare/v0.12.3...v0.12.4
Additionally, the patch link is the same as the original pull 1297 in the advisory: "py: fix reference count bug in From(Py<T>) for PyObject "
> [GHSA-2vx6-fcw6-hpr6] Reference counting error in pyo3

- advisories/github-reviewed/2022/05/GHSA-376m-3rm2-9jm6/GHSA-376m-3rm2-9jm6.json
**Updates**
- References
**Comments**
v1.0.3: https://github.com/ipsilon-project/ipsilon/commit/64fc366c054fc6af1d9d2692902db169884b5f78
v1.1.2: https://github.com/ipsilon-project/ipsilon/commit/1c48414877fc110652b6078a29529972c7ec9122
v1.2.1: https://github.com/ipsilon-project/ipsilon/commit/b4744a92d4fa7f6d7ade0ae2d99a2dc0ea94734d
v2.0.2: https://github.com/ipsilon-project/ipsilon/commit/a33303b6beb5c316d7c18b23566b7666a4e307a4
The CVE is in the commit message: 
"This resolves an issue where Ipsilon can be requested to initiate logout sessions for all currently open sessions, regardless of currently logged in user.
Fixes: CVE-2016-8638"
It's best to have a patch link for each fixed version due to minor changes from the backports.
> [GHSA-376m-3rm2-9jm6] Session Fixation in ipsilon

- advisories/github-reviewed/2022/05/GHSA-43w2-9j62-hq99/GHSA-43w2-9j62-hq99.json
**Updates**
- References
**Comments**
v0.6.14: https://github.com/servo/rust-smallvec/commit/5757ac500d4e544485d796b542e4e589749c291b
v1.6.1: https://github.com/servo/rust-smallvec/commit/9998ba0694a6b51aa6604748b00b6a98f0a0039e
The commit message mentions fixing the original issue (252): 
"Fix potential buffer overflow in insert_many. Fixes 252."
> [GHSA-43w2-9j62-hq99] Buffer overflow in SmallVec::insert_many

- advisories/github-reviewed/2018/09/GHSA-c9j3-wqph-5xx9/GHSA-c9j3-wqph-5xx9.json
**Updates**
- References
**Comments**
v2.8.1: https://github.com/eggjs/egg-scripts/commit/b98fd03d1e3aaed68004b881f0b3d42fe47341dd
The commit message mentions fixing the original issue (26): 
"fix: use execFile instead of exec for security reason (26)"
> [GHSA-c9j3-wqph-5xx9] Command Injection in egg-scripts

- advisories/github-reviewed/2022/10/GHSA-h423-w6qv-2wj3/GHSA-h423-w6qv-2wj3.json
**Updates**
- References
**Comments**
v4.10.17: https://github.com/parse-community/parse-server/commit/3d7a61ecd5231638f01ff1a965b6313043c594a7
v5.2.8: https://github.com/parse-community/parse-server/commit/066f29673ab4030b6b5b90c0c0326f7d3fe7612a
The commit message mentions fixing the GHSA-ID (GHSA-h423-w6qv-2wj3): 
"fix: server crashes when receiving file download request with invalid byte range; this fixes a security vulnerability that allows an attacker to impact the availability of the server instance; the fix improves parsing of the range parameter to properly handle invalid range requests GHSA-h423-w6qv-2wj3 (8235)"
> [GHSA-h423-w6qv-2wj3] parse-server crashes when receiving file download request with invalid byte range

- advisories/github-reviewed/2021/08/GHSA-h45v-vgvp-3h5v/GHSA-h45v-vgvp-3h5v.json
**Updates**
- References
**Comments**
v0.3.1: https://github.com/arcnmx/stack-rs/commit/369e55736f9bd29c37b1712afc2923f4028148c6
The commit message mentions fixing the original issue (4) from the security advisory: 
"Add bounds check to Vector::insert. Fixes 4"
> [GHSA-h45v-vgvp-3h5v] Out-of-bounds write in stack

- advisories/github-reviewed/2019/02/GHSA-2mhh-w6q8-5hxw/GHSA-2mhh-w6q8-5hxw.json
**Updates**
- References
**Comments**
v1.0.1: https://github.com/websockets/ws/commit/29293ed11b679e0366fa0f6bb9310b330dafd795
Found from the original reference link (https://gist.github.com/c0nrad/e92005446c480707a74a): 
"Even though the advisory is wrong, the fix is still correct. https://github.com/websockets/ws/commit/29293ed11b679e0366fa0f6bb9310b330dafd795"
Commit message: "[fix] Prevent allocation of memory through ping frames"
> [GHSA-2mhh-w6q8-5hxw] Remote Memory Disclosure in ws

- advisories/github-reviewed/2022/12/GHSA-xxfx-w2rw-gh63/GHSA-xxfx-w2rw-gh63.json
**Updates**
- References
**Comments**
v0.8.2: https://github.com/csaf-poc/csaf_distribution/commit/17f22855ee8d4270dd17ff748c30ed7304846fdc
The fix is highly related to the advisory description to ignore non-conforming files. Additionally, this was the only commit for version 0.8.2: https://github.com/csaf-poc/csaf_distribution/compare/v0.8.1...v0.8.2 
Commit message: "Add filename conformity check
* Add util function to check a filename for confirming to csaf-v2.0-csd02.
* Add code to reject bad filenames in provider, checker, aggregator and uploader."
> [GHSA-xxfx-w2rw-gh63] csaf-poc/csaf_distribution Cross-site Scripting vulnerability

- advisories/github-reviewed/2022/02/GHSA-95rw-fx8r-36v6/GHSA-95rw-fx8r-36v6.json
**Updates**
- References
**Comments**
v2.2.27: https://github.com/django/django/commit/c27a7eb9f40b64990398978152e62b6ff839c2e6
v3.2.12: https://github.com/django/django/commit/1a1e8278c46418bde24c86a65443b0674bae65e2
v4.0.2: https://github.com/django/django/commit/01422046065d2b51f8f613409cad2c81b39487e5
Adding the fix for each patch version. The CVE is in the commit message: "Fixed CVE-2022-22818 -- Fixed possible XSS via {% debug %} template tag."
> [GHSA-95rw-fx8r-36v6] Cross-site Scripting in Django

- advisories/github-reviewed/2023/09/GHSA-m4mm-pg93-fv78/GHSA-m4mm-pg93-fv78.json
**Updates**
**Comments**
From what I've seen, this issue already had backport bug fixes in pull request [#1457](https://github.com/undertow-io/undertow/pull/1457) and was released in version 2.2.24.Final. However, this vulnerability CVE-2023-1108 is still listed as unresolved in versions < 2.3.5.Final, as reported four days ago.
> [GHSA-m4mm-pg93-fv78] Undertow denial of service vulnerability

- advisories/github-reviewed/2022/02/GHSA-82hx-w2r5-c2wq/GHSA-82hx-w2r5-c2wq.json
**Updates**
**Comments**
Go versions of k8s.io artifacts start with 0, see for example https://pkg.go.dev/k8s.io/apiserver?tab=versions. The version corresponding to Kubernetes 1.17.3 is 0.17.3.
> [GHSA-82hx-w2r5-c2wq] Kubernetes API Server DoS Via API Requests

- advisories/github-reviewed/2023/09/GHSA-j7hp-h8jx-5ppr/GHSA-j7hp-h8jx-5ppr.json
**Updates**
- Description
**Comments**
Update based on prior discussion in https://github.com/github/advisory-database/pull/2727:
- Add SkiaSharp now that a patched version is available
- Add github.com/chai2010/webp with no patched version available since the package is unmaintained
- Fix the main source code location to point to libwebp, not its Rust binding
cc @darakian
> [GHSA-j7hp-h8jx-5ppr] libwebp: OOB write in BuildHuffmanTable

- advisories/github-reviewed/2020/05/GHSA-8727-m6gj-mc37/GHSA-8727-m6gj-mc37.json
**Updates**
- Description
**Comments**
Affected versions are clearly mentioned. But in the description it says not affected version rails < v4.0.0 and affected version rails < v6.0.3. Which implies, that affected versions are between 4.0.0 and 6.0.3 (>= 4.0.0, < 6.0.3) which is not the case.
The `each_pair` method returned `super` until v4.2.11.3. Which means whatever logic was written did not matter because it did not modify the class state but rather returned the instance of super class.
But later in v5.0.0.beta1 `each_pair` implementation returned the params itself. This caused the users to get the return values from the function which should not happen. Later it was fixed by returning an instance of its class.
This issue is mitigated either by bumping rails version …
> [GHSA-8727-m6gj-mc37] Possible Strong Parameters Bypass in ActionPack

- advisories/github-reviewed/2020/06/GHSA-2m34-jcjv-45xf/GHSA-2m34-jcjv-45xf.json
**Updates**
- References
**Comments**
v2.2.13: https://github.com/django/django/commit/6d61860b22875f358fac83d903dc629897934815
v3.0.7: https://github.com/django/django/commit/1f2dd37f6fcefdd10ed44cb233b2e62b520afb38
Adding the fix for each patch version. The CVE is in the commit message: "Fixed CVE-2020-13596 -- Fixed potential XSS in admin ForeignKeyRawIdWidget."
> [GHSA-2m34-jcjv-45xf] XSS in Django

- advisories/github-reviewed/2021/06/GHSA-rxjp-mfm9-w4wr/GHSA-rxjp-mfm9-w4wr.json
**Updates**
- References
**Comments**
v2.2.21: https://github.com/django/django/commit/04ac1624bdc2fa737188401757cf95ced122d26d
v3.1.9: https://github.com/django/django/commit/25d84d64122c15050a0ee739e859f22ddab5ac48
v3.2.1: https://github.com/django/django/commit/c98f446c188596d4ba6de71d1b77b4a6c5c2a007
"Fixed CVE-2021-31542 -- Tightened path & file name sanitation in file uploads."
> [GHSA-rxjp-mfm9-w4wr] Path Traversal in Django

- advisories/github-reviewed/2019/01/GHSA-r28v-mw67-m5p9/GHSA-r28v-mw67-m5p9.json
**Updates**
- References
**Comments**
v1.8.19: https://github.com/django/django/commit/1ca63a66ef3163149ad822701273e8a1844192c2
v1.11.11: https://github.com/django/django/commit/abf89d729f210c692a50e0ad3f75fb6bec6fae16
v2.0.3: https://github.com/django/django/commit/e157315da3ae7005fa0683ffc9751dbeca7306c8
"Fixed CVE-2018-7536 -- Fixed catastrophic backtracking in urlize and urlizetrunc template filters."
> [GHSA-r28v-mw67-m5p9] Django Denial-of-service possibility in urlize and urlizetrunc template filters

- advisories/github-reviewed/2018/08/GHSA-4q53-fqhc-cr46/GHSA-4q53-fqhc-cr46.json
**Updates**
- References
**Comments**
v1.2.2: https://github.com/emberjs/ember.js/commit/ab3199e68e1d0fc3c8f7f453cd38c51fe02af90b
v1.3.2: https://github.com/emberjs/ember.js/commit/94b28b8773acf894c4d7d7fccf4411a706292436
v1.4.0-beta.6: https://github.com/emberjs/ember.js/commit/45ee8df2a0efc0afe233d6b9b17045782a2e6b2d
The commit message mentions fixing the CVE:
"[SECURITY CVE-2014-0046] Ensure link-to non-block escapes title."
> [GHSA-4q53-fqhc-cr46] ember-source Cross-site Scripting vulnerability

- advisories/github-reviewed/2022/12/GHSA-65hj-9ppw-77xc/GHSA-65hj-9ppw-77xc.json
**Updates**
- References
**Comments**
v1.9: https://github.com/ff4j/ff4j/commit/62d03140f3bfbd380d0f4b4e5a94dcb8baa9d9c6
This commit is the complete merge of pull 625, which resolved the original issue 624 mentioned in the advisory. Additionally, the CVE is mentioned in the commit message: "fix: CVE-2022-44262 (624)"
> [GHSA-65hj-9ppw-77xc] ff4j is vulnerable to Remote Code Execution (RCE)

- advisories/github-reviewed/2022/02/GHSA-6cw3-g6wv-c2xv/GHSA-6cw3-g6wv-c2xv.json
**Updates**
- References
**Comments**
v2.2.27: https://github.com/django/django/commit/c477b761804984c932704554ad35f78a2e230c6a
v3.2.12: https://github.com/django/django/commit/d16133568ef9c9b42cb7a08bdf9ff3feec2e5468
v4.0.2: https://github.com/django/django/commit/f9c7d48fdd6f198a6494a9202f90242f176e4fc9
The CVE is mentioned in the commit message: "Fixed CVE-2022-23833 -- Fixed DoS possibility in file uploads."
> [GHSA-6cw3-g6wv-c2xv] Infinite Loop in Django

- advisories/github-reviewed/2017/10/GHSA-jmm9-2p29-vh2w/GHSA-jmm9-2p29-vh2w.json
**Updates**
- References
**Comments**
v3.0.4: https://github.com/rails/rails/commit/354da43ab0a10b3b7b3f9cb0619aa562c3be8474
"limit() should sanitize limit values. This fixes CVE-2011-0448"
> [GHSA-jmm9-2p29-vh2w] activerecord vulnerable to SQL Injection

- advisories/github-reviewed/2022/06/GHSA-pg8v-g4xq-hww9/GHSA-pg8v-g4xq-hww9.json
**Updates**
- References
**Comments**
v1.4.3: https://github.com/rails/rails-html-sanitizer/commit/45a5c10fed3d9aa141594c80afa06d748fa0967d
"fix: modify safelist option if it contains both select and style. Addresses CVE-2022-32209"
> [GHSA-pg8v-g4xq-hww9] Rails::Html::Sanitizer vulnerable to Cross-site Scripting

- advisories/github-reviewed/2022/05/GHSA-xx36-6rv4-gj8r/GHSA-xx36-6rv4-gj8r.json
**Updates**
**Comments**
It appears that the actual package name from the hex registry is [starkbank_ecdsa](https://hex.pm/packages/starkbank_ecdsa).  I'm unsure if it makes sense to keep the originally identified `ecdsa-elixir` name around.  I couldn't find anything corresponding to that name in any package registries though.
> [GHSA-xx36-6rv4-gj8r] ecdsa-elixir fails to check signatures, vulnerable to message forging

- advisories/github-reviewed/2023/09/GHSA-9jfq-54vc-9rr2/GHSA-9jfq-54vc-9rr2.json
**Updates**
**Comments**
This is incorrectly marking the foreman rubygem 0.87.2 (which has nothing to do with theforeman.org or the vulnerability listed here)
> [GHSA-9jfq-54vc-9rr2] Foreman Transpilation Enables OS Command Injection

- advisories/github-reviewed/2021/06/GHSA-7r7m-5h27-29hp/GHSA-7r7m-5h27-29hp.json
**Updates**
- References
**Comments**
v8.2.0: https://github.com/python-pillow/Pillow/commit/bb6c11fb889e6c11b0ee122b828132ee763b5856
"Fix FLI DOS -- CVE-2021-28676
* FliDecode did not properly check that the block advance was
non-zero, potentally leading to an infinite loop on load.
* This dates to the PIL Fork
* Found with oss-fuzz"
> [GHSA-7r7m-5h27-29hp] Potential infinite loop in Pillow

- advisories/github-reviewed/2021/06/GHSA-p99v-5w3c-jqq9/GHSA-p99v-5w3c-jqq9.json
**Updates**
- References
**Comments**
v2.2.24: https://github.com/django/django/commit/f27c38ab5d90f68c9dd60cabef248a570c0be8fc
v3.1.12: https://github.com/django/django/commit/203d4ab9ebcd72fc4d6eb7398e66ed9e474e118e
v3.2.4: https://github.com/django/django/commit/9f75e2e562fa0c0482f3dde6fc7399a9070b4a3d
"Fixed CVE-2021-33571 -- Prevented leading zeros in IPv4 addresses.
validate_ipv4_address() was affected only on Python < 3.9.5, see [1].
URLValidator() uses a regular expressions and it was affected on all
Python versions."
> [GHSA-p99v-5w3c-jqq9] Django Access Control Bypass possibly leading to SSRF, RFI, and LFI attacks 

- advisories/github-reviewed/2023/09/GHSA-x7m3-jprg-wc5g/GHSA-x7m3-jprg-wc5g.json
**Updates**
**Comments**
Version suggestion is incorrect, see http://www.gevent.org/changelog.html - vulnerability was fixed in 23.9.0, not 23.9.1
> [GHSA-x7m3-jprg-wc5g] Gevent allows remote attacker to escalate privileges

- advisories/github-reviewed/2020/09/GHSA-4f9m-pxwh-68hg/GHSA-4f9m-pxwh-68hg.json
**Updates**
- References
**Comments**
v3.20.9: https://github.com/swagger-api/swagger-ui/commit/1e184e8e218676278c83e60a45846c199ce3d15e
This patch is the complete merge of the pull 5190 mentioned in the original advisory to v3.20.9: 
" fix: sanitize URLs used for OAuth auth flow (via 5190)
* fix: sanitize URLs used for OAuth auth flow
* embetter test case
* fix linter issue"
> [GHSA-4f9m-pxwh-68hg] Cross-Site Scripting in swagger-ui

- advisories/github-reviewed/2022/03/GHSA-4p8f-2fwv-6xcw/GHSA-4p8f-2fwv-6xcw.json
**Updates**
- References
**Comments**
v1.5.0: https://github.com/jenkinsci/rocketchatnotifier-plugin/commit/1a0023be9f2e143434d028d5292ef9dc3195d051
This patch performs the exact updates described in the description by starting to check permission within the RocketChatNotifier: Jenkins.get().checkPermission(Jenkins.ADMINISTER);. 
Additionally, the commit message is relatively intuitive to be related to the fix: "feat(Security): Improve credential handling"
> [GHSA-4p8f-2fwv-6xcw] Missing permission check in Jenkins RocketChat Notifier Plugin

- advisories/github-reviewed/2019/09/GHSA-5m2v-hc64-56h6/GHSA-5m2v-hc64-56h6.json
**Updates**
- References
**Comments**
v1.3.0: https://github.com/rubyzip/rubyzip/commit/d65fe7bd283ec94f9d6dc7605f61a6b0dd00f55e
This is the complete merge of the original pull 403 from the advisory: "Validate entry sizes when extracting." This adds `validate_entry_sizes` option so that callers can trust an entry's reported size when using `extract.`
> [GHSA-5m2v-hc64-56h6] Rubyzip denial of service 

- advisories/github-reviewed/2019/04/GHSA-2777-2vq8-c4v4/GHSA-2777-2vq8-c4v4.json
**Updates**
- References
**Comments**
v5.3.0: https://github.com/sequelize/sequelize/commit/850c7fd04669e0fef9238b6dc4f8d6ee93ed71e9
This is the complete merge of pull 10746 mentioned in the original advisory: "feat(postgres): enable standard conforming strings when required (10746)"
> [GHSA-2777-2vq8-c4v4] SQL Injection in sequelize

- advisories/github-reviewed/2020/09/GHSA-2ggq-vfcp-gwhj/GHSA-2ggq-vfcp-gwhj.json
**Updates**
- References
**Comments**
v0.3.8: https://github.com/hapijs/boom/commit/0f8640bdba65aec6e6799bfc16ff5753150bfcaf
The patch link was mentioned in the external reference of Snyk: https://snyk.io/vuln/SNYK-JS-HAPIBOOM-541183. Additionally, the commit message is related: "Adding extra XSS protection"
> [GHSA-2ggq-vfcp-gwhj] Cross-Site Scripting in @hapi/boom

- advisories/github-reviewed/2020/07/GHSA-33c7-2mpw-hg34/GHSA-33c7-2mpw-hg34.json
**Updates**
- References
**Comments**
v0.11.7: https://github.com/encode/uvicorn/commit/895807f94ea9a8e588605c12076b7d7517cda503
Also, adding the original issue (Mentions CVE-2020-7694): https://github.com/encode/uvicorn/issues/723
The patch link was used in pull (724) to close the original issue (723): "Quote path component before logging (724)"
> [GHSA-33c7-2mpw-hg34] Log injection in uvicorn

- advisories/github-reviewed/2022/05/GHSA-34wj-p5jm-2p96/GHSA-34wj-p5jm-2p96.json
**Updates**
- References
**Comments**
v0.8.6: https://github.com/python-openxml/python-docx/commit/61b40b161b64173ab8e362aec1fd197948431beb
From the commit message: "Resolving entities in the XML is not required by the Open XML standard and represents a security vulnerability. Turn off entity resolution in both the opc (package) parser and the part parser."
The developer also set "resolve_entities=False", which means that the parser will not resolve any entity references (like &amp; or &lt;) to their corresponding characters (like & or <).
> [GHSA-34wj-p5jm-2p96] Improper Restriction of XML External Entity Reference in python-docx

- advisories/github-reviewed/2022/10/GHSA-35rx-7pc8-6963/GHSA-35rx-7pc8-6963.json
**Updates**
- References
**Comments**
v1.0.33: https://github.com/jenkinsci/katalon-plugin/commit/64f819387f3f14d54f3a1542578a5c7aa9feb85c
Adding the PR: https://github.com/jenkinsci/katalon-plugin/pull/28
The PR mentions the same reference in the advisory: "Resolve issue from https://issues.jenkins.io/browse/SECURITY-2846"
The commit is from the PR: "Stop storing credentials in plain text"
> [GHSA-35rx-7pc8-6963] API keys stored in plain text by Jenkins Katalon Plugin

- advisories/github-reviewed/2017/12/GHSA-3f5c-4qxj-vmpf/GHSA-3f5c-4qxj-vmpf.json
**Updates**
- References
**Comments**
v2.4.1: https://github.com/vercel/next.js/commit/02fe7cf63f6265d73bdaf8bc50a4f2fb539dcd00
The patch adds a new function, isServableURL, which is used to determine whether a given path is within the allowed directories to be served and prevents the serving of files outside those directories. Additionally, the branch merge was named "fix-dir-traversal-error," which is what the advisory is for.  
Also, github.com/zeit/next.js redirects to github.com/vercel/next.js ...which is why the patch is under vercel/next.js.
> [GHSA-3f5c-4qxj-vmpf] Next.js Directory Traversal Vulnerability
