advisories/github-reviewed/2022/11/GHSA-3fgr-xjr6-xqm8/GHSA-3fgr-xjr6-xqm8.json
**Updates**
- References
**Comments**
v4.9.0: https://github.com/gggeek/phpxmlrpc/commit/cf6e605e09d001ce520bfa8e7b168cfa514e663b
The commit message mentions the original issue (80): "fix security issues 80 and 81; comments; whitespace; docs; tag for release"
=> [GHSA-3fgr-xjr6-xqm8] code injection in phpxmlrpc/phpxmlrpc

advisories/github-reviewed/2021/05/GHSA-3fr8-mwpp-8h9p/GHSA-3fr8-mwpp-8h9p.json
**Updates**
- References
**Comments**
v3.1.0: https://github.com/maptiler/tileserver-gl/commit/10431d70d0f0d7b7950ae2c02aea0850c7566621
The commit message mentions the original issue (461): "Fix reflected XSS in 'key' parameter. Fixes 461"
=> [GHSA-3fr8-mwpp-8h9p] Cross-site scripting in TileServer GL

advisories/github-reviewed/2021/08/GHSA-4cww-f7w5-x525/GHSA-4cww-f7w5-x525.json
**Updates**
- References
**Comments**
v0.18.1: https://github.com/bluejekyll/trust-dns/commit/8b9eab05795fdc098976262853b2498055c7a8f3
This commit was mentioned in the original issue (980) as closing the issue: "reproduce error stack overflow from . as MX target stop additional lookup on Root name"
=> [GHSA-4cww-f7w5-x525] Stack consumption in trust-dns-server

advisories/github-reviewed/2022/12/GHSA-4jv9-3563-23j3/GHSA-4jv9-3563-23j3.json
**Updates**
- References
**Comments**
v2.4.0: https://github.com/knex/knex/commit/e145322da92749be7749f9ade5b5f5a66d6586a4
This commit was mentioned in the original issue (1227) as closing the issue: "1227: add assertion for basic where clause values (5417)"
=> [GHSA-4jv9-3563-23j3] Knex.js has a limited SQL injection vulnerability

advisories/github-reviewed/2020/09/GHSA-4xf9-pgvv-xx67/GHSA-4xf9-pgvv-xx67.json
**Updates**
- References
**Comments**
v0.5.2: https://github.com/ariabuckles/simple-markdown/commit/89797fef9abb4cab2fb76a335968266a92588816
This commit was mentioned in the original issue (71) as the fix: "inlineCode: Fix ReDoS & improve escape semantics". 
Also, the repo owner changed from Khan to ariabuckles, which is why the patch link differs.
=> [GHSA-4xf9-pgvv-xx67] Regular Expression Denial of Service in simple-markdown

advisories/github-reviewed/2022/01/GHSA-55m5-whcv-c49c/GHSA-55m5-whcv-c49c.json
**Updates**
- References
**Comments**
v0.6.13: https://github.com/servo/rust-smallvec/commit/e64afc8c473d43e375ab42bd33db2d0d4ac4e41b
This commit was used to backport the fix to 0.6.13, it was mentioned in the original issue (126) as part of the fix from pull (162): " Use MaybeUninit for storage of inline items. This is a backport of 162 to the smallvec 0.6 branch."
=> [GHSA-55m5-whcv-c49c] Use of Uninitialized Resource in smallvec

advisories/github-reviewed/2022/04/GHSA-5x4f-7xgq-r42x/GHSA-5x4f-7xgq-r42x.json
**Updates**
- References
**Comments**
v7.5.28: https://github.com/ezsystems/ezpublish-kernel/commit/133c33cbcaa330953d6283865153f3dfdc7a2e45
The commit message mentions the GHSA-ID: " Merge pull request from GHSA-5x4f-7xgq-r42x
* IBX-2786: Fixed evaluating Root Location in ObjectStateLimitationType
* IBX-2786: [Tests] Added test coverage for Non-Root Location"
=> [GHSA-5x4f-7xgq-r42x] Object state limitation has no effect

advisories/github-reviewed/2022/05/GHSA-96mh-7xpr-qcgw/GHSA-96mh-7xpr-qcgw.json
**Updates**
- CVSS
- Description
- Severity
- Summary
**Comments**
Wrong package. Not a vulnerability since user is trusted. Behavior is controlled by a permission (`backend.allow_unsafe_markdown`).
=> [GHSA-96mh-7xpr-qcgw] October CMS XSS

advisories/github-reviewed/2023/09/GHSA-2g8p-j2r6-vqpj/GHSA-2g8p-j2r6-vqpj.json
**Updates**
- Description
- Severity
**Comments**
This vulnerability is related to the October CMS installer (not October CMS the platform). These files are deleted when the installer finishes its process. This also was not responsibly disclosed to the October CMS team.
=> [GHSA-2g8p-j2r6-vqpj] October Cross-site Scripting vulnerability

advisories/github-reviewed/2023/09/GHSA-3qc2-v3hp-6cv8/GHSA-3qc2-v3hp-6cv8.json
**Updates**
**Comments**
The sidekiq gem version 6.5.10 that was released a few days ago fixes this issue, see https://github.com/sidekiq/sidekiq/blob/6-x/Changes.md#6510
This is also reflected in https://github.com/rubysec/ruby-advisory-db/blob/master/gems/sidekiq/CVE-2023-26141.yml.
So I think the version 6.5.10 should be added as a "patched version".
=> [GHSA-3qc2-v3hp-6cv8] sidekiq Denial of Service vulnerability

advisories/github-reviewed/2020/09/GHSA-8whr-v3gm-w8h9/GHSA-8whr-v3gm-w8h9.json
**Updates**
- References
**Comments**
v5.0.0: https://github.com/mithunsatheesh/node-rules/commit/100862223904bb6478fcc33b701c7dee11f7b832
In the original issue (84), a developer mentioned the fix as: "We should get rid of fromJSON and toJSON APIs in V5.0 release."
The patch link does that: "Remove fromJSON and toJSON from exposed APIs"
Snyk also has the same referenced patch link.
=> [GHSA-8whr-v3gm-w8h9] Command Injection in node-rules

advisories/github-reviewed/2023/08/GHSA-65rp-cv85-263x/GHSA-65rp-cv85-263x.json
**Updates**
- CVSS
- Severity
**Comments**
Please see https://github.com/golang/vulndb/issues/2016#issuecomment-1698677762. The vendor does not consider this a valid vulnerability (CVE-2022-34038 has been marked as DISPUTED). As such, this should be invalidated.
=> [GHSA-65rp-cv85-263x] etcd denial of service vulnerability

advisories/github-reviewed/2020/09/GHSA-qvjc-g5vr-mfgr/GHSA-qvjc-g5vr-mfgr.json
**Updates**
- References
**Comments**
v5.2.0: https://github.com/mholt/PapaParse/commit/235a12758cd77266d2e98fd715f53536b34ad621
The commit message mentions the original issue (777): "Avoid ReDOS on float dynamic typing (779) Fixes 777"
=> [GHSA-qvjc-g5vr-mfgr] Regular Expression Denial of Service in papaparse

advisories/github-reviewed/2022/02/GHSA-qfhg-m6r8-xxpj/GHSA-qfhg-m6r8-xxpj.json
**Updates**
- References
**Comments**
v9.2.6: https://github.com/drupal/core/commit/8e8e3d2ddd72471ba886346ecabfb5d98fd27d9b
The commit message mentions the same Drupal issue (SA-CORE-2021-009) linked in the original advisory: "SA-CORE-2021-009"
=> [GHSA-qfhg-m6r8-xxpj] Incorrect Authorization in Drupal core

advisories/github-reviewed/2020/05/GHSA-qfcv-5whw-7pcw/GHSA-qfcv-5whw-7pcw.json
**Updates**
- References
**Comments**
v21.10.1: https://github.com/ipfs/aegir/commit/e36e1def57b2dc1e4b7a5beba964c5924e87f8d8
The commit no longer passes all environment variables to the bundled code, which could have leaked keys: "fix: whitelist process env keys (557)
PSA: previous versions included process.env in the bundles so tokens, keys etc might be compromised please reset those to be safe!!"
=> [GHSA-qfcv-5whw-7pcw] Exposure of Sensitive Information to an Unauthorized Actor in AEgir

advisories/github-reviewed/2017/10/GHSA-pchc-949f-53m5/GHSA-pchc-949f-53m5.json
**Updates**
- References
**Comments**
v0.5.2: https://github.com/sferik/multi_xml/commit/c94b136d06822514fc2e99dc851e6c4eeb4c8bdf
This is the squashed merge of the original pull (34): "remove-ability-to-parse-symbols-and-yaml
Remove ability to parse symbols and yaml"
=> [GHSA-pchc-949f-53m5] Improper Input Validation in multi_xml

advisories/github-reviewed/2018/10/GHSA-p28m-34f6-967q/GHSA-p28m-34f6-967q.json
**Updates**
- References
**Comments**
v17.5.0: https://github.com/pyca/pyopenssl/commit/e73818600065821d588af475b024f4eb518c3509
This is the squashed merge from pull 723: "fix a memory leak and a potential UAF and also 722 (723)"
=> [GHSA-p28m-34f6-967q] PyOpenSSL Use-After-Free vulnerability

advisories/github-reviewed/2022/10/GHSA-mwwc-3jv2-62j3/GHSA-mwwc-3jv2-62j3.json
**Updates**
- References
**Comments**
v0.108.0-b.16: https://github.com/AdguardTeam/AdGuardHome/commit/756b14a61de138889130c239406dae43f1f115cb
This is the only commit to fix a cross-site request forgery for v0.108.0-b.16 (https://github.com/AdguardTeam/AdGuardHome/compare/v0.108.0-b.15...v0.108.0-b.16): "Pull request: HOFTIX-csrf."
=> [GHSA-mwwc-3jv2-62j3] AdGuardHome vulnerable to Cross-Site Request Forgery

advisories/github-reviewed/2021/08/GHSA-mp6f-p9gp-vpj9/GHSA-mp6f-p9gp-vpj9.json
**Updates**
- References
**Comments**
Adding the patch links for:
v0.6.3: https://github.com/bodil/sized-chunks/commit/99e593c3037438db478256a1f3101371a69cbd3f
&
https://github.com/bodil/sized-chunks/commit/3ae48bd463c1af41c24b96b84079946f51f51e3c
The original issue (11) required two PRs to fix the advisory. The first is PR 13: "Fix soundness issues in sized chunks and ringbuffer. This fixes (hopefully) part of 11, + something I've seen on the way."
The second is PR 14: "Fix alignment issues of InlineArray. This is case 4 of 11."
=> [GHSA-mp6f-p9gp-vpj9] Array size is not checked in sized-chunks

advisories/github-reviewed/2022/02/GHSA-mmjr-5q74-p3m4/GHSA-mmjr-5q74-p3m4.json
**Updates**
- References
**Comments**
v9.0.6: https://github.com/drupal/core/commit/f93a37b713b59f8d24e826bc74378099853eef3d
The commit message mentions the same Drupal issue (SA-Core-2020-011):  "SA-CORE-2020-011"
=> [GHSA-mmjr-5q74-p3m4] Exposure of Resource to Wrong Sphere in Drupal Core

advisories/github-reviewed/2023/08/GHSA-cwvm-v4w8-q58c/GHSA-cwvm-v4w8-q58c.json
**Updates**
**Comments**
The fix in GitPython 3.1.35 was incomplete, as discussed in https://github.com/gitpython-developers/GitPython/pull/1672. A new release, https://github.com/gitpython-developers/GitPython/releases/tag/3.1.37, includes a proper fix. The maintainer has updated the advisory associated with the repository, https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c, to indicate that the fully patched version is 3.1.37 instead of any earlier version.
This change proposes the corresponding change in the GitHub Advisory Database, which would make both advisories convey the same, up-to-date information. The maintainer of GitPython, @Byron, has requested that this be done …
=> [GHSA-cwvm-v4w8-q58c] Blind local file inclusion

advisories/github-reviewed/2020/09/GHSA-mrx7-8hxf-f853/GHSA-mrx7-8hxf-f853.json
**Updates**
- References
**Comments**
Adding the patch links for:
v2.2.1: https://github.com/swagger-api/swagger-ui/commit/331d2be070d89162aa3174a8773ae4a0093f78bc
This is from the PR (1869) that closed the original issue (1863): "Escape curl command to fix XSS vulnerability."
=> [GHSA-mrx7-8hxf-f853] Cross-Site Scripting in swagger-ui

advisories/github-reviewed/2023/08/GHSA-7gfq-f96f-g85j/GHSA-7gfq-f96f-g85j.json
**Updates**
- Description
- References
**Comments**
https://github.com/langchain-ai/langchain/pull/10252
https://github.com/langchain-ai/langchain/releases/tag/v0.0.312
=> [GHSA-7gfq-f96f-g85j] langchain vulnerable to arbitrary code execution

advisories/github-reviewed/2022/05/GHSA-xwf4-88xr-hx2j/GHSA-xwf4-88xr-hx2j.json
**Updates**
**Comments**
Several other components are also affected as a result of cloning (copying source code) or shading (copying source code and renaming packages). Proof-of-Vulnerability projects with tests to verify the presence of the CVE can be found here: https://github.com/jensdietrich/xshady-release/.
See https://github.com/github/advisory-database/pull/2258, especially https://github.com/github/advisory-database/pull/2258#issuecomment-1569073245, for more details.
=> Improve GHSA-xwf4-88xr-hx2j

advisories/github-reviewed/2022/05/GHSA-7g54-vgp6-jj5w/GHSA-7g54-vgp6-jj5w.json
**Updates**
**Comments**
Several other components are also affected as a result of cloning (copying source code) or shading (copying source code and renaming packages). Proof-of-Vulnerability projects with tests to verify the presence of the CVE can be found here: https://github.com/jensdietrich/xshady-release/.
See https://github.com/github/advisory-database/pull/2258, especially https://github.com/github/advisory-database/pull/2258#issuecomment-1569073245, for more details.
=> Improve GHSA-7g54-vgp6-jj5w

advisories/github-reviewed/2022/05/GHSA-gchv-364h-r896/GHSA-gchv-364h-r896.json
**Updates**
- Description
**Comments**
Link: https://jena.apache.org/about_jena/security-advisories.html#cve-2022-28890---processing-external-dtds
It says here under CVE-2022-28890 - Processing External DTDs that only version 4.4.0 is affected. We had a false positive with version 3.1.1.
Thanks!
=> [GHSA-gchv-364h-r896] XML External Entity Reference in apache jena

advisories/github-reviewed/2021/12/GHSA-fp5r-v3w9-4333/GHSA-fp5r-v3w9-4333.json
**Updates**
**Comments**
This is similar to https://github.com/github/advisory-database/pull/2844 that was already merged.
org.zenframework.z8.dependencies.commons:log4j-1.2.17 (https://mvnrepository.com/artifact/org.zenframework.z8.dependencies.commons/log4j-1.2.17) is a "forked" version of log4j-1.2.17. Their digest are the same:
- log4j-1.2.17-2.0.jar.sha1: 5af35056b4d257e4b64b9e8069c0746e8b08629f (https://repo1.maven.org/maven2/org/zenframework/z8/dependencies/commons/log4j-1.2.17/2.0/log4j-1.2.17-2.0.jar.sha1)
- log4j-1.2.17.jar.sha1: 5af35056b4d257e4b64b9e8069c0746e8b08629f (https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar.sha1)
This suggests that these two packages are identical, and therefore this vulnerability would apply to this package as …
=> [GHSA-fp5r-v3w9-4333] JMSAppender in Log4j 1.2 is vulnerable to deserialization of untrusted data

advisories/github-reviewed/2023/10/GHSA-wgh7-54f2-x98r/GHSA-wgh7-54f2-x98r.json
**Updates**
- Summary
**Comments**
Fixing title to include references to HTTP/3 and QPACK too.
Also removing `jetty-http` from impacted packages list, as those are where the fixes went, but have no release where those packages are vulnerable.
=> [GHSA-wgh7-54f2-x98r] HTTP/2 HPACK integer overflow and buffer allocation

advisories/github-reviewed/2021/05/GHSA-75qf-wgfj-v652/GHSA-75qf-wgfj-v652.json
**Updates**
**Comments**
Versions seem off and should be 0.7.0
This vuln was fixed in 0.9.0
https://github.com/u-root/u-root/issues/2449
=> [GHSA-75qf-wgfj-v652] github.com/u-root/u-root/pkg/tarutil Arbitrary File Write via Archive Extraction (Zip Slip)

advisories/github-reviewed/2020/07/GHSA-p6mc-m468-83gw/GHSA-p6mc-m468-83gw.json
**Updates**
- Description
- References
**Comments**
The root cause of this vulnerability is internal function `baseSet`, which is used by multiple public functions in addition to `zipObjectDeep`. This pull request adds those additional vulnerable functions to the description, as they may not be obvious to analysts determining if their codebase is affected. For example, https://hackerone.com/reports/864701 is essentially a duplicate of the HackerOne report that [created this CVE](https://hackerone.com/reports/712065) due to the shared root cause. However, it was awarded a bounty (and received a separate [Snyk entry](https://security.snyk.io/vuln/SNYK-JS-LODASH-608086)) because it is not obvious from the older HackerOne disclosure or CVE description that `set` and …
=> [GHSA-p6mc-m468-83gw] Prototype Pollution in lodash

advisories/github-reviewed/2023/07/GHSA-m88m-crr9-jvqq/GHSA-m88m-crr9-jvqq.json
**Updates**
- References
**Comments**
Added reference to blog post, which details the vulnerability.
=> [GHSA-m88m-crr9-jvqq] OpenRefine vulnerable to zip slip in project import

advisories/github-reviewed/2023/07/GHSA-vjh7-5r6x-xh6g/GHSA-vjh7-5r6x-xh6g.json
**Updates**
- References
**Comments**
Update references with a public technical advisory.
=> [GHSA-vjh7-5r6x-xh6g] CasaOS Gateway vulnerable to incorrect identification of source IP addresses

advisories/github-reviewed/2023/07/GHSA-m5q5-8mfw-p2hr/GHSA-m5q5-8mfw-p2hr.json
**Updates**
- References
**Comments**
Updates references with a public technical advisory.
=> [GHSA-m5q5-8mfw-p2hr] CasaOS contains weak JWT secrets

advisories/github-reviewed/2021/12/GHSA-fj7f-vq84-fh43/GHSA-fj7f-vq84-fh43.json
**Updates**
- References
**Comments**
A blog post was released with details about the vulnerability: https://www.sonarsource.com/blog/securing-developer-tools-package-managers/
**Please also sync this change to the CVE entry.**
=> [GHSA-fj7f-vq84-fh43] Local Code Execution through Argument Injection via dash leading git url parameter in Gemfile.

advisories/github-reviewed/2021/10/GHSA-frqg-7g38-6gcf/GHSA-frqg-7g38-6gcf.json
**Updates**
- References
**Comments**
A blog post was released with details about the vulnerability: https://www.sonarsource.com/blog/securing-developer-tools-package-managers/
**Please also sync this change to the CVE entry.**
=> [GHSA-frqg-7g38-6gcf] Improper escaping of command arguments on Windows leading to command injection

advisories/github-reviewed/2022/05/GHSA-rv63-gqm8-9w8q/GHSA-rv63-gqm8-9w8q.json
**Updates**
**Comments**
Wrong fixed version (missing Final release) and wrong artifact (the vulnerability is only on netty-handler artifact, as can be inferred from path of the affected files)
=> [GHSA-rv63-gqm8-9w8q] Loop with Unreachable Exit Condition in Netty

advisories/github-reviewed/2019/03/GHSA-h436-432x-8fvx/GHSA-h436-432x-8fvx.json
**Updates**
**Comments**
Several other components are also affected as a result of cloning (copying source code) or shading (copying source code and renaming packages). Proof-of-Vulnerability projects with tests to verify the presence of the CVE can be found here: https://github.com/jensdietrich/xshady-release/.
See https://github.com/github/advisory-database/pull/2258, especially https://github.com/github/advisory-database/pull/2258#issuecomment-1569073245, for more details.
=> Improve GHSA-h436-432x-8fvx

advisories/github-reviewed/2022/01/GHSA-w9p3-5cr8-m3jj/GHSA-w9p3-5cr8-m3jj.json
**Updates**
**Comments**
This is similar to https://github.com/github/advisory-database/pull/2844 that was already merged.
org.zenframework.z8.dependencies.commons:log4j-1.2.17 (https://mvnrepository.com/artifact/org.zenframework.z8.dependencies.commons/log4j-1.2.17) is a "forked" version of log4j-1.2.17. Their digest are the same:
- log4j-1.2.17-2.0.jar.sha1: 5af35056b4d257e4b64b9e8069c0746e8b08629f (https://repo1.maven.org/maven2/org/zenframework/z8/dependencies/commons/log4j-1.2.17/2.0/log4j-1.2.17-2.0.jar.sha1)
- log4j-1.2.17.jar.sha1: 5af35056b4d257e4b64b9e8069c0746e8b08629f (https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar.sha1)
This suggests that these two packages are identical, and therefore this vulnerability would apply to this package as …
=> [GHSA-w9p3-5cr8-m3jj] Deserialization of Untrusted Data in Log4j 1.x

advisories/github-reviewed/2022/01/GHSA-65fg-84f6-3jq3/GHSA-65fg-84f6-3jq3.json
**Updates**
**Comments**
This is similar to https://github.com/github/advisory-database/pull/2844 that was already merged.
org.zenframework.z8.dependencies.commons:log4j-1.2.17 (https://mvnrepository.com/artifact/org.zenframework.z8.dependencies.commons/log4j-1.2.17) is a "forked" version of log4j-1.2.17. Their digest are the same:
- log4j-1.2.17-2.0.jar.sha1: 5af35056b4d257e4b64b9e8069c0746e8b08629f (https://repo1.maven.org/maven2/org/zenframework/z8/dependencies/commons/log4j-1.2.17/2.0/log4j-1.2.17-2.0.jar.sha1)
- log4j-1.2.17.jar.sha1: 5af35056b4d257e4b64b9e8069c0746e8b08629f (https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar.sha1)
This suggests that these two packages are identical, and therefore this vulnerability would apply to this package as …
=> [GHSA-65fg-84f6-3jq3] SQL Injection in Log4j 1.2.x

advisories/github-reviewed/2023/10/GHSA-qppj-fm5r-hxr3/GHSA-qppj-fm5r-hxr3.json
**Updates**
**Comments**
Grpc-go is also affected: https://github.com/grpc/grpc-go/pull/6703.
Release notes at https://github.com/grpc/grpc-go/releases for a reference to the patched versions.
=> [GHSA-qppj-fm5r-hxr3] swift-nio-http2 vulnerable to HTTP/2 Stream Cancellation Attack

advisories/github-reviewed/2023/10/GHSA-57m8-f3v5-hm5m/GHSA-57m8-f3v5-hm5m.json
**Updates**
**Comments**
This security advisory should be removed all together as it's a "false-positive". Netty's `SslHandler` can be used with any protocol and so the user is responsible to configure it the right way. This is the same as when the user just use `SSLEngine` which is part of the JDK.
=> [GHSA-57m8-f3v5-hm5m] Netty-handler does not validate host names by default

advisories/github-reviewed/2022/06/GHSA-jq66-xh47-j9f3/GHSA-jq66-xh47-j9f3.json
**Updates**
- References
**Comments**
This doesn't seem related to the streebog package.
CC: https://github.com/rustsec/advisory-db/pull/1815
=> [GHSA-jq66-xh47-j9f3] Type confusion if __private_get_type_id__ is overriden

advisories/github-reviewed/2022/05/GHSA-mxq6-vrrr-ppmg/GHSA-mxq6-vrrr-ppmg.json
**Updates**
**Comments**
Please review the referenced commit with tag 1.2.2 addressing the command injection flaw in tree-kill by implementing pid sanitization. Although a formal GitHub release has not been created post-commit, it directly targets the vulnerability described in CVE-2019-15599, which involves a code injection vulnerability on Windows.
Reference:
https://github.com/pkrumins/node-tree-kill/commit/deee138a8cbc918463d8af5ce8c2bec33c3fd164
https://github.com/pkrumins/node-tree-kill/releases/tag/v1.2.2
=> [GHSA-mxq6-vrrr-ppmg] tree-kill vulnerable to remote code execution

advisories/github-reviewed/2023/10/GHSA-pffg-92cg-xf5c/GHSA-pffg-92cg-xf5c.json
**Updates**
fix package name in advisory
**Comments**
https:// should not be contained in package names.
=> fix package name in GHSA-pffg-92cg-xf5c.json

advisories/github-reviewed/2023/03/GHSA-cpmr-mw4j-99r7/GHSA-cpmr-mw4j-99r7.json
**Updates**
* Fixed version
**Comments** 
We are issuing an update to the previously published GHSA-cpmr-mw4j-99r7. In our initial advisory, the specific version in which the vulnerability was addressed was not mentioned. This was an oversight due to our unfamiliarity with the public advisory process, as it was our first time issuing such an announcement.
The vulnerability was originally resolved in version `1.7.2`. This fix was implemented in `heartexlabs/label-studio` and can be traced to [commit](https://github.com/HumanSignal/label-studio/commit/60a3ef57a22c50d7230a56c11d85e14454c99a28). The patch was derived from a private advisory fork before being merged into the main project.
I apologize for any inconvenience and are taking steps to ensure that future advisories are more …
=> [GHSA-cpmr-mw4j-99r7] Nginx alias path traversal allows unauthenticated attackers to read all files on /label_studio/core/

advisories/github-reviewed/2023/10/GHSA-hrfv-mqp8-q5rw/GHSA-hrfv-mqp8-q5rw.json
**Updates**
- CVSS
- Severity
**Comments**
* Fix was backported to version 2.3.8.
* Confidentiality and Integrity of data are not affected, and were incorrectly inflating the severity. The severity now matches what was reported in the original security advisory.
=> [GHSA-hrfv-mqp8-q5rw] Werkzeug DoS: High resource usage when parsing multipart/form-data containing a large part with CR/LF character at the beginning

advisories/github-reviewed/2022/01/GHSA-r3rr-wph6-9638/GHSA-r3rr-wph6-9638.json
**Updates**
- References
**Comments**
Add patch commit links for v1.23: https://github.com/jenkinsci/publish-over-ssh-plugin/commit/70b7689bf6fc894f4dc6c0ff34dd72808840760e
https://github.com/jenkinsci/publish-over-ssh-plugin/commit/2b4b9b2dfab5c001669f9a74c0e6078b0a27b928
The commit messages have explicitly shown their aim for fixing this CVE: "[SECURITY-2291] Unprotected Storage of Credentials".
=> [GHSA-r3rr-wph6-9638] Password stored in plain text by Jenkins Publish Over SSH Plugin

advisories/github-reviewed/2023/01/GHSA-q84x-3476-8ff2/GHSA-q84x-3476-8ff2.json
**Updates**
- References
**Comments**
The issue in question also affects the -storage component.
If you look at the patch
https://github.com/apache/james-mime4j/commit/021eb79ba312fe5a7f99fa867ee5350aa5533069
The patch is in the storage componet. The storage component is included in the apache-mime4j, keeping them both in affected makes sense
=> [GHSA-q84x-3476-8ff2] Apache James MIME4J vulnerable to information disclosure to local users

advisories/github-reviewed/2023/02/GHSA-j75r-vf64-6rrh/GHSA-j75r-vf64-6rrh.json
**Updates**
**Comments**
I'm not sure the resteasy-reactive-common-parent package belongs in the list, but I'm pretty sure resteasy-reactive-common should be.
If we look at the patch
https://github.com/quarkusio/quarkus/pull/30694/files
We see this file path
independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/FileBodyHandler.java
We find the pom for this project is here
https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/common/runtime/pom.xml
In that pom we see
```
<parent>
<groupId>io.quarkus.resteasy.reactive</groupId>
<artifactId>resteasy-reactive-common-parent</artifactId>
<version>999-SNAPSHOT</version>
</parent>
```
Which matches the current package name …
=> [GHSA-j75r-vf64-6rrh] RestEasy Reactive implementation of Quarkus allows Creation of Temporary File With Insecure Permissions

advisories/github-reviewed/2023/11/GHSA-5wvp-7f3h-6wmm/GHSA-5wvp-7f3h-6wmm.json
**Updates**
**Comments**
thee description says vulnerablity is from version >= 0.14.0 but the  vulnerable version starts from 0.4.0 which doesnt match advisory.
=> [GHSA-5wvp-7f3h-6wmm] PyArrow: Arbitrary code execution when loading a malicious data file

advisories/github-reviewed/2023/11/GHSA-hm9r-7f84-25c9/GHSA-hm9r-7f84-25c9.json
**Updates**
- References
**Comments**
added fix commit .
=> [GHSA-hm9r-7f84-25c9] Apache Airflow allows authenticated and DAG-view authorized users to modify some DAG run detail values when submitting notes

advisories/github-reviewed/2022/08/GHSA-7qq9-9g2w-56f9/GHSA-7qq9-9g2w-56f9.json
**Updates**
- References
**Comments**
Add the patch commit link for v2.4.0: https://github.com/xuxueli/xxl-job/commit/730c1066b80e8ab44503ed34ced19ef8e0471fec
The commit message has claimed it:""CVE-2022-36157"授权漏洞修复。"
=> [GHSA-7qq9-9g2w-56f9] Improper Privilege Management in com.xuxueli:xxl-job

advisories/github-reviewed/2022/11/GHSA-83w4-x5w9-hf4h/GHSA-83w4-x5w9-hf4h.json
**Updates**
- References
**Comments**
Add the patch commit for v2.4.0: https://github.com/xuxueli/xxl-job/commit/9293c61ca0a8d54afdfb27cc568885ae639a14dc
The commit message has explicitly claimed it: `"CVE-2022-43183" SSRF漏洞修复。`
=> [GHSA-83w4-x5w9-hf4h] XXL-JOB vulnerable to Server-Side Request Forgery (SSRF)

advisories/github-reviewed/2023/09/GHSA-rwhx-6hx7-pqc8/GHSA-rwhx-6hx7-pqc8.json
**Updates**
- References
**Comments**
Add the patch commit links for v3.6.0:  https://github.com/jeecgboot/jeecg-boot/commit/44952c79c244a998e3904e44cea47baab0ee681b, 
https://github.com/jeecgboot/jeecg-boot/commit/56e81fbf7bce11d2762b691f5d965b2265be608e
https://github.com/jeecgboot/jeecg-boot/commit/87677df925e55e51233bf740433b30a751fc7705.
And
https://github.com/jeecgboot/jeecg-boot/commit/473875a9d261780a3400cf6f8260ca441b768ed1 aims to deeply fix the bug induced by the bug fix for this CVE: "深度解决SQL注入漏洞问题(修复导致的bug修复)".
These commit messages have claimed their purpose: "解决严重SQL漏洞", which means solving the SQL injection in Chinese.
=> [GHSA-rwhx-6hx7-pqc8] SQL injection in jeecgboot

advisories/github-reviewed/2023/11/GHSA-4qq5-mxxx-m6gg/GHSA-4qq5-mxxx-m6gg.json
**Updates**
- References
**Comments**
Add the patch links at: https://github.com/mlflow/mlflow/pull/9700/commits/9b3032a98c8f6a34ea515cde87f0d9d21bc5ccd3, and https://github.com/mlflow/mlflow/pull/9700/commits/52dd2b375ec75fbb0facc10b3a1ab25e693743c0.
The fix PR containing these two patches is: https://github.com/mlflow/mlflow/pull/9700. They all mentioned that they changed the vulnable lines to "only admin create users".
The issue can prove it is at: https://github.com/mlflow/mlflow/issues/9669, which also matches the info in the original bug report: https://huntr.com/bounties/3e64df69-ddc2-463e-9809-d07c24dc1de4.
=> [GHSA-4qq5-mxxx-m6gg] MLflow authentication requirement bypass can allow a user to arbitrarily create an account

advisories/github-reviewed/2023/10/GHSA-p4jj-gwpg-9jwh/GHSA-p4jj-gwpg-9jwh.json
**Updates**
- References
**Comments**
Add patch commit for v9.2.2: https://github.com/concretecms/concretecms/commit/4990e68e8a4be2ee66e2d2bfcbfca38712614f76,
which has been mentioned in v9.2.2 release note https://github.com/concretecms/concretecms/releases: "Fixed CVE-2023-44761 Admin can add XSS via Data Objects with this commit"
=> [GHSA-p4jj-gwpg-9jwh] ConcreteCMS Cross-site Scripting vulnerability

advisories/github-reviewed/2023/04/GHSA-vcpr-hm2m-gjjj/GHSA-vcpr-hm2m-gjjj.json
**Updates**
- References
**Comments**
https://github.com/concretecms/concretecms/commit/861ba66d248165c9ee9d6d11a0457908b97d68f0
which has been mentioned in the release note https://github.com/concretecms/concretecms/releases/tag/8.5.13: "Fixed CVE-2023-28475 Concrete was vulnerable to reflected XSS".
=> [GHSA-vcpr-hm2m-gjjj] Reflected cross site scripting

advisories/github-reviewed/2023/04/GHSA-474f-mcjv-pgrm/GHSA-474f-mcjv-pgrm.json
**Updates**
- References
**Comments**
https://github.com/concretecms/concretecms/pull/11749
which has been mentioned in the release note https://github.com/concretecms/concretecms/releases/tag/8.5.13: "Fixed CVE-2023-28819 in version 8.5".
=> [GHSA-474f-mcjv-pgrm] Stored cross site scripting

advisories/github-reviewed/2023/04/GHSA-f55r-8rcv-mqcf/GHSA-f55r-8rcv-mqcf.json
**Updates**
- CWEs
- References
**Comments**
https://github.com/concretecms/concretecms/pull/11749
which has been mentioned in the release note https://github.com/concretecms/concretecms/releases/tag/8.5.13: "Fixed CVE-2023-28472 in version 8.5 by updating the Survey Block Controller.".
=> [GHSA-f55r-8rcv-mqcf] Missing secure cookie parameters

advisories/github-reviewed/2023/04/GHSA-pj76-75cm-3552/GHSA-pj76-75cm-3552.json
**Updates**
- References
**Comments**
https://github.com/concretecms/concretecms/pull/11749,
which has been mentioned in the release note https://github.com/concretecms/concretecms/releases/tag/8.5.13: "Fixed CVE-2023-28473 possible Auth bypass in the jobs section in version 8.5.“
=> [GHSA-pj76-75cm-3552] Authenication bypass

advisories/github-reviewed/2023/10/GHSA-6xx7-r8x4-fpjp/GHSA-6xx7-r8x4-fpjp.json
**Updates**
- References
**Comments**
Add patch commit for v9.2.2: 
https://github.com/concretecms/concretecms/pull/11746/commits/92bcc208078571f4beda38cb0952f8e99887737a
and 
https://github.com/concretecms/concretecms/pull/11746/commits/0f0564232e0a49719d0bdff6223539b624f116ee
The commits belong to this PR: https://github.com/concretecms/concretecms/pull/11746, which has been mentioned in v9.2.2 release note https://github.com/concretecms/concretecms/releases: "Fixed CVE-2023-44765 Stored XSS Associations (via data objects) with commit 11746"
=> [GHSA-6xx7-r8x4-fpjp] ConcreteCMS Cross-site Scripting vulnerability

advisories/github-reviewed/2023/11/GHSA-v8fc-qxvj-f3mg/GHSA-v8fc-qxvj-f3mg.json
**Updates**
- References
**Comments**
Add patch commit for v3.1.1: https://github.com/nasa/openmct/pull/7148/commits/4e95e12559c9c5364269ff366a59768573baacb4
which belongs to this PR: https://github.com/nasa/openmct/pull/7148
And they were mentioned in the release notes for v3.1.1: https://github.com/nasa/openmct/releases/tag/v3.1.1: "cherry-pick(#7144): fix(#7143): add eslint-plugin-no-unsanitized and fix errors by @ozyx in #7148
Fixes CVE-2023-45884, CVE-2023-45885" .
=> [GHSA-v8fc-qxvj-f3mg] NASA Open MCT Cross Site Scripting vulnerability

advisories/github-reviewed/2023/11/GHSA-4g88-4hgm-m99x/GHSA-4g88-4hgm-m99x.json
**Updates**
- References
**Comments**
Add patch commit for v3.1.1: https://github.com/nasa/openmct/pull/7148/commits/4e95e12559c9c5364269ff366a59768573baacb4
which belongs to this PR: https://github.com/nasa/openmct/pull/7148
And they were mentioned in the release notes for v3.1.1: https://github.com/nasa/openmct/releases/tag/v3.1.1: "cherry-pick(#7144): fix(#7143): add eslint-plugin-no-unsanitized and fix errors by @ozyx in #7148
Fixes CVE-2023-45884, CVE-2023-45885" .
=> [GHSA-4g88-4hgm-m99x] NASA Open MCT Cross Site Request Forgery (CSRF) vulnerability

advisories/github-reviewed/2023/04/GHSA-xfmj-r86m-j2hr/GHSA-xfmj-r86m-j2hr.json
**Updates**
- References
**Comments**
https://github.com/concretecms/concretecms/commit/546cef6ec29208d5c079113635cd6e6b250e9f7c, 
which has been mentioned in the release note https://github.com/concretecms/concretecms/releases/tag/8.5.13: "Fixed CVE-2023-28477 stored XSS on API Integrations via the name parameter in the 8.5 version".
=> [GHSA-xfmj-r86m-j2hr] Stored cross site scripting on API integration

advisories/github-reviewed/2023/11/GHSA-w496-f5qq-m58j/GHSA-w496-f5qq-m58j.json
**Updates**
- References
**Comments**
Add patch commit for v9.0.1: https://github.com/mattermost/mattermost/commit/77f094c7ee8c7a00be01c2df72f948a62c690b66,
the pointed pr is: https://github.com/mattermost/mattermost/pull/24429
The message within the commit and pr mentioned this fix:
`MM-54219 - Fix: Improve limits on redirectLocationDataCache`.
=> [GHSA-w496-f5qq-m58j] Mattermost vulnerable to excessive memory consumption

advisories/github-reviewed/2019/11/GHSA-vvwv-h69m-wg6f/GHSA-vvwv-h69m-wg6f.json
**Updates**
- References
**Comments**
add patch commit for v1.8.0: https://github.com/PHPOffice/PhpSpreadsheet/commit/0e6238c69e863b58aeece61e48ea032696c6dccd,
belonging to pr: https://github.com/PHPOffice/PhpSpreadsheet/pull/1041.
The commit message has claimed to fix this cve, and was also mentioned in the release note on version 1.8.0: "Security Fix (CVE-2019-12331)"
=> [GHSA-vvwv-h69m-wg6f] XXE in PHPSpreadsheet due to incomplete fix for previous encoding issue

advisories/github-reviewed/2023/04/GHSA-mx2q-35m2-x2rh/GHSA-mx2q-35m2-x2rh.json
**Updates**
- References
**Comments**
Add anther patch commit, which is for @openzeppelin/contracts-upgradeable v4.8.3: https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/commit/58fa0f81c4036f1a3b616fdffad2fd27e5d5ce21.
The code change is same with the exising patch for @openzeppelin/contracts.
=> [GHSA-mx2q-35m2-x2rh] OpenZeppelin Contracts TransparentUpgradeableProxy clashing selector calls may not be delegated

advisories/github-reviewed/2023/11/GHSA-r67m-mf7v-qp7j/GHSA-r67m-mf7v-qp7j.json
**Updates**
- References
**Comments**
Add the patch commit for v9.0.1:https://github.com/mattermost/mattermost/commit/698f4a97da564e2c1f2bf1fbd01755cefa3b7881, 
pointing to these two prs: https://github.com/mattermost/mattermost/pull/24362 and https://github.com/mattermost/mattermost/pull/24566,
which mentioned the purpose: "Sanitize user in update user response (#24362) (#24566)".
=> [GHSA-r67m-mf7v-qp7j] Mattermost password hash disclosure vulnerability

advisories/github-reviewed/2023/06/GHSA-5h3x-9wvq-w4m2/GHSA-5h3x-9wvq-w4m2.json
**Updates**
- References
**Comments**
Add patch commit for **openzeppelin-contracts-upgradeable** v4.9.1:https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/commit/66f390fa516b550838e2c2f65132b5bc2afe1ced,
which is the fix for openzeppelin-contracts-upgradeable, the code changes are same with the existng patch (https://github.com/OpenZeppelin/openzeppelin-contracts/commit/d9474327a492f9f310f31bc53f38dbea56ed9a57) for openzeppelin-contracts.
=> [GHSA-5h3x-9wvq-w4m2] OpenZeppelin Contracts's governor proposal creation may be blocked by frontrunning

advisories/github-reviewed/2023/05/GHSA-97cp-mr4m-9mcf/GHSA-97cp-mr4m-9mcf.json
**Updates**
- References
**Comments**
Add patch commit for 0.216.1: https://github.com/n8n-io/n8n/pull/5526/commits/1414bfa7906ea089b9dc55853405e774a5384ce2
The corresponding pr is https://github.com/n8n-io/n8n/pull/5526
their msg mentioned that "fix(core): User update endpoint should only allow updating email, firstName, and lastName #5526", also mentioned in the release note for this version.
=> [GHSA-97cp-mr4m-9mcf] n8n Privilege Escalation vulnerability

advisories/github-reviewed/2023/05/GHSA-p58x-7733-vp9m/GHSA-p58x-7733-vp9m.json
**Updates**
- References
**Comments**
Add patch commit for v0.216.1: https://github.com/n8n-io/n8n/commit/40b97846483fe7c58229c156acb66f43a5a79dc3 and https://github.com/n8n-io/n8n/commit/fb07d77106bb4933758c63bbfb87f591bf4a27dd.
The prs are https://github.com/n8n-io/n8n/pull/5523 and https://github.com/n8n-io/n8n/pull/5522.
As release note for v0.216.1 https://github.com/n8n-io/n8n/releases/tag/n8n%400.216.1 mentioned: "core: Do not allow arbitrary path traversal in BinaryDataManager (#5523) (40b9784)
core: Do not allow arbitrary path traversal in the credential-translation endpoint (#5522) (fb07d77)".
=> [GHSA-p58x-7733-vp9m] n8n Directory Traversal vulnerability

advisories/github-reviewed/2023/05/GHSA-r9xw-p7wj-w792/GHSA-r9xw-p7wj-w792.json
**Updates**
- Description
- References
**Comments**
Add the patch commit at: https://github.com/n8n-io/n8n/commit/27adea70459329fc0dddabee69e10c9d1453835f
the pr is: https://github.com/n8n-io/n8n/pull/5525.
the release note mentioned it: "core: Do not explicitly bypass auth on urls containing .svg (#5525) (27adea7)", is consistent with the content in the exising reference: https://www.synacktiv.com/sites/default/files/2023-05/Synacktiv-N8N-Multiple-Vulnerabilities_0.pdf--"An authentication bypass, which can be associated to one of the
previous path traversals to create a pre-authenticated file read." Meanwhile, the desc was also updated according to this existing refrence.
=> [GHSA-r9xw-p7wj-w792] n8n Information Disclosure vulnerability

advisories/github-reviewed/2019/11/GHSA-xcrg-29h7-h4cj/GHSA-xcrg-29h7-h4cj.json
**Updates**
- References
**Comments**
patched verison is 1.5.1, was mentioned in the existing reference link: https://github.com/PHPOffice/PhpSpreadsheet/issues/771.
Also mentioned in the release note at v1.5.1: https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.5.1.
Add the patch commit at https://github.com/PHPOffice/PhpSpreadsheet/commit/0f8f071e24ee8b114d894ac172f77dc250e5bfa4, the pr is: https://github.com/PHPOffice/PhpSpreadsheet/pull/780.
=> [GHSA-xcrg-29h7-h4cj] XXE in PHPSpreadsheet due to encoding issue

advisories/github-reviewed/2023/08/GHSA-7c28-wg7r-pg6f/GHSA-7c28-wg7r-pg6f.json
**Updates**
- References
**Comments**
Add patch commit for v2.8.8: https://github.com/RaspAP/raspap-webgui/pull/1303/commits/1fabc481690e008279113e18d0642c5279e3b56e,
belongs to pr: https://github.com/RaspAP/raspap-webgui/pull/1303
they are mentioned in release note v2.8.8: "Security: Sanitize post data w/ escapeshellcmd() by @billz in #1303"
=> [GHSA-7c28-wg7r-pg6f] RaspAP Command Injection vulnerability

advisories/github-reviewed/2023/07/GHSA-w33c-445m-f8w7/GHSA-w33c-445m-f8w7.json
**Updates**
**Comments**
The `okio-jvm` is a packaging of okio specific for JVM (There is also a specific for multiplatform). The vulnerability concerns specifically the JVM so we need to alert people about `okio-jvm` as well.
=> [GHSA-w33c-445m-f8w7] Okio Signed to Unsigned Conversion Error vulnerability

advisories/github-reviewed/2023/08/GHSA-7r88-wjhj-jr8m/GHSA-7r88-wjhj-jr8m.json
**Updates**
- References
**Comments**
Add the patch commit for v2.9.5: https://github.com/RaspAP/raspap-webgui/commit/e87e7d1d3a61617430851f2a040379de1ff3dd9d
- PR: https://github.com/RaspAP/raspap-webgui/pull/1395
mentioned in release note v2.9.5: "Sanitize post with escapeshellcmd() in #1395"
=> [GHSA-7r88-wjhj-jr8m] RaspAP Command Injection vulnerability

advisories/github-reviewed/2023/02/GHSA-6hr3-44gx-g6wh/GHSA-6hr3-44gx-g6wh.json
**Updates**
- References
**Comments**
Add patches:
-  on the 4.9 branch to fix this issue: https://github.com/phpmyadmin/phpmyadmin/commit/53f70fd7f3b388639922e6cc1ca51fbe890c91cc
- 5.2 branch to fix this issue: https://github.com/phpmyadmin/phpmyadmin/commit/efa2406695551667f726497750d3db91fb6f662e
they are also mentioned in the reference link: https://www.phpmyadmin.net/security/PMASA-2023-1/
=> [GHSA-6hr3-44gx-g6wh] XSS vulnerability in drag-and-drop upload of phpMyAdmin

advisories/github-reviewed/2019/08/GHSA-gwp4-hfv6-p7hw/GHSA-gwp4-hfv6-p7hw.json
**Updates**
- Description
**Comments**
The actual 2.8.11.x fix version is 2.8.11.4, not the 2.8.11.14 which does not exist.
As per the updated source: https://nvd.nist.gov/vuln/detail/CVE-2019-14439
https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/
=> [GHSA-gwp4-hfv6-p7hw] Deserialization of untrusted data in FasterXML jackson-databind

advisories/github-reviewed/2020/11/GHSA-g3wg-6mcf-8jj6/GHSA-g3wg-6mcf-8jj6.json
**Updates**
**Comments**
Actual version of fix is `9.4.33.v20201020`, not the shorthand `9.4.33`, which can not be found and fixed automatically.
=> [GHSA-g3wg-6mcf-8jj6] Local Temp Directory Hijacking Vulnerability

advisories/github-reviewed/2023/06/GHSA-ff3m-68vj-h86p/GHSA-ff3m-68vj-h86p.json
**Updates**
**Comments**
See *Products Affected* on this page: https://www.cvedetails.com/cve/CVE-2023-3432/ The plantuml-mit package is the same package as the plantuml package but with another license.
=> [GHSA-ff3m-68vj-h86p] PlantUML Server-Side Request Forgery vulnerability

advisories/github-reviewed/2018/10/GHSA-jv74-f9pj-xp3f/GHSA-jv74-f9pj-xp3f.json
**Updates**
- References
**Comments**
found the patch for 
- v4.2.0: https://github.com/apache/camel/commit/4580e4d6c65cfd544c1791c824b5819477c583cc
The commit msg also pointed the issue: CAMEL-12630
=> [GHSA-jv74-f9pj-xp3f] Apache Camel's Mail is vulnerable to path traversal

advisories/github-reviewed/2019/05/GHSA-f554-x222-wgf7/GHSA-f554-x222-wgf7.json
**Updates**
- References
**Comments**
The affected version is not correctly recorded in GHSA based on the patch commit and the CVE description. 
Affected versions have been updated and the link to the patch commit has been added to the references.
=> [GHSA-f554-x222-wgf7] Command Injection in Xstream

advisories/github-reviewed/2023/11/GHSA-vmq6-5m68-f53m/GHSA-vmq6-5m68-f53m.json
**Updates**
- Description
- References
**Comments**
Adding a clarification that it's only vulnerable if using receivers, and documentation for receivers so it's clear how to find if you're using them.
=> [GHSA-vmq6-5m68-f53m] logback serialization vulnerability

advisories/github-reviewed/2023/11/GHSA-jpr7-q523-hx25/GHSA-jpr7-q523-hx25.json
**Updates**
**Comments**
In v2 of `phpseclib` `Math/BinaryField` does not exist, see https://github.com/phpseclib/phpseclib/issues/1964
=> [GHSA-jpr7-q523-hx25] phpseclib vulnerable to denial of service

advisories/github-reviewed/2023/11/GHSA-jfhm-5ghh-2f97/GHSA-jfhm-5ghh-2f97.json
**Updates**
- CVSS
- Severity
**Comments**
The project published this advisory with a moderate severity score https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97
The GHSA entry shows up as critical with "integrity: high". There simply cannot be a complete loss of integrity from a NULL pointer deferefence.
=> [GHSA-jfhm-5ghh-2f97] cryptography vulnerable to NULL-dereference when loading PKCS7 certificates

advisories/github-reviewed/2023/11/GHSA-hx93-gc73-5rpr/GHSA-hx93-gc73-5rpr.json
**Updates**
- References
**Comments**
Add patch commit for v1.10.0: https://github.com/elastic/apm-agent-dotnet/commit/c2b519aaa0fe5e5044b736cfec695342f124bf30
PR is: https://github.com/elastic/apm-agent-dotnet/pull/1286
the commit msg also mentioned: "Sanitize HTTP headers when the agent reads them"
=> [GHSA-hx93-gc73-5rpr] Exposure of Sensitive Information in Elastic APM .NET Agent

advisories/github-reviewed/2023/11/GHSA-c38w-74pg-36hr/GHSA-c38w-74pg-36hr.json
**Updates**
**Comments**
rsa v0.9.6 has been released on 2023-12-01 and is still vulnerable to CVE-2023-49092. Currently, there is not solution available.
https://github.com/RustCrypto/RSA
https://github.com/RustCrypto/RSA/blob/master/CHANGELOG.md
=> [GHSA-c38w-74pg-36hr] Marvin Attack: potential key recovery through timing sidechannels

advisories/github-reviewed/2022/09/GHSA-5m2h-7rf2-rpx6/GHSA-5m2h-7rf2-rpx6.json
**Updates**
- Description
- References
**Comments**
I am the maintainer of unisharp/laravel-filemanager. `v2.6.4` has been released to fix this issue.
=> [GHSA-5m2h-7rf2-rpx6] UniSharp Laravel Filemanager directory traversal vulnerability

advisories/github-reviewed/2023/07/GHSA-mjmq-gwgm-5qhm/GHSA-mjmq-gwgm-5qhm.json
**Updates**
**Comments**
NVD database updated to reflect 2.9.3 release on November 21st.
=> [GHSA-mjmq-gwgm-5qhm] Apache MINA SSHD information disclosure vulnerability

advisories/github-reviewed/2023/10/GHSA-67hx-6x53-jw92/GHSA-67hx-6x53-jw92.json
**Updates**
- CVSS
- Severity
**Comments**
Using Babel to compile code that was specifically crafted by an attacker can lead to arbitrary code execution during compilation, when using plugins that rely on the path.evaluate()or path.evaluateTruthy() internal Babel methods.
Known affected plugins are:
@babel/plugin-transform-runtime
@babel/preset-env when using its useBuiltIns option
Any "polyfill provider" plugin that depends on @babel/helper-define-polyfill-provider, such as babel-plugin-polyfill-corejs3, babel-plugin-polyfill-corejs2, babel-plugin-polyfill-es-shims, babel-plugin-polyfill-regenerator
No other plugins under the @babel/ namespace are impacted, but third-party plugins might be.
Users that only compile trusted code are not impacted.
Patches
The …
=> [GHSA-67hx-6x53-jw92] Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code

advisories/github-reviewed/2023/12/GHSA-2j39-qcjm-428w/GHSA-2j39-qcjm-428w.json
**Updates**
- References
- Severity
**Comments**
CVE-2023-50164(S2-066) is considered Critical by the official wiki.
https://cwiki.apache.org/confluence/display/WW/S2-066
=> [GHSA-2j39-qcjm-428w] Apache Struts vulnerable to path traversal

advisories/github-reviewed/2023/11/GHSA-vfp6-jrw2-99g9/GHSA-vfp6-jrw2-99g9.json
**Updates**
**Comments**
The fix for this vulnerability has been ported back to v1.x.x
- https://github.com/sigstore/cosign/releases/tag/v1.13.2
- https://github.com/sigstore/cosign/pull/3364
=> [GHSA-vfp6-jrw2-99g9] Cosign vulnerable to possible endless data attack from attacker-controlled registry

advisories/github-reviewed/2023/11/GHSA-4grx-2x9w-596c/GHSA-4grx-2x9w-596c.json
**Updates**
- CVSS
- Severity
**Comments**
There shouldn't be any integrity impact since the vulnerability allows attackers to only reveal the private key. The CVSS scoring shouldn't consider any further actions being taken. This would correspond to the latest scoring of NVD/MITRE: https://nvd.nist.gov/vuln/detail/CVE-2023-49092
=> [GHSA-4grx-2x9w-596c] Marvin Attack: potential key recovery through timing sidechannels

advisories/github-reviewed/2023/12/GHSA-3m87-5598-2v4f/GHSA-3m87-5598-2v4f.json
**Updates**
**Comments**
This vulnerability was fixed in release [2.7.1](https://github.com/prometheus/prometheus/releases/tag/v2.7.1). However, starting with release v2.35.0 the prometheus team changed the go versioning scheme to respect Go rules, and the Go library version became [v0.35.0](https://github.com/prometheus/prometheus/releases/tag/v0.35.0). 
In essence, all `v0.x.x` versions are not vulnerable since they're all after v2.7.1.
=> [GHSA-3m87-5598-2v4f] Prometheus XSS Vulnerability

advisories/github-reviewed/2023/12/GHSA-45x7-px36-x8w8/GHSA-45x7-px36-x8w8.json
**Updates**
**Comments**
https://github.com/paramiko/paramiko/issues/2337 which is already in references. This advisory probably should be rewritten to not be Russh specific (CVE-2023-48795 is an issue affecting a lot of libraries, and in fact GitHub already acknowledges it affects golang.org/x/crypto).
See also: https://github.com/github/advisory-database/issues/2869.
=> [GHSA-45x7-px36-x8w8] Russh vulnerable to Prefix Truncation Attack against ChaCha20-Poly1305 and Encrypt-then-MAC

advisories/github-reviewed/2023/11/GHSA-4532-pmx7-9ww7/GHSA-4532-pmx7-9ww7.json
**Updates**
- Description
**Comments**
Removed the cesium npm package from the list of affected products. There doesn't seem to be a way to completely remove the advisory from the "Improve security advisory" form -- it may be a legit advisory, but the npm package itself is not affected.
The vulnerability exists in demo code within the Cesium Github repository, but is NOT included in the npm package or actual Cesium library that gets distributed. It should therefore not appear as an advisory in other applications that are using the Cesium library.
=> [GHSA-4532-pmx7-9ww7] Cross-site Scripting in cesium

advisories/github-reviewed/2018/10/GHSA-2fw5-rvf2-jq56/GHSA-2fw5-rvf2-jq56.json
**Updates**
- References
**Comments**
Add three patch links related to CVE-2014-0002.
=> [GHSA-2fw5-rvf2-jq56] Apache Camel's XSLT component allows remote attackers to read arbitrary files

advisories/github-reviewed/2018/10/GHSA-h6rp-8v4j-hwph/GHSA-h6rp-8v4j-hwph.json
**Updates**
- References
**Comments**
Add three patch links related to CVE-2014-0003.
=> [GHSA-h6rp-8v4j-hwph] Apache Camel's XSLT component allows remote attackers to execute arbitrary Java methods

advisories/github-reviewed/2018/10/GHSA-3hrc-f439-727g/GHSA-3hrc-f439-727g.json
**Updates**
- References
**Comments**
Add two patch links related to CVE-2015-0263.
=> [GHSA-3hrc-f439-727g] Apache Camel XML External Entity vulnerability

advisories/github-reviewed/2018/10/GHSA-mhx2-r3jx-g94c/GHSA-mhx2-r3jx-g94c.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2015-1264.
=> [GHSA-mhx2-r3jx-g94c] Apache Camel allows remote actor to read arbitrary files via external entity in invalid XML string or GenericFile object

advisories/github-reviewed/2018/10/GHSA-vq9j-jh62-5hmp/GHSA-vq9j-jh62-5hmp.json
**Updates**
- References
**Comments**
Add source location link and patch links related to CVE-2017-5643 which fixed in multi-branch.
=> [GHSA-vq9j-jh62-5hmp] Apache Camel using an outdated vulnerable JSON-lib library

advisories/github-reviewed/2018/10/GHSA-gv5f-cjw9-5vxg/GHSA-gv5f-cjw9-5vxg.json
**Updates**
- References
**Comments**
Add source location link, issue link and patch related to CVE-2015-5344 which fixed in multi-branch.
=> [GHSA-gv5f-cjw9-5vxg] Camel-xstream component in Apache Camel can allow remote attackers to execute arbitrary commands 

advisories/github-reviewed/2018/10/GHSA-hvpr-9cr6-q5v7/GHSA-hvpr-9cr6-q5v7.json
**Updates**
- References
**Comments**
Add issue link and some patch links related to CVE-2017-3159 which fixed in multi-branch.
=> [GHSA-hvpr-9cr6-q5v7] Apache Camel's camel-snakeyaml component is vulnerable to Java object de-serialization

advisories/github-reviewed/2018/10/GHSA-26v6-w6fw-rh94/GHSA-26v6-w6fw-rh94.json
**Updates**
- References
**Comments**
Add source location link and some patch links related to CVE-2015-5348 which fixed in multi-branch.
=> [GHSA-26v6-w6fw-rh94] Apache Camel can allow remote attackers to execute arbitrary commands

advisories/github-reviewed/2018/10/GHSA-vvjc-q5vr-52q6/GHSA-vvjc-q5vr-52q6.json
**Updates**
- References
**Comments**
Add issue links, source code location link and some patch links related to CVE-2016-8749 which fixed in multi-branch.
=> [GHSA-vvjc-q5vr-52q6] Apache Camel's Jackson and JacksonXML unmarshalling operation are vulnerable to Remote Code Execution attacks

advisories/github-reviewed/2022/05/GHSA-mfhr-3xmc-r2gg/GHSA-mfhr-3xmc-r2gg.json
**Updates**
- References
**Comments**
Add source code location link and patch link related to CVE-2013-1879.
=> [GHSA-mfhr-3xmc-r2gg] Improper Neutralization of Input During Web Page Generation in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-c9gx-27hq-wcvj/GHSA-c9gx-27hq-wcvj.json
**Updates**
- References
**Comments**
Add source code link and patch link related to CVE-2013-1880
=> [GHSA-c9gx-27hq-wcvj] Apache ActiveMQ Cross-site scripting (XSS) vulnerability in the Portfolio publisher servlet 

advisories/github-reviewed/2022/05/GHSA-3wfj-vh84-732p/GHSA-3wfj-vh84-732p.json
**Updates**
- References
**Comments**
Add source code link and one patch link related to CVE-2014-3576.
=> [GHSA-3wfj-vh84-732p] Improper Neutralization of Special Elements used in an OS Command in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-4vhf-2hv7-8mrx/GHSA-4vhf-2hv7-8mrx.json
**Updates**
- References
**Comments**
Add source code link and patch link related to CVE-2014-3600.
=> [GHSA-4vhf-2hv7-8mrx] Improper Restriction of XML External Entity Reference in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-3v63-f83x-37x4/GHSA-3v63-f83x-37x4.json
**Updates**
- References
**Comments**
Add source location and patch links related to CVE-2015-1830.
=> [GHSA-3v63-f83x-37x4] Improper Limitation of a Pathname to a Restricted Directory in Apache ActiveMQ

advisories/github-reviewed/2019/08/GHSA-jvpp-hxjj-5ccc/GHSA-jvpp-hxjj-5ccc.json
**Updates**
- References
**Comments**
Add location link and patch links related to CVE-2015-7559.
=> [GHSA-jvpp-hxjj-5ccc] Improper Input Validation and Missing Authentication for Critical Function in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-rxqh-fc23-gxp2/GHSA-rxqh-fc23-gxp2.json
**Updates**
- References
**Comments**
Add location link and patch link related to CVE-2016-3088.
=> [GHSA-rxqh-fc23-gxp2] Improper Input Validation in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-7qm4-p377-fr2r/GHSA-7qm4-p377-fr2r.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2017-15709.
=> [GHSA-7qm4-p377-fr2r] ActiveMQ's OpenWire protocol exposes certain system details as plain text

advisories/github-reviewed/2022/05/GHSA-2g99-c67p-56hm/GHSA-2g99-c67p-56hm.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2012-2379
=> [GHSA-2g99-c67p-56hm] XML Signature/Encryption Not Validated in Apache CXF

advisories/github-reviewed/2023/10/GHSA-r6j3-px5g-cq3x/GHSA-r6j3-px5g-cq3x.json
**Updates**
**Comments**
Improve visibility for org.apache.tomcat.embed:tomcat-embed-core
Reasoning -> fixed components are also part of tomcat-embed-core package:
(11.0.x) https://github.com/apache/tomcat/commit/eb5c094e5560764cda436362254997511a3ca1f6
(10.1.x) https://github.com/apache/tomcat/commit/8ecff306507be8e4fd3adee1ae5de1ea6661a8f4
(9.0.x) https://github.com/apache/tomcat/commit/59583245639d8c42ae0009f4a4a70464d3ea70a0
(8.5.x) https://github.com/apache/tomcat/commit/59583245639d8c42ae0009f4a4a70464d3ea70a0
=> [GHSA-r6j3-px5g-cq3x] Apache Tomcat Improper Input Validation vulnerability

advisories/github-reviewed/2023/10/GHSA-g8pj-r55q-5c2v/GHSA-g8pj-r55q-5c2v.json
**Updates**
**Comments**
Improve visibility for org.apache.tomcat.embed:tomcat-embed-core
Reasoning -> fixed components are also part of tomcat-embed-core package:
(11.0.x) https://github.com/apache/tomcat/commit/d6db22e411307c97ddf78315c15d5889356eca38
(10.1.x) https://github.com/apache/tomcat/commit/9375d67106f8df9eb9d7b360b2bef052fe67d3d4
(9.0.x) https://github.com/apache/tomcat/commit/44d05d75d696ca10ce251e4e370511e38f20ae75
(8.5.x) https://github.com/apache/tomcat/commit/30f8063d7a9b4c43ae4722f5e382a76af1d7a6bf
=> [GHSA-g8pj-r55q-5c2v] Apache Tomcat Incomplete Cleanup vulnerability

advisories/github-reviewed/2022/05/GHSA-3336-h95j-hvvf/GHSA-3336-h95j-hvvf.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2015-5253.
=> [GHSA-3336-h95j-hvvf] Improper Access Control in Apache CXF

advisories/github-reviewed/2022/05/GHSA-x7xf-253v-x3w8/GHSA-x7xf-253v-x3w8.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2016-8739
=> [GHSA-x7xf-253v-x3w8] Improper Restriction of XML External Entity Reference in Apache CXF JAX-RS

advisories/github-reviewed/2018/10/GHSA-jc7r-v6fg-2gpf/GHSA-jc7r-v6fg-2gpf.json
**Updates**
- References
**Comments**
Add one patch link related to CVE-2018-8039
=> [GHSA-jc7r-v6fg-2gpf] High severity vulnerability that affects org.apache.cxf:apache-cxf, org.apache.cxf:apache-cxf , and org.apache.cxf:cxf

advisories/github-reviewed/2023/10/GHSA-jq35-85cj-fj4p/GHSA-jq35-85cj-fj4p.json
**Updates**
**Comments**
According to the Moby project, this vulnerability was fixed in v23.0.8 as well, see https://github.com/moby/moby/releases/tag/v23.0.8
=> [GHSA-jq35-85cj-fj4p] /sys/devices/virtual/powercap accessible by default to containers

advisories/github-reviewed/2022/05/GHSA-whmq-v94q-34p9/GHSA-whmq-v94q-34p9.json
**Updates**
- References
**Comments**
Add some patch links and source code link related to CVE-2013-1965.
=> [GHSA-whmq-v94q-34p9] Improper Control of Generation of Code in Apache Struts

advisories/github-reviewed/2022/05/GHSA-q5q8-jghf-3pm3/GHSA-q5q8-jghf-3pm3.json
**Updates**
- References
**Comments**
Add one patch link related to CVE-2013-4310.
=> [GHSA-q5q8-jghf-3pm3] Apache Struts2 Broken Access Control Vulnerability

advisories/github-reviewed/2022/05/GHSA-38qw-j787-v8c2/GHSA-38qw-j787-v8c2.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2016-4430.
=> [GHSA-38qw-j787-v8c2] Apache Struts CSRF Vulnerability

advisories/github-reviewed/2018/10/GHSA-8fx9-5hx8-crhm/GHSA-8fx9-5hx8-crhm.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2017-12611.
=> [GHSA-8fx9-5hx8-crhm] Apache Struts 2.0.1 uses an unintentional expression in a Freemarker tag instead of string literal

advisories/github-reviewed/2018/10/GHSA-j77q-2qqg-6989/GHSA-j77q-2qqg-6989.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2017-5638.
=> [GHSA-j77q-2qqg-6989] Apache Struts vulnerable to remote arbitrary command execution due to improper input validation

advisories/github-reviewed/2018/10/GHSA-8mr5-h28g-36qx/GHSA-8mr5-h28g-36qx.json
**Updates**
- References
**Comments**
Add some patch links and source code link related to CVE-2017-9787 which fixed in multi-branch.
=> [GHSA-8mr5-h28g-36qx] Spring AOP functionality (Struts) vulnerable to DoS attack

advisories/github-reviewed/2018/10/GHSA-x5x7-3v85-wpc4/GHSA-x5x7-3v85-wpc4.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2017-9804 which fixed in multi-branch.
=> [GHSA-x5x7-3v85-wpc4] Apache Struts allows entering a custom URL in a form field if built-in URLValidator is used

advisories/github-reviewed/2018/10/GHSA-gg9m-fj3v-r58c/GHSA-gg9m-fj3v-r58c.json
**Updates**
- References
**Comments**
Add source code link and some patch links related to CVE-2017-9805.
=> [GHSA-gg9m-fj3v-r58c] REST Plugin in Apache Struts uses an XStreamHandler with an instance of XStream for deserialization without any type filtering

advisories/github-reviewed/2018/10/GHSA-cr6j-3jp9-rw65/GHSA-cr6j-3jp9-rw65.json
**Updates**
- References
**Comments**
Add source code link and some patch links related to CVE-2018-11776 which fixed in multi-branch.
=> [GHSA-cr6j-3jp9-rw65] Apache Struts vulnerable to remote command execution (RCE) due to improper input validation

advisories/github-reviewed/2018/10/GHSA-38cr-2ph5-frr9/GHSA-38cr-2ph5-frr9.json
**Updates**
- References
**Comments**
Add source code link and patch links related to CVE-2018-1327.
=> [GHSA-38cr-2ph5-frr9] Apache Struts REST Plugin can potentially allow a DoS attack

advisories/github-reviewed/2020/09/GHSA-r4m5-47cq-6qg8/GHSA-r4m5-47cq-6qg8.json
**Updates**
- Description
- References
**Comments**
This looks to have been addressed in the project.  I believe the org name of the repo changed and this advisory was orphaned.
https://github.com/QuorumDMS/ftp-srv/security/advisories/GHSA-jw37-5gqr-cf9j
=> [GHSA-r4m5-47cq-6qg8] Server-Side Request Forgery in ftp-srv

advisories/github-reviewed/2023/12/GHSA-7hpj-7hhx-2fgx/GHSA-7hpj-7hhx-2fgx.json
**Updates**
- CVSS
- Severity
**Comments**
Original reporter here, I originally found this exploit in the wild targeted against my services. This issue occurs on any configuration of msgpackr before the patch, the only requirement is for it to be set up in the chain in a position to deserialize anything the user submits. For example, if your REST API or WebSockets API takes MsgPack data through this library, it will be vulnerable to be DoS'd through this vulnerability. This is not the most common usage of msgpackr but not an entirely uncommon one.
Not sure if there should be a mention of the vuln being actively exploited.
=> [GHSA-7hpj-7hhx-2fgx] msgpackr's conversion of property names to strings can trigger infinite recursion

advisories/github-reviewed/2019/01/GHSA-4p24-vmcr-4gqj/GHSA-4p24-vmcr-4gqj.json
**Updates**
- Description
- References
**Comments**
we used the demonstration example from https://github.com/twbs/bootstrap/issues/20184#issuecomment-324985479 and proofed, that also version 2.0.4 and above are affected, but 2.0.3 and below not, see https://jsbin.com/dahojakupe/edit?html,output
=> [GHSA-4p24-vmcr-4gqj] Bootstrap XSS vulnerability

advisories/github-reviewed/2024/01/GHSA-vfxf-76hv-v4w4/GHSA-vfxf-76hv-v4w4.json
**Updates**
**Comments**
Removed protocol information from package names as this is the usual procedure with other GHSAs. Moreover, having package names starting with "https://" leads to import warnings in OWASP Dependency-Track, e.g.:
`[GitHubAdvisoryMirrorTask] Unable to create purl from GitHub Vulnerability. Skipping GO : https://github.com/gravitational/teleport for: GHSA-vfxf-76hv-v4w4`
=> [GHSA-vfxf-76hv-v4w4] User-provided environment values allow execution on macOS agents

advisories/github-reviewed/2023/09/GHSA-6qjf-7g3j-qx25/GHSA-6qjf-7g3j-qx25.json
**Updates**
**Comments**
The Neos team has fixed the vulnerability in the affected package (neos/media-browser). We have adapted the security advisory to the correct affected versions and packages. 
Please note, that we use a mono-repo with subsplit repos to release single packages.
Please see the respective issue and pr:
- Issue: https://github.com/neos/neos-development-collection/issues/4833
- PR: https://github.com/neos/neos-development-collection/pull/4812
And the releases:
- https://github.com/neos/neos-development-collection/releases/tag/7.3.19
- https://github.com/neos/neos-development-collection/releases/tag/8.0.16
- https://github.com/neos/neos-development-collection/releases/tag/8.1.11
- …
=> [GHSA-6qjf-7g3j-qx25] Neos CMS Cross Site Scripting vulnerability

advisories/github-reviewed/2018/09/GHSA-pj7m-g53m-7638/GHSA-pj7m-g53m-7638.json
**Updates**
- Description
**Comments**
I used the example of https://github.com/twbs/bootstrap/issues/26627#issuecomment-393058335 and modified the bootstrap version to one below the formerly stated patched version 3.4.0 and couldn't verify the issue see https://jsbin.com/jafujoqage/edit?html,output
=> [GHSA-pj7m-g53m-7638] Bootstrap Cross-site Scripting vulnerability

advisories/github-reviewed/2024/01/GHSA-ghjv-mh6x-7q6h/GHSA-ghjv-mh6x-7q6h.json
**Updates**
- References
**Comments**
Fix was backported to 2.x in https://github.com/avo-hq/avo/pull/2382 and the security-advisory updated to reflect this: https://github.com/avo-hq/avo/security/advisories/GHSA-ghjv-mh6x-7q6h
=> [GHSA-ghjv-mh6x-7q6h] avo vulnerable to stored cross-site scripting (XSS) in key_value field

advisories/github-reviewed/2024/01/GHSA-g8vp-2v5p-9qfh/GHSA-g8vp-2v5p-9qfh.json
**Updates**
**Comments**
The original repository advisory only mentioned one specific version (3.0.0.pre12) to be affected. As this advisory causes all older versions of avo to be flagged as vulnerable I propose the following changes which I verified manually (see linked repository).
I verified the vulnerability as described for version 3.0.0.pre12 (https://github.com/tamaloa/avo-CVE-2024-22411/commit/ae0df1d51469c59e456c86a18d7d25f2f93b14d9).
I also verified that version 2.47.0 is NOT vulnerable (https://github.com/tamaloa/avo-CVE-2024-22411/commit/bb1dc89dcaeb26c643ff91b4719f4959bf0b0103).
Maybe the initial reporter (@stevegeek) could add insight if really only 3.0.0.pre12 was affected or more versions. Unfortunately on a quick look I could not find a tag / commit …
=> [GHSA-g8vp-2v5p-9qfh] Cross-site scripting (XSS) in Action messages on Avo

advisories/github-reviewed/2023/12/GHSA-pfh2-hfmq-phg5/GHSA-pfh2-hfmq-phg5.json
**Updates**
- CVSS
- Severity
**Comments**
- A fixed version (2.9.0) was published.
- NIST NVD record has updated severity to 5.3 MEDIUM.
=> [GHSA-pfh2-hfmq-phg5] json-path Out-of-bounds Write vulnerability

advisories/github-reviewed/2023/06/GHSA-6w63-h3fj-q4vw/GHSA-6w63-h3fj-q4vw.json
**Updates**
**Comments**
Up until version 4.1.2, the entity name is parsed using `RegExp("^\\s([a-zA-z0-0]+)[ \t](['\"])([^&]+)\\2");` - see https://github.com/NaturalIntelligence/fast-xml-parser/blob/v4.1.2/src/xmlparser/DocTypeReader.js#L108C35-L108C45
In this implementation, the entity name regex is constructed as follows ```RegExp( `&${match[1]};`,"g"),```. Since `match[1]` is `[a-zA-z0-0]+`. It is not possible to construct a vulnerable regular expression.
Starting 4.1.3, the implementation changes to the following vulnerable implementation - https://github.com/NaturalIntelligence/fast-xml-parser/blob/v4.1.3/src/xmlparser/DocTypeReader.js#L62
=> [GHSA-6w63-h3fj-q4vw] fast-xml-parser vulnerable to Regex Injection via Doctype Entities

advisories/github-reviewed/2023/11/GHSA-rcjc-c4pj-xxrp/GHSA-rcjc-c4pj-xxrp.json
**Updates**
**Comments**
The fix range information from NVD is incomplete. Per the upstream project, patches have been backported all the way to 10.14: https://issues.apache.org/jira/browse/DERBY-7147
=> [GHSA-rcjc-c4pj-xxrp] Apache Derby: LDAP injection vulnerability in authenticator

advisories/github-reviewed/2022/05/GHSA-wmmc-qjq2-vvm2/GHSA-wmmc-qjq2-vvm2.json
**Updates**
- References
**Comments**
add patch commit for v2.5.0-rc1: https://github.com/moodle/moodle/commit/5df9bc3998095299c6862973866252649a5e0866. 
The commit msg mentioned: `MDL-37475 core_grade:fixed the handling of show totals`, which matches existing ref link: `http://git.moodle.org/gw?p=moodle.git&a=search&h=HEAD&st=commit&s=MDL-37475`
=> [GHSA-wmmc-qjq2-vvm2] Moodle is vulnerable to Sensitive Information Disclosure

advisories/github-reviewed/2022/05/GHSA-m63h-q4x3-6hwj/GHSA-m63h-q4x3-6hwj.json
**Updates**
- References
**Comments**
add patch commit for v2.5.0-rc1: https://github.com/moodle/moodle/commit/d5909fd1447bc6f05dbf37d7c9eb72b79004e24a.
=> [GHSA-m63h-q4x3-6hwj] Moodle is vulnerable to Improper Input Validation in MoodleQuickForm class

advisories/github-reviewed/2024/01/GHSA-r4q3-7g4q-x89m/GHSA-r4q3-7g4q-x89m.json
**Updates**
**Comments**
according to the [official announcement](https://spring.io/security/cve-2024-22233/), patched versions are `6.0.16` and `6.1.3`. and affected versions are just `6.0.15` and `6.1.2`.
=> [GHSA-r4q3-7g4q-x89m] Spring Framework server Web DoS Vulnerability

advisories/github-reviewed/2022/05/GHSA-9v64-447r-wch6/GHSA-9v64-447r-wch6.json
**Updates**
- References
- Summary
**Comments**
add patch commit: https://github.com/moodle/moodle/commit/40a04658232d898223462f84d8cd35510338acbe. 
the commit msg has shown it's a fix for `MDL-47050`. 
update vvr as well.
=> [GHSA-9v64-447r-wch6] Moodle Temporary Passwords are Brute Force-able

advisories/github-reviewed/2022/05/GHSA-vjwc-5hfh-2vv5/GHSA-vjwc-5hfh-2vv5.json
**Updates**
- CVSS
- References
**Comments**
added Source Code Location
updated cvss3.0 to cvss 3.1
updated package name as per fix commit.
=> [GHSA-vjwc-5hfh-2vv5] Use of a Broken or Risky Cryptographic Algorithm in Apache WSS4J

advisories/github-reviewed/2022/05/GHSA-h798-h7ff-93xv/GHSA-h798-h7ff-93xv.json
**Updates**
- CWEs
- References
**Comments**
update the cwe according to the info on nvd.
add patch commit: https://github.com/moodle/moodle/commit/db200a8e9f88c8c4a2141ac264062dca74ee2f29. 
the commit msg has shown it's a fix for `MDL-49179`.
=> [GHSA-h798-h7ff-93xv] Moodle Arbitrary Redirect

advisories/github-reviewed/2022/05/GHSA-r9pc-g29w-f86j/GHSA-r9pc-g29w-f86j.json
**Updates**
- References
**Comments**
add patch commit: https://github.com/moodle/moodle/commit/1688564a6eee6000013f6e185f704049283ae375. 
the commit msg has shown it's a fix for `MDL-52651`.
=> [GHSA-r9pc-g29w-f86j] Moodle sensitive information disclosure

advisories/github-reviewed/2022/05/GHSA-qrcj-6fjw-3h9h/GHSA-qrcj-6fjw-3h9h.json
**Updates**
- References
**Comments**
add patch commit: https://github.com/moodle/moodle/commit/93dda3bfd3caaaa8d23fe8ede543f27ef774958d. 
the commit msg has shown it's a fix for `MDL-63786`.
=> [GHSA-qrcj-6fjw-3h9h] Moodle XSS Vulnerability

advisories/github-reviewed/2021/08/GHSA-r628-mhmh-qjhw/GHSA-r628-mhmh-qjhw.json
**Updates**
**Comments**
Versions before 3.0.0 doesn't have directory cache, hence aren't affected by this vulnerability.
Version 3.0.0 introduced (dirCahce)[https://github.com/isaacs/node-tar/blob/v3.0.0/lib/unpack.js#L44].
While 2.2.2 uses includes only (extract.js)[https://github.com/isaacs/node-tar/blob/v2.2.2/lib/extract.js] which doesn't have any kind of cache.
=> [GHSA-r628-mhmh-qjhw] Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning

advisories/github-reviewed/2023/08/GHSA-c2cc-3569-6jh2/GHSA-c2cc-3569-6jh2.json
**Updates**
**Comments**
Updated affected version range and added patched version information. 
Path traversals and symlink escapes as described in CVE-2023-39138 were fixed with version 0.9.18 of ZIP Foundation: https://github.com/weichsel/ZIPFoundation/releases/tag/0.9.18
=> [GHSA-c2cc-3569-6jh2] Path traversal in ZIPFoundation

advisories/github-reviewed/2024/01/GHSA-7mgx-gvjw-m3w3/GHSA-7mgx-gvjw-m3w3.json
**Updates**
- CVSS
- Severity
**Comments**
I am the author of this vulnerability. This vulnerability does not require any user interaction or permissions. You only need to add specific fields in the request header to obtain superuser permissions for the createDB database, which completely affects confidentiality. According to the CVSS score, it should be 7.5 points.
=> [GHSA-7mgx-gvjw-m3w3] CrateDB authentication bypass vulnerability

advisories/github-reviewed/2024/02/GHSA-2cjh-75gp-34gc/GHSA-2cjh-75gp-34gc.json
**Updates**
- Description
**Comments**
Exclude livewire v2 from this advisory
**Edit**
I see that my reasoning from the form isn't included. So I'll add it again.
Reading the advisories it can be tracked back to a commit on the v3 tag of livewire. As such this would mean that v2 is unaffected.
Currently this advisory is scoped to also include v2, which doesn't seem correct following the above reasoning.
=> [GHSA-2cjh-75gp-34gc] livewire Cross-Site Request Forgery vulnerability

advisories/github-reviewed/2021/08/GHSA-9r2w-394v-53qc/GHSA-9r2w-394v-53qc.json
**Updates**
**Comments**
Versions before 3.0.0 doesn't have directory cache, hence aren't affected by this vulnerability.
Version 3.0.0 introduced (dirCahce)[https://github.com/isaacs/node-tar/blob/v3.0.0/lib/unpack.js#L44].
While 2.2.2 uses includes only (extract.js)[https://github.com/isaacs/node-tar/blob/v2.2.2/lib/extract.js] which doesn't have any kind of cache.
=> [GHSA-9r2w-394v-53qc] Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning using symbolic links

advisories/github-reviewed/2024/02/GHSA-9gh8-877r-g477/GHSA-9gh8-877r-g477.json
**Updates**
- CWEs
- Description
**Comments**
Checking the Issue, it states that versions including 3.15.12 are affected.
Checking the affected source code shows that it is under the beetl-core.
=> [GHSA-9gh8-877r-g477] Beetl Server-Side Template Injection vulnerability

advisories/github-reviewed/2024/02/GHSA-34q3-p352-c7q8/GHSA-34q3-p352-c7q8.json
**Updates**
- CVSS
**Comments**
The original documentation was not correct so I fixed it.
https://github.com/line/centraldogma/security/advisories/GHSA-34q3-p352-c7q8
=> [GHSA-34q3-p352-c7q8] Central Dogma Authentication Bypass Vulnerability via Session Leakage

advisories/github-reviewed/2021/08/GHSA-qq89-hq3f-393p/GHSA-qq89-hq3f-393p.json
**Updates**
- References
**Comments**
CVE-2021-37712 was fixed by two commits for each of the maintained branches
https://github.com/isaacs/node-tar/commit/bb93ba243746f705092905da1955ac3b0509ba1e - fixes `lib/path-reservations.js`, a functionality that was introduced in v4.4.16 hence irrelevant for earlier versions.
https://github.com/isaacs/node-tar/commit/2f1bca027286c23e110b8dfc7efc10756fa3db5a - fixes `lib/unpack.js`, a functionality that was introduced in v3.0.0, and caused other vulnerabilities like CVE-2021-32803.
Hence, to the best of my understanding this vulnerability affects versions 3.0.0 and above.
=> [GHSA-qq89-hq3f-393p] Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning using symbolic links

advisories/github-reviewed/2024/02/GHSA-7wh2-wxc7-9ph5/GHSA-7wh2-wxc7-9ph5.json
**Updates**
**Comments**
according to https://github.com/wixtoolset/issues/security/advisories/GHSA-7wh2-wxc7-9ph5 3.14.0 has also been patched, so should not be affected by the vulnerability?
=> [GHSA-7wh2-wxc7-9ph5] WiX Toolset's .be TEMP folder is vulnerable to DLL redirection attacks that allow the attacker to escalate privileges

advisories/github-reviewed/2024/02/GHSA-78xj-cgh5-2h22/GHSA-78xj-cgh5-2h22.json
**Updates**
- Description
**Comments**
Include v2.0.0 as vulnerable
=> [GHSA-78xj-cgh5-2h22] NPM IP package vulnerable to Server-Side Request Forgery (SSRF) attacks

advisories/github-reviewed/2021/04/GHSA-gwrp-pvrq-jmwv/GHSA-gwrp-pvrq-jmwv.json
**Updates**
- References
**Comments**
Several other components are also affected as a result of cloning (copying source code) or shading (copying source code and renaming packages). Proof-of-Vulnerability projects with tests to verify the presence of the CVE can be found here: https://github.com/jensdietrich/xshady-release/.
See https://github.com/github/advisory-database/pull/2258, especially https://github.com/github/advisory-database/pull/2258#issuecomment-1569073245, for more details.
(This PR is a second attempt at #3442, which went wrong due to a bad merge. Thanks @darakian for clarifying how `last_affected` should be applied.)
=> Improve GHSA-gwrp-pvrq-jmwv

advisories/github-reviewed/2024/02/GHSA-qf9m-vfgh-m389/GHSA-qf9m-vfgh-m389.json
**Updates**
**Comments**
The vulnerability isn't in fastapi's code rather than python-multipart, and GHSA-2jv5-9r88-3w3p is a duplicate.
Notice that the fix of fastapi was to update python-multipart - https://github.com/tiangolo/fastapi/commit/9d34ad0ee8a0dfbbcce06f76c2d5d851085024fc
While python-multipart actually fixed the vulnerability - https://github.com/Kludex/python-multipart/commit/20f0ef6b4e4caf7d69a667c54dff57fe467109a4
=> [GHSA-qf9m-vfgh-m389] FastAPI Content-Type Header ReDoS

advisories/github-reviewed/2024/02/GHSA-w6x2-jg8h-p6mp/GHSA-w6x2-jg8h-p6mp.json
**Updates**
- References
**Comments**
Adjusted Git commit references...
(each of those commits references back to the CVE `Security-References: CVE-2023-30451`)
=> [GHSA-w6x2-jg8h-p6mp] Path Traversal in TYPO3 File Abstraction Layer Storages

advisories/github-reviewed/2024/02/GHSA-fq6h-4g8v-qqvm/GHSA-fq6h-4g8v-qqvm.json
**Updates**
**Comments**
ckeditor is also a Composer package
=> [GHSA-fq6h-4g8v-qqvm] CKEditor4 Cross-site Scripting vulnerability caused by incorrect CDATA detection

advisories/github-reviewed/2023/11/GHSA-wf5p-g6vw-rhxx/GHSA-wf5p-g6vw-rhxx.json
**Updates**
- References
**Comments**
The fix for this issue was backported to 0.28.0.
https://github.com/axios/axios/pull/6091
https://github.com/axios/axios/commit/2755df562b9c194fba6d8b609a383443f6a6e967
https://github.com/axios/axios/releases/tag/v0.28.0
=> [GHSA-wf5p-g6vw-rhxx] Axios Cross-Site Request Forgery Vulnerability

advisories/github-reviewed/2022/01/GHSA-76w9-p8mg-j927/GHSA-76w9-p8mg-j927.json
**Updates**
- CVSS
- Severity
**Comments**
Updated the attack vector parameter from "Network" to "Local", and privileges required from "None" to "High", to be in line with the description reading "The issue would require editing /etc/groups to exploit, which is usually only editable by the root user."
=> [GHSA-76w9-p8mg-j927] Out-of-bounds Write in nix

advisories/github-reviewed/2022/06/GHSA-xvc9-xwgj-4cq9/GHSA-xvc9-xwgj-4cq9.json
**Updates**
**Comments**
it is necessary to reject this entry because it was rejected in the original advisory.
=> [GHSA-xvc9-xwgj-4cq9] Integer Overflow in HeaderMap::reserve() can cause Denial of Service

advisories/github-reviewed/2022/05/GHSA-p26v-97vp-jcx6/GHSA-p26v-97vp-jcx6.json
**Updates**
- References
**Comments**
Add patch links and source code links related to CVE-2011-1183.
=> [GHSA-p26v-97vp-jcx6] Access controll bypass in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-r7c8-hghc-2mp8/GHSA-r7c8-hghc-2mp8.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2011-2481.
=> [GHSA-r7c8-hghc-2mp8] Apache Tomcat Allows Replacing of XML Parser

advisories/github-reviewed/2022/05/GHSA-c38m-v4m2-524v/GHSA-c38m-v4m2-524v.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2011-3190.
=> [GHSA-c38m-v4m2-524v] Apache Tomcat Allows Remote Attackers to Spoof AJP Requests

advisories/github-reviewed/2022/05/GHSA-j448-j653-r3vj/GHSA-j448-j653-r3vj.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2013-4286.
=> [GHSA-j448-j653-r3vj] Apache Tomcat is vulnerable to HTTP request-smuggling

advisories/github-reviewed/2022/05/GHSA-xh5x-j8jf-pcpx/GHSA-xh5x-j8jf-pcpx.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2014-0099.
=> [GHSA-xh5x-j8jf-pcpx] Improper Neutralization of CRLF Sequences in HTTP Headers in Apache Tomcat

advisories/github-reviewed/2021/08/GHSA-5fg8-2547-mr8q/GHSA-5fg8-2547-mr8q.json
**Updates**
- Description
**Comments**
The version 0.7.0 for `xmldom` does not exist, `@xmldom/xmldom` does. 
Search results in npm - https://www.npmjs.com/search?q=xmldom
They both point to the same source repo - github.com/xmldom/xmldom
=> [GHSA-5fg8-2547-mr8q] Misinterpretation of malicious XML input

advisories/github-reviewed/2022/05/GHSA-9hjv-9h75-xmpp/GHSA-9hjv-9h75-xmpp.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2016-0763.
=> [GHSA-9hjv-9h75-xmpp] Improper Verification of Source of a Communication Channel in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-3mjp-p938-4329/GHSA-3mjp-p938-4329.json
**Updates**
- References
**Comments**
Add three patch links related to CVE-2016-6796.
=> [GHSA-3mjp-p938-4329] Apache Tomcat vulnerable to SecurityManager bypass

advisories/github-reviewed/2022/05/GHSA-cw54-59pw-4g8c/GHSA-cw54-59pw-4g8c.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2016-8735 which fixed in multi-branch.
=> [GHSA-cw54-59pw-4g8c] Apache Tomcat Improper Access Control vulnerability

advisories/github-reviewed/2022/05/GHSA-fjwp-r6fm-q6qw/GHSA-fjwp-r6fm-q6qw.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2016-8747.
=> [GHSA-fjwp-r6fm-q6qw] Apache Tomcat allows remote attackers to read data that was intended to be associated with a different request

advisories/github-reviewed/2018/10/GHSA-46j3-r4pj-4835/GHSA-46j3-r4pj-4835.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2018-8034 which fixed in multi-branch.
=> [GHSA-46j3-r4pj-4835] The host name verification missing in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-9785-w233-x6hv/GHSA-9785-w233-x6hv.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2017-5650.
=> [GHSA-9785-w233-x6hv] Improper Resource Shutdown or Release in Apache Tomcat

advisories/github-reviewed/2024/02/GHSA-97m3-52wr-xvv2/GHSA-97m3-52wr-xvv2.json
**Updates**
**Comments**
dompdf itself is not vulnerable, it's only one of the depencies.
=> [GHSA-97m3-52wr-xvv2] Dompdf's usage of vulnerable version of phenx/php-svg-lib leads to restriction bypass and potential RCE

advisories/github-reviewed/2023/07/GHSA-m9p2-j4hg-g373/GHSA-m9p2-j4hg-g373.json
**Updates**
**Comments**
Updating the affected range to ">=4.0.0, <4.0.10"
The current affected range is just "<4.0.10", which is not matching the description: 
> This issue affects Apache Cassandra: from 4.0.0 through 4.0.9, from 4.1.0 through 4.1.1.
Also, NVD is showing range should be ">=4.0.0, <4.0.10": https://nvd.nist.gov/vuln/detail/CVE-2023-30601
=> [GHSA-m9p2-j4hg-g373] Apache Cassandra: Privilege escalation when enabling FQL/Audit logs

advisories/github-reviewed/2018/10/GHSA-jx6h-3fjx-cgv5/GHSA-jx6h-3fjx-cgv5.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2018-1305.
=> [GHSA-jx6h-3fjx-cgv5] Apache Tomcat information exposure vulnerability

advisories/github-reviewed/2018/10/GHSA-m59c-jpc8-m2x4/GHSA-m59c-jpc8-m2x4.json
**Updates**
- References
**Comments**
Add some patch links related to CVE-2018-1336.
=> [GHSA-m59c-jpc8-m2x4] In Apache Tomcat there is an improper handing of overflow in the UTF-8 decoder 

advisories/github-reviewed/2022/05/GHSA-678x-xfp4-r92r/GHSA-678x-xfp4-r92r.json
**Updates**
- References
**Comments**
add 3 patches:
https://github.com/apache/geronimo/commit/aa0c2c26dde8930cad924796af7c17a13d236b16
https://github.com/apache/geronimo/commit/67dda0760bb0925ead201ddd5d809ff53686d63f
https://github.com/apache/geronimo/commit/f8a612df7b06729bfd6c826e1a110d4bb40dc1f5.
the msg shows it.
=> [GHSA-678x-xfp4-r92r] Apache Geronimo Application Server CSRF vulnerabilities

advisories/github-reviewed/2022/05/GHSA-j65f-mvgw-prp2/GHSA-j65f-mvgw-prp2.json
**Updates**
- References
**Comments**
add 9 patch commits:
https://github.com/apache/openjpa/commit/87a4452be08b4f97274d0ccfac585ae85841e470
https://github.com/apache/openjpa/commit/521fecd2d9b91c27e9f90d97e5f5479d17239eb8
https://github.com/apache/openjpa/commit/d3c68ad3bb9aa0e4e9abbfdec691abb06df642a5
https://github.com/apache/openjpa/commit/01bc0d257b38743372af91cb88269524634db7d3
https://github.com/apache/openjpa/commit/f4ca597b9a7000a88ad6bbe556283247e9f6bc14
https://github.com/apache/openjpa/commit/b8933dc24b84e7e7430ece56bd645d425dd89f24
https://github.com/apache/openjpa/commit/ad5cd6fb86af8809b367f709b6e041218055de2f
https://github.com/apache/openjpa/commit/4487017fbf57fb7aed4024e0991850bb89fc1c43
https://github.com/apache/openjpa/commit/7f14c7df6b7c7ef42f0671138b9b5dd062fe99aa …
=> [GHSA-j65f-mvgw-prp2] Deserialization of Untrusted Data in Apache OpenJPA

advisories/github-reviewed/2023/11/GHSA-2c7c-3mj9-8fqh/GHSA-2c7c-3mj9-8fqh.json
**Updates**
**Comments**
Version 2 is affected by this, and is fixed in v2.6.2
=> [GHSA-2c7c-3mj9-8fqh] Decryption of malicious PBES2 JWE objects can consume unbounded system resources

advisories/github-reviewed/2022/05/GHSA-vp63-rrcm-9mph/GHSA-vp63-rrcm-9mph.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2013-7315.
=> [GHSA-vp63-rrcm-9mph] Missing XML Validation in Spring Framework

advisories/github-reviewed/2022/05/GHSA-f93f-g33r-8pcp/GHSA-f93f-g33r-8pcp.json
**Updates**
- References
**Comments**
Add one more patch link and source code location related to CVE-2014-0225.
=> [GHSA-f93f-g33r-8pcp] Improper Restriction of XML External Entity Reference in Spring Framework

advisories/github-reviewed/2024/02/GHSA-ccgv-vj62-xf9h/GHSA-ccgv-vj62-xf9h.json
**Updates**
**Comments**
https://spring.io/security/cve-2024-22243
> Affected Spring Products and Versions
> Spring Framework
> - 6.1.0 - 6.1.3
> - 6.0.0 - 6.0.16
> - 5.3.0 - 5.3.31
> - **Older, unsupported versions are also affected**
Versions of the Spring Framework prior to 5.3.0 are also likely to be affected.
=> [GHSA-ccgv-vj62-xf9h] Spring Web vulnerable to Open Redirect or Server Side Request Forgery

advisories/github-reviewed/2024/02/GHSA-8m36-62rw-9mxw/GHSA-8m36-62rw-9mxw.json
**Updates**
- CWEs
**Comments**
As mentioned in report: https://huntr.com/bounties/c1cbc18b-e4ab-4332-ad13-0033f0f976f5, loading /dev/urandom or any other large files may cause a dos on the server by consuming whole memory and crash the process.
=> [GHSA-8m36-62rw-9mxw] mapshaper Path Traversal vulnerability

advisories/github-reviewed/2024/02/GHSA-8h22-8cf7-hq6g/GHSA-8h22-8cf7-hq6g.json
**Updates**
- References
**Comments**
This is a vulnerability in rails activestorage, so affected packages should be registered in activestorage.
The following link has been removed as it is broken.
https://github.com/rubysec/ruby-advisory-db/blob/master/gems/actionpack/CVE-2024-26144.yml
=> [GHSA-8h22-8cf7-hq6g] Rails has possible Sensitive Session Information Leak in Active Storage

advisories/github-reviewed/2024/02/GHSA-9822-6m93-xqf4/GHSA-9822-6m93-xqf4.json
**Updates**
**Comments**
The [patch][2] listed in the [original advisory][1] indicates that the vulnerability is in the actionpack gem, not the rails meta-gem.
[1]: https://discuss.rubyonrails.org/t/possible-xss-vulnerability-in-action-controller/84947
[2]: https://discuss.rubyonrails.org/uploads/short-url/xR0UfuAFkM0JshURTBlFDhVNfnI.patch
=> [GHSA-9822-6m93-xqf4] Rails has possible XSS Vulnerability in Action Controller

advisories/github-reviewed/2024/02/GHSA-jjhx-jhvp-74wq/GHSA-jjhx-jhvp-74wq.json
**Updates**
**Comments**
This is a vulnerability in rails actionpack, so affected packages should be registered in actionpack.
=> [GHSA-jjhx-jhvp-74wq] Rails has possible ReDoS vulnerability in Accept header parsing in Action Dispatch

advisories/github-reviewed/2018/10/GHSA-5q8m-mqmx-pxp9/GHSA-5q8m-mqmx-pxp9.json
**Updates**
- References
**Comments**
Add a patch https://github.com/spring-projects/spring-data-commons/commit/371f6590c509c72f8e600f3d05e110941607fba, of which the commit message claims `DATACMNS-1285 - PropertyPath now limits the depth of its parsing to 1000 segments.`
Add a patch https://github.com/spring-projects/spring-data-commons/commit/3d8576fe4e4e71c23b9e6796b32fd56e51182ee, of which the commit message claims `DATACMNS-1285 - PropertyPath now limits the depth of its parsing to 1000 segments.`
=> [GHSA-5q8m-mqmx-pxp9] Spring Data Commons contain a property path parser vulnerability caused by unlimited resource allocation

advisories/github-reviewed/2018/11/GHSA-rxmr-c9jm-7mm8/GHSA-rxmr-c9jm-7mm8.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/hive/commit/b0a58d245875dc1b3ac58a7cf1a61d3b17805e96, of which the commit message claims `HIVE-18879: Disallow embedded element in UDFXPathUtil needs to work if xercesImpl.jar in classpath (Daniel Dai, reviewed by Thejas Nair)`
=> [GHSA-rxmr-c9jm-7mm8] Exposure of Sensitive Information to an Unauthorized Actor in Apache hive

advisories/github-reviewed/2024/02/GHSA-c8v6-786g-vjx6/GHSA-c8v6-786g-vjx6.json
**Updates**
**Comments**
Developer says it's patched at 1.16.6 https://github.com/nov/json-jwt/issues/120#issuecomment-1976119331
=> [GHSA-c8v6-786g-vjx6] json-jwt allows bypass of identity checks via a sign/encryption confusion attack

advisories/github-reviewed/2018/10/GHSA-3pph-2595-cgfh/GHSA-3pph-2595-cgfh.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/lucene-solr/commit/02c693f3713add1b4891cbaa87127de3a55c10f, of which the commit message claims `SOLR-11971: Don't allow referal to external resources in DataImportHandler's dataConfig request parameter`
Add a patch https://github.com/apache/lucene-solr/commit/dd3be31f7062dcb2f3b2d7f0e89df29e197dee6, of which the commit message claims `SOLR-11971: Don't allow referal to external resources in DataImportHandler's dataConfig request parameter`
Add a patch https://github.com/apache/lucene-solr/commit/739a79338856599084617d44b6a1b424af059aa, of which the commit message claims `SOLR-11971: Don't allow referal to external resources in DataImportHandler's dataConfig request parameter`
=> [GHSA-3pph-2595-cgfh] There is a XML external entity expansion (XXE) vulnerability in Apache Solr 

advisories/github-reviewed/2018/10/GHSA-qh3m-qw6v-qvhg/GHSA-qh3m-qw6v-qvhg.json
**Updates**
- References
**Comments**
Add a patch https://github.com/vert-x3/vertx-web/commit/d814d22ade14bafec47c4447a4ba9bff090f05e, of which the commit message claims `Create safe xml parsers`
Add a patch https://github.com/vert-x3/vertx-web/commit/ac8692c618d6180a9bc012a2ac8dbec821b1a97, of which the commit message claims `Create safe xml parsers
(cherry picked from commit d814d22ade14bafec47c4447a4ba9bff090f05e8)`
=> [GHSA-qh3m-qw6v-qvhg] Moderate severity vulnerability that affects io.vertx:vertx-core

advisories/github-reviewed/2018/11/GHSA-v3vf-2r98-xw8w/GHSA-v3vf-2r98-xw8w.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/syncope/commit/7b168c142b09c3b03e39f1449211e7ddf026a14, of which the commit message claims `Review fields usable for search and orderBy`
Add a patch https://github.com/apache/syncope/commit/44a5ca0fbd357b8b5d81aa9313fb01cca30d8ad, of which the commit message claims `Review fields usable for search and orderBy`
Add a patch https://github.com/apache/syncope/commit/735579b6f987b407049ac1f1da08e675d957c3e, of which the commit message claims `Review fields usable for search and orderBy`
=> [GHSA-v3vf-2r98-xw8w] Exposure of Sensitive Information to an Unauthorized Actor in Apache syncope-cope

advisories/github-reviewed/2018/10/GHSA-h8w4-qv99-f7vj/GHSA-h8w4-qv99-f7vj.json
**Updates**
- References
- Severity
**Comments**
Add a patch https://github.com/spring-projects/spring-security-oauth/commit/623776689fdcc8047f5a908c71f348e1f172a97, of which the commit message claims `Validate authorization request on approval
Fixes gh-1481`
Add a patch https://github.com/spring-projects/spring-security-oauth/commit/f92223afc71687bd3156298054903f50aa71fbf, of which the commit message claims `Validate authorization request on approval
Fixes gh-1481`
"Add a patch https://github.com/spring-projects/spring-security-oauth/commit/ddd65cd9417ae1e4a69e4193a622300db38e2ef, of which the commit message claims `Validate authorization request on approval
Fixes gh-1481`
Add a patch https://github.com/spring-projects/spring-security-oauth/commit/4082ec7ae3d39198a47b5c803ccb20dacefb0b0, …
=> [GHSA-h8w4-qv99-f7vj] High severity vulnerability that affects org.springframework.security.oauth:spring-security-oauth2

advisories/github-reviewed/2018/11/GHSA-qfjv-998w-q48f/GHSA-qfjv-998w-q48f.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/syncope/commit/bdb6a180dcae6f1baaff16619cb906b7292da0d, of which the commit message claims `Ensuring all XML input processing is safe - disable DTD and external entities`
Add a patch https://github.com/apache/syncope/commit/a0f35f45f8ca5c98853ae8477fb2db81a84709a, of which the commit message claims `Ensuring all XML input processing is safe - disable DTD and external entities`
=> [GHSA-qfjv-998w-q48f] High severity vulnerability that affects org.apache.syncope:syncope-core

advisories/github-reviewed/2018/12/GHSA-2xpp-75vr-22vq/GHSA-2xpp-75vr-22vq.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/nifi/commit/dbf259508c2b8e176d8cb837177aaadbf44f0670, of which the commit message claims `NIFI-5258 - Changed addHeader to setHeader which stops X-Frame-Options being added twice to responses. Added unit test.
This closes #2791.
Signed-off-by: Andy LoPresto <alopresto@apache.org>`
=> [GHSA-2xpp-75vr-22vq] Improper Restriction of Rendered UI Layers or Frames in Apache nifif

advisories/github-reviewed/2018/12/GHSA-4qq9-rrq6-48ff/GHSA-4qq9-rrq6-48ff.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/nifi/commit/e62aa0252dfcf34dff0c3a9c51265b1d0f9dfc9f, of which the commit message claims `NIFI-5442 Get X-ProxyContextPath value from request attributes rather than directly from headers.
NIFI-5442 Populate request contextPath attribute during AccessResource before displaying on message-page.jsp.
Refactored shared code from CatchAllFilter to WebUtils.
NIFI-5442 Refactored filter and context path code to shared parent filter and subclass.
NIFI-5442 Removed unnecessary initParams from nifi-web-ui web.xml.
NIFI-5442 Added explicit dispatchers to nifi-web-ui web.xml and removed unnecessary code from AccessResource.
This closes #2908`
=> [GHSA-4qq9-rrq6-48ff] Moderate severity vulnerability that affects org.apache.nifi:nifi

advisories/github-reviewed/2018/12/GHSA-43fp-vwwg-qgv6/GHSA-43fp-vwwg-qgv6.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/nifi/commit/748cf745628dab20b7e71f12b5dcfe6ed0bbf134, of which the commit message claims `NIFI-5628 Added content length check to OkHttpReplicationClient.
Added unit tests.
This closes #3035`
=> [GHSA-43fp-vwwg-qgv6] Apache NiFi Improper Input Validation vulnerability

advisories/github-reviewed/2018/12/GHSA-3jq8-jg75-rqv6/GHSA-3jq8-jg75-rqv6.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/nifi/commit/246c090526143943557b15868db6e8fe3fb30cf6, of which the commit message claims `NIFI-5595 - Added the CORS filter to the templates/upload endpoint using a URL matcher.
Explicitly allow methods GET, HEAD. These are the Spring defaults when the allowedMethods is empty but now it is explicit. This will require other methods like POST etc to be from the same origin (for the template/upload URL).
This closes #3024.
=> [GHSA-3jq8-jg75-rqv6] Cleartext Transmission of Sensitive Information in Apache nifi

advisories/github-reviewed/2022/05/GHSA-m643-2pfv-xwm8/GHSA-m643-2pfv-xwm8.json
**Updates**
- References
**Comments**
Add a patch https://github.com/SonarSource/sonarqube/commit/7b567ba3d15ed7dd0b0bba0330686487e35af85c, of which the commit message claims `SONAR-11305 Return external identity only to sys admin in api/users/search`
=> [GHSA-m643-2pfv-xwm8] Exposure of Sensitive Information to an Unauthorized Actor in SonarSource SonarQube API

advisories/github-reviewed/2018/12/GHSA-rmm5-g63h-m6g9/GHSA-rmm5-g63h-m6g9.json
**Updates**
- References
**Comments**
Add a patch https://github.com/pippo-java/pippo/commit/9f36e5891c0b11f840e1e1561ae96d83ba9ce759, of which the commit message claims `Fix #486`
=> [GHSA-rmm5-g63h-m6g9] Improper Restriction of XML External Entity Reference in pippo-core

advisories/github-reviewed/2022/05/GHSA-x3cr-x949-h5jv/GHSA-x3cr-x949-h5jv.json
**Updates**
- References
**Comments**
Add a patch https://github.com/eclipse/rdf4j/commit/df15a4d7a8f2789c043b27c9eafe1b30316cfa79, of which the commit message claims `Verify that zip file entries don't try to escape the parent dir + test
Signed-off-by: Bart Hanssens <bart.hanssens@bosa.fgov.be>`
=> [GHSA-x3cr-x949-h5jv] RDF4J vulnerable to zip slip

advisories/github-reviewed/2018/12/GHSA-6x48-j4x4-cqw3/GHSA-6x48-j4x4-cqw3.json
**Updates**
- References
**Comments**
add 13 patches commits:
https://github.com/apache/hadoop/commit/cedc28d4ab2a27ba47e15ab2711218d96ec88d2
https://github.com/apache/hadoop/commit/fc4c20fc3469674cb584a4fb98bac7e3c2277c9
https://github.com/apache/hadoop/commit/12258c7cff8d32710fbd8b9088a930e3ce27432
https://github.com/apache/hadoop/commit/45a1c680c276c4501402f7bc4cebcf85a6fbc7f
https://github.com/apache/hadoop/commit/11a425d11a329010d0ff8255ecbcd1eb51b642e
https://github.com/apache/hadoop/commit/eaa2b8035b584dfcf7c79a33484eb2dffd3fdb1
https://github.com/apache/hadoop/commit/e3236a9680709de7a95ffbc11b20e1bdc95a860
https://github.com/apache/hadoop/commit/6d7d192e4799b51931e55217e02baec14d49607
https://github.com/apache/hadoop/commit/6a4ae6f6eeed1392a4828a5721fa1499f65bdde …
=> [GHSA-6x48-j4x4-cqw3] Path Traversal in Hadoop

advisories/github-reviewed/2018/10/GHSA-rc9v-h28f-jcmf/GHSA-rc9v-h28f-jcmf.json
**Updates**
- References
**Comments**
Add five patches :
https://github.com/apache/lucene-solr/commit/6c4e45e28494d4d4d04fb89852d18c86fa3d5f8
https://github.com/apache/lucene-solr/commit/1b760114216fcdfae138a8b37f183a9293c4911
https://github.com/apache/lucene-solr/commit/4ba409e0ff3dc38aad88f7b7ad69a76325272b8
https://github.com/apache/lucene-solr/commit/96f079b4b47eaadff65c7aaf0e5bafe68e30ec3
https://github.com/apache/lucene-solr/commit/6d082d5743dee7e08a86b3f2ef03bc025112512
of which the commit messages claims`SOLR-12316: Do not allow to use absolute URIs for including other files in solrconfig.xml and schema parsing`
=> [GHSA-rc9v-h28f-jcmf] There is a XML external entity expansion (XXE) vulnerability in Apache Solr  config files

advisories/github-reviewed/2022/05/GHSA-25gw-4pcc-45cf/GHSA-25gw-4pcc-45cf.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/batik/commit/f91125b26a6ca2b7a1195f1842360bed03629839, of which the commit message claims `BATIK-1222: Only call DOMImplementation in deserialization
git-svn-id: https://svn.apache.org/repos/asf/xmlgraphics/batik/trunk@1831241 13f79535-47bb-0310-9956-ffa450edef68`
=> [GHSA-25gw-4pcc-45cf] Deserialization of Untrusted Data in Apache Batik

advisories/github-reviewed/2022/05/GHSA-52gq-7j6c-xw6x/GHSA-52gq-7j6c-xw6x.json
**Updates**
- References
**Comments**
Add a patch https://github.com/beobal/cassandra/commit/28ee665b3c0c9238b61a871064f024d54cddcc79, of which the commit message claims `Remove dependencies on JVM internals for JMX support
Patch by Sam Tunnicliffe; reviewed by Jason Brown for CASSANDRA-14173`
=> [GHSA-52gq-7j6c-xw6x] Missing Authentication for Critical Function in Apache Cassandra

advisories/github-reviewed/2018/10/GHSA-j53j-gmr9-h8g3/GHSA-j53j-gmr9-h8g3.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/tika/commit/8a6a9e1344f5b10ebfa1a189dc3c30d0da2b9d4, of which the commit message claims `fix logic in iptc parser`
Add a patch https://github.com/apache/tika/commit/62926cae31a02d4f23d21148435804b96c543cc, of which the commit message claims `fix logic in iptc parser`
=> [GHSA-j53j-gmr9-h8g3] Moderate severity vulnerability that affects org.apache.tika:tika-core

advisories/github-reviewed/2018/10/GHSA-qcjv-wfcg-mmpr/GHSA-qcjv-wfcg-mmpr.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/ignite/commit/82a7b8209fcf56971d12cb10410a38ed632215b, of which the commit message claims `IGNITE-8565 Client marshalling improvements`
Add a patch https://github.com/apache/ignite/commit/bc374f85ca4a5e69572902d2167fe6bedebd40a, of which the commit message claims `IGNITE-8565 Client marshalling improvements`
=> [GHSA-qcjv-wfcg-mmpr] Critical severity vulnerability that affects org.apache.ignite:ignite-core

advisories/github-reviewed/2018/10/GHSA-r86j-2gc6-2cq9/GHSA-r86j-2gc6-2cq9.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/hbase/commit/625d4d002620139f49c8201f95b789b6a715cd4, of which the commit message claims `HBASE-20664 Reduce the broad scope of outToken in ThriftHttpServlet
Signed-off-by: Andrew Purtell <apurtell@apache.org>`
Add a patch https://github.com/apache/hbase/commit/bf25c1cb7221178388baaa58f0b16a408e151a6, of which the commit message claims `HBASE-20664 Reduce the broad scope of outToken in ThriftHttpServlet
Signed-off-by: Andrew Purtell <apurtell@apache.org>`
Add a patch https://github.com/apache/hbase/commit/30e98b4455f971c9cb3c02ac7b2daeebe4ee6f2, of which the commit message claims `HBASE-20664 Reduce the broad scope of outToken in ThriftHttpServlet
Signed-off-by: Andrew Purtell <apurtell@apache.org>`
Add a patch …
=> [GHSA-r86j-2gc6-2cq9] High severity vulnerability that affects org.apache.hbase:hbase-thrift

advisories/github-reviewed/2018/10/GHSA-7px3-6f6g-hxcj/GHSA-7px3-6f6g-hxcj.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/lucene-solr/commit/d1baf6ba593561f39e2da0a71a8440797005b55, of which the commit message claims `SOLR-12450: Don't allow referal to external resources in various config files`
Add a patch https://github.com/apache/lucene-solr/commit/e5407c5a9710247e5f728aae36224a245a51f0b, of which the commit message claims `SOLR-12450: Don't allow referal to external resources in various config files
Conflicts:
solr/CHANGES.txt`
Add a patch https://github.com/apache/lucene-solr/commit/e21d4937e0637c7b7949ac463f331da9a42c07f, of which the commit message claims `SOLR-12450: Don't allow referal to external resources in various config files`
Add a patch https://github.com/apache/lucene-solr/commit/1880d4824e6c5f98170b9a00aad1d437ee2aa1 …
=> [GHSA-7px3-6f6g-hxcj] Moderate severity vulnerability that affects org.apache.solr:solr-core

advisories/github-reviewed/2018/10/GHSA-7xr3-rgwh-pw22/GHSA-7xr3-rgwh-pw22.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/qpid-broker-j/commit/025b48f3193e2b10b1c41d2bc3bcfc9cfc238a27, of which the commit message claims `QPID-8203: [Broker-J][AMQP 0-9] Fix maximum message size check`
=> [GHSA-7xr3-rgwh-pw22] Denial of service vulnerability exists when .NET and .NET Core improperly process XML documents

advisories/github-reviewed/2022/05/GHSA-5c66-6h6g-6q6m/GHSA-5c66-6h6g-6q6m.json
**Updates**
- References
**Comments**
Add two patches.
https://github.com/AsyncHttpClient/async-http-client/commit/3c9152e2c75f7e8b654beec40383748a14c6b51b 's commit message claims `Merge pull request #510 from wsargent/fix-197
Fix for #197 -- use a hostname verifier that does hostname verification`
another patch https://github.com/AsyncHttpClient/async-http-client/commit/a894583921c11c3b01f160ada36a8bb9d5158e9, of which the commit message claims `Use a hostname verifier that does hostname verification, backport #510, close #197`
=> [GHSA-5c66-6h6g-6q6m] Insufficient Verification of Data Authenticity in Async Http Client

advisories/github-reviewed/2022/05/GHSA-45w3-2hvv-pfxq/GHSA-45w3-2hvv-pfxq.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/lucene-solr/commit/7239a57a51ea0f4d05dd330ce5e15e4f72f72747, of which the commit message claims `SOLR-4881: Fix DocumentAnalysisRequestHandler to correctly use EmptyEntityResolver to prevent loading of external entities like UpdateRequestHandler does
git-svn-id: https://svn.apache.org/repos/asf/lucene/dev/trunk@1487976 13f79535-47bb-0310-9956-ffa450edef68`
=> [GHSA-45w3-2hvv-pfxq] XML Injection in Apache Solr

advisories/github-reviewed/2022/05/GHSA-998j-j6v9-5846/GHSA-998j-j6v9-5846.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/lucene-solr/commit/f230486ce6707762c1a6e81655d0fac52887906d, of which the commit message claims `SOLR-3895, SOLR-3614: XML and XSLT UpdateRequestHandler should not try to resolve external entities; fix XML parsing in XPathEntityProcessor to correctly expand named entities, but ignore external entities
git-svn-id: https://svn.apache.org/repos/asf/lucene/dev/trunk@1390921 13f79535-47bb-0310-9956-ffa450edef68`
=> [GHSA-998j-j6v9-5846] Apache Solr UpdateRequestHandler for XML resolves XML External Entities

advisories/github-reviewed/2022/05/GHSA-j8qw-mwmv-28cg/GHSA-j8qw-mwmv-28cg.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/lucene-solr/commit/da34b18cb3092df4972e2b6fa5178d1059923910, of which the commit message claims `SOLR-4882: Restrict SolrResourceLoader to only allow access to resource files below the instance dir
git-svn-id: https://svn.apache.org/repos/asf/lucene/dev/trunk@1525246 13f79535-47bb-0310-9956-ffa450edef68`
=> [GHSA-j8qw-mwmv-28cg] Improper Limitation of a Pathname to a Restricted Directory in Apache Solr

advisories/github-reviewed/2022/05/GHSA-4p4w-6h54-g885/GHSA-4p4w-6h54-g885.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/santuario-java/commit/a09b9042f7759d094f2d49f40fc7bcf145164b25, of which the commit message claims `Disallow doc type declarations when secure validation is enabled
Conflicts:src/main/java/org/apache/xml/security/c14n/Canonicalizer.java
git-svn-id: https://svn.apache.org/repos/asf/santuario/xml-security-java/branches/1.5.x-fixes@1537956 13f79535-47bb-0310-9956-ffa450edef68`
=> [GHSA-4p4w-6h54-g885] Improper Input Validation in Apache Santuario XML Security

advisories/github-reviewed/2022/05/GHSA-p4mx-p49m-8rw4/GHSA-p4mx-p49m-8rw4.json
**Updates**
- References
**Comments**
Add a patch https://github.com/javamelody/javamelody/commit/aacbc46151ff4ac1ca34ce0899c2a6113071c66e, of which the commit message claims `fix for issue 346: XSS through X-Forwarded-For header spoofing
=> [GHSA-p4mx-p49m-8rw4] Improper Neutralization of Input During Web Page Generation in JavaMelody

advisories/github-reviewed/2022/05/GHSA-pqwh-44jj-p5rm/GHSA-pqwh-44jj-p5rm.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/httpcomponents-client/commit/08140864e3e4c0994e094c4cf0507932baf6a66, of which the commit message claims `Ensure X509HostnameVerifier is never null
git-svn-id: https://svn.apache.org/repos/asf/httpcomponents/httpclient/trunk@1528614 13f79535-47bb-0310-9956-ffa450edef68`
=> [GHSA-pqwh-44jj-p5rm] Hostname verification in Apache HttpClient 4.3 was disabled by default

advisories/github-reviewed/2022/05/GHSA-92j2-5r7p-6hjw/GHSA-92j2-5r7p-6hjw.json
**Updates**
- References
**Comments**
add three patch commits:
https://github.com/restlet/restlet-framework-java/commit/c3015e4783c2a36e7528aa611c911b7d8c4ec5b
https://github.com/restlet/restlet-framework-java/commit/b85c2ef182c69c5e2e21df008ccb249ccf80c7b
https://github.com/restlet/restlet-framework-java/commit/12cc79b3953c7bd276e9f1cae2fbfdb9c1a6f07
The commit msg can prove their intention:
`Fixed issue #774 - Removed default support of JavaBeans XML-serialization. Reported by David Jorm, Dinis Cruz, Abraham Kang and Alvaro Munoz.`
`Fixed issue #774 - Removed default support of JavaBeans XML-serialization. Reported by David Jorm, Dinis Cruz, Abraham Kang and alavaro Munoz.`
and
`Fixed issue #774 - Removed default support of JavaBeans XML-serialization. Reported by …
=> [GHSA-92j2-5r7p-6hjw] Restlet is vulnerable to Arbitrary Java Code Execution via crafted XML

advisories/github-reviewed/2022/05/GHSA-7j4h-8wpf-rqfh/GHSA-7j4h-8wpf-rqfh.json
**Updates**
- References
**Comments**
Add two patches:
https://github.com/apache/xerces2-j/commit/266e837852e0f0e3c8c1ad572b6fc4dbb4ded17
https://github.com/apache/xerces2-j/commit/628cbc7142ef9acfb61b8e571aab63504235849
of which the commit messages showed the intention.
=> [GHSA-7j4h-8wpf-rqfh] Missing XML Validation in Apache Xerces2

advisories/github-reviewed/2022/05/GHSA-qx6h-9567-5fqw/GHSA-qx6h-9567-5fqw.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/commons-fileupload/commit/163a6061fbc077d4b6e4787d26857c2baba495d1, of which the commit message claims `When deserializing DiskFileItems ensure that the repository location, if any, is a valid one.
Patch provided by Arun Babu Neelicattu.
git-svn-id: https://svn.apache.org/repos/asf/commons/proper/fileupload/trunk@1507048 13f79535-47bb-0310-9956-ffa450edef68`
=> [GHSA-qx6h-9567-5fqw] Arbitrary file write in Apache Commons Fileupload

advisories/github-reviewed/2022/05/GHSA-r237-w2w6-jq3p/GHSA-r237-w2w6-jq3p.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/santuario-java/commit/8e8f8bf92a43608d7d5f9e357fae19244454a61f, of which the commit message claims `Don't allow non-standard c14n method
git-svn-id: https://svn.apache.org/repos/asf/santuario/xml-security-java/branches/1.5.x-fixes@1493772 13f79535-47bb-0310-9956-ffa450edef68`
=> [GHSA-r237-w2w6-jq3p] Inefficient Algorithmic Complexity in Apache Santuario XML Security

advisories/github-reviewed/2022/05/GHSA-v64w-96p6-fx7w/GHSA-v64w-96p6-fx7w.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/geronimo/commit/ee031c5e62b0d358250d06c2aa6722518579a6c5, of which the commit message claims `set better classloader for jmx
git-svn-id: https://svn.apache.org/repos/asf/geronimo/server/branches/3.0@1458113 13f79535-47bb-0310-9956-ffa450edef68`
=> [GHSA-v64w-96p6-fx7w] Apache Geronimo JMX Remoting functionality allows remote code execution in 3.x before v3.0.1

advisories/github-reviewed/2018/10/GHSA-2x83-r56g-cv47/GHSA-2x83-r56g-cv47.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/httpcomponents-client/commit/6e14fc146a66e0f3eb362f45f95d1a58ee18886a, of which the commit message claims `Fixed CN extraction from DN of X500 principal
git-svn-id: https://svn.apache.org/repos/asf/httpcomponents/httpclient/trunk@1411702 13f79535-47bb-0310-9956-ffa450edef68`
=> [GHSA-2x83-r56g-cv47] High severity vulnerability that affects org.apache.httpcomponents:httpclient

advisories/github-reviewed/2022/05/GHSA-gw85-4gmf-m7rh/GHSA-gw85-4gmf-m7rh.json
**Updates**
- References
**Comments**
"Add a patch https://github.com/apache/httpcomponents-client/commit/a572756592c969affd0ce87885724e74839176fb, of which the commit message claims `HTTPCLIENT-1061: Proxy-Authorization header gets sent to the target host when tunneling requests through a proxy that requires authentication
git-svn-id: https://svn.apache.org/repos/asf/httpcomponents/httpclient/trunk@1074473 13f79535-47bb-0310-9956-ffa450edef68`"
=> [GHSA-gw85-4gmf-m7rh] Exposure of Sensitive Information to an Unauthorized Actor in Apache HttpClient

advisories/github-reviewed/2022/05/GHSA-c78g-qwpw-2jgv/GHSA-c78g-qwpw-2jgv.json
**Updates**
- References
**Comments**
Add source code location and patch links related to CVE-2010-4172.
=> [GHSA-c78g-qwpw-2jgv] Improper Neutralization of Input During Web Page Generation  in Apache Tomcat

advisories/github-reviewed/2018/12/GHSA-xx68-jfcg-xmmf/GHSA-xx68-jfcg-xmmf.json
**Updates**
- References
**Comments**
add a patch commit https://github.com/apache/commons-fileupload/commit/c61ff05b3241cb14d989b67209e57aa71540417a for apache/commons-fileupload, the commit msg shows it.
=> [GHSA-xx68-jfcg-xmmf] Commons FileUpload Denial of service vulnerability

advisories/github-reviewed/2022/05/GHSA-hmvj-gc9q-mg9p/GHSA-hmvj-gc9q-mg9p.json
**Updates**
- References
**Comments**
add a patch commit https://github.com/apache/struts/commit/9cad25f258bb2629d263f828574d2671366c238d. the code changes matches the recommended remediation measure in https://www.sec-consult.com/files/20120104-0_Apache_Struts2_Multiple_Critical_Vulnerabilities.txt
=> [GHSA-hmvj-gc9q-mg9p] Apache Struts's DebuggingInterceptor component allows remote code execution in developer mode

advisories/github-reviewed/2023/11/GHSA-j24h-xcpc-9jw8/GHSA-j24h-xcpc-9jw8.json
**Updates**
**Comments**
The previous entries for this CVE were incorrect, referencing version 4.29 of the Eclipse IDE project and applying them to artifacts who don't even have a version matching that release.  See additional conversation on https://github.com/github/advisory-database/pull/3785
=> [GHSA-j24h-xcpc-9jw8] Eclipse IDE XXE in eclipse.platform

advisories/github-reviewed/2023/10/GHSA-qppj-fm5r-hxr3/GHSA-qppj-fm5r-hxr3.json
**Updates**
**Comments**
Adds Eclipse Jetty to affected products based on release announcement: https://www.eclipse.org/lists/jetty-announce/msg00181.html
=> [GHSA-qppj-fm5r-hxr3] HTTP/2 Stream Cancellation Attack

advisories/github-reviewed/2024/02/GHSA-vr64-r9qj-h27f/GHSA-vr64-r9qj-h27f.json
**Updates**
- Description
- References
- Summary
**Comments**
I am a member of the Clojure core team working on addressing this issue. I have provided better information for Clojure users in the description about the combination of factors leading to this, the root cause, how to avoid it, and the affected versions.
=> [GHSA-vr64-r9qj-h27f] Clojure Denial of Service vulnerability

advisories/github-reviewed/2018/10/GHSA-3rmv-2pg5-xvqj/GHSA-3rmv-2pg5-xvqj.json
**Updates**
- References
**Comments**
Add a patch https://github.com/spring-projects/spring-framework/commit/d3acf45ea4db51fa5c4cbd0bc0e7b6d9ef805e6, of which the commit message claims `Modify SpEL code gen to take account of null safe refs
With this change the code generation for method and property
references is modified to include branching logic in the
case of null safe dereferencing (?.). This is complicated
by the possible usage of primitives on the left hand side
of the dereference. To cope with this case primitives are
promoted to boxed types when this situation occurs enabling
null to be passed as a possible result.
Issue: SPR-16489`
Add a patch https://github.com/spring-projects/spring-framework/commit/1db7e02de3eb0c011ee6681f5a12eb9d166fea8, of which the commit message claims …
=> [GHSA-3rmv-2pg5-xvqj] Improperly Implemented Security Check for Standard in org.springframework:spring-core

advisories/github-reviewed/2022/05/GHSA-86p9-x5pw-94qx/GHSA-86p9-x5pw-94qx.json
**Updates**
**Comments**
Please see itext story at: 
https://stackoverflow.com/questions/41820698/what-is-the-difference-between-itext-and-itextpdf
It is the same product with changed mname and group.
=> [GHSA-86p9-x5pw-94qx] Improper Restriction of XML External Entity Reference in  iText

advisories/github-reviewed/2024/03/GHSA-65x7-c272-7g7r/GHSA-65x7-c272-7g7r.json
**Updates**
- Description
**Comments**
This has been also fixed for `2.1.*` and the fix has been published in 2.1.7
See https://github.com/SixLabors/ImageSharp/pull/2688
The GH Advisory on the ImageSharp repository has been updated accordingly:
https://github.com/SixLabors/ImageSharp/security/advisories/GHSA-65x7-c272-7g7r
@KateCatlin will this update be also published on https://nvd.nist.gov/vuln/detail/CVE-2024-27929?
=> [GHSA-65x7-c272-7g7r] Use After Free in SixLabors.ImageSharp

advisories/github-reviewed/2021/05/GHSA-hhx9-p69v-cx2j/GHSA-hhx9-p69v-cx2j.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-13927 which fixed in multi-branch.
=> [GHSA-hhx9-p69v-cx2j] Authentication bypass in Apache Airflow

advisories/github-reviewed/2021/04/GHSA-ffw3-6mp6-jmvj/GHSA-ffw3-6mp6-jmvj.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2021-26559 which fixed in multi-branch.
=> [GHSA-ffw3-6mp6-jmvj] Improper Access Control in Apache Airflow

advisories/github-reviewed/2022/11/GHSA-7wqf-h36w-47mc/GHSA-7wqf-h36w-47mc.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2022-38649.
=> [GHSA-7wqf-h36w-47mc] OS Command Injection in Apache Airflow

advisories/github-reviewed/2022/09/GHSA-5rp4-749p-vx26/GHSA-5rp4-749p-vx26.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2022-40604 which fixed in multi-branch.
=> [GHSA-5rp4-749p-vx26] Apache Airflow vulnerable to Use of Externally-Controlled Format String

advisories/github-reviewed/2022/10/GHSA-3q8r-f3pj-3gc4/GHSA-3q8r-f3pj-3gc4.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2022-41672 which fixed in multi-branch.
=> [GHSA-3q8r-f3pj-3gc4] Apache Airflow may allow authenticated users who have been deactivated to continue using the UI or API

advisories/github-reviewed/2022/11/GHSA-rg94-84xj-7gq3/GHSA-rg94-84xj-7gq3.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2022-45402 which fixed in multi-branch.
=> [GHSA-rg94-84xj-7gq3] Apache Airflow Contains Open Redirect

advisories/github-reviewed/2023/07/GHSA-ggwr-4vr8-g7wv/GHSA-ggwr-4vr8-g7wv.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2023-22887 which fixed in multi-branch.
=> [GHSA-ggwr-4vr8-g7wv] Apache Airflow Path Traversal vulnerability

advisories/github-reviewed/2023/07/GHSA-2h84-3crq-vgfj/GHSA-2h84-3crq-vgfj.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2023-35908 which fixed in multi-branch.
=> [GHSA-2h84-3crq-vgfj] Apache Airflow Incorrect Authorization vulnerability

advisories/github-reviewed/2023/08/GHSA-5f35-pq34-c87q/GHSA-5f35-pq34-c87q.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2023-39441 which fixed in multi-branch.
=> [GHSA-5f35-pq34-c87q] Apache Airflow missing Certificate Validation

advisories/github-reviewed/2023/09/GHSA-wpg8-mf6h-gm92/GHSA-wpg8-mf6h-gm92.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2023-40611 which fixed in multi-branch.
=> [GHSA-wpg8-mf6h-gm92] Apache Airflow Incorrect Authorization vulnerability

advisories/github-reviewed/2023/10/GHSA-cgx2-rrmr-jx43/GHSA-cgx2-rrmr-jx43.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2023-40611 which fixed in multi-branch.
=> [GHSA-cgx2-rrmr-jx43] Apache Airflow vulnerable to sensitive information exposure when users list warnings for all DAGs

advisories/github-reviewed/2023/10/GHSA-fpxx-xv4c-gxqp/GHSA-fpxx-xv4c-gxqp.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2023-45348 which fixed in multi-branch.
=> [GHSA-fpxx-xv4c-gxqp] Apache Airflow vulnerable to sensitive information exposure when expose-config is set to non-sensitive-only

advisories/github-reviewed/2023/10/GHSA-cqpc-x2c6-2gmf/GHSA-cqpc-x2c6-2gmf.json
**Updates**
**Comments**
The war file is an artifact of the project and includes/embeds the vulnerable library and actually provides the WMS endpoint.
When used as a dependency in eg. Maven War overlays the .war dependency is not flagged by tooling such as Dependabot because the war file is not marked as vulnerable, while it is.
=> [GHSA-cqpc-x2c6-2gmf] Unsecured WMS dynamic styling sld=<url> parameter affords blind unauthenticated SSRF

advisories/github-reviewed/2018/10/GHSA-g8hw-794c-4j9g/GHSA-g8hw-794c-4j9g.json
**Updates**
- References
**Comments**
Add 7patch commits, of all which the commit messages claim `Backport clean duplicate separators in resource URLs
Issue: SPR-16616`:
https://github.com/spring-projects/spring-framework/commit/91b803a2310344d925e5d4b1709bbcea9037554
https://github.com/spring-projects/spring-framework/commit/f59ea610dfcf55cd0b42f6dd76a9b3dab0218aa
https://github.com/spring-projects/spring-framework/commit/b9ebdaaf3710db473a2e1fec8641c316483a22a
https://github.com/spring-projects/spring-framework/commit/98ad23bef8e2e04143f8f5b201380543a8d8c0c
https://github.com/spring-projects/spring-framework/commit/0e28bee0f155b9bf240b4bafc4646e4810cb23f
https://github.com/spring-projects/spring-framework/commit/13356a7ee2240f740737c5c83bdccdacc30603a …
=> [GHSA-g8hw-794c-4j9g] Path Traversal in org.springframework:spring-core

advisories/github-reviewed/2022/05/GHSA-5h2q-4hrp-v9rr/GHSA-5h2q-4hrp-v9rr.json
**Updates**
- References
**Comments**
Add more patch links related to CVE-2012-3444 which fixed in multi-branch.
=> [GHSA-5h2q-4hrp-v9rr] Django vulnerable to Improper Restriction of Operations within the Bounds of a Memory Buffer

advisories/github-reviewed/2022/05/GHSA-q7q2-qf2q-rw3w/GHSA-q7q2-qf2q-rw3w.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2014-1418 which fixed in multi-branch.
=> [GHSA-q7q2-qf2q-rw3w] Django Vulnerable to Cache Poisoning

advisories/github-reviewed/2022/05/GHSA-q5qw-4364-5hhm/GHSA-q5qw-4364-5hhm.json
**Updates**
- References
**Comments**
Add more patch links related to CVE-2015-5144 which fixed in multi-branch.
=> [GHSA-q5qw-4364-5hhm] Django Vulnerable to HTTP Response Splitting Attack

advisories/github-reviewed/2024/02/GHSA-vr64-r9qj-h27f/GHSA-vr64-r9qj-h27f.json
**Updates**
- Description
**Comments**
This issue has been fixed in 1.11.2 and 1.12.0-alpha9.
=> [GHSA-vr64-r9qj-h27f] Reading specially crafted serializable objects from an untrusted source may cause an infinite loop and denial of service

advisories/github-reviewed/2024/03/GHSA-rj98-crf4-g69w/GHSA-rj98-crf4-g69w.json
**Updates**
- CVSS
- Description
- References
- Severity
**Comments**
The full advisory for the vulnerability is now public:
https://www.shielder.com/advisories/pgadmin-path-traversal_leads_to_unsafe_deserialization_and_rce/
=> [GHSA-rj98-crf4-g69w] pgAdmin 4 vulnerable to Unsafe Deserialization and Remote Code Execution by an Authenticated user

advisories/github-reviewed/2019/06/GHSA-q4hg-rmq2-52q9/GHSA-q4hg-rmq2-52q9.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2019-10072 which fixed in multi-branch.
In https://tomcat.apache.org/security-8.html shows the patch and the other two related to other branch fix.
=> [GHSA-q4hg-rmq2-52q9] Improper Locking in Apache Tomcat

advisories/github-reviewed/2021/08/GHSA-4vww-mc66-62m6/GHSA-4vww-mc66-62m6.json
**Updates**
- References
**Comments**
Add patch links and source code location related to CVE-2021-33037 which fixed in multi-branch.
https://tomcat.apache.org/security-8.html shows three patch links related to one branch.
=> [GHSA-4vww-mc66-62m6] HTTP Request Smuggling in Apache Tomcat

advisories/github-reviewed/2022/02/GHSA-vvw4-rfwf-p6hx/GHSA-vvw4-rfwf-p6hx.json
**Updates**
- References
**Comments**
Add two more patch links related to CVE-2020-17527 which fixed in other branches.
https://tomcat.apache.org/security-10.html shows that.
=> [GHSA-vvw4-rfwf-p6hx] Exposure of Sensitive Information to an Unauthorized Actor in Apache Tomcat

advisories/github-reviewed/2021/05/GHSA-2rvv-w9r2-rg7m/GHSA-2rvv-w9r2-rg7m.json
**Updates**
- References
**Comments**
Add source code location and patch links related to CVE-2021-24122 which fixed in multi-branches.
https://tomcat.apache.org/security-10.html shows the patch in 10.x branch.
=> [GHSA-2rvv-w9r2-rg7m] Information Disclosure in Apache Tomcat

advisories/github-reviewed/2021/10/GHSA-wph7-x527-w3h5/GHSA-wph7-x527-w3h5.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2021-43240 which fixed in multi-branches.
https://tomcat.apache.org/security-10.html shows patch in 10.x branch.
=> [GHSA-wph7-x527-w3h5] Missing Release of Resource after Effective Lifetime in Apache Tomcat

advisories/github-reviewed/2022/09/GHSA-jx7c-7mj5-9438/GHSA-jx7c-7mj5-9438.json
**Updates**
- References
**Comments**
Add source code links and patch links related to CVE-2021-43980 which fixed in multi-branches
https://tomcat.apache.org/security-10.html shows patch in 10.X branch
=> [GHSA-jx7c-7mj5-9438] Apache Tomcat Race Condition vulnerability

advisories/github-reviewed/2022/11/GHSA-p22x-g9px-3945/GHSA-p22x-g9px-3945.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2022-42252 which fixed in multi-branches.
In https://tomcat.apache.org/security-10.html shows patch in two branches.
=> [GHSA-p22x-g9px-3945] Apache Tomcat may reject request containing invalid Content-Length header

advisories/github-reviewed/2023/02/GHSA-hfrx-6qgj-fp6c/GHSA-hfrx-6qgj-fp6c.json
**Updates**
- References
**Comments**
The CVE-2023-24998 also affect Apache Tomcat shows in https://tomcat.apache.org/security-10.html.
So I add patch links in Tomcat about this vulnerability.
=> [GHSA-hfrx-6qgj-fp6c] Apache Commons FileUpload denial of service vulnerability

advisories/github-reviewed/2023/06/GHSA-mppv-79ch-vw6q/GHSA-mppv-79ch-vw6q.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2023-34981 which fixed in multi-branches.
https://tomcat.apache.org/security-10.html shows patch in two branches.
=> [GHSA-mppv-79ch-vw6q] Apache Tomcat vulnerable to information leak

advisories/github-reviewed/2022/05/GHSA-qr42-82qj-mw65/GHSA-qr42-82qj-mw65.json
**Updates**
**Comments**
Add source code location related to CVE-2019-10401.
=> [GHSA-qr42-82qj-mw65] Improper Limitation of a Pathname to a Restricted Directory in Jenkins

advisories/github-reviewed/2023/09/GHSA-279f-qwgh-h5mp/GHSA-279f-qwgh-h5mp.json
**Updates**
- References
**Comments**
Add source code location and patch link related to CVE-2023-43494.
In https://www.jenkins.io/security/advisory/2023-09-20/#SECURITY-3261 shows it is related to SECURITY-3261.
=> [GHSA-279f-qwgh-h5mp] Jenkins does not exclude sensitive build variables from search

advisories/github-reviewed/2024/01/GHSA-6f9g-cxwr-q5jr/GHSA-6f9g-cxwr-q5jr.json
**Updates**
- Description
- References
**Comments**
Add patch link and source code location related to CVE-2024-23897.
In https://www.jenkins.io/security/advisory/2024-01-24/#SECURITY-3314 shows it is related to SECURITY-3314.
=> [GHSA-6f9g-cxwr-q5jr] Arbitrary file read vulnerability through the Jenkins CLI can lead to RCE

advisories/github-reviewed/2022/05/GHSA-x3p3-929j-pq66/GHSA-x3p3-929j-pq66.json
**Updates**
- References
**Comments**
Add patch links and source code location related to CVE-2015-7536.
In https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2015-12-09 shows CVE-2015-7536 is related to SECURITY-95.
=> [GHSA-x3p3-929j-pq66] Improper Neutralization of Input During Web Page Generation in Jenkins

advisories/github-reviewed/2022/06/GHSA-62wf-24c4-8r76/GHSA-62wf-24c4-8r76.json
**Updates**
- References
**Comments**
Add patch link and source code location related to CVE-2022-34170.
=> [GHSA-62wf-24c4-8r76] Cross-site Scripting vulnerability in Jenkins

advisories/github-reviewed/2023/11/GHSA-v94h-hvhg-mf9h/GHSA-v94h-hvhg-mf9h.json
**Updates**
- References
**Comments**
The patch is in https://github.com/spring-projects/spring-framework/compare/v6.0.13...v6.0.14.
https://spring.io/security/cve-2023-34053 shows the CVE is related to micrometer-core and Spring MVC or Spring WebFlux, it is a  denial-of-service (DoS). 
The patch I added is related to these and the https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-6091650 also shows that.
=> [GHSA-v94h-hvhg-mf9h] Spring Framework vulnerable to denial of service

advisories/github-reviewed/2023/04/GHSA-wxqc-pxw9-g2p8/GHSA-wxqc-pxw9-g2p8.json
**Updates**
- References
**Comments**
Add two more patch related to CVE-2023-20863 which fixed in multi-branches.
=> [GHSA-wxqc-pxw9-g2p8] Spring Framework vulnerable to denial of service

advisories/github-reviewed/2023/03/GHSA-564r-hj7v-mcr5/GHSA-564r-hj7v-mcr5.json
**Updates**
- References
**Comments**
Add two more patches related to CVE-2023-20861 which fixed in multi-branches.
=> [GHSA-564r-hj7v-mcr5] Spring Framework vulnerable to denial of service via specially crafted SpEL expression

advisories/github-reviewed/2023/03/GHSA-7phw-cxx7-q9vq/GHSA-7phw-cxx7-q9vq.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2023-20860.
=> [GHSA-7phw-cxx7-q9vq] Spring Framework is vulnerable to security bypass via mvcRequestMatcher pattern mismatch

advisories/github-reviewed/2020/01/GHSA-8wx2-9q48-vm9r/GHSA-8wx2-9q48-vm9r.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2020-5398.
=> [GHSA-8wx2-9q48-vm9r] RFD attack via Content-Disposition header sourced from request input by Spring MVC or Spring WebFlux Application

advisories/github-reviewed/2018/12/GHSA-27xw-p8v6-9jjr/GHSA-27xw-p8v6-9jjr.json
**Updates**
- References
**Comments**
Add a patch https://github.com/spring-projects/spring-security/commit/c70b65c5df0e170a2d34d812b83db0b7bc71ea25, of which the commit message claims `Favor URL.toExternalForm
Converts URLs to Strings before comparing them. Uses toString(),
which delegates to toExternalForm().
Fixes: gh-6073`
=> [GHSA-27xw-p8v6-9jjr] Spring Security vulnerable to Authorization Bypass

advisories/github-reviewed/2018/10/GHSA-cxrj-66c5-9fmh/GHSA-cxrj-66c5-9fmh.json
**Updates**
- References
**Comments**
Add a patch https://github.com/spring-projects/spring-security/commit/7b8fa90d96aaf751a3256fa755d5f17e081c20f, of which the commit message claims `Add accessDeniedHandler method to ExceptionHandlingSpec
This allows to configure accessDeniedHandler in ExceptionTranslationWebFilter through ServerHttpSecurity.
Issue: gh-5257`
=> [GHSA-cxrj-66c5-9fmh] Spring Framework when used in combination with any versions of Spring Security contains an authorization bypass

advisories/github-reviewed/2022/05/GHSA-hxqq-w4mr-mc62/GHSA-hxqq-w4mr-mc62.json
**Updates**
- References
**Comments**
add patch commit https://github.com/apache/struts/commit/9cad25f258bb2629d263f828574d2671366c238d. the code changes matches the solution in this link: https://web.archive.org/web/20120612142634/https://sec-consult.com/files/20120104-0_Apache_Struts2_Multiple_Critical_Vulnerabilities.txt, as shown in current ref links.
=> [GHSA-hxqq-w4mr-mc62] Apache Struts's ParameterInterceptor component does not prevent access to public constructors

advisories/github-reviewed/2023/11/GHSA-53v4-42fg-g287/GHSA-53v4-42fg-g287.json
**Updates**
- References
**Comments**
The https://issues.apache.org/jira/browse/AMQ-9201 shows it fixed in four branches.
So I add three other branch patches link.
=> [GHSA-53v4-42fg-g287] Apache ActiveMQ Deserialization of Untrusted Data vulnerability

advisories/github-reviewed/2021/06/GHSA-9mgm-gcq8-86wq/GHSA-9mgm-gcq8-86wq.json
**Updates**
- References
**Comments**
The https://activemq.apache.org/security-advisories.data/CVE-2021-26117-announcement.txt shows it is related to AMQ-8035.
And https://issues.apache.org/jira/browse/AMQ-8035 shows it is fixed in three branches.
So I add three patches and source code location.
=> [GHSA-9mgm-gcq8-86wq] Improper Authentication in Apache ActiveMQ and Apache Artemis

advisories/github-reviewed/2020/05/GHSA-cc94-3v9c-7rm8/GHSA-cc94-3v9c-7rm8.json
**Updates**
- References
**Comments**
The https://issues.apache.org/jira/browse/AMQ-7231 shows this CVE is related to AMQ-7231 and it is fixed in three branches.
So I add these patch links related to CVE-2020-1941.
=> [GHSA-cc94-3v9c-7rm8] Apache ActiveMQ webconsole admin GUI is open to XSS

advisories/github-reviewed/2022/06/GHSA-jqwc-c49r-4w2x/GHSA-jqwc-c49r-4w2x.json
**Updates**
**Comments**
> We have released Wasmtime 0.38.1 and cranelift-codegen (and other associated cranelift crates) 0.85.1 which contain the corrected implementations of these two instructions in Cranelift.
Reading the quoted part, I think that anything less than 0.85.1 is an affected version, but is the current version less than 0.85.0 correct?
=> [GHSA-jqwc-c49r-4w2x] Miscompilation of `i8x16.swizzle` and `select` with v128 inputs

advisories/github-reviewed/2024/03/GHSA-5fxj-whcv-crrc/GHSA-5fxj-whcv-crrc.json
**Updates**
- Description
- References
**Comments**
typo cause an incorrect identifier which doesn't exist on package manager so updating correct identifier.
updated typo mistake in package name (Runtime.Runtime -> Runtime)  
updated typo mistake in references (Runtime.Runtime -> Runtime)
added fix commit for respective branches 7.x and 8.x.
=> [GHSA-5fxj-whcv-crrc] Microsoft Security Advisory CVE-2024-21392: .NET Denial of Service Vulnerability

advisories/github-reviewed/2022/02/GHSA-66gw-ch5v-74v8/GHSA-66gw-ch5v-74v8.json
**Updates**
- References
**Comments**
The CVE is fixed in 5.16.1, so I get https://github.com/apache/activemq/compare/activemq-5.16.0...activemq-5.16.1. All these commits only https://github.com/apache/activemq/commit/177eb71c52069712bcc9fe14c70e079cc2671a80 fixed message.jsp.
=> [GHSA-66gw-ch5v-74v8] Cross-site scripting (XSS) in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-383p-xqxx-rrmp/GHSA-383p-xqxx-rrmp.json
**Updates**
- Summary
**Comments**
Vulnerability requires a combination of ognl:ognl < 3.0.12 and Apache Struts >= 2.0.0 through <= 2.3.24.1.
As documented by the official security bulletin at https://cwiki.apache.org/confluence/display/WW/S2-034, the recommended fix is to upgrade ognl:ognl to 3.0.12 or newer. The GitHub advisory listing was missing the impact to the ognl:ognl dependency and recommended remediation.
I also suggest the title be changed from "Improper Input Validation" to "Denial of Service" which better represents the CVE and impact.
=> [GHSA-383p-xqxx-rrmp] Improper Input Validation in Apache Struts

advisories/github-reviewed/2022/05/GHSA-3832-9276-x7gf/GHSA-3832-9276-x7gf.json
**Updates**
**Comments**
This vulnerability was pointing to the wrong package name. Version 3.x of Apache HTTP Components HTTP Client used a Maven package name of "commons-httpclient:commons-httpclient". Version 4.x used "org.apache.httpcomponents:httpclient", which this advisory was incorrectly pointing at.
=> [GHSA-3832-9276-x7gf] Improper Certificate Validation in apache HttpClient

advisories/github-reviewed/2022/02/GHSA-xgrx-xpv2-6vp4/GHSA-xgrx-xpv2-6vp4.json
**Updates**
- References
**Comments**
The NVD shows this CVE is related to LocateRegistry.createRegistry(). 
https://github.com/apache/activemq/commit/58382283330f7c7b110c7afd8ef4ca2648786532 fixed this CVE.
=> [GHSA-xgrx-xpv2-6vp4] Improper Authentication in Apache ActiveMQ

advisories/github-reviewed/2022/02/GHSA-wqfh-9m4g-7x6x/GHSA-wqfh-9m4g-7x6x.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-11998 which fixed in multi-branches and affected 'JMX re-bind'.
=> [GHSA-wqfh-9m4g-7x6x] Remote code execution in Apache ActiveMQ

advisories/github-reviewed/2023/09/GHSA-rmqp-9w4c-gc7w/GHSA-rmqp-9w4c-gc7w.json
**Updates**
**Comments**
Apache Axis is published to Maven Central with both the "axis" and "org.apache.axis" group ids.
=> [GHSA-rmqp-9w4c-gc7w] Apache Axis 1.x (EOL) may allow RCE when untrusted input is passed to getService

advisories/github-reviewed/2024/01/GHSA-hr2c-p8rh-238h/GHSA-hr2c-p8rh-238h.json
**Updates**
**Comments**
Apache Axis is published with both the "org.apache.axis" and "axis" group ids in Maven Central.
=> [GHSA-hr2c-p8rh-238h] Apache Axis Improper Input Validation vulnerability

advisories/github-reviewed/2019/05/GHSA-h9gj-rqrw-x4fq/GHSA-h9gj-rqrw-x4fq.json
**Updates**
**Comments**
Apache Axis is published with both the "org.apache.axis" and "axis" group ids in Maven Central.
=> [GHSA-h9gj-rqrw-x4fq] Server Side Request Forgery in Apache Axis

advisories/github-reviewed/2021/04/GHSA-72m5-fvvv-55m6/GHSA-72m5-fvvv-55m6.json
**Updates**
**Comments**
Bouncy Castle is released via multiple different JAR files, published under a variety of different Maven package names. Some of the packages were missed in this advisory.
=> [GHSA-72m5-fvvv-55m6] Observable Differences in Behavior to Error Inputs in Bouncy Castle

advisories/github-reviewed/2023/11/GHSA-wjxj-5m7g-mg7q/GHSA-wjxj-5m7g-mg7q.json
**Updates**
**Comments**
The official vendor CVE report at https://github.com/bcgit/bc-java/wiki/CVE-2023-33202 states all versions of Bouncy Castle Java versions 1.72 and earlier are affected, not just the JDK18 JAR files. Other relevant Bouncy Castle Maven packages (JARs) have been added.
=> [GHSA-wjxj-5m7g-mg7q] Bouncy Castle Denial of Service (DoS)

advisories/github-reviewed/2019/04/GHSA-jpv3-g4cc-6vfx/GHSA-jpv3-g4cc-6vfx.json
**Updates**
- References
**Comments**
This CVE's patch is to update the version of MQTT.
=> [GHSA-jpv3-g4cc-6vfx] Improper Control of Generation of Code ('Code Injection') in org.apache.activemq:activemq-client

advisories/github-reviewed/2018/10/GHSA-hvwm-2624-rp9x/GHSA-hvwm-2624-rp9x.json
**Updates**
- References
**Comments**
The CVE is related to https://issues.apache.org/jira/browse/AMQ-6954.
Add fixed in three branches.
=> [GHSA-hvwm-2624-rp9x] Apache ActiveMQ web console vulnerable to Cross-site Scripting

advisories/github-reviewed/2023/06/GHSA-hww2-5g85-429m/GHSA-hww2-5g85-429m.json
**Updates**
- References
**Comments**
It appears that versions 0.10.0.3 and 0.11.2 of the `uri` Ruby library contain the same fix as 0.10.3 and 0.12.2, even though the only the latter two are mentioned in the Ruby advisory. I've suggested additions to the References section of this advisory to list the commits included in the 0.10.0.3 and 0.11.2 releases that correspond to the already listed commits for 0.10.3 and 0.12.2--they seem to match exactly. I've also suggested updates to the listed affected and patched versions.
Note: The maintainers of the Ruby Advisory Database repository seem to have independently concluded that 0.10.0.3 and 0.11.2 include the fix for this vulnerability. If you look at https://github.com/rubysec/ruby-advisory-db/blob/master/gems/uri/CVE-2023 …
=> [GHSA-hww2-5g85-429m] URI gem has ReDoS vulnerability

advisories/github-reviewed/2022/05/GHSA-5jg4-p78r-p5j3/GHSA-5jg4-p78r-p5j3.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2016-6810.
=> [GHSA-5jg4-p78r-p5j3] Improper Neutralization of Input During Web Page Generation Apache ActiveMQ

advisories/github-reviewed/2022/04/GHSA-c2cp-3xj9-97w9/GHSA-c2cp-3xj9-97w9.json
**Updates**
- References
**Comments**
The parent POM (org.springframework.security.oauth:spring-security-oauth-parent) does not contain any binaries and is unaffected. The official security vulnerability reported by Spring (https://spring.io/security/cve-2022-22969) states that their oauth2 library is affected, not their oauth1 library. This advisory was referring to the wrong library.
=> [GHSA-c2cp-3xj9-97w9] Denial of service in Spring Security OAuth

advisories/github-reviewed/2022/05/GHSA-8rcq-p4gh-vmj8/GHSA-8rcq-p4gh-vmj8.json
**Updates**
- References
**Comments**
The https://activemq.apache.org/security-advisories.data/CVE-2016-0782-announcement.txt shows the CVE is related to configured on Jolokia.
In commits https://github.com/apache/activemq/compare/activemq-5.13.1...activemq-5.13.2, these three all related to Jolokia and I think these are related to the patch.
=> [GHSA-8rcq-p4gh-vmj8] Improper Neutralization of Input During Web Page Generation in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-w525-w93j-rxgm/GHSA-w525-w93j-rxgm.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2016-0734 which is fixed in multi-branches.
The NVD shows this CVE is related to X-Frame-Options HTTP.
=> [GHSA-w525-w93j-rxgm] Improper Neutralization of Input During Web Page Generation in Apache ActiveMQ

advisories/github-reviewed/2022/05/GHSA-9cvr-8xq4-2m73/GHSA-9cvr-8xq4-2m73.json
**Updates**
- References
**Comments**
The https://issues.apache.org/jira/browse/AMQ-5033 shows it is related to CVE-2014-8110.
So I add these two patch links related to CVE-2014-8110.
=> [GHSA-9cvr-8xq4-2m73] Improper Neutralization of Input During Web Page Generation in Apache ActiveMQ

advisories/github-reviewed/2024/03/GHSA-h59x-p739-982c/GHSA-h59x-p739-982c.json
**Updates**
- Severity
**Comments**
`langchain` and `langchain-core` got separated on 0.0.340.
the vulnerable code was moved from langchain - https://github.com/langchain-ai/langchain/blob/v0.0.339/libs/langchain/langchain/utils/loading.py
to langchain-core - https://github.com/langchain-ai/langchain/blob/v0.0.340/libs/core/langchain_core/utils/loading.py
Hence, technically langchain is only affected up to 0.0.339.
In addition, langhcain-core is affected as well, up to version 0.1.30 where the code was fixed.
=> [GHSA-h59x-p739-982c] LangChain directory traversal vulnerability

advisories/github-reviewed/2020/05/GHSA-p43x-xfjf-5jhr/GHSA-p43x-xfjf-5jhr.json
**Updates**
- References
**Comments**
Add one patch link related to CVE-2020-9548 which fixed in multi-branches.
=> [GHSA-p43x-xfjf-5jhr] jackson-databind mishandles the interaction between serialization gadgets and typing

advisories/github-reviewed/2020/06/GHSA-mc6h-4qgp-37qh/GHSA-mc6h-4qgp-37qh.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2020-14195.
=> [GHSA-mc6h-4qgp-37qh] Deserialization of untrusted data in Jackson Databind

advisories/github-reviewed/2020/06/GHSA-j823-4qch-3rgm/GHSA-j823-4qch-3rgm.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-14060.
=> [GHSA-j823-4qch-3rgm] Deserialization of untrusted data in Jackson Databind

advisories/github-reviewed/2020/04/GHSA-h4rc-386g-6m85/GHSA-h4rc-386g-6m85.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-11620.
=> [GHSA-h4rc-386g-6m85] jackson-databind mishandles the interaction between serialization gadgets and typing

advisories/github-reviewed/2020/05/GHSA-rf6r-2c4q-2vwg/GHSA-rf6r-2c4q-2vwg.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-10968.
=> [GHSA-rf6r-2c4q-2vwg] jackson-databind mishandles the interaction between serialization gadgets and typing

advisories/github-reviewed/2020/04/GHSA-95cm-88f5-f2c7/GHSA-95cm-88f5-f2c7.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2020-10672.
=> [GHSA-95cm-88f5-f2c7] jackson-databind mishandles the interaction between serialization gadgets and typing

advisories/github-reviewed/2018/10/GHSA-cggj-fvv3-cqwv/GHSA-cggj-fvv3-cqwv.json
**Updates**
- References
**Comments**
Add more patch links related to CVE-2018-7489.
=> [GHSA-cggj-fvv3-cqwv] FasterXML jackson-databind allows unauthenticated remote code execution 

advisories/github-reviewed/2022/05/GHSA-v2c9-9m8v-8jjm/GHSA-v2c9-9m8v-8jjm.json
**Updates**
**Comments**
In https://issues.apache.org/activemq/browse/AMQ-2700 says it can be fixed when update Jetty to 7.
And the https://issues.apache.org/jira/browse/AMQ-2600 is related to update Jetty to 7.
=> [GHSA-v2c9-9m8v-8jjm] Apache ActiveMQ Sensitive Information Disclosure via the Jetty ResourceHandler

README.md
This PR updates the README in the root of the project to include information about OSV's `database_specific` fields and how GitHub uses them in its OSV files.
[Rendered preview](https://github.com/github/advisory-database/blob/chrisbloom7/database-specific-values-readme/README.md#database_specific-values)
=> Add table of custom database_specific values to README

advisories/github-reviewed/2022/05/GHSA-p358-58jj-hp65/GHSA-p358-58jj-hp65.json
**Updates**
- References
**Comments**
Hello, I have found that there may be two possible fixes for the current vulnerability. I collected the commits between versions activemq-5.7.0 and activemq-5.8.0 at https://github.com/apache/activemq/compare/activemq-5.7.0...activemq-5.8.0 and found that only two commits are related to the fix mentioned in NVD, which is "The web console in Apache ActiveMQ before 5.8.0 does not require authentication." One of them is https://github.com/apache/activemq/commit/0fffe2172005f337412d5ec172cd92822395e239, which is mentioned in https://issues.apache.org/jira/browse/AMQ-3996 and addresses the validation issues with nio and ssl. The other one is https://github.com/apache/activemq/commit/76153ff24574fb91b474cca2f879b25395230786, which …
=> [GHSA-p358-58jj-hp65] Improper Authentication in Apache ActiveMQ

advisories/github-reviewed/2024/01/GHSA-chcr-x7hc-8fp8/GHSA-chcr-x7hc-8fp8.json
**Updates**
**Comments**
The associated CVE was opened in error and we are moving it to the Rejected status. We'd like to retract this GHSA to avoid confusion from users now that we've updated the documentation and communicated the issue.
=> [GHSA-chcr-x7hc-8fp8] Devise-Two-Factor vulnerable to brute force attacks

advisories/github-reviewed/2022/05/GHSA-5gg7-5wv8-4gcj/GHSA-5gg7-5wv8-4gcj.json
**Updates**
- References
**Comments**
added fix commits for respective versions.
1.3.31 https://github.com/undertow-io/undertow/commit/691440ee58259fba76711b60d56dde6679808bdc,
1.4.17 https://github.com/undertow-io/undertow/commit/5b008b7ac312c6cdb76679ff58c43620bb79d44f
2.0.0.Beta1 -https://github.com/undertow-io/undertow/commit/1e72647818c9fb31b693a953b1ae595a6c82eb7f
added Source Code Location
=> [GHSA-5gg7-5wv8-4gcj] Undertow Request Smuggling vulnerability

advisories/github-reviewed/2018/10/GHSA-898j-5cc8-cmf5/GHSA-898j-5cc8-cmf5.json
**Updates**
- References
**Comments**
Add four patfches:
https://github.com/apache/storm/commit/0fc6b522487c061f89e8cdacf09f722d3f20589
https://github.com/apache/storm/commit/efad4cca2d7d461f5f8c08a0d7b51fabeb82d0a
https://github.com/apache/storm/commit/1117a37b01a1058897a34e11ff5156e465efb69
https://github.com/apache/storm/commit/f61e5daf299d6c37c7ad65744d02556c94a16a4
, of which the commit message claims `STORM-3052: Allow for blobs to be unzipped/untarred`
=> [GHSA-898j-5cc8-cmf5] Moderate severity vulnerability that affects org.apache.storm:storm-core

advisories/github-reviewed/2024/03/GHSA-78hx-gp6g-7mj6/GHSA-78hx-gp6g-7mj6.json
**Updates**
- References
**Comments**
added fix commit for github.com/microsoft/go-crypto-openssl
release note
updated fix versions
=> [GHSA-78hx-gp6g-7mj6] Memory leaks in code encrypting and verifying RSA payloads

advisories/github-reviewed/2023/09/GHSA-hvpq-7vcc-5hj5/GHSA-hvpq-7vcc-5hj5.json
**Updates**
**Comments**
The changelog page for the package says it was fixed in 4.1.4: https://froala.com/wysiwyg-editor/changelog/#4.1.4
froala-editor is also available as an npm package, but this was missing from the advisory: https://www.npmjs.com/package/froala-editor
=> [GHSA-hvpq-7vcc-5hj5] Froala Editor Cross-site Scripting vulnerability

advisories/github-reviewed/2019/01/GHSA-77rc-x84q-pv4f/GHSA-77rc-x84q-pv4f.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2018-20245 which fixed in multi-branches.
=> [GHSA-77rc-x84q-pv4f] Improper Certificate Validation in Apache Airflow

advisories/github-reviewed/2020/07/GHSA-976r-qfjj-c24w/GHSA-976r-qfjj-c24w.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2020-11981.
=> [GHSA-976r-qfjj-c24w] Command injection via Celery broker in Apache Airflow

advisories/github-reviewed/2020/07/GHSA-9g2w-5f3v-mfmm/GHSA-9g2w-5f3v-mfmm.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2020-11982.
=> [GHSA-9g2w-5f3v-mfmm] Insecure default config of Celery worker in Apache Airflow

advisories/github-reviewed/2021/06/GHSA-fh37-cx83-q542/GHSA-fh37-cx83-q542.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2021-26697 which fixed in multi-branches.
=> [GHSA-fh37-cx83-q542] Improper Authentication in Apache Airflow

advisories/github-reviewed/2018/08/GHSA-gxpj-cx7g-858c/GHSA-gxpj-cx7g-858c.json
**Updates**
- CVSS
- Severity
**Comments**
Given that the advisory suggests itself this should be a low severity issue based on the amount of characters this needs to exploit, this should be downgraded to a Low severity issue.
=> [GHSA-gxpj-cx7g-858c] Regular Expression Denial of Service in debug

advisories/github-reviewed/2019/11/GHSA-q3p4-gw7r-wqjc/GHSA-q3p4-gw7r-wqjc.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2019-12417 which fixed in multi-branches.
=> [GHSA-q3p4-gw7r-wqjc] Apache Airflow vulnerable to XSS and local file disclosure

advisories/github-reviewed/2021/03/GHSA-57h3-9rgr-c24m/GHSA-57h3-9rgr-c24m.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2021-25289  which fixed in multi-branches.
=> [GHSA-57h3-9rgr-c24m] Out of bounds write in Pillow

advisories/github-reviewed/2021/03/GHSA-8xjq-8fcg-g5hw/GHSA-8xjq-8fcg-g5hw.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2021-25290 which fixed in multi-branches.
=> [GHSA-8xjq-8fcg-g5hw] Out-of-bounds Write in Pillow

advisories/github-reviewed/2024/03/GHSA-q84m-rmw3-4382/GHSA-q84m-rmw3-4382.json
**Updates**
- References
**Comments**
Original patch was reverted, and a new patch made and released as part of 0.1.35
=> [GHSA-q84m-rmw3-4382] LangChain's XMLOutputParser vulnerable to XML Entity Expansion

advisories/github-reviewed/2021/08/GHSA-m6h2-jx9v-58w6/GHSA-m6h2-jx9v-58w6.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2021-35936.
=> [GHSA-m6h2-jx9v-58w6] Missing Authorization in Apache Airflow

advisories/github-reviewed/2022/09/GHSA-q8h9-pqcx-59hw/GHSA-q8h9-pqcx-59hw.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2022-38170.
=> [GHSA-q8h9-pqcx-59hw] Apache Airflow exposes arbitrary file content

advisories/github-reviewed/2024/03/GHSA-6xwf-xvf3-v459/GHSA-6xwf-xvf3-v459.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2024-26280 which fixed in multi-branches.
=> [GHSA-6xwf-xvf3-v459] Apache Airflow: Incorrect Default Permissions in audit logs for Ops and Viewers users

advisories/github-reviewed/2024/02/GHSA-6v6w-h8m6-7mv2/GHSA-6v6w-h8m6-7mv2.json
**Updates**
- References
**Comments**
Add patch links related to CVE-2024-27906 which fixed in multi-branches.
=> [GHSA-6v6w-h8m6-7mv2] Apache Airflow: DAG Code and Import Error Permissions Ignored

advisories/github-reviewed/2024/03/GHSA-r65j-6h5f-4f92/GHSA-r65j-6h5f-4f92.json
**Updates**
**Comments**
`io.jsonwebtoken:jjwt-root` is a Maven base project ('pom') and doesn't contain any binaries or implementation (https://repo1.maven.org/maven2/io/jsonwebtoken/jjwt-root/0.12.5/jjwt-root-0.12.5.pom shows `<packaging>pom</packaging>`). 
The CVE lists the `signWith` and `setSigningKey` methods as affected. The implementation of these methods are distributed in `io.jsonwebtoken:jjwt-impl` (e.g. https://github.com/jwtk/jjwt/blob/26948610fbef81eba867cbaad54b516d1874c70a/impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParserBuilder.java#L242)
=> [GHSA-r65j-6h5f-4f92] JJWT improperly generates signing keys

advisories/github-reviewed/2022/05/GHSA-56gj-927p-mfph/GHSA-56gj-927p-mfph.json
**Updates**
**Comments**
It was brought to our attention via https://github.com/google/osv.dev/issues/2075 that the separator character should a slash and not a colon
=> [GHSA-56gj-927p-mfph] Jenkins Aqua Security Serverless Scanner Plugin showed plain text password in job configuration form fields 

advisories/github-reviewed/2022/10/GHSA-qrw5-5h28-6cmg/GHSA-qrw5-5h28-6cmg.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2022-41323 which fixed in multi-branches.
=> [GHSA-qrw5-5h28-6cmg] Django denial-of-service vulnerability in internationalized URLs

advisories/github-reviewed/2024/03/GHSA-cxjh-pqwp-8mfp/GHSA-cxjh-pqwp-8mfp.json
**Updates**
- Description
**Comments**
Reformatted the advisory to be much more human readable, including hyperlinks and using code blocks where needed. Also, removed duplicated links and wording which are already specified in the references section.
=> [GHSA-cxjh-pqwp-8mfp] follow-redirects' Proxy-Authorization header kept across hosts

advisories/github-reviewed/2022/05/GHSA-hr8g-f6r6-mr22/GHSA-hr8g-f6r6-mr22.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2022-30595.
=> [GHSA-hr8g-f6r6-mr22] Buffer over-flow in Pillow

advisories/github-reviewed/2021/06/GHSA-q5hq-fp76-qmrc/GHSA-q5hq-fp76-qmrc.json
**Updates**
- References
**Comments**
Add patch link related to CVE-2021-28677.
=> [GHSA-q5hq-fp76-qmrc] Uncontrolled Resource Consumption in Pillow

advisories/github-reviewed/2022/05/GHSA-pjqh-2jcc-5j84/GHSA-pjqh-2jcc-5j84.json
**Updates**
**Comments**
According to the Spring advisory https://spring.io/security/cve-2017-8028 this vulnerability affects Spring-LDAP and not spring-amqp. The linked PR https://github.com/spring-projects/spring-ldap/pull/432/files fixes a package in ldap core, hence the affected package seems to be org.springframework.ldap:spring-ldap-core
=>  [GHSA-pjqh-2jcc-5j84] Update pkg name from spring-amqp to spring-ldap-core

advisories/github-reviewed/2024/03/GHSA-f5x3-32g6-xq36/GHSA-f5x3-32g6-xq36.json
**Updates**
**Comments**
node-tar is a deprecated package, the vulnerability is for tar
https://www.npmjs.com/package/node-tar
https://www.npmjs.com/package/tar
=> [GHSA-f5x3-32g6-xq36] Denial of service while parsing a tar file due to lack of folders count validation

advisories/github-reviewed/2024/04/GHSA-f8h5-v2vg-46rr/GHSA-f8h5-v2vg-46rr.json
**Updates**
**Comments**
See https://github.com/quarkusio/quarkus/issues/39927#issuecomment-2041376909 - there might be a reason though why the team hasn't updated their internal tickets. Maybe even the link to Guillaume's comment would be of help for people coming to this advisory.
=> [GHSA-f8h5-v2vg-46rr] quarkus-core leaks local environment variables from Quarkus namespace during application's build

advisories/github-reviewed/2022/10/GHSA-p8f7-22gq-m7j9/GHSA-p8f7-22gq-m7j9.json
**Updates**
- CWEs
**Comments**
Add CWE
=> [GHSA-p8f7-22gq-m7j9] Phoenix before 1.6.14 mishandles check_origin wildcarding

advisories/github-reviewed/2023/07/GHSA-h755-8qp9-cq85/GHSA-h755-8qp9-cq85.json
**Updates**
- Description
- References
**Comments**
The 7.2.4 release still contains vulnerabilities, the original CVE was updated to include the 7.2.4 version as affected but the change was not mirrored into Github
https://github.com/protobufjs/protobuf.js/issues/1918#issuecomment-1723500294
=> [GHSA-h755-8qp9-cq85] protobufjs Prototype Pollution vulnerability

advisories/github-reviewed/2024/03/GHSA-v682-8vv8-vpwr/GHSA-v682-8vv8-vpwr.json
**Updates**
**Comments**
The indicated patches specifically touch org.apache.tomcat.websocket which appears to produce the [tomcat-websocket](https://github.com/apache/tomcat/blob/d2f8d8351fe66e153ca5d5fde15cef820f70cfef/res/bnd/tomcat-websocket.jar.tmp.bnd#L21) and [tomcat-embed-websocket](https://github.com/apache/tomcat/blob/d2f8d8351fe66e153ca5d5fde15cef820f70cfef/res/bnd/tomcat-embed-websocket.jar.tmp.bnd#L22) jars
=> [GHSA-v682-8vv8-vpwr] Denial of Service via incomplete cleanup vulnerability in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-5xv2-q475-rwrh/GHSA-5xv2-q475-rwrh.json
**Updates**
**Comments**
The [patch commit](https://github.com/Katello/katello/commit/7c256fef9d75029d0ffff58ff1dcda915056d3a3) appears in the [katello-1.0.6-1](https://github.com/Katello/katello/commits/katello-1.0.6-1/) and [katello-1.1.7-1](https://github.com/Katello/katello/commits/katello-1.1.7-1/) tags.
=> [GHSA-5xv2-q475-rwrh] Katello uses hard coded credential

advisories/github-reviewed/2024/04/GHSA-46cm-pfwv-cgf8/GHSA-46cm-pfwv-cgf8.json
**Updates**
**Comments**
Hi, I'm the maintainer of LiteLLM and we fixed this issue - please can you help us mark this as resolved 
Issue: https://github.com/BerriAI/litellm/issues/2949
PR with fix: https://github.com/BerriAI/litellm/pull/2941
=> [GHSA-46cm-pfwv-cgf8] LiteLLM has Server-Side Template Injection vulnerability in /completions endpoint

advisories/github-reviewed/2024/03/GHSA-7w75-32cg-r6g2/GHSA-7w75-32cg-r6g2.json
**Updates**
**Comments**
It appears that the patch applies specifically to org.apache.coyote.http2 which per https://github.com/search?q=repo%3Aapache%2Ftomcat+org.apache.coyote+path%3Ares%2Fbnd&type=code is bundled into the specific artifact`org.apache.tomcat:tomcat-coyote` (as well as `org.apache.tomcat.embed:tomcat-embed-core`)
=> [GHSA-7w75-32cg-r6g2] Apache Tomcat Denial of Service due to improper input validation vulnerability for HTTP/2 requests

advisories/github-reviewed/2023/09/GHSA-3p86-9955-h393/GHSA-3p86-9955-h393.json
**Updates**
- Description
- References
**Comments**
Updated Affected Products since the fix was backported to 5.13.3.202401111512-r per project release notes.
=> [GHSA-3p86-9955-h393] Arbitrary File Overwrite in Eclipse JGit 

advisories/github-reviewed/2024/01/GHSA-59j7-ghrg-fj52/GHSA-59j7-ghrg-fj52.json
**Updates**
**Comments**
Is this not a duplicate of https://github.com/advisories/GHSA-8g9c-28fc-mcx2? If it isn't I believe CVE-2024-21319 would still be the CVE-ID to refer to here, but I couldn't find a form field to add it.
=> [GHSA-59j7-ghrg-fj52] Microsoft Security Advisory CVE-2024-21319: .NET Denial of Service Vulnerability

advisories/github-reviewed/2023/06/GHSA-xm2m-2q6h-22jw/GHSA-xm2m-2q6h-22jw.json
**Updates**
- CVSS
- References
**Comments**
Added blog post to References, which provides additional background on the vulnerable components. Based on that analysis, the attack complexity should be considered high because an attacker must authenticate to Apache NiFi and must have permissions that authorize the configuration of the vulnerable components. Also added `nifi-dbcp-service-nar` to affected products as it contains the JAR artifacts with the vulnerable components.
=> [GHSA-xm2m-2q6h-22jw] Apache NiFi vulnerable to Code Injection

advisories/github-reviewed/2024/01/GHSA-264p-99wq-f4j6/GHSA-264p-99wq-f4j6.json
**Updates**
**Comments**
Older versions of Amazon Ion Java were published with the scope "software.amazon.ion:ion-java". In 2020 Amazon migrated to the new group id "com.amazon.ion": https://amazon-ion.github.io/ion-docs/news/2020/01/15/software.amazon.ion-deprecated.html
The affected versions (< 1.10.5) also cover the versions published under the deprecated group id (1.0.0 through 1.5.1), so I'm proposing it be included in this advisory. As there is no fix for the old scope, I didn't list any patched version for that new affected 'product' entry.
=> [GHSA-264p-99wq-f4j6] Ion Java StackOverflow vulnerability

advisories/github-reviewed/2018/10/GHSA-mh7g-99w9-xpjm/GHSA-mh7g-99w9-xpjm.json
**Updates**
- References
**Comments**
add 5 patch commits:
https://github.com/apache/lucene-solr/commit/f9fd6e9e26224f26f1542224ce187e04c27b268
https://github.com/apache/lucene-solr/commit/3bba91131b5257e64b9d0a2193e1e32a145b2a2
https://github.com/apache/lucene-solr/commit/d8000beebfb13ba0b6e754f84c760e11592d8d1
https://github.com/apache/lucene-solr/commit/d28baa3fc5566b47f1ca7cc2ba1aba658dc634a
https://github.com/apache/lucene-solr/commit/926cc4d65b6d2cc40ff07f76d50ddeda947e3cc
The commit msg show the intention: `SOLR-11477: Disallow resolving of external entities in Lucene queryparser/xml/CoreParser and SolrCoreParser (defType=xmlparser or {!xmlparser ...}) by default.`
and add the corresponding but track link: https://issues.apache.org/jira/browse/SOLR-11477.
=> [GHSA-mh7g-99w9-xpjm] Remote code execution occurs in Apache Solr

advisories/github-reviewed/2018/10/GHSA-rvgg-f8qm-6h7j/GHSA-rvgg-f8qm-6h7j.json
**Updates**
- References
**Comments**
Add a patch https://github.com/vert-x3/vertx-web/commit/f42b193b15a29b772fc576b2d0f2497e7474a7e, of which the commit message claims `Validate that X-XSRF-Token and X-XSRF-Token cookie are the same - fixes #970
(cherry picked from commit 482bc72)`
Add a patch https://github.com/vert-x3/vertx-web/commit/98891b1d9e022b467a3e4674aca4d1889849b1d, of which the commit message claims `Validate that X-XSRF-Token and X-XSRF-Token cookie are the same - fixes #970
(cherry picked from commit f42b193)`
And update the bug issue link: https://github.com/vert-x3/vertx-web/issues/970, which shows the tracing for this cve.
=> [GHSA-rvgg-f8qm-6h7j] High severity vulnerability that affects io.vertx:vertx-web

advisories/github-reviewed/2018/10/GHSA-m9jm-rhrm-gcxj/GHSA-m9jm-rhrm-gcxj.json
**Updates**
- References
**Comments**
Add a patch https://github.com/spring-projects/spring-integration-extensions/commit/a5573eb232ff85199ff9bb28993df715d9a19a25, of which the commit message claims `Disallow traversal entity in zip
When the file name holds path traversal file names it gets
concatenated to the target extraction directory,
the final path ends up outside of the target folder.`
=> [GHSA-m9jm-rhrm-gcxj] Path traversal in org.springframework.integration:spring-integration-zip

advisories/github-reviewed/2018/10/GHSA-j8g6-2wh7-6439/GHSA-j8g6-2wh7-6439.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/tika/commit/8a68b5d474205cc91cbbb610d4a1c05af57f0610, of which the commit message claims `clean up MatParser`, coinciding with the CVE desc and the code diff shows that it indeed tried to resolve the deserialization issue.
=> [GHSA-j8g6-2wh7-6439] Apache Tika allows Java code execution for serialized objects embedded in MATLAB files

advisories/github-reviewed/2022/05/GHSA-9284-j4c9-779q/GHSA-9284-j4c9-779q.json
**Updates**
- References
**Comments**
add 8 patch commits from github and git-svn for various version:
https://github.com/apache/jackrabbit/commit/26e601934d0f439f0a61d62265f52936d79df40d
https://github.com/apache/jackrabbit/commit/3903739363b79deb7579802fbc27b9b7448218b2
https://github.com/apache/jackrabbit/commit/ddf9a3cd408397d0805917299c4114b09449373d
https://github.com/apache/jackrabbit/commit/17e9f68f5a3f05ded20569777a7b07422680612d
https://github.com/apache/jackrabbit/commit/b7fa1ae39641936872617ff95363353b0345b777
https://github.com/apache/jackrabbit/commit/89c5c4ed6ab250ad609829517f167d2dbe0abdd0
https://github.com/apache/jackrabbit/commit/6191b366c607e65325a0116097aca8a359b36486
and a git-svn link: …
=> [GHSA-9284-j4c9-779q] Improper Input Validation in Apache Jackrabbit

advisories/github-reviewed/2022/05/GHSA-w7cq-j9p9-hm3m/GHSA-w7cq-j9p9-hm3m.json
**Updates**
- References
**Comments**
"Add a patch https://github.com/apache/santuario-java/commit/55857fd4cdfdb1af4069170ecdac448c078f544e, of which the commit message claims `more signature verification tests
git-svn-id: https://svn.apache.org/repos/asf/santuario/xml-security-java/trunk@1634334 13f79535-47bb-0310-9956-ffa450edef68`" and the git svn link's msg claims `CVE-2014-8152 - more signature verification tests`
=> [GHSA-w7cq-j9p9-hm3m] Improper Input Validation in Apache Santuario XML Security

advisories/github-reviewed/2022/05/GHSA-9fc5-q25c-r2wr/GHSA-9fc5-q25c-r2wr.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apereo/java-cas-client/commit/ab6cbdc3daa451b4fef89c0bd0f4e6568f3aa9ef, of which the commit message claims `Merge pull request #73 from battags/CASC-228
CASC-228 URL Encode Paramaters Passed to Server via Validate`, the bug id coincides with the one in reference links.
=> [GHSA-9fc5-q25c-r2wr] Jasig Java CAS Client, .NET CAS Client, and phpCAS contain URL parameter injection vulnerability

advisories/github-reviewed/2018/10/GHSA-cfh5-3ghh-wfjx/GHSA-cfh5-3ghh-wfjx.json
**Updates**
- References
**Comments**
Add two patch links: 
https://github.com/apache/httpcomponents-client/commit/51cc67567765d67f878f0dcef61b5ded454d3122
and 
https://svn.apache.org/viewvc?view=revision&revision=1614064
, 
of which the commit message claims `Improved cert subject parsing https://svn.apache.org/viewvc?view=revision&revision=1614064
`
And the original commit msg on svn show it fixed the cve: `CVE-2014-3577: Use javax.naming.ldap.LdapName to do the extraction of CN from DN of X500 principal`.
=> [GHSA-cfh5-3ghh-wfjx] Improper Verification of Cryptographic Signature in org.apache.httpcomponents:httpclient

advisories/github-reviewed/2024/04/GHSA-frc2-w2cc-x794/GHSA-frc2-w2cc-x794.json
**Updates**
- CVSS
**Comments**
Error in CVSS vector: 
- https://nvd.nist.gov/vuln/detail/CVE-2024-3046
- https://gitlab.eclipse.org/security/vulnerability-reports/-/issues/188
=> [GHSA-frc2-w2cc-x794] Eclipse Kura LogServlet vulnerability

advisories/github-reviewed/2022/05/GHSA-7vpq-g998-qpv7/GHSA-7vpq-g998-qpv7.json
**Updates**
- References
**Comments**
Add a patch https://github.com/netty/netty/commit/8599ab5bdb761bb99d41a975d689f74c12e4892b, of which the commit message reflects the motivation for fixing this cve, consistent with the issue (https://github.com/netty/netty/issues/2441) this cve referred to: `Remove ContinuationWebSocketFrame.aggregatedText()...`
=> [GHSA-7vpq-g998-qpv7] Netty denial of service vulnerability

advisories/github-reviewed/2022/05/GHSA-42j3-498q-m6vp/GHSA-42j3-498q-m6vp.json
**Updates**
- References
**Comments**
Add a patch https://github.com/apache/tomcat/commit/593a2447e6ebe465585cfa07e93b5635dffa1c70, of which the commit message claims `i18n for ChunkedInputFilter error message Add error flag to allow subsequent attempts at reading after an error to fail fast`, which coincides with the cve description.
=> [GHSA-42j3-498q-m6vp] Improper Input Validation in Apache Tomcat

advisories/github-reviewed/2020/09/GHSA-wmv4-5w76-vp9g/GHSA-wmv4-5w76-vp9g.json
**Updates**
- References
**Comments**
Add a patch https://github.com/spring-projects/spring-security/commit/934937d9c1dc20c396b96c08310b72cfa627acb, of which the commit message claims `SEC-2688: CAS Proxy Ticket Authentication uses Service for host & port`, coinciding with the CVE desc and the issue id SEC-2688
was also mentioned in the github issue link: https://github.com/spring-projects/spring-security/issues/2907.
=> [GHSA-wmv4-5w76-vp9g] Authorization Bypass in Spring Security

advisories/github-reviewed/2022/05/GHSA-q56h-jjj6-52mf/GHSA-q56h-jjj6-52mf.json
**Updates**
- References
**Comments**
Add 5 patch commits: 
- `https://github.com/apache/poi/commit/d72bd78c19dfb7b57395a66ae8d9269d59a87bd2`
- explanation: This commit tidies up the OPC SAX setup code, which is directly related to mitigating the XXE vulnerabilities identified in this cve.
- `https://github.com/apache/poi/commit/103b45073c7b504236588b3acc146530205af53c`
- explanation: This commit applies multiple security enhancements, including secure XML defaults and parser updates, to address the XXE vulnerabilities outlined in this cve. It merges critical security suggestions for robust defense mechanisms against XML entity attacks.
- `https://github.com/apache/poi/commit/6050a68d5adfb4ffef1edb778add09bcee32d1c3`
- explanation: Addition of test files and unit …
=> [GHSA-q56h-jjj6-52mf] Improper Restriction of XML External Entity Reference in Apache POI

advisories/github-reviewed/2022/05/GHSA-845h-985r-jrqh/GHSA-845h-985r-jrqh.json
**Updates**
- References
**Comments**
add 8 patch commits, the commit msgs show their role to fix the issue `HV-912`, as referred in the current reference links:
https://github.com/hibernate/hibernate-validator/commit/c489416f699a46859c134796b3ccfea41ef3ce52
https://github.com/hibernate/hibernate-validator/commit/c9525ca544b1281e2b7c7347e86e87c86dc1dc6e
https://github.com/hibernate/hibernate-validator/commit/7e7131939a4361a7cad3e77ab89a8462132c561c
https://github.com/hibernate/hibernate-validator/commit/fd4eaed7fb930db6a5e4c03742b4b3adcfecc90e
https://github.com/hibernate/hibernate-validator/commit/f97c2021a03c825abdeca1692f5be51e77e76a8f
https://github.com/hibernate/hibernate-validator/commit/e8c42b689df8c6752d635d02c6518da3fece3870 …
=> [GHSA-845h-985r-jrqh] Improper Authentication in Hibernate Validator

advisories/github-reviewed/2024/04/GHSA-5x7m-6737-26cr/GHSA-5x7m-6737-26cr.json
**Updates**
- CVSS
- CWEs
- Severity
- Summary
**Comments**
We internally discussed https://github.com/SixLabors/ImageSharp/security/advisories/GHSA-5x7m-6737-26cr with @JimBobSquarePants and came to an agreement that the original assesment of the vulnerability being a case of CWE-416 is incorrect: the attack does not have a Use After Free aspect and potential to corrupt memory so it doesn't impact Availability. Moreover, we determined that the Attack Complexity is High, and server-side software using ImageSharp might be exposed to Network attacks, therefore it's a better choice for Attack Vector.
https://github.com/SixLabors/ImageSharp/security/advisories/GHSA-5x7m-6737-26cr has been edited to reflect these decisions, but the CVE went out with incorrect content, so it …
=> [GHSA-5x7m-6737-26cr] SixLabors.ImageSharp vulnerable to Use After Free

advisories/github-reviewed/2024/04/GHSA-8m45-2rjm-j347/GHSA-8m45-2rjm-j347.json
**Updates**
**Comments**
This advisory is missing the versions from the original GHSA. Without them, Dependabot advisories won't clear, even if someone is using a non-affected version.
=> [GHSA-8m45-2rjm-j347] Version ranges input into GHSA did not end up on published advisory

advisories/github-reviewed/2022/05/GHSA-4v3g-g84w-hv7r/GHSA-4v3g-g84w-hv7r.json
**Updates**
**Comments**
The commits (for instance https://github.com/apache/tomcat/commit/a6b1ebc246b91b854237e5aad3dfd2b5460ea282) indicate that the affected component is under jasper.runtime which per https://github.com/search?q=repo%3Aapache%2Ftomcat+jasper.runtime+path%3A%2F%5Eres%5C%2Fbnd%5C%2F%2F&type=code corresponds to the `org.apacher.tomcat.embed:tomcat-embed-jasper` and `org.apache.tomcat:tomcat-jasper` maven artifacts.  Also, the v6 release line artifacts were present at `org.apache.tomcat:jasper`
=> [GHSA-4v3g-g84w-hv7r] Authentication Bypass Using an Alternate Path or Channel in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-3vx3-xf6q-r5xp/GHSA-3vx3-xf6q-r5xp.json
**Updates**
**Comments**
Per the associated commits (such as https://github.com/apache/tomcat80/commit/6d73b079c55ee25dea1bbd0556bb568a4247dacd), the affected component is catalina which corresponds to the `org.apache.tomcat:tomcat-catalina` and `org.apache.tomcat.embed:tomcat-embed-core` maven artifacts
=> [GHSA-3vx3-xf6q-r5xp] Exposure of Resource to Wrong Sphere in Apache Tomcat

advisories/github-reviewed/2022/05/GHSA-9hg2-395j-83rm/GHSA-9hg2-395j-83rm.json
**Updates**
**Comments**
Per the associated commit https://github.com/apache/tomcat/commit/9233d9d6a018be4415d4d7d6cb4fe01176adf1a8 the affected component is coyote.http11 which per https://github.com/search?q=repo%3Aapache%2Ftomcat+apache.coyote+path%3A%2F%5Eres%5C%2Fbnd%5C%2F%2F&type=code is distributed as part of the `org.apache.tomcat:tomcat-coyote` and `org.apache.tomcat.embed:tomcat-embed-core` maven artifacts
=> [GHSA-9hg2-395j-83rm] Expected Behavior Violation in Apache Tomcat

advisories/github-reviewed/2024/01/GHSA-6hwg-w5jg-9c6x/GHSA-6hwg-w5jg-9c6x.json
=> [GHSA-6hwg-w5jg-9c6x] Path Traversal in Moby builder

advisories/github-reviewed/2023/01/GHSA-rq2w-37h9-vg94/GHSA-rq2w-37h9-vg94.json
**Updates**
**Comments**
Per the commits (such as https://github.com/apache/tomcat/commit/b336f4e58893ea35114f1e4a415657f723b1298e), the specifically patched components get distributed as part of the following maven artifacts:
- org.apache.tomcat:tomcat-catalina
- org.apache.tomcat:tomcat-util
- org.apache.tomcat.embed:tomcat-embed-core
=> [GHSA-rq2w-37h9-vg94] Apache Tomcat improperly escapes input from JsonErrorReportValve

advisories/github-reviewed/2024/01/GHSA-f4qf-m5gf-8jm8/GHSA-f4qf-m5gf-8jm8.json
**Updates**
- References
**Comments**
Adds the fixing commits obtained from the tomcat security logs
- https://tomcat.apache.org/security-8.html [commit](https://github.com/apache/tomcat/commit/ce4b154e7b48f66bd98858626347747cd2514311)
- https://tomcat.apache.org/security-9.html [commit](https://github.com/apache/tomcat/commit/86ccc43940861703c2be96a5f35384407522125a)
Per the commits the affected component is under coyote/http11 which is bundled into the `org.apache.tomcat:tomcat-coyote` and `org.apache.tomcat.embed:tomcat-embed-core` maven artifacts
=> [GHSA-f4qf-m5gf-8jm8] Apache Tomcat vulnerable to Generation of Error Message Containing Sensitive Information

advisories/github-reviewed/2023/07/GHSA-cx6h-86xw-9x34/GHSA-cx6h-86xw-9x34.json
**Updates**
- References
**Comments**
Adds the commits for each release line obtained from the security pages at:
- https://tomcat.apache.org/security-10.html
- https://tomcat.apache.org/security-11.html
- https://tomcat.apache.org/security-8.html
- https://tomcat.apache.org/security-9.html 
Looking at the commits (such as https://github.com/apache/tomcat/commit/d53d8e7f77042cc32a3b98f589496a1ef5088e38), the affected code was under util/http which ends up bundled into the `org.apache.tomcat:tomcat-coyote` and `org.apache.tomcat.embed:tomcat-embed-core` maven artifacts per https://github.com/search?q=repo%3Aapache%2Ftomcat+util.http+path%3A%2F%5Eres%5C%2Fbnd%5C%2F%2F&type=code
=> [GHSA-cx6h-86xw-9x34] Apache Tomcat - Fix for CVE-2023-24998 was incomplete

advisories/github-reviewed/2024/04/GHSA-33c5-9fx5-fvjm/GHSA-33c5-9fx5-fvjm.json
**Updates**
**Comments**
Even though kube-apiserver is versioned as Kubernetes, the vulnerable package (`k8s.io/apimachinery`) is not. The versions affected are tagged as v0 instead of v1. The versions mentioned in this GHSA cause all packages ever published to be falsely reported as vulnerable.
=> [GHSA-33c5-9fx5-fvjm] Privilege Escalation in Kubernetes

advisories/github-reviewed/2021/09/GHSA-c36v-fmgq-m8hx/GHSA-c36v-fmgq-m8hx.json
**Updates**
**Comments**
The implementation of `objectTraps.get` changed.
In version 6.0.9 and earlier [`objectTraps.get`](https://github.com/immerjs/immer/blob/v6.0.9/src/core/proxy.ts#L108) always returns a proxy object returned by [`createProxy`](https://github.com/immerjs/immer/blob/v6.0.9/src/core/proxy.ts#L131) which protects against prototype pollution.
Starting version 7.0.0, if [`!has(source, prop)`](https://github.com/immerjs/immer/blob/v7.0.0/src/core/proxy.ts#L106) then [`readPropFromProto`](https://github.com/immerjs/immer/blob/v7.0.0/src/core/proxy.ts#L210) will be called which doesn't create a proxy.
I verified that for all the versions using the following scripts:
`run.py`:
```python
import requests
import os
import subprocess
import shutil
def …
```
=> [GHSA-c36v-fmgq-m8hx] Prototype Pollution in immer

advisories/github-reviewed/2021/09/GHSA-33f9-j839-rf8h/GHSA-33f9-j839-rf8h.json
**Updates**
**Comments**
The implementation of `objectTraps.get` changed.
In version 6.0.9 and earlier [`objectTraps.get`](https://github.com/immerjs/immer/blob/v6.0.9/src/core/proxy.ts#L108) always returns a proxy object returned by [`createProxy`](https://github.com/immerjs/immer/blob/v6.0.9/src/core/proxy.ts#L131) which protects against prototype pollution.
Starting version 7.0.0, if [`!has(source, prop)`](https://github.com/immerjs/immer/blob/v7.0.0/src/core/proxy.ts#L106) then [`readPropFromProto`](https://github.com/immerjs/immer/blob/v7.0.0/src/core/proxy.ts#L210) will be called which doesn't create a proxy.
I verified that for all the versions using the following scripts:
`run.py`:
```python
import requests
import os
import subprocess
import shutil
def …
```
=> [GHSA-33f9-j839-rf8h] Prototype Pollution in immer

advisories/github-reviewed/2021/01/GHSA-9qmh-276g-x5pj/GHSA-9qmh-276g-x5pj.json
**Updates**
**Comments**
The implementation of `objectTraps.get` changed.
In version 6.0.9 and earlier [`objectTraps.get`](https://github.com/immerjs/immer/blob/v6.0.9/src/core/proxy.ts#L108) always returns a proxy object returned by [`createProxy`](https://github.com/immerjs/immer/blob/v6.0.9/src/core/proxy.ts#L131) which protects against prototype pollution.
Starting version 7.0.0, if [`!has(source, prop)`](https://github.com/immerjs/immer/blob/v7.0.0/src/core/proxy.ts#L106) then [`readPropFromProto`](https://github.com/immerjs/immer/blob/v7.0.0/src/core/proxy.ts#L210) will be called which doesn't create a proxy.
I verified that for all the versions using the following scripts:
`run.py`:
```python
import requests
import os
import subprocess
import shutil
def …
```
=> [GHSA-9qmh-276g-x5pj] Prototype Pollution in immer

advisories/github-reviewed/2024/04/GHSA-98p4-xjmm-8mfh/GHSA-98p4-xjmm-8mfh.json
**Updates**
- CWEs
**Comments**
This adds the more specific weakness [CWE-88](https://cwe.mitre.org/data/definitions/88.html), as discussed in [the pull request that fixed this vulnerability](https://github.com/Byron/gitoxide/pull/1342), in comments https://github.com/Byron/gitoxide/pull/1342#issuecomment-2057647039 and below. I've already made this change at the corresponding repository-level advisory https://github.com/Byron/gitoxide/security/advisories/GHSA-98p4-xjmm-8mfh. Because [CWE-88](https://cwe.mitre.org/data/definitions/88.html) is a [child](https://cwe.mitre.org/data/definitions/88.html#Relationships) of [CWE-77](https://cwe.mitre.org/data/definitions/77.html), I wasn't sure if it was best to keep [CWE-77](https://cwe.mitre.org/data/definitions/77.html) as …
=> [GHSA-98p4-xjmm-8mfh] gix-transport indirect code execution via malicious username

advisories/github-reviewed/2022/05/GHSA-3xh5-5v5v-mfgm/GHSA-3xh5-5v5v-mfgm.json
The current affected version ranges overlap with a fixed version.  
The fix suggested is based on NVD data: https://nvd.nist.gov/vuln/detail/CVE-2019-14884
=> [GHSA-3xh5-5v5v-mfgm] Moodle: fixing affected version ranges

advisories/github-reviewed/2022/05/GHSA-9848-v244-962p/GHSA-9848-v244-962p.json
**Updates**
**Comments**
If the struts vulnerable version is <= 1.3.10, this must affect struts, not struts2.
=> [GHSA-9848-v244-962p] Apache Struts XSS

advisories/github-reviewed/2024/04/GHSA-c5pj-mqfh-rvc3/GHSA-c5pj-mqfh-rvc3.json
**Updates**
- Description
- References
- Summary
**Comments**
Because this is a vulnerability of cri-o, not runc. 
runc is working as designed, and it's cri-o's responsibility to validate the config.
Users do NOT need to update runc.
https://github.com/opencontainers/runc/issues/4263
=> [GHSA-c5pj-mqfh-rvc3] Runc allows an arbitrary systemd property to be injected

advisories/github-reviewed/2024/04/GHSA-cjwg-qfpm-7377/GHSA-cjwg-qfpm-7377.json
**Updates**
- Summary
**Comments**
The vulnerability does not affect JWT tokens but JWE messages. This is an important distinction because JWE is used less frequently.
=> [GHSA-cjwg-qfpm-7377] python-jose denial of service via compressed JWT tokens

advisories/github-reviewed/2024/03/GHSA-7f88-5hhx-67m2/GHSA-7f88-5hhx-67m2.json
**Updates**
**Comments**
According to SNYK and Maven Repo, version 3.8.14.Final is the latest version and patches vulnerability CVE-2023-5685:
https://mvnrepository.com/artifact/org.jboss.xnio/xnio-api/3.8.14.Final
https://security.snyk.io/vuln/SNYK-JAVA-ORGJBOSSXNIO-6403375
=> [GHSA-7f88-5hhx-67m2] XNIO denial of service vulnerability

advisories/github-reviewed/2024/03/GHSA-vm8q-m57g-pff3/GHSA-vm8q-m57g-pff3.json
**Updates**
- References
**Comments**
add patch commit: https://github.com/django/django/commit/3394fc6132436eca89e997083bae9985fb7e761e, the commit msg shows it fixed this cve.
=> [GHSA-vm8q-m57g-pff3] Regular expression denial-of-service in Django

advisories/github-reviewed/2024/04/GHSA-33c5-9fx5-fvjm/GHSA-33c5-9fx5-fvjm.json
**Updates**
**Comments**
While merging two PRs modifying this CVE, the fixed versions for the kubernetes package are now wrong.
https://nvd.nist.gov/vuln/detail/CVE-2020-8559
https://github.com/kubernetes/kubernetes/issues/92914
https://groups.google.com/g/kubernetes-security-announce/c/JAIGG5yNROs
=> [GHSA-33c5-9fx5-fvjm] Privilege Escalation in Kubernetes 

advisories/github-reviewed/2024/04/GHSA-33c5-9fx5-fvjm/GHSA-33c5-9fx5-fvjm.json
The original version of this advisory correctly used package k8s.io/apimachinery, but with the wrong versioning:
- The versioning used v1.x.y, instead of v0.x.y
- k8s.io/apimachinery has a major version offset compared to k8s.io/kubernetes
- For example, k8s.io/apimachinery v0.18.6, which is affected by the CVE, matches k8s.io/kubernetes v1.18.6 (see https://github.com/kubernetes/apimachinery/releases/tag/v0.18.6)
The updated version of this advisory over-corrected, changing both the package and the versions affected:
- As per the CVE issue, the k8s.io/kubernetes versions affected are v1.x.y, not v0.x.y (see https://github.com/kubernetes/kubernetes/issues/92914)
- The fix itself is in the apimachinery package (see https://github.com/kubernetes/kubernetes/pull/92941/commits/1f991f8a2f5a73d5 …
=> [GHSA-33c5-9fx5-fvjm] Privilege Escalation in Kubernetes kube-apiserver

advisories/github-reviewed/2022/09/GHSA-c9h3-c6qj-hh7q/GHSA-c9h3-c6qj-hh7q.json
**Updates**
- Description
- References
**Comments**
Added patch commits and bug tracker entry that I found useful while triaging this vuln for a VDR analysis engagement, plus added back lost whitespace in the description
=> [GHSA-c9h3-c6qj-hh7q] Apache Kafka vulnerability can lead to brokers hitting OutOfMemoryException, causing Denial of Service

advisories/github-reviewed/2024/02/GHSA-32h7-7j94-8fc2/GHSA-32h7-7j94-8fc2.json
**Updates**
- CVSS
- Description
**Comments**
The DoS of the mobile app is just a side-effect. See https://github.com/c0rydoras/cves/tree/main/CVE-2024-1402
=> [GHSA-32h7-7j94-8fc2] Mattermost vulnerable to denial of service via large number of emoji reactions

advisories/github-reviewed/2022/02/GHSA-pf59-j7c2-rh6x/GHSA-pf59-j7c2-rh6x.json
**Updates**
**Comments**
The previously mentioned version "0.8.6" didn't appear to exist for the calico project at all. I pulled the corrected affected and patched versions from https://www.tigera.io/security-bulletins-tta-2020-001/.
=> [GHSA-pf59-j7c2-rh6x] Exposure of Sensitive Information to an Unauthorized Actor and Insertion of Sensitive Information Into Sent Data in Calico

advisories/github-reviewed/2024/05/GHSA-x9vc-6hfv-hg8c/GHSA-x9vc-6hfv-hg8c.json
**Updates**
- Description
- References
**Comments**
I'm a maintainer for Npgsql. It was unclear to us the security vulnerability author provided the template for the advisory, and that we had to edit it. The suggested changes trim down the summary, remove the POCs links and provide the correct affected and patched versions.
=> [GHSA-x9vc-6hfv-hg8c] Npgsql vulnerable to SQL Injection via Protocol Message Size Overflow

advisories/github-reviewed/2024/01/GHSA-3fwx-pjgw-3558/GHSA-3fwx-pjgw-3558.json
**Updates**
- Summary
**Comments**
=> [GHSA-3fwx-pjgw-3558] Moby (Docker Engine) Insufficiently restricted permissions on data directory

advisories/github-reviewed/2022/05/GHSA-48rh-qgjr-xfj6/GHSA-48rh-qgjr-xfj6.json
**Updates**
**Comments**
According to [Patch](https://github.com/jhy/jsoup/commit/c0b275361ce8409f85de3573d89f6a617f0084d5), I have verified that this vulnerability could not be triggered before 1.6.0.
=> [GHSA-48rh-qgjr-xfj6] Improper Neutralization of Input During Web Page Generation in Jsoup

advisories/github-reviewed/2022/05/GHSA-xphj-m9cc-8fmq/GHSA-xphj-m9cc-8fmq.json
**Updates**
**Comments**
According to the [patch](https://github.com/apache/groovy/commit/4df8b652aa018a5d5d1cda8fba938bf3422db31c), I confirm that the patch location is between 2.4.7 and 2.4.8.
=> [GHSA-xphj-m9cc-8fmq] Deserialization of Untrusted Data in Groovy

advisories/github-reviewed/2021/10/GHSA-qcgx-crrx-38v5/GHSA-qcgx-crrx-38v5.json
**Updates**
**Comments**
According to [Patch](https://github.com/vaadin/framework/commit/2fc98eaf9c0e2cd42cf4a66fb6d2cd2e9f0a08a9), vulnerability functions did not exist before 8.0.6, and I have verified that this vulnerability could not be triggered before 8.0.6.
=> [GHSA-qcgx-crrx-38v5] Denial of service in DataCommunicator class in Vaadin 8

advisories/github-reviewed/2020/01/GHSA-m8p2-495h-ccmh/GHSA-m8p2-495h-ccmh.json
**Updates**
**Comments**
According to the [patch](https://github.com/hibernate/hibernate-validator/commit/124b7dd6d9a4ad24d4d49f74701f05a13e56ceee), CVE-2019-10219 also affect [6.1.0.Alpha1,6.1.0.Alpha6].
=> [GHSA-m8p2-495h-ccmh] The SafeHtml annotation in Hibernate-Validator does not properly guard against XSS attacks

advisories/github-reviewed/2018/10/GHSA-f26x-pr96-vw86/GHSA-f26x-pr96-vw86.json
**Updates**
**Comments**
Add the .RELEASE suffix to describe the affected version more accurately.
=> [GHSA-f26x-pr96-vw86] Moderate severity vulnerability that affects org.springframework:spring-core

advisories/github-reviewed/2022/06/GHSA-pv7h-hx5h-mgfj/GHSA-pv7h-hx5h-mgfj.json
**Updates**
**Comments**
According to [Patch](https://github.com/alibaba/fastjson/commit/35db4adad70c32089542f23c272def1ad920a60d), vulnerability function did not exist before 1.2.25, and I have verified that this vulnerability could not be triggered before 1.2.25.
=> [GHSA-pv7h-hx5h-mgfj] Unsafe deserialization in com.alibaba:fastjson

advisories/github-reviewed/2022/01/GHSA-r58x-wjg8-63m9/GHSA-r58x-wjg8-63m9.json
**Updates**
**Comments**
According to Patch, I have verified that this vulnerability could not be triggered before 3.1.0.
=> [GHSA-r58x-wjg8-63m9] Denial of Service in Apache James

advisories/github-reviewed/2019/12/GHSA-24r8-fm9r-cpj2/GHSA-24r8-fm9r-cpj2.json
**Updates**
- Severity
**Comments**
According to [Patch](https://github.com/line/armeria/commit/b597f7a865a527a84ee3d6937075cfbb4470ed20), vulnerability function did not exist before 0.50.0, and I have verified that this vulnerability could not be triggered before 0.50.0.
=> [GHSA-24r8-fm9r-cpj2] Low severity vulnerability that affects com.linecorp.armeria:armeria

advisories/github-reviewed/2022/02/GHSA-88cc-g835-76rp/GHSA-88cc-g835-76rp.json
**Updates**
**Comments**
According to [Patch](https://github.com/spring-projects/spring-security/commit/a40f73521c0dd88b879ff6165d280e78bdf8154f), vulnerability function did not exist before 9.4.1212.jre6, and I have verified that this vulnerability could not be triggered before 9.4.1212.jre6.
=> [GHSA-88cc-g835-76rp] Improper Restriction of XML External Entity Reference

advisories/github-reviewed/2021/08/GHSA-9c8w-jrw3-q2c3/GHSA-9c8w-jrw3-q2c3.json
**Updates**
**Comments**
According to [Patch](https://github.com/nahsra/antisamy/commit/be6a42b2a3e2600c774d91f9fb830c44bfc217fc), vulnerability function did not exist before 1.4.5, and I have verified that this vulnerability could not be triggered before 1.4.5.
=> [GHSA-9c8w-jrw3-q2c3] Cross-site Scripting in OWASP AntiSamy

advisories/github-reviewed/2022/03/GHSA-mqvp-7rrg-9jxc/GHSA-mqvp-7rrg-9jxc.json
**Updates**
**Comments**
According to [Patch](https://github.com/apache/poi/commit/6622d9badb3590cb6190d912730548635a359dc0), vulnerability function did not exist before 3.8-beta1, and I have verified that this vulnerability could not be triggered before 3.8-beta1.
=> [GHSA-mqvp-7rrg-9jxc] Improper Input Validation and Allocation of Resources Without Limits or Throttling in poi-scratchpad

advisories/github-reviewed/2018/12/GHSA-5p52-j8pw-j7x5/GHSA-5p52-j8pw-j7x5.json
**Updates**
**Comments**
According to [Patch](https://github.com/Bedework/bw-webdav/commit/ccb87c2757bab531c53faf0637ee342a378caa7f), vulnerability function did not exist before 4.0.1, and I have verified that this vulnerability could not be triggered before 4.0.1.
=> [GHSA-5p52-j8pw-j7x5] Improper Restriction of XML External Entity Reference in bedework:bw-webdav

advisories/github-reviewed/2022/05/GHSA-gw5j-77f9-v2g2/GHSA-gw5j-77f9-v2g2.json
**Updates**
**Comments**
According to [patch](https://github.com/apache/cxf/commit/0b3894f57388b9955f2c33b2295223f2835cd7b3), This vulnerability also affect `org.apache.cxf:cxf-rt-rs-security-xml`.
=> [GHSA-gw5j-77f9-v2g2] Loop with Unreachable Exit Condition in Apache CXF

advisories/github-reviewed/2022/05/GHSA-89hj-xfx5-7q66/GHSA-89hj-xfx5-7q66.json
**Updates**
- References
**Comments**
add 4 patches:
https://github.com/django/django/commit/1170f285ddd6a94a65f911a27788ba49ca08c0b0
https://github.com/django/django/commit/6872f42757d7ef6a97e0b6ec5db4d2615d8a2bd8
https://github.com/django/django/commit/d63e20942f3024f24cb8cd85a49461ba8a9b6736
https://github.com/django/django/commit/380545bf85cbf17fc698d136815b7691f8d023ca
for v1.4, v1.5, v.16 and v1.7
=> [GHSA-89hj-xfx5-7q66] Django Reuses Cached CSRF Token

advisories/github-reviewed/2018/07/GHSA-x88j-93vc-wpmp/GHSA-x88j-93vc-wpmp.json
**Updates**
- References
**Comments**
add 2 patches:
https://github.com/django/django/commit/ac7c3a110f906e4dfed3a17451bf7fd9fcb81296	v1.2
https://github.com/django/django/commit/fbe2eead2fa9d808658ca582241bcacb02618840	v1.3
=> [GHSA-x88j-93vc-wpmp] Moderate severity vulnerability that affects django

advisories/github-reviewed/2024/02/GHSA-rc6h-qwj9-2c53/GHSA-rc6h-qwj9-2c53.json
**Updates**
**Comments**
From the fix commit https://github.com/apache/dolphinscheduler/commit/ef9ed3db55cb1647886b06c2b2c6a5cfcdccfb5c the change was to the dolphinscheduler-master component.
Apache also specify it specifically in the CVE json: https://github.com/CVEProject/cvelistV5/blob/1c8cd9a8eaea06fdc2108233b3c3d2144e097dd4/cves/2024/23xxx/CVE-2024-23320.json#L19
=> [GHSA-rc6h-qwj9-2c53] Apache DolphinScheduler vulnerable to arbitrary JavaScript execution as root for authenticated users

advisories/github-reviewed/2024/05/GHSA-4724-7jwc-3fpw/GHSA-4724-7jwc-3fpw.json
**Updates**
**Comments**
the vulnerable code is in go language and has identifier in go-language it seems to be an typo.
=> [GHSA-4724-7jwc-3fpw] Grafana Spoofing originalUrl of snapshots

advisories/github-reviewed/2023/09/GHSA-364c-vvqx-446c/GHSA-364c-vvqx-446c.json
**Updates**
- References
**Comments**
https://github.com/schollz/croc/pull/697
=> [GHSA-364c-vvqx-446c] Croc sender may place ANSI or CSI escape sequences in filename to attach receiver's terminal device

advisories/github-reviewed/2022/05/GHSA-9v8h-57gv-qch6/GHSA-9v8h-57gv-qch6.json
**Updates**
- References
**Comments**
add 3 patches:
https://github.com/django/django/commit/8bc36e726c9e8c75c681d3ad232df8e882aaac81
https://github.com/django/django/commit/412ed22502e11c50dbfee854627594f0e7e2c234
https://github.com/django/django/commit/7dd2dd08a79e388732ce00e2b5514f15bd6d0f6f
=> [GHSA-9v8h-57gv-qch6] Django vulnerable to Denial of Service via i18n middleware component

advisories/github-reviewed/2024/05/GHSA-jj54-5q2m-q7pj/GHSA-jj54-5q2m-q7pj.json
**Updates**
**Comments**
Removed protocol information from package name as this is the usual procedure with other GHSAs. Moreover, having package names starting with "https://" leads to import warnings in OWASP Dependency-Track, e.g.:
`[GitHubAdvisoryMirrorTask] Unable to create purl from GitHub Vulnerability. Skipping GO : https://pkg.go.dev/github.com/nats-io/nats-server/v2 for: GHSA-jj54-5q2m-q7pj`
=> [GHSA-jj54-5q2m-q7pj] NATS server TLS missing ciphersuite settings when CLI flags used

advisories/github-reviewed/2023/09/GHSA-92jh-gwch-jq38/GHSA-92jh-gwch-jq38.json
**Updates**
- Description
**Comments**
This report only is relevant to pocketmine/pocketmine-mp because that repo contains the class `LoginPacket` that does not properly validate the input values. The relevant package dealing with mapping JSON to PHP classes is a fork in https://github.com/pmmp/netresearch-jsonmapper
This report does not affect the original JsonMapper library, as having NULL entries in arrays is a defined and tested use case (admittedly an unexpected one). The original project has received several invalid vulnerability reports because of this incorrect attribution, as multiple "security report collector" companies spread this incorrect information through channels beyond the maintainers control.
=> [GHSA-92jh-gwch-jq38] PocketMine-MP server crash with certain invalid JSON payloads in `LoginPacket` due to dependency vulnerability (again)

advisories/github-reviewed/2023/11/GHSA-ph87-4x2g-6hp4/GHSA-ph87-4x2g-6hp4.json
**Updates**
**Comments**
The Package name is incorrect. It is recommended to change it to "/io.jenkins.plugins/neuvector-vulnerability-scanner". Reference source: https://mvnrepository.com/artifact/io.jenkins.plugins/neuvector-vulnerability-scanner You can see the Maven coordinates here
=> [GHSA-ph87-4x2g-6hp4] Jenkins NeuVector Vulnerability Scanner Plugin missing permission check

advisories/github-reviewed/2022/05/GHSA-g6h2-4x64-c59x/GHSA-g6h2-4x64-c59x.json
**Updates**
**Comments**
The Package name is incorrect. It is recommended to change it to "org.jenkins-ci.plugins:token-macro". Reference source: https://mvnrepository.com/artifact/org.jenkins-ci.plugins/token-macro You can see the Maven coordinates here
=> [GHSA-g6h2-4x64-c59x] Improper Restriction of XML External Entity Reference Jenkins Token Macro Plugin

advisories/github-reviewed/2022/05/GHSA-922h-x9qv-2274/GHSA-922h-x9qv-2274.json
**Updates**
**Comments**
The Package name is incorrect. It is recommended to change it to "org.jenkins-ci.plugins:pegdown-formatter". Reference source: https://mvnrepository.com/artifact/org.jenkins-ci.plugins/pegdown-formatter You can see the Maven coordinates here
=> [GHSA-922h-x9qv-2274] Jenkins PegDown Formatter Plugin has Cross-site Scripting vulnerability

advisories/github-reviewed/2024/03/GHSA-c5q2-7r4c-mv6g/GHSA-c5q2-7r4c-mv6g.json
As reported in https://pkg.go.dev/vuln/GO-2024-2631, the go module `gopkg.in/square/go-jose.v2` is also affected by this reported vulnerability. Despite of been a deprecated repository, there is still a lot of software using it. So it'd be great to add it to this list of affected packages.
=> [GHSA-c5q2-7r4c-mv6g]: add missing package to the list of affected packages

advisories/github-reviewed/2024/05/GHSA-6wvf-f2vw-3425/GHSA-6wvf-f2vw-3425.json
**Updates**
**Comments**
For some products, updating to v5.29.3 is easier than v5.30.1. However, if they do that, many vuln scanners will still claim they are vulnerable as v5.29.3 < v5.30.1. Adding this make it clear v5.29.3 is also safe. See https://github.com/containers/image/releases/tag/v5.29.3 for proof.
=> [GHSA-6wvf-f2vw-3425] github.com/containers/image allows unexpected authenticated registry accesses

advisories/github-reviewed/2024/05/GHSA-8hqg-whrw-pv92/GHSA-8hqg-whrw-pv92.json
**Updates**
**Comments**
Removed protocol information from package name as this is the usual procedure with other GHSAs. Moreover, having package names starting with "https://" leads to import warnings in OWASP Dependency-Track, e.g.:
`[GitHubAdvisoryMirrorTask] Unable to create purl from GitHub Vulnerability. Skipping GO : https://github.com/ollama/ollama for: GHSA-8hqg-whrw-pv92`
=> [GHSA-8hqg-whrw-pv92] Ollama does not validate the format of the digest (sha256 with 64 hex digits)

advisories/github-reviewed/2024/05/GHSA-qjqp-xr96-cj99/GHSA-qjqp-xr96-cj99.json
**Updates**
- References
**Comments**
Suggesting adding the actiontext component of Rails versions 7.0 and 7.1 as documented as being affected by the Rails team at https://discuss.rubyonrails.org/t/xss-vulnerabilities-in-trix-editor/85803
https://rubyonrails.org/2024/5/17/Rails-Versions-7-0-8-3-has-been-released
https://rubyonrails.org/2024/5/17/Rails-Versions-7-0-8-2-and-7-1-3-3-have-been-released
Not sure if this is the appropriate way to manage these situations where one product embeds another, but seems reasonable.
=> [GHSA-qjqp-xr96-cj99] Trix Editor Arbitrary Code Execution Vulnerability

advisories/github-reviewed/2024/06/GHSA-cjcc-p67m-7qxm/GHSA-cjcc-p67m-7qxm.json
**Updates**
**Comments**
Dependabot is issuing upgrades for 2.0.49.1 as its above 2.0.49, but the fix is not until 2.0.50. This will prevent Dependabot improperly upgrading projects and calling it "resolved". So we correct the affected version property.
You can see the fix in 2.0.50 - https://github.com/yiisoft/yii2/blob/master/framework/CHANGELOG.md#2050-may-30-2024
=> [GHSA-cjcc-p67m-7qxm] Unsafe Reflection in base Component class in yiisoft/yii2

advisories/github-reviewed/2024/06/GHSA-qg5r-95m4-mjgj/GHSA-qg5r-95m4-mjgj.json
**Updates**
**Comments**
Just reviewing the 2 recent Yii2 CVEs and both were improperly tagged with "affected versions" - sending poor Dependabot on a rampage of mistakes.
This vulnerability was introduced in 2.0.43 as seen here (https://github.com/yiisoft/yii2/commit/8cc9aeb2f0b2ffe02fb54a817064e9da75512706) and referenced in the CVE as such. This means the proper range is greater than (or equal) to 2.0.43 and less than 2.0.50 (where it was patched)
=> [GHSA-qg5r-95m4-mjgj] Reflected Cross-site Scripting in yiisoft/yii2 Debug mode

advisories/github-reviewed/2024/03/GHSA-c5q2-7r4c-mv6g/GHSA-c5q2-7r4c-mv6g.json
**Updates**
- Description
**Comments**
Patch description is ambiguous as mentioned versions are not available for gopkg.in/square/go-jose.v2
=> [GHSA-c5q2-7r4c-mv6g] Go JOSE vulnerable to Improper Handling of Highly Compressed Data (Data Amplification)

advisories/github-reviewed/2022/02/GHSA-6hr9-4692-fch9/GHSA-6hr9-4692-fch9.json
**Updates**
**Comments**
This vulnerability is not related to the npm package "effect": https://www.npmjs.com/package/effect.
It does not seem to be tied to a package manager at all. The GitHub project claims to be for the Node project "effect", but the actual npm package is entirely different.
In addition, the Snyk advisory has revoked this vulnerability. This advisory should probably be withdrawn.
=> [GHSA-6hr9-4692-fch9] OS Command Injection in effect

advisories/github-reviewed/2020/02/GHSA-3mcp-9wr4-cjqf/GHSA-3mcp-9wr4-cjqf.json
**Updates**
**Comments**
According to [Patch](https://github.com/dropwizard/dropwizard/commit/d87d1e4f8e20f6494c0232bf8560c961b46db634), this vulnerability was introduced from 1.3.0.
=> [GHSA-3mcp-9wr4-cjqf] Remote Code Execution (RCE) vulnerability in dropwizard-validation

advisories/github-reviewed/2018/10/GHSA-hrmr-f5m6-m9pq/GHSA-hrmr-f5m6-m9pq.json
**Updates**
**Comments**
https://nvd.nist.gov/vuln/detail/CVE-2018-11771#range-11747091
=> [GHSA-hrmr-f5m6-m9pq] Moderate severity vulnerability that affects org.apache.commons:commons-compress

advisories/github-reviewed/2022/05/GHSA-wx54-3278-m5g4/GHSA-wx54-3278-m5g4.json
**Updates**
**Comments**
According to [Patch](https://github.com/spring-projects/spring-security/commit/a40f73521c0dd88b879ff6165d280e78bdf8154f), this vulnerability was introduced from 5.2.0.RELEASE.
=> [GHSA-wx54-3278-m5g4] Integer overflow in BCrypt class in Spring Security

advisories/github-reviewed/2024/03/GHSA-m4pq-fv2w-6hrw/GHSA-m4pq-fv2w-6hrw.json
**Updates**
**Comments**
The [original advisory](https://github.com/denoland/deno/security/advisories/GHSA-m4pq-fv2w-6hrw) does indicate `deno_runtime` as the package; however, the version constraints do not appear to align with the [available versions for deno_runtime](https://crates.io/crates/deno_runtime/versions) since all publised versions for that particular crate are still pre-1.0, so it would seem that perhaps `deno` would be the better package name to use here given the current version ranges.
Alternatively the version ranges could be updated to reflect the specific versioning for the `deno_runtime` sub-component, but I wasn't entirely sure how to figure that out
=> [GHSA-m4pq-fv2w-6hrw] Deno's deno_runtime vulnerable to interactive permission prompt spoofing via improper ANSI stripping

advisories/github-reviewed/2024/01/GHSA-7452-xqpj-6rpc/GHSA-7452-xqpj-6rpc.json
**Updates**
- Summary
**Comments**
=> [GHSA-7452-xqpj-6rpc] moby Access to remapped root allows privilege escalation to real root

advisories/github-reviewed/2024/01/GHSA-6fj5-m822-rqx8/GHSA-6fj5-m822-rqx8.json
=> [GHSA-6fj5-m822-rqx8] moby docker daemon crash during image pull of malicious image

advisories/github-reviewed/2024/04/GHSA-624g-8qjg-8qxf/GHSA-624g-8qjg-8qxf.json
**Updates**
**Comments**
An author published a patch to another version: 0.9.2
https://github.com/edmundhung/conform/security/advisories/GHSA-624g-8qjg-8qxf
Here is a commit: https://github.com/edmundhung/conform/commit/cb604dd58b99e2d12716d901a23bfca724e741ef
=> [GHSA-624g-8qjg-8qxf] Conform contains a Prototype Pollution Vulnerability in `parseWith...` function

advisories/github-reviewed/2024/02/GHSA-3hrr-xwvg-hxvr/GHSA-3hrr-xwvg-hxvr.json
**Updates**
**Comments**
This was discussed at https://github.com/keycloak/keycloak/issues/29603 and addressed by https://github.com/keycloak/keycloak/pull/27408 as per [this comment](https://github.com/keycloak/keycloak/issues/29603#issuecomment-2127499627). That PR was merged on `2024-03-01T15:14:27Z`.
[Keycloak v24.0.0](https://github.com/keycloak/keycloak/releases/tag/24.0.0#:~:text=27297), released on `2024-03-04T09:49:41Z`, already contains the fix.
=> [GHSA-3hrr-xwvg-hxvr] Keycloak DoS via account lockout

advisories/github-reviewed/2024/04/GHSA-25w4-hfqg-4r52/GHSA-25w4-hfqg-4r52.json
**Updates**
**Comments**
See https://quarkus.io/blog/quarkus-3-2-10-final-released/, CVE-2023-5675 is mentioned as fixed in this release note. I've pinged them re 3.8.4/5 LTS and they have responded it should also be fixed in the current LTS stream - but I haven't found any written prove so far.
=> [GHSA-25w4-hfqg-4r52] Quarkus: authorization flaw in quarkus resteasy reactive and classic

advisories/github-reviewed/2024/04/GHSA-mx3p-fhpw-x6rv/GHSA-mx3p-fhpw-x6rv.json
**Updates**
**Comments**
CVE appears to have been patched in version 6.7.5
https://github.com/tecnickcom/TCPDF/compare/6.7.4...6.7.5
=> [GHSA-mx3p-fhpw-x6rv] TCPDF vulnerable to Regular Expression Denial of Service

advisories/github-reviewed/2022/05/GHSA-qc99-g3wm-hgxr/GHSA-qc99-g3wm-hgxr.json
**Updates**
- References
**Comments**
add three patches for three versions:
https://github.com/django/django/commit/6eefa521be3c658dc0b38f8d62d52e9801e198ab	v0.90
https://github.com/django/django/commit/d31e39173c29537e6a1613278c93634c18a3206e	v0.91
https://github.com/django/django/commit/a132d411c6986418ee6c0edc331080aa792fee6e	v0.95
the official report shows them: https://docs.djangoproject.com/en/3.2/releases/security/
the vulnerable versions are also updated according to the official vulnerability report:
https://www.djangoproject.com/weblog/2006/aug/16/compilemessages/
=> [GHSA-qc99-g3wm-hgxr] Django Arbitrary Code Execution

advisories/github-reviewed/2024/06/GHSA-m5vv-6r4h-3vj9/GHSA-m5vv-6r4h-3vj9.json
**Updates**
**Comments**
Updates the version range to account for the mitgiated release of MSAL.NET that includes legacy frameworks (UWP, Xamarin) that is no longer available in the latest branch (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4806#issuecomment-2178960340)
=> [GHSA-m5vv-6r4h-3vj9] Azure Identity Libraries and Microsoft Authentication Library Elevation of Privilege Vulnerability

advisories/github-reviewed/2024/06/GHSA-cr7j-rwmv-vgch/GHSA-cr7j-rwmv-vgch.json
**Updates**
- CVSS
**Comments**
Duplicate of https://github.com/aimeos/aimeos-core/security/advisories/GHSA-rhc2-23c2-ww7c
Affected versions are only 2024.04.x below 2024.04.5
=> [GHSA-cr7j-rwmv-vgch] aimeos-core arbitrary file uopload vulnerability

advisories/github-reviewed/2024/06/GHSA-cchp-3rq6-69wj/GHSA-cchp-3rq6-69wj.json
**Updates**
- CWEs
**Comments**
I believe that CWE-639 + CWE-284 more accurately reflect the specific nature of this IDOR vulnerability.
[reference]
[CWE-639: Authorization Bypass Through User-Controlled Key](https://cwe.mitre.org/data/definitions/639.html)
=> [GHSA-cchp-3rq6-69wj] events2 TYPO3 extension insecure direct object reference (IDOR) vulnerability

advisories/github-reviewed/2024/04/GHSA-m6q9-p373-g5q8/GHSA-m6q9-p373-g5q8.json
**Updates**
- References
**Comments**
Added fix commit related to the this patch from 24.0.3
=> [GHSA-m6q9-p373-g5q8] Keycloak's unvalidated cross-origin messages in checkLoginIframe leads to DDoS

advisories/github-reviewed/2021/06/GHSA-ww39-953v-wcq6/GHSA-ww39-953v-wcq6.json
**Updates**
- Description
**Comments**
Version 3.0.0 (and before) did not use RegEx to detect and extract the parent path from a glob string. It used do-while loop and thepath.dirname method:
https://github.com/gulpjs/glob-parent/tree/bbe92930283eb87170b48f180183876508b7e6d7
https://github.com/gulpjs/glob-parent/tree/bbe92930283eb87170b48f180183876508b7e6d7/index.js
Also, the PoC of the ReDoS does not work for version 3.0.0.
=> [GHSA-ww39-953v-wcq6] glob-parent vulnerable to Regular Expression Denial of Service in enclosure regex

advisories/github-reviewed/2023/11/GHSA-jjfh-589g-3hjx/GHSA-jjfh-589g-3hjx.json
**Updates**
- Description
- References
- Summary
**Comments**
The spring-boot-actuator is part of the spring-boot project/repository. 
The vulnerable code is in the `org.springframework.boot:spring-boot-actuator` jar.
Snyk also tags this as such:
https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKBOOT-6226862
=> [GHSA-jjfh-589g-3hjx] Spring Boot denial of service vulnerability

advisories/github-reviewed/2024/04/GHSA-j628-q885-8gr5/GHSA-j628-q885-8gr5.json
**Updates**
- References
**Comments**
Improve the reference by attaching issue link and code fix commit link
=> [GHSA-j628-q885-8gr5] Keycloak vulnerable to log Injection during WebAuthn authentication or registration

advisories/github-reviewed/2022/02/GHSA-8grg-q944-cch5/GHSA-8grg-q944-cch5.json
**Updates**
- References
**Comments**
Currently listed 'org.infinispan:infinispan-hibernate-cache-v53' package does not match with the CVE description nor does it match with other CVE sources: https://nvd.nist.gov/vuln/detail/CVE-2019-14900 and https://security.snyk.io/vuln/SNYK-JAVA-ORGHIBERNATE-584563
Also added fix commit links for various branches.
=> [GHSA-8grg-q944-cch5] SQL Injection in Hibernate ORM

advisories/github-reviewed/2023/11/GHSA-q24v-hpg3-v3jp/GHSA-q24v-hpg3-v3jp.json
**Updates**
- References
**Comments**
The affected package name is actually io.projectreactor.netty:reactor-netty-core.
Code fixes are located in reactor-netty-core. See the added commit links for the CVE.
=> [GHSA-q24v-hpg3-v3jp] Reactor Netty HTTP Server denial of service vulnerability

advisories/github-reviewed/2024/06/GHSA-qqcv-vg9f-5rr3/GHSA-qqcv-vg9f-5rr3.json
**Updates**
**Comments**
This is not a current vulnerability. It's already been fixed. Incorrect report.
=> [GHSA-qqcv-vg9f-5rr3] litellm vulnerable to improper access control in team management

advisories/github-reviewed/2023/08/GHSA-r726-vmfq-j9j3/GHSA-r726-vmfq-j9j3.json
**Updates**
- Description
**Comments**
typo in a URL  https://blog.xss.am/2023/08/CVE-2023-39968-jupyter-token-leak/ to  https://blog.xss.am/2023/08/cve-2023-39968-jupyter-token-leak/
=> [GHSA-r726-vmfq-j9j3]  Open Redirect Vulnerability in jupyter-server

advisories/github-reviewed/2022/11/GHSA-22wj-vf5f-wrvj/GHSA-22wj-vf5f-wrvj.json
**Updates**
**Comments**
Relevant code wasn't included until version 1.4.198. [Snyk](https://security.snyk.io/vuln/SNYK-JAVA-COMH2DATABASE-3146851)
This matches the code too: [vulnerable](https://github.com/h2database/h2database/blob/96832bf5a97cdc0adc1f2066ed61c54990d66ab5/h2/src/main/org/h2/server/web/WebServer.java#L346-L347) vs. [non-vulnerable](https://github.com/h2database/h2database/blob/version-1.4.196/h2/src/main/org/h2/server/web/WebServer.java#L302)
=> [GHSA-22wj-vf5f-wrvj] Password exposure in H2 Database 

advisories/github-reviewed/2022/05/GHSA-hh32-7344-cg2f/GHSA-hh32-7344-cg2f.json
**Updates**
**Comments**
According to the description of the vulnerability announcement Affected Spring Products and Versions at https://spring.io/security/cve-2022-22978.
The affected version has an error and is recommended to be modified to 5.6.0<=version<5.6.4, 5.5.0<=version<5.5.7, version<5.4.11
Reference link: https://spring.io/security/cve-2022-22978
The detailed description is as follows:
Affected Spring Products and Versions
Spring Security
5.4.x prior to 5.4.11
5.5.x prior to 5.5.7
5.6.x prior to 5.6.4
Earlier unsupported versions
Mitigation
Users should update to a version that includes fixes. 5.5.x users should upgrade to 5.5.7 or greater. 5.6.x users should upgrade to 5.6.4 or greater. Releases that have fixed this issue include:
=> [GHSA-hh32-7344-cg2f] Authorization bypass in Spring Security

advisories/github-reviewed/2022/06/GHSA-rc57-9r3x-98cq/GHSA-rc57-9r3x-98cq.json
**Updates**
- References
**Comments**
The Drools project has moved in GitHub to the Apache Incubator, so the link to PR 3808 was broken.
=> [GHSA-rc57-9r3x-98cq] XML External Entity Reference in drools

advisories/github-reviewed/2024/07/GHSA-248v-346w-9cwc/GHSA-248v-346w-9cwc.json
**Updates**
- CVSS
- Severity
**Comments**
This is clearly not a vulnerability, just a change to the certificate list.
=> [GHSA-248v-346w-9cwc] Certifi removes GLOBALTRUST root certificate

advisories/github-reviewed/2022/11/GHSA-vp35-85q5-9f25/GHSA-vp35-85q5-9f25.json
=> [GHSA-vp35-85q5-9f25] Container build can leak any path on the host into the container

advisories/github-reviewed/2022/02/GHSA-8fvr-5rqf-3wwh/GHSA-8fvr-5rqf-3wwh.json
=> [GHSA-8fvr-5rqf-3wwh] Information Exposure in Docker Engine

advisories/github-reviewed/2022/02/GHSA-v4h8-794j-g8mm/GHSA-v4h8-794j-g8mm.json
=> [GHSA-v4h8-794j-g8mm] Arbitrary File Override in Docker Engine

advisories/github-reviewed/2024/01/GHSA-qrqr-3x5j-2xw9/GHSA-qrqr-3x5j-2xw9.json
=> [GHSA-qrqr-3x5j-2xw9] Docker Moby Authentication Bypass

advisories/github-reviewed/2022/05/GHSA-v2cv-wwxq-qq97/GHSA-v2cv-wwxq-qq97.json
=> [GHSA-v2cv-wwxq-qq97] Moby Docker cp broken with debian containers

advisories/github-reviewed/2021/05/GHSA-vj3f-3286-r4pf/GHSA-vj3f-3286-r4pf.json
**Updates**
- Severity
**Comments**
=> [GHSA-vj3f-3286-r4pf] Path Traversal in Docker

advisories/github-reviewed/2022/05/GHSA-r4ph-mx67-x58p/GHSA-r4ph-mx67-x58p.json
**Updates**
**Comments**
The composer package name `shopware/shopware` refers to `Shopware 5` and is a totally different system. See https://github.com/shopware5/shopware/blob/5.7/composer.json#L2
We just renamed the GitHub repository name from `shopware/platform` to `shopware/shopware`  a while ago. 
This urgently needs to be fixed, as it spreads misinformation about a wrong security issue on a project that is not affected
=> [GHSA-r4ph-mx67-x58p] Shopware database password is leaked to an unauthenticated users

advisories/github-reviewed/2023/09/GHSA-rrjw-j4m2-mf34/GHSA-rrjw-j4m2-mf34.json
**Updates**
- CWEs
- Description
**Comments**
This proposes two changes, with separate rationales, that I think are best made together:
- While working on the newer advisory https://github.com/advisories/GHSA-98p4-xjmm-8mfh for a related vulnerability, and when updating its CWEs ([#4316](https://github.com/github/advisory-database/pull/4316)), I noticed that this prior advisory did not list any CWEs, and that the original reporter [vin01](https://github.com/vin01) had attempted to add [CWE-88](https://cwe.mitre.org/data/definitions/88.html), which I believe is a correct and applicable CWE here. That attempt was part of [#3253](https://github.com/github/advisory-database/pull/3253), and I am unsure why that was closed without merging, but it may have been related to a …
=> [GHSA-rrjw-j4m2-mf34] gix-transport code execution vulnerability

advisories/github-reviewed/2023/04/GHSA-g5h3-w546-pj7f/GHSA-g5h3-w546-pj7f.json
**Updates**
**Comments**
Older versions of the package as mentioned in the description are affected by this vulnerability. Same is highlighted in the maven repository
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-actuator-autoconfigure
=> [GHSA-g5h3-w546-pj7f] Spring Boot Security Bypass with Wildcard Pattern Matching on Cloud Foundry

advisories/github-reviewed/2024/07/GHSA-74r5-g7vc-j2v2/GHSA-74r5-g7vc-j2v2.json
**Updates**
- Description
**Comments**
According to the [comment](https://github.com/unicode-org/icu4x/issues/5196#issuecomment-2214711069), the version in which the vulnerability was fixed is `0.10.3`, and version `0.10.4` is currently unpublished (unicode-org/icu4x#5197 was closed). In PR rustsec/advisory-db#2007, the patched version was updated to `0.10.3`
=> [GHSA-74r5-g7vc-j2v2] zerovec-derive incorrectly uses `#[repr(packed)]`

advisories/github-reviewed/2022/02/GHSA-gc58-v8h3-x2gr/GHSA-gc58-v8h3-x2gr.json
**Updates**
**Comments**
It appears that this affected the way tomcat was packaged within specific distributions rather than actually affecting the maven artifacts per https://lists.apache.org/thread/0z644xfjo49pn2oxcp9qslkvhhw4tb7q.  I wasn't sure how to best show that though, should this just be marked as withdrawn or something?
=> [GHSA-gc58-v8h3-x2gr] Incorrect Default Permissions in Apache Tomcat

advisories/github-reviewed/2024/07/GHSA-phg7-8mm9-gj88/GHSA-phg7-8mm9-gj88.json
**Updates**
- CVSS
- Description
- References
- Severity
**Comments**
Changed references and description to official MITRE details. Also changed CVSS vector because a user account is needed for this vulnerability
=> [GHSA-phg7-8mm9-gj88] EGroupware mishandles an ORDER BY clause

advisories/github-reviewed/2024/07/GHSA-43wq-xrcm-3vgr/GHSA-43wq-xrcm-3vgr.json
**Updates**
- CVSS
- CWEs
- Description
- Severity
**Comments**
The code in question (https://github.com/discordjs/opus/blob/814e500c2785c5207ace19650192629beba2728b/src/node-opus.cc#L47-L48) does lack checks to ensure the arguments provided in are castable to a number, but this is not something that can be exploited remotely. OpusEncoders should not be made ever with user-provided values that aren't sanitized, as it could potentially cause far bigger issues in opus itself
=> [GHSA-43wq-xrcm-3vgr] @discordjs/opus vulnerable to Denial of Service

advisories/github-reviewed/2024/07/GHSA-876p-c77m-x2hc/GHSA-876p-c77m-x2hc.json
**Updates**
- Description
**Comments**
AG Grid has resolved this security vulnerability in v32.0.1 which is now available.
Specifically, this issue was fixed by:
https://github.com/ag-grid/ag-grid/pull/8290
=> [GHSA-876p-c77m-x2hc] ag-grid-community were discovered to contain a prototype pollution via the _.mergeDeep function

advisories/github-reviewed/2024/07/GHSA-4wm9-3qmv-gvxj/GHSA-4wm9-3qmv-gvxj.json
**Updates**
- CVSS
- Severity
**Comments**
False accusation of criticality. These are internal helper functions, not explicitly documented or intended for usage by the user.
=> [GHSA-4wm9-3qmv-gvxj] jsonic was discovered to contain a prototype pollution via the function empty.

advisories/github-reviewed/2024/05/GHSA-49jc-r788-3fc9/GHSA-49jc-r788-3fc9.json
**Updates**
**Comments**
This removes `gix-fs` as an affected crate, as I have already done in [the repo-level advisory](https://github.com/Byron/gitoxide/security/advisories/GHSA-49jc-r788-3fc9). As discussed at https://github.com/Byron/gitoxide/discussions/1437#discussioncomment-9954713, a reexamination of this vulnerability revealed that, while the other listed crates were affected, `gix-fs` was not.
This mistake here was mine in my original analysis. As detailed in https://github.com/Byron/gitoxide/discussions/1437, this and another vulnerability of higher severity (CVE-2024-35186) were fixed together. The affected crates overlap but are not exactly the same. It was known that `gix-ref` was affected here and not there, but I had missed that `gix-fs` was affected …
=> [GHSA-49jc-r788-3fc9] gix refs and paths with reserved Windows device names access the devices

advisories/github-reviewed/2024/06/GHSA-qfjh-mvq6-c5p8/GHSA-qfjh-mvq6-c5p8.json
**Updates**
- Resolved product: Jan v0.5.2
**Comments**
Jan resolved the issue in Jan v0.5.2, and depre‌‌cated the @janhq/core pac‌‌kage. Could you kindly double-check if the problem still exists?
=> [GHSA-qfjh-mvq6-c5p8] Jan path traversal vulnerability

advisories/github-reviewed/2022/05/GHSA-f4c9-cqv8-9v98/GHSA-f4c9-cqv8-9v98.json
**Updates**
- CVSS
- References
- Severity
**Comments**
As mentioned in Snyk and in the GitHub issue comment written by lib maintainer, the issue is no longer deemed a vulnerability. Please remove the classification as a vulnerability.
=> [GHSA-f4c9-cqv8-9v98] Insufficient Granularity of Access Control in JSDom

advisories/github-reviewed/2024/07/GHSA-hhwc-gh8h-9rrp/GHSA-hhwc-gh8h-9rrp.json
**Updates**
**Comments**
XSLTResourceStream.java is in wicket-util see https://github.com/apache/wicket/blob/d7533716bf63b44c73a4a87193087762cd22f858/wicket-util/src/main/java/org/apache/wicket/util/resource/XSLTResourceStream.java#L4.  Also, apache have in many cases started adding more precise affected maven artifacts to [their cve 5 record data](https://github.com/CVEProject/cvelistV5/blob/a23d19ff53a681bd80ee7e0573f61d3a75cbee13/cves/2024/36xxx/CVE-2024-36522.json#L18), so it may be worth looking into if any of GitHub's parsing might be able to take advantage of that when available
=> [GHSA-hhwc-gh8h-9rrp] Apache Wicket: Remote code execution via XSLT injection

advisories/github-reviewed/2023/10/GHSA-m425-mq94-257g/GHSA-m425-mq94-257g.json
**Updates**
**Comments**
I believe this relates to CVE-2023-44487.  Why isn't it referenced anywhere on https://github.com/advisories/GHSA-m425-mq94-257g?
=> [GHSA-m425-mq94-257g] gRPC-Go HTTP/2 Rapid Reset vulnerability

advisories/github-reviewed/2022/05/GHSA-rfmp-97jj-h8m6/GHSA-rfmp-97jj-h8m6.json
**Updates**
**Comments**
If spring-core is affected, it means the spring package is also affected since spring was relocated to spring-core.
=> [GHSA-rfmp-97jj-h8m6] Improper Output Neutralization for Logs in Spring Framework

advisories/github-reviewed/2024/06/GHSA-q25c-c977-4cmh/GHSA-q25c-c977-4cmh.json
**Updates**
- Description
- References
- Summary
**Comments**
Patch has been released:
https://github.com/langchain-ai/langchain/pull/24451
https://github.com/langchain-ai/langchain/releases/tag/langchain-community%3D%3D0.2.9
The original CVE was not associated with the correct package. Huntr does not support mono-repos at the moment, so many issues get classified as corresponding to langchain package, even though the code corresponds to the langchain-community package. The report iself was also unclear and did not differentiate between the repository vs. the package.
=> [GHSA-q25c-c977-4cmh] Server-Side Request Forgery in langchain

advisories/github-reviewed/2024/07/GHSA-x3m3-4wpv-5vgc/GHSA-x3m3-4wpv-5vgc.json
**Updates**
**Comments**
requirejs fixed Prototype Pollution Vulnerability in 2.3.7
See more info: 
https://github.com/requirejs/r.js/issues/1015
https://github.com/requirejs/requirejs/issues/1854
https://security.snyk.io/vuln/SNYK-JS-REQUIREJS-5416713
=> [GHSA-x3m3-4wpv-5vgc] jrburke requirejs vulnerable to prototype pollution

advisories/github-reviewed/2024/05/GHSA-p343-9qwp-pqxv/GHSA-p343-9qwp-pqxv.json
**Updates**
- CVSS
- Description
- Severity
**Comments**
The vulnerability was published by the vendor: https://neo4j.com/security/cve-2024-34517/
It requires admin privileges to exploit and is only relevant in Enterprise editions between versions 5.0.0 and 5.0.18
=> [GHSA-p343-9qwp-pqxv] Neo4j Cypher component mishandles IMMUTABLE privileges

advisories/github-reviewed/2024/07/GHSA-x72p-g37q-4xr9/GHSA-x72p-g37q-4xr9.json
**Updates**
**Comments**
This CVE is invalid because it relies on cookie theft and the cookie was not stolen by exploiting an application layer vulnerability (e.g. XSS).
The reported issue affects every application that uses cookies.
If you steal users' cookies, you can obviously impersonate them and access their resources; this is a security issue if you can steal the cookie by exploiting a vulnerability in the application (SFTPGo in this case), but that's not what happens here.
This is not new: for example, Google is working on a new standard, [Device Bound Session Credentials (DBSC)](https://blog.chromium.org/2024/04/fighting-cookie-theft-using-device.html), to mitigate issues like this.
The blog post also reports an Insecure Direct Object Reference (IDOR) …
=> [GHSA-x72p-g37q-4xr9] SFTPGo's JWT implmentation lacks certain security measures

advisories/github-reviewed/2024/07/GHSA-v23v-6jw2-98fq/GHSA-v23v-6jw2-98fq.json
**Updates**
**Comments**
Add patch for 25.0.6 per https://github.com/moby/moby/releases/tag/v25.0.6
=> [GHSA-v23v-6jw2-98fq] Authz zero length regression

advisories/github-reviewed/2022/08/GHSA-mv48-hcvh-8jj8/GHSA-mv48-hcvh-8jj8.json
**Updates**
- Description
- Summary
**Comments**
I've removed the redundant "Vitejs" from the dependency's name.
=> [GHSA-mv48-hcvh-8jj8] Vitejs Vite before v2.9.13 vulnerable to directory traversal via crafted URL to victim's service

advisories/github-reviewed/2024/06/GHSA-mr7h-w2qc-ffc2/GHSA-mr7h-w2qc-ffc2.json
**Updates**
**Comments**
The code in question was removed: https://github.com/Lightning-AI/pytorch-lightning/pull/20039. 
Release: https://github.com/Lightning-AI/pytorch-lightning/releases/tag/2.3.3
=> [GHSA-mr7h-w2qc-ffc2] pytorch-lightning vulnerable to Arbitrary File Write via /v1/runs API endpoint

advisories/github-reviewed/2024/07/GHSA-28mc-g557-92m7/GHSA-28mc-g557-92m7.json
**Updates**
- Severity
**Comments**
1.1.2 released containing https://github.com/75lb/deep-merge/commit/a68541fac3c2372f1ca67effad825990ad8046e1
=> [GHSA-28mc-g557-92m7] @75lb/deep-merge Prototype Pollution vulnerability

advisories/github-reviewed/2024/05/GHSA-78h3-pg4x-j8cv/GHSA-78h3-pg4x-j8cv.json
**Updates**
- Summary
**Comments**
There are two packages with very similar names "libxmljs" and "libxmljs2". Apparently libxmljs2 is the one with the vulnerability, but the information about affected versions did not match the package version, which is currently "0.35.0", instead of "1.0.11" which is "libxmljs" latest version. Note that libxmljs2 does not depend on libxmljs.
=> [GHSA-78h3-pg4x-j8cv] libxmljs vulnerable to type confusion when parsing specially crafted XML

advisories/github-reviewed/2024/07/GHSA-g3ch-rx76-35fx/GHSA-g3ch-rx76-35fx.json
**Updates**
- CVSS
**Comments**
Vulnerability requires prior JS code execution rights in order to pollute DOM styling properties via prototypal inheritance.
In other words, you need to be able to load a library or execute some other arbitrary code in order to utilize the exploit. 
Which begs the question: If the attacker can already execute arbitrary code, why bother with the exploit? They're only going to create more work for themselves in order to gain the same level of rights they already had.
=> [GHSA-g3ch-rx76-35fx] vue-template-compiler vulnerable to client-side Cross-Site Scripting (XSS)

advisories/github-reviewed/2024/07/GHSA-v23v-6jw2-98fq/GHSA-v23v-6jw2-98fq.json
It appears that the fixed version mentioned in the advisory is incorrect. According to the [Docker Security Advisory](https://www.docker.com/blog/docker-security-advisory-docker-engine-authz-plugin/), the updated versions should be `> v23.0.14`, `> v26.1.4`, and `> v27.1.0`.
For verification, I reviewed the code and found discrepancies in the advisory.
For example: In the 26.0 branch, the CVE fix [commit](https://github.com/moby/moby/commit/411e817ddf710ff8e08fa193da80cb78af708191) is included in version [v26.1.5](https://github.com/moby/moby/blob/411e817ddf710ff8e08fa193da80cb78af708191/pkg/authorization/authz.go#L58) but is not present in [v26.1.4](https://github.com/moby/moby/blob/v26.1.4/pkg/authorization/authz.go).
Additionally, the advisory mentions a version `v23.0.14`, but there …
=> [GHSA-v23v-6jw2-98fq] Update patched version to the proper one

advisories/github-reviewed/2024/06/GHSA-cgvx-9447-vcch/GHSA-cgvx-9447-vcch.json
**Updates**
**Comments**
The package's changelog states that 3.8.2 resolves CVE-2024-39705
=> [GHSA-cgvx-9447-vcch] ntlk unsafe deserialization vulnerability

advisories/github-reviewed/2022/03/GHSA-3mpp-xfvh-qh37/GHSA-3mpp-xfvh-qh37.json
**Updates**
**Comments**
https://github.com/RIAEvangelist/node-ipc/compare/10.1.0...12.0.0
the latest package.json does not include peacenotwar malware anymore
=> [GHSA-3mpp-xfvh-qh37] node-ipc behavior change

advisories/github-reviewed/2024/08/GHSA-49q7-c7j4-3p7m/GHSA-49q7-c7j4-3p7m.json
**Updates**
- Severity
**Comments**
Fixed in 6.5.7.
See more info:
https://github.com/indutny/elliptic/pull/317
https://security.snyk.io/vuln/SNYK-JS-ELLIPTIC-7577917
=> [GHSA-49q7-c7j4-3p7m] Elliptic allows BER-encoded signatures

advisories/github-reviewed/2024/08/GHSA-977x-g7h5-7qgw/GHSA-977x-g7h5-7qgw.json
**Updates**
- Severity
**Comments**
Fixed in 6.5.7.
See more info:
https://github.com/indutny/elliptic/pull/317
https://security.snyk.io/vuln/SNYK-JS-ELLIPTIC-7577918
=> [GHSA-977x-g7h5-7qgw] Elliptic's ECDSA missing check for whether leading bit of r and s is zero

advisories/github-reviewed/2023/12/GHSA-q5q3-qm26-9jwm/GHSA-q5q3-qm26-9jwm.json
**Updates**
- CVSS
- Severity
**Comments**
Only admins with full server access can import files from urls and therefore scan ports of their own server. This is not exploitable or at least nonsensical.
=> [GHSA-q5q3-qm26-9jwm] Authenticated Blind SSRF in automad/automad

advisories/github-reviewed/2024/07/GHSA-47mc-qmh2-mqj4/GHSA-47mc-qmh2-mqj4.json
**Updates**
- CVSS
- References
- Severity
**Comments**
Dear GitHub Security Curators Team,
I, the maintainer of the affected repository, would like to correct some of the details regarding this report:
1. In contrast to the mentioned affected versions, the vulnerability was fixed with version 2.0.0-alpha.5. The linked issue #106 clearly states this.
2. The release date was already June 30th, but this entry was updated last week without mentioning the fix.
3. The vulnerability was reported as a CVE entry three weeks after the fix was released, why?
4. The linked commit is totally unrelated.
5. In order to exploit the vulnerability one has to an admin user. A malicious file has to be prepared and uploaded manually by the admin. Usually there is only one admin per site …
=> [GHSA-47mc-qmh2-mqj4] Automad arbitrary file upload vulnerability

advisories/github-reviewed/2023/12/GHSA-fpph-mqc8-h6q5/GHSA-fpph-mqc8-h6q5.json
**Updates**
- CVSS
- Description
**Comments**
Only admins, usually there is only one, can upload files. No hack is required to inject JS to a site since it is intended behaviour to upload JS snippets to pages.
=> [GHSA-fpph-mqc8-h6q5] Unrestricted File Upload affecting automad

advisories/github-reviewed/2024/08/GHSA-88g2-r9rw-g55h/GHSA-88g2-r9rw-g55h.json
**Updates**
**Comments**
Although newer versions than 0.39.1 of the [`gitoxide-core`](https://crates.io/crates/gitoxide-core/versions) crate have been released, that is coincidental and the changes in those versions are unrelated to this vulnerability, which is not yet patched. Therefore, this updates the upper bound of `gitoxide-core` versions known to be affected.
This is the same change as just made in the repository-local advisory https://github.com/Byron/gitoxide/security/advisories/GHSA-88g2-r9rw-g55h.
=> [GHSA-88g2-r9rw-g55h] gitoxide-core does not neutralize special characters for terminals

advisories/github-reviewed/2024/07/GHSA-328p-362g-r48j/GHSA-328p-362g-r48j.json
**Updates**
- Description
**Comments**
I've updated the table above listing the affected versions and the fixed versions for all the packages originally reported in this issue.
I've updated the description to list all the functions which are affected by this vulnerability.
Please update the advisory database with this information.
=> [GHSA-328p-362g-r48j] ag-grid packages vulnerable to Prototype Pollution

advisories/github-reviewed/2024/08/GHSA-g8h2-j9pm-4xx2/GHSA-g8h2-j9pm-4xx2.json
**Updates**
- CVSS
- CWEs
- Severity
**Comments**
Hello, as the maintainer of this project I would like to comment the following:
1. Please look at the security policy, before publishing such reports. Exactly this case is described there and is in fact intended behaviour! Maintainers don't write this for fun.
2. Please make sure you understand the underlying architecture of the project, the way sessions work and user privileges. All this is well documented in the main docs as well as the security policy.
3. A similar case was removed last week by the GitHub advisory team for being an obvious false positive. This is basically the same case here.
4. The security policy clearly states, how to communicate vulnerabilities. This here doesn't help.
Context: The report says, a …
=> [GHSA-g8h2-j9pm-4xx2] Automad Cross-site Scripting vulnerability

advisories/github-reviewed/2019/10/GHSA-c427-hjc3-wrfw/GHSA-c427-hjc3-wrfw.json
The jar files contains the vulnerable npm files so the maven should registry should be also concluded as vulnerable
=> [GHSA-c427-hjc3-wrfw] Cross-site scripting in Swagger-UI

advisories/github-reviewed/2022/02/GHSA-4v6p-cxf9-98rf/GHSA-4v6p-cxf9-98rf.json
**Updates**
- Description
**Comments**
Per conversation in this issue thread: https://github.com/drewnoakes/metadata-extractor/issues/561
The OOM associated with this CVE was addressed in version 2.18.0: https://github.com/drewnoakes/metadata-extractor/releases/tag/2.18.0
The fix PR: https://github.com/drewnoakes/metadata-extractor/pull/570
=> [GHSA-4v6p-cxf9-98rf] Allocation of Resources Without Limits or Throttling in metadata-extractor

advisories/github-reviewed/2024/02/GHSA-4265-ccf5-phj5/GHSA-4265-ccf5-phj5.json
**Updates**
- CVSS
- Severity
**Comments**
Updated vector accrding to the NVD: https://nvd.nist.gov/vuln/detail/CVE-2024-26308
=> [GHSA-4265-ccf5-phj5] Apache Commons Compress: OutOfMemoryError unpacking broken Pack200 file

advisories/github-reviewed/2022/05/GHSA-w7pm-cc4v-f3g8/GHSA-w7pm-cc4v-f3g8.json
**Updates**
**Comments**
The Version of com.liferay.portal.kernel does _not_ match the version of Liferay Portal. The CVE is reported for Liferay Portal prior to 7.2.1 CE GA2, which contains according to https://github.com/liferay/liferay-portal/blob/7.2.1-ga2/portal-kernel/bnd.bnd the package com.liferay.portal.kernel:4.35.3
=> [GHSA-w7pm-cc4v-f3g8] Deserialization of Untrusted Data in Liferay Portal

.github/workflows/delete_staging_and_head_branches.yaml
This fixes a very low risk security issue in the workflow, as someone could delete arbitrary branches by creating PRs. The workflow is only intended for non-fork PRs, so this just enforces that.
Had originally submitted through bug bounty but it wasn't considered serious enough so I am making a PR to fix it instead.
=> Don't run branch deletion on fork PRs.

advisories/github-reviewed/2024/08/GHSA-hxwh-jpp2-84pm/GHSA-hxwh-jpp2-84pm.json
**Updates**
**Comments**
Made configurable in 4.0.2, defaulting to false in 5.0.0:
https://github.com/corydolphin/flask-cors/issues/362
https://github.com/corydolphin/flask-cors/pull/363
https://github.com/corydolphin/flask-cors/pull/368
=> [GHSA-hxwh-jpp2-84pm] Flask-CORS allows the `Access-Control-Allow-Private-Network` CORS header to be set to true by default

advisories/github-reviewed/2024/08/GHSA-4vvj-4cpr-p986/GHSA-4vvj-4cpr-p986.json
**Updates**
**Comments**
v4 and below of Webpack are not affected by this vulnerability. See https://github.com/webpack/webpack/issues/18718#issuecomment-2326296270.
=> [GHSA-4vvj-4cpr-p986] Webpack's AutoPublicPathRuntimeModule has a DOM Clobbering Gadget that leads to XSS

advisories/github-reviewed/2022/08/GHSA-8x94-hmjh-97hq/GHSA-8x94-hmjh-97hq.json
**Updates**
**Comments**
The vulnerability exists in earlier versions as well.
See the listing in Snyk - https://security.snyk.io/vuln/SNYK-PYTHON-DJANGO-2968205
For example version 2.2.28 - https://github.com/django/django/blob/2.2.28/django/http/response.py#L445C56-L445C64
=> [GHSA-8x94-hmjh-97hq] Django vulnerable to Reflected File Download attack 

advisories/github-reviewed/2024/06/GHSA-2p57-rm9w-gvfp/GHSA-2p57-rm9w-gvfp.json
**Updates**
**Comments**
As far as I can tell, the package author has written a fix for this advisory and published it as version 2.0.1
=> [GHSA-2p57-rm9w-gvfp] ip SSRF improper categorization in isPublic

advisories/github-reviewed/2024/08/GHSA-wgmf-q9vr-vww6/GHSA-wgmf-q9vr-vww6.json
**Updates**
**Comments**
Also fixed version 1^ in https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.29.1
=> [GHSA-wgmf-q9vr-vww6] PhpSpreadsheet HTML writer is vulnerable to Cross-Site Scripting via style information

advisories/github-reviewed/2024/07/GHSA-cfxw-4h78-h7fw/GHSA-cfxw-4h78-h7fw.json
**Updates**
- References
**Comments**
The link is wrong, added the right commit addressing the vulnerability - https://github.com/dnsjava/dnsjava/commit/2073a0cdea2c560465f7ac0cc56f202e6fc39705
=> [GHSA-cfxw-4h78-h7fw] DNSJava DNSSEC Bypass

advisories/github-reviewed/2024/07/GHSA-mmwx-rj87-vfgr/GHSA-mmwx-rj87-vfgr.json
**Updates**
- References
**Comments**
https://github.com/dnsjava/dnsjava/commit/711af79be3214f52daa5c846b95766dc0a075116 was assigned 
CVE-2023-50868
=> [GHSA-mmwx-rj87-vfgr] DNSJava affected by KeyTrap - NSEC3 closest encloser proof can exhaust CPU resources

advisories/github-reviewed/2024/08/GHSA-rv9v-r4vm-gj8x/GHSA-rv9v-r4vm-gj8x.json
**Updates**
- Description
- Severity
**Comments**
Affected versions are wrong.
=> [GHSA-rv9v-r4vm-gj8x] Miniscript allows stack consumption

advisories/github-reviewed/2024/05/GHSA-v435-xc8x-wvr9/GHSA-v435-xc8x-wvr9.json
**Updates**
**Comments**
As can be seen in the fixing commits - 
https://github.com/bcgit/bc-java/commit/d7d5e735abd64bf0f413f54fd9e495fc02400fb0
https://github.com/bcgit/bc-java/commit/e0569dcb1dea9d421d84fc4c5c5688fe101afa2d
The fixes are affecting jcajce, tls, crypto modules, while the bcpkix jar doesn't include those modules - https://github.com/bcgit/bc-java/blob/r1rv77/ant/bc%2B-build.xml#L804-L819 .
Hence, bcpkix packages aren't affected by this vulnerability.
=> [GHSA-v435-xc8x-wvr9] Bouncy Castle affected by timing side-channel for RSA key exchange ("The Marvin Attack")

advisories/github-reviewed/2024/05/GHSA-m44j-cfrm-g8qc/GHSA-m44j-cfrm-g8qc.json
**Updates**
- References
**Comments**
As can be seen in the fixing commits - 
https://github.com/bcgit/bc-java/commit/9c165791b68a204678b48ec11e4e579754c2ea49
https://github.com/bcgit/bc-java/commit/ebe1c75579170072dc59b8dee2b55ce31663178f
The fixes are affecting math module, while the bcpkix jar doesn't include this module - https://github.com/bcgit/bc-java/blob/r1rv77/ant/bc%2B-build.xml#L804-L819 .
Hence, bcpkix packages aren't affected by this vulnerability.
=> [GHSA-m44j-cfrm-g8qc] Bouncy Castle crafted signature and public key can be used to trigger an infinite loop

advisories/github-reviewed/2024/05/GHSA-8xfc-gm6g-vgpv/GHSA-8xfc-gm6g-vgpv.json
**Updates**
- References
**Comments**
As can be seen in the fixing commits -
https://github.com/bcgit/bc-java/commit/fee80dd230e7fba132d03a34f1dd1d6aae0d0281
https://github.com/bcgit/bc-java/commit/efc498ca4caa340ac2fe11f2efee06c1a294501f 
The fixes are affecting math module, while the bcpkix jar doesn't include this module - https://github.com/bcgit/bc-java/blob/r1rv77/ant/bc%2B-build.xml#L804-L819 .
Hence, bcpkix packages aren't affected by this vulnerability.
=> [GHSA-8xfc-gm6g-vgpv] Bouncy Castle certificate parsing issues cause high CPU usage during parameter evaluation.

advisories/github-reviewed/2019/12/GHSA-m3jw-62m7-jjcm/GHSA-m3jw-62m7-jjcm.json
**Updates**
**Comments**
1.3.2 contains the fixes for this out-of-bounds-read: https://github.com/python/typed_ast/compare/1.3.1...1.3.2
Snyk provides a vulnerability correctly targeting 1.3.2 as fixed for this CVE - https://security.snyk.io/vuln/SNYK-PYTHON-TYPEDAST-535627
NVD CPE also only targets 1.3.0 and 1.3.1, as well as the CVE description  - https://nvd.nist.gov/vuln/detail/CVE-2019-19274
=> [GHSA-m3jw-62m7-jjcm] typed-ast Out-of-bounds Read

advisories/github-reviewed/2024/09/GHSA-6j75-5wfj-gh66/GHSA-6j75-5wfj-gh66.json
**Updates**
**Comments**
Update the advisory to account for the backporting of the patch in a 3.11.1 release.
this matches the updated advisory at https://github.com/twigphp/Twig/security/advisories/GHSA-6j75-5wfj-gh66
=> [GHSA-6j75-5wfj-gh66] Twig has a possible sandbox bypass

advisories/github-reviewed/2023/09/GHSA-pwh8-58vv-vw48/GHSA-pwh8-58vv-vw48.json
**Updates**
**Comments**
The 9.x line fix version was incomplete, meaning any automation could not use that version as is. With this fix the .patch version can be dropped in to resolve the issue.
=> [GHSA-pwh8-58vv-vw48] Jetty's OpenId Revoked authentication allows one request

advisories/github-reviewed/2024/09/GHSA-9wv6-86v2-598j/GHSA-9wv6-86v2-598j.json
**Updates**
**Comments**
https://github.com/pillarjs/path-to-regexp/security/advisories/GHSA-9wv6-86v2-598j
https://github.com/pillarjs/path-to-regexp/commit/925ac8e3c5780b02f58cbd4e52f95da8ad2ac485
https://github.com/pillarjs/path-to-regexp/commit/d31670ae8f6e69cbfd56e835742195b7d10942ef
=> [GHSA-9wv6-86v2-598j] path-to-regexp outputs backtracking regular expressions

advisories/github-reviewed/2024/07/GHSA-crjg-w57m-rqqf/GHSA-crjg-w57m-rqqf.json
**Updates**
**Comments**
Based on https://github.com/dnsjava/dnsjava/commit/07ac36a11578cc1bce0cd8ddf2fe568f062aee78 and https://github.com/dnsjava/dnsjava/commit/3ddc45ce8cdb5c2274e10b7401416f497694e1cf
Vulnerability is irrelevant to the origin version, the fix is in `dnssec` folder, which was only added in version 3.5, as per changelog
=> [GHSA-crjg-w57m-rqqf] DNSJava vulnerable to KeyTrap - Denial-of-Service Algorithmic Complexity Attacks

advisories/github-reviewed/2023/02/GHSA-mv6w-j4xc-qpfw/GHSA-mv6w-j4xc-qpfw.json
**Updates**
**Comments**
The versions of `github.com/argoproj/argo-cd` don't exist (it's `github.com/argoproj/argo-cd/v2`)
=> [GHSA-mv6w-j4xc-qpfw] Argo CD leaks repository credentials in user-facing error messages and in logs

advisories/github-reviewed/2022/05/GHSA-fcgg-qgxg-2g2x/GHSA-fcgg-qgxg-2g2x.json
**Updates**
**Comments**
EC-CUBE 3.0.16 - is vulnerable, < 3.0.16 means that 3.0.16 is not in affected range, but it is in
=> [GHSA-fcgg-qgxg-2g2x] EC-CUBE Open redirect vulnerability

advisories/github-reviewed/2024/08/GHSA-m3px-vjxr-fx4m/GHSA-m3px-vjxr-fx4m.json
**Updates**
- CVSS v3
- Description
**Comments**
CVE: https://github.com/pxlrbt/filament-excel/security/advisories/GHSA-m3px-vjxr-fx4m, Repo: https://github.com/pxlrbt/filament-excel/releases/tag/v1.1.14
=> [GHSA-m3px-vjxr-fx4m] Filament Excel Vulnerable to Path Traversal Attack on Export Download Endpoint

advisories/github-reviewed/2022/05/GHSA-wp7w-vx86-vj9h/GHSA-wp7w-vx86-vj9h.json
**Updates**
**Comments**
Incorrect major version of podman package specified
Compare https://deps.dev/go/github.com%2Fcontainers%2Fpodman/v1.4.2/versions with https://deps.dev/go/github.com%2Fcontainers%2Fpodman%2Fv4/v4.9.5/versions
=> [GHSA-wp7w-vx86-vj9h] Podman Elevated Container Privileges

advisories/github-reviewed/2023/06/GHSA-p976-h52c-26p6/GHSA-p976-h52c-26p6.json
**Updates**
**Comments**
Correct the package name
=> [GHSA-p976-h52c-26p6] Rancher vulnerable to Privilege Escalation via manipulation of Secrets

advisories/github-reviewed/2024/09/GHSA-w97f-w3hq-36g2/GHSA-w97f-w3hq-36g2.json
**Updates**
- CVSS v3
- Severity
**Comments**
The issue was fixed in the latest releases of Keycloak due to the introduction of a new feature named User Profile.
=> [GHSA-w97f-w3hq-36g2] Keycloak Denial of Service vulnerability

advisories/github-reviewed/2024/09/GHSA-f2jm-rw3h-6phg/GHSA-f2jm-rw3h-6phg.json
**Updates**
- CVSS v3
- References
- Severity
**Comments**
The link to the fix commit and affected package are wrong.
It's a common mistake to mark `langchain` as affected instead of `langchain-community`, as they both live in the same repository.
=> [GHSA-f2jm-rw3h-6phg] LangChain pickle deserialization of untrusted data

advisories/github-reviewed/2024/02/GHSA-2jv5-9r88-3w3p/GHSA-2jv5-9r88-3w3p.json
**Updates**
**Comments**
Starlette is not vulnerable to this vulnerability, only python-multipart is. Fixing commit https://github.com/encode/starlette/commit/13e5c26a27f4903924624736abd6131b2da80cc5 only bumps python-multipart version.
fastapi is not vulnerable to this vulnerability, only python-multipart is. Fixing commit https://github.com/tiangolo/fastapi/commit/9d34ad0ee8a0dfbbcce06f76c2d5d851085024fc only bumps python-multipart version.
=> [GHSA-2jv5-9r88-3w3p] python-multipart vulnerable to Content-Type Header ReDoS

advisories/github-reviewed/2022/08/GHSA-mv48-hcvh-8jj8/GHSA-mv48-hcvh-8jj8.json
**Updates**
- CVSS v3
- Severity
**Comments**
Corrected affected products , changed CVSS score for correction. (I am the initial reporter of this vulnerabiltiy.)
=> [GHSA-mv48-hcvh-8jj8] Vite before v2.9.13 vulnerable to directory traversal via crafted URL to victim's service

advisories/github-reviewed/2024/08/GHSA-mg8j-w93w-xjgc/GHSA-mg8j-w93w-xjgc.json
**Updates**
- CVSS v3
- Severity
**Comments**
NIST added CVSS score on 9/19  -- https://nvd.nist.gov/vuln/detail/CVE-2024-45440
Confirmation given by Drupal Core Team Committer poker10 (also a member of the Drupal Security Team) that the fault code has existed since 2010 in response to confirmation testing against tagged releases  8.0.0, 8.9.20, 9.5.11, 10.3.2, and 11.0.1 (latest tagged releases at time of testing in each major branch, along with oldest suspected vulnerable tagged release) https://www.drupal.org/project/drupal/issues/3457781#comment-15755727
The release constraint could be more strict using the below constraints, however the issue has not yet been fixed in any development branches and the vendor continues to tag new releases. 
```
11.x-dev
>=8.0.0, <= …
```
=> [GHSA-mg8j-w93w-xjgc] Drupal Full Path Disclosure

advisories/github-reviewed/2024/09/GHSA-6f62-3596-g6w7/GHSA-6f62-3596-g6w7.json
**Updates**
**Comments**
The version 1.8.2 seems to fix the issue: https://github.com/ruby/webrick/issues/145#issuecomment-2369994610
=> [GHSA-6f62-3596-g6w7] HTTP Request Smuggling in ruby webrick

advisories/github-reviewed/2023/10/GHSA-622h-h2p8-743x/GHSA-622h-h2p8-743x.json
**Updates**
**Comments**
It was recently found in our team that the affected versions and patched versions in this advisory don't reflect the correct go mod versions used in our repo and result in a few false positive findings reported by vulnerability scanners.  We have corrected the version in our repo's advisories (https://github.com/neuvector/neuvector/security/advisories/GHSA-622h-h2p8-743x). We hope the versions in GitHub advisories can also be corrected.
=> [GHSA-622h-h2p8-743x] JWT token compromise can allow malicious actions including Remote Code Execution (RCE) 

advisories/github-reviewed/2024/03/GHSA-f78j-4w3g-4q65/GHSA-f78j-4w3g-4q65.json
**Updates**
**Comments**
The NPM package uses SemVer (or at least SemVer formatted) versions. 3.5.0.pre0 and 3.5.0.rc4 are not valid SemVer versions and are not versions that exist on NPM for this package. I've noticed that some old NPM packages used to have non-SemVer versions, but that doesn't seem to be the case with this package.
=> [GHSA-f78j-4w3g-4q65] StimulusReflex arbitrary method call

advisories/github-reviewed/2024/09/GHSA-j76j-rqwj-jmvv/GHSA-j76j-rqwj-jmvv.json
**Updates**
- CVSS v3
**Comments**
This issue was fixed in 25.0.5, and not in 25.0.2 as stated now; see https://github.com/keycloak/keycloak/issues/32754
=> [GHSA-j76j-rqwj-jmvv] Keycloak Session Fixation vulnerability

advisories/github-reviewed/2023/03/GHSA-vp98-w2p3-mv35/GHSA-vp98-w2p3-mv35.json
**Updates**
**Comments**
The version number of log4j core in mvnrepository is 2.0 instead of 2.0.0
=> [GHSA-vp98-w2p3-mv35] Apache Log4j 1.x (EOL) allows Denial of Service (DoS)

advisories/github-reviewed/2024/06/GHSA-v5gf-r78h-55q6/GHSA-v5gf-r78h-55q6.json
**Updates**
- CVSS v3
- Description
**Comments**
- privileges required changed from low to high, as an attacker requires the permissions to create templates which isn't something a "normal" user is able to do (when configured correctly)
- add note about the screenshot, system was heavily misconfigured and therefore the service ran as root, when not misconfigured it would run as the user `document-merge-service` with UID 901
=> [GHSA-v5gf-r78h-55q6] document-merge-service vulnerable to Remote Code Execution via Server-Side Template Injection

advisories/github-reviewed/2024/07/GHSA-xpp6-8r3j-ww43/GHSA-xpp6-8r3j-ww43.json
**Updates**
- CVSS v3
- References
**Comments**
The CVE has been fixed with undertow version `2.3.15.Final`. See the vendor ticket for reference: https://issues.redhat.com/browse/UNDERTOW-2413
=> [GHSA-xpp6-8r3j-ww43] Undertow Denial of Service vulnerability

advisories/github-reviewed/2022/12/GHSA-vr8j-hgmm-jh9r/GHSA-vr8j-hgmm-jh9r.json
**Updates**
- CVSS v3
**Comments**
Per https://crates.io/crates/openssl-src/versions it looks like the first versions of the rust crate that corresponded to version 3.0.0 of openssl was 300.0.0 and the first version that corresponded to v3.0.8 was 300.0.12.  It is the same openssl affected range as on https://github.com/advisories/GHSA-29xx-hcv2-c4cp
=> [GHSA-vr8j-hgmm-jh9r] openssl-src subject to DoS by double-checked locking

advisories/github-reviewed/2024/07/GHSA-mpg4-rc92-vx8v/GHSA-mpg4-rc92-vx8v.json
**Updates**
- CVSS v3
- Description
**Comments**
https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/v5/valueParsers/currency.js#L10 does not contain a RegEx, but I can see in a previous version of the file, i.e. https://github.com/NaturalIntelligence/fast-xml-parser/blob/ba5f35e7680468acd7906eaabb2f69e28ed8b2aa/src/v5/valueParsers/currency.js that, at some point, `currencyCheckRegex` was on line 10.
=> [GHSA-mpg4-rc92-vx8v] fast-xml-parser vulnerable to ReDOS at currency parsing

advisories/github-reviewed/2024/09/GHSA-rrr8-f88r-h8q6/GHSA-rrr8-f88r-h8q6.json
**Updates**
- CVSS v3
**Comments**
`follow-my-way` v4.1.0 is NOT exploitable by CVE-2024-45813. The following test does NOT fail on Node 12 NPM 6 follow-my-way v4.1.0:
```javascript
test('prevent back-tracking', (t) => {
t.plan(0)
t.setTimeout(20)
const findMyWay = FindMyWay({
defaultRoute: () => {
t.fail('route not matched')
}
})
findMyWay.on('GET', '/:foo-:bar-', (req, res, params) => {})
findMyWay.find('GET', '/' + '-'.repeat(200000000) + 'a', { host: 'fastify.io' })
})
```
The reason is that CVE-2024-45813 exploits mechanism that does not exist in v4.1.0. CVE-2024-45813 exploits a mechanism to check the validity of a given regex, and could cause a ReDoS. At some point after 4.1.0, the maintainer transformed the function `router.prototype._on` to use loops instead …
=> [GHSA-rrr8-f88r-h8q6] find-my-way has a ReDoS vulnerability in multiparametric routes

advisories/github-reviewed/2024/10/GHSA-rf5m-h8q9-9w6q/GHSA-rf5m-h8q9-9w6q.json
**Updates**
- CVSS v3
**Comments**
The affected versions were incorrectly taken from the vendor advisory at https://github.com/TYPO3/typo3/security/advisories/GHSA-rf5m-h8q9-9w6q
=> [GHSA-rf5m-h8q9-9w6q] Information Disclosure in TYPO3 Page Tree

advisories/github-reviewed/2020/05/GHSA-q4m3-2j7h-f7xw/GHSA-q4m3-2j7h-f7xw.json
**Updates**
- Description
**Comments**
Test cases on https://research.insecurelabs.org/jquery/test/ Select CVE-2020-7656 from the issue list and click "Run" and it will load all versions of jQuery and try to exploit the bug for each version.
The load method does not support fragments before version 1.2, so <1.2 are not vulnerable.
Version 1.2 itself, adds the script but it does not execute.
The "Affected products" list was not updated as version 1.2 and earlier do not exist as packages in the ecosystems.
Only the description was updated.
=> [GHSA-q4m3-2j7h-f7xw] Cross-Site Scripting in jquery

advisories/github-reviewed/2024/08/GHSA-pp84-v3mw-gg4w/GHSA-pp84-v3mw-gg4w.json
**Updates**
- Description
- References
**Comments**
Linking existing CVEs to References to pass publishing steps.
=> [GHSA-pp84-v3mw-gg4w] Taipy 3.1.1 affected by CVEs on flask-core and pymongo

advisories/github-reviewed/2024/10/GHSA-4f8r-qqr9-fq8j/GHSA-4f8r-qqr9-fq8j.json
**Updates**
- CVSS v3
**Comments**
There are two different packages of go-tuf:
- https://pkg.go.dev/github.com/theupdateframework/go-tuf
- https://pkg.go.dev/github.com/theupdateframework/go-tuf/v2
The advisory data does not look correct - as the latest version of go-tuf (at the time of writing). is v0.7.0. However we're wrongly classifying that this is fixed in v2.0.1. There is no such version for this go-tuf package. The fix only exists in go-tuf/v2.
If we compare to here:
- https://pkg.go.dev/vuln/GO-2024-3166
That data source correctly makes a distinction between the versions, and it does list there is no fixed version in go-tuf (i.e non-v2). 
As further evidence, we can see here where they merged what looks to be the fix, into the v2.x release train:
- …
=> [GHSA-4f8r-qqr9-fq8j] Incorrect delegation lookups can make go-tuf download the wrong artifact

advisories/github-reviewed/2023/08/GHSA-5824-cm3x-3c38/GHSA-5824-cm3x-3c38.json
**Updates**
- CVSS v3
- Severity
**Comments**
This issue resulted in multiple hack totalling USD 61m loss.
https://cointelegraph.com/news/curve-vyper-exploit-whole-story-so-far
=> [GHSA-5824-cm3x-3c38] Vyper has incorrectly allocated named re-entrancy locks

advisories/github-reviewed/2024/10/GHSA-jqfv-jrvq-95jm/GHSA-jqfv-jrvq-95jm.json
**Updates**
- CVSS v3
- References
**Comments**
Changelog at https://xmlgraphics.apache.org/security.html indicates 2.10 is released with the fix
=> [GHSA-jqfv-jrvq-95jm] Apache XML Graphics FOP XML External Entity Reference ('XXE') vulnerability

advisories/github-reviewed/2023/06/GHSA-65wh-g8x8-gm2h/GHSA-65wh-g8x8-gm2h.json
**Updates**
**Comments**
The `nifi-jms-processors` JAR module contains the affected classes, and the `nifi-jms-processors-nar` NAR module includes the `nifi-jms-processors` JAR. The `nifi-jms-bundle` is the parent module of these two modules, but does not contain the affected class files.
=> [GHSA-65wh-g8x8-gm2h] Apache NiFi vulnerable to Deserialization of Untrusted Data

advisories/github-reviewed/2023/02/GHSA-hxjp-q6c3-38fx/GHSA-hxjp-q6c3-38fx.json
**Updates**
**Comments**
The `nifi-ccda-processors` JAR contains the `ExtractCCDAAttributes` class and the `nifi-ccda-nar` includes the `nifi-ccda-processors` JAR.
=> [GHSA-hxjp-q6c3-38fx] XML External Entity Reference in Apache NiFi

advisories/github-reviewed/2024/09/GHSA-7h5p-mmpp-hgmm/GHSA-7h5p-mmpp-hgmm.json
The actual vulnerable package is `github.com/projectdiscovery/nuclei/v3` and not `github.com/projectdiscovery/nuclei`
=> [GHSA-7h5p-mmpp-hgmm] Nuclei Template Signature Verification Bypass - Update Affected Packages

advisories/github-reviewed/2022/05/GHSA-h2p3-h48h-9jj7/GHSA-h2p3-h48h-9jj7.json
**Updates**
**Comments**
Both references provided already state versions 1.1.5 or above should be installed.
=> [GHSA-h2p3-h48h-9jj7] PIDUsage Enables OS Command Injection

advisories/github-reviewed/2024/06/GHSA-cgwc-qvrx-rf7f/GHSA-cgwc-qvrx-rf7f.json
**Updates**
- References
**Comments**
Fixing incorrect reference; secondary update to affected version change from https://github.com/github/advisory-database/pull/4910
=> [GHSA-cgwc-qvrx-rf7f] Remote code execution in pytorch lightning

advisories/github-reviewed/2024/06/GHSA-9442-gm4v-r222/GHSA-9442-gm4v-r222.json
**Updates**
- CVSS v3
- References
**Comments**
The fix for CVE-2024-6162 also got backported on the `2.2.x` branch to version `2.2.33.Final` and higher.
For reference, see:
* https://issues.redhat.com/browse/UNDERTOW-2334
* https://github.com/undertow-io/undertow/commit/a28ac53076e2fa532266d25e0c0b1a01d0e9d2cf
* https://github.com/undertow-io/undertow/pull/1612
=> [GHSA-9442-gm4v-r222] Undertow's url-encoded request path information can be broken on ajp-listener

advisories/github-reviewed/2022/05/GHSA-qg25-hgjv-cg9q/GHSA-qg25-hgjv-cg9q.json
**Updates**
**Comments**
groovy-all also contains the core groovy so every vulnerability in the core groovy is included in the groovy-all.
=> [GHSA-qg25-hgjv-cg9q] Improper Neutralization of Special Elements in Output Used by a Downstream Component in Apache Groovy

advisories/github-reviewed/2024/10/GHSA-255w-87rh-rg44/GHSA-255w-87rh-rg44.json
**Updates**
- CVSS v3
**Comments**
The 2.5.21 version and newer version of 2.5.x also have the security fix in them.
I tried to adopt this in: https://github.com/sulu/sulu/security/advisories/GHSA-6784-9c82-vr85
=> [GHSA-255w-87rh-rg44] Cross-site Scripting via uploaded SVG

advisories/github-reviewed/2024/10/GHSA-g9xm-7538-mq8w/GHSA-g9xm-7538-mq8w.json
**Updates**
**Comments**
Per the [upstream advisory for libexiv2](https://github.com/Exiv2/exiv2/security/advisories/GHSA-g9xm-7538-mq8w), only versions 0.28.0 and 0.28.1 are affected, and after inspection of the wheels available for the [exiv2 on PyPI](https://pypi.org/project/exiv2/), I believe only v0.16.0 is potentially affected:
| pypi exiv2 version| bundled libexiv2 version | affected |
| ----------------- | ----------------------- | ------- |
| 0.16.0 | 0.28.1 |true |
| 0.16.1 |0.27.7 | false |
| 0.16.2 | 0.27.7 | false |
| 0.16.2.post1 | 0.27.7 | false |
| 0.16.3 | 0.28.2 | false |
=> [GHSA-g9xm-7538-mq8w] Exiv2 has an out-of-bounds read in QuickTimeVideo::NikonTagsDecoder

advisories/github-reviewed/2024/10/GHSA-crmj-qh74-2r36/GHSA-crmj-qh74-2r36.json
**Updates**
**Comments**
Per the [upstream advisory for libexiv2](https://github.com/Exiv2/exiv2/security/advisories/GHSA-crmj-qh74-2r36), only versions 0.28.0 and 0.28.1 are affected, and after inspection of the wheels available for the [exiv2 on PyPI](https://pypi.org/project/exiv2/), I believe only v0.16.0 is potentially affected:
| pypi exiv2 version| bundled libexiv2 version | affected |
| ----------------- | ----------------------- | ------- |
| 0.16.0 | 0.28.1 |true |
| 0.16.1 |0.27.7 | false |
| 0.16.2 | 0.27.7 | false |
| 0.16.2.post1 | 0.27.7 | false |
| 0.16.3 | 0.28.2 | false |
=> [GHSA-crmj-qh74-2r36] Exiv2  has a denial of service due to unbounded recursion in QuickTimeVideo::multipleEntriesDecoder

advisories/github-reviewed/2024/10/GHSA-m4gq-x24j-jpmf/GHSA-m4gq-x24j-jpmf.json
**Updates**
- Summary
**Comments**
Prototype pollution vulnerability found in Mermaid's DOMPurify integration
=> [GHSA-m4gq-x24j-jpmf] Mermaid allows prototype pollution in bundled version of DOMPurify

advisories/github-reviewed/2024/10/GHSA-fc9h-whq2-v747/GHSA-fc9h-whq2-v747.json
**Updates**
**Comments**
Resolved by https://github.com/indutny/elliptic/commit/34c853478cec1be4e37260ed2cb12cdbdc6402cf in the 6.6.0 release.
=> [GHSA-fc9h-whq2-v747] Valid ECDSA signatures erroneously rejected in Elliptic

advisories/github-reviewed/2022/07/GHSA-h6gj-6jjq-h8g9/GHSA-h6gj-6jjq-h8g9.json
**Updates**
**Comments**
jquery-ui-rails 7.0.0 bundles jquery-ui 1.13.0, so this vulnerability is *not* patched in 7.0.0. There is currently no patched version of jquery-ui-rails.
https://github.com/jquery-ui-rails/jquery-ui-rails/blob/master/VERSIONS.md
=> [GHSA-h6gj-6jjq-h8g9] jQuery UI vulnerable to XSS when refreshing a checkboxradio with an HTML-like initial text label

advisories/github-reviewed/2024/10/GHSA-4gc7-5j7h-4qph/GHSA-4gc7-5j7h-4qph.json
**Updates**
- References
**Comments**
The 6.0.25 and 5.3.41 versions of org.springframework:spring-context were not found in the central repository or any platform. According to the Milestones listed at https://github.com/spring-projects/spring-framework/issues/33708 and the merged tags at https://github.com/spring-projects/spring-framework/commit/23656aebc6c7d0f9faff1080981eb4d55eff296c, the vulnerability should be fixed in versions 6.1.14 and 6.2.0-RC2.
=> [GHSA-4gc7-5j7h-4qph] Spring Framework DataBinder Case Sensitive Match Exception

advisories/github-reviewed/2024/11/GHSA-xhg6-9j5j-w4vf/GHSA-xhg6-9j5j-w4vf.json
**Updates**
- CVSS v3
- Description
**Comments**
The provided patch has been applied to ProDotNetZip and a new version 1.19.0 has been released on Nuget.
=> [GHSA-xhg6-9j5j-w4vf] DotNetZip Directory Traversal vulnerability

advisories/github-reviewed/2024/11/GHSA-xq3w-v528-46rv/GHSA-xq3w-v528-46rv.json
**Updates**
- CVSS v4
- Severity
**Comments**
Removed CVSSv4 as it was never declared or used in the original report and contains incorrect values.
Used CVSSv3 instead which should have the correct values.
https://github.com/netty/netty/issues/14473
=> [GHSA-xq3w-v528-46rv] Denial of Service attack on windows app using netty

advisories/github-reviewed/2024/12/GHSA-f626-677r-j5vq/GHSA-f626-677r-j5vq.json
**Updates**
**Comments**
mentioned code in https://github.com/CSIRTTrizna/CVE-2024-55586 does not check user input, I think it is not responsibility of framework to check user input 
CVE should be revoked!
=> [GHSA-f626-677r-j5vq] Nette Database SQL injection

advisories/github-reviewed/2024/10/GHSA-xgfv-xpx8-qhcr/GHSA-xgfv-xpx8-qhcr.json
=> [GHSA-xgfv-xpx8-qhcr] Improper Verification of SAML Responses Leading to Privilege Escalation in Keycloak

advisories/github-reviewed/2024/06/GHSA-4vc8-pg5c-vg4x/GHSA-4vc8-pg5c-vg4x.json
**Updates**
**Comments**
CVE Id is mentioned in https://github.com/keycloak/keycloak/security/advisories/GHSA-4vc8-pg5c-vg4x
But there Is no field to update it here, can it be updated to CVE-2021-3754
=> [GHSA-4vc8-pg5c-vg4x] Keycloak's improper input validation allows using email as username

advisories/github-reviewed/2024/10/GHSA-xmmm-jw76-q7vg/GHSA-xmmm-jw76-q7vg.json
=> [GHSA-xmmm-jw76-q7vg] One Time Passcode (OTP) is valid longer than expiration timeSeverity

advisories/github-reviewed/2024/10/GHSA-5rxp-2rhr-qwqv/GHSA-5rxp-2rhr-qwqv.json
=> [GHSA-5rxp-2rhr-qwqv] Session fixation in Elytron SAML adapters

advisories/github-reviewed/2024/01/GHSA-9vm7-v8wj-3fqw/GHSA-9vm7-v8wj-3fqw.json
=> [GHSA-9vm7-v8wj-3fqw] keycloak-core: open redirect via "form_post.jwt" JARM response mode

advisories/github-reviewed/2023/11/GHSA-94jh-j374-9r3j/GHSA-94jh-j374-9r3j.json
This Pull Request proposes correcting the **Attack Complexity** rating for CVE-2023-26031 / GHSA-94jh-j374-9r3j to align with the [CVSS v4 specification](https://www.first.org/cvss/v4.0/specification-document). Currently rated as **Attack Complexity = Low**, this assignment does not accurately reflect the conditions necessary for successful exploitation—particularly in remote scenarios, which lead to **Attack Complexity = High**.
Below is the detailed rationale for updating the rating to Attack Complexity = High:
The vulnerability under discussion requires an attacker to possess target-specific login credentials to authenticate with the YARN cluster in remote exploitation scenarios according to the description excerpts:
> If the YARN cluster is accepting work from remote (authenticated) …
=> [GHSA-94jh-j374-9r3j] Correcting Attack Complexity to Reflect Remote Exploitation

advisories/github-reviewed/2023/11/GHSA-94jh-j374-9r3j/GHSA-94jh-j374-9r3j.json
I am collaborating with @vulnerability-analyst to enhance the accuracy of the OSS vulnerability advisories.
In alignment with the feedback from @shelbyc in [this PR](https://github.com/github/advisory-database/pull/5153), the Attack Requirement (`AT`) should be updated to `P` (Present) rather than the erroneous `N` (None). This is because if _the attacker submits a job to the container_, he/she will not gain the root privileges. 
> If the YARN cluster is accepting work from remote (authenticated) users, and these users' submitted job are executed in the physical host, rather than a container, then the CVE permits remote users to gain root privileges.
The __sentence underlined above__ represents the “specific deployment and execution conditions” required for a successful attack, as defined …
=> [GHSA-94jh-j374-9r3j] Refining Attack Requirement to Reflect Dependency on Physical Host for Successful Exploitation

advisories/github-reviewed/2019/02/GHSA-9gqh-q4cx-f2h9/GHSA-9gqh-q4cx-f2h9.json
The CVSS 3.x Attack Complexity for CVE-2016-1059 / GHSA-9gqh-q4cx-f2h9 should be classified as High instead of Low, based on the requirement for the attacker to obtain **a privileged network position**. This aligns directly with the CVSS 3.x definition of High Attack Complexity, which states that a successful attack demands “some measurable amount of effort […] in preparation or execution against the vulnerable component before a successful attack can be expected.”
> In scenarios where an attacker has **a privileged network position**, they can modify or read such resources at will. While the exact severity of impact for a vulnerability like this is highly variable and depends on the behavior of the package itself, it ranges from being able to read sensitive information all the way up to …
=> [GHSA-9gqh-q4cx-f2h9] Update the CVSS 3.x Attack Complexity from Low to High

advisories/github-reviewed/2022/11/GHSA-xxcj-rhqg-m46g/GHSA-xxcj-rhqg-m46g.json
After reviewing the description and exploitation details for CVE-2022-41889 / GHSA-xxcj-rhqg-m46g, I believe the current CVSS 3.x vector assignment might not fully align with the nature of the vulnerability. The vulnerability targets the same module `tf.compat.v1.*` as CVE-2022-29205 / GHSA-54ch-gjq5-4976, and the exploitation path appears comparable. However, the following CVSS metrics for CVE-2022-41889 seem to overstate its complexity and attack requirements: CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:U/C:N/I:N/A:H
More specifically:
- Attack Vector (AV): The vulnerability only requires the use of quantized tensors in `tf.compat.v1.*` within a local execution context. There is no evidence suggesting that network access (i.e., `AV:N`) is a prerequisite. 
- Attack Complexity (AC): The exploitation …
=> [GHSA-xxcj-rhqg-m46g] Update AV, AC, and UI in CVSS 3.x

advisories/github-reviewed/2020/12/GHSA-4cch-wxpw-8p28/GHSA-4cch-wxpw-8p28.json
The CVE-2020-26258 / GHSA-4cch-wxpw-8p28 should be rated with an Attack Complexity of High rather than Low because the manipulation of input streams to exploit the vulnerability demands significant effort and precise preparation, aligning with the criteria for a High complexity rating in [CVSS 3.x specification](https://www.first.org/cvss/v3.0/specification-document): “a measurable amount of effort in preparation or execution against the vulnerable component is required before a successful attack can be expected.” 
> The vulnerability may allow a remote attacker to request data from internal resources that are not publicly available only by manipulating the processed input stream.
Additionally, similar CVEs affecting the same package, `com.thoughtworks.xstream:xstream`, have consistently …
=> [GHSA-4cch-wxpw-8p28] Update Attack Complexity from Low to High

advisories/github-reviewed/2022/09/GHSA-rc4r-wh2q-q6c4/GHSA-rc4r-wh2q-q6c4.json
The CVE-2022-36109 / GHSA-rc4r-wh2q-q6c4 highlights a vulnerability where an attacker could access sensitive information or execute code by exploiting supplementary group access within a containerized environment.
> Moby is an open-source project created by Docker to enable software containerization. A bug was found in Moby (Docker Engine) where supplementary groups are not set up properly. **If an attacker has __direct access to a container__ and manipulates their supplementary group access, they may be able to use supplementary group access to bypass primary group restrictions in some cases, potentially gaining access to sensitive information or gaining the ability to execute code in that container.**  (Excerpt of CVE-2022-36109 Description)
The vulnerability explicitly states that the …
=> [GHSA-rc4r-wh2q-q6c4] Update CVSS 3.x AV from Network (N) to Local (L)

advisories/github-reviewed/2022/05/GHSA-phf8-3qgv-rg5q/GHSA-phf8-3qgv-rg5q.json
The Privilege Required (PR) metric for CVE-2017-1000105 / GHSA-phf8-3qgv-rg5q should be revised from None to Low. This vulnerability enables users with lower privileges, such as Item/Read permissions, to elevate their access to higher privileges, like Run/Artifacts permissions, by modifying a Java system property. This scenario does not align with cases requiring no permissions or administrative privileges, justifying the proposed update.
> The optional **Run/Artifacts permission** can be enabled by setting a Java system property. Blue Ocean did not check this permission before providing access to archived artifacts, **Item/Read permission** was sufficient.
> The attacker is unauthorized prior to attack, and therefore does not require any access to settings or files of the vulnerable …
=> [GHSA-phf8-3qgv-rg5q] Update CVSS 3.x Privilege Required (PR) from None (N) to Low (L)

advisories/github-reviewed/2024/01/GHSA-733r-8xcp-w9mr/GHSA-733r-8xcp-w9mr.json
The User Interaction (UI) requirement for CVE-2024-21641 / GHSA-733r-8xcp-w9mr should be updated from None (N) to Required (R). This is because exploiting this vulnerability necessitates user action: logging into a “trusted domain” beforehand. This aligns with the CVSS 3.x specification, which states that user interaction is required if some action must be taken before the vulnerability can be exploited.
>   The Flarum `/logout` route includes a **redirect parameter that allows any third party to redirect users from a (trusted) domain of the Flarum installation to redirect to any link**. Sample: `example.com/logout?return=https://google.com`. For logged-in users, the logout must be confirmed. Guests are immediately redirected. This could be used by spammers to redirect to a web address …
=> [GHSA-733r-8xcp-w9mr] Update User Interaction (UI) for None (N) to Required (R)

advisories/github-reviewed/2024/02/GHSA-9xfw-jjq2-7v8h/GHSA-9xfw-jjq2-7v8h.json
The Scope (S) classification of CVE-2024-24768 / GHSA-9xfw-jjq2-7v8h should be revised from Changed (C) to Unchanged (U). The reason is that the leakage of cookies does not grant attackers access "beyond the security scope" when they use the cookies to impersonate users.
>   The https cookie that comes with the panel does not have the Secure keyword, which may cause the cookie to be sent in plain text when accessing http accidentally.
| Metric Value  | Description                                                  |
| :------------ | :----------------------------------------------------------- |
| Unchanged (U) | An exploited vulnerability can only **affect resources managed by the *same* security authority**. In this case, the vulnerable component and the impacted component are either the …
=> [GHSA-9xfw-jjq2-7v8h] Update CVSS 3.x Scope (S) from Changed (C) to Unchanged (U) 

advisories/github-reviewed/2022/10/GHSA-93m7-c69f-5cfj/GHSA-93m7-c69f-5cfj.json
The CIA triad of CVE-2020-25614 / GHSA-93m7-c69f-5cfj should be updated from `C:H/I:H/A:H` to `C:N/I:N/A:H`. While the description explicitly identifies a Denial of Service (DoS) scenario, justifying `A:H`, the inability to parse XML as described does not result in the exposure of sensitive information or unauthorized file modifications.
>   xmlquery before 1.3.1 lacks a check for whether a LoadURL response is in the XML format, which allows attackers to cause a **denial of service** (SIGSEGV) at xmlquery.(*Node).InnerText or possibly have unspecified other impact.
For reference, other CVEs that describe XML parsing failures have consistently been rated as `C:N/I:N/A:H`:
-   CVE-2022-23476 / GHSA-qv4q-mr5r-qprj (CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H)
>   Nokogiri `1.13.8, 1.13.9` …
=> [GHSA-93m7-c69f-5cfj] Updating Confidentiality and Integrity of CVSS 3.x Rating

advisories/github-reviewed/2022/11/GHSA-p5v9-g8w8-5q4v/GHSA-p5v9-g8w8-5q4v.json
The Availability (A) rating for CVE-2022-41930 / GHSA-p5v9-g8w8-5q4v should be updated from None (N) to High (H). Disabling any user on Wiki fully denies access to resources within the impacted component, which aligns with the CVSS 3.x specification for a High Availability impact.
>   Any user (logged in or not) with access to the page XWiki.XWikiUserProfileSheet can enable or disable any user profile. This might allow to a disabled user to re-enable themselves, or to an attacker to **disable any user of the wiki**.
-   CVE-2017-8382 / GHSA-c4v8-2hg8-jv77 (CVSS:3.0/AV:N/AC:L/PR:H/UI:R/S:U/C:N/I:N/A:H)
>   admidio 3.2.8 has CSRF in `adm_program/modules/members/members_function.php` with an impact of **deleting arbitrary user accounts**.
=> [GHSA-p5v9-g8w8-5q4v] Update CVSS 3.x Availability Rating

advisories/github-reviewed/2024/02/GHSA-4g9r-vxhx-9pgx/GHSA-4g9r-vxhx-9pgx.json
The Confidentiality (C) and Integrity (I) ratings for CVE-2024-25710 / GHSA-4g9r-vxhx-9pgx should both be updated from High (H) to None (N), as the infinite loop neither exposes sensitive information nor enables attackers to modify files. The Availability (A) rating, however, is appropriate, as this vulnerability can lead to a Denial of Service (DoS) by exhausting system resources.
>   Loop with Unreachable Exit Condition ('**Infinite Loop**') vulnerability in Apache Commons Compress. This issue affects Apache Commons Compress: from 1.3 through 1.25.0.
| Metric Value | Description                                                  |
| :----------- | :----------------------------------------------------------- |
| High (H)     | There is a total loss of confidentiality, resulting in all …
=> [GHSA-4g9r-vxhx-9pgx] Updating Confidentiality and Integrity of CVSS 3.x Rating

advisories/github-reviewed/2025/01/GHSA-9cxr-76pm-j3wf/GHSA-9cxr-76pm-j3wf.json
Based on the machine-readable ranges in
https://www.cve.org/CVERecord?id=CVE-2024-53299
=> GHSA-9cxr-76pm-j3wf: more accurate version ranges

advisories/github-reviewed/2022/07/GHSA-4x9r-j582-cgr8/GHSA-4x9r-j582-cgr8.json
Update fixed versions for Maven and PyPI ecosystems.
Change `last_affected` to `fixed` to more closely match the recommendations in: https://lists.apache.org/thread/p847l3kopoo5bjtmxrcwk21xp6tjxqlc
> Upgrade to supported Apache Spark maintenance release 3.1.3, 3.2.2, or 3.3.0 or later
This could be replaced with:
```
{
{"introduced": "0"},
{"last_affected": "3.0.3"}
},
{
{"introduced": "3.1.0"},
{"fixed": "3.1.3"}
},
{
{"introduced": "3.2.0"},
{"fixed": "3.2.2"}
}
```
But given there is no version between `3.0.3` and `3.1.0` this seems unnecessary and potentially confusing.
- https://mvnrepository.com/artifact/org.apache.spark/spark-parent
- https://pypi.org/project/pyspark/#history
This change follows the OSV format recommendations to use `fixed` instead of `last_affected`: …
=> Update GHSA-4x9r-j582-cgr8.json fixed versions

advisories/github-reviewed/2024/12/GHSA-43mq-6xmg-29vm/GHSA-43mq-6xmg-29vm.json
**Updates**
- Description
- References
- CWEs
**Comments**
- The vulnerable class was marked as deprecated in version 6.4.0 but was only removed in version 7.0.0. Therefore, applications using versions `>=6.4.0, < 7.0.0` are still vulnerable
=> [GHSA-43mq-6xmg-29vm] Apache Struts file upload logic is flawed

advisories/github-reviewed/2021/12/GHSA-7rjr-3q55-vv33/GHSA-7rjr-3q55-vv33.json
The `pax-logging-log4j2` artifact shades `log4j-core` with minimal modifications.
The correspondence between `pax-logging-log4j2` versions and the embedded `log4j-core` version is given by the table below:
| `pax-logging-log4j2` version | `log4j-core` version |
|------------------------------|----------------------|
| 2.0.10                       | 2.14.1               |
| 2.0.11                       | 2.15.0               |
| 2.0.12                       | 2.16.0               |
| 2.0.13                       | 2.17.0               |
| 2.0.14                       | 2.17.1               |
=> Add `pax-logging-log4j2` to CVE-2021-45046

advisories/github-reviewed/2021/12/GHSA-p6xc-xr62-6r2g/GHSA-p6xc-xr62-6r2g.json
The `pax-logging-log4j2` artifact shades `log4j-core` with minimal modifications.
The correspondence between `pax-logging-log4j2` versions and the embedded `log4j-core` version is given by the table below:
| `pax-logging-log4j2` version | `log4j-core` version |
|------------------------------|----------------------|
| 2.0.10                       | 2.14.1               |
| 2.0.11                       | 2.15.0               |
| 2.0.12                       | 2.16.0               |
| 2.0.13                       | 2.17.0               |
| 2.0.14                       | 2.17.1               |
=> Add affected `pax-logging-log4j2` to CVE-2021-45105

advisories/github-reviewed/2022/01/GHSA-8489-44mv-ggj8/GHSA-8489-44mv-ggj8.json
The `pax-logging-log4j2` artifact shades `log4j-core` with minimal modifications.
The correspondence between `pax-logging-log4j2` versions and the embedded `log4j-core` version is given by the table below:
| `pax-logging-log4j2` version | `log4j-core` version |
|------------------------------|----------------------|
| 2.0.10                       | 2.14.1               |
| 2.0.11                       | 2.15.0               |
| 2.0.12                       | 2.16.0               |
| 2.0.13                       | 2.17.0               |
| 2.0.14                       | 2.17.1               |
=> Add affected `pax-logging-log4j2` to CVE-2021-44832

advisories/github-reviewed/2021/12/GHSA-7rjr-3q55-vv33/GHSA-7rjr-3q55-vv33.json
This PR fixes the ranges of `pax-logging-log4j2` affected by CVE-2021-45046.
In my previous PRs for CVE-2021-45046 (#5502) all versions 1.x of `pax-logging-log4j2` were listed as affected. As it turns out, this is incorrect, since 7 security releases of version 1.x were created after December 2021, as summarized by the table below:
| PAX Logging version | Log4j Core version | Fixed CVEs                     |
|---------------------|--------------------|--------------------------------|
| 1.9.2               | 2.12.4             | all 4 CVEs                     |
| 1.10.8              | 2.12.2             | CVE-2021-44228, CVE-2021-45046 |
| 1.10.9              | 2.12.4             | CVE-2021-45105, CVE-2021-44832 |
| 1.11.10             | 2.15.0             | CVE-2021-44228 …
=> fix: `pax-logging-log4j2` ranges affected by CVE-2021-45046

advisories/github-reviewed/2021/12/GHSA-p6xc-xr62-6r2g/GHSA-p6xc-xr62-6r2g.json
This PR fixes the ranges of `pax-logging-log4j2` affected by CVE-2021-45105.
In my previous PRs for CVE-2021-45105 (#5503) all versions 1.x of `pax-logging-log4j2` were listed as affected. As it turns out, this is incorrect, since 7 security releases of version 1.x were created to address those issues, as summarized by the table below:
| PAX Logging version | Log4j Core version | Fixed CVEs                     |
|---------------------|--------------------|--------------------------------|
| 1.9.2               | 2.12.4             | all 4 CVEs                     |
| 1.10.8              | 2.12.2             | CVE-2021-44228, CVE-2021-45046 |
| 1.10.9              | 2.12.4             | CVE-2021-45105, CVE-2021-44832 |
| 1.11.10             | 2.15.0             | CVE-2021-44228 …
=> fix: `pax-logging-log4j2` ranges affected by CVE-2021-45105

advisories/github-reviewed/2022/01/GHSA-8489-44mv-ggj8/GHSA-8489-44mv-ggj8.json
This PR fixes the ranges of `pax-logging-log4j2` affected by CVE-2021-44832.
In my previous PRs for CVE-44832 (#5504) all versions 1.x of `pax-logging-log4j2` were listed as affected. As it turns out, this is incorrect, since 7 security releases of version 1.x were created to address those issues, as summarized by the table below:
| PAX Logging version | Log4j Core version | Fixed CVEs                     |
|---------------------|--------------------|--------------------------------|
| 1.9.2               | 2.12.4             | all 4 CVEs                     |
| 1.10.8              | 2.12.2             | CVE-2021-44228, CVE-2021-45046 |
| 1.10.9              | 2.12.4             | CVE-2021-45105, CVE-2021-44832 |
| 1.11.10             | 2.15.0             | CVE-2021-44228 …
=> fix: `pax-logging-log4j2` ranges affected by CVE-2021-44832

advisories/github-reviewed/2022/05/GHSA-4vp2-mj4m-69m4/GHSA-4vp2-mj4m-69m4.json
Updates:
- References
Comments:
Add 3 patch commits:
https://github.com/zoujingli/ThinkAdmin/commit/6ccd4055fc40d2d7d154920a1859a7c19774bd1a
https://github.com/zoujingli/ThinkAdmin/commit/640a61ae0772dcd5209d74dff8ad373e61e8ad8c
https://github.com/zoujingli/ThinkAdmin/commit/b8a2ded90866a285e9022c842e546d8a6fa5fa6d
=> [GHSA-4vp2-mj4m-69m4] ThinkAdmin insecure unserialize vulnerability

advisories/github-reviewed/2024/05/GHSA-gq9f-8rj4-w7jc/GHSA-gq9f-8rj4-w7jc.json
Updates:
- References
Comments:
https://github.com/moodle/moodle/commit/03e93da556201291e4a345d353a06d08d5d04dd6
=> [GHSA-gq9f-8rj4-w7jc] Moodle CSRF risk in admin preset tool management of presets

advisories/github-reviewed/2024/05/GHSA-68x5-4jg5-gjgg/GHSA-68x5-4jg5-gjgg.json
Updates:
- References
Comments:
https://github.com/moodle/moodle/commit/498a766263743ee649f6874e440a94517a077e2e
=> [GHSA-68x5-4jg5-gjgg] Moodle CSRF risk in analytics management of models

advisories/github-reviewed/2022/05/GHSA-2qm5-r82g-5hcx/GHSA-2qm5-r82g-5hcx.json
Updates:
- References
Comments:
Add 2 patch commits:
https://github.com/zoujingli/ThinkAdmin/commit/b8a2ded90866a285e9022c842e546d8a6fa5fa6d
https://github.com/zoujingli/ThinkAdmin/commit/ff2ab47cfabd4784effbf72a2a386c5d25c43a9a
=> [GHSA-2qm5-r82g-5hcx] ThinkAdmin directory traversal vulnerability

advisories/github-reviewed/2021/08/GHSA-rqgx-hpg4-456r/GHSA-rqgx-hpg4-456r.json
Updates:
- References
Comments:
https://github.com/actix/actix-net/commit/c41b5d8dd4235ccca84d0b687996615c0c64d956
The patch commit [c41b5d8](https://github.com/actix/actix-net/commit/c41b5d8dd4235ccca84d0b687996615c0c64d956) was identified from issue [#91](https://github.com/actix/actix-net/issues/91), where it was referenced as the fix in [this comment](https://github.com/actix/actix-net/issues/91#issuecomment-660659406).
=> [GHSA-rqgx-hpg4-456r] Use-after-free in actix-codec

advisories/github-reviewed/2024/02/GHSA-c85r-fwc7-45vc/GHSA-c85r-fwc7-45vc.json
Updates:
- References
Comments:
https://github.com/rancher/rancher/commit/649fdad268d8ecc748e9fdcca2ddcfdc900f9eaa
=> [GHSA-c85r-fwc7-45vc] Rancher permissions on 'namespaces' in any API group grants 'edit' permissions on namespaces in 'core'

advisories/github-reviewed/2022/05/GHSA-v2rh-5v88-rgvh/GHSA-v2rh-5v88-rgvh.json
**Updates**
* References
**Comments**
* This patch is the same fix on a different branch as the existing patch. They share the same commit msgs. 
* Add a patch commit https://github.com/moodle/moodle/commit/5ee3cbc624c1c4d39adc08c2121a1738d6b5e700 as it is another fix on another branch for the same vulnerability.
=> [GHSA-v2rh-5v88-rgvh] Moodle context freezing 

advisories/github-reviewed/2022/05/GHSA-9rmm-8fp4-26hv/GHSA-9rmm-8fp4-26hv.json
**Updates**
* References
**Comments**
* These patches are all the same fix on different branches as the existing patch. They share the same commit msgs. 
* Add a patch commit https://github.com/phpmyadmin/phpmyadmin/commit/abb3685c8702de887988fee31a97ef4d80d856a1 as it is another fix on another branch for the same vulnerability.
* Add a patch commit https://github.com/phpmyadmin/phpmyadmin/commit/805225a28c1428d7809e613c731c2126960e98df as it is another fix on another branch for the same vulnerability.
=> [GHSA-9rmm-8fp4-26hv] phpMyAdmin Denial Of Service (DOS) attack

advisories/github-reviewed/2021/01/GHSA-hvf8-h2qh-37m9/GHSA-hvf8-h2qh-37m9.json
**Updates**
* References
**Comments**
* These patches are all the same fix on different branches as the existing patch. They share the same commit msgs. 
* Add a patch commit https://github.com/puma/puma/commit/436c71807f00e07070902a03f79fd3e130eb6b18 as it is another fix on another branch for the same vulnerability.
* Add a patch commit https://github.com/puma/puma/commit/fb6ad8f8013ab5cdbb2f444cbfabd0b4fde71139 as it is another fix on another branch for the same vulnerability.
=> [GHSA-hvf8-h2qh-37m9] IPC messages delivered to the wrong frame in Electron

advisories/github-reviewed/2025/04/GHSA-5xm9-x7x4-4j5x/GHSA-5xm9-x7x4-4j5x.json
Updates:
- References
Comments:
Adding a patch commit:
https://github.com/elastic/elasticsearch/commit/097fc0654f9305e01402a06c82926bb04ebe5495
Limits nested depth in Well-KnownText and GeometryCollection parsing to replace StackOverflow with ParseException.
=> [GHSA-5xm9-x7x4-4j5x] Elasticsearch Vulnerable to Stack Overflow due to a Large Recursion

advisories/github-reviewed/2018/09/GHSA-w578-j992-554x/GHSA-w578-j992-554x.json
**Updates**
* References
**Comments**
* These patches are migrated to other branches from the existing patch commit https://github.com/ansible/ansible/commit/ed56f51f185a1ffd7ea57130d260098686fcc7c2. 
* Add a patch commit https://github.com/ansible/ansible/commit/fd30f5328986f9e1da434474481f32bf918a600c migrated to another branch.
* Add a patch commit https://github.com/ansible/ansible/commit/f0e348f5eeb70c1fb3127d90891da43b5c0a9d29 migrated to another branch.
=> [GHSA-w578-j992-554x] Ansible fails to properly mark lookup-plugin results as unsafe

advisories/github-reviewed/2019/12/GHSA-qhrx-hcm6-pmrw/GHSA-qhrx-hcm6-pmrw.json
**Updates**
* References
**Comments**
* These patches are migrated to other branches from the existing patch commit https://github.com/cakephp/cakephp/commit/1a74e798309192a9895c9cedabd714ceee345f4e. 
* Add a patch commit https://github.com/cakephp/cakephp/commit/81412fbe2cb88a304dbeeece1955bc0aec98edb1 migrated to another branch.
* Add a patch commit https://github.com/cakephp/cakephp/commit/c25b91bf7c72db43c01b47a634fd02112ff9f1cd migrated to another branch.
=> [GHSA-qhrx-hcm6-pmrw] Unsafe deserialization in SmtpTransport in CakePHP

advisories/github-reviewed/2021/05/GHSA-c52f-pq47-2r9j/GHSA-c52f-pq47-2r9j.json
**Updates**
* References
**Comments**
* These patches are migrated to other branches from the existing patch commit https://github.com/helm/helm/commit/d9ef5ce8bad512e325390c0011be1244b8380e4b. 
* Add a patch commit https://github.com/helm/helm/commit/f2ede29480b507b7d8bb152dd8b6b86248b00658 migrated to another branch.
* Add a patch commit https://github.com/helm/helm/commit/b0296c0522e837d65f944beefa3fb64fd08ac304 migrated to another branch.
* Add a patch commit https://github.com/helm/helm/commit/c8d6b01d72c9604e43ee70d0d78fadd54c2d8499 migrated to another branch.
* Add a patch commit https://github.com/helm/helm/commit/ac7c07c37d87e09797f714fb57aa5e9cb99d9450 migrated to another branch.
=> [GHSA-c52f-pq47-2r9j] plugin.yaml file allows for duplicate entries in helm

advisories/github-reviewed/2022/02/GHSA-j4f2-536g-r55m/GHSA-j4f2-536g-r55m.json
**Updates**
* References
**Comments**
* This patch is migrated to another branch from the existing patch commit https://github.com/socketio/engine.io/commit/734f9d1268840722c41219e69eb58318e0b2ac6b. 
* Add a patch commit https://github.com/socketio/engine.io/commit/58e274c437e9cbcf69fd913c813aad8fbd253703 migrated to another branch.
=> [GHSA-j4f2-536g-r55m] Resource exhaustion in engine.io

advisories/github-reviewed/2021/05/GHSA-7chv-rrw6-w6fc/GHSA-7chv-rrw6-w6fc.json
**Updates**
* References
**Comments**
* This patch is migrated to another branch from the existing patch commit https://github.com/x-stream/xstream/commit/24fac82191292c6ae25f94508d28b9823f83624f. 
* Add a patch commit https://github.com/x-stream/xstream/commit/f0c4a8d861b68ffc3119cfbbbd632deee624e227 migrated to another branch.
=> [GHSA-7chv-rrw6-w6fc] XStream is vulnerable to a Remote Command Execution attack

advisories/github-reviewed/2025/04/GHSA-887c-mr87-cxwp/GHSA-887c-mr87-cxwp.json
**Updates**
- CVSS v3
**Comments**
GHSA-887c-mr87-cxwp, since the fix exists but has not yet been incorporated into a tagged release, the vulnerable version range was set to <= 2.7.0, when this was the latest release, with no patched version specified. The same behavior was observed since the release of v2.7.1, for which the advisory entry should be readjusted to <= 2.7.1, since this latest release does not include the fix yet.
=> [GHSA-887c-mr87-cxwp] PyTorch Improper Resource Shutdown or Release vulnerability

advisories/github-reviewed/2025/07/GHSA-2gxp-6r36-m97r/GHSA-2gxp-6r36-m97r.json
Corrected severity on advisory so that is it consistent with CVSS 3.1 score and [CVE record](https://www.cve.org/CVERecord?id=CVE-2025-53528)
Additionally, I would like to point out that the description on the CVE record mentions that the patched version is 5.4.4 when the bug is actually fixed in version 5.4.3 as can be verified below:
- https://github.com/zmievsa/cadwyn/blob/5.4.3/CHANGELOG.md#fixed
- https://github.com/zmievsa/cadwyn/blob/5.4.3/cadwyn/applications.py#L393
=> [GHSA-2gxp-6r36-m97r] Corrected severity on advisory

advisories/github-reviewed/2024/09/GHSA-jg74-mwgw-v6x3/GHSA-jg74-mwgw-v6x3.json
This was not assigned a separate CVE as HashiCorp unilaterally disclosed this without referencing the project. This has been remediated for a while.
See also: https://openbao.org/docs/release-notes/2-0-0/#202
See also: https://github.com/openbao/openbao/pull/561
See also: https://github.com/openbao/openbao/commit/d5b4e922469830ac335b21dc0e8f9878c501a884
=> Note remediation for GHSA-jg74-mwgw-v6x3

advisories/github-reviewed/2025/08/GHSA-67mf-3cr5-8w23/GHSA-67mf-3cr5-8w23.json
Update version ranges as per updated https://github.com/bcgit/bc-java/wiki/CVE%E2%80%902025%E2%80%908885
1.0.2.6 & 2.0.1 are fixed versions.
1.0.2.5 & 2.0.0 are vulnerable.
=> Improve GHSA-67mf-3cr5-8w23

advisories/github-reviewed/2025/08/GHSA-g5qg-72qw-gw5v/GHSA-g5qg-72qw-gw5v.json
Fixes the issue where security vulnerability is incorrectly applied to projects that depend on the v0.4 version of `next` which is a totally different product than one started at v0.9.9.
It was already discussed before, see #179 for context
This problem was already fixed for some previous vulnerabilities of `next`, but constantly gets back, when new vulnerability is introduced
Note: I wasn't able to introduce this change via suggest form as it exposes just "Affected versions" field, which logically would have to be `>=0.9.9, < 14.2.31` but that value is not accepted (Looks as another bug worth reporting)
=> Update introduced version in GHSA advisory (CVE-2025-57752)

advisories/github-reviewed/2025/07/GHSA-c2fv-2fmj-9xrx/GHSA-c2fv-2fmj-9xrx.json
=> Add credits section to GHSA-c2fv-2fmj-9xrx.json

advisories/github-reviewed/2023/09/GHSA-6f9p-g466-f8v8/GHSA-6f9p-g466-f8v8.json
=> Add credits section to GHSA-6f9p-g466-f8v8.json

advisories/github-reviewed/2023/05/GHSA-vcxh-qvgr-9fw9/GHSA-vcxh-qvgr-9fw9.json
=> Add credits section to GHSA-vcxh-qvgr-9fw9.json

advisories/github-reviewed/2025/09/GHSA-9c4g-fp4r-prrv/GHSA-9c4g-fp4r-prrv.json
=> Add credits for vulnerability finder
